### ISSUE TITLE
Enable batch send on BIP49

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#1007]
quite easy, make bip49 class return true in allowBatchSend method and test it properly

**Comment by limpbrains** [comment]
@Overtorment 

Let's enable allowBatchSend for all the wallets. What kind of tests do you want? I've looked through all the wallets and all for them using the same `coinselect` func.

Can't find any unit tests for this feature. Only in e2e tests it is covered more or less. 

I suggest we remove `allowBatchSend` completely, allow it in all wallets, add a couple integration tests for main wallet types

**Comment by Overtorment** [comment]
good thinking.
no tests necessary. maybe do some manual testing for some weird wallet, like, legacy single-address, and that's it.
this ticket was created when we had createTransaction method way more inconsistent across wallet  types, and now everything works through same method, via same coinselect.

lets remove `allowBatchSend`.
and looks like we can remove `allowSendMax` as well..?
