### ISSUE TITLE
Negative value on fee calculation

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#1034]
wallet type p2sh, confirmation screen

![photo_2020-04-29_19-35-54](https://user-images.githubusercontent.com/1238429/80627767-b102f800-8a50-11ea-8a85-0e9cbc2f165d.jpg)

**Comment by Overtorment** [comment]
hopefully with latest send functionality refactor this shall  be fixed

**Comment by ncoelho** [comment]
Closing for now, haven't reappeared so far.
