### ISSUE TITLE
Encrypt - Plausible deniability deleted/lost my wallets

### ISSUE THREAD

**Issue by neoacevedo** [BlueWallet/BlueWallet#1039]
I don't know if is an error by myself or is actually some with the Android app.

I had a LN wallet, with a few sats, and a BTC wallet, without anything. When I turned on the storage protection with a password, I still was able to see my wallets, but, when I configured the Plausible deniability, I lost both wallets.

**Comment by ncoelho** [comment]
The plausible deniability brings you to a new storage with no wallets. That's why it is "plausible deniable". To go back to your main storage you need to kill the app, open again, and then insert your main storage password.

**Comment by neoacevedo** [comment]
@ncoelho I did it but I can't get back my previous wallets. I disabled too, the password.

**Comment by ncoelho** [comment]
If you disable the plausible deniability while on other storage you will "destroy" all the other storages.

**Comment by neoacevedo** [comment]
I disabled it after kill the app open again and type the password, because I couldn't get back my previous wallets.

**Comment by neoacevedo** [comment]
Another thing, I tried to recover the wallets via "Import", but the mnemotecnic never worked.
