### ISSUE TITLE
app headers

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#104]
Improve app headers across app

1- Big iOS header style
2- Normal Header navigation center aligned

![navigation bar large title - 1 action on white](https://user-images.githubusercontent.com/1238429/47258601-d13a1a00-d49d-11e8-8e85-cba2b90a84eb.png)
![navigation bar](https://user-images.githubusercontent.com/1238429/47258602-d13a1a00-d49d-11e8-8dd9-93c4512f262d.png)

**Comment by marcosrdz** [comment]
Implemented in 
https://github.com/BlueWallet/BlueWallet/pull/111
