### ISSUE TITLE
Feature: Import wallet from XPRIV

### ISSUE THREAD

**Issue by Transisto** [BlueWallet/BlueWallet#1042]
XPUB works, Seems like it could be useful.

**Comment by Overtorment** [comment]
Why did you close it?
We can keep it open and eventually will be implemented

**Comment by Transisto** [comment]
I just realised it was a harder task than expected. With an UI to enter the
addresses types, and derivation paths.

But for now it should detect when xpriv... are scanned and respond with
something meaningful.
