### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by talibamba** [BlueWallet/BlueWallet#1043]
Hello all !

Since a few days, BW crash on start. I can just see a white screen during 1-2 sec, and go back to home screen. 
Iphone 6s. Last updates ios and BW are made.

I haven’t bakup my QR code, so i can’t try to delete and reinstall the app.. :(

What can i do ?
Thanks !

**Comment by ncoelho** [comment]
What is your OS version?

**Comment by talibamba** [comment]
Hello, my ios version is 13.4.1

**Comment by Overtorment** [comment]
Electrum code was refactored in https://github.com/BlueWallet/BlueWallet/pull/1223 and will be out in next release, hopefully this issue will be fixed
