### ISSUE TITLE
Coin control (Benchmark)

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#1049]
This issue is a benchmark dump of different Coin control (UTXO management) implementations in user facing wallets.

**Bitbox**
![bitbox](https://user-images.githubusercontent.com/1238429/80981086-c057bc00-8e29-11ea-9d4f-754600d822e2.png)

Wasabi
![wasabi](https://user-images.githubusercontent.com/1238429/80981301-14fb3700-8e2a-11ea-997e-3b26d41bdf60.png)

**Bitcoin Core**
![](https://cryptomining-blog.com/wp-content/uploads/2016/04/coin-control-feature2-580x367.jpg)

**Electrum**
![electrum](https://user-images.githubusercontent.com/1238429/80983794-46293680-8e2d-11ea-9391-3397193100b9.png)

**Samourai**
![samourai](https://user-images.githubusercontent.com/1238429/80982519-ba62da80-8e2b-11ea-8bee-63424d3bb89e.png)

**Casa**
![casa](https://user-images.githubusercontent.com/1238429/80983209-a075c780-8e2c-11ea-878f-5056f1cfd085.png)

**Comment by ncoelho** [comment]
### Features map

feature/wallet | electrum | wasabi | bitbox | samourai | casa | core
------------ | ------------- | ------------- | ------------- | ------------- | ------------- | -------------
Big picture | X | | | | | |
Label | X | X | | | | X |
Output | X | | X | | | |
Address | X | |X | X | X | X |
Amount | X | X | | X | | |
Spend | X | X | X | X | X | X |
Don't spend | X | X | | X | | |
More Details | X | | | | | X |
Change Options | X | X | | | | X |

**Comment by MaxHillebrand** [comment]
Very good that you are thinking on how to get coin control into the wallet - it's a major privacy improvement, although might be a UX hurdle. 

Good comparison between the different UX models too!

FYI, when you double click on any coin [or tx] in Wasabi, there will be a dedicated Details tab, and this will show the address, tx id and index, etc. 

![screenshot_20200511_133027](https://user-images.githubusercontent.com/30683012/81557164-cef32580-938b-11ea-98d7-606e6ba95f8b.png)

I believe that coin control is only really useful when you have a good address / transaction labeling system. I know that You have the `note to self` in the send field, so you might be able to use this info for the UX.

**Comment by ncoelho** [comment]
Updated the wasabi info on the table, thanks.

Nice idea to use that field to start labelling UTXOs right away, wasn't thinking about that, but it does sound like a good approach

**Comment by ncoelho** [comment]
Adding a first idea. To be discussed and analyzed. 

Twitter comments
https://twitter.com/nvcoelho/status/1258716253029650435 

<img width="754" alt="Screenshot 2020-05-14 at 18 08 10" src="https://user-images.githubusercontent.com/1238429/81958182-e5101880-960d-11ea-89b9-eed56a3b3b15.png">

**Comment by Overtorment** [comment]
I think color coding should be used for amounts. the largest amount is dark red, for example, and the smallest is light green.

**Comment by GBKS** [comment]
I am not convinced about the functional aspect of the colored circles yet. Visually they are pleasant, but they should also make it easier for users to pick the right coins in some manner. Tinting by amount is easy to understand. Tinting by somehow deriving a colorful from the transaction hash is possible to understand rationally, but not intuitively and also not really helpful to the task at hand. Why not remove them and make more room for tags? That's where the information is that helps me make good decisions, and they could be color-coded, too.

**Comment by ncoelho** [comment]
yep, me neither, working on more concepts, feel free to suggest more as well. I am even not sure, if manual utxo selection is something the users should be doing, the algorithm will definitely do a better job if properly tagged or labelled by the user, maybe that's enough. 

Personally I'm only interested in defined the do not spends (app should be clever enough to do the rest) and in the future consolidate the UTXOs. This will be something necessary, that will break users privacy for instance... So, a lot to improve over time once we have something usable.

Anyway the feedback from users on the concept was very good. So let's see as it goes.

**Comment by ncoelho** [comment]
For anyone landing here, there's feedback on the figma file
https://www.figma.com/file/mPoRMRTBOvi61M8psIp4XY/Coin-Control?node-id=0%3A1
