### ISSUE TITLE
Fix App Store icon white spacing

### ISSUE THREAD

**Issue by kolya182** [BlueWallet/BlueWallet#1050]
Device: iPhone Se 1st gen
![IMAGE 2020-05-04 22:05:08](https://user-images.githubusercontent.com/3277207/81036270-518f5880-8e53-11ea-93f7-559570d98099.jpg)

**Comment by ncoelho** [comment]
Embarrassing! Fixed https://github.com/BlueWallet/BlueWallet/pull/1052
