### ISSUE TITLE
Prices is to damn high

### ISSUE THREAD

**Issue by kolya182** [BlueWallet/BlueWallet#1051]
Current price at CMC:`$9049`, app price for buying 26$ BTC is `$9325`. Is this normal ?

**Comment by ncoelho** [comment]
The prices depend on the partners we are integrating with and country. Which service you saw this? It does seem a big of a premium though :/

**Comment by kolya182** [comment]
It was 🌚 pay. Ok, seem like huge premium. Can you negotiate with them lower prices, otehrway closing this.
