### ISSUE TITLE
Add bluewallet: URL Scheme

### ISSUE THREAD

**Issue by jackeveritt** [BlueWallet/BlueWallet#1061]
This is mainly for iOS.  If a user has two wallets installed, then an app opening an invoice or lnurl via 'lightning:' url scheme will only be able to open the previous wallet that was installed.  The user cannot decide which wallet app to open, as they can on Android.

To give them a choice a 3rd party app that wants to open Blue Wallet will need to check if a custom url scheme such as bluewallet: exists.

**Comment by ncoelho** [comment]
implemented, see https://github.com/BlueWallet/BlueWallet/wiki/Deeplinking
