### ISSUE TITLE
Use notifications to have realtime updates

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#1069]
Notifications should allow the app to have realtime updates, use the payload to populate the data.

**Comment by jaonoctus** [comment]
By the way, before the user enable notifications shouldn't it explicitly warn that the addresses will be stored in an external database?

**Comment by ncoelho** [comment]
I don't think it is needed, the entire wallet works based on that principle, it is not something just exclusive to the notifications.
