### ISSUE TITLE
Importing electrum segwit wallet seed

### ISSUE THREAD

**Issue by JijoBose** [BlueWallet/BlueWallet#1070]
Electrum wallet segwit wallet seed

BlueWallet App version: 5.3.5 - Android

#### Steps to replicate
- Create a wallet from electrum desktop with seed type: "segwit"
- import the 12-word seed to bluewallet

#### Error:
"Failed to import. Please, make sure that the provided data is valid"

**Comment by ncoelho** [comment]
I believe this is available on 3.5.6, it will be out in a couple of days
