### ISSUE TITLE
Wrong value on success screen

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#1078]
This is the same transaction:
- the success screen on the tx creation flow shows a wrong value
- the correct screen is the detail tx screen on tapping from the list

<img width="310" alt="Screenshot 2020-05-15 at 10 49 20" src="https://user-images.githubusercontent.com/1238429/82031574-61503d80-969a-11ea-9187-a5f421edd16f.png">
<img width="311" alt="Screenshot 2020-05-15 at 10 49 00" src="https://user-images.githubusercontent.com/1238429/82031577-62816a80-969a-11ea-9538-4fae524f7a91.png">

**Comment by Overtorment** [comment]
duplicate https://github.com/BlueWallet/BlueWallet/issues/1072
