### ISSUE TITLE
Feature request: Auto logout iOS

### ISSUE THREAD

**Issue by Smiggel** [BlueWallet/BlueWallet#1089]
I have been playing around with the wallet and noticed that the wallet does not auto logout when you don't use it for while. To me that seems like a big security risk.

I would like to see an option to enable auto logout so, that you actually have to login when you active the app when it's in the background.

Tested this on iOS 13.5.

**Comment by ncoelho** [comment]
hi @Smiggel was it you that I replied to this on reddit? Let me know. Thanks

**Comment by Smiggel** [comment]
That was me indeed.

**Comment by ncoelho** [comment]
Ok, closing this issue then. Thanks!
