### ISSUE TITLE
TypeError: TypeError: TypeError: TypeError: undefined is not an object (evaluating 'this.state.tx.inputs.length')

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#109]
TypeError: TypeError: TypeError: TypeError: undefined is not an object (evaluating 'this.state.tx.inputs.length')

This error is located at:
    in TransactionsDetails
    in SceneView
    in RCTView
    in View
    in RCTView
    in View
    in RCTView
    in View
    in AnimatedComponent
    in Screen
    in Card
    in Container
    in RCTView
    in View
    in ScreenContainer
    in RCTView
    in View
    in StackViewLayout
    in withOrientation
    in RCTView
    in View
    in Transitioner
    in StackView
    in Navigator
    in KeyboardAwareNavigator
    in NavigationContainer
    in SceneView
    in RCTView
    in View
    in AnimatedComponent
    in RCTView
    in View
    in DrawerLayout
    in DrawerView
    in Navigator
    in NavigationContainer
    in RCTView
    in View
    in AwakeInDevApp
    in ExpoRootComponent
    in RCTView
    in View
    in RCTView
    in View
    in AppContainer

This error is located at:
    in NavigationContainer
    in SceneView
    in RCTView
    in View
    in AnimatedComponent
    in RCTView
    in View
    in DrawerLayout
    in DrawerView
    in Navigator
    in NavigationContainer
    in RCTView
    in View
    in AwakeInDevApp
    in ExpoRootComponent
    in RCTView
    in View
    in RCTView
    in View
    in AppContainer

This error is located at:
    in NavigationContainer
    in RCTView
    in View
    in AwakeInDevApp
    in ExpoRootComponent
    in RCTView
    in View
    in RCTView
    in View
    in AppContainer
  at workInProgress (/Users/admin/bluewalletsecure/screen/transactions/details.js:143:14)
...
(10 additional frame(s) were not displayed)

**Comment by Overtorment** [comment]
@marcosrdz I think you had it on your devce, can u reproduce and fix?

**Comment by marcosrdz** [comment]
Fixed 178c9a8457a49e404c632b68ec9ad549d7909ab5
