### ISSUE TITLE
Bug: TouchID switch never turns on

### ISSUE THREAD

**Issue by Smiggel** [BlueWallet/BlueWallet#1090]
So, I have enabled TouchID on my iPhone using iOS 13.5. However, I could not see it was actually on, because the switch never flips to the enable/on state. It stays of. I tried many time. After closing the app and opening it, I noticed it was actually turned on. Looking at the setting, the switch still says it's off.

So in the end you can turn in on, but also never turn it off.

**Comment by marcosrdz** [comment]
Would you mind providing a screen recording of this?

**Comment by Smiggel** [comment]
Of course. See the Dropbox url: https://www.dropbox.com/s/v4lrkgto31ee2t1/Video%2018-05-2020%2007%2013%2041.mov?dl=0

**Comment by marcosrdz** [comment]
thank you! I believe we currently have this fixed on master. We are getting ready to make a new release which will include the fix for this.

**Comment by P-Verbrugge** [comment]
Cool. Looking forward to the new release. :-)

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/commit/5807efdb6d76517aea980a84364aa79cd091e92e
