### ISSUE TITLE
Not verifiable status on WalletScrutiny.com

### ISSUE THREAD

**Issue by maltokyo** [BlueWallet/BlueWallet#1096]
Please take a look at the apparent non verifiable nature of bluewallet reported on https://walletscrutiny.com/

It's a concerning "review" for Bluewallet. Is there any feedback from developers to rectify this or otherwise prove the Wallet Scrutiny report wrong?

**Comment by ncoelho** [comment]
There’s an issue open with an effort ongoing to make the build verifiable,
which you can built it and verify it yourself.

Personally, I found the approach this project takes very dishonest and
misguided.
- there are listed projects not foss as verifiable, which is not true
- the effort to verify bluewallet was null to say the least

I suggest that you verify it yourself and don’t trust unreliable 3rd
parties to do so.

**Comment by maltokyo** [comment]
Thank you Nuno for your reply. I've been following bluewallet and a user for quite some time! I appreciate your work. I'm just pointing out a source of negative attention that you guys may want to address (directly to them?). That site gets quite some attention now on twitter. 

(Which one is not Foss in their verifiable list btw?)

**Comment by ncoelho** [comment]
The site is created by the lead developer of mycelium (there's a small conflict of interest here...) which does not have open source its backend and does not provide a FOSS license.

**Comment by maltokyo** [comment]
Thanks. I didn't realise this!

**Comment by maltokyo** [comment]
Sorry. But this is them no?

https://github.com/mycelium-com/wallet-android

**Comment by ncoelho** [comment]
> Sorry. But this is them no? https://github.com/mycelium-com/wallet-android

Yes. no backup, no open source license.

**Comment by ncoelho** [comment]
Closing this issue. Cheers!
