### ISSUE TITLE
Feature request: display currency and btc value

### ISSUE THREAD

**Issue by Smiggel** [BlueWallet/BlueWallet#1107]
Hi,

I would like to suggest a feature in the wallet that I am missing currently. I would like the wallets to be able to show the value in currency and btc at the same time. Like Green wallet is doing. It would be a nice feature to have that, next to the options that are available already.

![image](https://user-images.githubusercontent.com/1825953/82550242-7f1c1780-9b5e-11ea-8815-8ea71578e35a.png)

It would give a better overview from what is stored in the wallet.

**Comment by ncoelho** [comment]
At the moment what is there is the ability to change denomination when you tap the balance inside the wallet.

**Comment by Smiggel** [comment]
I know. But there is no option to display both at the same time. In my opinion it’s too much of a hassle to have to open a wallet and tap to switch. I there would like the option as a choice to have my suggestion added to the options.

**Comment by Overtorment** [comment]
id say its doable. one of the options when you tap through all possible denominations could be smth like btc_and_fiat where for all values like in transactions it acts as btc, but for wallet card it signals that fiat value should be rendered as well
@marcosrdz thoughts?

**Comment by marcosrdz** [comment]
Yup. Can be done
