### ISSUE TITLE
UX for Swiping between wallets

### ISSUE THREAD

**Issue by JijoBose** [BlueWallet/BlueWallet#1112]
After the latest update in the play store, swiping or scrolling between wallets UX is not good.
It opens the first wallet while swiping right or left.
Issue: Android

**Comment by ncoelho** [comment]
Thanks! It was changed to render faster on the app starts, we will check for this error.

cc @marcosrdz

**Comment by marcosrdz** [comment]
This was a bug when using ViewPager. It has been removed and will not occur in the next release.
