### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by limpbrains** [BlueWallet/BlueWallet#1124]
I want to improve localization of the project

Things want to fix besides missing translations in components:
#### Can't export language file

Bitcoin-core uses [transifex](https://www.transifex.com/bitcoin/bitcoin/), they are free for open source projects. If we store all stings in JSON, we will be able to use it. I believe this will make updates of language files much easier.

#### Do not compose strings
Different languages have different word order, things like
```
loc.wallets.details.delete + ' ' + loc.wallets.details.title
```
will not work for all of them. Also, you can't translate this by looking at en.js, you need also understand source code where these strings are used. It is better to have separated 

#### Plurals
0 confirmations

1 confirmation

2 confirmations

react-localization doesn't have plurals support

I have nice experience with [react-i18next](https://github.com/i18next/react-i18next), I would like to use it. It works fine with react-native, stores vocabulary in JSON. It also has nice `<Trans>` component with allows you to rearrange component depending on language. https://react.i18next.com/latest/trans-component. Also changing language will not require app relaunching.

But this will require wrapping components with `withTrans` HOC and use injected `t` function.

How do you think, should I create pull request to replace react-localization with react-i18next or just stick with the first one ? Anything else to look at?

**Comment by Overtorment** [comment]
Id say that, for now, it's too much work to do this change to localizations, and we have more important housekeeping to do (like, upgrading react navigation - that would be totally awesome! or upgrading RN itself), but yeah, `react-i18next` looks superior. but isn't it too enterprisey? I've seen only big companies worry about plurals etc etc. is it a good choice for small projects?

@marcosrdz thoughts on this all?

**Comment by limpbrains** [comment]
I don't feel `react-i18next` too enterprisy. Actually it's quite small - only one dependency besides babel. i18next itself big, because they have libs for a lot of languages

**Comment by Overtorment** [comment]
I feel that now is not a good time to spend efforts on localization. we haven't really outgrown current implementation yet.
 there are probably more exciting features on roadmap.

**Comment by limpbrains** [comment]
Ok, maybe later
