### ISSUE TITLE
Remove dep `node-libs-react-native`

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#1144]
cant remember why we have it. looks like its not used

**Comment by arizala13** [comment]
I tried removing it and it had an error on the build. It stated "Task :app:bundleReleaseJsAndAssets FAILED". I am not exactly sure why. 

The exact info can be found here: https://travis-ci.com/github/BlueWallet/BlueWallet/builds/169306560

**Comment by Overtorment** [comment]
negative result is also a result. thanks. means that its probably used somehow, not in an obvious way.
can be postponed

**Comment by Overtorment** [comment]
managed to fix it 
https://github.com/BlueWallet/BlueWallet/pull/1204
