### ISSUE TITLE
BlueWallet secretly charges fees without ever telling the user

### ISSUE THREAD

**Issue by viaj3ro** [BlueWallet/BlueWallet#1183]
This was reported to the team a long time ago but never got fixed.

**Comment by ncoelho** [comment]
Any suggestion on how to better do this?

**Comment by viaj3ro** [comment]
It should show up on the send screen that appears after you scan a QR code. Besides the amount that is send in sats and $ it should show the fee in sats and $ as well

**Comment by ncoelho** [comment]
The problem is that we don't really know the fee upfront. We can add the percentages, but these have too many rules and exceptions to be accurate :/ not easy, let me think of something

**Comment by limpbrains** [comment]
I think percentage interval would be fine until there is a better way.

**Comment by viaj3ro** [comment]
I think you only charge for larger payments. what other rules and exceptions exist? Maybe it makes sense to simplify?!

**Comment by ncoelho** [comment]
Added some of the hardcoded rules. We gonna try to make it more dynamic based on the info we have, that is the invoice amount. This is a "hotfix" for now to be release on the next update, probably in 2 weeks.

Thanks for brining this to our attention again.

https://github.com/BlueWallet/BlueWallet/pull/1186
