### ISSUE TITLE
Struggling to import Bech32 wallet

### ISSUE THREAD

**Issue by KayBeSee** [BlueWallet/BlueWallet#1197]
I am trying to import a Bech32 wallet but am really struggling. 

I DM'd BlueWallet on Twitter and they said that it might be because there are no transactions to the Bech32 addresses, so I sent a transaction and tried again but it still is only importing the P2SH wallet.

I can import a zpub and have a watch only wallet that is displaying the transaction history but when I use the seed to create a WIF to import a wallet with sending capabilities it is importing it as a regular P2SH wallet and not displaying any of the transactions.

The code I am using (taking the values from console.log and inputting them to the import box).

```
   const mnemonicWords = generateMnemonic(256);
    // taken from BlueWallet so you can import and use on mobile
    const seed = await mnemonicToSeed(mnemonicWords);
    const root = bip32.fromSeed(seed, 'mainnet');
    const xprvString = root.toBase58();
    console.log('xprvString: ', xprvString);

    const path = "m/84'/0'/0'";
    const child = root.derivePath(path).neutered();
    const xpubString = child.toBase58();
    console.log('xpubString: ', xpubString);

    // bitcoinjs does not support zpub yet, so we just convert it from xpub
    let data = b58.decode(xpubString);
    data = data.slice(4);
    data = Buffer.concat([Buffer.from('04b24746', 'hex'), data]);
    const zpubString = b58.encode(data);
    console.log('zpubString: ', zpubString);

    const node = bip32.fromBase58(xprvString, 'mainnet');
    const wifFrom = node.toWIF();
    console.log('wif: ', wif);

    const wifFromSeed = bip32.fromSeed(seed, currentBitcoinNetwork).toWIF();
    console.log('wifFromSeed: ', wifFromSeed);
```

The xpub will import a watch-only that isn't bech32 and the wifs are importing sendable wallets but in P2SH.

I looked at the code for importing and I'm wondering if maybe I need to just throw in mnemonicWords straight up?

**Comment by Overtorment** [comment]
Hey, I didnt get what exactly are you trying to do? Are you using the app or trying to hack some code to work?

Also, Bech32 like, single address or whole hierarchy? Where did you get it?


>> I can import a zpub and have a watch only wallet that is displaying the transaction history but when I use the seed to create a WIF

If you have zpub I assume you have mnemonics. In that case, WIF is unrelated. WIF usually represents a single private key which corresponds to a single address, while mnemonics and zpubs usually  represent HD wallets - a whole hierarchy of addresses.  So I'd say, forget about WIF and try to import mnemonics directly.

**Comment by KayBeSee** [comment]
I didn't realize that WIF is for single private keys that correspond to a single address.

I have access to the mnemonic and was able to import the wallet into BlueWallet using that. It even imported into bech32 format even without sending an initial transaction.

Thanks for the help!
