### ISSUE TITLE
Reorder screen drag not working

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#1198]
User is not able to drag the wallets to reorder them.

Reported on twitter
phone: Honor view 20
os: Android 10

**Comment by marcosrdz** [comment]
Seems like it's a known issue with the package used for the reordering UI.

https://github.com/gitim/react-native-sortable-list/issues/188

Will be implementing a work around for Android.

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/1202
