### ISSUE TITLE
Signed PSBT not recognized by OS

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#1201]
Reported on telegram:
https://t.me/bluewallet/22945

Signed PSBT not recognized by OS when importing tx. Wallet imported correctly though.

![IMG_1913](https://user-images.githubusercontent.com/1238429/84147178-3ff62d80-aa5d-11ea-99da-6c29142e30b5.jpg)

**Comment by Overtorment** [comment]
@marcosrdz ^^^

**Comment by marcosrdz** [comment]
More details?

Tried out with my device and it worked.

**Comment by Overtorment** [comment]
![image](https://user-images.githubusercontent.com/1913337/88407607-413fa780-cdca-11ea-9db3-b5f992315c05.png)

Worked well for me

**Comment by Overtorment** [comment]
watchonly wallet -> send -> import tx

tested with both sd card in apple's dongle & icloud
