### ISSUE TITLE
enable hermes for android

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#1205]
hermes was enabled for a little while and was turned off in commit `1b2bf0d59`. 
reason: when enabled some screens were crashing the app, but I suspect that was only because screens were poorly implemented.
after rnav was upgraded it is time to try hermes again. so we need to enable id, and test _all_ app screens whether they are crashing or not, and if they do - maybe they can be easily refactored.

**Comment by marcosrdz** [comment]
Attempted to enable it again. Faced issues, such as blankscreen, and tried reported workarounds. No success :-( . However, it appears that RN 62.2 has this issue fixed:

https://github.com/facebook/react-native/issues/26400#issuecomment-614601502

We are currently using RN 61.5

**Comment by licaon-kter** [comment]
So this is fixed? Ref: https://github.com/BlueWallet/BlueWallet/blob/master/package.json#L111

But not updated: https://github.com/BlueWallet/BlueWallet/blob/master/android/app/build.gradle#L81 ?

**Comment by Overtorment** [comment]
will probably attempt again after RN63 upgrade

**Comment by limpbrains** [comment]
Realm has no Hermes support yet https://github.com/realm/realm-js/issues/2455
