### ISSUE TITLE
Default wallet should provide wrapped segwit addresses

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#1215]
There's a common complain that is mainly related to some big wallets not providing support for native segwit (coinbase/blockchaininfo), which the normal user doesn't really understand why BW doesn't work with them.

There's should be, or an easy way, or an advanced setting (easy way will be ideal) where the user can change to a wrapped segwit address.

One seed + derivation paths (bip84/bip49)

**Comment by Overtorment** [comment]
after some thought, closing this.
native VS wrapped are different BIPs and mixing then under one mnemonic is bad for recoverability and interoperability with other wallets
