### ISSUE TITLE
speed up e2e tests

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#1217]
travis tests are crazy slow. typically 40 min, of which 30 min is setting up the environment with java and compiling production build. also, some tests randomly fail for an unknown reason, and it looks like app just crashes on CI.
it was hard to setup travis, and integration feels hacky as travis was not made to handle android emus.

we need to try out alternatives:

* github actions https://medium.com/@reime005/the-best-ci-cd-for-react-native-with-e2e-support-4860b4aaab29
* bitrise https://github.com/wix/Detox/blob/master/docs/Guide.RunningOnCI.md
* buddy https://buddy.works/docs/quickstart/react-native

**Comment by Overtorment** [comment]
target: 15min

**Comment by limpbrains** [comment]
I will try to port e2e tests on github actions
