### ISSUE TITLE
app is slow when tx count > 700

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#1218]
need to profile it.
@marcosrdz suggests this is because all txs are stored in RAM in runtime (700 txs actually take couple of megabytes when serialized as json, which is not much I'd say), and proposes to switch to dedicated db engine made for RN.

I say we can't tell for sure until we profile and measure.

**Comment by limpbrains** [comment]
On which screen? wallets/transactions ?

**Comment by ncoelho** [comment]
yep transaction.js

**Comment by JijoBose** [comment]
Could you use [realm DB](https://www.npmjs.com/package/realm) for caching the transactions
just a suggestion

**Comment by Overtorment** [comment]
what are the alternatives to realm?

**Comment by JijoBose** [comment]
Alternatives to realm I found that works with React Native are
[WatermelonDB](https://nozbe.github.io/WatermelonDB/ )
and 
[pouchdb](https://pouchdb.com/)

**Comment by JijoBose** [comment]
Let me try to implement this over the weekend and let you know 😃

**Comment by limpbrains** [comment]
I believe this was fixed in #1306
