### ISSUE TITLE
Remove additional styles from SafeBlueArea

### ISSUE THREAD

**Issue by limpbrains** [BlueWallet/BlueWallet#1226]
Almost in every screen there are custom styles applied to `SafeBlueArea` component.

Actually any `style` property will be overwritten by `SafeBlueArea` own styles defined in `BlueComponents.js`

We need to remove all custom styles applied to `SafeBlueArea` and their definitions, make sure that everything is ok

**Comment by phrazzld** [comment]
PR intended to address this issue here:
https://github.com/BlueWallet/BlueWallet/pull/2792

**Comment by phrazzld** [comment]
Fix for this issue has been merged. @limpbrains, good to close this out?
