### ISSUE TITLE
Teach GlaDOS to cleanup his previous comments in PR

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#1228]
`./appcenter-post-build.sh`

**Comment by Overtorment** [comment]
if anyone feels bored and wants to mess with github API a bit

**Comment by limpbrains** [comment]
Probably we can move run Glados as a Github action after appcenter build. Github action can have artifacts. In this case we can avoid Glados posting every success build as a comment

**Comment by Overtorment** [comment]
I personally like GlaDOS comments in main thread. in future we can make it post other useful stuff

**Comment by Overtorment** [comment]
https://github.com/BlueWallet/GlaDOS/commit/0b65661ff84a4563ae69e39749df77f1d42cb2ef
