### ISSUE TITLE
Import bug: WIF compressed private keys (P2PKH) get imported as SegWit (P2SH)

### ISSUE THREAD

**Issue by Tigerix** [BlueWallet/BlueWallet#1242]
Unfortunately importing WIF compressed private keys (e.g. Bitaddress.org) get imported as Segwit (P2SH) wallet.

Private Key WIF Compressed
52 characters base58, starts with a 'K' or 'L'

Example Private Key:
L2wvkfexLysPTF45YaYwKQRiCF574HoTrizqj7bCBHw71Ddw3aoK

**Comment by Overtorment** [comment]
this is a feature, not a buck. or to be more precise, its legacy behaviour from 2years ago when  BW was mostly single-address p2sh segwit wallet.
thing is, WIF was invented pre-segwit and doesn't carry a hint what type of address should be unwrapped from private key. so BW defaults to p2sh because used to be only single-address p2sh segwit wallet. 
today behaviour is a bit more complex,  BW unwraps all possible addresses from WIF and checks balances on all of them, and imports only the one with nonzero balance.
so if you actually have paperwallet from bitaddressorg with some coins, import should work as expected.

**Comment by Tigerix** [comment]
Would it be possible to change the import function in a way that it imports the wallet which has a history even if it has zero balance?

**Comment by Overtorment** [comment]
its possible, yes.

**Comment by MaxSikorski** [comment]
** I am adding to this closed issue, as I've came across this recently **


I tried today to import privkey into "import" section in blue wallet

here's some point from trying to import
- addr was generated on my desktop computer terminal using command "bitcoin-cli getnewaddr" (computer is running full node)
- P2WPKH addr (bc1...)
- i dumped private key from generated addr ( "bitcoin-cli privkeydump")
- privkeydump: starts with "L..."
- when trying to import private key, blue wallet tells me "no UTXO's found..."
- I suspect it is importing P2SH 

Solution (refer back to closed issue: #2505):
- I imported "dumpprivkey" into electrum wallet, using the prefix "p2wpkh:L..." 
- wallet imported successfully

**Comment by Overtorment** [comment]
address had zero transactions? then yes, WIF defaults to wrapped segwit.
prefixes like "p2wpkh:L..." actually a great idea, its been on my mind for a while, just had no time to implement it as its an advanced feature only few users will appreciate

**Comment by MaxSikorski** [comment]
> address had zero transactions? then yes, WIF defaults to wrapped segwit.
> prefixes like "p2wpkh:L..." actually a great idea, its been on my mind for a while, just had no time to implement it as its an advanced feature only few users will appreciate

I'd like to see these prefixes get added to blue wallet. Mind I make a new issue to incentivize others to do so? I'll put some sats for a bounty as well.

**Comment by Overtorment** [comment]
@MaxSikorski go ahead. would be great if you could do some research, maybe there is some kind of a standard, or examples how other wallets achieve similar result.

PS. i recently wrote https://github.com/BlueWallet/BlueWallet/wiki/Supported-wallet-types

**Comment by Overtorment** [comment]
maybe instead of a prefix it should be a dialog box..?

**Comment by ncoelho** [comment]
It should be the derivation path right?

For instance:

If advanced mode is on:
- trigger a dialog box
- "ok" for adding
- "automatic" for letting bluewallet search

![Create wallet](https://user-images.githubusercontent.com/1238429/108858734-c7380100-75ec-11eb-95a7-7ed7e997e6ea.png)

**Comment by Overtorment** [comment]
WIF doesnt need derivation path, only format (legacy/wrapped/native segwit)

**Comment by ncoelho** [comment]
Right. For me the biggest problem is the seeds with accounts inside and multiple derivation paths.
