### ISSUE TITLE
Use NavigationContainer for deep linking

### ISSUE THREAD

**Issue by marcosrdz** [BlueWallet/BlueWallet#1246]
https://reactnavigation.org/docs/deep-linking

**Comment by Overtorment** [comment]
pls add e2e test for basic deeplink as well

**Comment by Overtorment** [comment]
temp fix https://github.com/BlueWallet/BlueWallet/pull/1247

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/1263/files
