### ISSUE TITLE
Implementation of Onion Routing into BlueWallet (.04 btc bounty)

### ISSUE THREAD

**Issue by Sorikal** [BlueWallet/BlueWallet#1253]
### Suggestion

Implementation of Onion Routing into the **BlueWallet** app.

### Benefits

1. Extra layer of anonymity
2. Allowing users from countries like India (where bitcoin is banned) to use the wallet.
3.  Remove the need for users to buy a VPN so they can use the app safely.

### Conclusion

Implementing Onion Routing into the **BlueWallet** app will make the wallet much more safer to use as well as allowing users that live in countries that ban the use of bitcoin to use the app as well.

**Comment by thenewbug** [comment]
I would like to put .04 BTC for bounty to encourage this one. Appreciate it if anyone wants to help me update the label

**Comment by maltokyo** [comment]
@AaronDewes - this bounty is for you no?

**Comment by Overtorment** [comment]
TOR support for lndhub coming in this PR: https://github.com/BlueWallet/BlueWallet/pull/2295
TOR support for electrum connection is not ready yet, but the author or `react-native-tor` (@gabidi) is working on it. 
IMO he should claim the bounty when it's delivered.

**Comment by godSaysHODL** [comment]
> IMO he should claim the bounty when it's delivered.
Awesome! Excited to pay this one out!

HUGE. 

Does he have a twitter?

**Comment by Overtorment** [comment]
> > IMO he should claim the bounty when it's delivered.
> 
> Awesome! Excited to pay this one out!
> 
> HUGE.
> 
> Does he have a twitter?

this one probably https://twitter.com/SifirApps

**Comment by godSaysHODL** [comment]
@Overtorment any other big contributors on this one, including you? Will send some secondary tips to the bounty
