### ISSUE TITLE
Opening LNURL via Lightning: will ignore LNURL if invoked when the BW is closed

### ISSUE THREAD

**Issue by jackeveritt** [BlueWallet/BlueWallet#1257]
If BW has been closed in the background by the OS and another app uses lightning:LNURL to open BW; the LNURL gets lost once the app opens and initialises. The LNURL is ignored.

If you try the LNURL again it will work because BW is now running (in the background)

**Comment by Overtorment** [comment]
I believe that was fixed in https://github.com/BlueWallet/BlueWallet/pull/1247
release is pending, should be out nearest days.
lmk if that fixes issue for you
