### ISSUE TITLE
Question: Is Bluewallet Native Segwit BIP84 address using always BIP39 Mnemonic?

### ISSUE THREAD

**Issue by maltokyo** [BlueWallet/BlueWallet#1259]
Hi @ncoelho and team

I introduced a friend to bitcoin, and advised he gets bluewallet.  He bought a small amount of BTC and send to his bc1 address on bluewallet, and all went well.

He subsequently deleted his app, and tried to restore from Mnemonic, and seems there was some error in what he wrote on paper, because it is not restoring for him.. and gives zero balance.

Its only about 200EUR but I want to help him recover.

What I know is:
1. His 24 word mnemonic (likely with some error..)
2. The address he sent BTC to - it is: https://blockstream.info/address/bc1qc40vydt9ytkde5h76t75gjdpd5vd7c9w4e6d3q

I would like to use some of the tools here: https://github.com/3rdIteration to help him recover.  Thank you @3rdIteration for this!

My ask: is Bluewallet always using a BIP39 Mnemonic?  When I enter into an offline version of this tool: https://github.com/3rdIteration/mnemonic-recovery , it tells me that his mnemonic is not valid.  So I am wondering is that his issue, or is it not BIP39 after all?  Thanks!

**Comment by 3rdIteration** [comment]
Bluewallet follows BIP39 conventions and will default to the BIP84 derivation path. It's covered here: https://walletsrecovery.org/

If it isn't a huge amount, your best bet is to just use it with BTCRecover (https://github.com/3rdIteration/btcrecover/) and not really worry about being airgapped. (Assuming you then move to a new seed after you are done) You can use the defaults for seedrecover.py and it will probably find it within a few minutes. If it doesn't, running BTCRecover searching for 2 "big typos" and an address generation limit of something like 10 will almost certainly find it.

**Comment by maltokyo** [comment]
Many thanks @3rdIteration , will give it a try!  Though from here, it doesn't look like it uses BIP39, at least according to this guide, it is not checking the BIP39 checkbox...

http://help.bluewallet.io/en/articles/2847190-how-to-backup-export-and-import-your-wallet

The other issue is that when I type the seed into mnemonic-recovery (as above) it says the full 24-word seed is completely "invalid".. I thought this would mean it is not BIP39, even if one word is wrong?

**Comment by Overtorment** [comment]
default *onchain* wallets are definitely BIP39 (unless you enabled advanced mode and created single-address wallet, in that case wallet backup would be a WIF). 

sounds like a typo in one of the words. luckily mnemonic words were selected to be very distinctive, so it is easy to find which word is not right and fix it. a variety of tools can do that.

also, some people very rarely when writing down words, might write them down *as columns*, not as *rows*, so they are in incorrect order. old BW versions displayed mnemonics that way that it is not obvious. if that's the case then you just need to rearrange them

**Comment by Overtorment** [comment]
last word in mnemnics is always a checksum, so if it isn't matching then something is wrong with words and any wallet app will say that it is invalid

**Comment by maltokyo** [comment]
Thank you!  Interestingly electrum accepts his words as BIP39, and so does Bluewallet.  But it creates a new wallet with zero balance.  But the tool above linked, says the words are invalid. What is being checked differently I wonder?

**Comment by 3rdIteration** [comment]
For a 24 word seed, the likely hood of the seed phrase having an error while still producing a valid checksum is quite low. (Unlike with 12 word seeds) 

The main thing to check in Electrum is that you are using the right account type, have you checked with all three account types? Also, are you seeing any transactions at all in Electrum, or no balances or transactions.

**Comment by Overtorment** [comment]
Also, I see your address is bech32 and it **has** coins. So it’s a BIP84 type wallet

**Comment by maltokyo** [comment]
Indeed, it is definitely BIP84 address, this I am confident.  I just wasn't sure about BIP39 or how to test for that.  I guess it is, and there is just a wrong word.  Checks with btcrecover are ongoing...

**Comment by maltokyo** [comment]
UPDATE: mystery solved!!  there was one word incorrect in the seed.  Instead of "clay" he wrote "day" ;)  Many thanks to @3rdIteration and your tools.  I will insist / ask that he donates 10% of that to you.  As he had considered it lost!

**Comment by 3rdIteration** [comment]
Well done for holding your nerve and getting it sorted :)

You are the 1/256 unlucky enough to have a mistake that still checksummed ok for a 24 word seed ;)

If you just ran to tool on your normal desktop environment, my suggestion is that you move to a new seed. (Though it would have thrown that warning at you plenty of times while using it)

**Comment by maltokyo** [comment]
Indeed. But your tool sorted it in a few seconds. Great stuff. He is over the moon and will send you some of it. Thanks again!

**Comment by junderw** [comment]
yeah... every time I write down phrases I try to write extremely carefully, letter by letter, and leave plenty of space between letters... clay and day is a great example of why someone with slightly dirty handwriting can cause themselves a lot of pain...
