### ISSUE TITLE
Consider using `patch-package` instead of hand made patches

### ISSUE THREAD

**Issue by rikur** [BlueWallet/BlueWallet#1265]
I've enjoyed using it personally: warns you when you upgrade the dependency and makes patch creation a breeze.

Just curious: which modules are broken with mangling? I remember I had to disable it myself, but this was with react-native 0.5x version.

**Comment by rikur** [comment]
#1207

**Comment by Overtorment** [comment]
Bitcoinjs used to be broken with mangling.
Anyway, the goal is to remove patches completely, it should work now
