### ISSUE TITLE
Implement Storyboard to comply with App Store requirements

### ISSUE THREAD

**Issue by rikur** [BlueWallet/BlueWallet#1266]
The requirement: https://developer.apple.com/news/?id=03262020b

Suggested implementation: https://github.com/zoontek/react-native-bootsplash

React-native-bootsplash makes it easy to generate a stationary loading screen for both iOS and Android. Would make sense to have a static image that resembles the Lottie animation that's shown later.

**Comment by Overtorment** [comment]
are we having an issue with `Apps for iPhone or iPad must be built with the iOS 13 SDK or later and use an Xcode storyboard to provide the app’s launch screen.` ..?

if yes should be fixed natively by our magician @marcosrdz. no extra deps just for a splashscreen

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/1272
