### ISSUE TITLE
settings->network->broadcast: allow import of txhex from file and scan from QR

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#1268]
txhex from coldcard wallet for example have extension `.txn`

**Comment by ncoelho** [comment]
Support for signed PSBT (available on import transaction option) would be good as well

**Comment by marcosrdz** [comment]
Theres txn  import code available in send details.

**Comment by Overtorment** [comment]
yeah I know, but its not obvious, that's why I want to duplicate it.
