### ISSUE TITLE
HodlHodl improvements

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#1280]
* [x] when user is not logged in, clicking 'accept offer' should not just throw alert, but open login screen
* [x] before accepting offer, refetch it and use fresh id and version, so there are no 'outdated' errors
* [x] when 'I am selling', sort order should be reversed

**Comment by ncoelho** [comment]
- Local trader should be a full view
- Use modals for temporary actions (e.g. login action, can even be automatically dismissed once successful)
