### ISSUE TITLE
Problem recovering my wallet

### ISSUE THREAD

**Issue by mikele66** [BlueWallet/BlueWallet#1284]
I had problems with my walllet. Transactions were missing. I had to log out and refresh sometimes 7-8 times in a row before my balance got refreshed. I delete it and I am trying to recover it by scanning HD Segwit ( BIP 84 Bech32 Native). It keeps giving me an error. I tried to put the words manually and it gives me error again. Please help

**Comment by ncoelho** [comment]
Make sure you are connected before, the problem you describe feels like the app is not well connected.
You can try:
- Settings > network > electrum (to see if you connected)
- Settings > about > self test (to force reconnection)
- Restart the app to force reconnection
- Make sure you are on the latest version, improvements on this were released

**Comment by mikele66** [comment]
I am connected to electrum3.bluewallet.io:433. I have tried with 4G and WiFi. I have downloaded the app on my wife’s iPhone and tried to recover it, but it gives me the same error

**Comment by mikele66** [comment]
![97CDB908-8989-47A4-8084-7692D48BB1C0](https://user-images.githubusercontent.com/67366749/85531864-0b5ea600-b607-11ea-9d98-c5b24d69a9d9.jpeg)

**Comment by ncoelho** [comment]
Can you try to import it on another software, like electrum

**Comment by mikele66** [comment]
I was able to recover it in electrum

**Comment by ncoelho** [comment]
Can you try to recover in blue, but connected to another server like electrum1.bluewallet.io:433 for instance

**Comment by mikele66** [comment]
How do I change this

**Comment by ncoelho** [comment]
Easiest way is to restart the app, and let it change automatically

**Comment by mikele66** [comment]
No, same thing. I have uninstalled the app and reinstalled it again , I have restarted and was connecting to electrum1-2-3 and when I tried to import it gives me same error

**Comment by Overtorment** [comment]
can you make sure there is no typo in your words?
correct words are here: https://github.com/bitcoinjs/bip39/blob/master/src/wordlists/english.json

**Comment by Overtorment** [comment]
https://github.com/BlueWallet/BlueWallet/issues/1285

**Comment by mikele66** [comment]
I have tried manually inputting the words, I also scanned  my back up code. I downloaded the app on my wife’s IPhone and tried manually and scanned, same error. The words are good because obviously I was able to recover it on my desktop electrum. But I have no use of the app, if I can’t recover it into my blue wallet app. The app is updated because I have uninstalled it and downloaded it from the App Store , so I assume this is the latest version

**Comment by Overtorment** [comment]
Can you move funds out of the wallet and send mnemonics privately to
bluewallet@bluewallet.io to debug?

**Comment by mikele66** [comment]
Ok. Who should I send it to. Would they know what is the problem or should I explain everything from the beginning

**Comment by marcosrdz** [comment]
> Ok. Who should I send it to. Would they know what is the problem or should I explain everything from the beginning 


Please send it to bluewallet@bluewallet.io

**Comment by mikele66** [comment]
Ok. I have send you an email

**Comment by Overtorment** [comment]
problem identified and fixed here: https://github.com/BlueWallet/BlueWallet/pull/1288

the problem was in huge transactions (probably batched exchange payouts) that made bluewallet choke.
fix should be out in next release

**Comment by ncoelho** [comment]
Nice! Thanks for all the help on debugging this issue @mikele66 Cheers!
