### ISSUE TITLE
No amount passing to confirm screen

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#1287]
Happening since the fiat input release 

<img width="456" alt="Screenshot 2020-06-24 at 14 24 42" src="https://user-images.githubusercontent.com/1238429/85555695-74094b00-b626-11ea-8851-1ab0fb32ad82.png">

**Comment by Overtorment** [comment]
fixed in https://github.com/BlueWallet/BlueWallet/pull/1289
