### ISSUE TITLE
Incorrect (lnurl-withdraw) invoice amount is shown when € is the default unit (rounding error)

### ISSUE THREAD

**Issue by moonshot75** [BlueWallet/BlueWallet#1290]
18297 sats invoice turns into 18311 sats.
![230ed1b5-c952-4375-a274-a08c29e7d79e](https://user-images.githubusercontent.com/66482965/85624940-fae01700-b66a-11ea-976c-0451d01feeba.jpg)

**Comment by Overtorment** [comment]
acknowledged

**Comment by santochibtc** [comment]
I have found that this bug still exists in 6.2.17, right?

**Comment by Overtorment** [comment]
hmm. we made some fixes in master, pls wait till we release 6.2.19, and if the problem is still there - pls report it
