### ISSUE TITLE
Can't scan native segwit address (bc1) QR code

### ISSUE THREAD

**Issue by monkjuice** [BlueWallet/BlueWallet#130]
When trying to scan a qr code generated by bitcoin core wallet the camera closes and no text is inserted. 

As enhacement I would also add a warning ("Error reading QR") or something.

public key: bc1qmsc4nstw0ax0ru6eytyc0atdgk5ef35syxccsl

standard segwit works fine.

**Comment by Overtorment** [comment]
Bug confirmed. Will be fixed asap, thanks!

PS. Manually copypasting address works

**Comment by Overtorment** [comment]
fixed in
https://github.com/BlueWallet/BlueWallet/commit/ecb91d63fa97e86f8a3c9c3328ed74880e76242e
