### ISSUE TITLE
Sharing with signal doesn’t include text

### ISSUE THREAD

**Issue by jensamunch** [BlueWallet/BlueWallet#1309]
Sharing with signal only shares QR code which is confusing and useless to most people since they can’t scan the qr code with the phone they’re receiving it on. 

You can see in the screenshot how WhatsApp does share the text. Should I file this bug with signal or you? In my view you should only pass the text in the sharing - not the image. 

![AA3DA0FE-343C-4021-AF43-F7A373EC98CD](https://user-images.githubusercontent.com/1650140/86230764-740acd00-bb89-11ea-9c90-07b8219e2bed.png)

![258A9C40-236F-46C5-8A5E-81D8FE164FFB](https://user-images.githubusercontent.com/1650140/86230758-6fdeaf80-bb89-11ea-8318-5737d5539329.png)

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/1333
