### ISSUE TITLE
Add local currency equivalent when displaying tx fees before broadcast

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#131]
![image](https://user-images.githubusercontent.com/1913337/49015798-0fe98100-f17c-11e8-87d0-36cf6abacfe5.png)

**Comment by Overtorment** [comment]
![image](https://user-images.githubusercontent.com/1913337/49704425-d8aeb180-fc0a-11e8-9658-b70a2017db4a.png)

**Comment by ncoelho** [comment]
Great one!
