### ISSUE TITLE
Transaction date in future, wrong time labels - Android

### ISSUE THREAD

**Issue by neocogent** [BlueWallet/BlueWallet#1315]
Just trying out for first time. I received a new tx yesterday and showed up in list with time label "in a day". Now it says "in 11 hours". At first I thought must be non-English programmer but when I looked at tx details it had a date that was in the future.

Possible timezone issue? Anyway, it was confirmed tx shortly after sent. I'm in Australia so I was thinking it has some internal timezone/date issues between timestamp on tx info and local timezone.

Version is whatever is in play store right now.

**Comment by ncoelho** [comment]
Acknowledge

**Comment by limpbrains** [comment]
I can't reproduce the issue. Switched my TZ to Sydney, new unconfirmed TX has "a few seconds ago" time label, time in details also correct. Same for LN transactions

**Comment by neocogent** [comment]
Let me know what I can do to demonstrate/help. My last tx was a few days ago now but I'll try to screen shot on next tx if it still does the same thing. 

Perhaps it's phone related? Anyway, definitely happened. No idea why. TZ was just a guess.

I'm on a Samsung J7 Pro: Android version 9, kernel 3.18.91, security patch April 1/20. For what it's worth.

**Comment by limpbrains** [comment]
Sounds like BlueWallet doesn’t work correctly with Electum Server which runs in TZ different from UTC

Can you share your EPS address? If it is publicly accessible. What TZ is in OS settings where you run EPS?

**Comment by neocogent** [comment]
No, it's local on my LAN behind a NAT to the net. The machine it's on has correct local time (AEST, GMT+10). I watch the EPS logs and compared between when Electrum connects and when bluewallet connects. All the log timestamps are correct local times and I don't see any logged times being sent to wallets but it may not be logging that detail.

I "grepped" the logs for the tx id in question and it is logged at the matching time that Electrum has. There was a lot of occurrences and some may have been to bluewallet, as I viewed it on my phone while waiting for confirms, but they all were logged around that time.
 I guess if there is time data in the tx data that is assumed GMT but is not then that could be misinterpreted. No idea what is correct from EPS / Electrum specs but it sounds like a possible protocol difference. I had a look in EPS conf file and only thing time related was logging formatter had %(asctime)s substitution parm which places the log time. That is default, not changed by me.

Not sure what else I can check.

**Comment by Overtorment** [comment]
about a year go we had the same bugreport and I could not find root cause as well

**Comment by neocogent** [comment]
Oh, darn. I guess that means I'll have to see if I can find it when I get my next btc paycheck. Maybe I should try to log data exchanged between bluewallet and EPS during my first update after tx. I'm expecting that tonight.

**Comment by neocogent** [comment]
So, my new pmt came in today and the same happened again. 

In Electrum the correct received time is 2020-07-08 11:27 and on bluewallet it says "in 2 days" and shows 7/10/2020 4:45am. It's hard to see just a tz diff there. That seems to be 2 days - 6hrs 42 min. ahead or 41 hrs. 18 min. Weird. I got some screen caps for reference but could not do any data capture as my wifi card doesn't support monitor mode. 

I pasted screen caps here - really sorry they show up so big. Need thumbnails. Don't think that will be much help except to say "see, ain't making it up".

I looked at the EPS logs and located the transaction log entry where it's being sent to bluewallet. I retrieved the correct tx raw data from blockchain and compared and it's the identical raw tx data. So according to logs the correct raw tx data is sent to bluewallet. I could see no other indications of tx timestamp in the logs. I presume that bluewallet gets the raw tx data and decodes it to get tx timestamp, but something goes wrong. Best I have right now.

For privacy reasons I won't post txid or amounts here.

![bw1](https://user-images.githubusercontent.com/5811476/86872074-e1d16e80-c11e-11ea-9b99-6e8695096206.jpg)
![bw2](https://user-images.githubusercontent.com/5811476/86872079-e3029b80-c11e-11ea-8dde-50b837bc915a.jpg)
![bw3](https://user-images.githubusercontent.com/5811476/86872081-e39b3200-c11e-11ea-8a99-eded2c5413e0.jpg)

**Comment by neocogent** [comment]
I had a look at the bluewallet source code and fairly quickly found the problem. When retreiving a hex tx from EPS it does not use the decocded time value from the tx data. Instead it fakes it with the code below:

line 483 in BlueElectrum.js called by line 375, when tx data

module.exports.calculateBlockTime = function (height) {
  const baseTs = 1585837504; // sec
  const baseHeight = 624083;
  return baseTs + (height - baseHeight) * 10 * 60;
};

Using this code I plugged in block my tx was in:

1585837504+(638221−624083)×600

And put in a online unix time convert and got:

Friday, July 10, 2020 4:45:04 AM GMT+10:00

Exactly the time of tx details in bluewallet.

So some code should be added to extract actual block and tx time from  raw tx data. It should go in decode function at line 524. I was going to say it's already using the bitcoin-js lib for some values but looking at that there is no info available. So the next best option is to try and get some block header for the relevant block. Well, or at least update the reference block/timestamp at least once every day or when app opened so that the weird faked value isn't so far off.

I checked my sqlchain electrum implementation and saw that there is a Electrum server api called **blockchain.block.get_header**. Making a request to get that should allow decoding block time.

I guess I'd try to code this but it would mean getting all setup for Android dev and while I have done it in past I no longer have everything needed to get into that. Someone who's working on the app every day can likely do this code much quicker than me.

**Comment by neocogent** [comment]
Turns out I have Android Studio 2.2.3 on my system. I'll try to build for Android and see if I can add suitable code for fixing time. First step appears to upgrade to Android Studio 4.0 (819 MB). Will, report back how it all goes.

**Comment by neocogent** [comment]
Sigh. I spent 7 hours in Android Studio hell trying to get this to work. Between upgrading from 2.2.3 and problems with the emulator not connecting (adb seemingly not finding the emulator) and yada yada. I give up, for now. I'd like to get this all set up so I can help with dev work. Wat a nightmare of configurations and bloated downloads.  

Anyway, I did make changes here that I thought would get the block time and use it for the tx details and the diff output is below. Maybe someone who has this all working can give it  test.

```
diff --git a/blue_modules/BlueElectrum.js b/blue_modules/BlueElectrum.js
index fd11eecd..a5b76596 100644
--- a/blue_modules/BlueElectrum.js
+++ b/blue_modules/BlueElectrum.js
@@ -372,8 +372,9 @@ module.exports.multiGetTransactionByTxid = async function (txids, batchsize, ver
                 // ugly fix for when estimator lags behind
                 tx.confirmations = 1;
               }
-              tx.time = this.calculateBlockTime(txhashHeightCache[txid]);
-              tx.blocktime = this.calculateBlockTime(txhashHeightCache[txid]);
+              let hdr = await mainClient.blockchainBlock_getHeader(txhashHeightCache[txid]);
+              tx.time = hdr.timestamp;
+              tx.blocktime = hdr.timestamp;
             }
           }
           results.push({ result: tx, param: txid });

```

**Comment by misovan** [comment]
Hi, I am facing similar situation after I imported few watch only wallets. While connected to public electrum servers (e.g. blockstream.info) I got wallet balances correctly updated, but in spite of refresh / restart I could not past transactions (seems to be missing 'rescan from' support). When I switched to private EPS server I got both balances and transactions imported into the wallet, however:
- all transactions had wrong dates, coming event to the future (as mentioned above). Shift against real date spans from days to months
- transactions shown as future or recent show 0 confirmations even they are up to few months old
- in case of two wallets (from 7 imported), wallet balance is slightly different (order of 0.00x BTC) from reality (was correct with public Electrum server and at the same time is correct when the same view keys are imported into Electrum wallet connected to the same EPS.

Hope this helps in investigation. If there is a need to make some test against EPS, let me know

**Comment by Overtorment** [comment]
@misovan can you pls privately share some info with i@bluewallet.io ? I would need single zpub that shows incorrect balance & incorrect tx time, and your EPS address (if its private maybe you can port forward it for a while, while I debug this?)

**Comment by Overtorment** [comment]
there is a fresh android build on https://github.com/BlueWallet/BlueWallet/pull/1548 if anyone wants to test it and make sure its fixed

**Comment by misovan** [comment]
See my email to i@bluewallet.io with interim test results and some info I can safely share. I partially tested the new apk as well.

**Comment by Overtorment** [comment]
https://github.com/BlueWallet/BlueWallet/pull/1607
