### ISSUE TITLE
Receive/Scan of QR-Code doesn't work in LN wallet

### ISSUE THREAD

**Issue by Tigerix** [BlueWallet/BlueWallet#1327]
Steps to reproduce:
1. Open LN wallet
2. Tap on Receive
3. Tap on Scan

It keeps processing without an end showing the waiting circle.
It works though when using the Scan function on the main screen.

![photo_2020-07-06_10-49-19](https://user-images.githubusercontent.com/125405/86574600-5ddc8280-bf76-11ea-86f9-8c2c1bd5f084.jpg)

**Comment by ncoelho** [comment]
Is this a wallet using bluewallet backend?
Seems it is not connecting

**Comment by Tigerix** [comment]
Yes, its using bluewallet backend!
But why does it then work on the main screen using scan?

**Comment by ncoelho** [comment]
scan is general, works for any wallet. wallets then are connected to specific backends. It happens the same if you create a new wallet?

**Comment by Tigerix** [comment]
Now its showing "Network request failed"

**Comment by ncoelho** [comment]
ok, so it is not connecting. Restart the app, check settings > about > run self test

**Comment by Tigerix** [comment]
Self test says "OK"

**Comment by Tigerix** [comment]
As I said its always working on the wallets screen --> Scan

**Comment by Tigerix** [comment]
Please try yourself. I am sure you'll be able to reproduce.

**Comment by ncoelho** [comment]
works great here and as no one else complained about this I suspect it is something related with your connection. 

Things you can try:
- does lndhub.io opens on your phone?
- switch wifi/4g
- disconnect VPN

**Comment by ncoelho** [comment]
wait, manage to reproduce. On it!

**Comment by ncoelho** [comment]
ok, so. The scan on the "receive" screen is only for lnurl. It is working ok, you can try it out here
https://lnurl.bigsun.xyz/

**Comment by Tigerix** [comment]
Oh you are right! I was my mistake.
I should have clicked on "Send" since I wanted to send funds to Yalls.
Maybe it makes sense to improve the error message, so it is more clear what goes wrong?

**Comment by ncoelho** [comment]
Definitely. This was confusing to even understand what was going on here :D

**Comment by Tigerix** [comment]
I guess this issue can be closed?
