### ISSUE TITLE
HodlHodl -> logout option

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#1339]
probably place somewhere in settings? or straight on HH screen somewhere

logout is simply deleting 2 HH tokens from storage and re-rendering screens so `login` button appears again

@ncoelho where do we place it?

**Comment by ncoelho** [comment]
Inside "my contracts" on the top right, seems a good "localized" place.

**Comment by Overtorment** [comment]
https://github.com/BlueWallet/BlueWallet/pull/1411
