### ISSUE TITLE
bolt11 links are opening the app but not the invoice itself

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#1352]
Steps to reproduce:
1- create an invoice
2- share invoice
3- tap on the "link"
4- opens app and does nothing

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/1359

**Comment by Overtorment** [comment]
links with `//` are not used in real life.  I think there is even a specification somewhere that describes linking to `bitcoin:` and `lightning:`, and there is no double slashes there.
BW should not produce them as well.
