### ISSUE TITLE
Input field to rename wallet is covered when typing

### ISSUE THREAD

**Issue by Abstraktikus** [BlueWallet/BlueWallet#1356]
![image](https://user-images.githubusercontent.com/17813711/87850168-6d50b980-c8ee-11ea-9213-fe0ee86b80d4.png)

iOS + Android. Also visible here: https://appetize.io/app/4adxe5aejjvu7dpeb3aumgx5bc?device=nexus5&scale=100&orientation=portrait&osVersion=8.1

1.) Create a new bitcoin or lightning wallet OR import a watch-only wallet.
2.) Rename the wallet

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/1358
