### ISSUE TITLE
Font-Color in Input Field "transaction notes" is not adapted for dark mode

### ISSUE THREAD

**Issue by Abstraktikus** [BlueWallet/BlueWallet#1364]
Precondition: Night-Mode is switched 'On'.

1.) Click on a transaction
2.) Navigate to details
3.) Rename the "note to self".

Problem: Font-Color is black and not visible on the dark background.

**Comment by ncoelho** [comment]
Can you leave a ss and your os version

![image](https://user-images.githubusercontent.com/1238429/88070199-54ecd300-cb6a-11ea-885f-ef6dba8b4753.jpeg)

**Comment by Abstraktikus** [comment]
![image](https://user-images.githubusercontent.com/17813711/88090408-d73abe80-cb8d-11ea-8130-39e587abd995.png)

Build: G950FXXU99DTF1
Android-Version: Ple(Android 9)
Date 2020-07-06

**Comment by Abstraktikus** [comment]
All other fields looks like this:
![image](https://user-images.githubusercontent.com/17813711/88092074-300b5680-cb90-11ea-9e2f-88a2fd0110d5.png)

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/1367/files
