### ISSUE TITLE
Support: New feature watch wallet for bitcoin core wallet is not working

### ISSUE THREAD

**Issue by gaetawoo** [BlueWallet/BlueWallet#1366]
I'm not sure what kind of input the information needs to be to watch a wallet from bitcoin core. I have a multisig bitcoin core wallet that I want to watch, but when I try to import the descriptor which looks like this:

wsh(multi(3,xpubBLAHBLAHBLAH/*,xpubBLAHBLAHBLAH/*,xpubBLAHBLAHBLAH/*,xpubBLAHBLAHBLAH/*,xpubBLAHBLAHBLAH/*,xpubBLAHBLAHBLAH/*,xpubBLAHBLAHBLAH/*))#checksumcharacters

It doesn't like it. If I use one of the xpubs it obviously doesn't track the multisig wallet. So how do i do it?

**Comment by Overtorment** [comment]
1) multisig is not supported, yet
2) format that is supported is `[fingerprint/derivation]xpub`  for example `[8cce63f8/84h/0h/0h]zpub6s2RJ9qAEBW8Abhojs6LyDzF7gttcDr6EsR3Umu2aptZBb45e734rGtt4KqsCMmNyR1EEzUU2ugdVYez2VywQvAbBjUSKn8ho4Zk2c5otkk`

**Comment by gaetawoo** [comment]
Thanks @Overtorment . The format is unclear to me from the btc-core perspective. Core doesn't use zpubs, it doesn't use that derivation path, and where does one get the fingerprint? Thank you!

**Comment by Overtorment** [comment]
@stepansnigirev ?

**Comment by stepansnigirev** [comment]
This key format only helps to create proper PSBT transactions with valid derivation paths (master fingerprint and derivation path).
To make BlueWallet fully compatible with Core you would need to add support of descriptors, like `wpkh([fingerprint/derivation]xpub/0/*)` for receiving descriptor and `wpkh([fingerprint/derivation]xpub/1/*)` for change descriptor.
In Specter we drop the last part `/0/*` to transmit both change and receiving descriptor to the wallet.
FullyNoded2 uses a different approach - they only import the receiving descriptor and construct the change descriptor themselves by replacing `/0/*` to `/1/*`.
