### ISSUE TITLE
Add available languages to app store

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#1373]
<img width="601" alt="Screenshot 2020-07-23 at 10 37 56" src="https://user-images.githubusercontent.com/1238429/88272443-a1eab980-ccd0-11ea-92cb-1f1a98deb803.png">

**Comment by Overtorment** [comment]
what should be done here?

**Comment by ncoelho** [comment]
@marcosrdz I believe this are xcode settings?

**Comment by marcosrdz** [comment]
Yuuuup

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/1413
