### ISSUE TITLE
Cleanup and Refactor

### ISSUE THREAD

**Issue by marcosrdz** [BlueWallet/BlueWallet#138]
After releasing our next iOS update, code clean up and refactoring should be a priority. This will reduce bugs, and allow us to grow the app without having to write “cryptic” code to get around bugs. Here is the list of things I propose:

- separate styles from inline jsx styles
- use redux with pure functions. This will completely separate our logic from UI and allow for super easy testing.
- use flow. Flow will allow us to continue writing pure JS and add type checking. TypeScript requires us to learn special syntaxes and have it compile back to pure JS. 
- platform specific code should be a separate file, instead of having multiple in-line checks.

**Comment by ncoelho** [comment]
gonna transform this in different issues

**Comment by ncoelho** [comment]
https://github.com/BlueWallet/BlueWallet/issues/139
https://github.com/BlueWallet/BlueWallet/issues/140
https://github.com/BlueWallet/BlueWallet/issues/141
https://github.com/BlueWallet/BlueWallet/issues/142
