### ISSUE TITLE
App crashes on load

### ISSUE THREAD

**Issue by motud2** [BlueWallet/BlueWallet#1385]
I tried to add a watch only wallet using ‘import’ and a zpub.
The app hung so I shut it down.

Now it won’t load, it crashes after the fingerprint authorisation. 

IPad pro, latest release of BlueWallet.

Have deleted and reinstalled the app, no joy, still crashes on load.

:(

**Comment by ncoelho** [comment]
Can you point out how the zpub/wallet was created. So we can try to generate one as well. Thanks!

**Comment by motud2** [comment]
I used the Ian Coleman site,

BIP141 tab
derivation path:  m/0'/0  
script symantitcs  P2WPKH

**Comment by Overtorment** [comment]
are there any coins there? it might be BW fails to parse tricky transaction and crashes. 
in that case can you pls send xpub privately to i@bluewallet.io so I can debug this? thanks!

**Comment by motud2** [comment]
There are coins there.

This is a BRD wallet, their implementation uses the same derivation path for both legacy AND SegWit addresses.

**Comment by Overtorment** [comment]
yeah, we have support for BRD format. but I need to see if there's a tricky transaction there

**Comment by Overtorment** [comment]
most likely fixed in https://github.com/BlueWallet/BlueWallet/pull/1400
should be out in next release
