### ISSUE TITLE
Inverted QR codes

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#1386]
Apparently inverted QR codes (introduced in dark mode) are a known problem in many readers/cameras and there's no big support for them. 

We should:
- create a wrapper surrounding the QR codes
- keep the QR codes in the light mode always

**Comment by limpbrains** [comment]
Or we can keep inverted by default and change qrcode type when user taps on it.

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/1433
