### ISSUE TITLE
Use redux with pure functions

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#140]
**Use redux with pure functions. This will completely separate our logic from UI and allow for super easy testing.**

After releasing our next iOS update, code clean up and refactoring should be a priority. This will reduce bugs, and allow us to grow the app without having to write “cryptic” code to get around bugs

**Comment by bjornoj** [comment]
Can this issue be closed then?

**Comment by Overtorment** [comment]
Not implemented and I personally dont care about redux.
