### ISSUE TITLE
Use Flow

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#141]
use flow. Flow will allow us to continue writing pure JS and add type checking. TypeScript requires us to learn special syntaxes and have it compile back to pure JS.

**Comment by Overtorment** [comment]
Noted.

**Comment by Overtorment** [comment]
Is it possible to gradually introduce typescript, without rewriting _everything_ ..?

**Comment by pajasevi** [comment]
It should be possible, though I've never done it with React Native. I will start with something small.

**Comment by Overtorment** [comment]
Cool. Lets see how it works
