### ISSUE TITLE
Crash on start, on Android

### ISSUE THREAD

**Issue by Transisto** [BlueWallet/BlueWallet#1416]
End up on a white screen then crash.

I've only ever used it to import a few barely supported xpubs to test, So it could be related.

**Comment by Overtorment** [comment]
Very much likely fixed in https://github.com/BlueWallet/BlueWallet/issues/1399
Release is pending (v5.5.2), should be out in couple of days. 
Ill close this, please reopen if v5.5.2 wont fix it for you.
