### ISSUE TITLE
Font-Color in Bump-Fee Input Field "Custom" is not adapted for dark mode

### ISSUE THREAD

**Issue by Abstraktikus** [BlueWallet/BlueWallet#1439]
![Screenshot_20200804-212105_BlueWallet](https://user-images.githubusercontent.com/17813711/89338391-ccf3e680-d69c-11ea-8ab7-dddf0973ed6b.jpg)

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/1444

**Comment by Overtorment** [comment]
fix will be out in next release. thanks!
