### ISSUE TITLE
Ability to set amount to receive

### ISSUE THREAD

**Issue by pajasevi** [BlueWallet/BlueWallet#144]
Add number field to `ReceiveDetails` screen to set amount to receive which would update URI as specified in BIP21 and thus generated QR code.

**Comment by pajasevi** [comment]
@Overtorment Thanks for the info!

**Comment by pajasevi** [comment]
Ugh, I had to send a [PR](https://github.com/nating/react-native-custom-qr-codes/pull/11) to `react-native-custom-qr-codes` library because the component does not rerender after new props are passed. Hope it will not take too long.

**Comment by Overtorment** [comment]
I think it will, the other PR hangs there for a long time. Probably best to reach out maintainer directly and ask him to merge.
Worst case scenario, fork it and we can switch to forked version. Maybe even publish to npm with diferent package name

**Comment by pajasevi** [comment]
Closing this as done. Thanks.
