### ISSUE TITLE
Input field for Import wallet unusable on an Android with small screens  

### ISSUE THREAD

**Issue by sgornick** [BlueWallet/BlueWallet#1478]
My phone's display is 854 x 480.  When I try to import a wallet, I am unable to see the characters as I type.  The characters I press are added, it is just that I cannot see them.  The problem is the the field is too low and the on-screen keyboard takes up half the screen, leaving too little of the display for the input field to show feedback.

When I press the Enter on the on-screen keyboard, BlueWallet does re-render with the taller field, and I do see everything I typed.

I was able to work-around so that I could see the words in the entry field (at least one line of words) by changing, temporarily, my Font size (Settings -> Display -> Advanced -> Font size) to Small.

The device I'm experiencing this on is an Alcatel 5041c:
http://specdevice.com/showspec.php?id=6b4a-c88f-ffff-ffffd91d6a7a

As far as a fix ... I don't know if a scalable / responsive layout is needed ... raising the height of the field by removing just some of the whitespace probably would have left enough of the field to show the words  -- at least for this display resolution.

I tried to do a screenshot but when attempting to do so, Android shows an error message saying the app doesn't permit screen shots.

So, to recreate the issue as I encountered it:

- Using BlueWallet on an Android with a low resolution display (854 x 480, or smaller, presumably):
- In Wallets, select Bitcoin and then Import.
- In the field for entering the mnemonic / seed, private key, etc., press characters using onscreen keyboard.

Expected behavior:

See the results of each character pressed.

Observed behavior:

No display of any characters pressed, at least, not until press Enter key, and then the field is re-rendered and the characters pressed do now appear in the field.

**Comment by Overtorment** [comment]
Acknowledged. Thanks!

**Comment by marcosrdz** [comment]
Hello! We have made a change that will provide more viewing room on Android devices. 

https://github.com/BlueWallet/BlueWallet/pull/1487

It should be available on the next release. If the issue persists after said release, please don't hesitate to reopen the ticket.
