### ISSUE TITLE
Android Wallet Network - Electrum - Status always "Connected" even if it isn't

### ISSUE THREAD

**Issue by Kineticmb** [BlueWallet/BlueWallet#1480]
On the Android App the Status always says "Connected" tomy electrum server even if it is not connected. Its a local IP so when away from the network, this should read "disconnected" of course. 

Less experienced users may not know itsnotconnectedand transactions will hang without them knowing why. 

Thanks,

**Comment by Overtorment** [comment]
fixed in https://github.com/BlueWallet/BlueWallet/pull/1497
(https://github.com/BlueWallet/rn-electrum-client/commit/09453000a63b8b15b37e58f80c47c7120dc8d89d)
