### ISSUE TITLE
Ability to spend legacy (BIP44) outputs

### ISSUE THREAD

**Issue by pajasevi** [BlueWallet/BlueWallet#149]
Hi, will it be possible to spend imported legacy (BIP44) outputs in the future?

**Comment by Overtorment** [comment]
I'm not planning working on that right now, but eventually will be done.
I think its low to medium difficulty to make it, so anyone with bitcoinjs experience can jump in (or learn it along the way). I can provide full support in the process.
We also have full test coverage for HD wallets.

**Comment by pajasevi** [comment]
Closing as fixed
