### ISSUE TITLE
Add client wallet for Acinq Strike API

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#151]
* Add configuration for api key in settings
* Add wallet type which is a wrapper for Strike API (`class/lightning-custodian-wallet.js` as an example)
* Make it create payment requests, fetch invoices etc etc

**Comment by Overtorment** [comment]
Also, when creating LN wallet, there should be radiobox selector, so user can choose custodial or Strike-receive-only

**Comment by ncoelho** [comment]
Can you explain better the use case.
- One LN wallet for custodial.
- Another one for Strike. 

What is strike what does it do?

**Comment by Overtorment** [comment]
@ncoelho Strike is an awesome service by Acinq: https://strike.acinq.co
you can signup, get your api key and start creating LN invoices. or integrate your e-commerce with Strike.

**Comment by joaodealmeida** [comment]
If you guys are stepping in with this, I can add an ON integration after you make the abstraction :)

**Comment by Overtorment** [comment]
@joaodealmeida actually ON integration would be really cool! you dont need anything from us to start. if you could just start with cloning `class/lightning-custodian-wallet.js` and making it work with ON (dont forget integration tests, example here: `LightningCustodianWallet.test.js`) would be nice. we could then take it and integrate with our react-native frontend app.

**Comment by marcosrdz** [comment]
Implemented in acing branch.
