### ISSUE TITLE
Cannot connect to electrs using TLS on port 50002

### ISSUE THREAD

**Issue by RooSoft** [BlueWallet/BlueWallet#1516]
I have an electrs server working on a server through port 50002. I can tell because electrum itself works with this setup.

When trying with BlueWallet, it crashes directly from Electrum Settings.

Is there a way to consult some logs to understand what's wrong?

**Comment by RooSoft** [comment]
Oh, using the iOS latest version.

**Comment by Overtorment** [comment]
default electrum servers work okay? can you expose your electrs to the world (email me privately at i@bluewallet.io)?
you cannot access logs as is, unless you have a development setup (code, npm, android studio etc).

PS. also, can you email me your IP? ill check our crash reporting service.

**Comment by RooSoft** [comment]
Yeah, works with 50001

**Comment by Overtorment** [comment]
btw, heres the simplest nodejs script to test any electrum server (tls): https://runkit.com/overtorment/test-electrum-server

**Comment by RooSoft** [comment]
The outcome of this thread is that I was trying to connect to a faulty electrum server. Still, that made BlueWallet crash on iOS, but I think that @Overtorment has created another issue about it.
