### ISSUE TITLE
Testnet integration for development purposes

### ISSUE THREAD

**Issue by pajasevi** [BlueWallet/BlueWallet#152]
It would be great to have an option to use testnet for on-chain as well as off-chain transactions for development purposes.
Ideally this would only require one ENV variable and additional start script which would set this variable to "testnet".
Of course there are other implications, mainly addresses, that need to be covered by this change.

**Comment by ncoelho** [comment]
Developing and testing with your own bitcoin is a different level of responsibility :D

Yes, this would be great!

**Comment by Overtorment** [comment]
testnet support is not planned
