### ISSUE TITLE
Crashes if previously saved EPS goes offline during cold boot

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#1522]

**Comment by RooSoft** [comment]
How to reproduce

- Configure it for a working personal electrum server on port 50001
- Bring the server offline
- Shutdown BlueWallet app on iPhone
- Click on BlueWallet icon
- BlueWallet crashes instantly, no matter how many time you try to start it
  - This part is kind of creepy for people having funds in the wallet
- Bring the 50001 server back online
- Everything is back to normal, the app starts successfully
