### ISSUE TITLE
Settings|Network|Lightning Settings fails input for leading or trailing blank

### ISSUE THREAD

**Issue by HamishMacEwan** [BlueWallet/BlueWallet#1524]
Leading or trailing blanks in the Lightning Settings field result in error message. First without leading blank:
![Lightning Settings Success Screenshot_20200826_105821_io bluewallet bluewallet](https://user-images.githubusercontent.com/388061/91236374-d946fd00-e78b-11ea-9dda-d0ee233281e3.jpg)
Second with leading blank:
![Lightning Settings Fail Screenshot_20200826_105811_io bluewallet bluewallet](https://user-images.githubusercontent.com/388061/91236403-e82daf80-e78b-11ea-9360-caa6c45e7032.jpg) The only difference between the URI input is the leading blank.

**Comment by marcosrdz** [comment]
Thanks for reporting!

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/1526
