### ISSUE TITLE
Issue: Apple Watch invoice gets stuck

### ISSUE THREAD

**Issue by dannmat** [BlueWallet/BlueWallet#1529]
When creating an invoice on Apple Watch (S3 44mm WiFi only), the invoice gets stuck on "Creating invoice..." screen.

**Comment by dannmat** [comment]
![image](https://user-images.githubusercontent.com/9567098/91288568-0b0a9480-e789-11ea-9a02-78380c6af4f3.jpeg)

**Comment by marcosrdz** [comment]
Have you tested with the release 5.5.6?

**Comment by dannmat** [comment]
Sorry yes, I forgot to mention this is on 5.5.6, after the same bug had been fixed. I don't know if it's related to that issue?

But I'm running the latest blue wallet, 5.5.6 (build 1598372093)

**Comment by marcosrdz** [comment]
Was your iPhone and Watch connected, with good network conditions, when this occures?

**Comment by dannmat** [comment]
I've tried several times with good network conditions.

**Comment by Overtorment** [comment]
is it still happening?

**Comment by dannmat** [comment]
I've just tried to reproduce and the issue is still occurring, unfortunately.

What is strange is the invoice actually gets generated, as I can access it from my iPhone. However, the QR code never pops up on the watch (I'm assuming a QR code is the intended functionality).

I'm running ver 6.1.9.

Cheers!

**Comment by Overtorment** [comment]
@marcosrdz

**Comment by marcosrdz** [comment]
Finally was able to replicate the issue with the following scenario:

Close the iOS app(removing it from multitask drawer), then attempt to generate an invoice through the watch app. I'll look into a fixing it
