### ISSUE TITLE
Support AEZEED mnemonic seeds (compatibility with LND onchain)

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#1543]
https://github.com/bitcoinjs/aezeed

**Comment by junderw** [comment]
Note: LND uses two wallets from the seed.

1. BIP 84 p2wpkh
2. BIP 49 p2sh-p2wpkh BUT the change address keys are p2wpkh.

Not sure if that means change addresses are always fetched from the BIP84 change path or if they use the BIP49 change path but just encode the address using p2wpkh.

@roasbeef

**Comment by junderw** [comment]
Also, interestingly enough, the birthdate info is useless since we're querying addresses from a full index. :-P

**Comment by junderw** [comment]
`abandon female space sun pride era corn animal park paper ahead uniform retreat proud amateur stamp bone surge also over token fox balance gun`

This phrase is a valid aezeed, BIP39, AND Electrum v2 segwit seed.

Might be useful for testing to make sure an ambiguous seed performs in a certain way.
