### ISSUE TITLE
Safello flow is broken

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#1565]
Allow for Swedish id app deeplinking

_bankid://_

**Comment by odniklas** [comment]
Also allow for swish://

**Comment by Overtorment** [comment]
![image](https://user-images.githubusercontent.com/1913337/91839021-4a802780-ec46-11ea-9c8b-6101f5b64869.png)

**Comment by Overtorment** [comment]
To reproduce open https://app.safello.com/sdk/quickbuy.html?appId=4904c769-8a1d-43ca-8bd0-896520c94fdf&utm_source=BlueWallet&utm_medium=Wallet&country=SE&theme=bluewallet&layout=app&address=bc1qradv92e0q0w9gl98y49znd8qt783cpqqx8el3n on ios Safari, safari wont be able to open malformed deeplink and will throw an error
(problem is in triple slash)
