### ISSUE TITLE
Autocorrect when importing wallet

### ISSUE THREAD

**Issue by plengkeek** [BlueWallet/BlueWallet#164]
If the user imports the wallet multiple times using mnemonics then the keyboard autocorrect will store these words in the history. Although this might be a small concern other wallets have implemented this functionally. It would be nice if the autocorrect of the keyboard could be temporarily disabled for the sake of security.

**Comment by Overtorment** [comment]
Wow this is super important, I didnt even think about that, thanks!

**Comment by marcosrdz** [comment]
bc1fa41269a37694b11e3ec7190f43398faf7efb
