### ISSUE TITLE
Text not displayed correctly

### ISSUE THREAD

**Issue by plengkeek** [BlueWallet/BlueWallet#165]
There appears to be an issue with some of the text not being fully displayed even when there is space on the screen. 

![screenshot_20181221-104049__01](https://user-images.githubusercontent.com/26768472/50338212-f1c13780-0513-11e9-9a36-1048d3a23bb8.png)

**Comment by Overtorment** [comment]
@plengkeek thanks! what exact model is your device?

**Comment by plengkeek** [comment]
OnePlus 6 Android 9.0.2

**Comment by matt-auckland** [comment]
I also have this bug. OnePlus 6 running OxygenOS (OnePlus' Android flavour) v9.0.3

**Comment by marcosrdz** [comment]
05fc19d0d4b5f25f5cd4e0ff0edc8b67e5499adb

**Comment by plengkeek** [comment]
This commit is part of 3.8 if I understand correctly but this issue is still here in BlueWallet 3.8.1 OnePlus 6 Android 9.0.4

**Comment by Overtorment** [comment]
@marcosrdz ^^^

**Comment by marcosrdz** [comment]
I believe i just fixed it in the lnd PR. It should make it in the next release
