### ISSUE TITLE
Tx duplication

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#168]
User report on twitter:
https://twitter.com/frankyleejones/status/1076026447230320642?s=12

![du7qwiix0aal3o4 1](https://user-images.githubusercontent.com/1238429/50377239-a8571200-0611-11e9-8d84-7c28c8d03eb0.jpg)

**Comment by LukasVinc** [comment]
twitter report by me
more screenshots in #162 
I think those bugs belong together.

**Comment by foxikk** [comment]
Same for me. I send yesterday (24.12.2018) one BTC transaction from my NON Blue Wallet to TOP-UP the Blue Wallet. This transaction had 2 outputs (My BlueWallet and my friend's BlueWallet). Now I see multiple BTC and multiple LN wallets in my app (Yesterday 2 and today 8). All created wallets are the same. Just duplicates. We both have latest Android App.

**Comment by Overtorment** [comment]
Acknowledged.

**Comment by Overtorment** [comment]
![bug with wallets duplication peek 2018-12-29 01-47](https://user-images.githubusercontent.com/1913337/50532088-04d39900-0b0c-11e9-96fc-0f7717c2226c.gif)

reproduced. wallets duplication bug is related to URI scheme handling.

tx duplication (without wallets duplication) is basically a separate issue, and this one is an issue with blockchain data provider api.

**Comment by pajasevi** [comment]
Damn, what a nasty bug. Nice work @Overtorment
