### ISSUE TITLE
Confirmation rate lagging behind

### ISSUE THREAD

**Issue by LukasVinc** [BlueWallet/BlueWallet#169]
Somehow the confirmations of the transactions in the app is always lagging behind. I always have 1 confirmation less in the app, than on every block explorer I checked.
This can result in a long waiting time until I can use my UTXO if blocktimes are long. Especially because bluewallet does not allow the use of not confirmed UTXOs. You could have 1 confirmation already but the app shows 0.
I noticed the problem yesterday und today I was able to recreate it.

Pictures were taken 10 seconds apart: 
![image](https://user-images.githubusercontent.com/24192160/50377904-186f9300-0626-11e9-8685-85e5376f2758.png)
![image](https://user-images.githubusercontent.com/24192160/50377911-3210da80-0626-11e9-899b-fff7cd8e2347.png)

Maybe an option to use your own blockexplorer would be great, or it is just a counting error in the app.

**Comment by marcosrdz** [comment]
This bug has been fixed. It will be part of our next release.
