### ISSUE TITLE
Request: Currency TWD ($) - (Taiwan New Dollar)

### ISSUE THREAD

**Issue by B369** [BlueWallet/BlueWallet#1712]
Would be awesome if TWD ($) could be added into the settings as a currency option.

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/1713

**Comment by B369** [comment]
Thanks Marco. That was fast. It was the first time, i did a request here. May i ask when to expect the next .apk release with TWD in it ?

**Comment by marcosrdz** [comment]
Hello B36! It should be out with our next release
