### ISSUE TITLE
Cobo Vault; Scan to broadcast transaction is broken

### ISSUE THREAD

**Issue by Abstraktikus** [BlueWallet/BlueWallet#1764]
1.) Scan PSBT Barcode to CoboVault
2.) Sign Ttansaction
3.) scan barcode with the signed transaction from CoboVault
The barcode will not be recognized by BlueWallet. I made several attempt on an Android Samsung Smartphone. Reproducible with an iPad tablet. 

Version: 5.5.8 (build 1599752722)

**Comment by Overtorment** [comment]
whats the cobo firmware version?

**Comment by Overtorment** [comment]
nvm, reproduced. bug introduced in 5.5.8 by https://github.com/BlueWallet/BlueWallet/pull/1596

**Comment by Overtorment** [comment]
will be out in next release (probably tomorrow)
