### ISSUE TITLE
build 6656 - tap on send without finishing creating a tx

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#1795]
![photo_2020-09-15_11-50-04](https://user-images.githubusercontent.com/1238429/93195532-a4eead00-f749-11ea-94ab-352c276204a4.jpg)

**Comment by ncoelho** [comment]
this was fixed by https://github.com/BlueWallet/BlueWallet/pull/1790 ?

**Comment by Overtorment** [comment]
it is supposedly fixed in master
