### ISSUE TITLE
build 6656 - custom value on rbf/cpfp can't delete the 1

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#1801]
It is very difficult to remove the 1 value on the custom input option. You need to select and delete it, mainly because the cursor is on the right side on the text?!

**Comment by limpbrains** [comment]
Things that I've tried:
- onFocus put cursor to the right after the text. Works 50% of the time
- enable selectTextOnFocus, text should be selected when you tap on field. Doesn't work at all

How I can fix it:
1. redesign to something like
<img width="371" alt="изображение" src="https://user-images.githubusercontent.com/155891/93218785-46d6bf80-f773-11ea-820f-2511e1ae5ba6.png">

2. increase right padding in Input, so there would be no problems to put cursor after the text
<img width="385" alt="изображение" src="https://user-images.githubusercontent.com/155891/93218982-856c7a00-f773-11ea-8fb5-8e6b5bdf08ab.png">

@ncoelho What do you think of it?

**Comment by ncoelho** [comment]
Simple way just to fix it would be to have the text on the left, with default behaviour.

I check on UI frameworks, like in bootstrap, even when there's a label on the right, the input text keeps the default behaviour on the left.

https://getbootstrap.com/docs/4.0/components/input-group/
