### ISSUE TITLE
Notice about missing lighting wallet is immediately closed

### ISSUE THREAD

**Issue by iBobik** [BlueWallet/BlueWallet#1809]
When app is opened and there is lighting invoice in the clipboard, it will offer to use it. But then it shows notice about missing lighting wallet just for a second:

https://www.dropbox.com/s/ewvj0wc3cxhusxd/RPReplay_Final1600178955.MP4?dl=0

Btw, I think it is not good for usability that user have to care about type of wallet.

**Comment by Overtorment** [comment]
ack
