### ISSUE TITLE
PSBT flow - import transaction

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#1822]
Importing transaction from send screen to keep the PSBT sending flow, brings the user back to the send screen without any populated data.

**Comment by phonzy85** [comment]
I encountered this error this morning, when trying to import and send a signed .psbt. In my watch only wallet I chose "send" then "import transaction"' however I got an error message when trying to import the signed .psbt file from my SD card.

I was however able to import the .txn file and then I broadcasted that from within my watch only wallet. This seems to have worked, however I am still waiting on confirmations of the transaction (as I set the fees to a minimum).

-phonz

**Comment by phonzy85** [comment]
> I encountered this error this morning, when trying to import and send a signed .psbt. In my watch only wallet I chose "send" then "import transaction"' however I got an error message when trying to import the signed .psbt file from my SD card.
> 
> I was however able to import the .txn file and then I broadcasted that from within my watch only wallet. This seems to have worked, however I am still waiting on confirmations of the transaction (as I set the fees to a minimum).
> 
> -phonz

I should probably add that I signed the .psbt using my coldcard.
