### ISSUE TITLE
Notifications pop up does not clear on devices without Google Services (100k sats bounty)

### ISSUE THREAD

**Issue by thenewbug** [BlueWallet/BlueWallet#1839]
The pop-up to enable notifications doesn't go away on my bluewallet. There are two options... ask me later, and turn on notifications

Turning on the notifications does nothing, because without google services, it can't turn on. The setting immediately returns to the off position. It will ask me the same question the next time I am sending funds.

Ask me later... just asks me again the next time I am sending funds also.

Please make a "No" button, that disables the query upon sending funds.

**Comment by Overtorment** [comment]
ack

**Comment by Overtorment** [comment]
@marcosrdz remind me, how do you check whether gms is available..?

**Comment by marcosrdz** [comment]
> @marcosrdz remind me, how do you check whether gms is available..?

Theres no current builtin way to verify with RN. There are some packages for it. We could run the app on an emulator or a device with no GMS and see what error message is returned.

**Comment by marcosrdz** [comment]
> > @marcosrdz remind me, how do you check whether gms is available..?
> 
> Theres no current builtin way to verify with RN. There are some packages for it. We could run the app on an emulator or a device with no GMS and see what error message is returned.

We can also add a "dont ask again" option

**Comment by thenewbug** [comment]
I would like to put a 100k sat bounty on this one. Not sure how to add the label myself!
