### ISSUE TITLE
“Set to blank to use default” doesn't work.

### ISSUE THREAD

**Issue by benflap** [BlueWallet/BlueWallet#1842]
My Electrum server uses the default ports (50001, 50002) but BlueWallet won’t connect without me putting those ports in manually.
My device is an Iphone running ios 14, This was also a problem with ios 13.x.

**Comment by Overtorment** [comment]
it assumes _all_ inputs are empty to use default

**Comment by benflap** [comment]
That doesn't seem very useful if the only users that can use it are the ones with an Electrum server with the ip address of 111.222.333.111.

**Comment by Overtorment** [comment]
could pls you elaborate on this one?

**Comment by benflap** [comment]
In settings > Network > ‘Electrum server’ there is a form with three inputs.
- host
- TCP port
- SSL port

Above this form there is a line that says “Set to blank to use default”. The host input has the placeholder “host, for example 111.222.333.111”. So I assume the default is `111.222.333.111`.
The host input having a default isn’t useful because everyone’s Electrum server has a different IP address. What is useful is being able to leave the TCP port and SSL port inputs empty and just filling in the IP address of the Electrum server

**Comment by benflap** [comment]
I just checked what happens when I leave everything empty and now see that it sets the Electrum server back to what it is when the app is first opened up. I guess I just misunderstood.
