### ISSUE TITLE
Ability to connect to own Lighting node

### ISSUE THREAD

**Issue by plengkeek** [BlueWallet/BlueWallet#188]
Feature request: ability to connect to your own Lighting node using gRPC and macaroons.

It would be really nice to be able to connect to your own Lighting node using gRPC and macaroons besides the lnhub implementation. This would put this app as the number 1 for mobile lightning wallet.

**Comment by Overtorment** [comment]
We would love to, but at the moment we are a bit short-handed.
Will be done eventually.

**Comment by plengkeek** [comment]
No worries, unfortunately I don't know JavaScript but appreciate the work and I see great potential.
