### ISSUE TITLE
e2e: investigate why camera backdoor test always fails on githubactions but not on travis

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#1885]
and fix.

test is `can import zpub as watch-only and create PSBT` and it fails with weir errors somewhere around camera stuff

**Comment by Overtorment** [comment]
currently muted on github

**Comment by Overtorment** [comment]
@limpbrains remind me, we solved it somehow for github actions..?

**Comment by limpbrains** [comment]
I disabled camera for github actions here https://github.com/BlueWallet/BlueWallet/pull/2100
I don't remember why

**Comment by Overtorment** [comment]
oh right! because it was eating cp and tests were failing. and now they are fine, right?
closing this
