### ISSUE TITLE
Send screen freezes

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#1887]
Probably related with the fee calculations on the background. Sometimes the send screen freezes

![photo_2020-09-21_10-44-06](https://user-images.githubusercontent.com/1238429/93747732-664c6d00-fbf7-11ea-9ca1-5de16539ba14.jpg)

**Comment by Overtorment** [comment]
anything on sentry..?

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/issues/1945

**Comment by Overtorment** [comment]
should be fixed by https://github.com/BlueWallet/BlueWallet/pull/1949
