### ISSUE TITLE
Connect to Electrum via QR code

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#1889]

**Comment by Overtorment** [comment]
also, maybe some deeplinking scheme so BW could open it and instantly throw dialogue "are you sure you want to use this electrum server?" and so It could be scannable straight from main screen (we have large SCAN QR button there)

**Comment by thenewbug** [comment]
> also, maybe some deeplinking scheme so BW could open it and instantly throw dialogue "are you sure you want to use this electrum server?" and so It could be scannable straight from main screen (we have large SCAN QR button there)

A good note to think about for the scan button... it is preferable for privacy to connect to a custom node BEFORE creating a fresh new wallet, and prior to any wallets being created on the main screen, there is no scan button in the main menu

Maybe make a button to the deeplinked scan function in the threedot-dropdown for "Import Node Config"

![16007266187286226933982685688059](https://user-images.githubusercontent.com/14336691/93827150-8c850380-fc1d-11ea-84fc-9e756b7d6dfe.jpg)
