### ISSUE TITLE
Currency New Taiwan Dollar - Missing (NT) before $ sign

### ISSUE THREAD

**Issue by B369** [BlueWallet/BlueWallet#1890]
Please have a look at the attached screenshots. I did mark the issue and attached some screenshots of Wallet of Satoshi as a reference example. Should be pretty clear after seeing it. 
When you change the currency to TWD ( Taiwan Dollar) it's very confusing if you only see the $ sign. Taiwanese use US dollar here as well, therefore they add NT before the dollar sign. NT$ . The N stands for New Taiwan Dollar.
![bluewallet_shot_1_incorrect](https://user-images.githubusercontent.com/33085281/93857426-22d42a80-fced-11ea-8136-64b4f485f285.jpg)
![bluewallet_shot_2_correct](https://user-images.githubusercontent.com/33085281/93857434-25368480-fced-11ea-97cf-cc4a70597060.jpg)
![ww_example_shot_1_correct](https://user-images.githubusercontent.com/33085281/93857443-2667b180-fced-11ea-8966-c92ee6016e3f.jpg)
![ww_example_shot_2_0_correct](https://user-images.githubusercontent.com/33085281/93857448-27004800-fced-11ea-8ae8-1f51cac0223d.jpg)
![ww_example_shot_2_1_correct](https://user-images.githubusercontent.com/33085281/93857450-28317500-fced-11ea-980b-134210fd179e.jpg)

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/1894
