### ISSUE TITLE
failed to decode simple address from URL scheme?

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#190]
bitcoin:36JxaUrpDzkEerkTf1FzwHNE1Hb7cCjgJV

![1f18a138-94ad-44e9-9162-a80a6ee1291e](https://user-images.githubusercontent.com/1238429/50576159-3d70bc80-0e03-11e9-83f3-26c4900b0a57.png)

**Comment by pajasevi** [comment]
@ncoelho Was that scanned QR or clicked link?

**Comment by ncoelho** [comment]
@pajasevi link, maybe I did something wrong, but doesn't look like...

`<a href="bitcoin:36JxaUrpDzkEerkTf1FzwHNE1Hb7cCjgJV">36JxaUrpDzkEerkTf1FzwHNE1Hb7cCjgJV</a>`

**Comment by pajasevi** [comment]
[bitcoin:36JxaUrpDzkEerkTf1FzwHNE1Hb7cCjgJV](bitcoin:36JxaUrpDzkEerkTf1FzwHNE1Hb7cCjgJV) Link for testing purposes

**Comment by marcosrdz** [comment]
Fixed: 39deff924e8e0c9a8cd1674d02302dac44832190
