### ISSUE TITLE
e2e: test bip84 batch send

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#1904]
can be part of `can import BIP84 mnemonic, fetch balance & transactions, then create a transaction` test as it already tests sendMax

**Comment by limpbrains** [comment]
@Overtorment Do you think this scenario will be enough?

* open send screen
* add 3 outputs
* scroll to second and remove it
* make sure 1 and 2 hasn't been changed
* create tx, make sure there are 2 outputs
* go back
* use send MAX on the one output
* create tx, make sure it has one output

**Comment by Overtorment** [comment]
lgtm. i like paretto rule when writing tests, 20% efforts will bring 80% results, otherwise you end up chasing 100% coverage
make all outputs in batch different amounts so its easier to check them
