### ISSUE TITLE
Wrong android effect transition

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#1914]
After upgrading from v3 to v5, every Stack navigator in my app seems to have a strange animation and I'm not able to change. Tried following the docs but it always shows the same animation - video below.

https://imgur.com/Btv1dPh

https://github.com/react-navigation/react-navigation/issues/7775#issuecomment-602217370
https://github.com/NMF-earth/nmf-app/pull/152

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/1918
