### ISSUE TITLE
Bluewallet Bitcoin price widget content overlap

### ISSUE THREAD

**Issue by Abhishek12345679** [BlueWallet/BlueWallet#1925]
- ![image](https://user-images.githubusercontent.com/24722640/94254466-72606380-ff44-11ea-95b9-d0ed3d657abe.jpeg)

**Comment by eyal352** [comment]
I’d like to take this

**Comment by Abhishek12345679** [comment]
@eyal352  take what?

**Comment by Overtorment** [comment]
@eyal352  if you think you can fix this - great! please do

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/1935
