### ISSUE TITLE
Writing numbers standards 

### ISSUE THREAD

**Issue by klauslovgreen** [BlueWallet/BlueWallet#194]
Please consider using easier to read format for lightning (or large numbers in general like USD, BTC etc.)

Examples:
1,054,000 sats or maybe 1 054 000 sats
$417,592.21

https://www.grammarbook.com/numbers/numbers.asp
Or use similar standards.

Also - negative numbers (outgoings) are in bold black - perhaps red color would be more meaningful?

**Comment by klauslovgreen** [comment]
It would also look nice be more consistent with the same amount of digits after the decimal point in BTC

Incoming amounts right now are pretty random - I see for example:

0.02
0.247

but outgoing are all 8 digits after the decimal point:
-0.02105038
-0.20004438

**Comment by Overtorment** [comment]
spaces make sense. meaningless zero digits mathematically dont: `0.02000000`

**Comment by ncoelho** [comment]
There's still a bug here:

Happens:
1 000,000

Should happen:
1 000 000

cc @marcosrdz

**Comment by klauslovgreen** [comment]
I see no spaces at all in the lightning wallet 3.5.5

**Comment by marcosrdz** [comment]
3035747af3b29cf0fae57ed47276ab3c7256eb18
