### ISSUE TITLE
Allow user to issue new (onchain) addresses before the current one is used

### ISSUE THREAD

**Issue by dimaatmelodromru** [BlueWallet/BlueWallet#1941]
When I want 2+ people to pay me and I don't want them to know the amount of each other's payment it becomes complicated...

**Comment by Overtorment** [comment]
We have this on our TODO:  https://github.com/BlueWallet/BlueWallet/issues/990
basically, you'll be able to see a list of your addresses in HD wallet, and quickly copy-paste unused ones
