### ISSUE TITLE
Beta: 3.50 Cannot click on Lightning transactions

### ISSUE THREAD

**Issue by klauslovgreen** [BlueWallet/BlueWallet#196]
I am unable to click on any Lightning transaction to get detailed information (like with BTC wallet).

Secondly, when making an invoice you are able to click to see the invoice if you are in the Lightning Wallet only - not from the general transaction overview.

**Comment by klauslovgreen** [comment]
Yes that works - but no details, just this invoice has been paid. Would be nice to see the full description of the transaction at least, time stamp of the transaction etc - or a link to a block-explorer for more info?

**Comment by klauslovgreen** [comment]
Would be nice to get output like what is available via:
https://lndecode.com

- or a link to that

**Comment by Overtorment** [comment]
TBD

**Comment by marcosrdz** [comment]
Ability to tap on an invoice from the main screen: 6eb8dbfeca4d237ce5d95e2c5ad1436bb698957c
