### ISSUE TITLE
Weird "Pay" button when opening a lightning invoice in wallet

### ISSUE THREAD

**Issue by ViktorBohu** [BlueWallet/BlueWallet#1969]
![image](https://user-images.githubusercontent.com/18405140/95663908-6b8c4000-0b43-11eb-8755-5e720e7673b3.jpeg)

**Comment by ViktorBohu** [comment]
Button itself works fine only looks weird

**Comment by marcosrdz** [comment]
Fixed.

**Comment by marcosrdz** [comment]
Thanks for reporting!
