### ISSUE TITLE
Beta 3.50 Ability to delete (swipe) an expired invoice in Lightning

### ISSUE THREAD

**Issue by klauslovgreen** [BlueWallet/BlueWallet#199]
Please consider the ability to swipe to delete/hide expired invoices

**Comment by Overtorment** [comment]
I think we'll make expired invoices disappear after 24h of expiration or similar

**Comment by Overtorment** [comment]
is it a good idea to hide them after 24hrs..?
this can be done server-side

**Comment by klauslovgreen** [comment]
Perhaps even shorter / what is the rationale for keeping it after it has expired?
