### ISSUE TITLE
Want to activate transifex's glossary function

### ISSUE THREAD

**Issue by awesome-doge** [BlueWallet/BlueWallet#1995]
Hello, I want to participate in translation Chinese (Taiwan)
In order to improve the speed of my translation and the consistency of words, I hope you can activate the glossary function of transifex.

**Comment by ncoelho** [comment]
Let's see if we can do this. I just created an empty glossary file and added it to the project. Let me know if it is working of something else is needed.

**Comment by awesome-doge** [comment]
Thanks for your assistance
You have solved my problem
