### ISSUE TITLE
Ability to set fiat amount to send/receive

### ISSUE THREAD

**Issue by Astro92** [BlueWallet/BlueWallet#200]
Currently amount sent/received is only a BTC quantity and a calculated fiat equivalent, it would be nice to do the opposite, especially for on-boarding friends and family.

**Comment by marcosrdz** [comment]
This is planned for a future release.

**Comment by Overtorment** [comment]
@marcosrdz I think we now have a separate component for amounts import. @ncoelho has some sketches on how it should work. if I remmeber correctly,  there should be arrows on the side, upon clicking which  both local currency amoun & btc amount swap places (maybe with some nice animation)

**Comment by rafaelpac** [comment]
This is a feature I would like to use. But I am kind of lost here with git stuff... How could I help? The design of Wallet of Satoshi is nice, a double arrow to the side of the values that let them be swapped.

**Comment by marcosrdz** [comment]
Implemented.
