### ISSUE TITLE
seed not working

### ISSUE THREAD

**Issue by shamir11** [BlueWallet/BlueWallet#2002]
Hey
im using bluewallet for my iphone and want  to access it on my pc.

I have the 24 seed phrase, but when i try to import it to my pc with electrum it wont let me continue

I have checked so many times that i did not have any typos etc, what can i do? i have no access to that wallet and I know that with the seed phrase i should be able to restore it...
what can possibly be the reason?

**Comment by ncoelho** [comment]
Hi there, what is the error exactly?

Electrum shows the words when you are typing them, so no big chances of typos.

Make sure you are on the right place to import a wallet.

New > Standard wallet > I already have a seed > options > bip39

**Comment by shamir11** [comment]
first and foremost thanks for the fast reply!

I have been able to get it but it still won't work on my bluewallet app lol, the passphrase works on electrum but not bluewallet.

Oh wow, you just saved me !!

**Comment by shamir11** [comment]
now its working lol
