### ISSUE TITLE
electrum personal server

### ISSUE THREAD

**Issue by fewsats** [BlueWallet/BlueWallet#2009]
Hi, I see you host 3 instances of eps.
I'd like to host one myself to use with my wallets.

I know I could use a raspberrypi or the likes but I was wondering if your server configuration and deployment script is public somewhere.

Which VPS do you use?

Thanks

**Comment by Overtorment** [comment]
to be precise, we use electrumX, not EPS.
heres the config: https://github.com/BlueWallet/ops/blob/master/run_scripts/run-electrum.sh
at least one of our electrums is hosted on digitalocean, but its a bit pricey. the other ones I dont remember

**Comment by fewsats** [comment]
ok, do you have any vps seller to recommend?

**Comment by Overtorment** [comment]
not really
