### ISSUE TITLE
Investigate rust-lightning

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#202]
Investigate rust-lightning library for a possible integration in the future.

> The goal is to provide a full-featured but also incredibly flexible lightning implementation, allowing the user to decide how they wish to use it. 

https://github.com/rust-bitcoin/rust-lightning

**Comment by Overtorment** [comment]
I dont see how we can integrate rust sources with our RN app.
There are options if it were java/objC/swift, we could build a RN bridge for that...

**Comment by TheBlueMatt** [comment]
You could bridge it by compiling with wasm and then calling over the bridge there (not sure if React Native supports wasm or not) or by compiling with a C wrapper. I've got a C wrapper partially written but not done yet, but its not too hard to write a C wrapper in Rust.
