### ISSUE TITLE
question on UTXO

### ISSUE THREAD

**Issue by fewsats** [BlueWallet/BlueWallet#2030]
Hi,
looking at the code 
https://github.com/BlueWallet/BlueWallet/blob/master/blue_modules/BlueElectrum.js#L295

I can't figured out how UTXO are fetched in case the `disableBatching` flag is true (for instance if I use electrs connected to an own node)

Thanks

**Comment by Overtorment** [comment]
theres code in Wallet class, that if we could not fetch utxo - derive it from wallet transactions (`getDerivedUtxoFromOurTransaction()`)

**Comment by fewsats** [comment]
@Overtorment thanks for the clarification.
Considering you can extract UTXOs from TXs, is there any reason why you do not always do it, but you rely on the server call in case batching is supported?

thanks

**Comment by Overtorment** [comment]
the reason is that when I was implementing it I wasnt thinking about it. I saw electrum call and thought 'okay Ill use it', and only thought about extracting utxo from transactions  when I was adding support for EPS/electrs (EPS just doesnt support listunspent call)
