### ISSUE TITLE
Scroll down in My Contracts

### ISSUE THREAD

**Issue by Delvis** [BlueWallet/BlueWallet#2037]
Greetings everyone. I am using the app on IOS and i's updated. I just noticed it seems to be impossible to scroll down in hodlhodl My Contracts. So I cannot see my most recent contracts now that they fill the whole screen.

Also I'd recommend that the order presenting contracts should be inverted, i.e. most recent contracts appearing first. Makes more sense for usability IMHO.

Best,
J

**Comment by Overtorment** [comment]
acknowledged. will fix

**Comment by Delvis** [comment]
Thanks Overtorment. 👍
