### ISSUE TITLE
iOS app stuck on loading screen....

### ISSUE THREAD

**Issue by A-Zak** [BlueWallet/BlueWallet#205]
Hi,

I've downloaded the app, created a new wallet, and now when I open it, it shows me the security alert about the wallets in version 3.1 or below, but when I dismiss it, it's just stuck on a white screen with an activity indicator... /:

I tried opening the app on wifi, 4g and in airplane mode.
I've also tried dismissing the security alert with both option, none of which worked...

Not sure if relevant, but I did change the lightening node to `142.93.124.241:9735`

Please help.

**Comment by Overtorment** [comment]
My guess that it hangs trying to connect. Give it some time, like 1-2 mins.
Also, direct ip of your node wont work, you first have to install https://github.com/BlueWallet/LndHub and put a link to your lndhub in settings.
LMK.

**Comment by A-Zak** [comment]
Hey @Overtorment, Thank for the quick reply :)
I've got the app running in this white screen mode for the past 12 minutes now, and it doesn't seem to go anywhere... :/
Any other ideas of what could be going on? 🤞

**Comment by Overtorment** [comment]
Well that looks like a crash, but I'm not seeing any crash reports for the last several hours, so thats confusing.
I also could not reproduce that not on my iphone not on my android.
Best option is to delete the app and reinstall it again, this clears internal data storage.

If you didnt encrypt the storage yet, you can even extract wallets data. @marcosrdz what was the tool you used to extract storage files when you connected your iphone to your mac..?

**Comment by ncoelho** [comment]
Any other things you have done?
- wallets imported?
- encryption activated?
- plausible deniability activated?
- Version of app and OS you are using?

**Comment by A-Zak** [comment]
Sure thing, although there isn't much going on there...
[](https://dsh.re/e73bf)

**Comment by marcosrdz** [comment]
Still happening with 3.7.0?

**Comment by Overtorment** [comment]
Okay, I was fixing it some time ago. This is happening because before drawing screen app tries to refresh wallet balance/txs, and if network request hangs - whole app gets stuck. I think fix made it to 3.7.2 build
