### ISSUE TITLE
Bad formatting on the amount (send view)

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#2061]
<img width="346" alt="Screenshot 2020-11-04 at 14 57 13" src="https://user-images.githubusercontent.com/1238429/98134933-8e4e1200-1ebf-11eb-9862-595c57d2237e.png">

**Comment by Overtorment** [comment]
I dont think this small amount is sendable currently in bitcoin due to minrelayfee

**Comment by Overtorment** [comment]
only reproduceable if user is sending  < 100 sat (multisig is onchain!)

![image](https://user-images.githubusercontent.com/1913337/101180570-a9897a00-3643-11eb-872a-05fda12e4e0d.png)

![Uploading image.png…]()

while its impossible to send less thatn 500-something
