### ISSUE TITLE
Quorum modal, not possible to go back

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#2069]
On android small devices

<img width="324" alt="Screenshot 2020-11-05 at 13 01 42" src="https://user-images.githubusercontent.com/1238429/98238725-205d2580-1f67-11eb-9c48-9b7effdb5ff7.png">

**Comment by Overtorment** [comment]
Back button isn’t working?

**Comment by marcosrdz** [comment]
Thats RN Modal. It doesnt listen to the back button. We should add a Confirmation button

**Comment by ncoelho** [comment]
Should be or a close button, top right close button maybe.
