### ISSUE TITLE
Add topup indication on wallet selection

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#207]
When the user has no wallets available to select for topup Lightning he can still reach the wallet selection screen.

Instead, if there are no wallet available to select, indicate to the user that we need a bitcoin wallet first with funds.\

"To be able to refill your wallet, you need a bitcoin wallet first with funds available."

**Comment by marcosrdz** [comment]
d112d24974fe7569f86f1902a60109f308a66ae0
