### ISSUE TITLE
Creating invoices is not working with bitcoins, just sats

### ISSUE THREAD

**Issue by diegotco** [BlueWallet/BlueWallet#2071]
Check the images below

![2020-11-05 09 20 09](https://user-images.githubusercontent.com/22822405/98260163-9aca7d00-1f48-11eb-8322-7f9d5c68e22d.jpg)

And

![2020-11-05 09 20 18](https://user-images.githubusercontent.com/22822405/98260075-7e2e4500-1f48-11eb-9991-9228e5a06ec7.jpg)

**Comment by ncoelho** [comment]
This is the same as the other issue right?

**Comment by diegotco** [comment]
Sorry, yes it was the same Nuno
