### ISSUE TITLE
An error happens when you create an invoice for 0.00004 BTC

### ISSUE THREAD

**Issue by diegotco** [BlueWallet/BlueWallet#2072]
Check the images below

![2020-11-05 09 20 09](https://user-images.githubusercontent.com/22822405/98260163-9aca7d00-1f48-11eb-8322-7f9d5c68e22d.jpg)

**It works well in SATS**

![2020-11-05 09 20 18](https://user-images.githubusercontent.com/22822405/98260075-7e2e4500-1f48-11eb-9991-9228e5a06ec7.jpg)

**Comment by marcosrdz** [comment]
The attached screenshot is in USD. Not BTC.

**Comment by diegotco** [comment]
Nice catch @marcosrdz, I get confused because the UI. Below says BTC, then you have to enter a USD amount :(
