### ISSUE TITLE
Disregarding curent denomination (sat/fiat) on send screen, scanning address always resets it to BTC

### ISSUE THREAD

**Issue by markmio** [BlueWallet/BlueWallet#2088]
1. On sending wallet, tap send
2. On sending wallet, enter amount: 100,000 sats
3. On receiving wallet, tap receive to view QR
4. On sending wallet, tap scan and scan the QR
5. On sending wallet, amount is changed to: 100,000 BTC

Could be nasty!

**Comment by Overtorment** [comment]
reproduced.
basically the problem boils down to: 
disregarding curent denomination (sat/fiat) on send screen, scanning address always resets it to BTC
