### ISSUE TITLE
BRD wallet import not getting full balance

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#2090]
Reported here:
https://t.me/bluewallet/31223

![photo_2020-11-08_15-38-58](https://user-images.githubusercontent.com/1238429/98467972-9fa56000-21d8-11eb-9989-c72d2294aaea.jpg)

**Comment by jarendy** [comment]
Just try few minutes ago. Still no changes.

**Comment by limpbrains** [comment]
I can confirm the issue exists. I've imported my BRD wallet into BW and got 0 balance. Also, history doesn't match

**Comment by Overtorment** [comment]
@limpbrains great youre in perfect position to debug 😂

**Comment by limpbrains** [comment]
@jarendy 
BlueWallet v5.6.7 was released today with improved BRD import. Can you please test it with your wallet?
