### ISSUE TITLE
Proper build icon 1024x1024

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#21]
Pls push proper icon to https://github.com/Overtorment/BlueWallet/blob/master/img/icon.png

**Comment by Overtorment** [comment]
there probably should not be any white

**Comment by Overtorment** [comment]
@ncoelho still needs some love, I hacked it really ugly 💩

**Comment by Overtorment** [comment]
@ncoelho still needs some love, I hacked it really ugly

**Comment by Overtorment** [comment]
@ncoelho still 💩💩💩💩

**Comment by Pythoniasm** [comment]
![icon](https://user-images.githubusercontent.com/26092465/54499785-ebc1d380-4915-11e9-9d1c-c2b3208c4c38.png)
