### ISSUE TITLE
Suggestion: Add latin-american fiat currencies to wallet

### ISSUE THREAD

**Issue by grunch** [BlueWallet/BlueWallet#2155]
Please add fiat currencies from Venezuela and Argentina.

It's important to let you know that Argentina and Venezuela have currency controls so we should't use APIs that shows the official rate cause is not the real one, I propose to use the api from this site which have the free market fiat currencies rate.

https://yadio.io/api.html

VES: https://api.yadio.io/rate/VES
ARS: https://api.yadio.io/rate/ARS

The usd field in each endpoint is the pair rate VESUSD, ARSUSD

Thanks

**Comment by ncoelho** [comment]
@marcosrdz if you don't mind I'm going to reopen this issue. The "real" on the field price rate seems interesting and important to try to make available.

**Comment by grunch** [comment]
thanks @ncoelho the rate is extremly important, without free market rate is not useful

**Comment by grunch** [comment]
and also this issue ask for adding venezuelan fiat currency but it wasnt added on the PR merged

**Comment by marcosrdz** [comment]
Yea it got closed automatically after the PR was merged. We currently don't have code for obtaining the rate outside of the current source. We would need to implement said functionality.

**Comment by marcosrdz** [comment]
Ok so both the app and widgets can now read from alternate sources. We just gotta confirm the key/value we need to read  for VES and ARS

**Comment by marcosrdz** [comment]
I used https://yadio.io/calc.html to verify data. Seems to be good to go.
