### ISSUE TITLE
Import of the file failed with a transaction-signed.

### ISSUE THREAD

**Issue by nievk** [BlueWallet/BlueWallet#2161]
There is import of the file that quote (signed transaction) is broken the wallet cannot do
the decode is to broadcast to the network, I need to copy to the hex-transaction and send
by Network/Broadcast.

**Comment by Overtorment** [comment]
what are exact steps to reproduce?

**Comment by nievk** [comment]
> what are exact steps to reproduce?

It may be that it does not recognize the file created by electrum, electrum exports a transaction signed in hexdecimal, basically I created an unsigned transaction, passed it to my pendrive and signed the transaction and exported it to the pendrive again, then put the pendrive is I imported the file into a blue-wallet, it seems that she tried to decode it but she couldn't, that is, it may be because electrum exports in hex instead of coding with base64.

**Comment by clonmac** [comment]
I'm also having issues broadcasting an imported signed transaction from a file. Not sure if it is related or the same issue here or not, but I figured I'd provide additional input. 

I use a ColdCard for signing. A friend of mine who is also using a ColdCard who I am walking through the process is having an issue broadcasting his signed .txn file as well. My BlueWallet is connected to my Electrum Personal Server and when I go to broadcast the imported transaction it actually crashed my EPS and BlueWallet gives me an "Alert: Close Connect" error. I then need to restart my EPS.

For my friend who isn't using his own Electrum server (just connected to BlueWallet's electrum server), when he goes to broadcast, he gets an alert that says "Alert: the transaction was rejected by the network rules. TX Decode failed".

He sent me his hex encoded transaction that BlueWallet presented to him prior to broadcast and I was able to decode it just fine in another app.

I used to have no problems signing BlueWallet transactions with my ColdCard wallet and then broadcasting them out with Bluewallet with the same setup I am using now. I am not sure when it stopped working however as I don't send transactions often from cold storage. It seems like the last transaction I sent from my ColdCard with Bluewallet was about 3 months ago.

**Comment by Overtorment** [comment]
roger that, Ill get my coldcard from a box and will try to do a transaction

**Comment by Overtorment** [comment]
figured it out. 
*.txn files from coldcard have extra newline characters, so network could not recognize txhex, while it all looked correct manually copypasting and verifying.

however, everything would have worked great if you inported '-signed.psbt'  file instead.

anyways, wix is on the way and will be our with next release (~monday)

**Comment by clonmac** [comment]
Great. I had a feeling it was something like that. I did see that newline at the end, but for some reason BlueWallet or my phone wasn't allowing me to edit that encoded transaction field to get rid of it. Appreciate the quick turn around. I didn't think to try importing the -signed.psbt file.
