### ISSUE TITLE
[question] unconfirmed balances

### ISSUE THREAD

**Issue by vesparny** [BlueWallet/BlueWallet#2168]
Hi,

I see in the code you have
```js
  getUnconfirmedBalance() {
    let ret = 0;
    for (const bal of Object.values(this._balances_by_external_index)) {
      ret += bal.u;
    }
    for (const bal of Object.values(this._balances_by_internal_index)) {
      ret += bal.u;
    }
    return ret;
  }
```

when you call `getBalance()` there is a check to see if the unconfirmed balance is negative (I guess in the case there are pending outgoing transactions).

I checked the `fetchBalance()` logic but I couldn't understand when you convert unconfirmed balances to a negative number. I assume the balances are alway returned as positive integers right?

thanks

thanks

**Comment by Overtorment** [comment]
I dont really remember, but I think negative amounts are returned by electrum server

**Comment by vesparny** [comment]
uhm I am not sure, I will check but if I remember correctly balances, both confirmed and unconfirmed, are always returned as positive integers
