### ISSUE TITLE
Modal on multisig seed

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#2176]
The transparent background is not showing up. Only on this modal, works in the others

![image](https://user-images.githubusercontent.com/1238429/99884670-46a1e700-2c30-11eb-8e64-da06e6ad1954.png)

**Comment by marcosrdz** [comment]
![Screenshot_1606700134](https://user-images.githubusercontent.com/4793122/100560014-72e9e300-3282-11eb-9c77-eca882452da6.png)
 works for me. might've been fixed already on bottommodal

**Comment by ncoelho** [comment]
Still happens on latest version

**Comment by marcosrdz** [comment]
<img width="381" alt="Screen Shot 2020-12-04 at 10 43 40 PM" src="https://user-images.githubusercontent.com/4793122/101232833-2afffd00-3682-11eb-8e95-32955c861921.png">

This is what Im seeing.
