### ISSUE TITLE
Android doesnt have decimal when refiling LN wallet

### ISSUE THREAD

**Issue by AltQuest** [BlueWallet/BlueWallet#219]
I was trying to refill my LN from SegWit and it wouldnt let me type a decimal "." For the amount to send. Luckily I was able to write it off app somewhere else and paste it in. But that's a minor annoyance. Standard keyboard + system nothing fancy.

Thanks @bitcoinjake09

**Comment by Overtorment** [comment]
Acknowledged

**Comment by marcosrdz** [comment]
Does it still occur in 3.5.6?
