### ISSUE TITLE
Would be great to be able to pay to a photo of a QR code

### ISSUE THREAD

**Issue by gilescope** [BlueWallet/BlueWallet#220]
I get given a photo of a QR code and I'm like what can I do with that?

Great wallets you can probably paste in a copied photo and it will find the qr code in it. (or have a select from photos button)

It really does happen all the time.. would be a great usability improvement - important but not urgent.

**Comment by Overtorment** [comment]
Makes sense. Thanks for a suggestion!

**Comment by charltonh** [comment]
I've noticed on android there's a button to scan the QR code, which launches a camera screen, but it doesn't seem to work at the moment.  Nor is there any red markings to line the QR code up with on the camera screen.  I take it this is underway?
I've currently tested BlueWallet with my site at mex.dynet.com, and it works!  But I must copy and paste the ln invoice into the tiny box and cannot scan the QR code at the moment.

**Comment by Overtorment** [comment]
Strange, I fixed unscannable QRs in https://github.com/BlueWallet/BlueWallet/issues/235#issuecomment-453504615
Maybe google play release not propagated or smth

**Comment by charltonh** [comment]
I just retested since the update, and they do work now.  :-)
I think most people expect something like red brackets to know where to line the QR code up with though.

**Comment by Overtorment** [comment]
Valid point.
@ncoelho UX wise, we should add it, I guess..?

**Comment by marcosrdz** [comment]
389188593014093888b76d7b34f0cf333571dcb4
