### ISSUE TITLE
Feature request: BIP39 seed extension support

### ISSUE THREAD

**Issue by AllienWorks** [BlueWallet/BlueWallet#2212]
Feature request for supporting BIP38 passphrase encryption.

I would like to recover my wallet from 3rd party, which is BIP38 encrypted. I know it's possible via Ian Coleman's tool, but I'm not comfortable using that.

Could we get BIP38 support in BlueWallet?

**Comment by Overtorment** [comment]
BIP38 for single-address (backups starting with `6P`) is supported.
Encrypted mnemonc seeds are not yet supported.

**Comment by Overtorment** [comment]
Did you mean "BIP39 seed extension" ?

![image](https://user-images.githubusercontent.com/1913337/100360445-de1c8680-2ff0-11eb-9db7-250eaccf9aa1.png)

**Comment by AllienWorks** [comment]
Oh yes, my bad. BIP39 it is.

**Comment by thenewbug** [comment]
It would also be awesome if "advanced mode" in settings enabled an input box for custom derivation paths when importing a seed (for people restoring from odd wallets like Samourai or Bisq or Ledger)

**Comment by Overtorment** [comment]
related #2240

**Comment by yoshimo** [comment]
> 
> 
> It would also be awesome if "advanced mode" in settings enabled an input box for custom derivation paths when importing a seed (for people restoring from odd wallets like Samourai or Bisq or Ledger)

Looking at Bisq you should be careful and mark bisqs bsq colored coins as "do not spend" in such a case, to avoid problems with their reduced fee "token".

**Comment by rjakobsson** [comment]
Really interested in BlueWallet supporting this, do you have any thoughts on design (when to enter passphrase / which screen)? Could we support this in steps, or do we need to at _the same time_,  also support importing wallets which seed contains a passphrase?

**Comment by godSaysHODL** [comment]
> Really interested in BlueWallet supporting this, do you have any thoughts on design (when to enter passphrase / which screen)? Could we support this in steps, or do we need to at _the same time_, also support importing wallets which seed contains a passphrase? I'm interested in having a go at this feature.

There is a design mockup on #2240

**Comment by carlosmassa** [comment]
Adding this feature would make Bluewallet just perfect!

**Comment by Overtorment** [comment]
its being worked on in https://github.com/BlueWallet/BlueWallet/pull/3157

**Comment by carlosmassa** [comment]
Greats news! Can't wait to test this new functionality. When is it planned to be released?

**Comment by Overtorment** [comment]
@limpbrains i belive that was delivered recently?

**Comment by limpbrains** [comment]
Yes
