### ISSUE TITLE
Cannot scan lnurl-withdraw QR code from wallet->send/receive->scan 

### ISSUE THREAD

**Issue by moonshot75** [BlueWallet/BlueWallet#2213]
Occurs on both Android and iOS when using the "Scan" button to scan an lnurl-withdraw QR code within a wallet after selecting "Receive" or "Send". 

"Scan" from the homescreen works fine.

![cc2b4ccc-c6e1-4ee0-8133-2aa224a84f46](https://user-images.githubusercontent.com/66482965/100360033-add8e600-2ff8-11eb-9db4-00e93294d9d4.jpg)

Tested in version 5.6.6.

**Comment by Overtorment** [comment]
could not reproduce. tested with telegram ntxbot. 
worked great for me.
might have been a temporary lnd node downtime.

**Comment by moonshot75** [comment]
Only happens when scanning the QR, not when pasting the lnurl.

**Comment by ncoelho** [comment]
Just tested, works for me. Maybe you can give more information? Which
service are you using, and which are the steps to reproduce.

Here’s one if you wanna try
https://lightning.gifts/redeem/fab54975a9e9d457fbc9900f55e226197a9dc04f5bc84517

**Comment by moonshot75** [comment]
This one also worked for me. I'll DM a (LNPay) QR that reproduces the problem here.

**Comment by godSaysHODL** [comment]
I also had this issue while using an LNurl withdraw from lnbits

**Comment by arcbtc** [comment]
Investigating here:
https://github.com/lnbits/lnbits/issues/130
