### ISSUE TITLE
Non electrumX gives error on building transaction

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#2229]
![photo_2020-11-30_10-53-03](https://user-images.githubusercontent.com/1238429/100594647-3fe33600-32fa-11eb-9f23-14860119b652.jpg)

**Comment by thenewbug** [comment]
Might be able to close this if this was the issue from last night 

It appears to be working with my electrs on myNode now with latest build from this fix:
https://github.com/BlueWallet/BlueWallet/pull/2232

Thank you both for looking into this last night

**Comment by Overtorment** [comment]
yep, should be fixed in https://github.com/BlueWallet/BlueWallet/pull/2232
will be out in nearest release
