### ISSUE TITLE
One PK, two wallets problem

### ISSUE THREAD

**Issue by tdjastrzebski** [BlueWallet/BlueWallet#223]
Hi, I created two wallets using **the same PK**, using Electrum (P2PKH) and Bitcoin Core (P2SH), each wallet with one address.  Both addresses have some small money.
When I import wallet and enter my PK by scanning QR Code only the first (legacy) wallet with one address gets created. How do I import the other one?

**Comment by Overtorment** [comment]
This is by design. Bluewallet takes PK, and tries to check transactions against all possible shemes. The first one that has transactions is picked.
This is quite rare case, so I didnt add any workaround to add _the_other_scheme_ which also has some money.

**Comment by tdjastrzebski** [comment]
:/
