### ISSUE TITLE
Can't paste in address block while building tx (10k Sat bounty)

### ISSUE THREAD

**Issue by takeeatback** [BlueWallet/BlueWallet#2234]
Android -- Tried on multiple grapheneOS phones, and one samsung galaxy. 

10k sat bounty if you can fix this

Tap and Hold pasting doesn't work in address block, but for some reason works in note to self block.

![screen-20201130-0903231](https://user-images.githubusercontent.com/65305927/100640931-c47a8800-32eb-11eb-8b69-101c93dba339.gif)

**Comment by marcosrdz** [comment]
Thanks for reporting!

**Comment by thenewbug** [comment]
> Thanks for reporting!

Thanks for quick fix. paste an invoice for 10k sats on lightning please here or in twitter DM to @godsaysHODL :)
