### ISSUE TITLE
Can't create a Lightning Wallet 3.5.6 (223)

### ISSUE THREAD

**Issue by klauslovgreen** [BlueWallet/BlueWallet#224]
Can't click the Lightning wallet option at all

![img_0661 2](https://user-images.githubusercontent.com/9731754/50898405-6995ca00-140f-11e9-958a-4e76232fecec.png)

**Comment by Overtorment** [comment]
You probably already have an LN wallet. We have a limitation of 1 wallet at any time.
Maybe its time we remove this limitation...

**Comment by klauslovgreen** [comment]
Yes correct I have one Lightning wallet already. Either remove the limitation or explain it somehow.

**Comment by marcosrdz** [comment]
204e4ba867324ae9ba129f3b9c00140cd70198e0
