### ISSUE TITLE
Shareable LNDhub Payment links (.2 BTC Bounty)

### ISSUE THREAD

**Issue by godSaysHODL** [BlueWallet/BlueWallet#2241]
see the LNDhub issue for a more in depth description. https://github.com/BlueWallet/LndHub/issues/119

The in-app feature proposal is sketched in this picture below. 

![new](https://user-images.githubusercontent.com/14336691/100728641-ac9f1480-337c-11eb-8595-dc846a8d442b.png)

Imagine that on LNDhub, an account could request to make a 'payment link' from any LNurl withdrawal invoice that's been created. they could share that link and it could be accessed from whatever LNDhub they are connected to.

if this was done on the default instance, it could look like this -> LNDhub.io/withdraw/invoicenumber when the request was made. Sharing this link, would open a browser page where the LNURL withdrawal invoice could be scanned or linked into a button for bluewallet users. On this page there should also be a link to download Bluewallet if you don't have any bitcoin wallet that is LNurl compatible. The payment link will have an expiration date on the server which is listed in the text of the shared message. If the payment link expires or is canceled, the sats are returned to the original account owner.

This would be an incredible onboarding opportunity as well as a way to send a Bitcoin payment through any normal messaging app.

**Comment by thenewbug** [comment]
here is a poor mockup of a payment page

![desktop](https://user-images.githubusercontent.com/14336691/100733645-55507280-3383-11eb-92df-dc3699688201.png)

**Comment by Overtorment** [comment]
its a bit similar to sat2.io except sat2 doesnt support lnurl yet, only webln

**Comment by Overtorment** [comment]
and its hardwired to send SMS

**Comment by godSaysHODL** [comment]
> its a bit similar to https://sat2.io except sat2 doesnt support lnurl yet, only webln

Yes!!! Exactly. I had no idea sat2.io existed. But the landing page for it is EXACTLY like what I was thinking. It'd be amazing if that process was hosted on LNDhub so the sats never have to move unless claimed, and so a sending process could be integrated directly into Bluewallet with payment links to share with any messaging app

**Comment by NilByte** [comment]
You can do this with https://github.com/lnbits/lnbits

https://lnbits.com/

They also have an extension that let's you import wallet to BlueWallet.

**Comment by godSaysHODL** [comment]
I have LNbits on my node. It's withdrawal feature hasn't worked at all for me with bluewallet, (try the qr in the example, because it was literally made from LNbits lol) and the whole point of this feature would be to create sharable links from within the wallet and and lndhub backend. We shouldn't have to have multiple apps or know about random websites.

It's unfortunate that the BCASH shitcoiners have working implementations of this on their wallets but bitcoiners do not

https://twitter.com/HelloDavidBond/status/1332419995893166080?s=20

**Comment by alijamali2000** [comment]
🙂

**Comment by godSaysHODL** [comment]
There will be more to the payment link side of this, but this is the basic spec for UI implementation of LNurlWithdrawal creation. I currently have one person I'm communicating with who is working on the Backend LNDhub part. If you wish to help out with UI part, you can join our Signal chat with [this link](https://signal.group/#CjQKIGz6Gyak9XCEoTPmvNlGxJIPwYzosuQ54tMLVbjqivKLEhBUoudQVFuXZJZVog-XWHZw)

![image](https://user-images.githubusercontent.com/14336691/107127202-6036f000-6869-11eb-94dc-1b4303a1c6ab.png)

**Comment by kiwiidb** [comment]
I've created a draft PR that will deal with the server-side implementation of this: https://github.com/BlueWallet/LndHub/pull/324 . Would be awesome to have some feedback on the technical side, scope and the TODO's.

Is the Bluewallet team still open to adding this kind of feature to LNDHub? It has been some time and I saw that support has been added for shutting LNDHub down, so it might be that the focus has been elsewhere (on-device LN wallet with LDK for example).

**Comment by godSaysHODL** [comment]
I'm super excited to see you working on this. Your draft looks awesome. Would love to hear what the Bluewallet team says also. Hoping LNDhub doesn't go away completely, I still use it all the time on my node 🤝

I am still definitely going to pay out this bounty if we can get all the goals achieved and put in Bluewallet 🙌
