### ISSUE TITLE
Lebanese Pound - LBP API

### ISSUE THREAD

**Issue by marcondy** [BlueWallet/BlueWallet#2245]
The true LBP rate per 1 USD dollar is represented by "buy":

The price of 1 BTC in LBP would be ,  1 BTC = USD x LBP at the buy price.

https://fluus.me/wp-json/wcra/v1/lbprates/?secret_key=scQEXwNnL9d4tDrViepAWdZeqcx7WuQw

**Comment by marcondy** [comment]
Thanks ! However the price displayed is now the "official fixed" bank rate,not the correct one as per marker demand

**Comment by ncoelho** [comment]
@marcosrdz not coindesk, see if we can use this

https://fluus.me/wp-json/wcra/v1/lbprates/?secret_key=scQEXwNnL9d4tDrViepAWdZeqcx7WuQw

**Comment by marcosrdz** [comment]
> Thanks ! However the price displayed is now the "official fixed" bank rate,not the correct one as per marker demand 

The provided link has a key. It can be revoked at any time and/or used for tracking. 
Is there an alternative source that is fully public without the need for an api key?

**Comment by marcondy** [comment]
These are other links that provide price :

http://www.businessnews.com.lb/

https://lirarate.com/

https://www.the961.com/lira-rate/

**Comment by marcosrdz** [comment]
They don't appear to be APIs that can be used without a key.

**Comment by marcondy** [comment]
Understood, that is the best I could come up with, the initial API is what I was able to get through our bitcoin community. I will keep looking

**Comment by Overtorment** [comment]
i see an opportunity here for someone to create an api and provide for everyone to use :-)

**Comment by marcondy** [comment]
https://bitcoinduliban.org/api.php?key=lbpusd

@Overtorment I requested to build an API, it uses average from 3 different sources and is hosted on our community website

**Comment by marcondy** [comment]
@marcosrdz is this a better api?

**Comment by marcosrdz** [comment]
Code change had to be implemented to handle the response time from the API. It's pending review. Once it's merged, another PR (already available) will be reviewed. The latter PR will allow BlueWallet to obtain the rate from the provided API.
