### ISSUE TITLE
Lightning balance/fees don't add up

### ISSUE THREAD

**Issue by plengkeek** [BlueWallet/BlueWallet#225]
I have my own lighting node and today decided to test the BlueWallet implementation and found some weird behavior. 

- The balance does not add up when looking at the transactions (see screenshot)
- The fees from BlueWallet to my node are 3 sat for 10 sat payment and 12 sat for 10000 sat payment but when I send funds from my node to BlueWallet it uses 4 hops and only 1 sat fee so why are the fees so much higher for BlueWallet?
- Some transaction details would be nice, not sure if this has been asked for before.

![screenshot_20190109-133635](https://user-images.githubusercontent.com/26768472/50900201-ca73d100-1414-11e9-99f5-ee64e4ad6dff.jpg)

**Comment by Overtorment** [comment]
This is a good question. First of all. Bluewallet and LndHub do not take any fees at all.
You can see code processing payment and calculating balance here: https://github.com/BlueWallet/LndHub/blob/4317123ffebe694322bc7656ae1ed391f360fb70/controllers/api.js#L183

Second, routes for incoming and outgoing payments might be totally different, thus, routing fees differ.
The node that tries to send a payment takes into account fees, alive-ness of nodes along the route, capacity between nodes along the route etc.

Yep looks like balance does not add up, needs debugging
