### ISSUE TITLE
Privacy suggestion

### ISSUE THREAD

**Issue by marcondy** [BlueWallet/BlueWallet#2265]
I would like to suggest an option to hide transaction amounts from history while displaying all wallets, only available when entering a selected wallet.

**Comment by marcosrdz** [comment]
You can currently go into said Wallet's options and disable "display in wallets list". You can also tap and hold a wallet's balance and select hide balance:

**Comment by Overtorment** [comment]
when you hide balance on a wallet card it is still displayed in the list afair

**Comment by Overtorment** [comment]
but yes, there is an option to exclude specific wallets transactions from common list
