### ISSUE TITLE
Unable to manage funds on LN wallet with negative amount

### ISSUE THREAD

**Issue by pajasevi** [BlueWallet/BlueWallet#228]
When I send all funds from my LN wallet, I am not able to refill the wallet again because the "manage funds" link is hidden.

**Comment by Overtorment** [comment]
Looks like fixed in 9fc3c49c9e383b597fcb24bcbb74d7665ceb9e04
thanks @marcosrdz 

![image](https://user-images.githubusercontent.com/1913337/51208201-e4c21900-1904-11e9-8a38-1cb18a66eb2b.png)
