### ISSUE TITLE
Test PSBT multisig share

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#2298]
xiaomi mi 10
android version: 10 QKQ1.191117.002

https://t.me/bwalphabeta/1160

**Comment by Overtorment** [comment]
tried on my 2 android devices and 1 emulator, could not reproduce. tried disabling permissions etc, I always get correct dialog box offering me to re-acquire permisssions.
Ive prepared a debug build for this case, it is a bit more verbose and hopefully will throw us an alert about whats wrong https://github.com/BlueWallet/BlueWallet/pull/2302
