### ISSUE TITLE
Missing Strings for Translation

### ISSUE THREAD

**Issue by mcsaeid** [BlueWallet/BlueWallet#2301]
There are quite a number of missing strings that are left untranslated. I have checked other languages as well; the issue persists and is not exclusive to Persian. Please add the following strings to the Transifex project so that they can be translated and the inconsistency can be avoided. Here is a list that I have been able to come up with so far.

![1  Local Trader, New](https://user-images.githubusercontent.com/63400670/101652475-869c0300-3a53-11eb-8a2f-41bcefc17671.png)
**1. Main Page**
1a. Local Trader
1b. New
__________________________________________________
![2  sats](https://user-images.githubusercontent.com/63400670/101652504-91569800-3a53-11eb-84a5-bef0599b6d54.png)
**2. Bitcoin Wallet**
2a. BTC (currency)
2b. sats (currency)
__________________________________________________
![3  addres, sat,byte, BTC](https://user-images.githubusercontent.com/63400670/101652517-94ea1f00-3a53-11eb-8376-068290846ad7.png)
**3. Send**
3a. address
3b. sat/byte
__________________________________________________
![4  biometrics](https://user-images.githubusercontent.com/63400670/101652564-a16e7780-3a53-11eb-8dc3-87637e69b84f.png)
**4. Security**
4a. biometrics (title only)
__________________________________________________
![5  MIT License](https://user-images.githubusercontent.com/63400670/101652745-daa6e780-3a53-11eb-8dd4-fa59baf1092b.png)
**5. About**
5a. MIT License
__________________________________________________
![6  Importing Wallet…](https://user-images.githubusercontent.com/63400670/101652795-e98d9a00-3a53-11eb-9946-b2ddda6476ac.png)
**6. Importing**
6a. Importing Wallet…
__________________________________________________
![7  x+ confirmations](https://user-images.githubusercontent.com/63400670/101652860-fe6a2d80-3a53-11eb-8c16-c1f8a4eadb2c.png)
![8  Txid](https://user-images.githubusercontent.com/63400670/101687253-7863dc00-3a7f-11eb-97fe-1aae7338f8af.png)
**7. Transaction Details**
7a. [x+] confirmations
7b. Txid
__________________________________________________
![9  Watch-only](https://user-images.githubusercontent.com/63400670/101653043-2d809f00-3a54-11eb-9424-a93e196b27b0.png)
**8. Watching-Only Wallet**
8a. Watch-only (wallet type)
__________________________________________________
![10  Connect to your LNDHub, your node address](https://user-images.githubusercontent.com/63400670/101655857-55253680-3a57-11eb-8fd1-ca8c4f91c935.png)
**9. Creating Lightning Wallet**
9a. Connect to your LNDHub (even though translated; string #‌312)
9b. your node address (even though translated; string #‌314)
__________________________________________________
![11  marketplace, sats](https://user-images.githubusercontent.com/63400670/101656044-800f8a80-3a57-11eb-82e0-f98875a6aae3.png)
**10. Lightning Wallet**
10a. sats (as mentioned before)
10b. marketplace
__________________________________________________
![12  Lightning](https://user-images.githubusercontent.com/63400670/101656955-94a05280-3a58-11eb-9ddc-6bd19e4e53d5.png)
**11. Lightning Wallet Settings**
11a. Lightning (wallet type)
__________________________________________________
![14  Multisig Vault, multisig, derivation path](https://user-images.githubusercontent.com/63400670/101656119-99b0d200-3a57-11eb-99e3-880e6823d203.png)
**12. Multi-signature Wallet**
12a. Multisig Vaulet (wallet type)
12b. multisig (title)
12c. derivation path
__________________________________________________
![13  Seed](https://user-images.githubusercontent.com/63400670/101656379-df6d9a80-3a57-11eb-8bd4-714b7c839a6e.png)
**Bonus**
Extra space between the number of seed words and the period

**Comment by mcsaeid** [comment]
Update

![15  Cash, In Person](https://user-images.githubusercontent.com/63400670/101788649-94b25800-3b15-11eb-90e0-fc1bd26922c6.png)
**13. Local Trader**
13a. Cash
13b. In person (and other possible entries)
__________________________________________________
![16  MAX](https://user-images.githubusercontent.com/63400670/101788847-d216e580-3b15-11eb-8037-f4a758947989.png)
**14. Send**
14a. MAX (using the entire wallet’s balance; note: no reason to be all capital)

**Comment by mcsaeid** [comment]
Any thoughts on this, guys? @Overtorment @marcosrdz @ncoelho

**Comment by Overtorment** [comment]
@limpbrains

**Comment by limpbrains** [comment]
I'll work on this

**Comment by limpbrains** [comment]
I didn't translate wallet types - I think they should remain in English
Also translating hodlhodl payment types is not possible - it's coming from API

**Comment by SovereignNode** [comment]
"Is it my address" isn't translating in Dutch.
