### ISSUE TITLE
Use Full Balance and Multiple recipients

### ISSUE THREAD

**Issue by limpbrains** [BlueWallet/BlueWallet#2305]
Right now it is impossible to use these features together. It should be possible to create a transaction with multiple outputs, one of which will be MAX, where all the remaining funds will be sent. It's like change output but you can define the address.

Without this you can't spend all funds from the wallet with multiple receivers in one transaction.

**Comment by Overtorment** [comment]
makes sense to me. right now there is code that forcefully resets batch send if user chooses to sendMAX.
its a good thing that `coinselect` lib we use can handle this case (looks like would still need to use `coinselect/split` strategy)
