### ISSUE TITLE
INR currency has wrong number format

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#231]
Report from twitter:

> When I choose INR as the currency the numbers become Hindi script. This is not a generally recognised script in India. Bad UX for us needing to convert to inr.

![zhyy0duh](https://user-images.githubusercontent.com/1238429/50995229-ca5ff800-151e-11e9-8bf9-0006386fd354.jpg)

**Comment by marcosrdz** [comment]
What is the expected UI?  "1234" instead of what is currently displayed?

**Comment by Overtorment** [comment]
looks fixed, just tested on ios with ln invocie
