### ISSUE TITLE
Electrum format wallet failing to import

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#2313]
stomach
shallow
easily
suspect
catch
stove
spring
margin
erupt
say
hidden
motor

**Comment by Overtorment** [comment]
absolutely empty seed. we have a clause in code, to import electrum seed only if it was used. i think it was made to not screw it up with format (user expects legacy addresses for example, and we made a decision to import it as native segwit). if you put some transactions on this wallet it will import fine.

ps. we have a big list of used seeds  for all kind of formats, if you want to grab some and test
