### ISSUE TITLE
Text Not Quite Visible in Dark Mode

### ISSUE THREAD

**Issue by mcsaeid** [BlueWallet/BlueWallet#2315]
![IMG_4213](https://user-images.githubusercontent.com/63400670/101790042-3e461900-3b17-11eb-99fa-46e3496b6f55.PNG)

**Comment by mcsaeid** [comment]
![image](https://user-images.githubusercontent.com/63400670/102002086-5e8bf880-3d0e-11eb-936e-57c4aebe07df.png)

The text would look much better if it was white on black—that is in Dark Mode. The same goes for Dark Mode off.

![image](https://user-images.githubusercontent.com/63400670/102002110-8f6c2d80-3d0e-11eb-88da-04852896f291.png)

Right now, on iOS (5.6.9), the text color inverts when Dark Mode is enabled, but it seems here that is not the case.

**Comment by marcosrdz** [comment]
@ncoelho
