### ISSUE TITLE
Alert error after 2 sendings to Zap

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#232]
report from twitter:

When sending to Zap, after 2 or 3 payments user always get an alert error.

![lh_l9sp3](https://user-images.githubusercontent.com/1238429/50995513-933e1680-151f-11e9-8f79-0f584326ae08.jpg)

**Comment by Overtorment** [comment]
Zap is just a frontend for LND. Problem lies within this LND.
Looks like one of the nodes on the path of a payment "blinks" - goes online
and offline all the time.
