### ISSUE TITLE
Cant connect to Electrum server with v3 onion address

### ISSUE THREAD

**Issue by ascisco** [BlueWallet/BlueWallet#2323]
Trying to connect to my electrum server over tor. After entering my onion address and port in BlueWallet, it says unable to connect to server.

I am running the latest versions of BlueWallet, Electrs, and Orbot on a android phone.

I did some troubleshooting but still cant connect, I dont think im missing anything since I use electrum mobile wallet regularly with my electrum server.

**Comment by Overtorment** [comment]
onion addresses are not yet supported, but we are working on native TOR support.
Im not familiar with orbot, afaik its a proxying thingie for androids to proxy to TOR..? in that case you probably need to put orbot address and port (NOT onion address) in settings

**Comment by ascisco** [comment]
> onion addresses are not yet supported, but we are working on native TOR support.
> Im not familiar with orbot, afaik its a proxying thingie for androids to proxy to TOR..? in that case you probably need to put orbot address and port (NOT onion address) in settings

I dont think Orbot is able to work that way. Will native Tor support enable onion addresses to work?

**Comment by ascisco** [comment]
Got it to work. Had to use my electrs onion address across the TCP port of 50001, as opposed to 50002.

**Comment by ascisco** [comment]
Got it to work.

I had to use my electrs onion address across the TCP port of 50001, as opposed to 50002.
