### ISSUE TITLE
Contradition in Vault Introduction Text

### ISSUE THREAD

**Issue by mcsaeid** [BlueWallet/BlueWallet#2327]
![2020-12-11 11-28-28 High Res Screenshot](https://user-images.githubusercontent.com/63400670/101878211-6f205f80-3ba4-11eb-9d94-321c328c5ef6.jpg)
The text only works with the default quorum (a two-of-three multi-signature wallet).

**Suggestion**
It needs {m} Vault keys to spend and one or more keys that you can use as a backup.

This can be implemented along with the new changes made in PR #2322.

**Comment by Overtorment** [comment]
that needs some code change and cant be solved with just localization

**Comment by mcsaeid** [comment]
Can you ellaborate why the localization wouldn’t work in this case?

From what I understand, there are three strings involved:
1) “It needs”
2) “ {m} Vault keys ”
3) “to spend and a third one you can use as backup.”

Imagine a user wanting to use a three-of-five multi-signature wallet. The sentence “It needs {m} Vault keys to spend and _one or more_ keys that you can use as a backup.” fits perfectly, whether they opt for a two-of-three wallet, a three-of-four, or seven-of-ten. It applies to all cases logically. What kind of change in the code did you have in mind? I am only curious.

**Comment by marcosrdz** [comment]
We would need to implement this for all languages and JS doesnt have a builtin method to handle ordinals.

**Comment by mcsaeid** [comment]
Got it. But one thing I have picked up is that if you make a change, the translations are then cleared, I am guessing in all languages, so people just need to revise their content. Awesome, man. Well, I guess that is something that you guys can fix later, and since you are already working on the multi-signature feature, I am thinking it won't be long.

**Comment by jpph** [comment]
The phrase should be and '' zero, one or more '', in case of 2 of 2 qorum

**Comment by mcsaeid** [comment]
I agree with having zero in there as well, but not in the way suggested. It could be, “up to one or more keys.” It is shorter.
