### ISSUE TITLE
LNURL Withdraw - Stops on the receiving step (iOS)

### ISSUE THREAD

**Issue by jackeveritt** [BlueWallet/BlueWallet#2336]
Version 5.6.9
iOS

If you open an LNURL withdraw with the lightning: url scheme, it gets stuck on the receiving screen.

![photo_2020-12-12_15-29-42](https://user-images.githubusercontent.com/1027263/101988681-0c59c180-3c93-11eb-8ecb-ef01f827c67e.jpg)

**Comment by brmdbr** [comment]
Got one customer on our platform with this issue as well, same white screen.

**Comment by marcosrdz** [comment]
> Version 5.6.9
> 
> iOS
> 
> 
> 
> If you open an LNURL withdraw with the lightning: url scheme, it gets stuck on the receiving screen.
> 
> 
> 
> ![photo_2020-12-12_15-29-42](https://user-images.githubusercontent.com/1027263/101988681-0c59c180-3c93-11eb-8ecb-ef01f827c67e.jpg)
> 
> 

Do you have a sample that can be provided to test?

**Comment by Overtorment** [comment]
supposedly fixed in https://github.com/BlueWallet/BlueWallet/pull/2314
