### ISSUE TITLE
zigzag error on withdraw

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#234]
Reported on telegram:

> I am getting an error using zigzag to go back to my on chain wallet from lightning though
> Is this a common error? After getting the error I scanned the invoice with eclair and it went through.

![photo5023962171599595588](https://user-images.githubusercontent.com/1238429/51002253-fe451880-1532-11e9-8279-2306da714b7a.jpg)

**Comment by Overtorment** [comment]
Seems to be a problem on Zigzag end. Confirming with them...

**Comment by Overtorment** [comment]
Restarted out node, looks fixed.
To be investigated.
