### ISSUE TITLE
Unable to scan bluewallet lightning QR

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#235]
Reported on telegram:

> I've been getting my colleagues to download it and I'm teaching them how it works. I've noticed their iPhone cameras are unable to scan bluewallet generated lightning invoices.
> So we've been copy pasting instead

**Comment by Overtorment** [comment]
As I said before, ln invoices pack a lot of data and they should be as big
as possible because some lowend decices might nit recognize them

**Comment by davidapple** [comment]
The invoice QR is still not scanning on my friends smartphone. I suggest removing the logo from the center.
