### ISSUE TITLE
Batch Send UI bugs

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#2362]
* [ ]  when adding a recipient, scroll scrolls to _second to last_ recipient, not the last one (off-by-one bug?)
* [ ] when scanning address for a recipient scroll resets to the first recipient
* [ ] when removing _last_ recipient, scroll renders just blank space, you need to manually scroll to your other recipients

### dire need for e2e test of this feature!

since we have a huge overhead on running an e2e testcase and importing a wallet, I suggest e2e test for batch send will be added to the end of `can import BIP84 mnemonic, fetch balance & transactions, then create a transaction` test. do several `device.pressBack()` so app goes back to main screen, and start automating e2e from there. to speed things up you can temporarily comment out parts of this test (basically start coding test right after `helperImportWallet()`)

**Comment by marcosrdz** [comment]
https://github.com/facebook/react-native/issues/25239
