### ISSUE TITLE
Error message confusing when importing empty electrum seed

### ISSUE THREAD

**Issue by jpph** [BlueWallet/BlueWallet#2363]
Instead of '' failed to import '' it should says something like '' electrum wallet is empty, didnt import because can not determine the right address format used. Please make some trx in electrum first ''

**Comment by Overtorment** [comment]
noted. 
will think of something when will be refactoring import.
there is a bunch of things that can go wrong

**Comment by Transisto** [comment]
I have a electrum wallet with funds and I always get:

An error was encountered, ....

Not much more useful message,

**Comment by Overtorment** [comment]
@Transisto what bw version? import procedure was refactored in the latest release.
electrum seed format should be imported okay even if there are no funds or transactions there.
my guess is that you're using some obscure electrum wallet format that is not yet implemented in BW. like 2fa electrum wallets that are not supported.

**Comment by Transisto** [comment]
Nevermind, the seed had a typo, all good. Thanks!

**Comment by Overtorment** [comment]
closing because electrum seed format actually carries a hint that this _is_ an electrum seed for legacy or segwit address types.
empty seeds should be recognized and correctly imported with no issues.
