### ISSUE TITLE
Make clear that the Lightning Account is custodial

### ISSUE THREAD

**Issue by Giszmo** [BlueWallet/BlueWallet#2364]
BW promotes to be non-custodial and there is nothing wrong with having a custodial feature in a non-custodial wallet but only if the user that chose the wallet because "Private keys never leave your device" learns about the exception for this account type. Please add an alert about the account being custodial in the Add Lightning Account workflow.

**Comment by ncoelho** [comment]
Will make it more clear in the app flow. This is stated in the first line of the site, always has been.

Won't use the "custodial" term because that will be incorrect. But will use something similar.

**Comment by Giszmo** [comment]
> This is stated in the first line of the site, always has been.

Which first line of which site?

First line of bluewallet.io?
![Screenshot from 2020-12-16 13-07-37](https://user-images.githubusercontent.com/96378/102374141-bee59900-3f9f-11eb-881e-9539b8d27bbc.png)

First line on Google Play?
![Screenshot from 2020-12-16 13-08-40](https://user-images.githubusercontent.com/96378/102374220-d9b80d80-3f9f-11eb-9b38-8a7b8d3e9c3e.png)

I am confused.

> Won't use the "custodial" term because that will be incorrect.

Please elaborate in which way it is incorrect. So can the provider of the LN node not spend all the users' funds or "get hacked"?

**Comment by ncoelho** [comment]
No, on the lightning main page, the landing page where users searching for lightning arrive on and the only page with lightning information:
https://bluewallet.io/lightning/

I used to use the term "custodial", but I changed to "hosted" for two reasons. First is that users don't really know what that means and secondly because it is the term regulators are using nowadays. Custodial also means different things in different jurisdictions, with different "custodial" limits, and bitcoin is also regulated differently in different countries.

Take in consideration that lightning is a super early stage tech, that no one is really using and we are not really focused on it at the moment. We are playing and learning it as the rest of the teams, and pretty sure if it takes off in the future we will be providing an only non-custodial solution or self-hosted, or whatever term people will be using by then. Or we will just remove it if it doesn't take off.

I'm also not sure why you are broadcasting my comments on twitter, if you want drama go find someone else to bother please. We are busy building free open source software.

**Comment by Giszmo** [comment]
> I used to use the term "custodial", but I changed to "hosted" for two reasons. First is that users don't really know what that means and secondly because it is the term regulators are using nowadays. Custodial also means different things in different jurisdictions, with different "custodial" limits, and bitcoin is also regulated differently in different countries.

To have custody of something is well defined. Who has custody of the coins in LN accounts?

> Take in consideration that lightning is a super early stage tech, that no one is really using and we are not really focused on it at the moment. We are playing and learning it as the rest of the teams, and pretty sure if it takes off in the future we will be providing an only non-custodial solution or self-hosted, or whatever term people will be using by then. Or we will just remove it if it doesn't take off.

I have no issue what so ever with the LN account being custodial. I do have an issue though with the implied self-custody as that's what BW is advertising everywhere. Please add a clear disclaimer about who's holding the keys to the funds in the LN acccount as I have great hope for BW and would love to welcome it as a reproducible wallet.

> I'm also not sure why you are broadcasting my comments on twitter, if you want drama go find someone else to bother please. We are busy building free open source software.

This issue was raised half a year ago and no action was taken. Adding an AlertBox is a trivial task. WalletScrutiny is about promotion of self-hosted, reproducible wallets and that means to talk about issues where there are issues. Sorry if you took it personal. I see good things coming from BW otherwise. And yes, of course I would appreciate more exposure for the topic. Can't blame me for that I guess.

**Comment by godSaysHODL** [comment]
Giszmo,

 Lightning on Bluewallet is custodial by default but, you can use it non-custodially by running LNDhub on your node. I am and end user using Bluewallet lightning in a non-custodial fashion for myself through mynodeBTC. They probably should have a warning for the default setting, but it doesn't mean the wallet can be written off of the non-custodial list completely

**Comment by junderw** [comment]
@ncoelho Wouldn't it be simple to add logic to the app where:

1. IF lndhub URL is pointing to the default BW endpoint
2. AND user taps create new lightning wallet
3. THEN pop up a clear warning message saying "Please note: any funds you receive to this wallet are in the full control of BlueWallet's operating company. If you do not wish for us to control your funds, please set up your own lndhub here, and change the endpoint setting under settings > blah >blah > endpoint"
4. OR alternatively, only throw that pop-up once a certain balance is reached: ie. (IF >= X sats (or grab USD price data and do >= X USD equivalent))

One thing I do agree with OP is:
- A lot of the recent lightning wallets tend to be custodial, and tend to gloss over that fact in favor of not scaring off new people.
- This is not good.
- But, I think glossing over it up to a certain point is ok, since a user who will only use Lightning for 100 sat transactions max might look at a big warning and think "wow, lightning is too complicated" and give up, compared to the risk they bear by getting goxxed for 100 sats.
- So maybe the "once the balance hits a threshold, warn them more sternly" + "be more clear and explicit (with "custodial") with the website" should be sufficient.

**Comment by Giszmo** [comment]
> OR alternatively, only throw that pop-up once a certain balance is reached: ie. (IF >= X sats (or grab USD price data and do >= X USD equivalent))

It's not on the provider to judge which amount is ok and which not. Some would be devastated loosing $1, others wouldn't notice losing $100k.

And yes, other wallets glossing over this is a problem but not an excuse. If you see other wallets that are in the wrong category on [WalletScrutiny](https://walletscrutiny.com/), please let me know. Phoenix for example appears to be some less straight forward kind of non-custodial but if somebody makes the claim and explains it well, I'd certainly consider moving more wallets out of the implicit non-custodial categories. In my book, "custodial" means, the funds are permanently under the control of the provider or another entity other than the user himself. Even if in the case of Phoenix the wallet creation involved a step where the provider gets brief control of the funds, this would be very different from an ever growing stash, ready for grabs. If Phoenix is custodial though, even a disclaimer wouldn't be able to save the day for them as it would for BlueWallet, as Phoenix is lightning, only I think. So there wouldn't be a non-custodial account left.

**Comment by ncoelho** [comment]
This suggestion was introduced and released to production on Jan 7 in the version https://github.com/BlueWallet/BlueWallet/releases/tag/v6.0.2

Meanwhile we already released our two new open source libs that will be the core to our full Lightning non-custodial solution, that will fix the root problem on this concern.
https://github.com/BlueWallet/rn-lnd
https://github.com/BlueWallet/rn-ldk

**Comment by Giszmo** [comment]
So the addition of "- This wallet is hosted by BlueWallet." to the backup page is your disclaimer?

What legal entity is the custodian of the coins? Is BlueWallet a registered company? Under which jurisdiction? [Your website](https://bluewallet.io/about/) doesn't list any company.

![Screenshot from 2021-03-09 00-37-53](https://user-images.githubusercontent.com/96378/110415904-88d12600-8071-11eb-9361-a745a3be84f1.png)

**Comment by junderw** [comment]
Not to mention, people probably group "hosted" into wallets like blockchain . com and samourai, wallets where the node and public info is hosted but the private info is self-managed. (aka the "host" can not spend funds assuming it works as planned)

This "hosting" should be clearly stated, and anyone who reads it should understand that:

`"Any bitcoin you deposit to this wallet is spendable by Bluewallet, we could steal all your money in this wallet at the drop of a hat if we wanted to. We won't. But you have to take our word on it."`

This "warning" is extremely weak, and it doesn't help users understand that you are the god of their wallets in this mode.

**Comment by godSaysHODL** [comment]
I think the hosted wallet warning is sufficient personally.

**Comment by unixb0y** [comment]
So the LN wallet is custodial because it's basically the trade off you have to accept if you don't wanna run a 24/7 online one instance yourself right?

If I add funds to the normal Bitcoin wallet in BlueWallet though, it will be only on device correct?

**Comment by junderw** [comment]
> it's basically the trade off you have to accept if you don't wanna run a 24/7 online lnd instance yourself right?

No, it's one trade off of many you can choose. It's not "the trade off" (as in the only one). BlueWallet decided it would be easier if they held the lightning funds for all their users, which is true. It's also much easier to develop a wallet where you just send a request to a custody server.

> If I add funds to the normal Bitcoin wallet in BlueWallet though, it will be only on device correct?

Correct. On-chain funds are not custodial.

> I'm now actually unsure why BlueWallet needs to be partly custodial.

It doesn't NEED to be. It CHOSE to be.

**Comment by unixb0y** [comment]
Wow thanks a lot for the quick reply!

> BlueWallet decided it would be easier if they held the lightning funds for all their users, which is true.

What exactly is easier for the users? What would they have to do additionally if it weren't custodial?

> Correct. On-chain funds are not custodial.

Great! Good to hear. Used the xpub feature so far and that's definitely a great feature to have. Might use the hot on-chain wallet as well, but not sure yet about the LN one.

**Comment by Overtorment** [comment]
switch to non-custodial lightning is in progress here: https://github.com/BlueWallet/BlueWallet/pull/2615

**Comment by unixb0y** [comment]
> switch to non-custodial lightning is in progress here: https://github.com/BlueWallet/BlueWallet/pull/2615

Oh nice! But that will be solved by allowing to just connect to a self hosted lnd instance right?

I saw another wallet somehow solved the issue without requiring security concerned people to host an lnd instance.

**Comment by Overtorment** [comment]
@unixb0y no, that's a full-featured LND node that runs inside bluewallet

**Comment by unixb0y** [comment]
> @unixb0y no, that's a full-featured LND node that runs inside bluewallet

Oh I see, that sounds great! But don't lnd nodes have to say online for the duration of the channels lifetime?

**Comment by Overtorment** [comment]
@unixb0y no, only to send/receive/route payments, most of the time they can stay offline

**Comment by unixb0y** [comment]
> @unixb0y no, only to send/receive/route payments, most of the time they can stay offline

Wouldn't it be possible for a node to publish an older tx (like one where they had more money than now) without the other party noticing if the other party isn't online for an extended period of time?

**Comment by Overtorment** [comment]
@unixb0y first of all, allowed offline time in configurable, from 1 to 14 days (maybe even more?), second, watchtowers is a thing that can do this work for you, third, if opened your channel yourself you're only _paying_ with your channel, you are always safe as all old states are beneficial to you

**Comment by unixb0y** [comment]
> @unixb0y first of all, allowed offline time in configurable, from 1 to 14 days (maybe even more?), second, watchtowers is a thing that can do this work for you, third, if opened your channel yourself you're only _paying_ with your channel, you are always safe as all old states are beneficial to you

Got you, makes sense! I'll have to look up watch towers but the rest sounds good :) 

Any rough ETA for the feature implementation into release?
