### ISSUE TITLE
Import Multisig from Specter Desktop -  Fingerprint is Incorrect

### ISSUE THREAD

**Issue by flyingfaders** [BlueWallet/BlueWallet#2366]
When importing a multisig wallet from Specter Desktop using the QR Code from Specter the wallet imports fine into BlueWallet but the fingerprints for each key are incorrect. The fingerprints contain the correct letters/numbers but the order is wrong, they're sort of backwards. 

For example:

Fingerprint from Specter: 12345678
Fingerprint in Blue Wallet after import: 78563412

This causes issues when trying to sign a transaction with a HWW as the device doesn't recognize the multsig wallet.

**Comment by Overtorment** [comment]
ack
