### ISSUE TITLE
Possibility to pump fee or cancel transaction vanishes

### ISSUE THREAD

**Issue by derHase85** [BlueWallet/BlueWallet#2375]
I was sending a transaction with a low fee, expecting I could pump the fee after some time, if the transaction gets more important or the mempool gets more full.

After creation I checked and I had the options available to pump the fee or cancel the transaction.

Now after some hours and checking again these options vanished.
I am using IOS and it was a bech32 wallet.

I also have some transactions pending on multi sig wallets, where I already missed the options to pump the fee. But now I am not sure if it there also was available after sending the transaction and just vanished also.

**Comment by marcosrdz** [comment]
Has the transaction been confirmed? Those options don't show up after the tx has been confirmed or if the transaction is not bumpable.

**Comment by derHase85** [comment]
No, transactions have not yet confirmed. 35 MB Mempool to go

Will Check tomorrow if it is bumbable in electrum. But would assume it is

by the way, a information showing how much mb mempool still to climb in BlueWallet would be very helpful, so there would be no need to do the extra step over the block explorer

**Comment by marcosrdz** [comment]
Go into your wallet transactions. Do a pull to refresh on the list, wait for it to load, then tap on your unconfirmed transaction.

**Comment by derHase85** [comment]
Did a refresh on all wallets: nothing

did a refresh on the specific wallet: nothing

did a refresh on the specific wallet: timeout to electrum server

did a refresh on the specific wallet: timeout to electrum server

Closed BlueWallet, waited some time and did a refresh on the specific wallet: pump fee available again

I can live with that, now knowing, that is maybe some connection problems. But I think it would be more straight forward, if it is different solved in the ui instead of hiding the options to pump or cancel

So for me this is solved, thank you!

**Comment by Overtorment** [comment]
I suspect electrum server was down when you tried, so bluewallet could not check that transaction is really unconfirmed
