### ISSUE TITLE
can you share your splash screen animation aep source file

### ISSUE THREAD

**Issue by ebtone** [BlueWallet/BlueWallet#2379]
can you share your splash screen animation source file（aep）?

yangmengqing@gmail.com

**Comment by ncoelho** [comment]
Hi @ebtone why do you need this? I'm using specific software to generate lottie/json animations. So the source is the json files.

**Comment by ebtone** [comment]
> Hi @ebtone why do you need this? I'm using specific software to generate lottie/json animations. So the source is the json files.

Hi @ncoelho I want to copy the animation effect, So need source file.

**Comment by Overtorment** [comment]
here you go https://github.com/BlueWallet/BlueWallet/blob/master/img/bluewalletsplash.json
no need to thank me
