### ISSUE TITLE
Fiat should never be 0.00, round up to 0.01

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#238]

**Comment by charltonh** [comment]
Not sure if this should be true, actually.  Rounded to nearest penny seems like the most logical.

But while we're on the topic, I noticed that balances do not immediately update even after the transaction is visible and successful.  It looked like something was wrong/buggy with the wallet when I first used it.

**Comment by Overtorment** [comment]
@ncoelho UX wise, $0.00 makes sense..? Your decision.

Yes, balances are actually updated, just the wallet is not refreshing it. After refreshing tx list manually it refreshes the balance as well. Will create another ticket for that.

**Comment by Overtorment** [comment]
rel https://github.com/BlueWallet/BlueWallet/issues/252
