### ISSUE TITLE
Source wallet not found

### ISSUE THREAD

**Issue by plengkeek** [BlueWallet/BlueWallet#239]
I get the error message as below when I do the following: tap on lighting transaction outside of the lighting wallet and tap back on Android instead of pressing the cross in the right top corner. When I press back again the message disappears and the functionality of the wallet seems unaffected. 

![screenshot_20190111-190322](https://user-images.githubusercontent.com/26768472/51051438-0acd7d80-15d4-11e9-8924-3cd378e3b767.jpg)

**Comment by bitcoinuser** [comment]
I have the same problem.

**Comment by marcosrdz** [comment]
Fixed 5d248413e607c74102418d245c1d8fa103015d1d
