### ISSUE TITLE
Scanning a Vault PSBT Qr code when scanning for a send address hangs the app

### ISSUE THREAD

**Issue by Transisto** [BlueWallet/BlueWallet#2390]
back button work but it loads forever.

**Comment by marcosrdz** [comment]
Which BlueWallet version? May you provide the device you're using?

**Comment by Transisto** [comment]
Latest version on Android

**Comment by Overtorment** [comment]
can you record and upload a video?

**Comment by Transisto** [comment]
https://youtu.be/ywW-0zKYr6w

Try SEND (any wallet)
at address click the scan button
Scan an animated QR code of a PSBT from a 2/3 Vault wallet.

**Comment by Overtorment** [comment]
fixed in https://github.com/BlueWallet/BlueWallet/pull/2488
video helped, thanks!
