### ISSUE TITLE
error - recipient list empty.

### ISSUE THREAD

**Issue by Transisto** [BlueWallet/BlueWallet#2391]
Got a "Internal error: Recipient list empty (this should never happen)"

Was sending MAX of single UTXO from a 2-3 vault wallet, 

When I click confirm I got above popup error, 
 I can dismiss with OK and still broadcast the transaction normally.

**Comment by Overtorment** [comment]
This happens when sending to your own address (to address belonging to this specific wallet)

**Comment by Transisto** [comment]
I confirm this was the case.
