### ISSUE TITLE
Bluewallet missing from homebrew

### ISSUE THREAD

**Issue by maltokyo** [BlueWallet/BlueWallet#2395]
I added it, it is awaiting review.
https://github.com/Homebrew/homebrew-cask/pull/96024

After that, it can be installed with:

`brew install bluewallet`

on macOS..

Just letting you guys know, will update here when it gets approved for use.

**Comment by Overtorment** [comment]
noice! i dont use macos tho, but @marcosrdz does. what are your thoughts on this @marcosrdz ?

**Comment by marcosrdz** [comment]
Yup. This is great.

**Comment by maltokyo** [comment]
Cool. Should be approved soon. Then I would suggest to add to your homepage as an alternative install method.  Probably the most reliable way to avoid scammer sites etc, as it checks the SHA256 hash of your binary. I'll maintain it if you like. Or I can hand over to you. Whichever is fine for you guys.

**Comment by marcosrdz** [comment]
Whats the process to transfer ownership?

**Comment by maltokyo** [comment]
Have no idea ;)

**Comment by maltokyo** [comment]
This is now merged. There is no ownership. It's FOSS. You can keep it up to date just as easily as I can. I'll do when I see you have a new version or you can too. Please add in your documentation, wiki etc if you like. Or shall I?

**Comment by maltokyo** [comment]
https://github.com/Homebrew/homebrew-cask/blob/master/Casks/bluewallet.rb

**Comment by marcosrdz** [comment]
Thank you!

https://formulae.brew.sh/cask/bluewallet
