### ISSUE TITLE
Notch support on Android

### ISSUE THREAD

**Issue by plengkeek** [BlueWallet/BlueWallet#240]
Currently shows a grey bar and not as shown in the README.

![screenshot_20190109-133635](https://user-images.githubusercontent.com/26768472/51206494-754e2880-1908-11e9-8658-9782ffc54b7a.jpg)

**Comment by Overtorment** [comment]
Can you pls attach screenshot? Thanks!


cc @ncoelho

**Comment by plengkeek** [comment]
Added screenshot
