### ISSUE TITLE
Co-Signing 2of2 Native Segwit Transactions from Electrum don't work!

### ISSUE THREAD

**Issue by Tigerix** [BlueWallet/BlueWallet#2401]
Steps to reproduce:

Electrum (4.0.9):
Create a TX based on Seed 1 and Zpub 2
Show QR-Code

Bluewallet (6.0.1):
Vault based on Seed 2 and Zpub 1
Click on Send --> Sign a transaction
Scan QR-Code
TX is shown with Vault key 1 having a green check mark.
Vault key 2 is having a grey check mark.
Confirm button is grayed out.

**Comment by mangobtc** [comment]
The issue persists when 2 of the 3 keys are in blue wallet in two separate wallets ( tested in the same android phone)

**Comment by alexionescu** [comment]
Also ran into this bug.

**Comment by Overtorment** [comment]
Fixed, will be out in next release
