### ISSUE TITLE
Incorrect price calculation with coin control

### ISSUE THREAD

**Issue by Abstraktikus** [BlueWallet/BlueWallet#2404]
![0$](https://user-images.githubusercontent.com/17813711/102709195-60befb80-42a8-11eb-8f18-c03d7054475c.png)
![5$](https://user-images.githubusercontent.com/17813711/102709197-67e60980-42a8-11eb-84d3-9db56de8d283.png)
![10$](https://user-images.githubusercontent.com/17813711/102709201-6e748100-42a8-11eb-944e-6ca98f1be36c.png)
![100$](https://user-images.githubusercontent.com/17813711/102709207-7fbd8d80-42a8-11eb-8122-7b1156aedd2e.png)
![1000$](https://user-images.githubusercontent.com/17813711/102709208-81875100-42a8-11eb-84d6-8721c6d4bbe5.png)

Sending 1000$ will cost less than sending 100$. Banking allures :-)
The fee drops (actually) exactly from 410$ to 411$. AND
Until 410$: The fast & medium option shows the same price. Only by 411$ AND 412$, the medium price option is higher, than the fast. From 413$ to 1000$ the fast price option is as expected more expensive.

Also, price jumps between 0$, 5$, 10$.
Type: HD SegWit (BIP84 Benach32 Native) with 24 words imported from https://iancoleman.io/bip39/

I observed this in CHF and switched to $ to open the ticket.

Important: I have 4 Coins: $406.82 / $12.45 and Freezed: 2'081.52 / $11'466.48. I think this may show the error. (406+12 are close to the magic 411$).

YES! - This is hot: I unlocked the freezes. Then, the price drop moves up from 411$ to 13'950$. Same behavior there. The medium option for 13'950$ is higher than the fast prices.

I allways just changed the amount. No changes in inputs or outputs. Allow fee bump On/Off shows no impact.

I first beleaved, that diffrent wallet types result in different behavior. As the phenomenon is not observable with my watch-ony wallet, imported from CoboVault. And is not observale with Legacy (P2PKH), SegWit (P2SH), Legacy (BIP 44PSPKH), Multisig Vault. But there i have either not used coin control or zero or only one UTXO.

**Comment by Abstraktikus** [comment]
#2156

**Comment by Overtorment** [comment]
@limpbrains
