### ISSUE TITLE
Import of Coldcard from Specter failed

### ISSUE THREAD

**Issue by imacfan** [BlueWallet/BlueWallet#2406]
Given below is the raw data (example) of Coldcard wallet in Specter which I tried to import in Bluewallet. 
It failed

{ "label": "Coldcard", "blockheight": 6506, "descriptor": "wpkh([mXXGH2XX\/84h\/0h\/0h]XXXXXXXXXXXXXXXXXXXXXXXXXXX\/0\/*)#YYYYYYYY" }

**Comment by Overtorment** [comment]
how exactly did you try to import it? did you paste this json into input field?

**Comment by imacfan** [comment]
> how exactly did you try to import it? did you paste this json into input field?

Tried copy paste and JSON import

**Comment by ncoelho** [comment]
If you want to import from coldcard import it directly. Specter will
transform the backup to descriptors which we only support for multisig at
the moment

**Comment by davterra** [comment]
> If you want to import from coldcard import it directly. Specter will transform the backup to descriptors which we only support for multisig at the moment

I exported a wallet from my Coldcard using the generic json format. Importing that file into Bluewallet, for me, generates an error message saying it can't read that format. Any thoughts appreciated.

**Comment by ncoelho** [comment]
From coldcard you need to choose electrum format

**Comment by davterra** [comment]
Thank you!
