### ISSUE TITLE
Bluewallet  AND Cobo vault  Multi-signature problem

### ISSUE THREAD

**Issue by caixiao-QA** [BlueWallet/BlueWallet#2435]
blue wallet version: 6.0.1
Devices Modle:HUAWEI P30 pro(VOG-AL00)

Trying to create and sign a multi-signature wallet with cobo vault, I encountered the following problems:
1. On the send page, 577sat was sent, but the sending amount is displayed as 0 BTC
2. After clicking "confirm", it prompts "internal error: recipients list empty (this should never happen)"
3. On the broadcast success page, the amount sent is displayed as 0 BTC
4. After the broadcast, check the broadcasted transaction in the transaction record, bluewallet crash

https://user-images.githubusercontent.com/37337093/103187048-defd4c80-48fd-11eb-9533-1c02c146c62e.MOV
https://user-images.githubusercontent.com/37337093/103187044-d86ed500-48fd-11eb-98fa-66e157bea633.MOV

Attached operation video, looking forward to your reply

**Comment by Overtorment** [comment]
was that a transfer to yourself?

**Comment by caixiao-QA** [comment]
> was that a transfer to yourself?

yes

**Comment by Overtorment** [comment]
why did you close the issue?
crash is still not okay
