### ISSUE TITLE
Descriptor fails to import

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#2442]
wsh(multi(3,xpub661MyMwAqRbcFL5NEom7FhRh1ByXyZXpcm85Q3rjqK3YFJ1yoezHQ9z5ogrLMGBGqvwiR6oAdD1HotYZkuFczueNqm3dzRJ3jN384AJsWwS/*,xpub661MyMwAqRbcGCPbmZuW9zkFj4rwvAMr9cPp6SMig3y7iCVnTpVsHLbmz3MUATtPRdMY2feqYnXm5vXuTYZfJBjxQpqsetDo9UXtbhGAzqJ/*,xpub661MyMwAqRbcEtqVNu4mRwL5KQUqVnBs1kAN6kaTwbXywtF64o8NWNJssDasGG2PWpeSxxd2p6rq5skQTqdSkM3fAKhVKbrz56zpg773pNB/*,xpub661MyMwAqRbcFNCa7tWFdYuossZF7Eou7vkuVJXooDXPaeZSxqnks9ggDgCgwA1FbcLS72e2fhnUQ4UyzkGfQvDvqPp3pe2WWNg3w4xunYL/*,xpub661MyMwAqRbcFdbDnszKT7K5pMoBqxmUx2oqmv3gi3dpmmz7dkWgM5bd3SBy248DfF3k7S9nKwyBUgzKZ9Qm75mexp7WP295ygV6SNY447Y/*,xpub661MyMwAqRbcGD2aMpbcYwWRRMAbD8oGGcwE4GqfcC5hXxh9Fkc16fwWf4NxRoviR8zbzDYnMvDZL4yAvB1QmLAFXcM3LMYdhqGqVD4yn3d/*,xpub661MyMwAqRbcFnpboE9VxtA767dFYftXvcnrQ7wvigWq95hQrj5ynYaXL4sx8DznU5u2hhzawGr1UnZDEX72mEicjikc4fiGRDDRXCfqu5E/*))#dq63vzxc

**Comment by Overtorment** [comment]
@ncoelho can you get me first external (and internal) address for this wallet for verification?
also, where this wallet descriptor comes from? it has `multi` instead of `sortedmulti` which implies pubkeys are not sorted to get the address - BIP67 is not used.
this is super rare beast, me & @stepansnigirev don't even know where is this coming from

**Comment by ncoelho** [comment]
This is from core I believe, let me ping the user that shared this

**Comment by JWWeatherman** [comment]
Yes, this is coming from bitcoin core. I think we implemented it before sortedmulti was available in bitcoin core so this is the format of the descriptor wallets we create in yeti. I will grab a couple addresses right now.

**Comment by willweatherman** [comment]
Descriptor: wsh(multi(3,xpub661MyMwAqRbcF13nMmebEmEzQvNH6ZC65QMi6wvmTAvbu957VAWpt2SM7wQiLd5NVudfUpvzpeXNfT5AjhWbbuSKpJ2cssPiPM2tCeZMy7T/*,xpub661MyMwAqRbcEbwCpKydkE7KTa2EeMNtZtvSQ8BS1UK2jxVpb9767T5hyBxt67Wa2vev7defUorAFxVvNuSsrMJA34pSDAqj7MYig32Yn12/*,xpub661MyMwAqRbcEnmMnN5ish1Z7tPBfPDKp4wdKhSj6j4UDhiK5bzU6qjE5KnQKw6cQLKg6AhwnPvGmw7A7gsgZqvkEQZDmDqgPUutccd74Wh/*,xpub661MyMwAqRbcEydQM8Y6dCRKkpFszd8xeCFTqiwSUZW7MQ5f249yjRuD8EV43gtkNNxHCDgDmZwy2oVDuAY9pV6sWdBbeU2FuoWGtkERFhV/*,xpub661MyMwAqRbcGNZ4VG1dRWTN2qcsQhz5w4McN9KRXrAECe4toPr44jEtskvCjizC63xM3QnSXyfraFgLqb14ExZUP4QQxnSejCngFjQ8sZz/*,xpub661MyMwAqRbcGHtzSBVBkk166iS6XQgYQnrgu2CHAFL5znv1byy5e4ZjCmZ3ZhugmUx3x91kC5xjyYAQCvtoJXheTyUSQ23y8RWDhH6wbs2/*,xpub661MyMwAqRbcGUuSCPhxc7NDC6Zh4fhecozKEiR7QK7APCVt9Yhyx2NMUd4wrTHYP91G4Fh6Jp9P5Aipf8FjDsrSutkLj3Lie5bCrrM2CfT/*))#9hky7ctt
First, receive address generated by bitcoin core: bc1qg4wtpw3vn9lv0je3ca679nhpqstmvxqan8mjrj8rkg52snq0hzyqsncezw

I am going to check my generation of the internal address and Ill post the first one here.

**Comment by Overtorment** [comment]
@willweatherman  thanks! I'll use it as a test vector

**Comment by willweatherman** [comment]
No thank you, this will keep my grandma from nagging me about not being able to see her bitcoin balance every time it goes up a 1000$.

**Comment by willweatherman** [comment]
This is the change address:
bc1q25ercknufqd2a9lkwr0sgzd54634w4nfww4jkp7gl6yt7cs9gztsvn5utg

If whatever checks you are doing do not line up with these two addresses it could be because I am messing around with how we import the descriptors right now.

**Comment by Overtorment** [comment]
> Descriptor: wsh(multi(3,xpub661MyMwAqRbcF13nMmebEmEzQvNH6ZC65QMi6wvmTAvbu957VAWpt2SM7wQiLd5NVudfUpvzpeXNfT5AjhWbbuSKpJ2cssPiPM2tCeZMy7T/_,xpub661MyMwAqRbcEbwCpKydkE7KTa2EeMNtZtvSQ8BS1UK2jxVpb9767T5hyBxt67Wa2vev7defUorAFxVvNuSsrMJA34pSDAqj7MYig32Yn12/_,xpub661MyMwAqRbcEnmMnN5ish1Z7tPBfPDKp4wdKhSj6j4UDhiK5bzU6qjE5KnQKw6cQLKg6AhwnPvGmw7A7gsgZqvkEQZDmDqgPUutccd74Wh/_,xpub661MyMwAqRbcEydQM8Y6dCRKkpFszd8xeCFTqiwSUZW7MQ5f249yjRuD8EV43gtkNNxHCDgDmZwy2oVDuAY9pV6sWdBbeU2FuoWGtkERFhV/_,xpub661MyMwAqRbcGNZ4VG1dRWTN2qcsQhz5w4McN9KRXrAECe4toPr44jEtskvCjizC63xM3QnSXyfraFgLqb14ExZUP4QQxnSejCngFjQ8sZz/_,xpub661MyMwAqRbcGHtzSBVBkk166iS6XQgYQnrgu2CHAFL5znv1byy5e4ZjCmZ3ZhugmUx3x91kC5xjyYAQCvtoJXheTyUSQ23y8RWDhH6wbs2/_,xpub661MyMwAqRbcGUuSCPhxc7NDC6Zh4fhecozKEiR7QK7APCVt9Yhyx2NMUd4wrTHYP91G4Fh6Jp9P5Aipf8FjDsrSutkLj3Lie5bCrrM2CfT/*))#9hky7ctt
> First, receive address generated by bitcoin core: bc1qg4wtpw3vn9lv0je3ca679nhpqstmvxqan8mjrj8rkg52snq0hzyqsncezw
> 
> I am going to check my generation of the internal address and Ill post the first one here.

for some reason addresses that I derive do not match the ones you provided.

I got:

bc1qwckrq8mmlg4ws2pl30rgv7d3t4hstgvjchmpdvrdhwtk7pvaptts4q7cdg (e0)
bc1quz8qe99rsukxet239u5sed7h7a0adua6gzvrt6jw0kwysmhsqmkqvfcart (e1) bc1qs6ltrkpzf0cvnv4qam8f0qgy0vv6c70qn4n7mqy3l4dm5h9lh7fqvs3zzm (i0) bc1qjwmxmnkyj898qxzwuhp2xcegp2xhphw2a42l3hf5upq95xw4gcqqsl6mn9 (i1)


Can you pls double check?
Or maybe you have test vectors youre absolutely sure about?

**Comment by willweatherman** [comment]
None of those addresses are derived from the descriptor I gave you via bitcoin core.
I create a wallet that is a blank, descriptor wallet, with disabled Private key and run this command inside of it.
importdescriptors '[{ "desc": "wsh(multi(3,xpub661MyMwAqRbcF13nMmebEmEzQvNH6ZC65QMi6wvmTAvbu957VAWpt2SM7wQiLd5NVudfUpvzpeXNfT5AjhWbbuSKpJ2cssPiPM2tCeZMy7T/*,xpub661MyMwAqRbcEbwCpKydkE7KTa2EeMNtZtvSQ8BS1UK2jxVpb9767T5hyBxt67Wa2vev7defUorAFxVvNuSsrMJA34pSDAqj7MYig32Yn12/*,xpub661MyMwAqRbcEnmMnN5ish1Z7tPBfPDKp4wdKhSj6j4UDhiK5bzU6qjE5KnQKw6cQLKg6AhwnPvGmw7A7gsgZqvkEQZDmDqgPUutccd74Wh/*,xpub661MyMwAqRbcEydQM8Y6dCRKkpFszd8xeCFTqiwSUZW7MQ5f249yjRuD8EV43gtkNNxHCDgDmZwy2oVDuAY9pV6sWdBbeU2FuoWGtkERFhV/*,xpub661MyMwAqRbcGNZ4VG1dRWTN2qcsQhz5w4McN9KRXrAECe4toPr44jEtskvCjizC63xM3QnSXyfraFgLqb14ExZUP4QQxnSejCngFjQ8sZz/*,xpub661MyMwAqRbcGHtzSBVBkk166iS6XQgYQnrgu2CHAFL5znv1byy5e4ZjCmZ3ZhugmUx3x91kC5xjyYAQCvtoJXheTyUSQ23y8RWDhH6wbs2/*,xpub661MyMwAqRbcGUuSCPhxc7NDC6Zh4fhecozKEiR7QK7APCVt9Yhyx2NMUd4wrTHYP91G4Fh6Jp9P5Aipf8FjDsrSutkLj3Lie5bCrrM2CfT/*))#9hky7ctt", "timestamp": "now", "active": true}]'

Because of the /* symbol after every xpub I should be able to at least find those address if they are any path bellow the descriptor.
How are you deriving these addresses?

**Comment by willweatherman** [comment]
I just saw the descriptor that I gave you has a typo notice the missing /* after the first xpub.

**Comment by willweatherman** [comment]
Looks like it is a GitHub format thing after every xpub there should be a "/*".

**Comment by willweatherman** [comment]
https://pastebin.com/RfBYjqVS

**Comment by Overtorment** [comment]
I have just noticed that other examples of descriptors I have always end with `/0/*`
and the one you provided ends with `/*`
how to interpret this?
I always do `hdNode.derive(externalOrInternal).derive(index).publicKey` where `externalOrInternal` is either 1 or 0

**Comment by willweatherman** [comment]
I don't know what the derivation path /0/* is compared to /*.

**Comment by willweatherman** [comment]
Using Pastebin because I cant display * https://pastebin.com/TpFvuP8n

**Comment by Overtorment** [comment]
so how do I derive address from your example?

PS. you can use char ` to wrap things up, like this :

 `/*`

**Comment by Overtorment** [comment]
when Im parsing descriptors, I just take xpub and throw away everything after it, doesn't matter if its `/0/*` or `/*` and then to derive addresses I do
`hdNode.derive(externalOrInternal).derive(index).publicKey`

**Comment by willweatherman** [comment]
I don't know what the hdNode stuff is I just use the "Create new receiving address" Button in bitcoin core. Before descriptor wallets, I was using deriveadressses bitcoin core RPC command but I am unsure of the path that used also.

**Comment by willweatherman** [comment]
I would assume that bitcoin core has a BIP explaining the process of derivation but I have yet to find it.

**Comment by willweatherman** [comment]
Hi, I just received a response from some one who has more understanding of the derivation paths and he said he thinks that `m/0'/0'/k'` is how bitcoin core derives external address and `m/0'/1'/k'` is the internal addresses where
m = master key = public key
k = A counter that starts at 0 and increases every time a new address is requested.

**Comment by willweatherman** [comment]
Ok, So I found out that the descriptors contain their own derivation path. So for the descriptor I put out above the path is `/*` which means to replace * with 0 and count upwards every time a new address is requested. According to BIP 32, the path should be `/0/1/*`. The 0 is the account number that should be left at 0. The 1 is whether or not it's a change address 0 for external, 1 for internal. And again the star means start at 0 and work upwards. Yeti has not been using any standards so the path has always been `/*`. But blue wallet should not expect that the descriptor contains the path `/0/0/*`. For bitcoin core, it accepts any two descriptors one for external addresses and one for internal addresses. The only requirement is that the descriptors are not the same. Examples:

`wsh(multi(3,xpub661MyMwAqRbcF13nMmebEmEzQvNH6ZC65QMi6wvmTAvbu957VAWpt2SM7wQiLd5NVudfUpvzpeXNfT5AjhWbbuSKpJ2cssPiPM2tCeZMy7T/0/0/*,xpub661MyMwAqRbcEbwCpKydkE7KTa2EeMNtZtvSQ8BS1UK2jxVpb9767T5hyBxt67Wa2vev7defUorAFxVvNuSsrMJA34pSDAqj7MYig32Yn12/0/0/*,xpub661MyMwAqRbcEnmMnN5ish1Z7tPBfPDKp4wdKhSj6j4UDhiK5bzU6qjE5KnQKw6cQLKg6AhwnPvGmw7A7gsgZqvkEQZDmDqgPUutccd74Wh/0/0/*,xpub661MyMwAqRbcEydQM8Y6dCRKkpFszd8xeCFTqiwSUZW7MQ5f249yjRuD8EV43gtkNNxHCDgDmZwy2oVDuAY9pV6sWdBbeU2FuoWGtkERFhV/0/0/*,xpub661MyMwAqRbcGNZ4VG1dRWTN2qcsQhz5w4McN9KRXrAECe4toPr44jEtskvCjizC63xM3QnSXyfraFgLqb14ExZUP4QQxnSejCngFjQ8sZz/0/0/*,xpub661MyMwAqRbcGHtzSBVBkk166iS6XQgYQnrgu2CHAFL5znv1byy5e4ZjCmZ3ZhugmUx3x91kC5xjyYAQCvtoJXheTyUSQ23y8RWDhH6wbs2/0/0/*,xpub661MyMwAqRbcGUuSCPhxc7NDC6Zh4fhecozKEiR7QK7APCVt9Yhyx2NMUd4wrTHYP91G4Fh6Jp9P5Aipf8FjDsrSutkLj3Lie5bCrrM2CfT/0/0/*))#f8f3nj73`
First address: bc1q82uthafwkj9mecxrz0xv5veqtcr804xn8600l00fkxfncx5m0rgsfq6vln

`wsh(multi(3,xpub661MyMwAqRbcF13nMmebEmEzQvNH6ZC65QMi6wvmTAvbu957VAWpt2SM7wQiLd5NVudfUpvzpeXNfT5AjhWbbuSKpJ2cssPiPM2tCeZMy7T/*,xpub661MyMwAqRbcEbwCpKydkE7KTa2EeMNtZtvSQ8BS1UK2jxVpb9767T5hyBxt67Wa2vev7defUorAFxVvNuSsrMJA34pSDAqj7MYig32Yn12/*,xpub661MyMwAqRbcEnmMnN5ish1Z7tPBfPDKp4wdKhSj6j4UDhiK5bzU6qjE5KnQKw6cQLKg6AhwnPvGmw7A7gsgZqvkEQZDmDqgPUutccd74Wh/*,xpub661MyMwAqRbcEydQM8Y6dCRKkpFszd8xeCFTqiwSUZW7MQ5f249yjRuD8EV43gtkNNxHCDgDmZwy2oVDuAY9pV6sWdBbeU2FuoWGtkERFhV/*,xpub661MyMwAqRbcGNZ4VG1dRWTN2qcsQhz5w4McN9KRXrAECe4toPr44jEtskvCjizC63xM3QnSXyfraFgLqb14ExZUP4QQxnSejCngFjQ8sZz/*,xpub661MyMwAqRbcGHtzSBVBkk166iS6XQgYQnrgu2CHAFL5znv1byy5e4ZjCmZ3ZhugmUx3x91kC5xjyYAQCvtoJXheTyUSQ23y8RWDhH6wbs2/*,xpub661MyMwAqRbcGUuSCPhxc7NDC6Zh4fhecozKEiR7QK7APCVt9Yhyx2NMUd4wrTHYP91G4Fh6Jp9P5Aipf8FjDsrSutkLj3Lie5bCrrM2CfT/*))#9hky7ctt`
First address: bc1qg4wtpw3vn9lv0je3ca679nhpqstmvxqan8mjrj8rkg52snq0hzyqsncezw

**Comment by Overtorment** [comment]
i had a WIP PR for this
https://github.com/BlueWallet/BlueWallet/pull/2458

but im going to close it now till someone complains again
