### ISSUE TITLE
too much nodejs dependencies

### ISSUE THREAD

**Issue by lzunsec** [BlueWallet/BlueWallet#2446]
https://github.com/BlueWallet/BlueWallet/blob/master/package.json relies on TOO MUCH dependencies, which in turn relies on much more dependencies. Who audits all of that?

**Comment by Overtorment** [comment]
we do. really, when we bump deps we glance over the diff, and all versions are pinned. also we use paid audit solution https://snyk.io which is specifically designed to keep an eye on deps.

and yes we have too many of them, and PRs cutting deps are welcome (see https://github.com/BlueWallet/BlueWallet/blob/master/CONTRIBUTING.md )

**Comment by Overtorment** [comment]
i forgot to mention that really risky dependencies (like, from not-reputable/anonymous maintainers) we fork and use under our organization, and when we update them from upstream (rarely) we do review the code

**Comment by Overtorment** [comment]
https://github.com/BlueWallet/BlueWallet/wiki/FAQ
