### ISSUE TITLE
success screen shows wrong value (in sats) after LN payments

### ISSUE THREAD

**Issue by jleo84** [BlueWallet/BlueWallet#2447]
I've installed BlueWallet from TestFlight in a iOS device. After payed 5 sats of an invoice (Lightning wallet), the success screen showed 500000000 sats. It has happened to all Lightning transactions.

However I cloned the code from master branch, ran the code in the simulator and the success screen showed the correct value.
So it's maybe related to the TestFlight version.

**Comment by marcosrdz** [comment]
Yes. This bug is present on older testflight builds. It was a UI bug. It has been fixed and said fix will be included on the next release
