### ISSUE TITLE
Deeplink Bugs on iOS

### ISSUE THREAD

**Issue by normand1** [BlueWallet/BlueWallet#2448]
I'm using an iPhone X
I tried following the directions found here: https://github.com/BlueWallet/BlueWallet/wiki/Deeplinking

First issue is that the deeplinks are shown in this format on the wiki:
`bitcoin:bc1qh6tf004ty7z7un2v5ntu4mkf630545gvhs45u7?amount=666&label=Yo`

When deeplinks in iOS require the `bitcoin://` schema to work unless you're using universal links which these don't appear to be.

Second, I can't seem to get any bitcoin address, other than the one from the example, to be recognized after the deeplink. 

Third, changing the amount in the deeplink doesn't work. The value pre-filled for transfer is always 666 BTC.

**Comment by Overtorment** [comment]
we have a testpage for deeplinks: https://bluewallet.io/testpage/
can you try it from there? there's also one with 0.004 amount

Im not too familiar with deeplinking, but everything works for me, both ios and android. plus, most resources I use don't do douple slashes in address and it still works, e.g.  https://tippin.me/@overtorment

![image](https://user-images.githubusercontent.com/1913337/103479608-d35ec980-4dc6-11eb-9405-1bd05e2b9160.png)

**Comment by normand1** [comment]
I see, thanks for the link, seeing it in action explains a lot. It looks like that deeplink works fine as long as it's wrapped in a with an href tag. The main way I've been testing on my iPhone is to send my self a link via iMessage. iMessage doesn't recognize the `bitcoin:bc1qh6tf004ty7z7un2v5ntu4mkf630545gvhs45u7?amount=666&label=Yo` format. So not a big deal if that's not how you expect the deeplinks to be opened, maybe I'm just misusing them.

I think using tippin.me would actually work perfect for my use case anyway so I'll just use that, thanks!
