### ISSUE TITLE
Lapp browser Q&A

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#245]
- [ ] Use same style for input as in the rest of the app
- [ ] Maybe we need a home icon?
- [ ] There's the need to have a load indicator, no feedback after tapping feels weird
- [ ] Inconsistent title. Marketplace vs Lapp Browser
- [ ] Icon color should be the app main blue

I will keep updating as I go...

**Comment by Overtorment** [comment]
@ncoelho do we have a design for lapp browser..?
