### ISSUE TITLE
Fail to sign

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#2452]
1. construct and sign tx in electrum with a key.
2. move the tx file(psbt) into mobile.
3. In BW android vault- choose 'sign tx'
4. choosing the psbt file asks if i want to co-sign opting yes shows a screen with vault-1 signed but vault-2 unsigned(asking provide sinature)

P.S. BW has one of the keys..

https://t.me/bluewallet/36849

**Comment by mangobtc** [comment]
This issue seems to be a duplicate of https://github.com/BlueWallet/BlueWallet/issues/2401

**Comment by ncoelho** [comment]
Closed in favour of #2401
