### ISSUE TITLE
Prompted for password after fresh App Store Install

### ISSUE THREAD

**Issue by Worst-End-User** [BlueWallet/BlueWallet#2459]
iOS 14.3 (18C66)
BlueWallet 6.0.1

After fresh install via AppStore, opening app shows slash screen but then UI Alert with text box “Enter Password” “Your storage is encrypted. Password is required to decrypt it”

Ive installed BlueWallet in the past. Where is this coming from?

-

**Comment by ncoelho** [comment]
BlueWallet has a security feature on iOS that allows to keep the storage when the app is uninstalled. 

Settings > storage

To clean the storage fail the password 10 times.
