### ISSUE TITLE
Multisig transaction from Electrum isn't signed

### ISSUE THREAD

**Issue by vbnmvhnhjk** [BlueWallet/BlueWallet#2479]
When trying to sign a multisig transaction imported from Electrum, either via psbt or QR code, Blue gives the option to "sign" it, but it doesn't actually seem to sign it because it can't be broadcast. If the "share" option is selected and the resulting psbt is imported back into Electrum it seems that the signature from Blue hasn't been added (ie. it's the same psbt as before).

For info, this is a 3 of 4 multisig wallet. Two of the signatures needed to sign have been added to the transaction using Electrum before it is imported into version 6.02 of Blue Wallet.

**Comment by Overtorment** [comment]
so, when you sign with BW, if its the final signature, it should allow you to navigate further to the broadcast screen, and you can try to broadcast or copy txhex and verify it with some 3rd party tool. can you do that?

currently, if you take PSBT from BW and try to feed it to electrum it might not work because there will be fingerprint and derivation path mismatch.
to make it work you need to set up multisig on electrum completely, save backup file (File->Save backup) and import this file in bluewallet. this way paths & fingerprints should match, and you can start transaction on BW and finish signing it on electrum (we have a ticket to improve that: https://github.com/BlueWallet/BlueWallet/issues/2475 )

**Comment by vbnmvhnhjk** [comment]
It won't allow me to navigate further to the broadcast screen. So it seems to sign it, but that's it. After that the only option is to share.

I'm not totally sure how setting it all up on Electrum would work since one of the signers in the quorum is on BW only, but I'll give it a go.

**Comment by Overtorment** [comment]
>> It won't allow me to navigate further to the broadcast screen.

is the button to navigate further disabled? can you post a screenshot of that screen? 
maybe BW didn't actually do a signature, so there is not enough signatures

**Comment by vbnmvhnhjk** [comment]
After pressing to provide cosignature, this is the next screen. But bear in mind this transaction has already been signed by to cosigners prior to this (I doubled checked it in Electrum). If I hit "provide signature" it then goes to a screen to provide another signature. So my suspicion is that BW didn't really sign it prio
![ima_ee3e4b7](https://user-images.githubusercontent.com/77191785/104091699-e0703280-5276-11eb-9d9b-b9be7f5fa182.png)
r to this.

**Comment by vbnmvhnhjk** [comment]
It looks like this could be an iOS thing. I tried importing the Electrum backup file into the iOS version and it wouldn't import, it just went back to the main screen. Whereas with Android it did import.

**Comment by Overtorment** [comment]
yep, looks like BW didnt sign it.

can you walk me through the steps needed to create such wallet so I can try to replicate the issue?
so, its 3of4 multisig created on electrum, desktop, right..?

**Comment by vbnmvhnhjk** [comment]
Yes, 3 of 4 created on Electrum desktop and Blue Wallet. So seeds were created on 3 different computers plus BW. Some funds were sent to the wallet then a transaction was created to spend the funds. A signed psbt was saved from one computer, sent to another and signed, then sent to the BW wallet, but of course it couldn't then be signed after that.

**Comment by Overtorment** [comment]
Im lookign into this right now. 
what was Electrum's version?

**Comment by Overtorment** [comment]
at least electrum 4.0.4 required, they had bugs with psbt multisig prior to that

**Comment by vbnmvhnhjk** [comment]
it's the latest version - 4.09.

**Comment by Overtorment** [comment]
could not reproduce. 
I recreated setup - created 3of4 multisig, 3 of them were electrum desktop, each holding a key.
4th cosigner was BW,  I took it's Zpub to finalize creation of wallets on electrums.

__all wallets agree on first receiving address__


I then create transaction on first electrum, export it to psbt file.
then I import this file in second electrum (tools -> load transaction), it shows that this transaction has only 1 sig: _'Status: Partially signed (1/3)'_, I press Sign button, and now transaction
has 2 signatures. 
I press Export -> Show as QR code, and sign it with BW no prob

https://user-images.githubusercontent.com/1913337/104498508-acc53d80-55d3-11eb-9f50-c5cc341aa941.mp4

**Comment by Overtorment** [comment]
can you make sure that BW has at least one signing key? You can check it by going to "manage keys" to see how many signarutes BW can make.
can you make sure that transaction that goes into BW has 2 signatures?

**Comment by vbnmvhnhjk** [comment]
it does have one signing key for sure and the transaction does have two signatures, but I will try it again. I'm glad it worked for you. Thanks so far!

**Comment by vbnmvhnhjk** [comment]
Could you try importing a psbt into BW?

**Comment by Overtorment** [comment]
I imported PSBT 2 ways, by scanning QR code and by importing .psbt file, both ways worked fine

**Comment by vbnmvhnhjk** [comment]
OK, I've tried it again and the issue was that BW seems to hang after it signs the transaction but it DOES sign it eventually. Thanks to your video, which was super useful, I was able to see the expected behaviour of the app. But I think perhaps it could be improved by adding something like "please wait" or a spinning icon or something, so that it's obvious the app is doing something. Anyway, the problem has been resolved so I think this can be closed :+1:

**Comment by Overtorment** [comment]
Ive added spinner so its obvious that app is doing something here: https://github.com/BlueWallet/BlueWallet/pull/2498
will be out in next release. cheers!
