### ISSUE TITLE
Option to exclude transactions 

### ISSUE THREAD

**Issue by klauslovgreen** [BlueWallet/BlueWallet#248]
Please consider a toggle option to exclude transactions in the general overview of transactions when a single wallet is not selected. This can be handy for read-only wallets when just wanting to keep an eye on an address it but does not the transactions to show up among the transactions of the main wallets.

**Comment by Overtorment** [comment]
acknowledged

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/1220
