### ISSUE TITLE
Coin Control screen not loading

### ISSUE THREAD

**Issue by groundstart** [BlueWallet/BlueWallet#2481]
Coin Control screen will not complete loading during Lightning Refill -- spinner hangs on both GrapheneOS and iOS.

No issue on macOS.

All devices running BlueWallet v6.0.2.

**Comment by groundstart** [comment]
> Coin Control screen will not complete loading during Lightning Refill -- spinner hangs on both GrapheneOS and iOS.
> 
> No issue on macOS.
> 
> All devices running BlueWallet v6.0.2.

Discovered same issue with Send from BTC wallet, then selecting Coin Control.

**Comment by limpbrains** [comment]
Can't reproduce the issue. 
Couple of questions:
Do you have this issue with the same wallet imported on two devices?
What is the wallet type?
Are you using default electrum settings? Do you have internet connection when you open coin control?
Do you have the same issue if you import this wallets xpub as a watch-only wallet?
If it is possible, can you please share your xpub? Better do it privately, you can email to bluewallet@bluewallet.io or contact me in telegram, I'm "limpbrains" there. 
Also, if you share your public ip, @Overtorment will be able to find error log. Also better do it by email.

**Comment by limpbrains** [comment]
@groundstart We believe that the problem was with the poor internet connection. BW now will handle this properly. In the next release
