### ISSUE TITLE
Error message when attempting to send from Multisig Vault

### ISSUE THREAD

**Issue by Albion2** [BlueWallet/BlueWallet#2482]
Version 6.0.2
Android + iOS

When sending from multisig wallet, receipt of prompt 'Alert - Can not finalize input #1'.

![paste](https://user-images.githubusercontent.com/77217002/104112382-0f71bd00-52e6-11eb-9eaa-6751c29f0b3a.png)

**Comment by Overtorment** [comment]
can you share more details?
how was the wallet created? which cosigners etc

**Comment by jessduarte** [comment]
I'm having the same problem.

I created 2 multisig wallets in Bluewallet.  I am trying to send coin from one multisig wallet to another multisig wallet. 

I get the error: Can not finalize input #1.

I'm using BlueWallet ver 6.0.3 (build 1610750144)

I am connected to electrum1.bluewallet.io:443

**Comment by ncoelho** [comment]
Anyone can help us reproduce this problem.

1. A video of the problem happening
2. Steps to reproduce
3. Sharing Zpubs to build a transaction

For privacy bluewallet@bluewallet.io
