### ISSUE TITLE
Updated Bluewallet iOS app, lost wallet with $500 in BTC

### ISSUE THREAD

**Issue by slavik0329** [BlueWallet/BlueWallet#2499]
Hi, I have had one of the earlier versions of bluewallet installed. I've had it for at least a year and a half. I was in the lightening wallet today and I saw my balance was there and I decided to update to latest version. Upon opening the app after update, it asked me to create a new wallet. My wallet was not in the app. Is there anything i can do??

Thanks in advance!

**Comment by marcosrdz** [comment]
Whenever a wallet is created, a set of words is provided for the user to write and keep somewhere safe. These set of words are what is used to import a wallet. In the case of a lightning wallet, a login with an URL is shown to the user when they
Create a wallet.

**Comment by slavik0329** [comment]
@marcosrdz I understand. When I created the wallet it was worth significantly less. I'm just confused as to why an update of an app would wipe the wallet without warning? And also if there's any way to revert the version.

**Comment by BluewalletAdmin** [comment]
Hello @slavik0329 is the issue resolved yet? You'll have to rectify with the bluewallet loptimal weblink.
