### ISSUE TITLE
Add lapps on kriptode.com for marketplace

### ISSUE THREAD

**Issue by pseudozach** [BlueWallet/BlueWallet#251]
First very nice feature, thanks as a user.
Second, can you add my lapps on kriptode.com to this or should I do a pr maybe to the bluewallet.io website repository?

**Comment by Overtorment** [comment]
I especially liked  'Receive SMS' - that one can be added to marketplace. Its a fine addition to https://lnsms.world
Can you add it via pull request to website repo..?
