### ISSUE TITLE
Question: Does Blue Wallet downloads the Bitcoin Headers?

### ISSUE THREAD

**Issue by igorgue** [BlueWallet/BlueWallet#2515]
Hi guys,

After looking at the code I see no place you call `blockchain.block.headers` so I'm wondering how do you guys deal with the headers, how can you make sure you follow the correct chain in order to make sure you're spending a confirmed UTXO?

**Comment by Overtorment** [comment]
The idea is that by default BW doesn’t use public electrum servers, only
ones hosted by bluewallet, so they are kinda trusted. And user has an
option to change electrum server to something he provides, so he knows what
is he doing and trusting his own electrum server.

We would definitely need proper SPV verification if we used  random
electrum server every time from a pool of public servers.

**Comment by Overtorment** [comment]
https://github.com/BlueWallet/BlueWallet/wiki/FAQ
