### ISSUE TITLE
iOS 14.5 beta 1 crash upon launch

### ISSUE THREAD

**Issue by bholm** [BlueWallet/BlueWallet#2561]
I've noticed that since updating to iOS 14.5 beta 1, BlueWallet fails to launch. It just immediately crashes.

**Comment by Overtorment** [comment]
@marcosrdz

**Comment by newtonick** [comment]
Same experience here. Also happens to other apps. Like my Microsoft apps.

**Comment by MoNTE48** [comment]
Same issue on macOS 11.3 beta 1

**Comment by newtonick** [comment]
> Same experience here. Also happens to other apps. Like my Microsoft apps.

The updated build of iOS 14.5 beta 1 fixes the Microsoft apps, but BlueWallet continues to crash on launch.

**Comment by marcosrdz** [comment]
https://github.com/realm/realm-js/issues/3557

Seems to be an issue with Realm. Keeping an eye on this

**Comment by Overtorment** [comment]
@marcosrdz  
![image](https://user-images.githubusercontent.com/1913337/107370669-308f1e80-6adb-11eb-8600-97c7a2f3058c.png)

and we have a PR to upgrade realm to 10

**Comment by MoNTE48** [comment]
https://github.com/BlueWallet/BlueWallet/commit/c3ca89d096dc7590bbcdf470376b28c20a3fd730

**Comment by ncoelho** [comment]
Beta release with the crash fix here:

https://t.me/bwalphabeta/1883

**Comment by marcosrdz** [comment]
> Same issue on macOS 11.3 beta 1
> 
> ```
> 
> Application Specific Information:
> 
> dyld: in dlopen()
> 
> /System/iOSSupport/System/Library/AccessibilityBundles/AnnotationKit.axbundle/Contents/MacOS/AnnotationKit
> 
> *** Terminating app due to uncaught exception 'RCTFatalException: Unhandled JS Exception: TypeError: Attempting to change configurable attribute of unconfigurable property.', reason: 'Unhandled JS Exception: TypeError: Attempting to change configurable attribute of unconfigurable property., stack:
> 
> defineProperties@(null):(null)
> 
> <unknown>@884:11643
> 
> <unknown>@863:1471
> 
> v@2:1473
> 
> <unknown>@822:1054
> 
> v@2:1473
> 
> <unknown>@821:84
> 
> v@2:1473
> 
> <unknown>@535:1633
> 
> v@2:1473
> 
> <unknown>@419:247
> 
> v@2:1473
> 
> <unknown>@6:88
> 
> v@2:1473
> 
> d@2:875
> 
> global code@2065:3
> 
> '
> 
> terminating with uncaught exception of type NSException
> 
> abort() called
> 
> ```
This has been reported to Realm (the dependency causing this crash). We are keeping an eye on this.
