### ISSUE TITLE
Custom fee cancelation on iPadOS 14.4 fade into black screen

### ISSUE THREAD

**Issue by Sh0ham** [BlueWallet/BlueWallet#2568]
Instead of getting back to fees options like on iOS; I guess it's about the screen size

**Comment by marcosrdz** [comment]
Hello! Any chance you can provide a screenshot? Im debugging this issue.

**Comment by Sh0ham** [comment]
https://user-images.githubusercontent.com/24498412/107196725-a623bd80-69fb-11eb-98d0-1b9e713a1d20.MP4


https://user-images.githubusercontent.com/24498412/107196746-ad4acb80-69fb-11eb-9d0c-d7420a92616e.MP4

Two versions as iPad allow to shrink the keyboard; while it's full size it behave better

**Comment by Sh0ham** [comment]
> Hello! Any chance you can provide a screenshot? Im debugging this issue.

Two versions as iPad allow to shrink the keyboard; while it's full size it behave better


https://user-images.githubusercontent.com/24498412/107196879-de2b0080-69fb-11eb-9951-c7f0d8b8b105.MP4


https://user-images.githubusercontent.com/24498412/107196899-e420e180-69fb-11eb-83e0-08fa59ea54c8.MP4
