### ISSUE TITLE
FIX: Amounts not showing up in Farsi version

### ISSUE THREAD

**Issue by mcsaeid** [BlueWallet/BlueWallet#2592]
In some instances, the amounts do not show up at first when the app starts. This was tested on two Android phones, both running the latest version of the app. Please test to see if you can re-create the bug.

![d023182c-a75e-4503-80f4-88233afcb35a](https://user-images.githubusercontent.com/63400670/107236720-38978180-6a3b-11eb-9da7-1a14222f46e6.jpg)
![da210b2d-daa0-4f4d-a412-7d88ea7e8fef](https://user-images.githubusercontent.com/63400670/107236727-3a614500-6a3b-11eb-9628-f2d99ce80cf0.jpg)
![185b768c-dcb7-4307-b514-80b2004572e8](https://user-images.githubusercontent.com/63400670/107236758-3e8d6280-6a3b-11eb-8825-e6f6be3f53d1.jpg)

I also used the Appetize version (the latest found [here](https://github.com/BlueWallet/BlueWallet/pull/2572)). Oddly, I ran into the same thing, but in a different scenario. When I was _switching_ between currencies ($, BTC, and sats), this happened again.

![2021-02-08 18-22-24 High Res Screenshot](https://user-images.githubusercontent.com/63400670/107236773-40efbc80-6a3b-11eb-81cf-7d17d8634476.png)

**Comment by limpbrains** [comment]
What Currency do you have in Settings? Can you please check same Language, but different Currency ?

**Comment by mcsaeid** [comment]
The default currency, the USD. Being on the latest version, the only variable that I can think of the language. This doesn’t happen with English. Here is a recording, in which I try two different currencies, the United States dollar and the Australian dollar, both in the Farsi version. Feel free to check for yourself. Once I start switching between the currencies, at least one of them comes up blank. Sometimes it is the fiat currency, sometimes BTC.

https://user-images.githubusercontent.com/63400670/107354766-cdee5080-6ae3-11eb-93d7-60aa0a343c02.mp4
