### ISSUE TITLE
Feature Request: Copying Block Explorer Link

### ISSUE THREAD

**Issue by mcsaeid** [BlueWallet/BlueWallet#2597]
There lacks a feature that allows the user to copy the block explorer link (for archival purposes or to send to others) without opening the link (which may reduce privacy).

One could copy the transaction ID and look up the transaction, but that obviously isn’t convenient. You could take this further and add a short URL feature.

![Screenshot](https://user-images.githubusercontent.com/63400670/107390555-0eae8f80-6b0d-11eb-8db8-6ab0367da404.jpg)

**Comment by Overtorment** [comment]
imo this is overthinking and overengineering

**Comment by mcsaeid** [comment]
@Overtorment Understandable. I personally have to do all the above to get the URL, either to save it somewhere or to share it with someone. Since all the other details have the same _copy_ functionality, I thought it made sense for this to have it as well. It is certainly not a priority, but I would love to see it implemented one day. Cheers.
