### ISSUE TITLE
deeplinking support for BIP21 w/BOLT11

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#260]
Example: https://github.com/BlueWallet/BlueWallet/issues/257

This scheme should also be handled at deeplinking. If it has both `bitcoin:` and `&lightning=` deeplinking should offer bitcoin AND lightning wallets to send from

**Comment by Overtorment** [comment]
@marcosrdz can u pls..?

**Comment by marcosrdz** [comment]
Sure

**Comment by joaodealmeida** [comment]
Shouldn't it be lightning:xx instead of lightning=xx ?

**Comment by ncoelho** [comment]
what's the status?

**Comment by Overtorment** [comment]
@marcosrdz I think this is done?

**Comment by marcosrdz** [comment]
Nope. Its on my list of todos

**Comment by marcosrdz** [comment]
Working on this now.

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/764/files
