### ISSUE TITLE
Releases - version number issues

### ISSUE THREAD

**Issue by maltokyo** [BlueWallet/BlueWallet#2613]
Why does 6.0.4:
![image](https://user-images.githubusercontent.com/1388507/107750281-1c862f80-6d1c-11eb-89dd-a6ad51e03165.png)

Have 6.0.5 assets:
![image](https://user-images.githubusercontent.com/1388507/107750339-30ca2c80-6d1c-11eb-8a0b-b7fc8a674c15.png)

**Comment by ncoelho** [comment]
We had to revert a commit and bump the version. So it is 6.0.5, the title and tagging were not updated, just that.

**Comment by maltokyo** [comment]
ok, just wanted to inform you.  I wanted to get apk, and didn't as I wasn't sure if someone replaced the file somehow.
