### ISSUE TITLE
Importing AEZEED wallet

### ISSUE THREAD

**Issue by rmerka** [BlueWallet/BlueWallet#2614]
When importing an AEZEED wallet created with LND, the app repeatedly asks for the decryption key/unlock passphrase on both iOS and Android. Import ultimately fails.

**Comment by Overtorment** [comment]
hello! are you inputing correct password for your aezeed seed?
if it asks again then it means the previous one was incorrect. if you provide blank it will stop asking.

if you want to make sure it works, here's an aezeed `able mix price funny host express lawsuit congress antique float pig exchange vapor drip wide cup style apple tumble verb fix blush tongue market` with password `strongPassword`

and here's an aezeed without password: `able concert slush lend olive cost wagon dawn board robot park snap dignity churn fiction quote shrimp hammer wing jump immune skill sunset west`


also, there are chances that your aezeed is of some very old version Im not aware of

**Comment by rmerka** [comment]
I'm definitely entering my password correctly. Your test mnemonic and password worked fine for me.  My my wallet was created with Lnd 0.12.0-Beta.  It's probably worth noting that my password contains a special character. It's not just letters/numbers

Thanks!

**Comment by Overtorment** [comment]
@rmerka could you please reproduce the issue on the new mnemonic and post it here? Ill try to debug

PS. just had a though - is one of special characters a semicolon (`:`) ?

**Comment by rmerka** [comment]
I'll give it a shot.  I don't think the special character is the issue now (it was a $).  I changed the password on the wallet of my Lnd node and I'm still getting the issue.  I've got to find out if I'm going to mess up any of my channels, I've got a lot open right now, if I start mucking about with my wallet before I do it.

**Comment by Overtorment** [comment]
is it still happening?

**Comment by rmerka** [comment]
You know I had put it way on the back burner as just didn't want to shut down my node and close all my channels.  But I updated BW today on my phone and gave it a shot and it worked, no problems.  Thank you for your help, it appears to have resolved itself.
