### ISSUE TITLE
Small tablet Screen unusable QR

### ISSUE THREAD

**Issue by trafficpest** [BlueWallet/BlueWallet#2625]
Small Tablets >8in are partially unusable. The screen mode goes into computer version (wallet list as side bar) problem is these tablets are too small to show the QR horizontal (it's vertically clipped) and vertically the side bar clips the QR horizontally.

Fixes would be...Allow scaling the QR, Collapsible side bar, menu option for app display, or the best and cleanest is force phone display till larger display is used.

Tablets used were amazon fire 7 in (600x1024)  and amazon fire 8 HD  (800x1280) the 8 literally was just pixels short probably 850 and up fine

Thank you and THIS IS the best wallet!

**Comment by Overtorment** [comment]
some screenshots would be appreciated. thanks!

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/2566

**Comment by trafficpest** [comment]
![IMG_20210215_102807824](https://user-images.githubusercontent.com/79076910/107982747-78012900-6f79-11eb-808d-bb28c5f45532.jpg)
![IMG_20210215_102734022](https://user-images.githubusercontent.com/79076910/107982759-7f283700-6f79-11eb-8084-b99582267f17.jpg)
