### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'delete c[_.param].hex')

### ISSUE THREAD

**Issue by cconcannon** [BlueWallet/BlueWallet#2633]
I can't load transactions for my wallets in the app. The wallet balances show correctly, but when I try to refresh in order to view transactions I get the error:

`TypeError: undefined is not an object (evaluating 'delete c[_.param].hex')` 

I ran the self-test inside the BlueWallet app and the same error above came up as the self-test result.

I'm running BlueWallet version 6.0.5 (build 1612982073) on an iPhone 11 with iOS 14.4

Screenshots attached to show version details and self-test result.

![IMG_2754](https://user-images.githubusercontent.com/16453494/108103218-79e0f000-703e-11eb-8ef8-65eef9e700bd.PNG)
![IMG_2753](https://user-images.githubusercontent.com/16453494/108103227-7cdbe080-703e-11eb-8020-ffebc10effa4.PNG)

**Comment by marcosrdz** [comment]
Are you connected to a custom server?

**Comment by cconcannon** [comment]
Yes, I specified a url for the Electrumx server that I connect to

**Comment by marcosrdz** [comment]
Can you remove the custom Electrum server, by using the default, and restart the app? Let us know if the same error is encountered

**Comment by cconcannon** [comment]
Removing the custom Electrum server removed the error. Is there anything I can do to make BlueWallet work seamlessly with the custom Electrum Server? The main reason I’m using BlueWallet is because it allows connection to a custom Electrum server. The server I’m trying to use is the most recent version of spesmilo/electrumx.

**Comment by ncoelho** [comment]
There’s something wrong with your server, maybe not indexed correctly.
Bluewallet is also using electrumX

**Comment by Overtorment** [comment]
Maybe you can share your server's ip privately to bluewallet@bluewallet.io ?
Will debug

**Comment by cconcannon** [comment]
just sent you an email with the server IP address, thanks!

**Comment by Overtorment** [comment]
@cconcannon I debugged your server, and looks like your bitcoind is running without `-txindex`, so electrum can't index all data.
the error I got from your electrum is :
```
daemon error: DaemonError({'code': -5, 'message': 'No such mempool transaction. Use -txindex or provide a block hash to enable blockchain transaction queries. Use gettransaction for wallet transactions.'})
```

where other electrum servers respond okay.


if you want to debug it yourself, here's the console command that queries regular electrum server:

```
$ echo '{"id": 1, "method": "blockchain.transaction.get", "params": ["881c54edd95cbdd1583d6b9148eb35128a47b64a2e67a5368a649d6be960f08e"]}' | timeout 2 nc electrum1.bluewallet.io  50001 -i 1
{"jsonrpc": "2.0", "result": "02000000000102f1155666b534f7cb476a0523a45dc8731d38d56b5b08e877c968812423fbd7f3010000000000000000d8a2882a692ee759b43e6af48ac152dd3410cc4b7d25031e83b3396c16ffbc8900000000000000000002400d03000000000017a914e286d58e53f9247a4710e51232cce0686f16873c870695010000000000160014d3e2ecbf4d91321794e0297e0284c47527cf878b02483045022100d18dc865fb4d087004d021d480b983b8afb177a1934ce4cd11cf97b03e17944f02206d7310687a84aab5d4696d535bca69c2db4449b48feb55fff028aa004f2d1744012103af4b208608c75f38e78f6e5abfbcad9c360fb60d3e035193b2cd0cdc8fc0155c0247304402207556e859845df41d897fe442f59b6106c8fa39c74ba5b7b8e3268ab0aebf186f0220048a9f3742339c44a1e5c78b491822b96070bcfda3f64db9dc6434f8e8068475012102456e5223ed3884dc6b0e152067fd836e3eb1485422eda45558bf83f59c6ad09f00000000", "id": 1}
```


and here's how your server responds:


```
$ echo '{"id": 1, "method": "blockchain.transaction.get", "params": ["881c54edd95cbdd1583d6b9148eb35128a47b64a2e67a5368a649d6be960f08e"]}' | timeout 2 nc YOUR_IP_ADRESS  50001 -i 1
{"jsonrpc": "2.0", "error": {"code": 2, "message": "daemon error: DaemonError({'code': -5, 'message': 'No such mempool transaction. Use -txindex or provide a block hash to enable blockchain transaction queries. Use gettransaction for wallet transactions.'})"}, "id": 1}
```

**Comment by Overtorment** [comment]
https://github.com/BlueWallet/BlueWallet/pull/2665

**Comment by cconcannon** [comment]
With your help here I was able to figure out that my bitcoin node was not reading a config file correctly on startup, so reboots were not using -txindex. I was able to fix the issue and verify the above commands give the expected response from my custom ElectrumX server. 

I really appreciate the help!
