### ISSUE TITLE
New Missing Strings for Translation

### ISSUE THREAD

**Issue by mcsaeid** [BlueWallet/BlueWallet#2645]
Missing strings left untranslated. This issue is not exclusive to Persian. Please add the following strings to the Transifex project so they can be translated. Here is a new list (besides #2301) that I have been able to come up with so far.

![1  General](https://user-images.githubusercontent.com/63400670/108376916-bcf6bb00-7218-11eb-901f-0c9654166bee.jpg)
1. Settings > General
1a. Page Title (General)

![2  Currency](https://user-images.githubusercontent.com/63400670/108376971-cb44d700-7218-11eb-8e32-320c86ca9688.jpg)
2. Settings > Currency
2a. Page Title (Currency)

![3  Network](https://user-images.githubusercontent.com/63400670/108377030-d861c600-7218-11eb-8da3-6442706caa9b.jpg)
3. Settings > Network
3a. Page Title (Network)

![4  Electrum Settings](https://user-images.githubusercontent.com/63400670/108377072-e44d8800-7218-11eb-83db-d77dc66a2094.jpg)
4. Settings > Network > Electrum Server > Electrum Settings
4a. Page Title (Electrum Settings)
4b. Notice that the title is not the same as the button, “Electrum Server,” or it should be “Electrum Server Settings.”
4c. There is something weird going on in the description text. I will have to look into that.

![5  Privacy](https://user-images.githubusercontent.com/63400670/108377225-0e06af00-7219-11eb-90dc-1e4c9abb2df8.jpg)
5. Settings > Privacy
5a. Page Title (Privacy)

![6  Notifications](https://user-images.githubusercontent.com/63400670/108377252-14952680-7219-11eb-9dc8-92c92b444a10.jpg)
6. Settings > Notifications
6a. Page Title (Notifications)

![7  About](https://user-images.githubusercontent.com/63400670/108377283-2080e880-7219-11eb-9338-3f24630eb21e.jpg)
7. Settings > About
7a. Page Title (About)

![8  Self-Test](https://user-images.githubusercontent.com/63400670/108377314-28d92380-7219-11eb-9609-6b513ce879cd.jpg)
8. Settings > About > Self-Test
8a. Page Title (Self-test)
8b. Text (OK)
8c. Also, please notice that the majority of the page is just blank. I think either the text could be modified to say something more, or it should be something a little bit more visual (like a button).

![9  Re-order Wallets](https://user-images.githubusercontent.com/63400670/108378467-435fcc80-721a-11eb-801d-c534fa9b9ba7.jpg)
9. Re-order Wallets
9a. Page Title (Re-order Wallets)

Thank you for the hard work. I appreciate it.

**Comment by limpbrains** [comment]
Majority of these issues fixed in #2626. It's already merged and will be fixed in next release. You can test it appetize there

**Comment by mcsaeid** [comment]
Perfect. I will check these on Appetize and update the issue. Thanks.

**Comment by mcsaeid** [comment]
Everything looks good. Great job, @limpbrains.

Please take a look at **4b**¹, **4c**, and **8c**.

¹ Electrum Server > Electrum Settings (different titles)
