### ISSUE TITLE
Sats Not Displaying Correctly in Persian

### ISSUE THREAD

**Issue by mcsaeid** [BlueWallet/BlueWallet#2646]
The number of satoshis is displayed incorrectly in Persian, as well as in Arabic (languages that are written from right to left). The amount is displayed backward. For example, 0.00008911 BTC should be “8 911 sats,” whereas right now, it is “911 8 sats.”

It should be displayed correctly without space acting as the thousands separator, but I am sure you can fix it without having to remove the space (which, in my opinion, not only looks good but helps readability as numbers can get quite large with sats). Please take a look at the screenshots below.

![BTC](https://user-images.githubusercontent.com/63400670/108399399-503aeb00-722f-11eb-9d6b-b589e9d52a39.jpg)

![Sats](https://user-images.githubusercontent.com/63400670/108398801-ab201280-722e-11eb-9a1d-3a164318b4f3.jpg)

**Comment by marcosrdz** [comment]
Hello! 
-What are your Currency and Language settings on BlueWallet.
- What are your language and region settings on your system settings?

**Comment by mcsaeid** [comment]
My default currency in the app settings is the USD. As mentioned above, I have tested this with both Persian (فارسی) and Arabic. The issue seems to derive from languages that support RTL writing.

I am using an iOS device. The language is English, and the region is set to the United States (both default settings).

**Comment by marcosrdz** [comment]
Replicated. Will work on a fix. Thank you!

**Comment by mcsaeid** [comment]
Perfect. Thank _you_.
