### ISSUE TITLE
UI streamlining

### ISSUE THREAD

**Issue by TomasHo** [BlueWallet/BlueWallet#266]
A small UI improvement suggestion(iOS/Android?):
When you click Receive/Send, you have to do an extra click for numpad to pop up.
I suggest the app goes directly to "amount" field and the numpad pop up.

And it goes the same for onchain/offchain txs.

**Comment by Overtorment** [comment]
Pefrectly valid suggestion. Thanks!

**Comment by ncoelho** [comment]
Keyboards should start closed.

**Comment by Overtorment** [comment]
UX god said
