### ISSUE TITLE
Amount denomination changing on scanQR

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#2662]
1. Change denomination from btc to fiat
2. scan a QR code
3. $1000 become 1000 btc

**Comment by limpbrains** [comment]
I don't think this is a bug. I'm refactoring Send screen right now and it is in the code - when you scan qrcode, unit changes to BTC. Because usually amount it qrcode is in BTC

**Comment by limpbrains** [comment]
> Set $10 dollars, scan an address (no amount) value switches to 10 btc automatically after scan. Very dangerous at least :D

Agree, for qrcode without amount.

**Comment by Overtorment** [comment]
hmm. i thought i fixed something like this (or very similar)

**Comment by limpbrains** [comment]
Tested it again. 
If you scan qr code with no amount, just address, it doesn't change the denomination.
If you scan qr code with amount, denomination changes to BTC
I believe there is no bug.

**Comment by ncoelho** [comment]
Steps to reproduce
- wallet is in btc
- on send screen change to fiat
- insert $10
- scan QR code with address
- amount is 10 btc

**Comment by limpbrains** [comment]
> Steps to reproduce
> 
>     * wallet is in btc
> 
>     * on send screen change to fiat
> 
>     * insert $10
> 
>     * scan QR code with address
> 
>     * amount is 10 btc

Can't reproduce. When I'm scanning qr code with address (like first one from bluewallet test page) denomination remains in USD
I'm on testflight 6.0.7 (1614833433)

**Comment by limpbrains** [comment]
To reproduce this you need to switch currency to BTC for the wallet
