### ISSUE TITLE
Lightning Refill amount doubled

### ISSUE THREAD

**Issue by japaweiss** [BlueWallet/BlueWallet#269]
![screenshot_20190122-085307](https://user-images.githubusercontent.com/13430816/51520213-f468c280-1e1a-11e9-872d-821e1712550b.jpg)

**Comment by japaweiss** [comment]
Paid some satoshi. Now it is displayed correctly

**Comment by Overtorment** [comment]
Thanks for the report!
Fixed yesterday in https://github.com/BlueWallet/LndHub/issues/8#issuecomment-456303433
