### ISSUE TITLE
Android back button

### ISSUE THREAD

**Issue by plengkeek** [BlueWallet/BlueWallet#271]
Found that the Android back button does not work when you try to go back from transaction details. Additionally, when you use the back button in the lightning market place browsing a site instead of bringing you back to the list of all the applications it closes the marketplace. Hope this is clear enough.

Blue Wallet 3.6.2 
Android 9.0.3

**Comment by Overtorment** [comment]
Acknowledged.

**Comment by marcosrdz** [comment]
b763f77
