### ISSUE TITLE
App crashing when there is no network

### ISSUE THREAD

**Issue by klauslovgreen** [BlueWallet/BlueWallet#272]
App crashes when launched and there is no internet connection. Try to start the app in flight mode to see the effect. Suggest a basic error message of some sort also to make the user aware that the balances are not updated.  

Version 3.6.2 build 1547924886 - iPhone XS running iOS 12.1.2

**Comment by Overtorment** [comment]
Just tried on 2 ios devices, could not reproduce

**Comment by klauslovgreen** [comment]
Odd - this is mine, just closed - can't click on the accounts:
https://www.icloud.com/photos/#0xE1xVYVyJzsVlQj5tulYiWWQ

I tried to install on another device and it worked there, maybe I need to reinstall bluewallet.  

I still think the app should state clearly that there is no network connection and that the info may not be up to date.

If you click on send/receive in a Lightning wallet the the amount is grayed out and when pressing the digit it closes the send/receive dialog.

**Comment by Overtorment** [comment]
Acknowledged.
