### ISSUE TITLE
Single sig - in watch only creating unsigned tx - only available with bc1 pub master key 

### ISSUE THREAD

**Issue by 2pac1** [BlueWallet/BlueWallet#2735]
Hey guys,
  
Send button is missing if you import legacy segwit pub master key, segwit wrapped master pub key but it is only present (send button that is) when you import pub master key from native segwit (bc1).

Does that mean that it is not possible to create an unsigned transaction with anything other than anything other then native segwit master pub key?

Tnx

**Comment by 2pac1** [comment]
I would like to request a feature where BlueWallet would support creating unsigned transactions while using master pub Segwit P2SH (wrapped) key.

**Comment by Overtorment** [comment]
are you talking about extended pubkey for p2sh segwit? which is ypub?

**Comment by 2pac1** [comment]
When importing master pub key for P2SH-P2WPKH wallet with addresses
starting with prefix 3, you cannot create unsigned tx (send button is
missing).
So, P2SH-segwit master pub key doesn't not work in this scenario.

While bech32 master pub key can create unsigned tx.

Anything that can be done so P2SH-segwit (3) has this same functionality?
So yes, I would like to see functionality for creating unsigned tx with
ypub and now that is only available with zpub.


Thank you

**Comment by Overtorment** [comment]
acknowledged.
@limpbrains maybe you would be interested in making it happen?
a bit of work here required - you would need also to make it work with HW wallets, because those features are bound together

**Comment by wallclockbuilder** [comment]
> acknowledged.
> 
> @limpbrains maybe you would be interested in making it happen?
> 
> a bit of work here required - you would need also to make it work with HW wallets, because those features are bound together

Interested.

**Comment by limpbrains** [comment]
> > acknowledged.
> > @limpbrains maybe you would be interested in making it happen?
> > a bit of work here required - you would need also to make it work with HW wallets, because those features are bound together
> 
> Interested.

Are you interested in implementing this feature? If so, go for it. I haven't started yet.

**Comment by wallclockbuilder** [comment]
Go ahead and assign it to me.

**Comment by Overtorment** [comment]
@wallclockbuilder for the win!!!

**Comment by wallclockbuilder** [comment]
I'm happy to help.

**Comment by jaonoctus** [comment]
@wallclockbuilder any news?

**Comment by 2pac1** [comment]
Looking forward to the update.

**Comment by Overtorment** [comment]
delivered in https://github.com/BlueWallet/BlueWallet/pull/2986
should be out in the next release
cc @limpbrains
