### ISSUE TITLE
Right-to-Left Writing in Menus

### ISSUE THREAD

**Issue by mcsaeid** [BlueWallet/BlueWallet#2755]
I am not sure if this is possible at the moment, but for languages that support RTL writing, such as Persian and Arabic, the page direction should be the opposite, where menu buttons and texts appear on the right side of the screen. Here are some examples:

![IMG_5148](https://user-images.githubusercontent.com/63400670/109978018-b08f5980-7d12-11eb-84fe-b449c5936025.jpg)

![IMG_5149](https://user-images.githubusercontent.com/63400670/109978027-b2591d00-7d12-11eb-82ff-f24ab4c736de.jpg)

![IMG_5150](https://user-images.githubusercontent.com/63400670/109978038-b4bb7700-7d12-11eb-91fa-f90cebe8d078.jpg)

**Comment by Overtorment** [comment]
@limpbrains @marcosrdz Rn gurus, what are your thoughts?

**Comment by mcsaeid** [comment]
Thanks, @marcosrdz. Will do.
