### ISSUE TITLE
Unable to connect to node's electrum server (Android, local/tor)

### ISSUE THREAD

**Issue by deepfingvalue** [BlueWallet/BlueWallet#2766]
Hi!

I recently set up two full nodes (Raspibolt and umbrel) with Electrum (electrs).
I was able to successfully connect to the Electrum server on iOS using a local address (e.g. umbrel.local:50001).

However, when trying to connect using Android I received an alert saying 'Can't connect to the provided Electrum server'
I receive this alert both for local addresses and onion addresses when using tor via Orbot. 

![image](https://user-images.githubusercontent.com/79589605/110260884-fef36100-7f7b-11eb-8a96-a9ea8331cdb0.png)

Any clue why this may be happening?

Running Android 11, Pixel 5. I've also tried this on other Android devices.. No luck :(

**Comment by Overtorment** [comment]
maybe name resolution doesnt work on android? try direct ip

**Comment by deepfingvalue** [comment]
good call. I tried direct ip for a local address and that worked.

Any clue how I might connect via tor? Will I have to wait for #2487 to merged?

**Comment by marcosrdz** [comment]
You can use Orbot on Android while that PR is being worked on

**Comment by deepfingvalue** [comment]
Sadly Orbot on Android doesn't seem to be working for me. At least on the Pixel phone. I can try the other Android phone later.

host: xxxx.onion
Tcp port: 50001

Orbot v. 16.4.0-rc-2a-tor-0.4.4.6
VPN mode is on for Blue Wallet.

Orbot/Tor seems to be working well with the Electrum app but I prefer the Blue Walllet UI so I was hoping I could get that working.

**Comment by Overtorment** [comment]
@deepfingvalue or you can take APK build from #2487 and use it.
its quite usable, but might be buggy.

**Comment by deepfingvalue** [comment]
Looks like the resource is not available

![image](https://user-images.githubusercontent.com/79589605/110662492-8ff05500-8193-11eb-8ad7-715bf0d4615e.png)

I tried with a Samsung phone and that worked. Odd....

Can you make the apk available again? I'd like to try with my pixel as that is my primary Android phone.

**Comment by Overtorment** [comment]
@deepfingvalue fresh TOR build is in https://github.com/BlueWallet/BlueWallet/pull/2295
so far no bugs spotted, but please give it a go and tell me if it works good for you as well. basically its ready for merge & release in next bluewallet's major release

**Comment by deepfingvalue** [comment]
Thanks! It works for the most part as far as being able to to connect, add wallets and see transactions.
I do notice a fair bit of client blocking/unresponsiveness when tor is on (at least on my pixel). When I try to navigate in and out of wallets or go to the settings manual some times I'm unable to do so. Restarting the app usually resolves the issue temporarily.

**Comment by satrinity402** [comment]
As of the current public build (v6.0.7), I am having this issue as well. Pixel 5 running CalyxOS Android 11.

**Comment by Overtorment** [comment]
further work on TOR is done in https://github.com/BlueWallet/BlueWallet/pull/2295
