### ISSUE TITLE
Can't restore various wallets

### ISSUE THREAD

**Issue by DoorOfSouls** [BlueWallet/BlueWallet#2789]
Hey team,

I have multiple mobile phones, running on the latest version of Blue wallet (ver 6.0.6 (build 1614602255) )

Whenever I create a new wallet, and restore them either on the same phone (after I deleted said wallet), or restore it on a different phone, manually (writing it down) or using the scan QR code, the app doesn't restore those wallets, as it gives me a generic "An error was encountered when attempting to import this wallet".

I tested to restore wallets while having an internet connection, and without a connection. Same error/issue.

All of the test mentioned above has been tried with new wallets, and with an old wallet that has a balance too (1,000 sats).

I've also test on a different version of Blue wallet (ver 3.0.3 (1610743490) ), where I tried using the seed words from the above tests, and created a new one on that version of Blue wallet, yet still facing the same issue of not being able to restore.

Another thing that I've tried is to restore on Electrum on my laptop, but when I wrote the last 12th words, the next button was greyed out. (Edit: In regards to Electrum, I checked the box in the options "BIP 39 seed" and it went through and restored wallets with the correct addresses. So it seems like the only issue here is Blue wallet not being able to restore for some reason.)

Edit: After trying to restore multiple times, it seems to work sometimes, but not always, and only in an online environment / when I'm connected to the internet. So this brings up a question: Does Blue Wallet not function, in terms of restoring a wallet, without an internet connection?

**Comment by Overtorment** [comment]
currently, internet connection is required yes.
thats because bw supports a lot of wallet standards/schemes. this is both a blessing and a curse.
when bw gets a backup from user it tries to unwrap all possible schemes/addresses and see if there are transactions there, and then bw imports only the scheme that has transactions.

we have a ticket somewhere to add an option to import a scheme user explicitly provided, but that's still in TODO

**Comment by DoorOfSouls** [comment]
> currently, internet connection is required yes.
> thats because bw supports a lot of wallet standards/schemes. this is both a blessing and a curse.
> when bw gets a backup from user it tries to unwrap all possible schemes/addresses and see if there are transactions there, and then bw imports only the scheme that has transactions.
> 
> we have a ticket somewhere to add an option to import a scheme user explicitly provided, but that's still in TODO

Ah, gotcha. Looking forward to the option when it gets implemented then =3
For my use case, a compromise was to use the Electrum app alongside BW to confirm I backed up my seed correctly.

**Comment by pointbiz** [comment]
Why does the restore work sometimes and not other times? A failed restore is a hard experience for the user.

**Comment by Overtorment** [comment]
Ill be working on better import process next

**Comment by limpbrains** [comment]
@DoorOfSouls BlueWallet now has new import workflow. It even can import some types of wallet completely offline. Have you tried it? If you have any problems, please report.
