### ISSUE TITLE
Incorrect amount for lntxbot transaction

### ISSUE THREAD

**Issue by moonshot75** [BlueWallet/BlueWallet#2795]
Lntxbot wallet in BW shows -763 213 for a 763 sats transaction.

![photo_2021-03-15_09-47-14](https://user-images.githubusercontent.com/66482965/111127284-ebe02280-8573-11eb-965c-0bd331e3a975.jpg)
![photo_2021-03-15_09-47-14 (2)](https://user-images.githubusercontent.com/66482965/111127301-f1d60380-8573-11eb-8532-c5a73eb8ff0f.jpg)

**Comment by Overtorment** [comment]
thats the number returned from lntxbot via API, I assume.
better take it to bot's owner.

**Comment by moonshot75** [comment]
sure, forwarded it.
