### ISSUE TITLE
Cannot withdraw from lightningspin.com

### ISSUE THREAD

**Issue by rene78** [BlueWallet/BlueWallet#2797]
According to an email from their support they have a lot of issues with users of _Blue Wallet_ and asked me to use _Wallet of Satoshi_ instead.

![Screenshot_2021-03-15-18-57-39-081_io bluewallet bluewallet](https://user-images.githubusercontent.com/36115705/111200631-42744d80-85c2-11eb-9b64-703fffe439a8.jpg)

**Comment by ncoelho** [comment]
You are sending 3000 sats but your wallet has 148 sats.

**Comment by rene78** [comment]
The thing is that I want to **receive** money from Lightningspin. Below is the whole "workflow", from request for withdrawal to error message.
![image](https://user-images.githubusercontent.com/36115705/111203434-4ce41680-85c5-11eb-9933-ce0e2c3c51e0.png)

**Comment by ncoelho** [comment]
Does seem like a bug. Does it work from outside the Lapp browser. The normal phone browser?

**Comment by rene78** [comment]
That's the next problem. I cannot sign in with Google from within the Lapp browser, thus cannot access my Lightningspin funds outside Blue Wallet.

**Comment by ncoelho** [comment]
What about if you tap "no thanks", it should take you to the normal flow.

**Comment by rene78** [comment]
When clicking on "no thanks" a Lightning payment request is generated (so far so good). But once I tap on the withdraw button the following error message is shown:
![processed](https://user-images.githubusercontent.com/36115705/111207269-b23a0680-85c9-11eb-84e2-d08c44360c5d.jpeg)
Some routing problem apparently?

**Comment by Overtorment** [comment]
>> To get the "Send Payment" user interface does not really make sense I suppose.

this looks like a UI bug on BW side

**Comment by rene78** [comment]
Tried it again 2 days ago. No error messages and after awhile the balance on their website showed 0. But I never received anything on my wallet. If those 3750 sats turn into 3750$ in 10 years I had my pizza moment here 😉.

**Comment by Overtorment** [comment]
@rene78 email them asking what ln invoice they paid (if any) and forward it to support bluewallet@bluewallet.io

ps. this lnurl withdrawal bug in lapp browser still needs to be adressed

**Comment by Yiidiir** [comment]
@rene78 this might be relevant for you https://github.com/BlueWallet/BlueWallet/issues/2740

**Comment by Overtorment** [comment]
is it still happening?

**Comment by rene78** [comment]
Hi @Overtorment, I have to admit that I didn't follow up on it anymore. I just accepted the loss 😉.
You can close the issue, if you want.
