### ISSUE TITLE
Unable to spend after the upgrade to 6.0.6

### ISSUE THREAD

**Issue by fdmello** [BlueWallet/BlueWallet#2798]
The wallet freezes when I go into my wallet and attempt to Send.  Nothing works.
I am able to Receive sats from the exchange.
I am using BlueWallet on an iPhone 7 Plus (software version 14.4)

The issue first appeared after the upgrade a few days ago.

**Comment by fdmello** [comment]
After the most recent upgrade to 6.0.7, the issue still persists.
I can receive sats to the wallet but cannot spend.

Is there another wallet compatible with BlueWallet that I can use to move my bitcoins to a hardware wallet?

**Comment by ncoelho** [comment]
Most wallets should be compatible with bluewallet. It would be nice to discover why only one report on this case. Any other clues you can give us?

**Comment by fdmello** [comment]
I tried the 24 word recovery phrase with Green Wallet but got an error.
I removed the bluewallet app on my iPhone, re-installed it and tried the 24 word recovery phrase and my funds showed up.  Since then I have moved funds to the bluewallet from an exchange without any problem.

I updated my iPhone to ver. 14.4.2 yesterday.  Now when I try to send sats from the bluewallet, it just hangs.

**Comment by fdmello** [comment]
No, I am not behind a VPN.  I do not have an Electrum server.

**Comment by ncoelho** [comment]
It won't work with green, green is a multisig wallet with one of the keys in their server.

**Comment by fdmello** [comment]
Can you name another wallet that uses a 24 word phrase?  Would the Bread wallet work.  I have not tried it yet.

**Comment by ncoelho** [comment]
Here's how to recover your wallet on electrum for desktop

https://bluewallet.io/docs/recover-wallet/

**Comment by fdmello** [comment]
thanks...I'll give it a go later today

**Comment by ncoelho** [comment]
Can you send us a video of what you see? Maybe that will give us some clues, please send to bluewallet@bluewallet.io to keep your privacy from the public chat.

**Comment by fdmello** [comment]
ok, will do.

**Comment by fdmello** [comment]
video sent.

**Comment by ncoelho** [comment]
ok, interesting. Can you go to settings > about > run self test. And see what it says please

**Comment by fdmello** [comment]
________________________________

**Comment by fdmello** [comment]
I also just stopped all apps running on my iphone (thinking there might be a conflict with an app on my phone) and started up bluewallet again.  Tried Send - same thing.  The bluewallet app just hangs.

Regards,
Fred
________________________________

**Comment by fdmello** [comment]
[Image.jpeg]
________________________________

**Comment by ncoelho** [comment]
can't see the image

**Comment by fdmello** [comment]
The result of the self-test was
OK
All internal tests have passed successfully.  The wallet works well.

which is all the more mind boggeling.
________________________________

**Comment by ncoelho** [comment]
if you only have this wallet. I would backup it up, delete the app and install again, to make sure all the data is deleted. Then import again and try to access the send screen again.

**Comment by Overtorment** [comment]
can you also pls replicate the freeze again, restart the app, and send your current public IP to the same email..?
you can see your public IP on website https://ifconfig.co
I will try to look it up on our crash-reporting service

**Comment by fdmello** [comment]
Good news.  I tried again this morning but after closing the app after seeing the spinning wheel for 15-20 seconds, I let it run this time and eventually managed to complete a send.
I don't know what the initial issue was but BlueWallet is working on my phone now.

Thanks for all your help.

Regards,
Fred HODL D'Mello
________________________________
