### ISSUE TITLE
Do a research

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#28]
Do a research on existing iOS (and Android if possible wallets). 
Points of interest:

* Batch send. Whether wallets have this feature, and if yes, how is it implemented UX wise? I assume, for every target address & amount there should be an option to scan it via QR.
* Multisig. I'm not aware how wallets usually implement multisig so it is user-friendly. I know only Electrum (desktop wallet)  supports multisig, but I never tried it.  Multisig is super important for security reasons, and doent necessary involves several people. It's usually one person but with several keys (od devices), which he uses to sign the send transaction. So security leaks on one devices doesnt compromise security. Multisig is a corner stone in wallet being made by CasaHODL, see Lopp talk from "Building on Bitcoin"

I feel those are most important features for next releases, and it would be nice to know how other mobile wallets handling it to adopt best practices. If they don't - well, bad for them.

**Comment by maxtannahill** [comment]
Copay has an excellent multisig workflow that’s very user friendly. Available on mobile desktop operating systems. No Segwit though.

**Comment by Overtorment** [comment]
Thank's @maxtannahill will look into Copay on iOS.
