### ISSUE TITLE
Invoice layout

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#287]
There's two buttons on the invoice layout.

There should be a main call to action. The share. 
The other option, which is also a button, but looks like a link is a secondary option.

Here's how it looks:
![img_0854](https://user-images.githubusercontent.com/1238429/52006506-8f713480-24cc-11e9-85f5-aa491ed4fcc4.PNG)

Here's how it should look:
[zpl.io/VKK3xAE](https://zpl.io/VKK3xAE)

**Comment by marcosrdz** [comment]
1b19ab5dc87419c31c9da10c623eecabb50530e1
