### ISSUE TITLE
Privacy: BW connects to public servers when user's Electrum server is unreachable

### ISSUE THREAD

**Issue by donnlee** [BlueWallet/BlueWallet#2871]
It seems that BW will try to connect to public servers when my personal Electrum server is not reachable.
This is undesirable because it leaks my BW data to servers that I do not control. Thus, I cannot trust that BW will use my Electrum server ONLY.

I can understand this is good UX because BW will always appear to "just work".
But, is there a way to force BW to fail if it cannot reach my own Electrum server?

**Comment by ncoelho** [comment]
Here's how it works.

1. Bluewallet does not connect to public electrum servers. Only Bluewallet servers.
2. It doesn't fallback to any server when the selected is not available.

**Comment by donnlee** [comment]
@ncoelho , thank you for the lightning fast reply.  That's better than picking any public electrum server, for sure. But is there a way to block Bluewallet servers too?
I want to "lock" BW to my own electrum server and fail (display an error) otherwise.
I'm looking for an iOS wallet that works with my Electrum (umbrel) server.

I don't mind working on a PR for this, however I haven't looked at the BW code yet.  Pointers to the code that connects to BW servers, and how to create a new Setting, is appreciated.

**Comment by donnlee** [comment]
![IMG_bluewallet_electrum](https://user-images.githubusercontent.com/1100053/112890245-7dc74f80-908b-11eb-9415-36f601ff3f62.jpg)
BW says "Connected" and I know for certain 10.0.0.1 is unreachable.

**Comment by ncoelho** [comment]
The status label is not really working that well. Restart the app to check.

But, bluewallet will not overwrite your settings, if it is defined for a server it won't try to connected to other. There is a lot of functionality that works offline as well.

**Comment by donnlee** [comment]
ah i see.  Ok, i guess i can test this by sending BTC from BW.  The transaction should fail when my electrum server is unreachable.  Thanks @ncoelho !
