### ISSUE TITLE
Can't Import Lightning Wallet

### ISSUE THREAD

**Issue by fxphysics** [BlueWallet/BlueWallet#2884]
Hi guys, I have myNode running on a Raspi4 with LND Hub ready to go. I already set up a funded lightning wallet in RTL with open channels and I wanted to import that same wallet (and its open channels) into my iOS BlueWallet app. If fails no matter what I try. Namely:

(a) scanning the **Node URI** that shows in the myNode LND Hub app,

(b) scanning a full length custom QR formatted as **lndhub://URI@http://192.168.1.26:3000** since this is apparently the recovery QR format for a brand new lightning wallet made directly in-app,

(c) scanning a shorter custom QR formatted as **lndhub://URI** as shown in the Bluewallet website tutorial on how to restore a lightning wallet, and

(d) pasting the **raw URI** in the import field without anything else.

Nothing works. Setting up a Lightning wallet on Bluewallet only seems to work fine when new. Just not imported.

What am doing wrong? Is it merely an import format issue or am I attempting to do something impossible? I found that thread https://github.com/BlueWallet/LndHub/issues/17 but I cannot find any resolution to my problem. Thanks a lot for your help.

PS: I am reposting this question from the Bluewallet Reddit group due to a non-responsive community. So my apologies in advance to the devs in case this is not best practice.

**Comment by Overtorment** [comment]
its a good place, thanks for the report.

can you try the following? go to http://lndhub-staging.herokuapp.com/ and scan its QR (basically, set it as a default lndhub).
its our staging lndhub. its basically pre-production, just running a bit fresher software.
then create ln account in bluewallet. back it up. delete, try importing again. is that working for you?
(your backup string should be something like `lndhub://xxx:yyy@http://lndhub-staging.herokuapp.com/`)

I was testing lndhub's backup-restore yesterday, and could only found this little bug: https://github.com/BlueWallet/BlueWallet/issues/2889
but everything worked in general.

**Comment by fxphysics** [comment]
Yes, this workaround does work. But it is not accomplishing what I am looking for.

First, I want my Lightning BW to remain connected to my own LND Hub through the local IP on myNode, not to `http://lndhub-staging.herokuapp.com/`. Second, my initial intention was to import into BW an **existing** lightning wallet (and its funded channels) that I already set up in RideTheLightning. I do not intend to create a new wallet from scratch in BW.

Once again, I am new to this and I do not know if what I am asking for is even possible. Thank you for your help.

**Comment by Overtorment** [comment]
i understand. that was to test if everything is well with your wallet in general.

so, to debug further. in your setup your phone always needs to be on the same local network as lndhub. to check this try opening lndhub web from your phone's browser. (you're using a local network IP `192.168.*.*`)

**Comment by fxphysics** [comment]
Yes, it works just fine. I can use the phone browser to access and login into myNode from the local network IP, then open the LND Hub service in that same browser.

**Comment by Overtorment** [comment]
try setting this lndhub url as a default lndhub in bluewallet, and then create a lightning wallet (don't worry, nothing happens here, only a record in database is added)

**Comment by fxphysics** [comment]
The URL shown in myNode for the LND Hub (192.168.x.x:3000) is how I tried to set everything up initially. As I said, I can create a new wallet but I still cannot import an existing one.

**Comment by Overtorment** [comment]
ok what you want to achieve is to create lndhub wallet, and then fix it so it has your LND's balance.
there is no easy way to do that.
what you can do is create lndhub wallet in bluewallet (while connected to your own custom lndhub), and then actually _fund_ it with your bitcoins. those bitcoins will land on your LND and you can move them back to whatever wallet, but this way lndhub will award you with balance that you can spend through underlying LND

**Comment by fxphysics** [comment]
Ok I just created a new (still unfunded) wallet in BlueWallet in addition to my funded RideTheLightning wallet. 

-  Both wallets in RTL and BW are pointing to the **same LND Hub** i.e. the same local IP/port.
-  The RTL wallet and the BW wallet have **different URIs**.
-  I will fund my BW wallet **on-chain**, NOT through lightning using an invoice.

I feel like I am missing something major as far as how lightning works. Is merely pointing these two wallets to the same LND Hub enough to share their channels with one another? If so, then what is the point of URIs?

**Comment by Overtorment** [comment]
you're probably missing that lndhub is just a tiny accounting wrapper around LND, and it is not related to RTL in any way.
