### ISSUE TITLE
Importing AEZEED wallet zpub for Watch-Only displaying 0 balance

### ISSUE THREAD

**Issue by krupawan5618** [BlueWallet/BlueWallet#2886]
Hi, 

I was wondering if anyone was able to import an AEZEED XPUB as a Watch Only wallet? I have an AEZEED wallet that imports successfully and displays the funds using the mnemonic phrase. After importing, I am able to Show Wallet XPUB and copy it. Because I would like to remove the private key to this wallet and convert it to Watch Only, I paste this XPUB into ‘Import Wallet’ field; however, the AEZEED Watch-Only wallet displays 0 funds.

**Comment by krupawan5618** [comment]
Email sent.

**Comment by Overtorment** [comment]
turns out, zpub produced by bluewallet was incorrect. fixed in https://github.com/BlueWallet/BlueWallet/pull/2896
