### ISSUE TITLE
iOS dark mode makes text illegible

### ISSUE THREAD

**Issue by cryptograffiti** [BlueWallet/BlueWallet#2888]
Hello,

When in dark mode, the text for sending a payment is very difficult to read.  

Possible to have the text lighter?

Thanks!

![IMAGE 2021-03-31 11:15:07](https://user-images.githubusercontent.com/47867295/113191400-59e24600-9212-11eb-843c-018afe8423d4.jpg)

**Comment by ncoelho** [comment]
This is lnurl-withdraw or pay?

**Comment by cryptograffiti** [comment]
Pay!
