### ISSUE TITLE
Initial LNDHUB backup screen doesnt include custom server

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#2889]
STR

1. open bw
2. scan qr code from https://lndhub-staging.herokuapp.com and set lndhub to custom server  (which is `https://lndhub-staging.herokuapp.com`)
3. create wallet -> lightning -> please backup screen

AR:
rendered QR code doesnt include custom server part `@https://lndhub-staging.herokuapp.com` while text representation does. but if you close this screen and go to wallet->details->export backup everything will be fine

ER: 
both qr and text should have custom server part

**Comment by demerzel3** [comment]
I think this is a duplicate of https://github.com/BlueWallet/BlueWallet/issues/3379

**Comment by Overtorment** [comment]
good catch. closed as duplicate
