### ISSUE TITLE
help 

### ISSUE THREAD

**Issue by leonardoprest** [BlueWallet/BlueWallet#291]
come faccio a configurare il nodo di lightning  network su bluewallet 
grazie

**Comment by ncoelho** [comment]
https://github.com/dangeross/guides/blob/master/raspibolt/raspibolt_6B_lndhub.md

https://bitcoinmirror.ghost.io/how-to-install-bitcoin-lightning-and-lndhub-on-your-own-vps/

https://medium.com/@jpthor/running-lndhub-on-mac-osx-5be6671b2e0c
