### ISSUE TITLE
Signing multisig transaction using QR codes on old hardware is broken

### ISSUE THREAD

**Issue by vbnmvhnhjk** [BlueWallet/BlueWallet#2920]
I have repurposed an old iPhone 5 as one device in a 2 of 3 multisig wallet, but I discovered that signing a transaction offline using QR codes using this device is near-impossible. The camera freezes and flashes, and eventually stops counting up during the QR code process. The only way I could make it work is to start the transaction using the iPhone. I have no idea if this is because the iPhone 5 just isn't a powerful enough device to make this work, or if it's a bug that can be fixed.

**Comment by Overtorment** [comment]
can you share a video? maybe privately to bluewallet@bluewallet.io

**Comment by vbnmvhnhjk** [comment]
OK well in making the video, both times it worked perfectly. The only reason I can think that it didn't work well the first time is that the number of QR code "cycles" was 116, so relatively high, and I think the old hardware couldn't for whatever reason cope with it. But this time I did attempt a transaction with 95 "cycles" and it still worked fine. Closing this as I think it's an edge case.

**Comment by Overtorment** [comment]
weird.
i personally tried ~117 frames in QR and it worked. not on old hardware
tho, iphone11
