### ISSUE TITLE
 200k sat bounty: offline mode with working import (private key, bip38, bip39 and passphrase) and choosing derivation path

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#2921]
With the introduction of an offline mode plus an electrum server error every time it needs to connect, there's a problem here where the error is annoying the offline mode users.

- We could have an "implicit" offline mode with the app (but the phone already provides this)
- The error message being somehow less intrusive 

Any ideas...

**Comment by Overtorment** [comment]
well, I was adding TOR in other branch, and noticed that connection alert is buggy and fixed it in TOR branch, as well as some other minor electrum issues. maybe I should port fix and release it independently.

basically, pressing Cancel should stop electrum from reconnecting completely for current session, but right now it tries again and again anyway

**Comment by bitcoinheiro** [comment]
Also for the "offline mode" would be good to activate the custom derivation path option - or at least enable to choose from the default paths provided by bluewallet when creating a new wallet. The "magical" discovery mode that requires online connection is a problem for offline users.

Related to this issue: https://github.com/BlueWallet/BlueWallet/issues/2240

**Comment by jpph** [comment]
willing to offer a 200k sat bug bounty on this one : offline mode with working import (private key, bip38, bip39 and passphrase)  and choosing derivation path. if an admin can modify the title

**Comment by limpbrains** [comment]
offline import of BIP39 + passphrase + custom derivation path will be released in next BW version.
You can watch it working here https://github.com/BlueWallet/BlueWallet/pull/3452#issuecomment-922987714

Do you really need private key and bip38 in offline mode? 
You can't sign a transaction in single wallet address in BW, as far as I remember.

**Comment by jpph** [comment]
Great news! Offline mode for private key and bip38 will be really useful for people needing to sweep securely paper wallet (paper wallet are still produced by ATMs). Maybe we can open a new feature request for that. I am ok to redeem bounty without pv key and bip38.

**Comment by limpbrains** [comment]
I created a discussion for that #3908. I think this issue can be closed. 
@jpph if you want to donate me these sats, please DM me at twitter, or telegram @limpbrains, thanks!

**Comment by jpph** [comment]
done :-) With great pleasure and thank you.
