### ISSUE TITLE
Interface with other Exchanges than HodlHodl

### ISSUE THREAD

**Issue by yoshimo** [BlueWallet/BlueWallet#2923]
Exchanges, both centralised and decentralised, offer api access to external applications.
Thelikes of Coinbase, Kraken,Binance, Huobi on the one side, bisq on the other.
It would be good if BW broadened its horizon and allow people to plug in their favourite exchange account 

- Create Buy and sell orders
- AutoBuy as Cost-Averaging at fixed intervals if there is enough balance
- Automatic withdrawal of funds once a certain balance threshold is reached and the fees and withdrawal costs don't eat too much %age
- import order history
- keep track of the profit/loss within BW, allowing the user to manually edit exchange rate for transactions that aren't on the book

**Comment by BeOleg** [comment]
We are from https://n.exchange and we are happy to collaborate on the above 👍

**Comment by Overtorment** [comment]
hodlhodl integration was removed.
other exchanges integrations are not planned.
