### ISSUE TITLE
Maximum Lightning Wallet Capacity

### ISSUE THREAD

**Issue by ViktorBohu** [BlueWallet/BlueWallet#2929]
Is there a maximum amount that can be (safely?) stored in a lightning wallet? A maximum amount that can per sent per transaction/invoice?

If so we maybe should add some kind of disclaimer like "don't store more cash that you're comfortable with carrying around in your physical wallet" or "Max 10M sats / invoice".

**Comment by Overtorment** [comment]
i dont think there asre limitations anywhere. lndhub rolls with wumbo channels for more than a year now

**Comment by ViktorBohu** [comment]
Did anyone try storing / sending / receiving 1 BTC at once with lndhub?

**Comment by Overtorment** [comment]
i did try 0.4 btc personally
