### ISSUE TITLE
Add more emphasis to custodial nature of LN wallets

### ISSUE THREAD

**Issue by Bosch-0** [BlueWallet/BlueWallet#2930]
Currently BlueWallet LN wallets are custodial by default when created. There is a subtle warning once the LN wallet is created (highlighted below) however this tradeoff should be explained PRIOR to wallet creation and with more emphasis on the trade offs. Maybe a popup could appear when you click 'create' on the Add Wallet page that briefly explains that these wallets are custodial. @GBKS. 

![Frame 29](https://user-images.githubusercontent.com/55287964/113957169-5291ec80-9851-11eb-9e95-d8a2255f799f.png)

**Comment by ncoelho** [comment]
Good enough for now. The current lightning implementation is in code freeze till the [new solution is released](https://github.com/BlueWallet/BlueWallet/pull/2615). Thanks!
