### ISSUE TITLE
ACINQ Strike design

### ISSUE THREAD

**Issue by marcosrdz** [BlueWallet/BlueWallet#294]
Please, create:
- Gradients
- Logo

For ACINQ Strike wallets. It'll help differentiate from normal Lightning.

**Comment by marcosrdz** [comment]
@ncoelho  say something I'm giving up on you

**Comment by ncoelho** [comment]
top: #1A63DF
bottom: #0A4873

<img width="394" alt="screenshot 2019-02-17 at 19 43 55" src="https://user-images.githubusercontent.com/1238429/52917486-73eb9380-32ec-11e9-8741-2c03162f39e3.png">
