### ISSUE TITLE
Show Xpub for wallets with electrum mnemonic

### ISSUE THREAD

**Issue by limpbrains** [BlueWallet/BlueWallet#2941]
work on in after #2899 is merged

**Comment by mcsaeid** [comment]
I have been wanting to point this out. I thought I would search first to see if it had been mentioned before.

![image](https://user-images.githubusercontent.com/63400670/115163470-8fb27600-a0be-11eb-9237-57015ca29bea.jpeg)

Is this it? I noticed Electrum-imported wallets lack XPUBs.

Great work, as always.
