### ISSUE TITLE
Impossible to scan QR invoice with a specific BTC amount

### ISSUE THREAD

**Issue by xAdamPos** [BlueWallet/BlueWallet#296]
I experience issues with scanning BTC invoices (all addresses - bc1/1/3) with a specific amount.

- when there is no amount in the invoice preset, it's alright and it fills the BTC address
- when there is any amount in the invoice, nothing happens and it comes back to send payment with all the fields empty (no error)
- only mainnet, LN invoices are OK

- issues on both iPhone 7 and iPhone XS

**Comment by Overtorment** [comment]
Acknowledged.

`bitcoin:bc1quhnve8q4tk3unhmjts7ymxv8cd6w9xv8wy29uv?message=trololo&amount=111` 
![image](https://user-images.githubusercontent.com/1913337/52239936-849d1200-28c7-11e9-93bb-a0c31fa64ddf.png)
is not scanned correctly

**Comment by Overtorment** [comment]
Thanks for the report! Will be fixed.

**Comment by Overtorment** [comment]
test vectors 

![image](https://user-images.githubusercontent.com/1913337/52539421-d0433600-2d75-11e9-8e01-3cc86a5833b2.png)


![image](https://user-images.githubusercontent.com/1913337/52539424-d507ea00-2d75-11e9-8c69-0136a346d2de.png)

![image](https://user-images.githubusercontent.com/1913337/52539429-de915200-2d75-11e9-9f5b-e9fa3631d854.png)
