### ISSUE TITLE
I can't download the bluewallet from GooglePlay

### ISSUE THREAD

**Issue by forest21000** [BlueWallet/BlueWallet#299]
Can you upload the bluewallet apk to the release.So that we can download directly from the release.Tks

**Comment by Overtorment** [comment]
@ncoelho sound like a job for you.
I think you can download APK from google play admin page, and push it to our website github.
I'd suggest intermediate popup before actual download, explaining that user should backup his keys before update (I still havent figured out googleplay updates, Im afraid that some BW version gona overwite previous installation's storage and user looses his keys). Also, I'd suggest maintain several APK versions, so for example user can download 3.7.0,  3.6.0, and 3.5.0, just for any case (if our latest release  instacrashes for example).

**Comment by matt-auckland** [comment]
I would suggest attaching the APKs to your Github releases

**Comment by forest21000** [comment]
@matt-auckland I do agree with you!That will be convinent to users!

**Comment by marcosrdz** [comment]
APK available on bluewallet.io
