### ISSUE TITLE
Received an invoice for 1.5 sats, paid it, 4 were paid, now wallet no longer works. Error message below.

### ISSUE THREAD

**Issue by johnr365** [BlueWallet/BlueWallet#2999]
As above:

Received an invoice for 1.5 sats, paid it, 4 sats were paid (no idea why) - now wallet no longer works.

Getting the error message:
```
Alert
API error: Payment failed. Does the receiver have enough inbound capacity? (Code 10)
```

Initially we thought the error was on the side of the person invoicing me. 

Then they opened another hosted LN wallet, and I got the same error when trying to pay that.

Then they tested invoicing between their 2 hosted wallets and it worked.

So seems its just my Blue wallet. Has adequate sats in there.

**Comment by Overtorment** [comment]
if you are trying to pay super small invoice (like 2 sat) - the issue might be that intermediate nodes take at least 1sat routing fee, so fees are comparable to the payment amount, and built-in sanity check kicks in like, this is a mistake, you're paying 200% fee!

**Comment by johnr365** [comment]
@Overtorment - Thanks for the reply.

Was able to send payment for 5 or less sats previously without issue?

**Comment by Overtorment** [comment]
payments might go different routes, with different fees (sometimes even no fees at all)

**Comment by johnr365** [comment]
@Overtorment - Thanks for explaining. 

Any chance you could send me an invoice for a satoshi amount you think should work? I'll try paying it and see.

Have around 990 sats in the wallet currently - so can't be more than that.

**Comment by Overtorment** [comment]
here https://tippin.me/@overtorment knock yourself out
pay as much as you want

**Comment by johnr365** [comment]
@Overtorment - Ah, that worked! Thanks

So it was as you said - it was going via a route with fees, and some sort of sanity check kicked in.

I guess the next problem is that the error message should match what's going on. 

If it had kicked up an error that said something to the effect of "Transaction automatically cancelled, the fees are >50% of the payment amount" - then I'd have at least understood what was going on.

Anyhow - again - much appreciated for your help.

**Comment by Overtorment** [comment]
10 more reports like this and I'll fix the error message 😆

**Comment by StopNato** [comment]
+
![Screenshot_20210622-021633](https://user-images.githubusercontent.com/26277164/122841957-0bba7b80-d305-11eb-85c9-a9809b2f7b34.jpg)
