### ISSUE TITLE
Arabic translation on transifex 

### ISSUE THREAD

**Issue by EZ0010** [BlueWallet/BlueWallet#3013]
Hi.
I'm not sure if this is the right place to say this but please mark the Arabic language translated strings on Transifex as reviewed or let me have a role as a reviewer to do it, I'm the only one contributing to the language, and it's been 2 months since the last pull request for the Arabic language there is no one reviewing it
I just completed translating 100% of the strings and fixed some old translations, so please consider adding them to the next release.

Thanks

**Comment by ncoelho** [comment]
Added you, let me know if you got it

**Comment by EZ0010** [comment]
Thanks. got it.
