### ISSUE TITLE
Multisig vault: "Error: Not Enough balance. Try sending smaller amount or decrease the fee."

### ISSUE THREAD

**Issue by blankscreengithub** [BlueWallet/BlueWallet#3015]
I am getting this error when creating any transaction from all of my multisig vaults, even if I am trying to send $5 at 14 sat/byte and there are plenty of funds in each vault. I even tried a different electrum server. This is using version 6.0.8. I have a different device with 6.0.7 and it created the transaction just fine.

Edit: this error even pops up if I use MAX full balance as the amount on all on-chain wallets, even on a paper wallet I imported.

**Comment by blankscreengithub** [comment]
Issue resolved itself? It works now, but when it wasn't working, the fee estimator was not giving me dollar amounts. Now the fee estimator is giving me dollar amounts and I can send transactions now.

**Comment by ncoelho** [comment]
There's couple of reasons for the fee estimator to not give estimations:
- Connection to the server is failing
- Not enough balance
- Dollars not defined

Maybe you were facing one of this issues?

**Comment by blankscreengithub** [comment]
It must have been "Connection to the server is failing" because it is happening right now for all my wallets except one where I received a transaction last night. There is enough balance if I have 800,000 sats and I am trying to send 50,000 sats with a 72 sat/byte fee. The currency setting has always been USD, but I get the same error no matter which currency I select. Why would the connection to the server fail for multiple wallets except one?

I notice the error happens when on the send screen, the fee shows up as 1 sat/byte instead of $xx.xx. Maybe I'll try the release candidate version.

This only happens on my main device that has version 6.0.8 on it. My other devices with version 6.0.7 work as expected. And I'm using multisig vaults on devices with both versions on it.

**Comment by Overtorment** [comment]
1 sat/byte is a sign that something is wrong with the connectivity (so it even could not fetch feerate and/or currency exchange rate)

**Comment by blankscreengithub** [comment]
Would connectivity be an issue with an individual wallet or the app? See screenshots of 2 different vaults within the same app (android version 6.0.8) Spending Vault shows the dollar amount of the fee and I can send from this wallet without any problems. Extra Vault shows 1 sat/byte and I get the "Not enough balance error". I switched wallets by using the "select wallet >" button at the bottom.

![Screenshot_BlueWallet](https://user-images.githubusercontent.com/66571264/116594036-675d1f80-a8e7-11eb-8eb5-3f715b298a1d.jpg)

![ScreenshotBlueWallet](https://user-images.githubusercontent.com/66571264/116594043-69bf7980-a8e7-11eb-8286-a7029761abde.jpg)

**Comment by blankscreengithub** [comment]
I replicated the issue and the reason the fee was only showing 1 sat/byte was because all of the coins were frozen under Coin Control. So I guess it's a feature, not a bug.
