### ISSUE TITLE
Android not redering QR code

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#302]
Some reports that android phones are not rendering/drawing the QR code

**Comment by massi93** [comment]
I also have noticed this issue on a couple of phones, but not on every android one, I can give you the exact models, if this can be useful.  Maybe is related to screen resolution?

**Comment by Overtorment** [comment]
Please do, cant reproduce it on Pixel on emulator

**Comment by massi93** [comment]
Huawei P8 Lite and Essential Phone not rendering. Works on OnePlus 6

**Comment by marcosrdz** [comment]
c615ebbc07d1c52fe5f0e2cdfcc14cb2da6096e8
