### ISSUE TITLE
lnd - create invoice - cant tap bottom half of button

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#303]
Defo on android, ios - not sure. Looks like some black RN magic. @marcosrdz u r the pro

![lnd - create invoice - cant tap bottom half of button - peek 2019-02-08 14-30](https://user-images.githubusercontent.com/1913337/52484425-32e9d580-2bae-11e9-9d76-3a9c0d6c6852.gif)

**Comment by marcosrdz** [comment]
395c0ce19398e615af325b0362246745150b46a4
