### ISSUE TITLE
Opennode integration

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#304]
Opennode integration placeholder task. To be planned

**Comment by marcosrdz** [comment]
@ncoelho UI God, work your magic.

**Comment by ncoelho** [comment]
top: #6A56F6
bottom: #4736C3

<img width="391" alt="screenshot 2019-02-17 at 19 38 48" src="https://user-images.githubusercontent.com/1238429/52917432-ba8cbe00-32eb-11e9-973c-7d87171d43b6.png">
