### ISSUE TITLE
Moscow time on watchOS

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#3040]
cc @seerowanyan

**Comment by marcosrdz** [comment]
More details?

**Comment by seerowanyan** [comment]
![image](https://user-images.githubusercontent.com/83396935/119215718-d6d1c380-bacf-11eb-8118-79803859166c.jpeg)

hi, it can happen that there is not enougth place if we have a 5digit btc/usd price. 

maybe would be possible to show sats/usd instead?

**Comment by marcosrdz** [comment]
Gotcha! Coincidentally I was working on implementing currency abbreviation just a few hours ago. In addition, the complication is also available for the large module on the center which gives more roof the price
