### ISSUE TITLE
Tippin.me integration

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#305]
Tippin.me integration placeholder task to be planned.

**Comment by marcosrdz** [comment]
@ncoelho UI God, work your magic.

**Comment by Overtorment** [comment]
I cant imagine how it should work.
@ncoelho has to invent it as a product

**Comment by marcosrdz** [comment]
The API will allow to create an invoice by indicating a username.

Example:

User goes into their LN wallet, press Create, they'll type @marcosrdz, and the API will return a payment request for that tippin handle. They'll share that invoice and monitor if it's paid for.

**Comment by ncoelho** [comment]
> The API will allow to create an invoice by indicating a username.
> 
> Example:
> 
> User goes into their LN wallet, press Create, they'll type @marcosrdz, and the API will return a payment request for that tippin handle. They'll share that invoice and monitor if it's paid for.

hummm. What about import, user inserts his handle or url and then user can use the wallet?

**Comment by ncoelho** [comment]
top: #FD7478
bottom: #E73B40

<img width="393" alt="screenshot 2019-02-17 at 19 42 32" src="https://user-images.githubusercontent.com/1238429/52917469-31c25200-32ec-11e9-8c65-42dc7e2350ac.png">
