### ISSUE TITLE
Upgrade deps in build.gradle & use static versions instead of + or enable dependency locking

### ISSUE THREAD

**Issue by emanuelb** [BlueWallet/BlueWallet#3050]
Below versions in `./android/build.gradle` file are old:
https://github.com/BlueWallet/BlueWallet/blob/1bdd37d0fb3d79880fefe5a624b6598572f5a1ca/android/build.gradle#L56
https://github.com/BlueWallet/BlueWallet/blob/1bdd37d0fb3d79880fefe5a624b6598572f5a1ca/android/build.gradle#L5-L12
https://github.com/BlueWallet/BlueWallet/blob/1bdd37d0fb3d79880fefe5a624b6598572f5a1ca/android/build.gradle#L18-L22
Also the + is used (for `kotlinVersion` and `googlePlayServicesVersion`) which make the build not reproducible unless gradle dependency locking is enabled, more info:
https://docs.gradle.org/current/userguide/dependency_locking.html

Versions used:

kotlin-gradle-plugin used: 1.3.1 | latest is: 1.4.32
buildToolsVersion used: 28.0.0 & 29.0.2 | latest is: 29.0.3
firebaseVersion used: 17.3.4 & firebaseMessagingVersion used: 20.2.1| latest: 21.1.0
https://firebase.google.com/support/release-notes/android

Android Gradle plugin used: 4.0.1| latest: 4.1.0
https://developer.android.com/studio/releases/gradle-plugin?hl=ru

google-services used: 4.3.3 | latest: 4.3.5
https://developers.google.com/android/guides/google-services-plugin
https://developers.google.com/android/guides/releases#january_28_2021

**Comment by Overtorment** [comment]
could you please help with locking those deps?
ill deal with git->HTTP and bash->sh

**Comment by emanuelb** [comment]
yes, I could after being able to compile the app which require at least issue #3059 fixed in master branch (then I will retry compiling the app from latest commit in master & open new issue if errors/issues exists).

also fixing #3075 would be helpful as well for the locking operation testing if `+` is used (it's small related subset of this issue regarding gradle upgrade) as the gradle 7.0 (currently used in this repo version: 6.3) has some improvements for the dependency locking mechanism:
https://docs.gradle.org/7.0/release-notes.html#dependency-locking-improvements

**Comment by emanuelb** [comment]
The `buildToolsVersion '28.0.0'` line in:
https://github.com/BlueWallet/BlueWallet/blob/1bdd37d0fb3d79880fefe5a624b6598572f5a1ca/android/build.gradle#L56
can be removed as it's ignored, from `./gradlew assembleRelease` output:

> WARNING: The specified Android SDK Build Tools version (28.0.0) is ignored, as it is below the minimum supported version (29.0.2) for Android Gradle Plugin 4.0.1.
Android SDK Build Tools 29.0.2 will be used.
To suppress this warning, remove "buildToolsVersion '28.0.0'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
