### ISSUE TITLE
Refill not working on Lightning (using own LNDHub)

### ISSUE THREAD

**Issue by maltokyo** [BlueWallet/BlueWallet#3051]
Have my own LNDHub, which connects well to LND, and Bluewallet is connected to it, all logs are clean, and connections ok.

What do I do wrong here, steps I took are:

1. Create lightning wallet with my own LNDHub server already pre-connected
2. Select "Manage Funds" then "refill" on the lightning wallet, and select my on-chain Bluewallet wallet with funds in it (this is all in Bluewallet)
3. Make the on-chain transaction and wait for 3 confirmations (docs say this should convert it into a lightning balance after 3 confirmations, is it supposed to open a channel all at at the same time?  That is what I expected..
4. Balance shows now at top of the yellow lightning wallet (looks good so far)
5. Try to spend some sats on lightning, and cannot spend anywhere.
6. Check RTL Server, and LND has only the on-chain funds, no lightning channels to be seen anywhere (already 10 confirmations by this time)

So, I dont get Bluewallet and LNDHub.  After I refill my Lightning wallet, nothing happens, it is just showing the on-chain balance of the LND Node behind it.

How do I now get a channel, and how do I finally get lightning funds available, I am lost - help! (Thanks!)

I can share LNDHub logs etc, if they contain no sensitive data(?)

**Comment by maltokyo** [comment]
This is what the wallet looks like now, as if these funds are available to spend on the Lightning Network (but they are not, they are still on-chain!):

![image](https://user-images.githubusercontent.com/1388507/116798709-bd51e300-aaf2-11eb-9979-5f5e75042f29.png)

**Comment by maltokyo** [comment]
@ncoelho @Overtorment would really appreciate your help if possible.  I cannot work it out, after spending far too many hours on it ;(

**Comment by Overtorment** [comment]
So, if you have your own LND you need to open and manage your own channels! Now that you funded lnd onchain, use any tool (like RTL or even lnd console) to open channels wherever you like. Have fun!

**Comment by maltokyo** [comment]
Ah! ok, this part is not clear anywhere (on LNDHub site), thanks @Overtorment 

So if user A sends 100,000 sats (refill, on-chain) and user B sends 200,000 sats (refill, on-chain), does it mean that I need to open a channel for 300,000 sats in total for them to use it?  Can it be one channel, or needs to be two, how does LND wallet keep track of who's sats are who's?

**Comment by Overtorment** [comment]
You as a node owner can create any combination of channels, it's up to you. Lndhub tracks balances so don't worry about it. 
That way you can onboard your friends and family to lightning while you do all the heavy lifting for them (opening and managing channels)

**Comment by maltokyo** [comment]
got it, thanks

**Comment by junderw** [comment]
@Overtorment maybe LNDHub could have an API that receives a satoshi amount and returns true or false as to whether the current channel balances can support activity of that size.

BW can then query before refilling the off-chain, and if false, show a warning asking them to inform the admin they need more capacity.

It would never trigger for official server since you have tons of capacity, but the main case we want to cover is someone that uses Umbrel and BlueWallet off the bat and has nothing in their LND. Bluewallet should warn them all payments will fail because they have no channels.

**Comment by Overtorment** [comment]
> @Overtorment maybe LNDHub could have an API that receives a satoshi amount and returns true or false as to whether the current channel balances can support activity of that size.
> 
> 
> 
> BW can then query before refilling the off-chain, and if false, show a warning asking them to inform the admin they need more capacity.
> 
> 
> 
> It would never trigger for official server since you have tons of capacity, but the main case we want to cover is someone that uses Umbrel and BlueWallet off the bat and has nothing in their LND. Bluewallet should warn them all payments will fail because they have no channels.

Great idea. Basically could be done with a small change in existing code - throw new error code on /sendpayment route that prints a message if send amount is greater than lnd's channelBalance

**Comment by maltokyo** [comment]
Exactly, and at least, mentioning this in the docs of LNDHub would be super helpful.  I had no idea!  And wasted so much time working out why it was not opening channels for me.  You could even combine/batch the on-chain refill transaction (when it is coming from a Bluewallet on-chain wallet at least) with the channel open transaction, so there is one single transaction doing both things at once (refill and channel opening).  The "default" should be to open a channel with the Bluewallet node (users would not have an issue with this, if it is well documented, and it would be awesome for your node, and be a routing source of sats for you!).
