### ISSUE TITLE
Build failure, Avoid SSH dependecy for npm install command, use HTTPS instead

### ISSUE THREAD

**Issue by emanuelb** [BlueWallet/BlueWallet#3059]
Running `npm ci install` or `npm install --production` in tag `v6.1.0` where `ssh` binary not exists (ssh not installed) return:

> npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/BlueWallet/react-native-widget-center.git
npm ERR! 
npm ERR! error: cannot run ssh: No such file or directory
npm ERR! fatal: unable to fork
npm ERR! 
npm ERR! exited with error code: 128

after installing packages `openssh-client` and trying again, errors:
> npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/BlueWallet/react-native-tooltip.git
npm ERR! 
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128

Running the command `/usr/bin/git ls-remote -h -t ssh://git@github.com/BlueWallet/react-native-tooltip.git` Result:

> /usr/bin/git ls-remote -h -t ssh://git@github.com/BlueWallet/react-native-tooltip.git
The authenticity of host 'github.com (140.82.121.4)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,140.82.121.4' (RSA) to the list of known hosts.
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights

It's better to avoid the `ssh` binary dependency completely, and clone repos over `https://` which not require it & authentication.

To reproduce, I used the below Containerfile and run above commands in the generated container:

```dockerfile
FROM frolvlad/alpine-glibc

RUN set -ex; \
    apk update; \
    apk add --no-cache \
        openjdk8 \
        git \
        npm; \
    adduser -D appuser;

USER appuser

ENV ANDROID_SDK_ROOT="/home/appuser/app/sdk" \
    ANDROID_HOME="/home/appuser/app/sdk" \
    NODE_ENV="production"

RUN set -ex; \
    mkdir -p "/home/appuser/app/sdk/licenses" "/home/appuser/app/bluewallet/"; \
    printf "\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > "/home/appuser/app/sdk/licenses/android-sdk-license"; \
    cd /home/appuser/app/bluewallet/; \
    git clone https://github.com/BlueWallet/BlueWallet; \
    cd BlueWallet; \
    git checkout v6.1.0;
```

**Comment by emanuelb** [comment]
it's partial fix, as `npm ci install` still fail cause the `package-lock.json` still contain `git+https` & `git+ssh` entries, the package-lock.json should be regenerated (better with upgrading packages in the process)

**Comment by Overtorment** [comment]
hmm, when I delete lock file and do `npm i` I still get `git+https` for my deps.

```
"react-native-document-picker": "https://github.com/BlueWallet/react-native-document-picker#3684d4fcc2bc0b47c32be39024e4796004c3e428",
```

-->


```
    "react-native-document-picker": {
      "version": "git+https://github.com/BlueWallet/react-native-document-picker.git#3684d4fcc2bc0b47c32be39024e4796004c3e428",
      "from": "git+https://github.com/BlueWallet/react-native-document-picker.git#3684d4fcc2bc0b47c32be39024e4796004c3e428"
    },
```


how do I solve this? npm ver `6.14.11`

**Comment by emanuelb** [comment]
change the line in `url` in package.json for the related package, for above `react-native-document-picker` it's in:
https://github.com/BlueWallet/react-native-document-picker/blob/30c9ebbf6ead227d69549aee87dd15956a0ce28b/package.json#L12
same need to be done for other deps.

**Comment by Overtorment** [comment]
> change the line in `url` in package.json for the related package, for above `react-native-document-picker` it's in:
> https://github.com/BlueWallet/react-native-document-picker/blob/30c9ebbf6ead227d69549aee87dd15956a0ce28b/package.json#L12
> same need to be done for other deps.

and that will change how the package is referenced in bw's lock file..?

**Comment by emanuelb** [comment]
> and that will change how the package is referenced in bw's lock file..?

maybe, didn't test it myself, but it might be not necessary as the problem on your end might be elsewhere...  
searching this org for `ssh` & `git+ssh` will help to catch such instances that require fixing.
I removed `package-lock.json` and run `npm install` then in `package-lock.json` file, there are "git+https" instances which are ok.
Then removing `./node_modules/` and running `npm ci install` works, as there no `git+ssh` entries in `package-lock.json`file
looks like when you did the same process on your end it's adding the `git+ssh` entries, not sure how to avoid this (except running it in clean environment like I did) but there probably a way... searching the net I cam across this issue+comment which may be related: https://github.com/npm/cli/issues/2610#issuecomment-780761122

The problem is in the `package-lock.json` currently located in the repo which contain `git+ssh` entries (so running `npm ci install` after cloning the repo will fail and require not needed ssh dependency), for example:
https://github.com/BlueWallet/BlueWallet/blob/59b2fa5a50c58b9569bacc1d94d62c4fc70c82b8/package-lock.json#L5918

```json
      "version": "git+ssh://git@github.com/BlueWallet/react-native-qrcode-local-image.git#b8baa79ba3b3859c9353c9dee7f01392b989a530",
      "version": "git+ssh://git@github.com/BlueWallet/react-native-document-picker.git#3684d4fcc2bc0b47c32be39024e4796004c3e428",
      "version": "git+ssh://git@github.com/BlueWallet/react-native-fingerprint-scanner.git#ce644673681716335d786727bab998f7e632ab5e",
      "version": "git+ssh://git@github.com/marcosrdz/react-native-handoff.git#f5becc63f3e36bf2da1ed1fc60fc690323e73602",
      "version": "git+ssh://git@github.com/BlueWallet/react-native-idle-timer.git#8587876d68ab5920e79619726aeca9e672beaf2b",
      "version": "git+ssh://git@github.com/BlueWallet/react-native-inappbrowser.git#fa2d8e1763e46dd12a7e53081e97a0f908049103",
      "version": "git+ssh://git@github.com/BlueWallet/react-native-is-catalyst.git#a665155424ae5b865971f71ba2625b2c53983364",
      "version": "git+ssh://git@github.com/BlueWallet/react-native-navigation-bar-color.git#34e44b8f44e442133de9d35c35f2679d40982804",
      "version": "git+ssh://git@github.com/BlueWallet/react-native-passcode-auth.git#a2ff977ba92b36f8d0a5567f59c05cc608e8bd12",
      "version": "git+ssh://git@github.com/BlueWallet/react-native-privacy-snapshot.git#529e4627d93f67752a27e82a040ff7b64dca0783",
      "version": "git+ssh://git@github.com/BlueWallet/react-native-prompt-android.git#2073b07f64bf5dc95807f64d79f37bdb111e6951",
      "version": "git+ssh://git@github.com/BlueWallet/react-native-secure-key-store.git#4828fd1a67d12e4c0e21eee0bee673fde75e6f9a",
      "version": "git+ssh://git@github.com/BlueWallet/react-native-tooltip.git#d369e7ece09e4dec73873f1cfeac83e9d35294a6",
      "version": "git+ssh://git@github.com/BlueWallet/react-native-widget-center.git#e2e9a9038b76d096bf929a87105a97a0a7095001",
```

**Comment by limpbrains** [comment]
Fixed in #3110

**Comment by Giszmo** [comment]
This issue appears to have come back.

```
$ git checkout v6.3.2 
HEAD is now at 81ed68b55 Merge pull request #5182 from BlueWallet/renovate/react-navigation-monorepo
$ podman run -it --rm -v$PWD:/mnt --workdir=/mnt walletscrutiny/android
# mkdir -p ~/.ssh
# ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
# apt update -y
# apt install npm -y
# npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!
npm WARN tar ENOENT: no such file or directory, open '/mnt/node_modules/.staging/crypto-js-0bc3b6fd/LICENSE'
npm WARN tar ENOENT: no such file or directory, open '/mnt/node_modules/.staging/crypto-js-0bc3b6fd/aes.js'
npm WARN tar ENOENT: no such file or directory, open '/mnt/node_modules/.staging/crypto-js-0bc3b6fd/cipher-core.js'
...
npm WARN tar ENOENT: no such file or directory, lstat '/mnt/node_modules/.staging/react-native-99ce84bc/ReactCommon/react/renderer/components'
npm WARN tar ENOENT: no such file or directory, lstat '/mnt/node_modules/.staging/react-native-99ce84bc/ReactCommon/react/renderer/components'
npm WARN tar ENOENT: no such file or directory, open '/mnt/node_modules/.staging/react-native-99ce84bc/ReactCommon/hermes/inspector/Inspector.cpp'
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/BlueWallet/react-native-secure-key-store.git
npm ERR! 
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128
```

**Comment by emanuelb** [comment]
Opened issue with suggestion to use lint tool in CI to detect some unwanted changes to package-lock.json file (such as having non https protocol or domains not in allowed list) in: #5329

meanwhile a workaround is to run sed command before any npm commands to replace git+ssh with https in `package-lock.json`:
```shell
sed -i 's/git+ssh/https/g' /home/appuser/BlueWallet/package-lock.json
```

such as in Containerfile:

```dockerfile
FROM frolvlad/alpine-glibc

RUN set -ex; \
    apk update; \
    apk add --no-cache \
        openjdk11 \
        git \
        npm; \
    adduser -D appuser;

USER appuser

ENV ANDROID_SDK_ROOT="/home/appuser/sdk" \
    ANDROID_HOME="/home/appuser/sdk" \
    NODE_ENV="production"

RUN set -ex; \
    mkdir -p "/home/appuser/sdk/licenses"; \
    printf "\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > "/home/appuser/sdk/licenses/android-sdk-license"; \
    cd /home/appuser/; \
    git clone https://github.com/BlueWallet/BlueWallet; \
    cd BlueWallet; \
    git checkout v6.3.2; \
    sed -i 's/git+ssh/https/g' /home/appuser/BlueWallet/package-lock.json; \
    npm install;
```

**Comment by emanuelb** [comment]
Found a global workaround that don't require running sed and edit files in repo, it worked in another repo where `sed` on package-lock.json and package.json didn't work (npm install still failed with error, probably due to problem from deps files)

Running commands such as: 

```shell
git config --global --add url.https://github.com/.insteadOf git://github.com/
git config --global --add url.https://github.com/.insteadOf git+ssh://git@github.com/
git config --global --add url.https://github.com/.insteadOf git+https://git@github.com/
git config --global --add url.https://github.com/.insteadOf git://git@github.com/
```

Should fix the issue and allow to compile any version of bluewallet that suffer from this issue (latest 6.3.2, and 6.1.0 the one this issue was opened about)

**Comment by amovfx** [comment]
I think the above should be added to the readme.
