### ISSUE TITLE
Link to own node confirmation's feedback

### ISSUE THREAD

**Issue by iamjackharper** [BlueWallet/BlueWallet#306]
Just a UI/UX improvement proposal: when a user adds his own node's URL under "Lighting Settings" and touches "Save" there isn't any kind of check or confirm feedback. I can write every kind of text there and it gives the feeling it isn't even saving it or trying to connect. A fast solution could be to just check if it's a valid URL, a more complex one for the future is to set up a new call to the provided URL that asks if LndHub is running there.

**Comment by ncoelho** [comment]
Done
