### ISSUE TITLE
Add language: Chinese, can't find it in app

### ISSUE THREAD

**Issue by Valuebai** [BlueWallet/BlueWallet#307]
I strongly advise u to add chinese version, and it'll attract more chinese users to use Bitcoin & Lightning

**Comment by ncoelho** [comment]
Can you help with the translation?

**Comment by Valuebai** [comment]
> Can you help with the translation?

i can try, you can send to my email: luhuibo306@foxmail.com

**Comment by uiharu-s** [comment]
may I contribute on the traditional chinese translation?

**Comment by oday0311** [comment]
https://github.com/BlueWallet/BlueWallet/pull/322

**Comment by oday0311** [comment]
add a chinese language support https://github.com/BlueWallet/BlueWallet/pull/322

**Comment by Overtorment** [comment]
closing in favor of https://github.com/BlueWallet/BlueWallet/pull/322
