### ISSUE TITLE
minimum android version alteration

### ISSUE THREAD

**Issue by FerMG** [BlueWallet/BlueWallet#3072]
hello, today I noticed I'm not able to enter in my wallet anymore because the app was updated and stopped being compatible with my device I suppose it was a change in the min supported version

I just wanted to know if this will be temporary or permanent, I had some funds in the wallet and was enjoying the app

**Comment by ncoelho** [comment]
Last version brings Tor, which is not compatible with older versions. To install an older version you can find them here:
https://github.com/BlueWallet/BlueWallet/releases/tag/v6.0.8

**Comment by FerMG** [comment]
thank you for the link, but the only way to install it was uninstalling the app installed previously through play store, and as result I lost the wallet I had funds on. but that's ok, it was a very low amount
sad I won't be able to use this app anymore, but thx anyway :)
