### ISSUE TITLE
Use newer lockfileVersion > 1 (newer Lockfile format for package-lock.json)

### ISSUE THREAD

**Issue by emanuelb** [BlueWallet/BlueWallet#3080]
https://github.com/BlueWallet/BlueWallet/blob/59b2fa5a50c58b9569bacc1d94d62c4fc70c82b8/package-lock.json#L4
old format of package-lock.json is used (`"lockfileVersion": 1`), npm 7 released with newer lockfile format, more details in links:
https://github.blog/2021-02-02-npm-7-is-now-generally-available/#changes-to-the-lockfile
> The lockfile v2 unlocks the ability to do deterministic and reproducible builds to produce a package tree.

https://nitayneeman.com/posts/catching-up-with-package-lockfile-changes-in-npm-v7/

**Comment by Overtorment** [comment]
last time i tried npm7 we had an issue with one of the deps, and the consensus among general RN developers was to stick to npm6 for a while.
ill test again if it was fixed

**Comment by Overtorment** [comment]
yep, with npm@7 I get 

```
overtorment@laptop3 ~/Documents/BlueWallet (master) $ npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: bluewallet@6.1.2
npm ERR! Found: react-native@0.63.4
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.63.4" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native@"^0.59.5" from react-native-fs@2.17.0
npm ERR! node_modules/react-native-fs
npm ERR!   react-native-fs@"2.17.0" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
```

it does work with ` --legacy-peer-deps` tho.

here's a ticket https://github.com/itinance/react-native-fs/issues/997
