### ISSUE TITLE
Weird coin selection algo, use 20 UTXO when it could have used 1 or 2.

### ISSUE THREAD

**Issue by Transisto** [BlueWallet/BlueWallet#3085]
example numbers

list of UTXO

0.0001000
0.0001000
0.0001000
0.0001000
0.0001000
0.0002000
0.0002000
(...)
0.1
0.2
0.3
0.4

When trying to send 0.35 the wallet selected **everything** but the 0.4

It selected about 25 UTXO while only 1 or 2 could have been used.

Is the wallet trying to make the change as close to the amount sent as possible?

It's super obvious anyway which part is the change, with different address type and a 0000 rounded amount.

**Comment by Overtorment** [comment]
ill try to reproduce it

**Comment by Transisto** [comment]
Looks like that one too https://github.com/breadwallet/breadwallet-ios/issues/188

**Comment by Transisto** [comment]
Been doing many tests, I don't think it's possible not to reproduce it.

At no point does the wallet ever use the minimal amount of UTXO to save on fees.

![image](https://user-images.githubusercontent.com/388716/117182559-7e4ab880-ada4-11eb-8047-566d8862d452.png)
Simulating sending 0.6 Wallet doesn't mind it's business and is merging a bunch irrelevant dust.

![image](https://user-images.githubusercontent.com/388716/117182668-a63a1c00-ada4-11eb-8bf8-748dc6aa7ef4.png)

**Comment by Overtorment** [comment]
ok, so a very basic test case would be:

send 0.6

provide inputs

0.00001
0.00001
0.69

inputs used:

0.00001
0.00001
0.69

inputs that should have been used:
0.69



is that correct?

**Comment by ncoelho** [comment]
PSA: This is a custom path m/0 from bread wallet, probably with coins on different paths

**Comment by Transisto** [comment]
> PSA: This is a custom path m/0 from bread wallet, probably with coins on different paths

This has nothing to do with bread wallet beside possibly using the same bitcoin library.

The wallet was generated on electrum native segwit and imported as IIRC an xpriv.

Yes from the example above there was no need to add the two 0.00001000 to send 0.6 while 0.69 would have been enough.

In the original issue, the wallet needlessly spent about 20 test UTXO of about the same near dust sizes.

**Comment by Transisto** [comment]
https://github.com/BlueWallet/BlueWallet/issues/3113
Somewhat similar but used unconfirmed change when it didn't had to.
