### ISSUE TITLE
lnurl-withdraw over Tor hangs

### ISSUE THREAD

**Issue by klnit** [BlueWallet/BlueWallet#3086]
first of all, using my wallet over a Tor address is super cool!

My problem seems similar to  #2213
Pasting or scanning QR with lnurl-withdraw, generated from an .onion address (in this case from LNBits) shows a spinner indefinitely and no error message. This is from a wallet send button.
When I use the scan button on wallet main page I get "Network request failed"
It is the same on Android and iOS

**Comment by Overtorment** [comment]
ok, this was overlooked. our lnurl integration is not even trying to switch to tor with dotonion links.
can you share a withdrawal onion link to test against?
ill be working on this

**Comment by klnit** [comment]
yes, can I dm you? (to not having it public ;-))

**Comment by Overtorment** [comment]
can you pls send it to i@bluewallet.io? thanks!

**Comment by 3ooabkhxtn** [comment]
Any progress on this? Need ln-url payments over tor for a little project

Would add a little 50 $ Bounty on this, of course as a ln-url withdraw link over tor ;-)

**Comment by 3ooabkhxtn** [comment]
Thanks for solving this! Send bounty to i@bluewallet.io, please let me know if it is not working, have still development going on on my side of the node.
