### ISSUE TITLE
App compilation fails in node production mode

### ISSUE THREAD

**Issue by emanuelb** [BlueWallet/BlueWallet#3087]
Ensure compiling both android & ios apps works when enviroment variable `NODE_ENV` is set to `production` instead of development, which is equal to running `npm install --production`, also ensure app compilation works when `npm ci install` is used instead.
compiling android app via `./gradlew assembleRelease` throw warnnings & fails with error when production mode is used.
fixing it will require moving needed deps for compilation from `devDependencies` to `dependencies`, also related issue to deps used in compilation which needs fixing is #3078 (same apply for when yarn is used instead of npm, with or without `--frozen-lockfile` parameter)

**Comment by Overtorment** [comment]
whats the error? we have env `NODE_ENV=production` on our CI for both ios and android (appcenter.ms)

**Comment by emanuelb** [comment]
yesterday it's failed with different errors, such as `error Unable to resolve module ./ReactNativeSVG from node_modules/react-native-svg/src/index.ts` and others, probably was when trying to rebuild the v6.1.0 version, today testing latest commit "99cdd1b2e22174589f86838ade6eacf43222c620" on master it's working (no errors, but lots of warning) with npm when running:

```shell
npm install --production=true --no-optional --ignore-scripts --no-audit
npm run postinstall
cd android; ./gradlew assembleRelease
```

But fails with error when yarn is used:

```shell
yarn add npx
yarn postinstall
cd android; ./gradlew assembleRelease
```

>error SyntaxError: /home/appuser/app/bluewallet/BlueWallet/node_modules/bip39/node_modules/pbkdf2/lib/default-encoding.js: Unexpected token (5:36)
  3 | if (global.process && global.process.browser) {
SyntaxError: /home/appuser/app/bluewallet/BlueWallet/node_modules/bip39/node_modules/pbkdf2/lib/default-encoding.js: Unexpected token (5:36)
  4 |   defaultEncoding = 'utf-8'
> 5 | } else if (global.process && global."v14.16.1") {
  3 | if (global.process && global.process.browser) {
    |                                     ^
  4 |   defaultEncoding = 'utf-8'
  6 |   var pVersionMajor = parseInt(process.version.split('.')[0].slice(1), 10)
> 5 | } else if (global.process && global."v14.16.1") {
  7 |
    |                                     ^
  8 |   defaultEncoding = pVersionMajor >= 6 ? 'utf-8' : 'binary'. Run CLI with --verbose flag for more details.
  6 |   var pVersionMajor = parseInt(process.version.split('.')[0].slice(1), 10)
  7 |
  8 |   defaultEncoding = pVersionMajor >= 6 ? 'utf-8' : 'binary'
    at Object._raise (/home/appuser/app/bluewallet/BlueWallet/node_modules/@babel/parser/lib/index.js:807:17)
    at Object.raiseWithData (/home/appuser/app/bluewallet/BlueWallet/node_modules/@babel/parser/lib/index.js:800:17)
    at Object.raise (/home/appuser/app/bluewallet/BlueWallet/node_modules/@babel/parser/lib/index.js:761:17)
    at Object.unexpected (/home/appuser/app/bluewallet/BlueWallet/node_modules/@babel/parser/lib/index.js:9931:16)
    at Object.parseIdentifierName (/home/appuser/app/bluewallet/BlueWallet/node_modules/@babel/parser/lib/index.js:12105:18)
    at Object.parseIdentifier (/home/appuser/app/bluewallet/BlueWallet/node_modules/@babel/parser/lib/index.js:12078:23)
    at Object.parseMaybePrivateName (/home/appuser/app/bluewallet/BlueWallet/node_modules/@babel/parser/lib/index.js:11415:19)
    at Object.parseMember (/home/appuser/app/bluewallet/BlueWallet/node_modules/@babel/parser/lib/index.js:10962:63)
    at Object.parseSubscript (/home/appuser/app/bluewallet/BlueWallet/node_modules/@babel/parser/lib/index.js:10950:19)
    at Object.parseSubscript (/home/appuser/app/bluewallet/BlueWallet/node_modules/@babel/parser/lib/index.js:3933:18)

That happened cause old version 3.0.8 of pbkdf2 exists in deps resolution, related upstream issue: https://github.com/crypto-browserify/pbkdf2/issues/96
was able to "fix" it by workaround in latest comment of above issue (adding `resolutions` to `package.json`)

for running `npm ci install` and yarn with `--frozen-lockfile` require first fixing: https://github.com/BlueWallet/BlueWallet/issues/3059#issuecomment-832689593

Also there is many warnings, which to know if it's ok to ignore then (they not affect the output) I need a apk to compare against, so will retest again when next version is released with apk in github releases.

**Comment by Overtorment** [comment]
i have just done
`NODE_ENV=production  npm ci install`
and then 
`cd android; ./gradlew assembleRelease`
worked with no issues

**Comment by emanuelb** [comment]
it doesn't work currently which is exactly what explained in #3059, here how to reproduce it again in linux container:

build with: `podman build --pull --rm -t bluewallet_master_npm_build_apk -f ContainerFileMasterNPM`
run with: `podman run --rm --name bluewallet_master_npm_build_apk -ti bluewallet_master_npm_build_apk`
then inside container run `npm ci install` (the `NODE_ENV=production` already declared in ContainerFileMasterNPM)

Result:
```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/BlueWallet/react-native-widget-center.git
npm ERR! 
npm ERR! error: cannot run ssh: No such file or directory
npm ERR! fatal: unable to fork
npm ERR! 
npm ERR! exited with error code: 128
```

installing `openssh-client` then retry `npm ci install`

result:
```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/BlueWallet/react-native-tooltip.git
npm ERR! 
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128
```
ContainerFileMasterNPM content:

```dockerfile
FROM frolvlad/alpine-glibc

RUN set -ex; \
    apk update; \
    apk add --no-cache \
        openjdk8 \
        git \
        npm; \
    adduser -D appuser;

USER appuser

ENV ANDROID_SDK_ROOT="/home/appuser/app/sdk" \
    ANDROID_HOME="/home/appuser/app/sdk" \
    NODE_ENV="production"

RUN set -ex; \
    mkdir -p "/home/appuser/app/sdk/licenses" "/home/appuser/app/bluewallet/"; \
    printf "\n24333f8a63b6825ea9c5514f83c2829b004d1fee" > "/home/appuser/app/sdk/licenses/android-sdk-license"; \
    cd /home/appuser/app/bluewallet/; \
    git clone --depth 1 https://github.com/BlueWallet/BlueWallet; \
    cd BlueWallet;
    
WORKDIR /home/appuser/app/bluewallet/BlueWallet/
```

when above ssh issue will be fixed I will test it again inside the linux container, to see if android app compilation works ` cd android; ./gradlew assembleRelease` after the `npm ci install` will work...

**Comment by Overtorment** [comment]
feels like `NODE_ENV=production` is not an issue, only that `ssh` biz is, so its safe to close this ticket

**Comment by emanuelb** [comment]
this issue is about the possible variations with npm+yarn in production mode, using yarn currently fail (probably cause old ver for rn-nodeify or pbkdf2) details in comment: https://github.com/BlueWallet/BlueWallet/issues/3087#issuecomment-832771157
and using `ci` operations fail cause the `ssh` stuff (but there might be more issues, which I will be able to test once the `ssh` stuff is fixed, and new release with downloadable apk is available)
Anyway it's fine to close this issue, and I will open new one later if needed after testing when the related issues (ssh, npx) are fixed...
