### ISSUE TITLE
Sign git tags on new releases

### ISSUE THREAD

**Issue by emanuelb** [BlueWallet/BlueWallet#3088]
Currently tags in repo are not signed:
https://github.com/BlueWallet/BlueWallet/tags

see for more info on how to sign:
https://help.github.com/en/github/authenticating-to-github/signing-tags

also upload related public key to github (so it will be shown as verified instead of unverified in github UI)
https://help.github.com/en/github/authenticating-to-github/adding-a-new-gpg-key-to-your-github-account

why it's important:
https://www.qubes-os.org/security/verifying-signatures/#how-to-verify-qubes-repos

also update the guide in: (to include `-s` for `git tag` commands)
https://github.com/BlueWallet/BlueWallet/blob/560fb8127e998b498201bd12afcded14f676b666/CONTRIBUTING.md#L6-L10

**Comment by Overtorment** [comment]
we stated signing tags
