### ISSUE TITLE
Releases links to stores are incorrect and points to direct downloads instead

### ISSUE THREAD

**Issue by emanuelb** [BlueWallet/BlueWallet#3094]
Visiting github release such as:
https://github.com/BlueWallet/BlueWallet/releases/tag/v6.1.0

Clicking on "Download on the AppStore" icon, the link is:
https://github.com/BlueWallet/BlueWallet/releases/download/v6.1.0/BlueWallet.6.1.1.dmg

And when clicking on "GET IT ON Google Play" icon, the links is:
https://github.com/BlueWallet/BlueWallet/releases/download/v6.1.0/BlueWallet-6.1.1.apk

while the versions is matched in the link to github release version, the intent is probably to point to appstores links for latest version instead such as: (so it will be downloaded from stores instead of direct download)
https://play.google.com/store/apps/details?id=io.bluewallet.bluewallet
https://apps.apple.com/us/app/bluewallet-bitcoin-wallet/id1376878040

**Comment by Overtorment** [comment]
@ncoelho

**Comment by ncoelho** [comment]
links are correct, image text may not be the best.

**Comment by emanuelb** [comment]
The same images are used in project README.md at:
https://github.com/BlueWallet/BlueWallet#bluewallet---a-bitcoin--lightning-wallet
and point to links in stores, so probably changing the images text in github releases is better (as the files downloaded are from github, and not related to "google-play" or "appstore" but to the underlying os Android and MACOSX)
