### ISSUE TITLE
Add .ipa file to github releases

### ISSUE THREAD

**Issue by emanuelb** [BlueWallet/BlueWallet#3095]
Add .ipa file (ios app) to the github releases as asset, which currently have only apk (android app) and .dmg (macosx) files:
https://github.com/BlueWallet/BlueWallet/releases

**Comment by Overtorment** [comment]
how useful is that? i dont think such ipa files are installable?

**Comment by emanuelb** [comment]
very useful, regarding installation on apple device and side-loading I don't know and don't have apple hardware (running MACOSX on vm on linux), it's still useful for other purposes, such as:
- test for reproducible-builds, see this comment for more details to understand why publishing the .ipa is needed: https://gitlab.com/walletscrutiny/walletScrutinyCom/-/issues/149#note_537109159
- compare them between versions (such as with `diffoscope`)
- look at the .ipa content as well and report issues if found in this repo...

**Comment by Overtorment** [comment]
if you can get the ipa file from jailbroken ios device, why not just compare it to the one you've assembled yourself to verify it?
afaik ipa files cannot be installed by ordinary users, so it makes no sense to put it in releases

**Comment by emanuelb** [comment]
it does makes sense, for once I don't have jailbroken device, also I didn't test it but you can read at issue:
https://gitlab.com/walletscrutiny/walletScrutinyCom/-/issues/149
which showed that there is diff between the .ipa file uploaded by airgap wallet to apple to one taken from jailbroken device (what you suggest to do), in android appbundle the server-side operation work by bundletool which is open-source and available, on ios I am not aware about what is happening on server-side (is there any published tool to reproduce the operation?), so the first step of useful verification is to compare against what the vendor publish to apple, so that's why I ask for vendors to publish the .ipa file in github releases, as this result should be reproducible.
comparing to .ipa taken from jailbreaked device is the second step, read the linked issue in this repo it contain more details on how it works and why publishing the .ipa is needed (not one taken from jailbreak device, but the one compiled by the vendor,uploaded to store...)

**Comment by marcosrdz** [comment]
IPA file, along with sig file, is available on Github releases.
