### ISSUE TITLE
Apply for bitcoin.org review again after self-certify

### ISSUE THREAD

**Issue by emanuelb** [BlueWallet/BlueWallet#3103]
The last review was done in 2019 here:
https://github.com/bitcoin-dot-org/Bitcoin.org/pull/3000#issuecomment-522330241

The current list of criteria/checklist is:
https://github.com/bitcoin-dot-org/bitcoin.org/blob/master/docs/managing-wallets.md

so apply for the review again after self-certification (checking that all criteria are passed before applying)
for example regarding the HSTS issue on the website I opened #3101 for it.

also may be worth to self-certify for CII program before applying to bitcoin.org again , see issue #3102

**Comment by ncoelho** [comment]
No plans to apply for listenings on 3rd party websites at the moment.
