### ISSUE TITLE
Unexpected Cobo import behaviour

### ISSUE THREAD

**Issue by Beemyguest** [BlueWallet/BlueWallet#3107]
Downloaded Bluewallet, using default network electrum server, imported (scanned) QR from cobo (firmware 2.6.1) as watch-only in the Cobo Settings>Watch-only Wallet>BlueWallet.

Wallet is imported but has full signing functionality(!) and is identified as "Imported HD Legacy Electrum (BIP32 P2PKH)" with a "1..." address even though it's supposed to be native segwit.

> Small aside: When pointing to my own electrum server, the HD Legacy wallet no longer has send functionality "missing txhex of the input"
> 
> Reverting to Bluewallet's electrum2.bluewallet.io returns send functionality.

Check wallet in BlueWallet. "Export/Backup" Zpub, HD path, fingerprint all match Cobo Vault.

BlueWallet > "Show Wallet XPUB" shows a totally different xpub!

Figure maybe it's Cobo. Import into Sparrow and wallet behaves as expected, matching all data zpubs/xpubs.

Go back to Bluewallet, importing from Cobo using Settings>Watch-only Wallet> (Electrum or Generic) result in properly behaving "Imported Watch-only" wallet with native segwit addresses.

Is this an issue on Cobo's end or Bluewallet?

**Comment by Overtorment** [comment]
check the QR code that cobo shows, the one that produced the wrong wallet type.
you can scan it with any other scanner and see its contents. it should have *zpub* inside, not the *xpub*

**Comment by Beemyguest** [comment]
> check the QR code that cobo shows, the one that produced the wrong wallet type.
> you can scan it with any other scanner and see its contents. it should have _zpub_ inside, not the _xpub_




> > Figure maybe it's Cobo. Import into Sparrow and wallet behaves as expected, _matching all data zpubs/xpubs_.

**Comment by Overtorment** [comment]
can you record a video and send it to bluewallet@bluewallet.io ?

**Comment by Beemyguest** [comment]
Sure, will do it when I get a moment.

**Comment by Overtorment** [comment]
did you send it? im kinda lost in our mailbox, cant find it

**Comment by Beemyguest** [comment]
Yes, sent it on the weekend.
________________________________

**Comment by Overtorment** [comment]
got it. requested access for file from your google drive

**Comment by Overtorment** [comment]
fixing it here: https://github.com/BlueWallet/BlueWallet/issues/3152
this one is closed.
