### ISSUE TITLE
Can't send transactions

### ISSUE THREAD

**Issue by Hodan1980** [BlueWallet/BlueWallet#3123]
Hi,

I am using bluewallet on iPhone and in general I am happy with it but at the moment I can't send transaction from it and I am really worried since I have significant amount of money in it. In the moment I am hitting "send" and it reveal the next screen where I should insert the amount, address, note etc. it is stuck with the fee ... It is just spinning/loading for indefinite time and I can't press on anything else :( The screen freezes and I can't even close it - I need to restart the app... Please help!!!!

**Comment by limpbrains** [comment]
Loading indicator has been fixed in #3241
