### ISSUE TITLE
Can't import wallets created using the optional BIP39 passphrase

### ISSUE THREAD

**Issue by compatibilizer** [BlueWallet/BlueWallet#3135]
Importing a watch-only wallet, whose master key is created with an **optional BIP39 passphrase** results in staying locked out of account when you want to spend the funds.

To reproduce :

Go to https://iancoleman.io/bip39/ and generate a random mnemonic  **using an optional BIP39 passphrase**
Import watch-only wallet using Account Extended Public Key (xpub/ypub/zpub)
Receive funds in the addresses generated by this watch-only wallet
When you want to sweep this account, you can't access the funds in Bluewallet!

Why:

Importing the wallet using just seed mnemonic (without BIP39 passphrase) results in a different root. Importing seeds with a BIP39 passphrase is not supported in Bluewallet. The problem could be circumvented by importing a wallet using Account Extended Private Key (**xprv/yprv/zprv**) but they're not recognized as valid inputs either.

Solution alternatives:

a) Query optional BIP39 passphrase during seed mnemonic import
b) Using a menu item in advanced settings, allow modifying the account root with the optional passphrase
c) Allow importing a wallet using extended private keys (xprv/yprv/zprv)

**Comment by steve-vincent** [comment]
suggestion A sounds elegant. 
I found this issue after typing 13th word, thinking it would work...

**Comment by Overtorment** [comment]
bip39 passphrase was implemented and released.
xprv support ticket:  https://github.com/BlueWallet/BlueWallet/issues/3197

**Comment by steve-vincent** [comment]
it days 6.2.2 (build 7/27) includes this, but i installed from latest release page.... it does not show new UI to support passphrase
