### ISSUE TITLE
Marketplace shows NaN amount payment request

### ISSUE THREAD

**Issue by pseudozach** [BlueWallet/BlueWallet#314]
Scenario: Testing withdrawal from LN Hunt Lapp on marketplace  

Steps:
1. Have more than 0 balance (2660 satoshis in my test) on website, click withdraw.
2. Lapp requests invoice for 2660 amount via WebLN.
3. Bluewallet catches the request and shows pop up "Lapp wants to send you NaN satoshis"
4. Click OK. 2660 satoshi amount invoice created by the app and lapp pays the invoice.
5. Bluewallet shows 0 satoshis received, user balance is not increased but Lapp backend paid 2660 satoshis.

**Comment by Overtorment** [comment]
Acknowledged.
This happens because lnhunt is not passing amount, and bw backend creates
zero-amount invoice, bit the client is not ready for zero-amount invoices
yet. Pass full amount to webln call, or as a workaround, I will add
sub-step asking user for amount he wants to receive

**Comment by pseudozach** [comment]
you are right, I just checked and I wasn't making sure it was a number, it probably gets called as a string. Fixed on my side but still good idea to double check on bluewallet as well.

**Comment by Overtorment** [comment]
Will do! So are any chanes necessary on my side, except validation..?

**Comment by pseudozach** [comment]
It takes a while for my website updates to go through so I haven't tested yet. But yes you can add some extra validation and close. thanks.

**Comment by Overtorment** [comment]
@pseudozach any progress?

**Comment by pseudozach** [comment]
Done and tested.
