### ISSUE TITLE
Apple Watch not updating

### ISSUE THREAD

**Issue by iivarih** [BlueWallet/BlueWallet#3141]
Apple Watch doesn't update wallet balances or recently added wallets.

**Comment by marcosrdz** [comment]
What version of BlueWallet?

Would you mind sharing the types of wallets you have ?

This can help in the debugging process

**Comment by iivarih** [comment]
Thanks for the reply!

 BlueWallet version is 6.1.2 (build 1620538431), but the watch app hasn't updated balances and new wallets for a long time (i believe there has been several updates after the issue started). Transaction history says I received some lightning 17 days ago and that never showed up on the watch side.

 I have two bitcoin wallets, a lightning wallet and a vault. All but the second bitcoin wallet show up on watch but without any transactions and zero balance.

PS. Just tested to create a lightning invoice on watch and it immeadiately showed up on phone.

**Comment by marcosrdz** [comment]
Managed to replicate. Fix will be available on our next release. Thank you for reporting!
