### ISSUE TITLE
please add toman or IRrial (iran currency) preview for wallet

### ISSUE THREAD

**Issue by saremeskandary** [BlueWallet/BlueWallet#3143]
you can use [this website](https://arzdigital.com/coins/bitcoin/) or iranian exchanes like [exir](https://pro.exir.io/trade/btc-irt) or [nobitex](https://nobitex.ir/).
tank you

**Comment by marcosrdz** [comment]
https://api.exir.io/v1/ticker?symbol=btc-irt 

To confirm, which one would be the current price? Would it be "last"? Meaning the number in "last" would get you 1 BTC?

**Comment by saremeskandary** [comment]
last is the current price
