### ISSUE TITLE
Add BitcoinUnit.Bits as a currency denominator

### ISSUE THREAD

**Issue by ishristov** [BlueWallet/BlueWallet#3144]
Blue wallet currently support `BTC`, `Sats` and a `fiat` option as a main currency across the wallet.

My request is to add `Bits` because that is the best denominator and will help with adoption. My reasonings are:

- It consists of 100 sats, so it is similar with the most common currencies like USD and Euro;
- We'll be able to price things with bits.sats just like we price things with dollars.cents (e.g. $5.50) or euros.cents;
- It is much easier to calculate from BTC because it is `BTC/1000/1000`. 1000x is what is generally used to show the next order of magnitude in almost anywhere (`1 thousand is 1000`, `1 GB = 1000 x 1000 KB`, `1 tone is 1000 x 1000 grams`);
- BTC scares people because "it's too high" and sats is a bit intuitive because it's too small. Most people will never be able to afford 1 BTC and it's impossible to own 1 sat (dust limit) unless on lightning;
- Currently 1 bit is 5 cents which is easy to understand. If BTC reaches 1m, that will make `1 bit = $1` which will make pricing a breeze. And if BTC's total market cap reaches 100T, that would translate to `1 bit = $5` which is again pretty straightforward for everyone as most currencies fluctuates between $0.01 and $2;
- We don't use cents to price things in the real world so trying to make "sats" the main denominator would be counterintuitive to people outside of crypto;
- According to [Adam Back](https://twitter.com/adam3us/status/1335363437841485831) the satoshi (sat) was initially intended the to be a 2digit decimal bitcent after the smallest base unit, which was supposed to be a `bit`;
- It just sounds good and make sense to have `bits` be the main currency of the internet.

**Comment by ishristov** [comment]
@Overtorment, any reason why this was closed?

**Comment by Overtorment** [comment]
Bits won't be added

**Comment by ishristov** [comment]
Why not? It's not an unreasonable request and other wallets have the option for displaying things in bits.
