### ISSUE TITLE
VersionCode=1 in AndroidManifest from generated APK instead of 1620538430 from apk in github

### ISSUE THREAD

**Issue by emanuelb** [BlueWallet/BlueWallet#3148]
Generating APK locally in linux container result in AndroidManifest.xml which have versionCode=1:
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1"
```

while the apk in: https://github.com/BlueWallet/BlueWallet/releases/download/v6.1.2/BlueWallet-6.1.2.apk have:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android" android:versionCode="1620538430"
```

The locally generated apk from tag should have a matching version-code to the one in github release.

**Comment by Overtorment** [comment]
this is a timestamp and its inserted by CI (appcenter.ms) during build time

**Comment by emanuelb** [comment]
timestamp value is not reproducible unless it's written somewhere and then reused if compiled from the same tag in order to achieve reproducible result, while timestamp kinda make sense for test/debug builds, for release builds probably another algo can be used which is more meaningful, also for time related fix the usage of env var `SOURCE_DATE_EPOCH` may help.

**Comment by Overtorment** [comment]
not much can be done as its appcenter's default.
for reproducible builds you can insert actual timestamp from released build manually
