### ISSUE TITLE
Upgrade Flipper Deps

### ISSUE THREAD

**Issue by emanuelb** [BlueWallet/BlueWallet#3162]
https://github.com/BlueWallet/BlueWallet/blob/0ec80f0616db9efc5204e6758630171fbe6985b7/android/gradle.properties#L33-L34

latest version is: 0.90.2
https://mvnrepository.com/artifact/com.facebook.flipper/flipper

https://github.com/BlueWallet/BlueWallet/blob/af0dc8d2aa43f87db567387f82d36b35d9ce2a7d/ios/Podfile#L15

latest version for Flipper-Folly is: 2.6.7
https://cocoapods.org/pods/Flipper-Folly

latest version for Flipper is: 0.90.2
https://cocoapods.org/pods/Flipper

latest version for 'Flipper-RSocket' is: 1.4.3
(From search "Flipper-RSocket" in https://cocoapods.org/pods/)

**Comment by Overtorment** [comment]
@marcosrdz thoughts?

**Comment by marcosrdz** [comment]
We align with the version that the RN comes with. 

https://react-native-community.github.io/upgrade-helper/

The exception being if a Xcode upgrade fails to compile.
