### ISSUE TITLE
Pending Status UX

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#3183]
As the pending experience can be a stressful moment for new users, we can improve their expectations by showing a "real time" or approximation (eta) of how long it will take for a 1st confirmation. 

https://github.com/BlueWallet/BlueWallet/discussions/2688

**Comment by Overtorment** [comment]
ok i think we are in a position to actually start implementing this.


we can start from the **receive** screen:
on receive screen, when user is staring at his address QR code, periodically (like, 5 sec) check address balance via electrum,
and if there is unconfirmed balance on this address show this:

![image](https://user-images.githubusercontent.com/1913337/126863410-097c8838-c50f-4e74-b7d1-db6e06846c27.png)

(without "bump fee" button, too complicated for now)

and if polling returns confirmed balance, show this:

![image](https://user-images.githubusercontent.com/1913337/126863477-840450b9-860d-4189-884c-1795bf7b7698.png)
(should be gree incoming arrow icon)

**Comment by scottmilla** [comment]
Hi guys, I was gonna try to implement this but it seems like its kinda done.. Am I missing what you wanted to add on to what's currently there?

**Comment by Overtorment** [comment]
@scottmilla no this is not implemented (for onchain addresses), so you can go ahead.
basically, you can tap 'receive' on onchain address, and while staring at the qr code - send funds to this address from other device.
result: nothing changes, ever.
expected result: we should poll electrum (maybe 5 sec itnerval) and display other icon if there's pending balance on this specific address. show checkmark icon when this confirms and address has only confirmed balance

**Comment by ncoelho** [comment]
The idea on this one is more about the ETA (like mempool.space does). So users that don't know why transactions take time, in high fees scenarios have more context on what is going on.

**Comment by Overtorment** [comment]
yeah, fetching feerate of the pending transaction and comparing it to current fees is a nice detail

**Comment by scottmilla** [comment]
Thanks for the clarification! I'm getting familiar with the code base now, and will try implementing something soon.

**Comment by Overtorment** [comment]
is anyone working on this? i might take this

**Comment by scottmilla** [comment]
I am! Up to you though. Shouldn’t take long but I’m not sure about how to estimate fee/transaction time.

**Comment by Overtorment** [comment]
@scottmilla have you started already?

**Comment by scottmilla** [comment]
@Overtorment yes mainly on showing the icons, etc. No big deal though if you wanna hop in!
