### ISSUE TITLE
Self-Test succeeds, then consistently fails on subsequent attempts

### ISSUE THREAD

**Issue by sgornick** [BlueWallet/BlueWallet#3193]
## Are you reporting a bug?

Please provide:

* Samsung A10e with Android 9
* BlueWallet app version v6.1.2

* self-test passes? 

Yes, then no.

The first attempt to self-test passes fine, with OK.
The second attempt, responds nearly instantly with the following message:
 
`Error: Stream for connectionId [connnectionId] is not initialized, call startTcpConn first`

* unique ID for our crash reporting service (settings->about->scroll down, tap "copy")

user.id:3f3047eab012954d

## How to replicate:

- Launch BlueWallet v6.1.2
- Open settings->about->scroll down, tap "Run self-test"
- Wait ~90 or so seconds, then:

`OK`
`All internal tests have passed successfully. The wallet works well.`

- Press the Back arrow ( <-- )
- Tap "Run self-test".
- Within 5 or so seconds, see:

`Error: Stream for connectionId [connnectionId] is not initialized, call startTcpConn first`

All subsequent attempts to do a self-test result in the same manner.

But closing BlueWallet app and re-launching it will permit the self-test to be run again successfully (just the one time, with subsequent attempts yeilding that Error message again).

**Comment by vechitech** [comment]
`https://github.com/simplycash/simplycashwallet/Backup/Wallet: 1P5ZEDWTKTFGxQjZphgWPQUpe554WKDfHQ/v0`

**Comment by Overtorment** [comment]
problem with tor (reported here https://github.com/BlueWallet/BlueWallet/issues/3079 )
for now tor is excluded from self-test (in newest bw version)
