### ISSUE TITLE
Cannot read seed words for vault key - mostly blank

### ISSUE THREAD

**Issue by raymondclowe** [BlueWallet/BlueWallet#3232]
I believe this is a bug, perhaps a formatting bug.

* OnePlus 6 - Android 10, OxygenOS 10.3.11 - Build number ONEPLUS A6003_22_210511 - Model ONEPLUS A6003
* bLUEwALLET VER 6.1.4 (build 1621515471)
* Self test passed OK
* user.id:603d8bf0778186f4  

(Note that when copying the user id the word "copy" is truncated to "cop")

I have just installed the app, have not created any wallets.  Just looking around to see what the options are and decided to look at "vault" as I am not familiar with that.

Steps to reproduce:

Closed, stopped and cleared storage/cache to ensure a clean test
Open app
Tap "Add"
Tap "Vault"
Tap "Create"
Tap "Let's start"
Tap "Create New"

What I see at this point is in screenshot.  The numers 1. through 12. should have words, but do not.

Tried this three times.

First time all words blank
Second time one word appeared (this is the screenshot attached)
Third time, all words blank.

![Screenshot_20210531-105440](https://user-images.githubusercontent.com/68897994/120134200-32066300-c200-11eb-9b1e-450105e9827b.jpg)

**Comment by ncoelho** [comment]
Hi, change your phone font to the default value please and let me know if it helps.

**Comment by raymondclowe** [comment]
![Screenshot_20210531-175115](https://user-images.githubusercontent.com/68897994/120175639-0358ae80-c239-11eb-843b-a05aac30806f.jpg)

My phone is already at the default font size.  I actually had to factory reset my phone just a few weeks ago so it is quite "clean".

**Comment by ncoelho** [comment]
Not the font size. The font type, if your phone is not using the android default font "roboto". You will face this kind of problems.

**Comment by raymondclowe** [comment]
I am using the default font for this phone .

![Screenshot_20210531-184725](https://user-images.githubusercontent.com/68897994/120182346-da3c1c00-c240-11eb-82e8-1055265e0635.jpg)

Changing to the alternative font fixes the display problem.

Thanks.
