### ISSUE TITLE
Notifications don't turn on

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#3235]
Seen on iOS and android

Error from logs:

> 06-01 09:46:06.566 I/rokuapp.com/...(21405): type=1400 audit(0.0:6228): avc: denied { read } for name="81b9768f.0" dev="dm-5" ino=8765 scontext=u:r:untrusted_app_29:s0:c249,c256,c512,c768 tcontext=u:object_r:system_data_root_file:s0 tclass=file permissive=1 app=io.bluewallet.bluewallet

https://user-images.githubusercontent.com/1238429/120303740-6a28a700-c2cf-11eb-8a26-2996d604a601.mp4

**Comment by Overtorment** [comment]
that was the problem with push notifications server. 
its back online now
