### ISSUE TITLE
The use of "Amount" in "Buy BTC" page is unclear and beyond the user's understanding

### ISSUE THREAD

**Issue by wuyih9** [BlueWallet/BlueWallet#3247]
I found that "Amount" in "Buy BTC" page is confused the user, who did not know what the "Amount" was for and what it stood for. In this application, we can know "Amount" is meant to represent the amount of "BTC" or "USD" as shown in the figure. However, the point of confusion for the user is if the user wants to buy "300" USD of the bitcoins. Then, what does the "BTC price" displayed in the "Summary" represent? Much to the user's confusion, is the user spending "300" USD to buy "0.00824" bitcoin? But we know for sure that's impossible. So what does "Amount" actually mean and represent?

**Comment by marcosrdz** [comment]
The page rendered inside the Buy Bitcoin page is handled by MoonPay. It is not BlueWallet.
