### ISSUE TITLE
Unnecessary feature

### ISSUE THREAD

**Issue by wuyih9** [BlueWallet/BlueWallet#3248]
I found that the "+" button in the upper right corner of "Home" page and the trigger event in the "Add Now" button will result in a jump to the page in "Add Wallet" page. I think it's OK to remove one of them between the "+" button and the "Add Now" button. Based on "Add Now", there are some simple descriptions to make it clear to the user what the button is for. Therefore, I think the "+" button can be removed. They overlap functions between the two, so one is not practical.

**Comment by marcosrdz** [comment]
This allows you to add a wallet, be it new or imported, without having to scroll to your last wallet.

**Comment by wuyih9** [comment]
#3261
