### ISSUE TITLE
Not enough confirmed inputs

### ISSUE THREAD

**Issue by codenamecoder** [BlueWallet/BlueWallet#325]
I can’t refill my lightning wallet from my bitcoin wallet, or send out from my bitcoin wallet to an external address without getting this error. Poor user experience, no reference to what this means and nothing I could find here or on google. My bitcoin is locked in the blue wallet until I can find a resource for correcting this. Thanks!

**Comment by Overtorment** [comment]
When you sent bitcoins to BW, how many confirmations you now have..?

Also, people reported that sometimes this error is thrown when device is
working through VPN or TOR.

Worse case scenario, you can export your wallet menmonic phrase and import
it in any other wallet.

**Comment by codenamecoder** [comment]
Thanks Igor, I understand now. I only have 1 confirmation so far. How many do I need?


On Feb 14, 2019, at 09:59 AM, Igor Korsakov <notifications@github.com> wrote:


When you sent bitcoins to BW, how many confirmations you now have..?

Also, people reported that sometimes this error is thrown when device is
working through VPN or TOR.

Worse case scenario, you can export your wallet menmonic phrase and import
it in any other wallet.

**Comment by Overtorment** [comment]
Actually should be enough. But sometimes API BW uses is lagging behind, so
give it a little bit of time.
Also, we are working on migrating away from that API.

**Comment by codenamecoder** [comment]
Ok it went through, I am on a vpn so that was a concern. It was 10 minutes ago and it still hasn't shown up in my lightning wallet yet but I'm sure it will in a few more minutes.



Great support, thank you!


On Feb 14, 2019, at 10:07 AM, Igor Korsakov <notifications@github.com> wrote:


Actually should be enough. But sometimes API BW uses is lagging behind, so
give it a little bit of time.
Also, we are working on migrating away from that API.

**Comment by Overtorment** [comment]
Lightning wallet will require 3 confirmations.
Also, pls do manual pull-to-refresh on lightning wallet. Automatic refresh
will arrive in next release.
Cheers!
