### ISSUE TITLE
Error feedback in Lightning Settings

### ISSUE THREAD

**Issue by dangeross** [BlueWallet/BlueWallet#326]
I recently setup LndHub on my own node and tried to connect to it via the Lightning Settings. The app gives no feedback positive or negative to say that the user has entered the correctly formatted URI for the node.

I tried entering the following and the last one worked. But I only knew from monitoring the LndHub log:
- IP_ADDRESS
- IP_ADDESSS:PORT
- http://IP_ADDRESS:PORT

**Comment by Overtorment** [comment]
Valid point!

Wats your experience using Bluewallet with your own node?

**Comment by dangeross** [comment]
Slick! 🤘Loving it.  

Barrier to entry is high though setting up LndHub on your own node. I wrote a guide for setting it up on [RaspiBolt](https://github.com/dangeross/guides/blob/master/raspibolt/raspibolt_6B_lndhub.md) to help others having trouble on [Reddit](https://www.reddit.com/r/lightningnetwork/comments/aps06u/help_with_bluewallets_lndhub_installation_on/). Hope it helps

**Comment by ncoelho** [comment]
this one is done
