### ISSUE TITLE
FlatList Wallet Carousel

### ISSUE THREAD

**Issue by marcosrdz** [BlueWallet/BlueWallet#3273]
Rewrite Wallet Carousel to use FlatList so we can take advantage of builtin RN functionality and one less dependency

**Comment by blankscreengithub** [comment]
I currently have 20 wallets in my horizontal scrolling list. Scrolling to the right and left in a fast manner on android results in a jittery scroll. Would this change remove this issue?

Maybe there could be a drop down list of some sort between the word "Wallets" and the "+" sign on the home screen where I could quickly open the wallet I need?

Or even if I could just do a single tap on the "Re-order Wallets" screen and open that wallet directly?

The horizontal scrolling of wallet cards is clunky with this many wallets.
