### ISSUE TITLE
Node Modules Install Failure in windows 10

### ISSUE THREAD

**Issue by ritvikshandilya** [BlueWallet/BlueWallet#3286]
Issue coming in the very first step with  the latest version of bluewallet : npm install,

node -v
v14.17.1

npm -v
7.17.0

Expected: No error shall come after npm install
Actual: 

```
npm ERR! code 1
npm ERR! path C:\Users\Ritvik\Downloads\BlueWallet-master\BlueWallet-master\node_modules\detox-recorder
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c ./postinstall.sh
npm ERR! '.' is not recognized as an internal or external command,
npm ERR! operable program or batch file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Ritvik\AppData\Local\npm-cache\_logs\2021-06-17T17_05_52_834Z-debug.log
```

**Comment by Overtorment** [comment]
@marcosrdz  do you thinks its `detox-recorder`'s issue..?

**Comment by marcosrdz** [comment]
Yup. Doesnt get along with Windows. Lets remove it since its not really a dependency we absolute require to develop. It can be reinstalled on a local instance for new e2e tests
