### ISSUE TITLE
SSS-Import fails

### ISSUE THREAD

**Issue by Abstraktikus** [BlueWallet/BlueWallet#3297]
* Samsung Galaxy S8
* BlueWallet Version 6.1.5
* Self-Test: OK
* UID 4b7e02775be7db90

According to https://iancoleman.io/slip39/ all of the SLIP39 SSS parts below are correct. But BlueWallet refuses their import. 

Generated with Trezor Model T: ---> Master Seed: 765acd980cb9ab91aee9ac61d6dddfda
salon smug academic acne coding sunlight transfer problem tracks pecan public theory vexed leaves vanish lecture short sunlight inherit dwarf
salon smug academic agree alarm coding junior emperor dining webcam duration suitable soul merchant guard visual response floral mixed furl
salon smug academic amazing depict meaning debut mouse desktop daisy machine peaceful hanger forward smug sugar thunder true loyalty guitar
salon smug academic arcade belong improve payment lamp threaten increase alive ocean express evening employer primary mobile hamster gather amazing
salon smug academic axle ancestor pacific aunt slavery scatter hearing crazy metric spider ugly ceramic thank scramble isolate item observe

Generated with a CoboVault: ---> Master Seed: bf7a75d54ddb23bd9a46065e55e16edb
crucial pajamas academic acne biology acrobat sugar silver medical losing scatter evening obtain budget corner category race husky wildlife unkind
crucial pajamas academic agree debut patrol shaped campus result pencil living ruin usual laden again group exhaust decision ceiling silent
crucial pajamas academic amazing answer grownup unfair vampire adorn race valid kind promise learn discuss dynamic fraction rhythm blessing always
crucial pajamas academic arcade deadline scene wrist company decorate multiple provide visitor scout tolerate birthday isolate paper zero smart crush
crucial pajamas academic axle daisy charity duration mortgage process charity laden dragon party ladybug cultural escape superior destroy friar believe

Generated with https://iancoleman.io/slip39/ ---> Master Seed: d548dbec38c1dc1dd743efa0ebf11bc7
ocean away adjust academic downtown epidemic plains wine density upgrade royal warmth remind anatomy behavior hush idea venture various rebound
ocean away being academic carbon damage robin identify photo intend column bucket beard declare database fangs picture anxiety maximum fancy
ocean away chemical academic duckling building pencil force density kitchen away pickup mixture paper soul prune length boring freshman wrap
ocean away demand academic bumpy ladle python snapshot photo welfare volume endorse document numerous unkind moisture favorite unfold center branch
ocean away elder academic blimp priority wrist exotic stilt plastic agree random axle aviation inmate negative counter medal amount mobile

**Comment by limpbrains** [comment]
After converting SLIP39 SSS parts to master seed BlueWallet tries to find what kind of wallet it should import (bech32, P2PKH or P2SH). So it generates addresses for all of them and checks if there are any transactions. All the wallets you have provided are new, that is why BW can't find suitable wallet to import. This behavior is not absolutely correct, so I'm changing it and after the fix it will import Bech32 wallet by default, even it is empty.

**Comment by Abstraktikus** [comment]
Great! - Thank you very much for the ongoing efforts. I have ordered a https://keyst.one/ to build a real SLIP39 setup.  BlueWallet offers, to my knowledge, the industry's first end-to-end solution for SLIP39. End-to-end because the HW alone is not a sufficient backup.  So, for the first-time mankind has the possibility to use a SSS-SLIP39 configuration without further tools. Thanks to BlueWallet, SSS via SLIP39 has left the beta phase and is now usable. You've just written a little bit of code history.

Why this is so exciting is due to the complexity of setting up a MultiSignature Wallet. Sorry, that should be even easier. It is therefore easier to carve 5x12 words in steel than to create a MultiSignature backup. And the generated standard wallet is easier to use. 
Conclusion: In combination with https://keyst.one/ there is now a PSBT + SLIP39 solution on the market and BlueWallet is the only software for it!
Once my setup is up and running, I think it would be worth a more proper announcement. If necessary, with a video. I still have CoboVaults and will have to check if the new Keystone Firmware offers the same feature. I'll get back to you after that.

From my point of view, this is a noticeably big step towards a feasible, unconfiscable self-custody system. To keep 12 words hidden under the mattress is simply not good enough. And I can't do a multi-signature wallet to my relatives. 

I really don't understand, why I'm the only one celebrating it like this. Except, of course, the CryptoTag providers. (https://vimeo.com/291784521 - They should also celebrate 5x12 words :-)

**Comment by Overtorment** [comment]
@Abstraktikus a video would be nice!
can you elaborate a bit on your intended setup, I don't quite get it? how should SSS work in a combination with the Keystone device?
