### ISSUE TITLE
Disable Analytics does not disable Sentry.io connections

### ISSUE THREAD

**Issue by licaon-kter** [BlueWallet/BlueWallet#3309]
Trying the [recipe](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/9259) for https://github.com/BlueWallet/BlueWallet/issues/233 I'm looking at the resulting APK, and I see that disabling analytics does not influence Sentry data leaking.

Is this by design?

Ref: https://github.com/BlueWallet/BlueWallet/issues/3084

**Comment by Overtorment** [comment]
do you see actuall onnections via some sort of traffic sniffer?
we have this fix for sentry: https://github.com/BlueWallet/BlueWallet/pull/3302
not sure maybe it'll solve this issue as well
cc @marcosrdz

**Comment by licaon-kter** [comment]
https://github.com/M66B/NetGuard

**Comment by Overtorment** [comment]
@licaon-kter can you retry with fix from #3302 ? (merged to master but not yet released)

**Comment by licaon-kter** [comment]
@Overtorment nope :(

**Comment by marcosrdz** [comment]
I'll look into this

**Comment by Overtorment** [comment]
sentry removed in the latest release.
