### ISSUE TITLE
Scanning QR for Electrum Server Fails in Various Ways

### ISSUE THREAD

**Issue by tehelsper** [BlueWallet/BlueWallet#3315]
* Phone: Pixel 4a
* Version: 6.1.6
* Self Test: Pass

Several random bugs / notes:

1. I've scanned the QR code for a secure connection to connect to a local Electrum server, but it puts the port in the TCP port rather than SSL which makes Save operation fail. A user needs to know to move the port to SSL before it will save.

2. Scanning a Tor-based URL for electrum was failing until I followed these instructions. Having some data in the fields prior to scanning seems to cause a URL parse failure every time until resetting the server, restarting app, and rescanning. (Duplicate of https://github.com/BlueWallet/BlueWallet/issues/3262)

3. Tor + SSL does not seem to work properly for electrum scanning. I was able to get 50001 to work just fine and 50002 is working fine for local connections. (minor, I can just make the QR use 50001)

**Comment by marcosrdz** [comment]
Would you mind sharing QR Code ?

You can send it to bluewallet@bluewallet.io

**Comment by tehelsper** [comment]
Email sent. Thanks.

**Comment by Overtorment** [comment]
@marcosrdz i think that was fixed in recent pr..?

**Comment by marcosrdz** [comment]
Scanning a Tor-based URL for electrum was failing until I followed these instructions. Having some data in the fields prior to scanning seems to cause a URL parse failure every time until resetting the server, restarting app, and rescanning. (Duplicate of Problems connecting to electrum over tor after ssl port is already specified #3262)

FIXED in recent PR. Fields will be cleared out before inserting the new scanned values.

**Comment by marcosrdz** [comment]
By default, the provided port number goes into TCP port. We may need to provide a parameter that would let us know which field to insert the port into OR provide an alert letting the user pick where to have it inserted.

**Comment by tehelsper** [comment]
I was just about to ask for that. I would be nice if I could set ssl_port vs tcp_port or something to be explicit. Perhaps "port" could also make a more intelligent guess. 50002 seems pretty consistently meant to be SSL.

**Comment by marcosrdz** [comment]
@Overtorment  perhaps an "easy" way is to assume that if 50001 was scanned then insert into TCP, if its 50002 then insert into SSL field, otherwise default to TCP?

**Comment by Overtorment** [comment]
no need to guess. if port is SSL, scanned string looks like this:

`electrum1.bluewallet.io:443:s`

and plain TCP:


`electrum1.bluewallet.io:50001:t`

**Comment by tehelsper** [comment]
@Overtorment Thanks, I missed that the ":t" or ":s" was supported in the electrum URL. That's exactly what I was looking for.

@marcosrdz I like the toggle! Looks nice.
