### ISSUE TITLE
Save to disk exception - realm file decryption failed

### ISSUE THREAD

**Issue by pysiak** [BlueWallet/BlueWallet#3332]
I had bluewallet on an iPhone 7. I migrated to iPhone 11. When I launch bluewallet I get this:
![image](https://user-images.githubusercontent.com/2396137/123832274-78d1a080-d905-11eb-8942-ae9e69dbd3ed.png)

The iPhone 11 has some MDM restrictons.

What do?

**Comment by Overtorment** [comment]
how did you migrate from iphone7 to iPhone 11?
looks like encryption key didn't migrate for this particular database file

**Comment by Overtorment** [comment]
luckily this is not very important database file, so we could probably handle this exception and recreate this database from scratch.

you could also backup wallet export, and then reinstall bluewallet

**Comment by pysiak** [comment]
new phone was restored from iCloud backup of previous phone. I made sure previous phone had a very recent backup.
where are the keys stored? iCloud keychain?
I know that the new phone is managed and has some OS-level restrictions. Perhaps in such scenario this fails.

Restrictions I have are:
1. Authentication before Auto Filling passwords enforced
2. Managed apps cloud sync not allowed
3. Diagnostic submission not allowed
4. Unmanaged apps read managed contacts allowed
5. USB drives not accessible in Files app
6. Sharing managed documents using AirDrop not allowed
7. iCloud Keychain not allowed
8. Delay period for Delayed Software Updates is 45 days
9. Safari fraud warning enforced
10. Synchronizing enterprise books notes and highlights not allowed
11. Managed apps write to unmanaged contacts allowed
12. Network drives not accessible in Files app
13. Documents in the Cloud not allowed
14. Delayed Software Updates enforced
15. Wrist detection enforced on Apple Watch
16. Establishing untrusted TLS connections not allowed
17. Opening documents from managed to unmanaged apps not allowed
18. Backup up enterprise books not allowed
19. Limited ad tracking enforced

Perhaps #7, #13, maybe #12 are causing issues in my situation. I suspect that may be some of it because I'm seeing the new phone cannot decrypt my Breez wallet, says PIN incorrect. 

I will try to reinstall and restore using an export and report how that goes.

**Comment by Overtorment** [comment]
`iCloud Keychain not allowed` might be the issue.
but the existing wallet survived the migration? in this case, it's a bit odd.

**Comment by motud2** [comment]
I have th same problem on iPaf.

New iPad restored from old iPad.

![B429E1F4-1B08-4853-BA7E-0F6D3C3CC324](https://user-images.githubusercontent.com/38567532/125287417-cb06be80-e314-11eb-8367-51b8b72550a3.jpeg)

**Comment by brendanphall** [comment]
Same problem occurring after backup / restore on Mac OS 11.3.1

**Comment by Overtorment** [comment]
fix should make it into the next release
