### ISSUE TITLE
impossible to add decimals in fiat

### ISSUE THREAD

**Issue by andresbezem** [BlueWallet/BlueWallet#3349]
## Are you reporting a bug?

Please provide:

* your phone model and OS version
iPhone 12 - IOS14.6

* BlueWallet app version (settings->about->scroll down)
 6.1.6

* self-test passes? Open settings->about->scroll down, tap "Run self-test"
all successful

* unique ID for our crash reporting service (settings->about->scroll down, tap "copy")
user.id:5D030230-AC5D-40DA-9313-CBCBAF659601

## Proposing a feature?

Go right ahead

When trying to enter an amount on FIAT (euros in my case) it will not accept the comma(,) to enter the cents
So when I want to receive €3,20 it will ignore the decimals and enter €320
Since I want to use lightning for small payments, those decimals are important

Thanks in advance for resolving the issue, and great work with the wallet!

**Comment by marcosrdz** [comment]
Thank you! We are currently working on fixing this issue. A temporary solution would be to use "." Instead of "," by switching keyboards or by pasting the total amount with "." From another source.

**Comment by andresbezem** [comment]
Thanks for the fast answer.

The comma is the only available in the numeric pad, no “.” There to use, nor a chance to change keyboard in the phone.

Pasting the total from another place works well. Thanks for the temporary fix 

:)

**Comment by marcosrdz** [comment]
Changing your keyboard to something like US Keyboard will show the "." On the numeric pad. 

Those are the two temporary solutions while we implement a fix.

**Comment by andresbezem** [comment]
My keyboard has always been in US qwerty Keyboard. That’s my default keyboard in my IOS, in my coinomi wallet even though the numeric pad shows a comma it writes a period, but still the comma appears in the blue wallet and it doesn’t type anything

Creo que por tu nombre podemos escribir en español, no? Quedo esperando a que hagan el update y se solucione el tema de los decimales.

Saludos!

**Comment by marcosrdz** [comment]
#3243
