### ISSUE TITLE
Sweep segwit address returns legacy address

### ISSUE THREAD

**Issue by JijoBose** [BlueWallet/BlueWallet#3362]
When sweeping a paper wallet that contains Segwit address that starts with 3, it returns legacy address instead of address starting with 3

I have pasted a sample paper wallet below, you may scan it with the latest version of BlueWallet available in PlayStore.

<img width="1768" alt="Screen Shot 2021-07-08 at 10 58 20 AM" src="https://user-images.githubusercontent.com/13100108/124867487-d176fc80-dfdb-11eb-97cc-c0e374c0ec3e.png">

**Comment by marcosrdz** [comment]
BlueWallet's import procedure automatically detects wallet type based on transactions. If transactions are found during the matching process, it will select the one with transactions. If none are found, it selects the legacy wallet type. Send some BTC. to an empty wallet and then import it to BlueWallet.
