### ISSUE TITLE
iPadOS wallet list issue after v6.1.7 update

### ISSUE THREAD

**Issue by KHP86** [BlueWallet/BlueWallet#3363]
## Do you need support? Just email bluewallet@bluewallet.io
No

## Are you reporting a bug?
Yes

Please provide:

* your phone model and OS version
Apple iPad Pro 11-inch; iPad OS Ver.14.6

* BlueWallet app version (settings->about->scroll down)
6.1.7 Build 1625672198

* self-test passes? Open settings->about->scroll down, tap "Run self-test"
Yes

* unique ID for our crash reporting service (settings->about->scroll down, tap "copy")
No crash related to bug.

The bug seems to be an issue with layout of wallets in sidebar list. I have multiple wallets yet only one is displayed.
Issue exists in both landscape and portrait view.

please see attached screenshots for more details.

![57A1B15B-4ECF-4ECE-BD7A-0BDBBF21DF0D](https://user-images.githubusercontent.com/12993061/124919784-762d1600-dfab-11eb-98ac-5d920eeef0b5.jpeg)
![E3FABB98-D92B-4E04-AF78-090CA34BDE5C](https://user-images.githubusercontent.com/12993061/124919793-775e4300-dfab-11eb-9c00-c529722b19ca.jpeg)

**Comment by marcosrdz** [comment]
You should be able to scroll within that list to access other wallets. A fix  for this layout issues has been submitted for review.

**Comment by KHP86** [comment]
Thanks for the quick response! Looking forward to the update.
