### ISSUE TITLE
iOS widget "Next Block" sat/b calculation stuck at 52 sat/b

### ISSUE THREAD

**Issue by Wreckss** [BlueWallet/BlueWallet#3366]
## Are you reporting a bug?

Please provide:

* your phone model and OS version
iPhone 12, iOS 14.6
* BlueWallet app version (settings->about->scroll down)
ver 6.1.6 (build 1623737981)
* self-test passes? Open settings->about->scroll down, tap "Run self-test"
Tests passed
* unique ID for our crash reporting service (settings->about->scroll down, tap "copy")
user.id:0EE70BE4-AF7C-4241-8B97-D924B51F2675

## Proposing a feature?

Go right ahead

**Comment by marcosrdz** [comment]
#2580 

It is an issue we are working on. This is because the widget using the previous network estimation fee logic. We are working on updating it so it matches the new logic.
