### ISSUE TITLE
Problem in building the iOS app

### ISSUE THREAD

**Issue by shahrokhDaijavad** [BlueWallet/BlueWallet#3381]
I tried building the iOS app using the instructions and though the app built successfully for the simulator running on my Mac laptop , it gives an error when running  it. I am including screenshots of the successful build and the error I get. 
<img width="569" alt="Screen Shot 2021-07-09 at 9 07 49 AM" src="https://user-images.githubusercontent.com/11182134/125357262-4029c200-e31c-11eb-99e6-78e43a240b31.png">
<img width="398" alt="Screen Shot 2021-07-09 at 9 06 58 AM" src="https://user-images.githubusercontent.com/11182134/125357340-5cc5fa00-e31c-11eb-894f-6f1f5becf7d1.png">
<img width="426" alt="Screen Shot 2021-07-09 at 9 09 55 AM" src="https://user-images.githubusercontent.com/11182134/125357352-60f21780-e31c-11eb-8463-48b0180889c6.png">

**Comment by marcosrdz** [comment]
You need to run "npm start" at the root of the project and then click Reload

**Comment by shahrokhDaijavad** [comment]
Thank you. It solved the problem!
