### ISSUE TITLE
Alert: Critical error. Last actions were not saved

### ISSUE THREAD

**Issue by blankscreengithub** [BlueWallet/BlueWallet#3383]
Samsung S8
Android 9
BlueWallet version 6.1.9

This error randomly pops up and I'm not sure what is causing it. Self check result was OK.

**Comment by limpbrains** [comment]
How much free space do you have on your device?
How much space BlueWallet does BW take?
How many wallets do you have? Maybe you have a lot of transactions?

**Comment by blankscreengithub** [comment]
> How much free space do you have on your device?
> How much space BlueWallet does BW take?
> How many wallets do you have? Maybe you have a lot of transactions?

24.3 GB free
BW takes 191 MB
I have 19 wallets, mixed with single sig, vault, lightning, and imported watch only. I do a lot of lightning transactions, but not very many on-chain transactions.

**Comment by Overtorment** [comment]
do you have many lightning transactions? roughly how much? thousands?

its funny that we left this error message with expectation that _it should never happen_.

@limpbrains that's probably because ln transactions are not offloaded to realm like HD wallet transaction. should be relatively trivial to implement tho

**Comment by Overtorment** [comment]
as a workaround, probably worth transfer your ln balance to a fresh wallet and delete the old one

**Comment by blankscreengithub** [comment]
> do you have many lightning transactions? roughly how much? thousands?
> 
> its funny that we left this error message with expectation that _it should never happen_.
> 
> @limpbrains that's probably because ln transactions are not offloaded to realm like HD wallet transaction. should be relatively trivial to implement tho

I'm running my own LndHub if that makes a difference, so most of these transactions are internal to LndHub. My main lightning wallet has about 150 transactions and I have another 8 lightning wallets that have maybe another 160 transactions combined.

**Comment by blankscreengithub** [comment]
> as a workaround, probably worth transfer your ln balance to a fresh wallet and delete the old one

I could try that with the main lightning wallet.

**Comment by blankscreengithub** [comment]
> as a workaround, probably worth transfer your ln balance to a fresh wallet and delete the old one

I did this and I still get the error.

**Comment by Overtorment** [comment]
we had some fixes in latest release, did it help?

**Comment by blankscreengithub** [comment]
> we had some fixes in latest release, did it help?

I'm on version 6.2.1 and I haven't seen the error.

**Comment by Overtorment** [comment]
@limpbrains so the source of that was that @marcosrdz refactored wallets carousel, and it started firing too much onSnap events, each event triggering wallet fetch & saveToDisk, that's why they piled up.
it was fixed and released.
