### ISSUE TITLE
Debug app cannot be installed in sdk version less than 28

### ISSUE THREAD

**Issue by Sayan-dev** [BlueWallet/BlueWallet#3388]
## Are you reporting a bug?
Yes

Please provide:

* your phone model `Redmi 5 - 8.1.0` and OS version `Android sdk version 27`
* BlueWallet app version (settings->about->scroll down) `6.2.0`
* self-test passes? Open settings->about->scroll down, tap "Run self-test" `-`
* unique ID for our crash reporting service (settings->about->scroll down, tap "copy") `-`

## Proposing a feature?

Go right ahead

**Comment by marcosrdz** [comment]
This is due to the introduced Tor feature. This dependency requires said Android API level.

**Comment by marcosrdz** [comment]
Latest build.gradle was lowered to minSdk 26.
