### ISSUE TITLE
Regarding dropping support for Android 8 and lower devices

### ISSUE THREAD

**Issue by javad94** [BlueWallet/BlueWallet#3389]
## Are you reporting a bug?

Please provide:

* your phone model and OS version
* BlueWallet app version (settings->about->scroll down)
* self-test passes? Open settings->about->scroll down, tap "Run self-test"
* unique ID for our crash reporting service (settings->about->scroll down, tap "copy")

## Proposing a feature?

As per discussion in [Twitter](https://twitter.com/bluewalletio/status/1414566011601399809), Bluewallet dropped support for android 8 and below devices because of new google play store rules. But as you can see in the [Google announcement](https://developer.android.com/distribute/best-practices/develop/target-sdk#:~:text=Starting%20in%20November%202021%2C%20app%20updates%20will%20be%20required%20to%20target%20API%20level%2030%20or%20above%20and%20adjust%20for%20behavioral%20changes%20in%20Android%2011), their decision only affects the **targetSdkVersion**, not the **minSdkVersion**. So why Bluewallet dropped support for devices with android 8 and lower?

**Comment by Overtorment** [comment]
@marcosrdz is that what we fixed in https://github.com/BlueWallet/BlueWallet/pull/3391 ?

**Comment by marcosrdz** [comment]
The referenced PR lowers it so Android 8 can run the latest code.

**Comment by Overtorment** [comment]
@marcosrdz so this ticket can be closed?

**Comment by marcosrdz** [comment]
Not yet. This PR allows users with older devices to get a Tor-less but working APK https://github.com/BlueWallet/BlueWallet/pull/3387 . In addition, I opened #3393 to eliminate the need to keep a separate branch in sync. So in a way, once #3393  is closed then this one should too

**Comment by javad94** [comment]
> The referenced PR lowers it so Android 8 can run the latest code.

Thank you very much. 
Can minSdkVersion be lowered to **26** like previous versions? Because in many developing countries like Iran, android 6 and 7 still has a relatively large market share ([source for Iran](https://insight.cafebazaar.ir/report/api-versions-users)) and with this new change, they will be deprived of trusted wallets like Bluewallet.

**Comment by marcosrdz** [comment]
> > The referenced PR lowers it so Android 8 can run the latest code.
> 
> 
> 
> Thank you very much. 
> 
> Can minSdkVersion be lowered to **26** like previous versions? Because in many developing countries like Iran, android 6 and 7 still has a relatively large market share ([source for Iran](https://insight.cafebazaar.ir/report/api-versions-users)) and with this new change, they will be deprived of trusted wallets like Bluewallet.

I referenced a PR on my previous comment that contains an APK that has the latest BlueWallet (without Tor) that runs on Android 5 or newer.

**Comment by javad94** [comment]
> > > The referenced PR lowers it so Android 8 can run the latest code.
> > 
> > 
> > Thank you very much.
> > Can minSdkVersion be lowered to **26** like previous versions? Because in many developing countries like Iran, android 6 and 7 still has a relatively large market share ([source for Iran](https://insight.cafebazaar.ir/report/api-versions-users)) and with this new change, they will be deprived of trusted wallets like Bluewallet.
> 
> I referenced a PR on my previous comment that contains an APK that has the latest BlueWallet (without Tor) that runs on Android 5 or newer.

That's great. Will the version be available on the play store in the future?

**Comment by javad94** [comment]
Hi. why I can't install _BlueWallet-6.2.2-API24-27.apk_ on my android 6 device? also the new update of Bluewallet is not available for this device on the play store.

**Comment by marcosrdz** [comment]
This APK is for Android API 24 and up to 27. Android 6 is API 23. BlueWallet 6.0.8 is available for API 23

**Comment by javad94** [comment]
> This APK is for Android API 24 and up to 27. Android 6 is API 23. BlueWallet 6.0.8 is available for API 23

oh. got it. Thank you.
