### ISSUE TITLE
Auto lock or kill

### ISSUE THREAD

**Issue by Sh0ham** [BlueWallet/BlueWallet#3401]
Password isn't required after phone went sleep or by leaving the app in the background, even after hours.
It might be a good call to make the app require it after serval minutes or something

**Comment by KHP86** [comment]
I noticed this also. This feature would be a great for wallet security. The app can give dropdown options for Auto Lock: "disabled", "5 minutes", "10 minutes", "30 minutes", "1 hour" and so on if more timeout options are desired.

**Comment by Overtorment** [comment]
the app always requests biometrics (if enabled) before _any_ sensitive operation, like doing a transaction or exporting wallet's backup.
so to my opinion, that's good enough.

and if your phone is unlocked and in hands of an enemy - that's entirely your fault.
