### ISSUE TITLE
Regtest build

### ISSUE THREAD

**Issue by Kixunil** [BlueWallet/BlueWallet#3416]
I'd like to test Blue Wallet with [loptos - experimental PayJoin server capable of opening LN channels](github.com/Kixunil/loptos), however I'm neither confident in risking real funds nor have the desire to wait for transactions to confirm just for testing. Regtest is the best testing tool Bitcoin has and it'd greatly help here.

I didn't find regtest builds nor instructions how to build it myself. Is there a way to do it? If not, could it be added? I believe it'd massively help with testing BW and other software leading to much higher quality.

**Comment by Overtorment** [comment]
bluewallet doesnt support testner or regtest.
if you can make regtest work with regular btc addresses (not testnet addresses), you can probably setup electrum server with regtest and and configure bluewallet to use this electrum.
(not sure if its even possibe)

**Comment by Kixunil** [comment]
> bluewallet doesnt support testner or regtest.

Bummer, in my experience regtest is of **massive** help.

> if you can make regtest work with regular btc addresses (not testnet addresses), you can probably setup electrum server with regtest and and configure bluewallet to use this electrum.

I guess convert the mainnet address given out by BW, then sending regtest coins to it, then convert regtest address from BIP21 to mainnet and feed that to BW? That seems possible since the Electrum protocol uses scripts instead of addresses. Although it's messy, how hard would it be to add a build flag to make a separate regtest build which just switches address types?

**Comment by Overtorment** [comment]
for a single wallet type, probably messing with `AbstractHDElectrumWallet._nodeToBech32SegwitAddress()` in `class/wallets/abstract-hd-electrum-wallet.js` would be enough.

but we dont have any build flags, so you'd have to monkey-patch and build it
