### ISSUE TITLE
iOS java save to disk exception

### ISSUE THREAD

**Issue by ostermayer** [BlueWallet/BlueWallet#3439]
the following error occurs on launch of the app and during transaction send or lighting wallet use.  reinstall, restore, and re-imports have failed to fix issue 
![89FD33CF-DF63-4673-8E35-4167FE0E7BEF](https://user-images.githubusercontent.com/4887941/126858922-87fd328c-1ee6-4821-9bec-717cc5c3f278.jpeg)

**Comment by Overtorment** [comment]
caused by: https://github.com/BlueWallet/BlueWallet/issues/3357
to be fixed
