### ISSUE TITLE
Export wallet transactions in CSV

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#3441]
apparently, some users want it for tax/accounting..?

**Comment by yiet89** [comment]
Any updates?

**Comment by oliverlj** [comment]
We need it for our tax project. https://gitlab.com/c1560/cryptofiscafacile/-/issues/277 I will try to submit a pr this month

**Comment by mattmcgiv** [comment]
Hello, it looks like this was completed in #5045

**Comment by oliverlj** [comment]
it is not solved for lightning wallet. I do not have any buttons

**Comment by Overtorment** [comment]
good point. ln wallets were overlooked

**Comment by marcosrdz** [comment]
True...ill add that

**Comment by masikotimo** [comment]
Hello @Overtorment  Is this issue still pending I would like to give it a go

**Comment by masikotimo** [comment]
> True...ill add that

Hey @marcosrdz , is this  issue still pending I would like to give it a go

**Comment by marcosrdz** [comment]
> > True...ill add that
> 
> 
> 
> Hey @marcosrdz , is this  issue still pending I would like to give it a go

Go for it

**Comment by masikotimo** [comment]
> > > True...ill add that
> > 
> > 
> > Hey @marcosrdz , is this  issue still pending I would like to give it a go
> 
> Go for it

Hello @marcosrdz  could you please review this 

https://github.com/BlueWallet/BlueWallet/pull/5400
