### ISSUE TITLE
6.1.9 Errors on startup - MacOS 10.15.7

### ISSUE THREAD

**Issue by AlexMinty** [BlueWallet/BlueWallet#3450]
Reverting to 6.1.8 works fine

**Comment by AlexMinty** [comment]
Process:               BlueWallet [8316]
Path:                  /Applications/BlueWallet 2.app/Contents/MacOS/BlueWallet
Identifier:            io.bluewallet.bluewallet
Version:               6.1.9 (602)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           BlueWallet [8316]
User ID:               501

Date/Time:             2021-07-26 10:43:48.578 +0200
OS Version:            Mac OS X 10.15.7 (19H1323)
Report Version:        12
Bridge OS Version:     5.5 (18P4759a)
Anonymous UUID:        F7454319-55FB-1F6A-C075-DC082AD8281B


Time Awake Since Boot: 350000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /System/iOSSupport/System/Library/Frameworks/AssetsLibrary.framework/Versions/A/AssetsLibrary
  Referenced from: /Applications/BlueWallet 2.app/Contents/MacOS/BlueWallet
  Reason: image not found

Binary Images:
       0x1043b1000 -        0x104d94fcf +io.bluewallet.bluewallet (6.1.9 - 602) <706A2F10-E9E7-35A1-B665-415B37FF1F90> /Applications/BlueWallet 2.app/Contents/MacOS/BlueWallet
       0x104fb6000 -        0x105199ff7 +com.github.krzyzanowskim.OpenSSL (1.1.180 - 1) <4252BAA9-3905-377D-8149-67F6C4BB4E26> /Applications/BlueWallet 2.app/Contents/Frameworks/OpenSSL.framework/Versions/A/OpenSSL
       0x10f298000 -        0x10f32a267  dyld (750.7) <FCEF919F-F7F8-3C1A-B208-7ECDCB5EA674> /usr/lib/dyld
    0x7fff2925b000 -     0x7fff29456ff8  com.apple.avfoundation (2.0 - 1855.3) <0837D912-3783-35D6-A94A-E474E18600CF> /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
    0x7fff29643000 -     0x7fff29643fff  com.apple.Accelerate (1.11 - Accelerate 1.11) <4F9977AE-DBDB-3A16-A536-AC1F9938DCDD> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fff2bdb1000 -     0x7fff2be92ff2  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <A13B1F42-F90D-3B4C-9C43-1B64F7B24161> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff2c22b000 -     0x7fff2c5b9ffa  com.apple.CFNetwork (1128.1 - 1128.1) <04F37E21-8AC6-35BF-8D2C-8ED954B09026> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff2d9bb000 -     0x7fff2de3bff2  com.apple.CoreFoundation (6.9 - 1677.207) <ACA14447-39AE-31E6-A58B-48383123B1E7> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff2de3d000 -     0x7fff2e4b2fe8  com.apple.CoreGraphics (2.0 - 1355.24) <D4921BEE-0AD8-333E-9D64-BC85095368F1> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff2e4c0000 -     0x7fff2e81bff0  com.apple.CoreImage (15.0.0 - 940.9) <69361069-01AB-342E-862B-73A74271A765> /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage
    0x7fff2e81c000 -     0x7fff2e885ff0  com.apple.corelocation (2394.0.22 - 2394.0.22) <75966124-2FB7-33C3-BE49-3DD5F327F911> /System/Library/Frameworks/CoreLocation.framework/Versions/A/CoreLocation
    0x7fff2ebdc000 -     0x7fff2ecb7ffc  com.apple.CoreMedia (1.0 - 2625.9) <A3FF3AFC-8C1C-36E5-9179-66D8F075EE35> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
    0x7fff2ed1b000 -     0x7fff2eda3ff3  com.apple.coremotion (2394.0.22 - 2394.0.22) <EACCA10E-4A14-3143-AE98-B826E97B7431> /System/Library/Frameworks/CoreMotion.framework/Versions/A/CoreMotion
    0x7fff2eda4000 -     0x7fff2eda4fff  com.apple.CoreServices (1069.27 - 1069.27) <C00E80D2-3787-3862-A3E6-58F1C2890D7F> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff2f817000 -     0x7fff2f9ceffc  com.apple.CoreText (643.1.5.7 - 643.1.5.7) <34D12C1B-541D-3796-BDD8-D40EE509CD5F> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
    0x7fff2f9cf000 -     0x7fff2fa13ffb  com.apple.CoreVideo (1.8 - 344.3) <5314E70D-325F-3E98-99FC-00FDF520747E> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff2fc5a000 -     0x7fff2fc5cff3  com.apple.DeviceCheck (1.0 - 1) <887E7380-5BCC-3C28-8925-0135A6D5751B> /System/Library/Frameworks/DeviceCheck.framework/Versions/A/DeviceCheck
    0x7fff30079000 -     0x7fff3043eff7  com.apple.Foundation (6.9 - 1677.207) <B79613A3-18A8-3C53-869D-46DD355636BA> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff308e8000 -     0x7fff30a46ff6  com.apple.ImageIO.framework (3.3.0 - 1976.11.8) <6197DB17-688F-3BC3-BBD3-8C3D633AA00C> /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
    0x7fff324eb000 -     0x7fff32501ff2  com.apple.LocalAuthentication (1.0 - 693.140.3) <5D391FD1-391B-390A-BBC1-62A537C8DAFE> /System/Library/Frameworks/LocalAuthentication.framework/Versions/A/LocalAuthentication
    0x7fff3892b000 -     0x7fff38b79ff7  com.apple.Photos (1.0 - 161.0.120) <BFE43748-5620-3302-96B2-361A9473C8E4> /System/Library/Frameworks/Photos.framework/Versions/A/Photos
    0x7fff3952b000 -     0x7fff397aeffb  com.apple.QuartzCore (1.11 - 841.6) <0E585F1D-CFD2-3262-9ED8-3DA1C78344FC> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff3a331000 -     0x7fff3a67cff1  com.apple.security (7.0 - 59306.140.9) <5E1E1C8B-EDCB-3A25-836A-A835D57D4E3C> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff3b627000 -     0x7fff3b65cff2  com.apple.UserNotifications (1.0 - ???) <8DB163D1-66F0-3B52-933F-48F945E3FF4D> /System/Library/Frameworks/UserNotifications.framework/Versions/A/UserNotifications
    0x7fff64ae4000 -     0x7fff64ae5fff  libSystem.B.dylib (1281.100.1) <A8845AB6-40B5-357A-AF66-AEC21E112D65> /usr/lib/libSystem.B.dylib
    0x7fff64dca000 -     0x7fff64e1cfff  libc++.1.dylib (902.1) <59A8239F-C28A-3B59-B8FA-11340DC85EDC> /usr/lib/libc++.1.dylib
    0x7fff66944000 -     0x7fff66977fde  libobjc.A.dylib (787.1) <6DF81160-5E7F-3E31-AA1E-C875E3B98AF6> /usr/lib/libobjc.A.dylib
    0x7fff66abf000 -     0x7fff66ca9ff7  libsqlite3.dylib (308.6) <33057143-AB4E-348B-9650-98BC48866F34> /usr/lib/libsqlite3.dylib
    0x7fff67020000 -     0x7fff67032ff3  libz.1.dylib (76) <793D9643-CD83-3AAC-8B96-88D548FAB620> /usr/lib/libz.1.dylib
    0x7fff68431000 -     0x7fff694c7e1b  com.apple.JavaScriptCore (15609 - 15609.4.1) <095F7CC4-60D0-3D3F-9656-0A26A92FD38E> /System/iOSSupport/System/Library/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore
    0x7fff69aa1000 -     0x7fff69aa1ff7  com.apple.MobileCoreServices (1069.27 - 1069.27) <C9AC75DD-BCF9-3FC7-B27E-C006A8E2E1C4> /System/iOSSupport/System/Library/Frameworks/MobileCoreServices.framework/Versions/A/MobileCoreServices
    0x7fff6adc7000 -     0x7fff6adc7fff  com.apple.UIKit (1.0 - 61000) <01D18FD1-7E41-3BD8-93D0-AF77ECC49035> /System/iOSSupport/System/Library/Frameworks/UIKit.framework/Versions/A/UIKit

Model: MacBookPro15,2, BootROM 1554.140.20.0.0 (iBridge: 18.16.14759.0.1,0), 4 processors, Quad-Core Intel Core i7, 2.7 GHz, 16 GB, SMC 
Graphics: kHW_IntelIrisGraphics655Item, Intel Iris Plus Graphics 655, spdisplays_builtin
Memory Module: BANK 0/ChannelA-DIMM0, 8 GB, LPDDR3, 2133 MHz, Micron, -
Memory Module: BANK 2/ChannelB-DIMM0, 8 GB, LPDDR3, 2133 MHz, Micron, -
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x7BF), wl0: Oct 28 2020 13:06:41 version 9.30.357.42.32.5.48 FWID 01-4f9e2d7c
Bluetooth: Version 7.0.6f8, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: Extreme SSD
USB Device: USB 3.1 Bus
USB Device: Apple T2 Bus
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 47.4
Thunderbolt Bus: MacBook Pro, Apple Inc., 47.4

**Comment by marcosrdz** [comment]
6.2.1 will be released later this week with this crash fixed.

**Comment by NickKaramoff** [comment]
Version 6.2.3 still has this bug...

macOS Version: 10.15.7 (19H1323)

```
Process:               BlueWallet [8244]
Path:                  /Applications/BlueWallet.app/Contents/MacOS/BlueWallet
Identifier:            io.bluewallet.bluewallet
Version:               6.2.3 (612)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           BlueWallet [8244]
User ID:               501

Date/Time:             2021-08-25 00:14:39.608 +0200
OS Version:            Mac OS X 10.15.7 (19H1323)
Report Version:        12
Bridge OS Version:     3.0 (14Y908)
Anonymous UUID:        7217825E-4BA0-D57C-EEF3-77EDCC56188C

Sleep/Wake UUID:       C027FBD4-CA14-4C61-A427-B62E5DEAFBF3

Time Awake Since Boot: 120000 seconds
Time Since Wake:       560 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /System/iOSSupport/System/Library/Frameworks/AssetsLibrary.framework/Versions/A/AssetsLibrary
  Referenced from: /Applications/BlueWallet.app/Contents/MacOS/BlueWallet
  Reason: image not found

Binary Images:
       0x10baf7000 -        0x10c4eefcf +io.bluewallet.bluewallet (6.2.3 - 612) <E0AFBB83-A1C6-39BD-9ACF-02E3A3193346> /Applications/BlueWallet.app/Contents/MacOS/BlueWallet
       0x10c718000 -        0x10c8fbff7 +com.github.krzyzanowskim.OpenSSL (1.1.180 - 1) <4252BAA9-3905-377D-8149-67F6C4BB4E26> /Applications/BlueWallet.app/Contents/Frameworks/OpenSSL.framework/Versions/A/OpenSSL
       0x113133000 -        0x1131c5267  dyld (750.7) <FCEF919F-F7F8-3C1A-B208-7ECDCB5EA674> /usr/lib/dyld
    0x7fff31fb6000 -     0x7fff321b1ff8  com.apple.avfoundation (2.0 - 1855.3) <0837D912-3783-35D6-A94A-E474E18600CF> /System/Library/Frameworks/AVFoundation.framework/Versions/A/AVFoundation
    0x7fff3239e000 -     0x7fff3239efff  com.apple.Accelerate (1.11 - Accelerate 1.11) <4F9977AE-DBDB-3A16-A536-AC1F9938DCDD> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fff34b0c000 -     0x7fff34bedff2  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <A13B1F42-F90D-3B4C-9C43-1B64F7B24161> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff34f86000 -     0x7fff35314ffa  com.apple.CFNetwork (1128.1 - 1128.1) <04F37E21-8AC6-35BF-8D2C-8ED954B09026> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff36716000 -     0x7fff36b96ff2  com.apple.CoreFoundation (6.9 - 1677.207) <ACA14447-39AE-31E6-A58B-48383123B1E7> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff36b98000 -     0x7fff3720dfe8  com.apple.CoreGraphics (2.0 - 1355.24) <D4921BEE-0AD8-333E-9D64-BC85095368F1> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff3721b000 -     0x7fff37576ff0  com.apple.CoreImage (15.0.0 - 940.9) <69361069-01AB-342E-862B-73A74271A765> /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage
    0x7fff37577000 -     0x7fff375e0ff0  com.apple.corelocation (2394.0.22 - 2394.0.22) <75966124-2FB7-33C3-BE49-3DD5F327F911> /System/Library/Frameworks/CoreLocation.framework/Versions/A/CoreLocation
    0x7fff37937000 -     0x7fff37a12ffc  com.apple.CoreMedia (1.0 - 2625.9) <A3FF3AFC-8C1C-36E5-9179-66D8F075EE35> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
    0x7fff37a76000 -     0x7fff37afeff3  com.apple.coremotion (2394.0.22 - 2394.0.22) <EACCA10E-4A14-3143-AE98-B826E97B7431> /System/Library/Frameworks/CoreMotion.framework/Versions/A/CoreMotion
    0x7fff37aff000 -     0x7fff37afffff  com.apple.CoreServices (1069.27 - 1069.27) <C00E80D2-3787-3862-A3E6-58F1C2890D7F> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff38572000 -     0x7fff38729ffc  com.apple.CoreText (643.1.5.7 - 643.1.5.7) <34D12C1B-541D-3796-BDD8-D40EE509CD5F> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
    0x7fff3872a000 -     0x7fff3876effb  com.apple.CoreVideo (1.8 - 344.3) <5314E70D-325F-3E98-99FC-00FDF520747E> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff389b5000 -     0x7fff389b7ff3  com.apple.DeviceCheck (1.0 - 1) <887E7380-5BCC-3C28-8925-0135A6D5751B> /System/Library/Frameworks/DeviceCheck.framework/Versions/A/DeviceCheck
    0x7fff38dd4000 -     0x7fff39199ff7  com.apple.Foundation (6.9 - 1677.207) <B79613A3-18A8-3C53-869D-46DD355636BA> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff39643000 -     0x7fff397a1ff6  com.apple.ImageIO.framework (3.3.0 - 1976.11.8) <6197DB17-688F-3BC3-BBD3-8C3D633AA00C> /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
    0x7fff3b246000 -     0x7fff3b25cff2  com.apple.LocalAuthentication (1.0 - 693.140.3) <5D391FD1-391B-390A-BBC1-62A537C8DAFE> /System/Library/Frameworks/LocalAuthentication.framework/Versions/A/LocalAuthentication
    0x7fff41686000 -     0x7fff418d4ff7  com.apple.Photos (1.0 - 161.0.120) <BFE43748-5620-3302-96B2-361A9473C8E4> /System/Library/Frameworks/Photos.framework/Versions/A/Photos
    0x7fff42286000 -     0x7fff42509ffb  com.apple.QuartzCore (1.11 - 841.6) <0E585F1D-CFD2-3262-9ED8-3DA1C78344FC> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff4308c000 -     0x7fff433d7ff1  com.apple.security (7.0 - 59306.140.9) <5E1E1C8B-EDCB-3A25-836A-A835D57D4E3C> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff44382000 -     0x7fff443b7ff2  com.apple.UserNotifications (1.0 - ???) <8DB163D1-66F0-3B52-933F-48F945E3FF4D> /System/Library/Frameworks/UserNotifications.framework/Versions/A/UserNotifications
    0x7fff6d83f000 -     0x7fff6d840fff  libSystem.B.dylib (1281.100.1) <A8845AB6-40B5-357A-AF66-AEC21E112D65> /usr/lib/libSystem.B.dylib
    0x7fff6db25000 -     0x7fff6db77fff  libc++.1.dylib (902.1) <59A8239F-C28A-3B59-B8FA-11340DC85EDC> /usr/lib/libc++.1.dylib
    0x7fff6f69f000 -     0x7fff6f6d2fde  libobjc.A.dylib (787.1) <6DF81160-5E7F-3E31-AA1E-C875E3B98AF6> /usr/lib/libobjc.A.dylib
    0x7fff6f81a000 -     0x7fff6fa04ff7  libsqlite3.dylib (308.6) <33057143-AB4E-348B-9650-98BC48866F34> /usr/lib/libsqlite3.dylib
    0x7fff6fd7b000 -     0x7fff6fd8dff3  libz.1.dylib (76) <793D9643-CD83-3AAC-8B96-88D548FAB620> /usr/lib/libz.1.dylib
    0x7fff7118c000 -     0x7fff72222e1b  com.apple.JavaScriptCore (15609 - 15609.4.1) <095F7CC4-60D0-3D3F-9656-0A26A92FD38E> /System/iOSSupport/System/Library/Frameworks/JavaScriptCore.framework/Versions/A/JavaScriptCore
    0x7fff727fc000 -     0x7fff727fcff7  com.apple.MobileCoreServices (1069.27 - 1069.27) <C9AC75DD-BCF9-3FC7-B27E-C006A8E2E1C4> /System/iOSSupport/System/Library/Frameworks/MobileCoreServices.framework/Versions/A/MobileCoreServices
    0x7fff73b22000 -     0x7fff73b22fff  com.apple.UIKit (1.0 - 61000) <01D18FD1-7E41-3BD8-93D0-AF77ECC49035> /System/iOSSupport/System/Library/Frameworks/UIKit.framework/Versions/A/UIKit
```

**Comment by marcosrdz** [comment]
Please try 6.2.2 and let us know if it opens on 10.5.7

**Comment by NickKaramoff** [comment]
> Please try 6.2.2 and let us know if it opens on 10.5.7

Yes, 6.2.2 works 👍
