### ISSUE TITLE
OnePlus 6 device: Text in various places within the app is truncated/cut-off

### ISSUE THREAD

**Issue by brettl-03** [BlueWallet/BlueWallet#3466]
On my OnePlus 6 device, there are multiple areas of the app where words are truncated/cut-off at the end (seen in attached images). I'm only seeing this issue on my **OnePlus 6** device, as this issue isn't present on my newer OnePlus 9 or my Pixel 3a devices.

I double-checked and the OnePlus 6 display settings (display size & font size) are set to default, so that's ruled out as the cause.

* OnePlus 6 (Android 10)
* BlueWallet app version - 6.2.2
* Self-test passes 

![Screenshot_20210726-112356](https://user-images.githubusercontent.com/88056982/127410914-6484df13-f048-4e20-8603-48bcba071b90.jpg)
![PXL_20210728_232344659](https://user-images.githubusercontent.com/88056982/127410921-a4c4e409-0ece-421a-a1c2-6abb3bb84daf.jpg)
![PXL_20210728_231805988](https://user-images.githubusercontent.com/88056982/127410929-d69e44d3-204b-4cd6-82c2-b8e395d83af5.jpg)
![PXL_20210728_232037590](https://user-images.githubusercontent.com/88056982/127410934-a1472e50-ae2a-429b-a8d1-853b9f83fea8.jpg)

**Comment by marcosrdz** [comment]
OnePlus has a "font style" appearance customization option that is the root of this issue. I believe it offers two options.
