### ISSUE TITLE
Bug: App window cannot be moved (MacOS 11.4, Intel and Apple Silicon)

### ISSUE THREAD

**Issue by oetorrez** [BlueWallet/BlueWallet#3467]
OS: MacOS 11.4
Architecture(s): Intel and Apple Silicon M1
App version: 6.2.2 (610)
Self-test(s): OK
Bug description:
The app window cannot be easily moved once the app has loaded. During the app start-up/splash screen, the app window can be dragged around screen by the title bar and relocated as normal. Once the app has loaded past the splash screen, the window title bar (not including the close/minimize/maximize buttons) becomes totally unresponsive to click/drag actions on an M1 Macbook Pro. On an Intel Macbook Air (also running MacOS 11.4 and app 6.2.2), only a small portion of the title bar is active for click/drag actions.

**Comment by marcosrdz** [comment]
Reproduced. You can click and drag all the time if doin so from the wallets list on the left side of the screen. Will look into this.
