### ISSUE TITLE
API error: LND failure (code 7)

### ISSUE THREAD

**Issue by PeterKallos2017** [BlueWallet/BlueWallet#347]
I entered the LN address on my iPhone (version 3.7.2) and this address was seemingly validated because I could see the destination description right under the Scan field. When I clicked the Pay button I got this blocking message:

API error: LND failure (code 7)

**Comment by Overtorment** [comment]
Sometimes API hickups. It passes.

**Comment by PeterKallos2017** [comment]
It's quite a frustrating hiccup. It is still present when writing this response.

**Comment by Overtorment** [comment]
Oh okay, this is not API hickup, sorry.
This is a problem with a route/destination you're trying to pay.
Can you share the place you're paying? I'll look into establishing a better route to it.

**Comment by PeterKallos2017** [comment]
lnbc1pwxusz8pp5cmtwak04xy594datyqwzpenk8mztkl49fkgsutf4j92nm52sx9nqdzz235hqurfdcs9x6tddahyg6tcdah9gamfw36zq2r5d9c8q6tw9ekk22fgw5mnjv3c9ycqzysxqyz5vqwqsmkaw9dq089w3umes5gmz746d6qyz352hxtc3r6kawzyt2w9xhdsumja02zk533jkxjalx9j073x8wcl4us6jyv9m0edxk6rhm5tqqqx3p8t

**Comment by Overtorment** [comment]
Store name or node’s uri would help more

**Comment by PeterKallos2017** [comment]
Tippin SimonDixonTwitt (tippin.me)(u7928)

**Comment by Overtorment** [comment]
![Image](https://i.imgur.com/YlQYj2c.jpg)
