### ISSUE TITLE
Inaccurate error message when scanning QR code

### ISSUE THREAD

**Issue by thelwyn** [BlueWallet/BlueWallet#3472]
At the moment when scanning (or importing image with) a QR Code, if it doesn't work it displays this message whatever the issue: 
"The selected image doesn't contain a QR Code"

But I'm clearly scanning a QR Code. It confused me and at first I thought maybe the code was blurry of something, but it's not this. It seems to me it happens if it's a code for an expired or already paid invoice?

Maybe this error message should be rephrased and/or a distinction made between "QR Code not found" and "QR Code invalid" ?

**Comment by marcosrdz** [comment]
May you be able to share a screenshot of the QR Code? You can send it to m@bluewallet.io

**Comment by thelwyn** [comment]
![425214988426335947](https://user-images.githubusercontent.com/9986007/127791818-35663b6f-d72a-4c48-9160-d6eaa8c1d97e.jpg)

Here is one. But actually now I notice it only happens if I try to import it from gallery, not if I scan it directly with the camera. So maybe it's related to this bug: https://github.com/BlueWallet/BlueWallet/issues/3022 it looked like it was fixed so I initially thought It was another issue.

I'm using Android 8 and BW 6.2.2

**Comment by marcosrdz** [comment]
The provided image works when cropping it so it has less content. For example, no texts or share button.

**Comment by thelwyn** [comment]
You're right!
It's super important to make it work I think, because when you do everything from a phone you can't scan a QR code displayed on the phone itself obviously, so making a screenshot and then opening the captured image is probably a common scenario.

**Comment by marcosrdz** [comment]
For the mean time, the error message has been expanded to include more context. Cropping using builtin phone tools on Android and iOS should be enough for now

**Comment by marcosrdz** [comment]
You can tap and hold on a QR Code to save as image on the Bitcoin receive address screen. I will add the same to Lightning invoices.

**Comment by Overtorment** [comment]
its weird that our lib cannot read qr from file if its a part of a larger picture

**Comment by thelwyn** [comment]
Is that this lib: https://github.com/remobile/react-native-qrcode-local-image that looks inactive since 2017?

**Comment by Overtorment** [comment]
> Is that this lib: https://github.com/remobile/react-native-qrcode-local-image that looks inactive since 2017?

yeah, we need to find something better...

**Comment by marcosrdz** [comment]
@Overtorment  I just added code to it resizes the selected image. Now the screenshot in this ticket scans successfully.

**Comment by Overtorment** [comment]
noice!
