### ISSUE TITLE
Unable to Browse Past First Wallet (Among Other Issues)

### ISSUE THREAD

**Issue by mcsaeid** [BlueWallet/BlueWallet#3496]
**Redmi Note 9S, Android 11, BlueWallet 6.2.2**

I am not able to browse past the first wallet. Swiping right has no effect. The second wallet—partially visible on the left—will show if I tap on it. The issue was not persistent in that if you closed and re-opened BlueWallet, it would most likely be resolved. However, after updating to the latest version, 6.2.2 (July 27, 2021), the wallets seem to be stuck.

![Untitled-1](https://user-images.githubusercontent.com/63400670/128216274-0fea1256-d453-4d3a-878d-91d6d19684e7.png)

The problem seems to have been **resolved** after I switched the language to **Persian**.

The self-test never completed even after trying twice, the first time **waiting for five minutes**, the second time **waiting for ten minutes**. The same test on an iPhone device (iOS 14.6, BlueWallet 6.2.1) took exactly **thirty seconds**. It should be noted that even though this is a relatively new phone, opening the Bluewallet app takes twenty to sometimes thirty seconds, which is a lot for a capable, up-to-date Android phone. The reason I bring this up is that another user complained about the same issue on [my Twitter](https://twitter.com/ali29/status/1419677989596504066), despite his phone having a somewhat fast processor (Snapdragon 865) and 4 GB of RAM.

**Comment by marcosrdz** [comment]
RN Bug: When running the app for the first time, it wont change the layout to RTL. This is a known bug in React Native. The bug goes away after the first run
