### ISSUE TITLE
Find a way to move bip38 out of blue_modules to regulat deps 

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#3555]
AFAIR currenty its monkey-patched to use `scrypt` from `react-native-blue-crypto`.
patching in postnstall is an option, but I wonder if there's a better way

**Comment by limpbrains** [comment]
Besides using `react-native-blue-crypto` it is also validates passphrase

**Comment by Overtorment** [comment]
passphrase where?

**Comment by limpbrains** [comment]
> passphrase where?

https://github.com/BlueWallet/BlueWallet/blob/master/blue_modules/bip38/index.js#L216

**Comment by Overtorment** [comment]
oh right, forgot about this

**Comment by Overtorment** [comment]
hm, maybe we should just fork `bip38` into `rn-bip38`...

**Comment by limpbrains** [comment]
> hm, maybe we should just fork `bip38` into `rn-bip38`...

Agree, I will do it

**Comment by limpbrains** [comment]
Fixed in #3556
