### ISSUE TITLE
Mining fees to be calculated based on vByte instead of Bytes for SegWit transactions

### ISSUE THREAD

**Issue by KHP86** [BlueWallet/BlueWallet#3573]
## Do you need support? Just email bluewallet@bluewallet.io
No

## Are you reporting a bug?
No

Please provide:

* your phone model and OS version
iPad Pro (11-inch) -iPad OS 14.7.1
iPhone 12 Pro - iOS 14.7.1

* BlueWallet app version (settings->about->scroll down)
6.2.2 (build 1627389453)

* self-test passes? Open settings->about->scroll down, tap "Run self-test"
Passes Self Test

* unique ID for our crash reporting service (settings->about->scroll down, tap "copy")
iPad: 488B2435-8225-43CE-983C-D9F94334CB80
iPhone: E76E60C5-C5AC-44E2-BAE0-787C70ACC4D8

## Proposing a feature?
Yes

## Mining fees to be calculated based on vBytes instead of bytes for SegWit transactions. Doing so will pass possible mining fee savings to users.

#Note#
All transactions below have been constructed from the same wallet seed, same 4 inputs (UTXO) and same 1 output to help provide transaction size consistency. Wallet is HD SegWit (BIP84 Bech32 Native).

Reference document: https://en.bitcoin.it/wiki/Weight_units

Below is transaction constructed in BlueWallet after selecting "Slow" (1 sat/byte) or custom (1 sat/byte).

![IMG_0115](https://user-images.githubusercontent.com/12993061/128896859-5d92a65a-179b-4de7-b665-c7cb0ba7b621.jpeg)

Below is transaction constructed in BlueWallet, then imported into Sparrow wallet results in ~(2 sat/vByte) total fee.

![Screen Shot1](https://user-images.githubusercontent.com/12993061/128896598-ac59cc4e-0a1b-4b05-8da5-88600dcf40dc.jpeg)

Below is a transaction constructed in Sparrow Wallet selecting (1 sat/vByte) fee. This results in half the fee (for this particular case) BlueWallet offers the user.

![Screen Shot2](https://user-images.githubusercontent.com/12993061/128896643-dde9b01a-8a50-4d74-b978-28873783a40d.jpeg)

**Comment by Overtorment** [comment]
duplicate https://github.com/BlueWallet/BlueWallet/issues/2785
