### ISSUE TITLE
Android: 'Leave us a review' button becomes unresponsive 

### ISSUE THREAD

**Issue by brettl-03** [BlueWallet/BlueWallet#3577]
Android Only: 
Given I tap on the "Leave us a review" button for the first time (and the corresponding review modal pops up)
When the Play Store review modal is dismissed (i.e. tapping on "Not now")
Then the "Leave us a review" button becomes unresponsive
And attempting to tap on this button from here on produces no action

Notes: 
Even after force closing the app and re-opening, the "Leave us a review" button is still unresponsive. 
I tested this issue on an iPhone Xr and it appears okay for iOS, as this same issue was not present.

* OnePlus 6 (Android 10) & Google Pixel 3a (Android 11)
* BlueWallet app version - 6.2.2
* Self-test passes

https://user-images.githubusercontent.com/88056982/128949854-8545a961-fda0-4a7a-887b-fe9010e65982.mp4

**Comment by marcosrdz** [comment]
The account being used has previously left a review?

**Comment by marcosrdz** [comment]
https://issuetracker.google.com/issues/167352813?pli=1#comment15

Seems like its a known Google API issue in their new in-app review. The "fix" for now is to send the user to the Google Play Store app page. However, Im unable to find some public parameter that would auto scroll to the reviews section.

**Comment by Overtorment** [comment]
can we throw away `rate` package and use linking module to open the link?

**Comment by marcosrdz** [comment]
I wouldn't since it works for iOS and Android should be fixed once that ticket is resolved. Theres no direct "leave review" link that is user friendly that would be a good replacement.
