### ISSUE TITLE
New deeplinking scheme

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#359]
App must handle new deeplinking scheme.
Opening specific deeplink, BW must navigate to first LN wallet (or create one if it doesnt exist), open Lapp browser, and Lapp browser should navigate to the link provided in deeplink.
Here's an example for TrustWallet:

`trust://open?link_click_id=a-eyJldmVudCI6Im9wZW5VUkwiLCJ1cmwiOiJodHRwczovL2V0aDIuaW8vIy9yP3A9NDQ3NDY2ODY4NTI3JmM9NTVSWU9URGtrM2ltbHUwcTJoMkYmdz10cnVzdCJ9`

Thus, I propose: 
* scheme `bluewallet://`
* action `lappbrowser`
* get param `?url=` (urlencoded)

thus, complete link will look like that:

`bluewallet://lappbrowser?url=https://coolnewlapp.com/path`

If you have better ideas for naming things - share them.

**Comment by AliMeer** [comment]
Using Deeplinking scheme won’t allow for links to open in all via WhatApp or other chat apps in iOS. Universal linking is required in order for this to work in chat apps.

**Comment by Overtorment** [comment]
Old schemes will be still supported (like `lightning:`) but this new scheme is designed for a specific planned feature

**Comment by Overtorment** [comment]
merged with some changes https://github.com/BlueWallet/BlueWallet/pull/455
