### ISSUE TITLE
LNURL Pay doesn't support comments

### ISSUE THREAD

**Issue by rkfg** [BlueWallet/BlueWallet#3617]
* Moto G7 Power, Android 10
* BlueWallet app version 6.2.2
* self-test passes? Open settings->about->scroll down, tap "Run self-test" ☑

## Proposing a feature?

Not sure if it's a feature request or a bug but it's not possible to enter a comment during the LNURL Pay flow. Try it on https://chat.blixtwallet.com/, since there's no comment field the server doesn't accept the payment request (this comment is the whole purpose of this site).

**Comment by Fittiboy** [comment]
There are quite a few use cases for lnurl-pay that benefit greatly from comments, for example lightning tip jars.
Supporting comments is fairly simple: https://github.com/fiatjaf/lnurl-rfc/blob/luds/12.md#wallet-side
