### ISSUE TITLE
How to transfer my LN balance to BTC wallet ? 

### ISSUE THREAD

**Issue by kasadawa** [BlueWallet/BlueWallet#366]
How to transfer my LN balance to BTC wallet ? 

Usually you have to have this kind of option. 
I am not seeing any option to send my SAT to BTC address. I have an LND node, but it gives me and error code 7 when I try to pay some invoice, I suppose it's because there is no open channel, but I am also not seeing any option to open channel to another node .

Your 'funny' way of withdrawing the money with ZigZag is also not working, because ZigZag is not working ...  
Also your "SEND" option is not working on IOS devices. (You are not able to write any amount )

So what are the alternatives to withdraw my SAT ?

**Comment by ncoelho** [comment]
Hi there,

To withdraw, if zigzag.io is not working just use any exchange that accepts lightning.
Error code 7, means that no route was found. Usually means no inbound capacity on the node. To open a channel with bluewallet, go to receive > create invoice > additional info (or lndhub.io)

To "send" you need to scan an invoice first or have an invoice address...

**Comment by kasadawa** [comment]
Thanks for the Error code explanation. 

But I need to open a channel from bluewallet, because otherwise if I am opening a channel from my node to bluewallet it wont be possible to transfer the funds located in bluewallet.

I cant understand why you don't have feature just to get my local balance.

Also I am not aware of any reliable lightning exchange. Your  lndhub node need to have a route to this exchange. 

For the "send" you are right , sorry, my bad  . 


Does bluewallet generates node for me, or every bluewallet customer is representation of lndhub node ?

**Comment by freaksh0** [comment]
Ahem, shouldn't this settle automatically when you close a channel ? 
Seems strange that this is not a feature in the wallet to settle on chain...

**Comment by kasadawa** [comment]
Yes , when you close a channel you will receive your local balance funds , but thats not the point.

I am also using eclair and there the things are clear - you dont have your own node, but you can open a channel to someone. You cant receive funds. But whem it comes to converting the sat to btc it is doing it instantly, because that the normal way of doing it ... 
When you create a ln wallet, a node shoud be created for you, but as far as I see bluewallet is simulating this step and its providing a channels from the master node lndhub. 
The point is that if you have either simulation or real node you have to convert your sat to btc instantly , but bluewalleth is going smart and it’s blocking this normal behaviour , because it wants from you either to spend your funds or to send them to some ‘exchange’ .
