### ISSUE TITLE
API error: LND failue (code 7) - make errors more contextual 

### ISSUE THREAD

**Issue by pavlenex** [BlueWallet/BlueWallet#367]
Please make your errors more contextual. I have large number of customers and also users in BTCPay support not having any clue what the error means. Explain them that it means there's no direct route or whatever. Thanks.

**Comment by nodecheck** [comment]
I am experiencing this.  I want to use BlueWallet to connect to my btcpay store, and find that I get:

```
API error: LND failue (code 7)
```
it seems that you are unable to open a channel to me, despite my lnd node being accessible and working fine on mainnet.

**Comment by Amacruz** [comment]
I'm having a similar issue. When I try to refill the lightning wallet with BTC I get "API failure: Error undefined".
