### ISSUE TITLE
HD wallet as the main wallet change

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#368]
Here's the proposal to make HD wallets as the main wallet and the UX changes needed.

- [ ] HD wallet takes over with the main blue color
- [ ] Single address wallets take the purple color
- [ ] Two main options present on the create wallet view (Segwit HD/Lightning)
- [ ] Advanced settings to choose more options related to wallets on the create wallet view
- [ ] No changes on the settings page. Advanced options remain contextual for now to avoid having to explain what the advanced options are

**UI changes - [Zeplin Assets link](https://app.zeplin.io/project/5b252c1057a0c54542fe1f02/dashboard?seid=5bdbcfbbd146820d4892181e)**

<img width="100%" alt="screenshot 2019-02-28 at 17 21 59" src="https://user-images.githubusercontent.com/1238429/53581185-64d2d400-3b7d-11e9-8a44-02e46e8dd1e3.png">

**Comment by marcosrdz** [comment]
3d764e48ae13090a27f802fe85d9e877e1c6d8db
