### ISSUE TITLE
3.8.2 RC Q&A

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#370]
😠Nice to have
😡Important
👿Blocking the release

### build 3.8.2 (1551396366)

**Android**
😠Status bar, gets lost between colors and screens
😠Marketplace button paddings not aligned
😡Google suggestions still present on keyboard
👿Sending a transaction is not possible to tap "create" button
👿Not possible to import Lightning wallet. App crashes
👿Possible to import segwit single address. App crashes
👿Create new HD wallet. Tap on receive, generates address/QR. Tap a second time App crashes
👿Tap on receive, generates address/QR. Close the view, app crashes

**iOS**
😡TX main list not updating automatically
😡Broadcasting the tx on electrum generated 3 tx that disappeared after refresh [link](https://user-images.githubusercontent.com/1238429/53636851-debc9900-3c21-11e9-8183-9921e4a17a8a.PNG)
😡Broadcasting the tx on electrum generated 2 tx on the next time the app was opened [link](https://user-images.githubusercontent.com/1238429/53637178-c4cf8600-3c22-11e9-9c39-fc772d8ccd3a.PNG)

@marcosrdz @Overtorment

**Comment by marcosrdz** [comment]
😡Google suggestions still present on keyboard < It will be present, except during import.

**Comment by marcosrdz** [comment]
👿Sending a transaction is not possible to tap "create" button
👿Not possible to import Lightning wallet. App crashes
👿Possible to import segwit single address. App crashes
👿Create new HD wallet. Tap on receive, generates address/QR. Tap a second time App crashes
👿Tap on receive, generates address/QR. Close the view, app crashes

All fixed

**Comment by marcosrdz** [comment]
😠Status bar, gets lost between colors and screens
Fixed

**Comment by marcosrdz** [comment]
😠Marketplace button paddings not aligned
Fixed

**Comment by ncoelho** [comment]
Tested on 3.8.3 (1551752957)

all good to go! @marcosrdz @Overtorment
