### ISSUE TITLE
Invalid LNDHub URI while trying to connect to reverse proxied LNDHub using a self signed certificate

### ISSUE THREAD

**Issue by ulzeraj** [BlueWallet/BlueWallet#3752]
Hi.

I'm trying to connect to an LNDHub instance that is being reverse proxied by an Nginx server serving HTTPS connections though a self signed certificate.

Problem happens in:
iOS 14.7.1 Blue Wallet 6.2.4
iPadOS 14.7.1 Blue Wallet 6.2.4

Problem does not happen in:
MacOS 11.5.2 Blue Wallet 6.2.4

All mentioned devices can open the status page from Safari without certificate warnings. CA is installed on all devices.

MacOS works fine however an "invalid lndhub uri" alert will be thrown from the iOS and iPadOS configuration page.

There are no logs coming from LNDHub side but enabling debug on Nginx will result in the following message:

`6391#259682: *5 peer closed connection in SSL handshake while SSL handshaking, client: 10.10.10.104, server: 0.0.0.0:443`

TLS config is as follows:
```
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers on;
```

Changing to unencrypted HTTP allows the iOS clients to connect to the hub. 

Thanks in advance.

EDIT: I should mention the same certificate is working on the iOS devices on Electrum configuratio. For this particular connection Nginx is doing a TCP proxy with added TLS.

**Comment by Overtorment** [comment]
i dont think there is anything we can do about it. the way our framework (react native) handles HTTP requests is out of our control, so if adding CA on the device didn't help - chances are nothing will.
electrum connection works differently though, its a separate tcp/ip package that has explicit setting to disable certificate check.

i recommend getting free certificate via certbot
