### ISSUE TITLE
 Issue funding Umbrel / Lightening node / BlueWallet 

### ISSUE THREAD

**Issue by Beach1801** [BlueWallet/BlueWallet#3755]
Trying to fund a Umbrel Lightening node / wallet. 

Steps taken:
1. Install Umbrel on a RaPi server (has been running fully synced for over 3 months).
2. Installed BlueWallet on Umbrel & IOS Apple phone
3. Pointed BW LN to my Umbrel Lightening Node using QC code provided by Umbrel server.
(BWallet on my IOS device acknowledges that it’s connected (using Tor).
4. Funded wallet using public address provided by BW on IOS phone
(Trans ID: 1c3e4bd0a2d645cf0c2d28fa38bbbc14b160f276bd7f922805f46ef44c076f1d)

**I get a popup notification on my phone that says “10000 Sats received”** 
(and that’s exactly what I sent).

I log into my BlueWallet and do not see any funds, says it’s empty…
Checking the BW on my Umbrel server - also is empty… no funds….

I did a pull to refresh in W… phone seems to pause to refresh… still no balance…

This is my first attempt at this so I'm probably missing something obvious.... checked discussions everywhere I could to resolve.

**Comment by Beach1801** [comment]
OK, I noticed a step that I missed.... configuring the Electrum server on my IOS device. Added this using the QC Code provided by the Umbrel server... now shows green (also connected via TOR).
Still no sats appearing.
Since I configured the Electrum server on my IOS device AFTER sending the sats to the LWallet does this mean the transaction is lost?
Still can't understand why I'd get the notification popups about the deposit and yet the LW shows 0 sats...

**Comment by Overtorment** [comment]
can you check LND and make sure coins landed on your lnd?
you would need to look up lnd's onchain transactions

**Comment by Beach1801** [comment]
I would assume that you would do this via Thunderhub or just the home page Lightening interface... This is a little new to me but looking at the Umbrel server that hosts my LND it does not show any incoming transactions on either my BlueWallet or the Thunderhub Lightening Node Manager .. the balance is 0 sats, no transactions, nothing pending... all 0 or null..

**Comment by Overtorment** [comment]
i would take it to umbrel support, as Im not familiar with it or how it works exactly
