### ISSUE TITLE
Buttons `Clear Paste Done` missing on iPad in Portrait Mode

### ISSUE THREAD

**Issue by sebastian13** [BlueWallet/BlueWallet#3761]
## Reporting a bug:

The buttons `Clear Paste Done` on the Wallet Import Screen are missing in Portrait Orientation running on:

* iPad Air (4th Gen), iPad OS 14.7.1
* BlueWallet 4.2.4 (build: 1630444758)
* Self-Test passes, yes.

Also, the iOS / iPadOS usual _single tap_ to paste copied text isn't working. Probably that's intended?!

### Portrait Mode:
![IMG_0094](https://user-images.githubusercontent.com/10852783/132351639-2003f46f-8a01-4453-9a0d-85521508077e.PNG)

### Landscape Mode:
![IMG_0096](https://user-images.githubusercontent.com/10852783/132351654-7fd5b956-7521-482f-a789-4074ccacc770.PNG)

**Comment by marcosrdz** [comment]
Hello! Would you be able to provide a screen recording of this issue ? I was unable to replicate. 
In addition, do you have any accessibility feature enabled?
Thanks!

**Comment by sebastian13** [comment]
> Hello! Would you be able to provide a screen recording of this issue ? I was unable to replicate.
> In addition, do you have any accessibility feature enabled?
> Thanks!

Of course! I also tried to show you, how I cannot paste using build in iOS copy-paste-function.
No, I don't have any accessibility features enabled.

https://user-images.githubusercontent.com/10852783/132468321-a8e83e8d-6bab-41a5-a802-09c76a9dac7f.mp4

**Comment by marcosrdz** [comment]
Thank you for the video. I'll continue attempting to replicate.

Yes any context related functions on the import screen are disabled to avoid sensitive information from being copied to a clipboard. 

Are the paste, clear, and done buttons fully functional when visible?

**Comment by sebastian13** [comment]
I see. Yes, all 3 buttons are fully functional in landscape mode.
