### ISSUE TITLE
Thank you!  Interestingly electrum accepts his words as BIP39, and so does Bluewallet.  But it creates a new wallet with zero balance.  But the tool above linked, says the words are invalid. What is being checked differently I wonder?

### ISSUE THREAD

**Issue by Robloccs** [BlueWallet/BlueWallet#3798]
Thank you!  Interestingly electrum accepts his words as BIP39, and so does Bluewallet.  But it creates a new wallet with zero balance.  But the tool above linked, says the words are invalid. What is being checked differently I wonder?

_Originally posted by @maltokyo in https://github.com/BlueWallet/BlueWallet/issues/1259#issuecomment-645474645_

I'm having this exact same issue and I'm wondering if OP or anybody can tell me exactly the command typed into btcrecover that found the mistake? I'm 95% of the way there and if I I just knew whatever command OP typed to find the mistake I'm confident my issue would be resolved.

**Comment by Overtorment** [comment]
i suggest you ask at btcrecover repo https://github.com/3rdIteration/btcrecover/
