### ISSUE TITLE
BlueWallet is crashing when I create an onchain HD segwit wallet

### ISSUE THREAD

**Issue by Raddow** [BlueWallet/BlueWallet#3819]
Phone Model: J5 Prime. 

OS Version: Android 8

BlueWallet ver 6.2.5

userId:998e1b09d43b2664

**Comment by marcosrdz** [comment]
Are you running a custom Android flavor?

**Comment by Raddow** [comment]
Hi, sorry for delay. I am now able to create an wallet of this type. Thank you so much for this amazing software.
