### ISSUE TITLE
LNURL-withdraw QR codes multiply amount by 10 when wallet is displaying value not in sats

### ISSUE THREAD

**Issue by blackcoffeexbt** [BlueWallet/BlueWallet#3842]
## Are you reporting a bug?
Yes

Please provide:

* your phone model and OS version - Pixel 4, CalyxOS
* BlueWallet app version (settings->about->scroll down) 6.2.5
* self-test passes? Open settings->about->scroll down, tap "Run self-test" - Yes
* unique ID for our crash reporting service (settings->about->scroll down, tap "copy") - N/A

When attempting to use a LNURL withdrawal QR code from LNBits, if a wallet is displaying its balance in GBP, when creating the withdrawal QR code, the number of sats in the withdrawal is multiplied by 10. When the wallet is displaying its balance in sats, it works fine.

**Comment by marcosrdz** [comment]
Ok the issue is that the onTextChange only knows how to handle lnurl if its on sat mode. Ill expand it to handle other units

**Comment by letatcest** [comment]
Idem with LNURL from BTCPay server: amount in sats is given as amount in euro's (when BW is set to EUR instead of Sats)
