### ISSUE TITLE
Possible Bug: Case-Sensitive Passpharse Intrepreted Same as Non-Case-Sensitive

### ISSUE THREAD

**Issue by mcsaeid** [BlueWallet/BlueWallet#3848]
This was tested using a recent Appetize version from a [merged pull request](https://github.com/BlueWallet/BlueWallet/pull/3847).

Passphrases should be **case-sensitive**, meaning a wallet with the **same seed combination** but different passphrases—for example, one that features uppercase letters and another lowercase—should result in two completely different wallets. This, however, is _not_ the case with BlueWallet.

**What Was Tested**
Seed words: office leopard immense slender skull habit laundry egg broccoli income sadness bind
Passphrase #‌1: abc
Passphrase #‌2: ABC

The first wallet is imported using the passphrase with lowercase letters _abc_. When trying to import another wallet with the same seed words and uppercase passphrase _ABC_, the app refuses, stating that the wallet had already been imported. I am assuming it interprets the two passphrases as being the same.

![import](https://user-images.githubusercontent.com/63400670/133893598-7ace7c28-02d0-4ce0-8939-415de8dde35a.jpg)

This was [first mentioned](https://t.me/bluewallet/57852) in the BlueWallet Telegram group, but it did not get any replies. Feel free to test this and report your findings.

**Comment by ncoelho** [comment]
I think this happens because the import is only looking to the seed for
duplicates, not the passphrase. cc @limpbrains

**Comment by mcsaeid** [comment]
> I think this happens because the import is only looking to the seed for duplicates, not the passphrase. cc @limpbrains

Maybe. Either way, it is something that can be easily avoided.
