### ISSUE TITLE
Screenshot prevented in onchain receive

### ISSUE THREAD

**Issue by MaxHillebrand** [BlueWallet/BlueWallet#3852]
In the onchain Single sig wallet, the app prevents Screenshots from being taken.
This should be allowed here (it is in ln receive for example).

**Comment by Overtorment** [comment]
@marcosrdz

**Comment by MaxHillebrand** [comment]
Being this quick to squash user reported bugs?! :black_heart: 
Closed source has no chance - it's kinda unfair, really... :cry:

Thanks @marcosrdz!!

**Comment by marcosrdz** [comment]
> Being this quick to squash user reported bugs?! :black_heart: 
> 
> Closed source has no chance - it's kinda unfair, really... :cry:
> 
> 
> 
> Thanks @marcosrdz!!

No problem! This will make it into the next release. In the mean time, you can long press the QRCode to save it as an image on your device.
