### ISSUE TITLE
Add QR Density Configurability

### ISSUE THREAD

**Issue by SeedSigner** [BlueWallet/BlueWallet#3862]
Have heard several reports of users with lower-resolution phones being unable to scan PSBT QR codes displayed by BlueWallet because the individual QR frames are being rendered with too large of a payload. I'd like to propose some sort of configurability for the amount of data that's included in displayed QR frames so users with lower-resolution phones won't experience this kind of issue. We have accomplished this in SeedSigner with a basic low-medium-high user-configurable option in settings. Happy to provide more detail if something isn't clear about this request. Thank you for all of your work on BlueWallet -- Vaults is an immensely important piece of the puzzle for Bitcoin savers in developing economies.

**Comment by Overtorment** [comment]
we had this issue when by accident we left bluewallet logo in the center of QR frames for psbt.
in the latest release we removed them.

**Comment by bitcoinhelp** [comment]
I'd like to second this request.

Would be great to have an option to change the QR "density" for PSBTs to accommodate more devices. As @SeedSigner mentions, perhaps a low/medium/high choice

For example, users with smaller phone screens could adjust these settings to show a lower density QR to allow camera-based signers to read the PSBT more easily. Also helpful for devices with lower resolution cameras

**Comment by Syturio** [comment]
2 years later and still no fix for this, dissapointing

**Comment by FREEBORN-MAN** [comment]
Just getting more experience with QR code scanning of offline devices is with a Jade and Seedsigner and am having difficulty loading the transaction details on the dense QR code generated by bluewallet. Nunchuck wallet worked fine. 

I would like to see this change and think it’s really helpful.

**Comment by Sparks17** [comment]
I’m also having trouble scanning PSBT from Blue on mobile. Have iPhone XR.
No trouble with scanning from Sparrow.
Blue and SeedSigner are up to date.
I’ve tried low, medium, and high density setting on SS, no success.

**Comment by Overtorment** [comment]
i checked the code, and apparently we have 200 of someting for capacity:

![image](https://github.com/BlueWallet/BlueWallet/assets/1913337/63677c21-9b9e-4c82-b1dc-443e81ebf11a)



i see no problem lowering it, but what would be the sensible amount thats good for everyone?

making a dedicated setting for density feels like too much work especially if we can solve it just lowering one number a bit

**Comment by Overtorment** [comment]
ive prepared an experimental PR lowering it to 175: https://github.com/BlueWallet/BlueWallet/pull/6316
if someone is on android, can you pls try the build from that PR and see if its a good enough value..?
