### ISSUE TITLE
External "lightning:LNURL..." links not working anymore

### ISSUE THREAD

**Issue by Fittiboy** [BlueWallet/BlueWallet#3867]
I'm on iOS 15, running BW 6.2.7
Described the issue in Telegram, so here's a lazy copy-paste of that:
> Ran into a weird issue. Using iOS 15 and the latest BlueWallet (6.2.7). When I scan a "lightning:LNURL..." link with from inside the app, it all works just fine. But when I scan it with my iOS camera app, and open BlueWallet from there, it just asks me if I want to use the invoice I stored in my clipboard (I have no invoice in my clipboard). It then does nothing when I hit "Yes," and the "Scan" button stops working.

**Comment by marcosrdz** [comment]
Hello! Can you provide a video of this issue? Im unable to replicate after testing with LNBits' LNURL

**Comment by Fittiboy** [comment]
Well the issue disappeared as soon as you asked for a video lol. I'll reopen if it happens again!

**Comment by marcosrdz** [comment]
We were able to replicate thanks to your detailed description that included the clipboard process. Thank you!
