### ISSUE TITLE
Balance problems

### ISSUE THREAD

**Issue by Marabun** [BlueWallet/BlueWallet#387]
1. I sent a lightning payment. The balance has decreased but the transaction is not received. This problem was not the first time! The amounts were less and I did not pay attention to it.
2. Updated my wallet. I have done this many times. Removed and installed the wallet again. Nothing has changed.
3. Where did the coins go??
Watch the video. What should be the balance on the balance sheet?

https://youtu.be/hDp-sopAaXM

**Comment by Overtorment** [comment]
1. When paid, wallet reported success, failure, or "in transition" ? If "in
transition" then payment might be stuck, and it will get un-stuck (and
funds freed) after some time (hours?). Can you send me the problematic
invoice string..? Ill investigate this.

**Comment by Marabun** [comment]
> When paid, wallet reported success, failure, or "in transition" 
This is the result of the second attempt to pay the same invoice. For the first time the same result. Watch the video.
https://youtu.be/E60FqRkRoSY
Yes, it's "in transition".

**Comment by Overtorment** [comment]
invoice from the video failed and got un-stuck automatically.
althtough you have older payment from march, 6th in stuck state. Ill see
what I can do

**Comment by Marabun** [comment]
> invoice from the video failed and got un-stuck automatically.
> althtough you have older payment from march, 6th in stuck state. Ill see
> what I can do

Why the amount is not returned to the balance? Before payment I checked the balance. There was 11504586 Satoshi. 
If You do count from the first video, you'll see that lack 4816586 Satoshi! This is from the last refill.

**Comment by Overtorment** [comment]
You have only 1 payment stuck, for 1980471 sats, and I don't know what
happened, yet.
Incorrect balance on wallet card is usually a cache issue, and it will fix
itself automagically in 1 hour.

**Comment by Marabun** [comment]
Sorry, я не понял о чем здесь речь - "Incorrect balance on wallet card is usually a cache issue" ?
Я говорю о том, что в кошельке разница между учетом дохода и расхода! Баланс меньше чем учтённые траты. У меня уже не в первый раз Alert "in transition", после чего деньги списываются с баланса и пропадают в неизвестном направлении, транзакции не завершаются, получателю ничего не приходит. И это списание не учитывается в истории платежей из-за чего такая разница между приходом и расходом.

**Comment by Marabun** [comment]
> You have only 1 payment stuck, for 1980471 sats

Судя по приходу и расходу там проблемы значительно больше. И "зависшие" деньги где-то еще лежат..

**Comment by Overtorment** [comment]
Баланс всегда считается как сумма прихода и расхода, вот тут
https://github.com/BlueWallet/LndHub/blob/1ad26e21b85f347ef72ccd4865e95657e01a0f40/class/User.js#L137
Есть еще кеш, который экспайрится за час и обычно проблем не доставляет.

**Comment by Marabun** [comment]
Спасибо, понял. Значит у вас по всем фронтам: сумма прихода и расхода, а так же кеш, есть проблемы. Это судя по статистике и балансу.

**Comment by Overtorment** [comment]
Возможно есть. Если сможешь отрепродюсить на свежем аккаунте, чтоб небыло много транзакций, было б неплохо.

**Comment by Marabun** [comment]
Сложность в том, что я ловил такой баг только при крупных транзакциях, мелкие никогда не зависали с алертом in transition". К сожалению я понял это только сегодня, раньше думал, что неправильно запоминал баланс, или типа не обновил его, а он был в реальности меньше. Поэтому продолжал юзать кошелек. Но после сегодняшней транзы и повторения истории нет желания репродюсить. Мужики, я бы помог, но уже и так 190$ испарилось, дорогие тесты.

**Comment by Overtorment** [comment]
если я смотрю правильный аккаунт, то вот такая история

```
imported_txid
==============
 [ 1',  '2',  '3' ]

userinvoices
================

+ 2005 Tue Jan 08 2019 10:33:44 GMT+0000 (Greenwich Mean Time)
+ 4000000 Thu Feb 21 2019 20:53:54 GMT+0000 (Greenwich Mean Time)
+ 4000000 Thu Feb 21 2019 20:55:09 GMT+0000 (Greenwich Mean Time)
+ 4000000 Thu Feb 21 2019 21:46:38 GMT+0000 (Greenwich Mean Time)
+ 4000000 Thu Feb 21 2019 22:03:53 GMT+0000 (Greenwich Mean Time)
+ 4000000 Thu Feb 21 2019 23:27:10 GMT+0000 (Greenwich Mean Time)
+ 4000000 Thu Feb 21 2019 23:29:15 GMT+0000 (Greenwich Mean Time)
+ 4000000 Thu Feb 21 2019 23:32:56 GMT+0000 (Greenwich Mean Time)
+ 4000000 Thu Feb 21 2019 23:43:15 GMT+0000 (Greenwich Mean Time)
+ 4000000 Thu Feb 21 2019 23:51:55 GMT+0000 (Greenwich Mean Time)
+ 4083000 Fri Feb 22 2019 00:12:09 GMT+0000 (Greenwich Mean Time)
+ 4051361 Fri Feb 22 2019 00:18:35 GMT+0000 (Greenwich Mean Time)
+ 200 Thu Feb 28 2019 19:51:10 GMT+0000 (Greenwich Mean Time)
+ 3249892 Thu Feb 28 2019 19:55:54 GMT+0000 (Greenwich Mean Time)

txs
===

+ 210000
+ 4000000
+ 20000000
- 2005 Tue Jan 08 2019 16:20:39 GMT+0000 (Greenwich Mean Time) Wallet of Satoshi
- 4000000 Thu Feb 21 2019 22:01:11 GMT+0000 (Greenwich Mean Time) Wallet of Satoshi
- 4000000 Thu Feb 21 2019 23:28:27 GMT+0000 (Greenwich Mean Time) Wallet of Satoshi
- 4000000 Thu Feb 21 2019 23:30:08 GMT+0000 (Greenwich Mean Time) Wallet of Satoshi
- 4000000 Thu Feb 21 2019 23:49:33 GMT+0000 (Greenwich Mean Time) Wallet of Satoshi
- 4000016 Thu Feb 21 2019 23:55:30 GMT+0000 (Greenwich Mean Time) Wallet of Satoshi
- 4050000 Fri Feb 22 2019 00:13:14 GMT+0000 (Greenwich Mean Time) Wallet of Satoshi
- 3998703 Fri Feb 22 2019 01:28:41 GMT+0000 (Greenwich Mean Time) Exchange 4125 UAH to card 
- 4000802 Fri Feb 22 2019 01:32:42 GMT+0000 (Greenwich Mean Time)
- 4000802 Fri Feb 22 2019 01:37:25 GMT+0000 (Greenwich Mean Time)
- 4000802 Fri Feb 22 2019 01:38:07 GMT+0000 (Greenwich Mean Time)
- 171036 Sat Feb 23 2019 04:29:16 GMT+0000 (Greenwich Mean Time)
- 220046 Sat Feb 23 2019 04:30:50 GMT+0000 (Greenwich Mean Time)
- 2519155 Sat Feb 23 2019 04:33:39 GMT+0000 (Greenwich Mean Time)
- 2 Sat Feb 23 2019 04:38:32 GMT+0000 (Greenwich Mean Time) Wallet of Satoshi
- 402 Sat Feb 23 2019 04:43:18 GMT+0000 (Greenwich Mean Time) Wallet of Satoshi
- 402 Sat Feb 23 2019 04:44:53 GMT+0000 (Greenwich Mean Time) Wallet of Satoshi
- 500102 Sun Feb 24 2019 20:47:43 GMT+0000 (Greenwich Mean Time)
- 400082 Sun Feb 24 2019 20:48:21 GMT+0000 (Greenwich Mean Time)
- 30002 Sun Feb 24 2019 20:49:10 GMT+0000 (Greenwich Mean Time)
- 38366 Sun Feb 24 2019 23:11:15 GMT+0000 (Greenwich Mean Time)
- 400000 Sun Feb 24 2019 23:38:06 GMT+0000 (Greenwich Mean Time) Wallet of Satoshi
- 3900000 Thu Feb 28 2019 19:46:55 GMT+0000 (Greenwich Mean Time) Wallet of Satoshi
- 113024 Thu Feb 28 2019 19:51:50 GMT+0000 (Greenwich Mean Time)
- 3000628 Fri Mar 01 2019 14:39:28 GMT+0000 (Greenwich Mean Time)
- 150032 Sat Mar 02 2019 11:49:37 GMT+0000 (Greenwich Mean Time)
- 350072 Sat Mar 02 2019 11:50:29 GMT+0000 (Greenwich Mean Time)
- 550112 Sat Mar 02 2019 11:51:19 GMT+0000 (Greenwich Mean Time)
- 650136 Sat Mar 02 2019 11:52:00 GMT+0000 (Greenwich Mean Time)
- 850176 Sat Mar 02 2019 11:53:35 GMT+0000 (Greenwich Mean Time)
- 2781511 Mon Mar 04 2019 14:35:11 GMT+0000 (Greenwich Mean Time) Exchange 2000 UAH to card 
- 1432985 Tue Mar 05 2019 09:51:44 GMT+0000 (Greenwich Mean Time) Exchange 1000 UAH to card 

calculatedBalance
================
 11504586
```

и еще 1980471 sat залочено в зависшем платеже от 6го марта с которым разбираюсь

**Comment by Marabun** [comment]
Wow, это видимо вернулась сумма с того самого кеша?

**Comment by Overtorment** [comment]
скорее всего кеш сбросился и баланс пересчитался, какойто пеймент неудался, но корректно завершился ошибкой. я ничего не делал. проблема только в оставшихся зависших 1980471  от 6го марта. разберусь и пофикшу.

**Comment by Marabun** [comment]
Ок, готов репродюсить. Завтра сделаю новый акк. Что учитывать, фиксировать?

**Comment by Overtorment** [comment]
Уже ничего, разобрались, раз баланс вернулся.

**Comment by Marabun** [comment]
Хорошо. Возможно стоит все же такие транзакции показывать в статистике, чтобы было понятно что они учтены и где-то в процессе. А иначе вот такой гемор возникает.

**Comment by Overtorment** [comment]
Хорошая идея, да, зависшие транзы выдавать в списке

**Comment by Marabun** [comment]
> скорее всего кеш сбросился и баланс пересчитался, какойто пеймент неудался, но корректно завершился ошибкой. я ничего не делал. проблема только в оставшихся зависших 1980471 от 6го марта. разберусь и пофикшу.

Если я правильно посчитал, то проблема с зависшим платежом от 6го марта решена?

**Comment by Overtorment** [comment]
Да, я вчера закомитил скрипт который процессит зависшие платежи

**Comment by vix184** [comment]
I have the same problem now, fuck: /
As Marabun said, it does it with big amounts, for me more than 2000000sats.
But it is written now "payment in transition" is better;) I have more than wait about 72h to see my 5756091sats if I understood correctly?
Can nothing be done to improve this problem?

**Comment by Overtorment** [comment]
Payment it transition is okay. Regular script that checks those
transactions will soon launch, tx will either go through or will stay
locked for up to 4 days if I remember correctly

**Comment by vix184** [comment]
the payment has expired since 24 hours and has been in transition since the same time. I'm waiting, I'm in no hurry;) I'll come back to you if it has not moved in 4 days Igor :))). Thank you for your work, you are the best;)
