### ISSUE TITLE
HD Segwit Wallet not showing balance from sub-wallet

### ISSUE THREAD

**Issue by gereon76** [BlueWallet/BlueWallet#388]
https://www.blockonomics.co/#/search?q=ypub6XRzrn3HB1tjhhvrHbk1vnXCecZEdXohGzCk3GXwwbDoJ3VBzZ34jNGWbC6WrS7idXrYjjXEzcPDX5VqnHEnuNf5VAXgLfSaytMkJ2rwVqy

In the Bluwallet i only see 0.00045544 BTC as balance, even after reinstall and wallet restore

**Comment by Overtorment** [comment]
Acknowledged. Will debug

**Comment by Overtorment** [comment]
Ok, the problem is that in this hierarchy there is one address skipped in `external` branch.

```
    external 0 37EX3KrmopubWPLB8Y8NR36wXs7icu2kjQ
    external 1 398qz3BtNG8DABpEGa2VkHBcficxkgeKvX  <--- that one
    external 2 3Nx4xZ5xgG92j7eaFbEUrPpsPBmJfjzn26
```

BW cant work with gaps yet, but the fix is trivial. Will fix it in next release.
Thanks for reporting!

**Comment by phorest0** [comment]
Hi, I’ve got the same issue. I’ve create a test Wallet for bloconomics, https://www.blockonomics.co/#/search?q=ypub6YAZANqNrSb2s1JjkAipRZxosWGERbKWUYgLUvq8pwuzY8JDfkoDxMMiz26zegjjwfD1LQtwwcML1r88GG56CpVzGStykbiabnSxHnWukYZ

Made a several payments with small amounts of btc, but in app balance it’s shows me 0 balance.

**Comment by Overtorment** [comment]
@phorest0 you have large gaps in hierarchy. Did you use some other app to create this specific wallet..?
BlueWallet should not be making such gaps

**Comment by phorest0** [comment]
Overtorment, нет. Кошелек был создан в BlueWallet, и от туда был скопирован публичный адрес. Обновление не помогло, баланс тех денег так и не отображается в кошельке. Как теперь получить эти деньги??

https://www.blockonomics.co/#/search?q=ypub6YAZANqNrSb2s1JjkAipRZxosWGERbKWUYgLUvq8pwuzY8JDfkoDxMMiz26zegjjwfD1LQtwwcML1r88GG56CpVzGStykbiabnSxHnWukYZ

**Comment by Overtorment** [comment]
@phorest0 Electrum на десктопе должен уметь работать с этим форматом. Или вот тут https://iancoleman.io/bip39/ вбить мнемонику и на вкладке BIP49, в разделе Derived Addresses будут все адреса кошелька. Можно брать приватные ключи на каждый и импортировать как кошелек в почти любом приложении. 
Откуда взялся такой промежуток непонятно. BW теперь умеет работать с gap_limit=5 но 30 это пока черезчур. Если удастся отрепродюсить - пофикшу.

**Comment by phorest0** [comment]
@Overtorment разобрался с https://iancoleman.io/bip39/ и вытащил все через Electrum.
 Спасибо, Хороший проект, респект! Буду тестить дальше :)
