### ISSUE TITLE
Bitcoin payment not successfully sent

### ISSUE THREAD

**Issue by BenGWeeks** [BlueWallet/BlueWallet#3882]
## Environment

* Phone model and OS version: iPhone 12 Pro Max, iOS v14.7.1
* BlueWallet app version: v6.2.7
* Umbrel version: v0.4.1
* BlueWallet Lightning version: v1.3.3 (with LND installed)

## Steps to reproduce

(NB This is connected to my Bitcoin/Lightning node that is running)
Send a Bitcoin payment (repeat until payments start failing)

### Result

After a period of time, transactions do not go through, and you just see a spinning timer as below.

![image](https://user-images.githubusercontent.com/5950171/134539007-3a5009fd-6b0a-4ea8-951a-b16191856874.png)

I believe this also causes this page to not update:

![image](https://user-images.githubusercontent.com/5950171/134568717-16ced375-d483-4b88-9618-27edc70f2f4a.png)

### Expected behaviour

Success screen should be displayed and the transaction is sent.

### Workaround

Kill the app and re-open.

**Comment by BenGWeeks** [comment]
Possibly related to [issue 3869](https://github.com/BlueWallet/BlueWallet/issues/3869).

**Comment by Overtorment** [comment]
looks like networking issue
