### ISSUE TITLE
Styling and usability recommendations for the export screens

### ISSUE THREAD

**Issue by GBKS** [BlueWallet/BlueWallet#3885]
I find the wallet export screens too sparse, there is not enough information for non-experienced users to understand what the information is and what do do with it. I'm proposing some minor cosmetic and usability changes here.

![Blue wallet export review 210924](https://user-images.githubusercontent.com/695901/134659167-f71eb717-a5a5-4dae-a992-914be947b12a.png)

I recreated the screens in Figma using dummy data, so nothing important in these screens here.

**Comment by Overtorment** [comment]
@ncoelho

**Comment by ncoelho** [comment]
Thanks @GBKS please keep them coming whenever you can 👍

**Comment by limpbrains** [comment]
I'm really excited about this proposal and have finally decided to work on it. I’d like to share my progress and some thoughts.

I don’t want to increase paddings or font size, as I believe that should be adjusted across the app, if needed. BlueWallet supports various wallet types (SLIP39, watch-only, Multisig), and here’s a video where I demonstrate using them all, including both light and dark modes. For instance, with SLIP39, we deal with multiple seeds (shares).

https://github.com/user-attachments/assets/294f402d-eab3-482f-b4d8-6aa695f16a77

I still need to tweak some text, like prompting users to back up words for BIP39 and URLs for LN wallets. Also, I’ve noticed that BW doesn’t allow copying the seed. If that’s the case, why display a QR code? What’s the advantage?

Regarding "Scan this QR code to import your wallet into another application," I can imagine a scenario where someone opens the Camera app on an iPhone, scans the QR code, and the OS suggests opening Google with the seed in the search query. That’s far from ideal.

Thoughts, gentlemen?
Maybe it is time to revisit it once again, before I finish polishing it

**Comment by Overtorment** [comment]
@limpbrains lgtm! as for QR, its super useful when porting wallets from one device to another (kinda airgap). and copying seed to clipboard imo is not a good idea, users leak their seeds all the time, that would be just another source of leaks.

@ncoelho wdyt

**Comment by ncoelho** [comment]
I don't like some things here.

- the blue looks like a button
- the text telling the user to copy is not a good practice
- allowing copy, needs warning modals to the risks and clear the clipboard when possible. Not cool to allow the key to leave the app.

Not sure we are gaining things with this change. Am I missing something?

**Comment by limpbrains** [comment]
> @limpbrains lgtm! as for QR, its super useful when porting wallets from one device to another (kinda airgap)
Agree, but maybe it should not be shown by default

Will disable copy for seeds.

> the blue looks like a button 
Indeed

**Comment by GBKS** [comment]
Thank you. I updated the graphic in my comment above with your feedback (so this page doesn't get annoyingly long with endless mockup variations).

**Comment by limpbrains** [comment]
@GBKS @ncoelho thank you guys! [PR is here](https://github.com/BlueWallet/BlueWallet/pull/7324)

**Comment by GBKS** [comment]
I'd love to help test the code, but can't get the app to build locally (not a dev) and don't have access to BrowserStack. Someone else will have to review.
