### ISSUE TITLE
Translation flaw

### ISSUE THREAD

**Issue by Abstraktikus** [BlueWallet/BlueWallet#3894]
Right-clicking on a transaction opens the following menu:
Copy (365) Amount (169)
Copy (365) Note (355)
Copy (365) Transaction ID (389)
Copy (365) Block Explorer Link (357)
View in Block Explorer (Ok)
Expand Note (Ok)

(365 = ID's from Transifex)

Problem:
In German, the verb should be at the end. Would it be possible to make separate keys for the respective entries instead of a composition?

**Comment by Overtorment** [comment]
up to @limpbrains

**Comment by marcosrdz** [comment]
Perhaps strings for each or 1 "copy" string that takes a parameter.

**Comment by limpbrains** [comment]
It is better not try to construct any phrases in code. Each option should be separate string. 

@Abstraktikus thanks for reporting!
