### ISSUE TITLE
The term "Alert" is not part of the localisation file

### ISSUE THREAD

**Issue by Abstraktikus** [BlueWallet/BlueWallet#3895]
BTW, it would be great if Blue Wallet could distinguish between an alert (critical) and a notice (info).
I even wonder if it's not standard today to trust an app to save customizations. At least Microsoft no longer confirms within the settings.

**Comment by marcosrdz** [comment]
We use the device haptic engine and use the platform specific feedback based on the event. Like for successful wallet import.

**Comment by Overtorment** [comment]
@ncoelho
