### ISSUE TITLE
Fix main call to actions.

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#39]
- Fix style to match design
- send button should always be present to avoid confusion. Error for no funds should be presented on sending view.

[zpl.io/Vk5m4DZ
](url)
<img width="1175" alt="screen shot 2018-09-08 at 22 25 15" src="https://user-images.githubusercontent.com/1238429/45258340-202c6400-b3b6-11e8-92d0-692f024ea85d.png">

**Comment by Overtorment** [comment]
https://media.giphy.com/media/xT9DPr4VjeCgeiLoMo/giphy.gif
