### ISSUE TITLE
Why can't I see the commission when sending lightning payments?

### ISSUE THREAD

**Issue by Marabun** [BlueWallet/BlueWallet#390]
I sent a payment where the commission was 40k satoshi! Why so much and why I don’t see it before sending the payment?
Why is the commission more than the on-chain network?

![photo_2019-03-13_14-26-58](https://user-images.githubusercontent.com/12554812/54279262-503f0480-459d-11e9-8864-415158b773d6.jpg)

**Comment by Marabun** [comment]
А вот пример платежа с другого кошелька:

![photo_2019-03-13_14-56-52](https://user-images.githubusercontent.com/12554812/54280513-600c1800-45a0-11e9-9e73-a3b598186e8e.jpg)

**Comment by ncoelho** [comment]
We are still experimenting with the fees, displaying the fee upfront was not implemented yet

**Comment by giulnz** [comment]
not only before sending but also can't see fee in trasaction detail

**Comment by Overtorment** [comment]
we dont really plan to work on this
