### ISSUE TITLE
Sign any message with private key

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#393]

**Comment by whiteyhat** [comment]
Any progress to provide this feature?

How is the architecture to execute lightning requests, through `bitcoinjs`? 

Using `ln-service` to overcome this issue could bootstrap this issue and also allow a non-custodial element to connect your own node to the bluewallet app by using the `invoice_macaroon`

**Comment by turbolay** [comment]
This feature is still unavailable in BlueWallet ? Being able to provide proof of ownership should become more and more important, especially if people use BTC as an SoV. It can be required to be granted a loan or a visa for example.

**Comment by whiteyhat** [comment]
The feature of signing messages can be a qualitative asset as well as a technological advantage for lightning clients. However, this requires 1 node per signature. 

Not sure, but maybe implementing this solution enters in conflict with the dev roadmap

**Comment by Derad6709** [comment]
Will be very useful in this app

**Comment by pointbiz** [comment]
I'm also interested in this feature. 

Maybe inside the menu on the send screen an option for Sign Message can be listed there. Or maybe inside the coin control screen a button next to each UTXO that says “Sign”. That would open a sign message dialog screen.
