### ISSUE TITLE
Android keyboard when entering mnemonic at import should not enforce number row

### ISSUE THREAD

**Issue by jpph** [BlueWallet/BlueWallet#3956]
The keyboard type query should be same as wallet name. On small screen, adding number row on keyboard make the input zone very small/unreadable. 

![IMG_20211001_034755](https://user-images.githubusercontent.com/901620/135554784-6049d62a-a9b0-4bd9-8cdf-1270ea05f652.jpg)

Here you see at wallet name, not number row:
![IMG_20211001_041143](https://user-images.githubusercontent.com/901620/135554996-f159303c-169e-47b8-8c80-52d940981033.jpg)

**Comment by jpph** [comment]
Or maybe the pop-up keyboard should hide also the passphrase/search toggle, so the input zone is taller...

**Comment by marcosrdz** [comment]
Thats the android keyboard that is designed for sensitive content. The other keyboards provide options for outside content to be inserted.

**Comment by jpph** [comment]
understood. If i understand your patch, you are hiding now the toggles when the keyboard is poped up ? nice job!

**Comment by marcosrdz** [comment]
> understood. If i understand your patch, you are hiding now the toggles when the keyboard is poped up ? nice job!

That is correct. It should provide more room to see what is being typed
