### ISSUE TITLE
LNDHUB error on Lightning wallet creation [Tor | ios]

### ISSUE THREAD

**Issue by Covalent5** [BlueWallet/BlueWallet#3970]
## Bug Report

Environment:

* iPhone XS Max on iOS 15.0.1

* BlueWallet app version 6.2.8

* self-test passes OK

* userId:E8DA7720-1E22-45C5-B5F7-BA4960AA077C

Description:

After the 6.2.8 update, lightning wallet creation fails with error `TypeError: Network request failed`. 

I am using my umbrel node, correctly configured in settings (both electrum and lightning). 

Before the BlueWallet update everything was ok. The app accepts my LNDHUB tor address in settings, but when I go to create a wallet it gives the above error. 

Steps Tried Unsuccessfully:
- Reboot node
- Reinstalled BlueWallet app on the node
- Reinstalled BlueWallet app on iPhone
- LNDHUB Tor link reachable via Tor browser
- Manually restarted Tor deamon from settings

**Comment by Overtorment** [comment]
can you pls share your lndhub url privately to i@bluewallet.io ?

**Comment by Covalent5** [comment]
What do you mean?
