### ISSUE TITLE
PSBT failure bc of incorrect derivation path

### ISSUE THREAD

**Issue by atom686** [BlueWallet/BlueWallet#3974]
iPhone 11 Pro with BlueWallet 6.2.5

I have watch only wallet in BlueWallet with Coldcard as a signing device. The account number for the wallet is not 0. When I generate PSBT, coldcard fails to sign with the following error:
“Path m84 /0 /0 /0/26 led to wrong pubkey for input 0”
It makes sense because path should be different (account number is 4). Seems like it’s a bug on BlueWallet side.

**Comment by ncoelho** [comment]
Coldcard support is only for account 0.

**Comment by Overtorment** [comment]
You should be able to import a watch-only wallet with the correct path so coldcard can sign with no problem, for example:

```
{"ExtPubKey":"zpub6rcabYFcdr41zyUNRWRyHYs2Sm86E5XV8RjjRzTFYsiCngteeZnkwaF2xuhjmM6kpHjuNpFW42BMhzPmFwXt48e1FhddMB7xidZzN4SF24K","MasterFingerprint":"5271c071","AccountKeyPath":"84'\/0'\/3'"}
```

**Comment by Overtorment** [comment]
but you need version `6.2.8`  at least
