### ISSUE TITLE
Work through proxy? TOR?

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#398]

**Comment by chrisc93** [comment]
Is this being worked on?

**Comment by ncoelho** [comment]
Up for grabs 👍

**Comment by talvasconcelos** [comment]
Desperately needing this...

**Comment by chrisc93** [comment]
Addressed here https://github.com/BlueWallet/BlueWallet/pull/1318 😃

**Comment by primeroz** [comment]
Really need this, i want to migrate to bluewallet but without this is i simply can't
