### ISSUE TITLE
Electrum server doesn't support Verbose param in blockchainTransaction_get call 

### ISSUE THREAD

**Issue by limpbrains** [BlueWallet/BlueWallet#3985]
Electrum server like, `electrum.blockstream.info:60002` (testnet) doesn't support VERBOSE param in `blockchainTransaction_get`. It throws `verbose transactions are currently unsupported` error and BW doesn't handle it correctly. Instead it just can't load transactions list and fails silently 

`electrum.blockstream.info:60002` uses `electrs-esplora 0.4.1`, `ElectrumX 1.16.0` works fine

**Comment by Overtorment** [comment]
damn, before they used to just silently ignore verbose param and return txhex
