### ISSUE TITLE
Sweep other private key

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#400]

**Comment by GlenCooper** [comment]
I would make use of sweeping functionality if it existed.  Not super important, just one of those nice-to-have kinda things...
![Screenshot from 2020-10-07 00-34-40](https://user-images.githubusercontent.com/967793/95274306-efd57f00-0834-11eb-8bc9-677e870de199.png)

**Comment by rafaelpac** [comment]
I would use it too, for importing P2PKH paper wallets.

**Comment by Overtorment** [comment]
Well, you can achieve the same with fer extra steps:
1) Import your paper wallet
2) SendMAX from this wallet wherever you want to
3) ...
4) profit!

**Comment by rafaelpac** [comment]
Yes! It works.
I had tried before to import a paper wallet and it didn't work. I did it with an empty balance wallet, just for testing, but it doesn't work if it is empty.
I just tried again with a loaded one and it worked (actually, it first gave me an error, but there was an option to try again and then it worked). 
I see now that BW will check to see if the p2pkh address has any balance. If not, then it just creates a p2sh wallet.
Nice! Thanks.

**Comment by rafaelpac** [comment]
![Capture+_2020-10-10-12-35-25-1](https://user-images.githubusercontent.com/6444444/95659198-c0a16500-0af5-11eb-8bf7-4e393c38d5c7.png)
![Capture+_2020-10-10-12-35-32-1](https://user-images.githubusercontent.com/6444444/95659205-c8f9a000-0af5-11eb-9242-77b9f90ca8aa.png)
![Capture+_2020-10-10-12-35-37-1](https://user-images.githubusercontent.com/6444444/95659208-cc8d2700-0af5-11eb-9552-b8a953c93197.png)
![Capture+_2020-10-10-12-36-07](https://user-images.githubusercontent.com/6444444/95659210-d0b94480-0af5-11eb-8ba5-6722318239a2.png)
