### ISSUE TITLE
Multisig Vault wallet card moves to end of wallet list if key zpub is added or removed

### ISSUE THREAD

**Issue by blankscreengithub** [BlueWallet/BlueWallet#4011]
Example:
1. A 2 of 3 multisig wallet that is setup for watch only
2. BlueWallet only has the zpubs of each key
3. Move wallet card up in the list of wallets
4. Use Manage Keys and tap on "I have a seed for this key."
5. Enter seed phrase
6. Tap "save" at bottom
7. Wallet card is moved to the far right of the line of wallets
8. I have to move the wallet card back up the list to the position I want
9. The wall card moving to the end of the list also happens if I remove the seed phrase and replace it with the zpub

**Comment by Overtorment** [comment]
cant say its by design, but this is the way its made (technically we delete old one and create a new one).
fixing it is probably gonna be hard and not worth it. easier to live with it

**Comment by blankscreengithub** [comment]
> cant say its by design, but this is the way its made (technically we delete old one and create a new one). fixing it is probably gonna be hard and not worth it. easier to live with it

I'm fine with leaving it the way it is. I didn't realize it deleted the old wallet and created a new one.
