### ISSUE TITLE
"min relay fee not met" not a localizable label?

### ISSUE THREAD

**Issue by pysiak** [BlueWallet/BlueWallet#4031]
![06610DA1-5900-43F5-83FD-F5D72506068C](https://user-images.githubusercontent.com/2396137/136998981-dfeb5e90-7b89-4464-a2c3-0f34b0ba268b.jpeg)

This error message is not translated because I think there's no localizable resource label.

Am I right?

**Comment by marcosrdz** [comment]
Its not localizable as it appears to be a message provided by the server
