### ISSUE TITLE
User guidance in case of frozen coins

### ISSUE THREAD

**Issue by Abstraktikus** [BlueWallet/BlueWallet#4054]
Users often forget that they have frozen coins. (I at least am such a candidate.)

If someone tries to send the maximum amount with frozen coins, only the unfrozen amount will be sent without prior warning. What remains is a residual balance and a big question mark.

**Message for use Full Balance:** "Are you sure you want to use your wallet's full balance for this transaction?"
**Cheap solution:** "Are you sure you want to use your wallet's full balance for this transaction? 
                                  Please note that frozen coins are excluded."

**If no unfrozen balance is left, this error appears:** "Not enough balance. Try sending smaller amount or decrease the fee"
**Cheap solution:** "Not enough balance. Try sending smaller amount or decrease the fee.  
                                  Please note that frozen coins are excluded."

Of course, it would be better to display this specific text additions only when coins are frozen. Or to display the concrete amount on the send mask instead. (Probably unattractive.)
A more optimal solution would be to permanently show the balance of unfrozen coins exactly only additionally when coins are frozen.

Wallet name (Medium)
0.004576365 (Large)
Not frozen: 0.000263012 (Very small - but balance can also be copied with the right mouse button.)
(Alternative: Available for TX:  0.000263012)

Could this save a few rare but complex tickets? 
I would find it nicer.

**Comment by limpbrains** [comment]
Nice idea, thanks @Abstraktikus!
