### ISSUE TITLE
Missing strings in the translation file

### ISSUE THREAD

**Issue by Abstraktikus** [BlueWallet/BlueWallet#4055]
These texts are not part of the translation file:

"Not enough balance. Try sending smaller amount or decrease the fee."

"my first wallet" (basic text for the wallet name) --> Be careful, this string comes before the wallet is created and is different to the string displayed when the wallet is already created.

"API error: Payment failed. Does the receiver have enough inbound capacity (code 10)"

**Comment by marcosrdz** [comment]
> These texts are not part of the translation file:
> 
> 
> 
> "Not enough balance. Try sending smaller amount or decrease the fee."

Text comes from API 

> 
> 
> 
> "my first wallet" (basic text for the wallet name) --> Be careful, this string comes before the wallet is created and is different to the string displayed when the wallet is already created.

Noted. Will implement
> 
> 
> 
> "API error: Payment failed. Does the receiver have enough inbound capacity (code 10)"

Text comes from API
