### ISSUE TITLE
disable notification when Plausible Deniability is enabled

### ISSUE THREAD

**Issue by EZ0010** [BlueWallet/BlueWallet#4065]
I think notification for the wallet (sent transaction, received transaction) should be disabled by default if the wallet has Plausible Deniability enabled, because it can compromise the main benefit of it.

or make it you can receive notifications only if you unlocked the wallet and didn't force close the app since then.

**Comment by Overtorment** [comment]
not doable, push-notification server is not aware of client's state.
its better to disable pushes manually (like, in OS settings).
