### ISSUE TITLE
Create wallet view 

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#41]
Create wallet view where should be possible to:
- see wallet tx
- receive/send tx
- options to edit wallet settings

[zpl.io/Vk5m4DZ](url)

![wallet view](https://user-images.githubusercontent.com/1238429/45258497-07717d80-b3b9-11e8-93a8-785e037abaf7.png)

**Comment by marcosrdz** [comment]
Added in commit 3b479baee22144bade2e35841377379a997bb93c
