### ISSUE TITLE
Import wallet never completes on iOS

### ISSUE THREAD

**Issue by ohenrik** [BlueWallet/BlueWallet#410]
Hi, importing a wallet using the qr code scanner does not work on iOS, the "spinning" icon never ends and the wallet is not imported when restarting the app. There also does not seem to be any communication with my lndhub. 

The lightning "wallet" I am trying to import is from my own lndhub server and it was previously deleted from my phone (to test import/export logic).

It is also not possible to paste anything into the import field, making scanning a qr code the only viable option for importing wallets and lN "wallets".

**Comment by Overtorment** [comment]
Do you have your hub saved in settings..? If not - it tries to use your credentials on a defaut lndhub, which ofcourse are not there.

**Comment by Overtorment** [comment]
I will retest it tho

**Comment by ohenrik** [comment]
Yes, i have set the correct LndHub. Maybe test if the import mechanism somehow tries to use the default server regardless of my lightning-settings. 

Also maybe add an error response and let the user exit the import if it does not find any thing on the server. Atm. I have to close the app completely and restart it to be able to use the app again.

**Comment by Overtorment** [comment]
will be out in 3.9.0
