### ISSUE TITLE
Payment in transit, invoice timed out, funds not returned to balance

### ISSUE THREAD

**Issue by justtryinggit** [BlueWallet/BlueWallet#411]
After scanning an invoice and clicking pay it took a little longer than usual and a message appeared saying funds are in transit. Trying to pay the same invoice or another invoice triggers the same message saying payment is in transit and try again in 5 minutes. The invoice timed out without being paid. Funds have not returned to the wallet balance after over 13 hours. There's a direct channel between the two nodes.

I can now pay new invoices again, but funds from the original payment are still missing and don't show up on the transactions list.

**Comment by Overtorment** [comment]
Stuck payments are processed once per 24hrs, and they still might be stuck at that time (something to do with channels getting stuck where this payment was routed; havent figured it out yet).
In future versions stuck payments will probably be displayed in transactions list (till they are unstuck), I agree, its confusing for now (you cant see how much satoshis you have temporarily locked)

**Comment by justtryinggit** [comment]
Okay, I'll wait and report back. Thanks

**Comment by justtryinggit** [comment]
So, after over 48hrs nothing has changed. Refreshed several times both inside and outside lightning wallet. Anything else I can do?

**Comment by justtryinggit** [comment]
All right, thank you. I'll keep following it.

**Comment by justtryinggit** [comment]
Did I understand correctly that you'll only be able to get the hang of the funds after you close the respective channel?

**Comment by Overtorment** [comment]
Its either closing channel, or waiting for a combined (of all hops in a route) timeout, by default 24h per each hop.

**Comment by justtryinggit** [comment]
Any luck in clearing funds and crediting them back?

**Comment by Overtorment** [comment]
Ok, so some payments report being in transition for over 30 days. If I understand HTLC correctly, it should be safe to assume it is not paid and unlock them.
A bunch of payments got unlocked, yours too.
Improved unlocking script. Now payments can get stuck for max 4 days, no more.

**Comment by david29fez** [comment]
> comentado
Hello, I have a payment problem in transition.
Might you help me?

**Comment by monomadic** [comment]
I have this error also, and it's deeply unhelpful. When I delete the wallet and try to import the old "key", I get "API Failure".

Not the first time I have had problems with lightning network or blue wallets implementations of it.

It's honestly no wonder people think the lightning network is unusable. I now agree with them.
