### ISSUE TITLE
No transaction history after the update

### ISSUE THREAD

**Issue by xAdamPos** [BlueWallet/BlueWallet#416]
After the last BlueWallet update, I see only my balance but no transaction history (**latest transaction: never**) even after multiple refreshing. I have even tried to import the HD wallet once again but with the same result. 

- if I make a completely new wallet everything is fine (tx visible in other wallets)
- balance is updated correctly if I receive a new tx
- new addresses are generated properly
- impossible to make a transaction (Error: Not enough confirmed inputs - although they are)
- issues only with on-chain HD wallet (LN is OK)
- iPhone XS

**Comment by Overtorment** [comment]
Acknowledged. Will investigate

**Comment by xAdamPos** [comment]
Just a follow up: no change after the next update v 3.9.0 :-(

**Comment by Overtorment** [comment]
Pull-to-refresh isnt helping..?

Can you try opening options->about->run self test
and report if it passes or throws an error..?

**Comment by xAdamPos** [comment]
Unfortunately, it does not help.
I have just done the self test and the following error appeared:
error: Error: ESOCKET

**Comment by Overtorment** [comment]
That means BW could not connect to Electrum server. 
Try restarting the app and repeat  test, several times.

Some people reported they had issues with connection when they had VPN/TOR enabled. Do you have those..?

**Comment by xAdamPos** [comment]
The test went OK now but still no transactions list (just a balance is visible).

I suppose I will have to create a new HD wallet (because when I make a new wallet it's OK - the only one which has problem is my original one - but it was fine till the update)...

I have reinstalled the app multiple times - imported the private key again and again and it's still the same. If I use the private key with Electrum, the transactions appear correctly :-(

**Comment by Overtorment** [comment]
Its an HD wallet, right..?
Thats all very strange. There should be no difference between old wallets
and new ones. Try on other device..?

At least funds are SAFU 😂

**Comment by xAdamPos** [comment]
Yeah, it's a HD wallet.
I've just created a completely new HD wallet and no problems.
Very strange... Hopefully this one will stay after future updates :D

**Comment by Overtorment** [comment]
Try importing your seed on other device with BW

**Comment by xAdamPos** [comment]
I have just done that with no progress.
The same situation on another iOS device.

**Comment by Overtorment** [comment]
Can you send  ypub to i@bluewallet.io ?

**Comment by xAdamPos** [comment]
Sure, sent.

**Comment by Overtorment** [comment]
Ok, problem identified! My code has a hickup with that particular amount of transactions :-)
Quite easy to deal with, will try to squeeze a fix in next release, thanks!

**Comment by Overtorment** [comment]
Oh, would be nice if you could move all your funds from this wallet somewhere else, so I could use this ypub in a test suite. With your permission, of course.

**Comment by xAdamPos** [comment]
Of course you can.
I have already proceeded necessary steps :-)
Thank you as well!
