### ISSUE TITLE
passphrase is not taken in account in offline mode

### ISSUE THREAD

**Issue by jpph** [BlueWallet/BlueWallet#4178]
setup : smartphone in airplane mode and network / electrum server set to offline.
create new wallet, import : "acquire cushion tiny thought mutual approve park around behave climb another slide cross hospital will merge detail magnet witness charge record pattern flavor width"
passphrase set : "test"
first receive address is bc1q6pngee5uc632qvd0d6cndtsjva3x2j2mw6td7n , should be : bc1qw8t9d0qklpffy8dqkq9se2c5yhy3q37v0vjla3
This is big issue because if user dont take attention can loose fund or think he has lost funds....

**Comment by Overtorment** [comment]
cc @limpbrains
