### ISSUE TITLE
Custom derivation - chosing m44 or m49 is not working

### ISSUE THREAD

**Issue by jpph** [BlueWallet/BlueWallet#4185]
When using custom derivation path in offline mode, and other than segwit native, the derivation path is locked to m/84/0/0. The display format is correct though ( 1xxx or 3xxxx) but value is wrong because derivation path is wrong.
Fixing this might make address generated on previous version unspedable....

**Comment by limpbrains** [comment]
It is not locked to `m/84`, it is just default value for the input field. You can freely change it.
The idea that you can use any combination of path + wallet type

**Comment by jpph** [comment]
I understand, but give confusion. I think there should be a trigger that when user select for example m49/ the input field is updated.
The screen looks like there is 4 options, 1 input field and 3 predefined select box...

**Comment by limpbrains** [comment]
I agree that filling path depending on wallet type is a nice feature, you don't have to remember those values for different wallet types. 
But when I tried to design form in this manner, I broke Discovery feature.

Before that you can edit derivation path, see if any wallet exists for it and choose it 
Now, when you choose wallet, path changing and you have very different wallet.

Take a look at the video

https://user-images.githubusercontent.com/155891/140923265-c10e7405-9149-4ef7-a0d4-900d7e1abfa0.mp4

**Comment by jpph** [comment]
Your video is very nice, I do not understand why you disabled the path change. And having it at the bottom make more sense

**Comment by limpbrains** [comment]
Path change is not disabled

**Comment by jpph** [comment]
I meant you disabled path change to default when clicking on the 3 types. Your video is really nice and having BW like in the video would be perfect.

**Comment by Overtorment** [comment]
so, I dont get it. whats the issue here?

**Comment by jpph** [comment]
For less savy user, it can generate address with very uncommon bip format by inadvertence. Clicking on select box should reset the derivation path input field like in the video. Also the input field should be in the bottom screen because the flow is to choose first the wallet format ( hd bipxx) then the derivation path.
If issue with the design form, maybe the screen could be split in 2 screen, first choose the format and then the derivation path.

**Comment by jpph** [comment]
https://user-images.githubusercontent.com/901620/142875173-59438fd5-abb5-43ad-a11d-cbf5a1b364c5.mp4

Video showing that changing selection doesn't reset deprivation path. At the end it have a bip49 format with bip84 derivation path

**Comment by Overtorment** [comment]
@limpbrains thoughts..?

**Comment by limpbrains** [comment]
This screen is primarily designed to work in online mode. So that user can discover all types of wallets for given path. 
Even wrong ones. 
Discovery flow on my post with video is broken (found / not found), because when you tap on wallet type, derivation path changes instantly. I would like to keep this feature.
I understand that form is confusing and can be improved. 
Choosing derivation path by hand is hard and it needs a set of predefined values, maybe some sort of autocomplete (as far as I remember we don't have such UI element)

**Comment by jpph** [comment]
I understand, but still the input field should be in 4th position , or maybe screen split in half so user understand he need to fill both, there is 1 option + 3 select box.

**Comment by ncoelho** [comment]
This looks good for me. There's an input box and results below. It is an advanced option, so people should know what they are doing here.
