### ISSUE TITLE
Incorrect side of transactions displayed when both send and receive wallets are on same device

### ISSUE THREAD

**Issue by so7ow** [BlueWallet/BlueWallet#4189]
## Are you reporting a bug?

When selecting a transaction that exists as a send in one wallet and a receive in another wallet (both on the same device) the wrong side of the transaction is sometimes shown. Example: send from wallet A to wallet B, then select the transaction in wallet B but see the send from wallet A instead of seeing the receipt in wallet B. Acknowledged by Nuno on Telegram as a known issue that no one has reported or cared about fixing.

Please provide:

* your phone model and OS version
iPhone 13 Pro Max, iOS 15.1

* BlueWallet app version (settings->about->scroll down)
6.2.12 (build 1635261971 master)

* self-test passes? Open settings->about->scroll down, tap "Run self-test"
Yes

* unique ID for our crash reporting service (settings->about->scroll down, tap "copy")
userId:06215401-E054-4814-A696-1C32348E9856

**Comment by Overtorment** [comment]
this is because when user navigates to transactino details screen we dont pass which wallet was opened before, so the screen tries to guess which wallet thix tx belongs to (just simply iterating through wallets, so whichever wallet comes first).

@marcosrdz willing to look into it?

**Comment by marcosrdz** [comment]
Please provide a video of such flow as it may be an expected behavior due to mobile apps contextual navigation flow

**Comment by so7ow** [comment]
https://user-images.githubusercontent.com/633079/144449269-7dbd2b60-f310-4d95-8ea8-dd1f0191931a.MOV
