### ISSUE TITLE
lightning double spend

### ISSUE THREAD

**Issue by igoriokas** [BlueWallet/BlueWallet#4195]
**Environment**
* iPhone 12 mini, iOS 15.1
* BlueWallet app version 6.2.12
* self-test passes? yes
* electrum server: default
* lightning node: default ([lndhub.io](https://lndhub.io/))
* userId: 12E9BE1E-F4CF-4A48-9438-F50092FADACB

#### The issue:

1. On my lightning bluewallet I had 19677 sats.
2. Sent 19400 sats to my muun lightning wallet.
3. Received the 19400 sats on muun, all good there.
4. Back to bluewallet: the transaction just disappeared from bluewallet and balance did not update, still had the same 19677 sats.
5. Again, sent 19401 sats from bluewallet to muun.
6. This time transaction stayed on bluewallet and balance updated.
7. On muun wallet I got to keep sats from both transactions: 19400 + 19401 

**The spent 19401 sats transaction on my bluewallet:**
![image](https://user-images.githubusercontent.com/38182908/141282905-a1367e4a-23cb-42ac-896a-ebe080e7861e.png)

**Received transaction on muun wallet:**
![image](https://user-images.githubusercontent.com/38182908/141281974-75862300-249e-436c-b5d2-54414f0ee11a.png)

**The 19400 sats transaction is missing on bluewallet.**
![image](https://user-images.githubusercontent.com/38182908/141282511-d30a9290-88f3-4437-939e-cd6ee22ca053.png)
Payment hash: cbf4213fa35896c5ad4ab373605abd6445d7c259e67fb75a434ef8e080325951
Payment preimage: Ofaa676fd8fbe34c6cdbc9bddd64438fb2d70493f6c78f1ea390c5636aea35c2

**Comment by Overtorment** [comment]
Thanks for reporting this!
I tried to investigate it but there's nowhere I could find payment hash `cbf4213fa35896c5ad4ab373605abd6445d7c259e67fb75a434ef8e080325951`: not in lnd sent payments, not in lnd logs, not in lndhub logs. It feels like your wallet account is not on default lndhub.
Can you pls send me your ln wallet export to i@bluewallet.io ?

PS. I fixed some doublespend  issues on Oct, 28 (in commit https://github.com/BlueWallet/LndHub/commit/53361d2e3ab07a2e7aaf22ead9e7c3819985f73a) I wonder if you can reproduce the issue, or even spend this while balance in Muun (I heard they do some funky business with channels, to the point I'm not even sure whether its custodial or non-custodial)

**Comment by Overtorment** [comment]
finally could find the only entry for this hash in logs:

```
$ cat /home/overtorment/.pm2/logs/run-lnd-* | grep cbf4213
2021-11-10 22:52:51.168 [WRN] CRTR: Attempt 364772 for payment cbf4213fa35896c5ad4ab373b05abd6445d7c259e67fb75a434ef8e080325951 failed: UnknownNextPeer@1
```

which says that the payment failed.
At this point it feels that the problem is on muun's side

**Comment by igoriokas** [comment]
OK, I have managed to send my full balance from muun to bluewallet, all went smooth.
So, bluewallet failed to send transaction, but the muun did received the funds.
As per your suggestion I will open an issue on the muun's side.

**Comment by igoriokas** [comment]
shall I close this issue here?

**Comment by Overtorment** [comment]
lets keep it open for now. pls let me know howsit going on muun's side.

**Comment by igoriokas** [comment]
Forwarded issue to the muun's team
https://github.com/muun/falcon/issues/14

**Comment by champo** [comment]
Hi! We've found and the fixed the issue on our node. Thanks @Overtorment for looking into it!
