### ISSUE TITLE
Bug: intent-filter for android deeplinks for Safello

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#4202]
apparently in : app/src/main/AndroidManifest.xml
![image](https://user-images.githubusercontent.com/1913337/141457626-09420398-cd4b-4d74-97f1-ff92713a74d6.png)

possible relevant docs:
https://developer.android.com/training/app-links/deep-linking
https://developer.android.com/guide/navigation/navigation-deep-link

**Comment by odniklas** [comment]
bankid://
swish://

are the two apps required to be whitelisted. The equivalent for iOS can be found at https://github.com/BlueWallet/BlueWallet/blob/f36f1d80141bff58dfca94e6722888534a24c14d/ios/BlueWallet/Info.plist#L133
