### ISSUE TITLE
Manage funds in LN wallet >> hard to find - not visible (orange on orange)

### ISSUE THREAD

**Issue by 2pac1** [BlueWallet/BlueWallet#4203]
<img width="211" alt="Screenshot 2021-11-12 at 16 36 38" src="https://user-images.githubusercontent.com/35058480/141493045-52c108b0-5b41-423f-8c49-6f254f9aa923.png">

When one creates a LN wallet, then he wants to top it up and send funds there.
It is super hard to find MANAGE FUNDS section as it is orange on the background orange.

Color should be changed of the MANAGE FUNDS or somehow make it more visible and intuitive and visible to the eye.

This leads to "How do I top up?"

**Comment by hrodrig** [comment]
Same issue in Desktop App, macOS, but "Manage Funds" and "Market" not found...

<img width="361" alt="Screen Shot 2022-03-15 at 10 30 28 AM" src="https://user-images.githubusercontent.com/105245/158400730-43dbbea5-9653-45f9-b09a-f5eaba9193b1.png">
