### ISSUE TITLE
Unable to create aab (android bundle)

### ISSUE THREAD

**Issue by Idan-Neeman** [BlueWallet/BlueWallet#4235]
Hello, I'm having a weird problem trying to create an aab file for android, since google play requires uploading apps in this format.
I execute the command:
`./gradlew bundleRelease`
but I get at the end of the process error:
`Unrecognized native architecture for directory 'lib/arm64'.`

If I try to build APK with:
`./gradlew assembleRelease`
It works without error, but it's not really helping me.
Someone can help me?

**Comment by Overtorment** [comment]
i dont think we have tried to build aab yet, right, @marcosrdz?
so pls let us know when you manage to fix it

**Comment by Idan-Neeman** [comment]
@Overtorment 
I just let you know that after long research the problem is the package react-native-tor...
if I remove this line:
`implementation files("../../node_modules/react-native-tor/android/libs/sifir_android.aar")`
from app/build.gradle
then the build success... but I guess then the tor will not work LOL

**Comment by Idan-Neeman** [comment]
Okay I got it :)
Need to back the Init function to make it work with react-native-tor:
https://github.com/Sifir-io/react-native-tor/blame/f7719a85a90bbdd6e8202764d84cedba47665084/android/src/main/java/com/reactnativetor/TorPackage.kt#L15

**Comment by Idan-Neeman** [comment]
The solution:
In TorPackage.kt (file) System.load("${ai.nativeLibraryDir}/libsifir_android.so"); to System.loadLibrary("sifir_android");
Then recreate the aar :)

**Comment by marcosrdz** [comment]
It appears that it is not a BlueWallet issue but an issue in one of our dependencies.
