### ISSUE TITLE
Multisig Provide signature button not scrollable

### ISSUE THREAD

**Issue by igoriokas** [BlueWallet/BlueWallet#4238]
**Environment**
* iPhone 12 mini, iOS 15.1
* BlueWallet app version 6.2.13
* self-test passes? yes
* electrum server: default

**Scenarion**
* Multisig 3 of 5 wallet
* Current iphone has only 2 keys
* Initiate spending transaction 
* No way to export PSBT to sign by the 3rd key
 Loos like the _Provide signature_ button is hidden below but not scrollable to

![image](https://user-images.githubusercontent.com/38182908/143491144-92fbb6f1-a903-4302-9651-8baab7e7d46b.png)

**Comment by igoriokas** [comment]
I think this issue is related to #4231

**Comment by igoriokas** [comment]
Was this one also solved by https://github.com/BlueWallet/BlueWallet/pull/4252 ?

**Comment by marcosrdz** [comment]
> Was this one also solved by https://github.com/BlueWallet/BlueWallet/pull/4252 ?

Thats correct
