### ISSUE TITLE
"View in Block Explorer" consistently fails

### ISSUE THREAD

**Issue by dleshem** [BlueWallet/BlueWallet#4244]
Clicking "View in Block Explorer" in transaction details screen consistently fails with

`Unable to open URL with the default browser. Please change your default browser and try again`

Phone model: Galaxy S21 5G (SM-G991U1)
OS version: Android 11
BlueWallet version: 6.2.13
Self-Test: OK
userId: 9ed1b6ddf257b209

**Comment by dleshem** [comment]
React Native's [Linking.canOpenURL](https://reactnative.dev/docs/linking#canopenurl) has this warning, which may be related:

> When targeting Android 11 (SDK 30) you must specify the intents for the schemes you which to handle in AndroidManifest.xml
>
> For example to handle `https` schemes the following needs to be added to your manifest:
>
>``` <manifest ...>```
>```    <queries>```
>```        <intent>```
>```            <action android:name="android.intent.action.VIEW" />```
>```            <data android:scheme="https"/>```
>```        </intent>```
>```    </queries>```
>``` </manifest>```

**Comment by Overtorment** [comment]
good catch!
will fix.
related: https://github.com/BlueWallet/BlueWallet/issues/4202

**Comment by dleshem** [comment]
This still consistently happens in 6.2.14 :(

**Comment by fabyeah** [comment]
Same problem :(
BW 6.2.17, Android 12

**Comment by eisenbruch** [comment]
This is still an. 6.2.17

**Comment by Marc-Gee** [comment]
Can this issue be re-opened? Its still a bug in 6.2.17 for many months now.

**Comment by Marc-Gee** [comment]
@Overtorment thank you very much!! I am hoping this bug is now truly dead!😃
