### ISSUE TITLE
Payment failed

### ISSUE THREAD

**Issue by Doweig** [BlueWallet/BlueWallet#425]
Hello guys, I'm launching my LN app today and finish up the last testings. I got all custodial wallets to work except for Bluewallet.
The error I get is "API Error: Payment failed. Does the receiver have enough inbound capacity?". 
![Screen Shot 2019-03-19 at 5 34 24 PM](https://user-images.githubusercontent.com/1850848/54599739-d495f980-4a6d-11e9-937d-8bf6cdca56bf.png)

Though my node has 11 channels as we speak, several well funded inbounds, including one of 2million satoshi to bitrefill (using their Thor service), which is very well connected.
Not sure what we can do from here, bitlum devs accepted to directly open an inbound channel with my node. Could you guys do the same?

My LND node for ref:
https://1ml.com/node/020d6989eaaf107a020501607aae8f489dd207cc495fbdd6b80eee14336ed3217c

Cheers!

PS: love bluewallet, personally use it on my phone.

**Comment by Overtorment** [comment]
Sure, will open direct.
Also, will debug a route, probably fee exceeds 1% for small test payments
(we have feelimit 1%)

**Comment by Doweig** [comment]
That's great. That 1% is smart, might be the issue yes.
Thank you

**Comment by Doweig** [comment]
Works now
