### ISSUE TITLE
Unable to delete a multisig wallet I imported from specter desktop

### ISSUE THREAD

**Issue by lvnilesh** [BlueWallet/BlueWallet#4255]
## Are you reporting a bug?

Yes

Please provide:

* your phone model and OS version

iPhone 13 Pro latest version

* BlueWallet app version (settings->about->scroll down)

6.2.13

## self-test

Passed OK

##  unique ID for our crash reporting service

userId:1B5A4B0C-EBCF-40FE-9FBF-63002BCC06B9

## ISSUE:

I exported a multisig from @SpecterWallet desktop & imported into @bluewalletio iOS. 

It appears the imported multisig is malformed.

![image](https://user-images.githubusercontent.com/93558/144087710-ee6e913e-3338-400c-8c05-27cd437d529c.png)

Now I can’t delete that imported multisig from BlueWallet no matter what I do. I deleted BlueWallet and app specific storage. Reinstalling BlueWallet brings back that multisig. 

![image](https://user-images.githubusercontent.com/93558/144087865-216d0b89-ea9e-483a-bde2-f64f46b62e6a.png)

I am able to delete other singlesig wallets from BlueWallet no problem.

**Comment by marcosrdz** [comment]
What happens when attempting to press Delete? Can you provide a video of the flow from start to finish(this gives us more details)

**Comment by lvnilesh** [comment]
It gets stuck on "attempting to delete" screen and does not actually get deleted. 

I delete app and delete any trace from iPhone and also iCloud.

I reinstall the app and this "broken" wallet reappears. 

Where exactly is the blue wallet app storing user generated data on an iPhone?

**Comment by Overtorment** [comment]
its in keystore.

if i remember correctly, to wipe the device you can encrypt storage, and then try to open the app with wrong password 10 times in a row, till it will offer to manually wipe all data.


can you provide steps to reproduce?
maybe create empty wallet wihouth funds in specter and post it here?

**Comment by lvnilesh** [comment]
ok I wiped. Thanks.

**Comment by moranda3** [comment]
> 

I have this same issue. How were you able to delete the wallet?
