### ISSUE TITLE
API error: not enough balance

### ISSUE THREAD

**Issue by SimonMcCabes** [BlueWallet/BlueWallet#426]
I was trying to pay an invoice for 0.0396 and had sufficient fund but kept getting above error. I kept adding more sats to see if it would got through. Once I had 0.04048631 it went through but for the wrong amount. It sent 0.039996 rather than 0.0396. Have all screenshots.

**Comment by Overtorment** [comment]
Thats fees

**Comment by ncoelho** [comment]
There was a bug on the fee calculation that affected some transactions. This is fixed already, thanks for reporting.
