### ISSUE TITLE
Question: Need help find code for detecting xpub

### ISSUE THREAD

**Issue by niteshbalusu11** [BlueWallet/BlueWallet#4267]
Hello! 

Could you please point me to the code where BlueWallet detects what kind of watch only wallet was imported based on the xpub entered. There are several types of xpub one can enter and I’m curious to see how BlueWallet detects the format of it and imports it accordingly. 
Is it based on the format of the xpub entered? I want to generate addresses from master pubkeys but a little lost on how to read the format and use the right derivation paths. 

Also, for derivation paths, as I understand one needs to change the number to generate a different address. What is the logic used to generate separate addresses everytime, please? 

Thanks!

**Comment by Overtorment** [comment]
i think this one https://github.com/BlueWallet/BlueWallet/blob/a36863432ea08114025cf439a7e8dfb520ba650a/class/wallets/abstract-wallet.ts#L272


we also have integration test for import procedure, might be worth checking out `tests/integration/import.test.js`

**Comment by niteshbalusu11** [comment]
Will check them out, thank you!
