### ISSUE TITLE
Invoice not paid and funds disappeared

### ISSUE THREAD

**Issue by SimonMcCabes** [BlueWallet/BlueWallet#427]
Had 0.00049031 in wallet and trying to pay 0.00020000 invoice. Got long API error message (have screenshot) and balance reduced by 0.000396 rather than 0.0002. No funds received at the other end.

API failure: Error 'originalResponse":
"type":"default","status":
503,"ok":false,"headers"{'map":
'cache-control":"no-cache,
no-store","content-type":"text/html;
charset utf-8","content-length": "506"
. "date":"Tue, 19 Mar 2019 08:08:29
GMT","server"."Cowboy","connection":
t "keep-alive"}};"url":"https://Indhub
herokuapp.com/getpending","
bodylnit":("_data":{"size":506,"offset":
0,"blobld":"d70373b9-ca37-4ef9
934d-9d02ceabc4e9"}},"_bodyBlob":
"_data":("size":506,"offset":0
"blobld":"d70373b9-ca37-4ef9-934d
-9d02ceabc4e9"}}},"err":}}

**Comment by Overtorment** [comment]
Payment is in transit, funds are locked. Sometimes it takes days for them
to unlock.
It is nit something immediately fixable.
