### ISSUE TITLE
the transaction was rejected by network rules

### ISSUE THREAD

**Issue by lucaszanella** [BlueWallet/BlueWallet#4279]
## Are you reporting a bug?

Please provide:

* Galaxy S21, Android 10
* BlueWallet app version 6.2.13
* self-test passes? yes
* unique ID for our crash reporting service (settings->about->scroll down, tap "copy")

When I try to transmit a transaction from my coldcard, I get:

**the transaction was rejected by network rules**

and then a large number (which I think is the transaction)

I have to sign multiple times until it works.

What is this error?

**Comment by lucaszanella** [comment]
Apparently it says "dust" and then a bunch of numbers. Just found out that it's rejecting because it thinks it's dust because the amount is too small. Should be good to put some prhase like "the ammount you're trying to send is too small and considered dust and for safety reasons is being rejected by the network"

**Comment by Overtorment** [comment]
also, could be too low fee.
we have a ticket to fix that: https://github.com/BlueWallet/BlueWallet/issues/4248

**Comment by lucaszanella** [comment]
My error specifically said "dust" though, so I think at least create a better message for the dust case
