### ISSUE TITLE
Funds did not arrive in my node

### ISSUE THREAD

**Issue by 22008** [BlueWallet/BlueWallet#428]
Hi today I made three payments from the blue wallet two of 10000 sats and one of 10 sats , the first two of 10000 sats confirmed as invoice paid but on my node they completed but zero sats arrived , I then tried sending 10 sats which also confirmed as invoice paid  but on this transaction the sats arrived in my node wallet . Where has my btc gone ?

**Comment by Overtorment** [comment]
If you saw success message (nothing about "payment in transit") then funds payment most definitely sent, problem is on the other end (your node). If you can send me your wallet export to i at bluewallet dot io I can look deeper into that

**Comment by 22008** [comment]
When you say wallet export do you mean from blue wallet?  And we’re exactly do I get that

**Comment by Overtorment** [comment]
open LN wallet -> options -> export

**Comment by 22008** [comment]
Ok

**Comment by 22008** [comment]
Can you give me the exact address to send it to

**Comment by Overtorment** [comment]
i at bluewallet dot io

**Comment by 22008** [comment]
Hi



Sent from Yahoo Mail for iPhone


On Wednesday, March 20, 2019, 11:30 pm, Igor Korsakov <notifications@github.com> wrote:

i at bluewallet dot io

**Comment by 22008** [comment]
I just sent the export address

**Comment by Overtorment** [comment]
Got nothing. Try again i@bluewallet.io
