### ISSUE TITLE
At 2nd step of sending, pressing the green fee amount at the bottom could let us edit the network fee. 

### ISSUE THREAD

**Issue by Transisto** [BlueWallet/BlueWallet#4284]
![Screenshot_20211210-154131_BlueWallet](https://user-images.githubusercontent.com/388716/145638646-c16335ac-4c94-481b-9dac-ed5c9c3c8cd6.jpg)

**Comment by marcosrdz** [comment]
This would require reconstructing the transaction. Said process is done on the previous screen. This Screen is meant to be a final preview prior to final broadcasting. @ncoelho  thoughts?

**Comment by Overtorment** [comment]
yeah, not doable. 
transaction is cunstructed on prev screen.
but the idea has merit

**Comment by Transisto** [comment]
> 

How is it not doable?, Clicking the fee would be just a combination of back and click fee option.

The address and the amount stay there.

BTW there is no $ amount on the fee until that last step.

**Comment by ncoelho** [comment]
If you use local currency it shows the amount on the step before. This is a confirmation screen, not an edit screen. You can confirm or go back to change.
