### ISSUE TITLE
App crashes when accessing sign/verify screen

### ISSUE THREAD

**Issue by TKone7** [BlueWallet/BlueWallet#4296]
## Are you reporting a bug?

Yes. Please provide:

* your phone model and OS version
Xiaomi Mi 9T Pro / Android 11 RKQ1

* BlueWallet app version (settings->about->scroll down)
6.2.14

* self-test passes? Open settings->about->scroll down, tap "Run self-test"
Succeeded

* unique ID for our crash reporting service (settings->about->scroll down, tap "copy")
userId:aa336f8b7309dc3f

### Reproduce bug
1. Select onchain wallet (with keys)
2. Tap three dots on the top right
3. Tap "Sign/verify message"
4. App crashes

### Expected behavior
Should show screen to sign a message.

**Comment by marcosrdz** [comment]
This was fixed on 6.2.15
