### ISSUE TITLE
Paddings and margins on tx detail view

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#43]
We have a problem on basically every view, regarding paddings and elements alignment in general. The new TX detail view is a small example were we can start fixing them.

We should use a 8px grid. In this specific situation padding should be 16px.

![photo5819062443173850794](https://user-images.githubusercontent.com/1238429/45505293-93eeb800-b78c-11e8-8f78-7142d014d765.jpg)

**Comment by Overtorment** [comment]
I think thats fixed already
