### ISSUE TITLE
Cryptographic APIs misuses

### ISSUE THREAD

**Issue by misterAnderson90** [BlueWallet/BlueWallet#4304]
I'm a PhD student interested in finding security vulnerabilities in open source projects.

We found a total of 29 warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on BlueWallet (or its library dependencies). We documented these issues in private gists for the sake of confidentiality (non-disclosure).

Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve BlueWallet's security, and the quality of the reports of static analysis tools.

(*) https://github.com/CROSSINGTUD/CryptoAnalysis

**Comment by Overtorment** [comment]
![image](https://user-images.githubusercontent.com/1913337/146811405-6f36d788-d5f5-4c44-8ac4-cb9ba1e76c39.png)

**Comment by misterAnderson90** [comment]
Hello @Overtorment,

I have sent the report by email. Please let me know whether you are interested in discussing the report and/or receiving all the issues.
