### ISSUE TITLE
Blank screen after importing wallet

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#432]
Reported on support

> 
The screen is just totally white like this. And nothing happened. I have tried to reinstall the software. Then I can open it. But if I reload my wallet using the memory word. It will become white screen again.

![image1](https://user-images.githubusercontent.com/1238429/55005403-3c06f880-4fdc-11e9-94f0-fc3d3b370a4b.png)

**Comment by Overtorment** [comment]
ypub wouldnt hurt. might be a crash due to super unexpected/nonstandard transaction
