### ISSUE TITLE
Slightly bigger application icon under macOS BigSur

### ISSUE THREAD

**Issue by greenchapter** [BlueWallet/BlueWallet#4334]
macOS 12.1 (21C52) running on M1
BlueWallet Version 6.2.15 (680)

## Description of the Bug

Steps to reproduce

1. Start the BlueWallet App under macOS BigSur on a M1 machine

Finally you will see the bigger app icon under the app switcher and the dock
<img width="252" alt="Screenshot 2021-12-30 at 21 17 30" src="https://user-images.githubusercontent.com/693276/147785686-00b6f16b-c8f6-4b63-9046-5358c5a40cb6.png">

**Comment by ghqe** [comment]
Same here

**Comment by Overtorment** [comment]
duplicate https://github.com/BlueWallet/BlueWallet/issues/5246
