### ISSUE TITLE
MacOS: Can't click anywhere within the app.

### ISSUE THREAD

**Issue by ulzeraj** [BlueWallet/BlueWallet#4362]
* OS: MacOS 12.1 Apple M1
* Version: 6.2.16 (685) from Apple Store
* self-test passes? Unable to run self tests
* unique ID for our crash: Unable to retrieve it

After typing in password I can't click anywhere on the window. Everything other than clicking works. Clicking on BlueWallet -> Preferences opens the preference Window but no item is clickable. Scrolling and swiping gestures works. I can also move the window.

PS: Connected to my own LND/LNDHub and Electrs node. iOS versions on iPad and iPhone connected to the same node and using same BIP/LN wallets works just fine.

**Comment by toothoptimism** [comment]
Work around: Open all of the menus in the menu bar. Then the UI becomes clickable.

**Comment by kukam** [comment]
Hi, I have the same problem on the same hardware and your work around is not working.

**Comment by Overtorment** [comment]
@marcosrdz

**Comment by marcosrdz** [comment]
Alert prompts seem to be unreliable with mac catalyst. This UI will need to be made into a local React component.It is being worked on

**Comment by Sea-Worker9552** [comment]
Workaround doesn't always work :(

M1 Pro MacBook Pro 14"

**Comment by tenfef** [comment]
Same thing is happening to me. Also happened after I enabled Encrypting the storage

**Comment by dirtymouse** [comment]
Is there going to be a solution to this problem? I just installed Blue Wallet on Monterey, imported a wallet. Did a signed transaction for a multisig. Now, after relaunching, the app is unclickable, unresponsive..

**Comment by Sea-Worker9552** [comment]
This is concerning how long this issue has been around. With infrequent releases one has to wonder if this wallet will be supported and if it's reliable enough to use for long term storage.
