### ISSUE TITLE
Trezor TaprooT XPUb sceme noT recognized by bluewalleT

### ISSUE THREAD

**Issue by allinfinite** [BlueWallet/BlueWallet#4376]
## Do you need support? Just email bluewallet@bluewallet.io

The scheme used by Trezor To exporT a TaprooT xpub is noT recognizing any addresses in bluwalleT
example
tr([5c9e228d/86'/0'/1']xpub***/<0;1>/*)

iOS 15.1.1 iPhone 12 pro
BlueWallet app version 6.2.16 
self-test passes? OK 
 unique ID for our crash reporting service
userId:3B813166-B7F5-4AF5-AD30-8E31A8D1A38B

**Comment by limpbrains** [comment]
BlueWallet doesn't support taproot yet #3880

**Comment by Overtorment** [comment]
we could for watch-only tho, as temporary hack until we implement send-from-taproot
