### ISSUE TITLE
The transaction was rejected by network rules. min relay fee not met

### ISSUE THREAD

**Issue by orfeas0** [BlueWallet/BlueWallet#4379]
When trying to send from P2PKH to a bc1 address, the fee options are: 

- Fast, 904 sats (4 sat/vByte)
- Medium, 226 sats (1 sat/vByte)
- Low, grayed out

Even worse, when selecting amount (to send) -> MAX, Medium fee option changes to 192.
The transaction fails to send with the following message:
```
Alert
the transaction was rejected by network rules.

min relay fee not met, 192 < 221 [.....................]
```

When sending with 226, I get the message:
```
Alert
the transaction was rejected by network rules.

min relay fee not met, 226 < 254 [.....................]
```

_Why does the minimum relay fee change?_
While writing this, I realized: a "use-all" transaction costs less to send because it has only 1 destination address, while a partial send has 2 destination addresses: the target, and the change address. Right?

_Most importantly, should bluewallet allow fees lower than the minimum relay fees?_

As a solution, I input a custom fee of 2 sat/vbyte, translating to 384 sats. _But is that what we want from the everyday user? Shouldn't the default fast/medium/low options all be acceptable?_

Tech Specs:
Galaxy Note 9, Android 10
Bluewallet ver 6.2.16.
Self-test passes OK.

**Comment by doc-hex** [comment]
I am seeing this issue too. Here's an example:

![IMG_35EA61B4777F-1](https://user-images.githubusercontent.com/1482781/152664489-fd8dd0c2-e5a4-4dc4-bcc4-38e77cfc48ca.JPEG)

**Comment by Overtorment** [comment]
thanks for reporting!
duplicated here https://github.com/BlueWallet/BlueWallet/issues/4248
