### ISSUE TITLE
Funds arrived but unspendable due to being flagged as unconfirmed even though they are confirmed 6 days ago.

### ISSUE THREAD

**Issue by viaj3ro** [BlueWallet/BlueWallet#438]
I send 0.01 BTC from mycelium to my BlueWallet Segwit HD account and they show up but only with 0 conf. They are confirmed since 23.03. and even the linked blockexplorer confirms this.

What now?

**Comment by ncoelho** [comment]
Hi there,

- Can you share the link to the explorer?
- Can you refresh your wallet, with a pull to refresh inside the wallet.

Thanks

**Comment by viaj3ro** [comment]
refreshing did help. got stuck a couple times and had to restart the app but after waiting for a minute or two it finally worked.

For usability would be good to have an automatic refresh after a restart.

For sending it would be nice to have a "send all" option after selecting the fee. It's quite complicated to manually deduct the fee from the sending amount.

**Comment by missaghi** [comment]
Same use, day old transaction but wallet shows zero balance https://share.icloud.com/photos/0zTzMrBiCUHybpRoezF3bloSw

**Comment by Overtorment** [comment]
@missaghi looks like connectivity issue. can you open settings->about->run self test and tell if there are any errors there..?
also, make sure youre on the latest build, I did some fixes on that part in recent release

**Comment by missaghi** [comment]
Thanks for looking into it. Because it's great that you show private key I was able to recover funds but they never did update the zero balance. Self test failed.



Thanks! 
Riaz
