### ISSUE TITLE
Channels screen keeps loading on iOS (LDK)

### ISSUE THREAD

**Issue by EZ0010** [BlueWallet/BlueWallet#4382]
When you go to channels screen on iOS it keeps loading and gray out the "New channel" button.

I found a weird solution for it:
turn off wifi
open BlueWallet
it will show an Alert (LDK init error: Network request failed)
click ok and turn on wifi again
new channel button will not be grayed out

**Comment by Overtorment** [comment]
@marcosrdz can you pls look into it?

**Comment by EZ0010** [comment]
I can provide logs if you aren't able to reproduce the issue.

**Comment by EZ0010** [comment]
issue seems to be solved I will close it
