### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by EZ0010** [BlueWallet/BlueWallet#4385]
when running `npx pod-install` everything goes without issues but it shows error at last step:

```
[!] Unable to install vendored xcframework `LDKFramework` for Pod `rn-ldk`, because it contains both static and dynamic frameworks.
```

**Comment by Overtorment** [comment]
@marcosrdz

**Comment by marcosrdz** [comment]
Remove your node_modules folder. You might have an old LDKFramework in there.

**Comment by limpbrains** [comment]
> Remove your node_modules folder. You might have an old LDKFramework in there.

I have the same issue. rm -rf node_modules doesn't help
