### ISSUE TITLE
Loss of Fund: BTC wallet replaced by a new empty one

### ISSUE THREAD

**Issue by jsappme** [BlueWallet/BlueWallet#440]
Yesterday i send some btc to this wallet https://www.blockchain.com/btc/address/34sHz7xb2WcAHvbTZHM8p72QGyy4SMRvmU
This was the wallet address of the one shown on the app as my BTC wallet.
I could see the transaction on the list but not confirmed yet.

Today I come back to the app and I see a new BTC wallet https://www.blockchain.com/btc/address/3QsZHiyyG6BH3hsF5mywMpSYA8aXntp5wE

And my old one is completely gone.

Any idea how to recuperate those funds?

**Comment by Overtorment** [comment]
Are you using HD wallet? That means that there are many addresses in
hierarchy, and once address is used, it shows new address to receive.
Funds should be visible though. You can doublecheck if you take XPUB from
the wallet and search it on
https://www.blockonomics.co

**Comment by jsappme** [comment]
thanks for your reply. Yes it's the Btc HD.

here it is: https://www.blockonomics.co/#/search?q=ypub6XDh6mPizN9YLz2P9W2WxvUvCRCavnwvsQxtxmP9hJ9GbBReyMm9CU7L1oQjaN6aMvqSXjnpTPitwNDaDbg1RSTLmq4WsGjHE1GSqtKjbaE

my balance is still at 0 on the app though.

**Comment by ncoelho** [comment]
Try to refresh, there’s connectivity issues. Pull to refresh inside the
wallet till it works.

The wallet public address shows funds there

**Comment by jsappme** [comment]
![55811480_1414876738654291_2150090371026124800_n](https://user-images.githubusercontent.com/13439477/55250737-81ae0600-5214-11e9-8921-3d3cb97388a7.png)

i tried refreshing many times. now i see duplicates of my tx. but still balance at zero.

**Comment by jsappme** [comment]
Funds arrived finally.
