### ISSUE TITLE
Reorder wallet is clunky to use. 

### ISSUE THREAD

**Issue by Transisto** [BlueWallet/BlueWallet#4405]
I was able to move a wallet up a notch but it seems like it was by luck.

Spend 2-3 min on this and I don't understand what how it's meant to be used.

There's no distinction between scrolling the page and moving the wallet, usually there's a three dot (burger) that you know you can hold onto.

**Comment by kirkawolff** [comment]
On Android 9 I have a slightly different experience. I can move a wallet up or down fairly easily, but only by two or three at the most and only if I place the wallet I want to move near the bottom or top of the screen and drag it the opposite direction. Then I can consistently move it three spaces. 

My preference is that when you drag it up, it will continue to move up the list off-screen, but 'hop' one wallet at a time every quarter or third second so you can have time to let go when its in-place.
