### ISSUE TITLE
Stop iOS App from Opening Files from Files App

### ISSUE THREAD

**Issue by ghanbak** [BlueWallet/BlueWallet#4429]
Idk what’s going on but when I try to open a PDF from my files app, the wallet app opens. This is shady AF!

**Comment by marcosrdz** [comment]
<img width="656" alt="Screen Shot 2022-01-27 at 11 22 09 AM" src="https://user-images.githubusercontent.com/4793122/151399981-012e74df-6e8f-4c51-8729-536f5b97b9d2.png">

**Comment by marcosrdz** [comment]
The app has no knowledge of PDFs. My previous comment shows the list of files BlueWallet accepts.

**Comment by obiordu** [comment]
Same thing happened to me 😭 , downloaded TLCL-19.01.pdf from https://sourceforge.net/projects/linuxcommand/files/TLCL/19.01/TLCL-19.01.pdf/download and it opened bluewallet

Not sure what is going on

**Comment by marcosrdz** [comment]
> Same thing happened to me
> 
> 
> 
> Not sure what is going on

Can a screen recording of the whole process be provided? The code base has zero references to PDF files.

**Comment by obiordu** [comment]
Too scared to run again,

happened twice on Android,

deleted bluewallet, deleted the downloaded file and just got antivirus app to run scan,

So far scan came back clean, for now keeping fingers crossed.

**Comment by intercoarse** [comment]
Came across this because I Googled when this happened to me just now.

Tried opening a text file in Files app. The text file was saved from a shared Note. It tried to open, screen went black, then BlueWallet app opened. 🧐 Now sometimes the text file opens, sometimes BlueWallet opens.. 

Running ios 15.6.1

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/5029
