### ISSUE TITLE
LNURL Payment UI has 7 BTC decimals

### ISSUE THREAD

**Issue by tlindi** [BlueWallet/BlueWallet#4446]
## Are you reporting a bug?

Please provide:

* your phone model and OS version
Nokia 6.1 Android 10

* BlueWallet app version (settings->about->scroll down)
Latest

* self-test passes? Open settings->about->scroll down, tap "Run self-test"
Likely yes
* unique ID for our crash reporting service (settings->about->scroll down, tap "copy")
No crash
## Proposing a feature?
Yes, fix bug

Invoice / product price on BTCPay was Set to 0.01€ ~30sat today.

BlueWallet UI uses only 7 decimals so payment never matches exactly to invoice sat amount.

![Screenshot_20220131-172212](https://user-images.githubusercontent.com/7249767/151821807-1ef5839a-0e55-43d1-b1cd-8e935bbb8659.png)

**Comment by Overtorment** [comment]
i dont see an issue here. you mentioned 30 sat? 
thats exactly 0.0000003 BTC (or 0.00000030 BTC if you wish)

can you share a specific invoice or a shop youre paying so maybe i can reproduce the problem myself?

**Comment by tlindi** [comment]
I Will Make invoice and get Back.

**Comment by tlindi** [comment]
Case was that BTCPay 0.01€ invoice was shown as 31sats. But on BlueWallet as 30sat. But invoice min and max payments were 31sat. And it was impossible to pay. I retried it with bigger amounts with similar results. 

But... Err.. I cannot reproduce issue anymore :-/
