### ISSUE TITLE
Dark Mode on Android 11 prevents other Apps (including BlueWallet) to read the QR-Codes!

### ISSUE THREAD

**Issue by pjw65** [BlueWallet/BlueWallet#4458]
Xiaomi Mi Note 10 Lite
Android 11 (MIUI Global 12.5.5)
BlueWallet 6.2.17
self-test passes? Yes

Reproduce:
- Phone Settings / Display / Dark Mode

QR-Codes (i.e. Wallet Address) are displayed inverted and can not be read even with another BlueWallet App.

Workaround : 
- Phone Settings / Display / Other Dark Mode Options 
- exclude BlueWallet from Dark Mode

**Comment by marcosrdz** [comment]
QRCodes have a white border when the device is on dark mode. This allows cameras to read the QRcode.

**Comment by pjw65** [comment]
> QRCodes have a white border when the device is on dark mode. This allows cameras to read the QRcode.

Not on my phone (Xiaomi) with the default Dark Mode settings.
Only when I choose to exclude BlueWallet like here: 

![Screenshot_2022-02-06-15-43-17-909_com android settings](https://user-images.githubusercontent.com/869541/152686578-daa41178-275f-4941-8cf7-e61843aa63e1.jpg)

**Comment by marcosrdz** [comment]
If possible, please provide a screenshot of a bluewallet QR Code in dark mode

**Comment by pjw65** [comment]
![Screenshot_2022-02-06-15-41-58-640_io bluewallet bluewallet](https://user-images.githubusercontent.com/869541/152691911-a309ef8c-1c8c-4e7c-abe6-395b61c4031c.jpg)

**Comment by pjw65** [comment]
I think the problem is, that the default dark mode settings on my phone are, that for all apps in the beckground and text ist automaically changed (germen text of 2nd slider, see abover).

**Comment by marcosrdz** [comment]
I can see a slight border. But its too dim. What the result if you kill the app, have dark mode enabled, then reopen the app, and go to this same screen?

**Comment by marcosrdz** [comment]
Ok I think I know what's going on. I have opened a pull request with the suspected fix.  An APK will be created inside that pull request. If you are able to, please test that APK to see if it fixes the issue.

**Comment by pjw65** [comment]
After installing adb, uninstalling BlueWallet 
(because of: adb: failed to install app-release.apk: Failure [INSTALL_FAILED_UPDATE_INCOMPATIBLE: Package io.bluewallet.bluewallet signatures do not match previously installed version; ignoring!]
I could install it with: $ adb install app-release.apk

It looks still the same. No white border if the App is included in the list, white border if I uncheck the app. 
Also no white border if app is included, but the two slider above are unchecked (change wallpaper, change text and backgrounds automatically).

![Screenshot_2022-02-06-19-12-22-235_io bluewallet bluewallet](https://user-images.githubusercontent.com/869541/152695419-8c3497c0-cdc3-491a-a1dd-655dc6ba3409.jpg)

**Comment by pjw65** [comment]
https://geektech.me/miui-12-5-broke-dark-mode-in-popular-apps-xiaomi-wont-be-able-to-fix-the-problem/
MIUI 12.5 broke dark mode in popular apps - Xiaomi won't be able to fix the problem

Seems to be a problem of MIUI 12.5 (and later?). 
Can we give future users a help (in the FAQ or Message in app), that they have to exclude BlueWallet in Display/Other Dark Mode Settings?
Because the difference of Default Dark Mode and Dark Mode + exlude App is only the QR-Codes. Everything else will be in Dark Mode and readable anyway.

**Comment by marcosrdz** [comment]
> https://geektech.me/miui-12-5-broke-dark-mode-in-popular-apps-xiaomi-wont-be-able-to-fix-the-problem/
> 
> MIUI 12.5 broke dark mode in popular apps - Xiaomi won't be able to fix the problem
> 
> 
> 
> Seems to be a problem of MIUI 12.5 (and later?). 
> 
> Can we give future users a help (in the FAQ or Message in app), that they have to exclude BlueWallet in Display/Other Dark Mode Settings?
> 
> Because the difference of Default Dark Mode and Dark Mode + exlude App is only the QR-Codes. Everything else will be in Dark Mode and readable anyway.
> 
> 

This seems to be a specific issue to those devices. I recently tested it on an older device from Xiaomi (with Android 10) and it had the same issue. 
Closing since this is not a BlueWallet issue, but a Xiaomi issue.

**Comment by marcosrdz** [comment]
![image](https://user-images.githubusercontent.com/4793122/152704560-0eb3aedb-0ee3-4acf-ad0b-a1eb507683e3.jpeg)![image](https://user-images.githubusercontent.com/4793122/152704561-8b743837-6401-49d8-84d3-a1a73cc1e464.jpeg)
