### ISSUE TITLE
importing xpub will create a legacy(should be native segwit) wallet with derivation m/84'/0'/0'

### ISSUE THREAD

**Issue by odudex** [BlueWallet/BlueWallet#4472]
I'm working on Krux air gapped signer compatibility with Blue.
If I import a zpub to create a watch only wallet it works fine, by creating it with native segwit addresses for m/84'/0'/0' derivation.
However if I import a xpub it will create a legacy wallet with m/84'/0'/0' derivation and "unrecoverable" addresses

**Comment by limpbrains** [comment]
Can you share an example?

**Comment by odudex** [comment]
The case was. I had a seed loaded on may air-gapped device. I would like to import  this in Blue as a watch-only wallet.
My device exported a xpub QR code which contained a master fingerprint, derivation and the xpub.
If you wish you could try yourself scanning [this](https://photos.app.goo.gl/eFYC8BQc3NjQ8cfJA)
Blue seems to chose the Script type under the hood, it does use the given derivation (m/84'/0'/0') but instead of creating a native segwit, it creates a legacy wallet(P2PKH), with addresses starting with 1... instead of bc1q...
Sorry I'm new to this, but I think it should pick native segwit script(P2WPKH) when this derivation is given.
If I use the zpub, Blue does pick P2WPKH and works as I expected

**Comment by Overtorment** [comment]
to make watchonly use bc1 addresses, supply zpub instead of xpub

**Comment by odudex** [comment]
Sorry, I learned now xpub is usually used for legacy. So is my device that should use /44/0/0 derivation. Thanks
