### ISSUE TITLE
When connecting to personal instance of LndHub claims invalid URI

### ISSUE THREAD

**Issue by CaptJakk** [BlueWallet/BlueWallet#448]
Title says it all. When I go to lightning settings and manually set the URI of the copy of LndHub that I'm running, it claims that every sane version of the URI (trailing slash, no trailing slash, http, https, no protocol prefix) is "Not a valid LndHub URI". Has this issue been encountered before?

**Comment by Overtorment** [comment]
It also makes a request to test that lndhub instance is valid, that might
be the case. Is it working..?
You can try putting link to a default lndhub (the one on herokuapp) and see
that it is accepted ok.
Some folks use own Lndhub and this is the first time its reported.

**Comment by CaptJakk** [comment]
The lndhub at heroku seems to work.

When I navigate to my lndhub route /, it gives the same structural output as the heroku one. The only difference is that mine isn't being served over https, however it seems that I can't get lndhub to serve over https directly either.

I got lndhub from master today
lnd is 0.5.2-beta

**Comment by CaptJakk** [comment]
it seems that lndhub is giving a `{"error":true,"code":1,"message":"bad auth"}` response on getinfo. This seems to be related given the query that bluewallet makes. Have you seen this before?

**Comment by Overtorment** [comment]
This is actually expected. BW checks exactly for json response with bad
auth code.
Will refer source a bit later

**Comment by Overtorment** [comment]
https://github.com/BlueWallet/BlueWallet/blob/master/screen/settings/lightningSettings.js#L40
https://github.com/BlueWallet/BlueWallet/blob/master/class/lightning-custodian-wallet.js#L561

seek the problem in connectivity between phone and server

**Comment by Overtorment** [comment]
code === 1 to be specific
