### ISSUE TITLE
Receive BTC does not work

### ISSUE THREAD

**Issue by wdey** [BlueWallet/BlueWallet#451]
Blue Wallet on IOS; sent 3 mBTC to receive address. Can verify with browser and see 6 confirmations; however, nothing appears on my iPhone. Try to reboot ! no success. 
tx id 2b5943c8aac7aaaa593fbdd53c48e2d1c8f254fae2eb2fc1945cff867c4b0e8c

**Comment by wdey** [comment]
I didn't create yet a LN wallet; after doing that, I could see my BTC tx !

**Comment by Overtorment** [comment]
Should be network connectivity issue. Bluewallet uses public electrum servers, which might sometimes go down. Or just slow. We are working on improving that.

@ncoelho can you add this to our help portal..?
