### ISSUE TITLE
Feature: LNAuth support for lndhub wallets

### ISSUE THREAD

**Issue by kirkawolff** [BlueWallet/BlueWallet#4527]
Alby (a browser plugin) supports LNAuth from lndhub wallets, this is very useful. The problem is when you want to access a site that you have an account set up with LNAuth but from your phone. There is no way to do this since each LNDHub wallet will have a different key pair (I presume), so you can't use a different wallet that accesses the underlying LND wallet directly to generate a LNAuth signature. Either Bluewallet could provide a mechanism sign an authorization token in the form of a pasted lnurl or scanned lnurl QR, or it could support LNAuth through its LApp browser.

https://coincharge.io/en/lnurl-for-lightning-wallets/
https://github.com/fiatjaf/lnurl-rfc

This appears to be where Alby is processing the lnurl and executing signMessage()
https://github.com/getAlby/lightning-browser-extension/blob/4a8d6336acdbdd2a0848426d404cf79a71f7404b/src/extension/background-script/actions/lnurl/index.ts#L45

This appears to be where Alby implements signMessage() for lndHub
https://github.com/getAlby/lightning-browser-extension/blob/4a8d6336acdbdd2a0848426d404cf79a71f7404b/src/extension/background-script/connectors/lndhub.ts#L153

It appears master of Bluewallet was recently updated with support to lnAuth, so maybe this ticket isn't necessary? 

https://github.com/BlueWallet/BlueWallet/pull/4315

Leaving this open for a list of potential features as there is no documentation on how this feature was implemented from the user's point of view

**Comment by Overtorment** [comment]
yes, lnauth was merged in https://github.com/BlueWallet/BlueWallet/pull/4493
yes I suspect implementation is different from Alby, so signing in BW and Alby (with the same lndhub account) will actually yield different accounts on the website.

**Comment by bumi** [comment]
Actually I have just created an issue in Alby to update our key generation to be compatible with the recent addition in BlueWallet: https://github.com/getAlby/lightning-browser-extension/issues/629
This then should allow people to login into the same lnurl-auth accounts with BlueWallet and Alby.

**Comment by kirkawolff** [comment]
> yes, lnauth was merged in #4493 yes I suspect implementation is different from Alby, so signing in BW and Alby (with the same lndhub account) will actually yield different accounts on the website.

Is there any documentation or explanation of the UX journey (use case, screenshots, etc) for this feature on Bluewallet?

**Comment by Overtorment** [comment]
closing as implemented

**Comment by kirkawolff** [comment]
@Overtorment is there any documentation for this feature?

**Comment by Overtorment** [comment]
only the code + lnurl-auth spec. and i think there was a demo video somewhere
