### ISSUE TITLE
Transfer to LN wallet: Return doesn't show up in BTC wallet 

### ISSUE THREAD

**Issue by wdey** [BlueWallet/BlueWallet#453]
Transferred 3 mBTC to BTC wallet; then Refill LN wallet with 2 mBTC. Although the tx shows 1 input (3mBTC) and 2 outputs (2mBTC) and 0.00099496 mBTC; my BTC wallet balance is 0.0 ? What's wrong here ?

**Comment by ncoelho** [comment]
Hi there, there are problems reaching electrum servers at the moment, should be related with the Ddos attack going on.

We are looking into it.

**Comment by wdey** [comment]
Thanks for your help !
see https://cointelegraph.com/news/electrum-faces-another-fake-wallet-attack-users-reported-to-lose-millions-of-dollars?utm_source=newsletter1&utm_medium=email

**Comment by wdey** [comment]
Still no progress ! I can hardly believe that this is related to Ddos. It's more a feature of this custodial concept.

**Comment by ncoelho** [comment]
Update to android just went out. iOS still pending.

https://twitter.com/bluewalletio/status/1115989428730724353

**Comment by Overtorment** [comment]
Btc wallets are non custodial. Send me xpub so i can take a look.
If your issue is with ln wallet - send me this wallets backup, ill debug.

**Comment by wdey** [comment]
Hi Igor

Don’t ask me why ? I was horsing around, turning off / on my iphone. And in case you don’t believe me, I by accident did made screen shot, we show this miracle.

[cid:image001.png@01D4F065.DC775C00]

[cid:image002.png@01D4F066.2E2CDED0]

I don’t see a refresh button? Do I miss something ?

Cheers Walter.





Von: Igor Korsakov <notifications@github.com>
Gesendet: Mittwoch, 10. April 2019 17:03
An: BlueWallet/BlueWallet <BlueWallet@noreply.github.com>
Cc: wdey <wdey@bluewin.ch>; Author <author@noreply.github.com>
Betreff: Re: [BlueWallet/BlueWallet] Transfer to LN wallet: Return doesn't show up in BTC wallet (#453)

Btc wallets are non custodial. Send me xpub so i can take a look.
If your issue is with ln wallet - send me this wallets backup, ill debug.

**Comment by Overtorment** [comment]
I dont see any images.

Just fyi, there is no refresh button. Refresh is made by pull-to-refresh

**Comment by wdey** [comment]
See attachments

I have another issue: I can send from ZAP and Éclair full node wallet to Bluewallet without problems.

However from Blue to ZAP resp. Éclair always fails with the error: API error: Payment failed…receiver have enough inbound capacity ? Code 10.

My Éclair has enough inbound/outbound balance !

Von: Igor Korsakov <notifications@github.com>
Gesendet: Donnerstag, 11. April 2019 13:01
An: BlueWallet/BlueWallet <BlueWallet@noreply.github.com>
Cc: wdey <wdey@bluewin.ch>; Author <author@noreply.github.com>
Betreff: Re: [BlueWallet/BlueWallet] Transfer to LN wallet: Return doesn't show up in BTC wallet (#453)


I dont see any images.

Just fyi, there is no refresh button. Refresh is made by pull-to-refresh
