### ISSUE TITLE
Feature request: allow users to specify mempool.space instance

### ISSUE THREAD

**Issue by tylerchambers** [BlueWallet/BlueWallet#4562]
I run my own mempool.space instance, and would like to be able to use it as the block explorer in blue wallet. 
I think it would make sense to add an option to specify a mempool.space instance under the "network" tab, next to the "Electrum Server" options.

I have some react native xp, and am interested in implementing this. If this sounds OK to you guys, I'll take a crack at it some time this week.

Cheers.

**Comment by orangesurf** [comment]
I would also use this feature.

**Comment by bota87** [comment]
Me too

**Comment by fjriosp** [comment]
It could be a privacy improvement.
