### ISSUE TITLE
pdf file opened bluewallet 

### ISSUE THREAD

**Issue by obiordu** [BlueWallet/BlueWallet#4569]
downloaded TLCL-19.01.pdf (the Linux command line book by William shotts) from
https://sourceforge.net/projects/linuxcommand/files/TLCL/19.01/TLCL-19.01.pdf/download
and it opened bluewallet

Not sure what is going on.

**Comment by limpbrains** [comment]
is it on iOS or Android?

**Comment by obiordu** [comment]
Too scared to run again,

happened twice on Android,

deleted bluewallet, deleted the downloaded file and just got antivirus app to run scan,

So far scan came back clean, for now keeping fingers crossed.

downloaded TLCL-19.01.pdf (the Linux command line book by William shotts) from https://sourceforge.net/projects/linuxcommand/files/TLCL/19.01/TLCL-19.01.pdf/download

**Comment by marcosrdz** [comment]
> Too scared to run again,
> 
> happened twice on Android,
> 
> deleted bluewallet, deleted the downloaded file and just got antivirus app to run scan,
> 
> So far scan came back clean, for now keeping fingers crossed.
> 
> downloaded TLCL-19.01.pdf (the Linux command line book by William shotts) from https://sourceforge.net/projects/linuxcommand/files/TLCL/19.01/TLCL-19.01.pdf/download

Hello! A code fix for this was submitted for review. It was simply a wrongly formatted acceptance list for allowing the app to open (nothing else but simply open). This PR will fix the issue. Thank you!
