### ISSUE TITLE
Support for non-English mnemonic import

### ISSUE THREAD

**Issue by Kexkey** [BlueWallet/BlueWallet#4598]
Hello!  Looks like BlueWallet only supports importing English (bitcoinjs-bip39's default) mnemonic words.

With the BRD end-of-life, I was referring people to BlueWallet but unfortunately it doesn't work (most people here in Quebec set their device to French language).  It is not really possible to "convert" the mnemonic words from one language to another, since the literal 12-word string is used to derive the seed.

I know having the 2048 words for each language takes unnecessary space, so I guess dynamically download the list using the device language could be a solution.

Thanks for your amazing work!

**Comment by limpbrains** [comment]
Does BRD offers you non-english mnemonic if you are using non-english system language?

**Comment by Kexkey** [comment]
Yes, BRD automatically sets its language to the system one, but on iOS you can choose a per-app language in the settings.  I don't know how it behaves if we change the language after the wallet creation.  Unfortunately, the BRD team has deactivated the wallet so it's not possible to use it and so I cannot test it.

**Comment by limpbrains** [comment]
BRD supports not so many languages
https://github.com/breadwallet/brd-mobile/tree/main/brd-android/app-core/src/main/assets/words

We can do this.
PS 
I thinks it is possible to convert the seed. Even the last word represend sequence of bytes, nothing more

**Comment by Overtorment** [comment]
i think our bip39 npm dep already ships wordslist for all major langs

**Comment by Kexkey** [comment]
Hi @Overtorment!  It looks like the default (English) one is used (which makes sense most of the time btw)…

https://github.com/BlueWallet/BlueWallet/blob/master/class/wallets/abstract-hd-wallet.ts#L84

This said, I am not much familiar with the code.  In the app, I tried to enter French words and it didn’t recognize them.

**Comment by Kexkey** [comment]
“Fun” fact: It’s kinda ironic that in the bip39 spec, they discourage the use of non-English wordlists but one of the bip authors is also the author of BRD :)

https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#wordlists

**Comment by Overtorment** [comment]
iirc, spec guidance is in case of unrecognized wordlist app should complain, throw some notice but still use provided mnemonics. it just hashes the string anyways, right?

**Comment by limpbrains** [comment]
> it just hashes the string anyways, right?

in case of electrum - yes, in case of bip39 it is predefined vocabulary.

**Comment by GitTankMusic** [comment]
The same problem, BRD closed down, now I only have 12 BRD non-English mnemonic, don't know what to do, need help

**Comment by Kexkey** [comment]
Amazing!  You rock!
