### ISSUE TITLE
Lightning invoice details

### ISSUE THREAD

**Issue by thisconnect** [BlueWallet/BlueWallet#462]
I need to find out the transaction id. There is no information about a lightning transaction all it says is:

"This invoice has been paid for"

Is there any way to see the transaction id of a lightning transaction?

**Comment by Overtorment** [comment]
Ok, adding this as TODO for me. Finished transactions for LN should provide more info for people who really need them.
Meanwhile you can email me your LN wallet backup and point out which TX you want details for.

i at bluewallet dot io

**Comment by thisconnect** [comment]
thanks, sent the LND export QR code with a screen shot. 

I couldn't copy the LND wallet export to clipboard.

**Comment by Overtorment** [comment]
replied to your email

**Comment by thisconnect** [comment]
hm.. somehow I did not get any reply.
you can paste the 2 tx id's here, if it is not a problem

**Comment by Overtorment** [comment]
Have you checked spam folder..?


```
- 193147 Thu Apr 18 2019 14:32:03 GMT+0100 (British Summer Time) Bitrefill 5cb87c53cac37c0004c46d9a ; preimage: cd9e10e5621276d2946fe898ef0fde061e52a1d33b182c2f04d40f3e832c4114
- 193934 Thu Apr 18 2019 15:14:23 GMT+0100 (British Summer Time) Bitrefill 5cb8863f8bcd6a0004fb3aee ; preimage: 8de748874c6812d79015e2e4b4ac20eb24ff1f5c7e7726eaf71206e3946af3a0
- 1332385 Fri Apr 19 2019 08:48:59 GMT+0100 (British Summer Time) GloBee ; preimage: af7a52982612c28bb2d38989797e9ebbf6378fb3201adfa6197bec9cddc7547d
```

**Comment by thisconnect** [comment]
yes, I double checked. Not sure, why protonmail didnt receive it. Thanks I copied the tx id's.

**Comment by thisconnect** [comment]
thank you

**Comment by ncoelho** [comment]
Already in production, on the tx list for now. If you tap for a bit it will
expand to show all the content

**Comment by thisconnect** [comment]
ios switzerland ist still the old "This invoice has been paid for" 
maybe it takes a while for the app store to update everywhere?

**Comment by ncoelho** [comment]
Appears on the list, not inside.
