### ISSUE TITLE
bad master fingerprint from coldcard - 00000000

### ISSUE THREAD

**Issue by raytorres280** [BlueWallet/BlueWallet#4641]
## Are you reporting a bug?

* M1 Macbook Air 2020 macOS Monterey 12.3.1 (21E258)
* Version 6.2.18 (701)
* OK
* userId:6C2C2A7D-E918-567D-A9D1-2687D42717C5

Coldcard firmware: 4.1.3

When importing electrum wallet json file from coldcard I get an invalid master fingerprint. importing the same json file to electrum client does work without any changes.

**Comment by raytorres280** [comment]
My SD card is plugged in.Does BlueWallet still write to original file location while SD card is still plugged in? as ckcc_xfp in keystoree seems to be removed when I check back after the transaction has completed. And it looks like thats required to generate the master fingerprint in abstract-wallet.ts. At least for ColdCard judging by the comment on line 243. 

After the file gets rewritten I would imagine it hits the else-if on 245, which might not be what we want for a ColdCard? Still trying to figure out when the file is getting updated. Seems like when loading the list of transactions maybe? 

What confuses me is why the SD card file is being written to while plugged in, since a Bluewallet wallet import seemingly stores the wallet json to local storage as I can still access my wallets while SD card is removed.

**Comment by raytorres280** [comment]
for anyone else from google. If you use electrum alongside BlueWallet in any way, Electrum will write to the wallet.json export from your hardware wallet. Electrum changes the keystore values upon being loaded and writes to the original file if you don't make a copy. 

If you tried to load that same file now, which still works on electrum without issue, BlueWallet has trouble as Bluewallet tries to use the ckcc_xfp value in the keystore. Since Electrum removes this value, BlueWallet cannot follow normal procedure.

Could  we add logic to read the value ckcc_xfp is replaced with? Which is root_fingerprint.

steps to reproduce: 

1. First, open electrum client using your hardware wallet's SD card export. the JSON should be written to and keystore updated.
2. Now if you try to import that modified wallet export, the file gets imported correctly, all your transactions read, but when trying to sign an airgapped transaction you will get an error. If you inspect the wallet details screen by pressing the '...' button in the specified wallet, you can see that your master fingerprint is 00000000.

original coldcard export
`
"keystore": {
        "ckcc_xpub": "...",
        "derivation": "m/XX'/X/X'",
        "hw_type": "coldcard",
        "label": "Coldcard Import ABC123AB",
        "root_fingerprint": "abc123ab",
        "type": "hardware",
        "xpub": "asdfasdf..."
    }
`

electrum client modified keystore
`
"keystore": {
    "ckcc_xpub": "...",
    "xpub": "...",
    "label": "Coldcard Import ABC123AB",
    "ckcc_xfp": 123456789,
    "type": "hardware",
    "hw_type": "coldcard",
    "derivation": "m/XX'/X/X'"
  }
`

**Comment by raytorres280** [comment]
Trying to fix this myself currently but keep get SHA validation errors for npm install step sadly.

**Comment by Overtorment** [comment]
i dont get at what point the fp gets lost.
we have a bunch of example wallet exports in `tests/unit/fixtures/` and unit tests that test against them.

**Comment by raytorres280** [comment]
I sadly never got this working in debug configuration for react native. release configuration I can run locally. I am on latest electrum. I would expect it to still work as well since AppStorage still searches for root_fingerprint on line 245 of abstract-wallet.ts. 

m1 is just giving me problems getting setup with project.

**Comment by raytorres280** [comment]
skeleton-electrum.txt is basically what my wallet file gets transformed into after being used by electrum. Not sure what difference is. I have run same unit test against my wallet locally and do manage to get it to error with my wallet. 

It looks getMasterFingerprintHex() in watch-only-wallet.js is only working correctly for number types. My root_fingerprint for the wallet I am having my issue for is an alphanumeric string value.

**Comment by raytorres280** [comment]
I think setSecret() needs to be updated, unless the data in my wallet is somehow corrupt. There is some bad formatting going on with some parsing of file.

Still searching for root cause

**Comment by raytorres280** [comment]
turns out root_fingerprint was only being handled as a number. I personally have not had that happen in my experience, only hex values, but I added some logic for when it is a hex value.
