### ISSUE TITLE
Importing via mnemonic is impossible on iOS 15.4.1

### ISSUE THREAD

**Issue by eratio08** [BlueWallet/BlueWallet#4648]
It's currently impossible to import a wallet using a mnemonic phrase because entering text in the text area will open a keyboard that can not be closed anymore thus is will hide the button at the bottom.

* your phone model and OS version
  iOS 15.4.1, iPhone 11Pro
* BlueWallet app version (settings->about->scroll down)
  6.2.17
* self-test passes? Open settings->about->scroll down, tap "Run self-test"
  yes
* unique ID for our crash reporting service (settings->about->scroll down, tap "copy")
  not crashed so why

**Comment by Overtorment** [comment]
you should have an overlay above the keyboard with text "clear", "paste" & "done", is it present..? post a screenshot plz

**Comment by eratio08** [comment]
Oh nvm I thought this was the auto-complete bar of ios. Thanks a lot. :D thanks
