### ISSUE TITLE
Support import of localized recovery phrases

### ISSUE THREAD

**Issue by GBKS** [BlueWallet/BlueWallet#4649]
The default wordlist is in English, which can be problematic for non-English speakers. To improve accessibility, Blue Wallet could support creation and import of recovery phrases in various languages. The Phoenix team is [working on this](https://github.com/ACINQ/phoenix/pull/233), and pointed out that a good starting point would be to support import of localized recovery phrases, and only support their creation at a later stage when there is more broad support.

So Blue could add support for importing recovery phrases that use one of the [10 wordlists](https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md) that are included with the BIP39 spec.

A parallel effort, outside the scope of this issue, could be to create wordlists in more languages. And eventually, once more wallets support this, a call would need to be made when the creation of recovery phrases in other languages should become an option in the UI, or even the default.

**Comment by GitTankMusic** [comment]
I am in this trouble, I have 12 BRD wallet Chinese recovery phrase word from BRD, BRD wallet end-of-life, I don't know how can I use the Chinese recovery phrase word to get my coins back, that got me really worried.

**Comment by GBKS** [comment]
That was crazy quick! Thank you for making this happen.

![Hug](https://media.giphy.com/media/ZBQhoZC0nqknSviPqT/giphy.gif)

**Comment by Overtorment** [comment]
thanks. making actual release will take a while tho, since we have some bugs that sneaked into master
