### ISSUE TITLE
"Display in wallets list" does not work as expected

### ISSUE THREAD

**Issue by BenGWeeks** [BlueWallet/BlueWallet#4656]
**Environment**

Phone model and OS version: iPhone 12 Pro Max, iOS v15.3.1
BlueWallet app version: v6.2.17

**Description**

Using the "Display in Wallets list" does not work as expected and when switched off, the wallet still appears on the home screen

**Steps to reproduce**

- Open a wallet that you previously created
- Click on "..." at the top right
- Untick "Display in Wallets List"
- Click "Save" (should see "Alert: Wallet updated"
- Click on the back arrow

**Expected result**

The wallet should not be displayed on the Wallets home screen.
There should be an option for "Display hidden wallets" in the General Settings.

**Actual result**

The wallet is still displayed.

The wallet is still displayed on the home screen

**Comment by Overtorment** [comment]
"Display in wallets list" is under "transactions" subheader, and if enabled on the main screen transactions from this wallet wont be mixed with other wallets

**Comment by BenGWeeks** [comment]
Ah, perhaps this should be renamed "Display wallet transactions on home screen"?

**Comment by BenGWeeks** [comment]
Or not?! ;-)
