### ISSUE TITLE
Frequent API Error

### ISSUE THREAD

**Issue by BenGWeeks** [BlueWallet/BlueWallet#4659]
**Environment**

Phone model and OS version: iPhone 12 Pro Max, iOS v15.3.1
BlueWallet app version: v6.2.17

**Description**

I have myself frequently seen "API Errors" when sending funds. I assumed this was due to a slow performing node that I am connected to. However, when onboarding new people (not connecting to their own node) I have seen this a few times as well.

**Steps to reproduce**

- Create a new wallet
- Open the wallet

**Expected result**

Empty wallet opens as expected.

**Actual result**

The user (sometimes) receives an "API Error".

**Resolution**

As this is difficult to narrow down, I would suggest that perhaps this "API Error" is a little bit of a catch-all error handling. Therefore, perhaps more specific (and ideally user friendly) message should be relayed back to the user to give a better indication of any potential issues that are occurring and how they could be resolved.

**Comment by Overtorment** [comment]
[ususall](https://github.com/BlueWallet/LndHub/) issue
