### ISSUE TITLE
Is there any way to get my private key from the 12 BRD recovery phrase word?

### ISSUE THREAD

**Issue by GitTankMusic** [BlueWallet/BlueWallet#4672]
BRD don't give users the private keys, is there a way to get my btc private key from my 12 brd recovery phrase word? BRD closed down, my recovery phrase is non-english recovery phrase, I want to use the private key to recovery my coins in new wallet.

**Comment by limpbrains** [comment]
> @limpbrains should this pr #4667 help it..?

Yes

**Comment by GitTankMusic** [comment]
> @GitTankMusic If you are on Android you can download apk from #4667 and test your seed there

@limpbrains No, I am on iPhone, don't have Android, will we have the iOS version?

**Comment by GitTankMusic** [comment]
> > @limpbrains No, I am on iPhone, don't have Android, will we have the iOS version?
> 
> Then you need to wait for the next BW release. If you want to help to test it, there is a link to appetize.io in PR, you can run BW in browser, but I don't recommend it - you will expose your seed.

I'll be waiting for the next release, thank you!
