### ISSUE TITLE
Transaction doesn't register with wallet

### ISSUE THREAD

**Issue by Pillagr** [BlueWallet/BlueWallet#468]
I tried sending a tx from a Legacy wallet. It confirmed that the Tx was sent, but it never appears in my history, and never goes through. I tried upping the fee, nothing. 

![IMG_0837](https://user-images.githubusercontent.com/46731461/56677561-ca7ba200-668e-11e9-9207-1665c6f0f372.PNG)
![IMG_0835](https://user-images.githubusercontent.com/46731461/56677576-d49da080-668e-11e9-9a96-77f5adecb7e8.PNG)
![IMG_0836](https://user-images.githubusercontent.com/46731461/56677588-d7989100-668e-11e9-9728-f1331bbb94a2.PNG)

**Comment by Overtorment** [comment]
I forgot that we even support legacy addresses. Okay I need to test it, this functionality might be broken. I will get back to you.

**Comment by Pillagr** [comment]
okay. I deleted thhe app and restored the wallets on the latest version, same problems.
