### ISSUE TITLE
Push Notification taking too long to arrive 

### ISSUE THREAD

**Issue by Chileads** [BlueWallet/BlueWallet#4721]
Push notification can take up to 10hrs to arrive especially for incoming transactions. I mainly use the notification to know when their is incoming transactions because the transaction does not appear even when you open and refresh the app. When I get a notification I go to "coin control" to verify the amount. 

I learnt that it's cause of traffic in the groundcontrol-bluewallet.herokuapp.com server that's causing the delay in notification.
I suggest we should have multiple servers or alternatives for app notifications.

**Comment by Chileads** [comment]
I'm using bluewallet 6.2.17
Redmi note 8 Pro,, android 10
userId:afcd5c31f0bd868b

**Comment by Overtorment** [comment]
PN server runs on quite cheap plan.
btw, heres the repo for PN server: https://github.com/BlueWallet/GroundControl/

i did some improvements lately to make things quicker and send queue stuck less. out of ideas for now
