### ISSUE TITLE
Fee handling Improvement

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#477]
- Calculate automatically the value to pay
- Offer the option for the user to define custom sat/byte

<img width="905" alt="Screenshot 2019-05-08 at 10 40 15" src="https://user-images.githubusercontent.com/1238429/57361863-b69b6a00-717d-11e9-98c6-2fb368f0e797.png">

**Comment by ncoelho** [comment]
Q&A testing:

- [ ] Should the label on the screen display the text or the value?
- [ ] There's a gap on the container, it doesn't touch the bottom
- [ ] Should de behaviour be, select and close the modal, or select stay and let the user close the modal?
- [ ] The custom value alert, feels buggy, should it dismiss the modal before triggering the alert
- [ ] The alert for custom value, should display a placeholder, so the user knows he is dealing with sat/byte

**Comment by ncoelho** [comment]
Updated proposal:

<img width="884" alt="Screenshot 2019-05-22 at 15 39 35" src="https://user-images.githubusercontent.com/1238429/58179160-ed0dd480-7ca7-11e9-95bb-869c9c4d6221.png">

**Comment by Overtorment** [comment]
Local currency equivalent wouldn't hurt

**Comment by ncoelho** [comment]
> Local currency equivalent wouldn't hurt

Feature set:
- Everything is calculated in real time
- Denomination is defined by wallet (can be BTC, sats or local currency)
- 3 options only by default (fast, medium, slow)
- Option to set custom value in sat/byte

**Comment by limpbrains** [comment]
@marcosrdz would you mind if I work on this?

**Comment by marcosrdz** [comment]
> @marcosrdz would you mind if I work on this?

Go for it!
