### ISSUE TITLE
Not enough balance, but I have it

### ISSUE THREAD

**Issue by dimiandre** [BlueWallet/BlueWallet#478]
I'm trying to pay an invoice of 179000 sats, and I have 179408 sats but I get the error "API error: not enough balance (code 2)"

screen attached

![IMG_6822](https://user-images.githubusercontent.com/543292/57364409-6c1cec00-7183-11e9-82a4-a84d160190a1.PNG)

**Comment by ncoelho** [comment]
Seems it is not enough for the service fee. I think zigzag has a 1% fee.
http://help.bluewallet.io/common-problems/not-enough-balance

**Comment by dimiandre** [comment]
> Seems it is not enough for the service fee. I think zigzag has a 1% fee.
> http://help.bluewallet.io/common-problems/not-enough-balance

fee of zigzag are already included in the payment request, maybe it's not enough for lightning network fees but it's strange since there are 408 sats available for ln fees
