### ISSUE TITLE
New Feature: Export xPub as a file

### ISSUE THREAD

**Issue by tadeubas** [BlueWallet/BlueWallet#4796]
When the user click to show XPUB the interface should allow to download it as a file instead of just the QRCode and the copy to clipboard. This is important when using a phone that is not online and you want to share the file to another phone without physical contact, copying it to a SD card.

**Comment by marcosrdz** [comment]
Currently you can save the QRCode by tap and hold and you'll see the copy to copy the image to your clipboard or save it as an image.

**Comment by duckman2277** [comment]
How do i get my blue wallets out of watch only mode? And whos decision was it to put them in watch only mode if i didnt do it?

**Comment by Overtorment** [comment]
> How do i get my blue wallets out of watch only mode? And whos decision was it to put them in watch only mode if i didnt do it?

someone gave you something to import into bluewallet? sounds like you got scammed.
