### ISSUE TITLE
Payment description

### ISSUE THREAD

**Issue by grunch** [BlueWallet/BlueWallet#481]
Hi guys, I have a LApp called Microbet, I have a way to let people to recover their session that I called `PoP sign in`, which means that I use the payment preimage and I add a small ID at the end of the description, a couple of users wrote me to tell me that they can't see the complete description on their bluewallet and for that reason the can't login to Microbet after they logout.

Is it possible for you to add the entire payment description on the payment detail?

Thanks

**Comment by Overtorment** [comment]
Sure. @marcosrdz can you look into this..? Also, tx list shortens payment description too much. We clearly have some spare space.

**Comment by Overtorment** [comment]
@grunch  btw, lapp browser webview  stores cookies/localStorage pretty well. You can rely on that.
