### ISSUE TITLE
UI issues: Lightning authenticated screen

### ISSUE THREAD

**Issue by JijoBose** [BlueWallet/BlueWallet#4840]
## Are you reporting a bug?

Please provide:

* iPhone 13 and iOS 15.5
* BlueWallet app version: 6.3.0
* self-test passes? Yes

- Authenticated screen when you confirm a lightning auth is broken

<img src="https://user-images.githubusercontent.com/13100108/176716643-39916a6d-9a99-4dc8-89be-7fe82d62091f.png" height="500px" />

**Comment by JijoBose** [comment]
To replicate you can sign in using lightning wallet from 
https://stacker.news/

**Comment by Overtorment** [comment]
@marcosrdz
