### ISSUE TITLE
Invoice expiration options

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#485]
As requested in https://github.com/BlueWallet/BlueWallet/issues/475 . This is a proposal to improve the expiration time of invoices.

Users should be able to choose (open to feedback) between:

- 1 hour
- 12 hours
- 7 days

The interface should be a picker (and equivalent option of android) upon tap on the expiration option on the view.

Preview [full assets and specs here](https://app.zeplin.io/project/5b252c1057a0c54542fe1f02/dashboard?seid=5c1bdd862e3f282424c749a1):

<img width="1425" alt="Screenshot 2019-05-15 at 14 39 19" src="https://user-images.githubusercontent.com/1238429/57776719-8117f300-7720-11e9-8ccd-bf3d8ba0312d.png">

Includes also improvements on the invoice view screen.

**Comment by Overtorment** [comment]
Is it a good idea to place it in app settings?

**Comment by ncoelho** [comment]
Don't think so, I see it as "local" option rather then a "global" option, that's how I view the options on the settings. 

Should default to 1 hour and allow users with other use cases to just set a bigger time there.

**Comment by marsrobertson** [comment]
I think these are very sensible defaults covering most of the use cases.

**Comment by Overtorment** [comment]
we hardcoded it to 24h
