### ISSUE TITLE
Watch-only wallet error "Should not be used in watch-only HD wallets"

### ISSUE THREAD

**Issue by limpbrains** [BlueWallet/BlueWallet#4859]
Saw a user complaining in BW chat that he can't construct transaction for watch-only wallet. Wallet was imported from seed signer, as a qrcode.

I couldn't reproduce the issue, can't find any working emulator for seed sigher.

User reports that he has same wallet on Sparrow and it working fine.

![2022-07-09 12 55 22](https://user-images.githubusercontent.com/155891/178100845-ba6898d3-acb8-475c-a949-37050f54a730.jpg)

Maybe BW doesn't support some qrcode format, which sparrow does?

**Comment by Overtorment** [comment]
hmm. test vectors would be helpful

**Comment by limpbrains** [comment]
No test vectors
