### ISSUE TITLE
Mnemonic on creation improvement

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#486]
Users are reporting that they don't know the order of the words on the new mnemonic view.

We can just do something like this to help the readability and understanding.

Text:

> Success, your wallet is now created! 
Please take a moment to write down this mnemonic sentence on paper. It’s your backup that you can use to restore your wallet.

Preview ([Specs here](https://app.zeplin.io/project/5b252c1057a0c54542fe1f02/screen/5cdc10cc37576a1d44086873)):

<img width="388" alt="Screenshot 2019-05-15 at 15 17 05" src="https://user-images.githubusercontent.com/1238429/57778554-942cc200-7724-11e9-98b1-b7895251c87d.png">

**Comment by Overtorment** [comment]
I dont know how to do that layout in RN. Easier with numbers

**Comment by ta32** [comment]
the seed words appeared to me like a table, and i almost wrote them down column by column.

I think numbering the seed words will emphasis that the order is important. This step only has to be done once so I don't care if it doesn't look pretty enough when the seed words are numbered.

**Comment by anilakkaraveedu** [comment]
You transfer to my Trx wallet 
I will help you 
TLB5GCwwLtExTaq5XtqX3daixdU6XXQV4b
