### ISSUE TITLE
LDK lightning wallet - force close funds are sent to address not controlled by selected wallet

### ISSUE THREAD

**Issue by blankscreengithub** [BlueWallet/BlueWallet#4861]
## Are you reporting a bug?
yes

Please provide:

* your phone model and OS version
* Samsung S1 Android 12

* BlueWallet app version (settings->about->scroll down)
* 6.3.1

* self-test passes? Open settings->about->scroll down, tap "Run self-test"
* yes

* unique ID for our crash reporting service (settings->about->scroll down, tap "copy")
* userId:f910178399b30040

Go right ahead

I had one channel that was stuck at pending even though the transaction was confirmed. That channel never connected as a peer, so I issued the force close command. I selected the wallet I wanted the funds to return to, but they ended up going to an address that my selected wallet does not control. This resulted in not being able to access the funds from the channel force close.

**Comment by Overtorment** [comment]
funds might be stuck in a temp address, youll need to wait for some time (something between a 1 and 14 days) for them to unlock and actually be transferred to your intended address

**Comment by blankscreengithub** [comment]
I saw the note about "balance awaiting confirmations: ETA 24 hours.i guess this is what that means.

What controls the private key to the temp address, the LDK wallet?

**Comment by Overtorment** [comment]
keys to temp addresses are derived from the mnemonic that seeds LDK, so they never leave your device

**Comment by blankscreengithub** [comment]
Thanks! Everything came back to my funding wallet as expected. Maybe there should be some sort of message indicating this.
