### ISSUE TITLE
Update App Store Keywords

### ISSUE THREAD

**Issue by jesterhodl** [BlueWallet/BlueWallet#4879]
App Store Keywords include words like: cryptocurrency and samourai.
Do they make sense there? It's bitcoin only.
![image](https://user-images.githubusercontent.com/103882255/179242067-19aaa968-8958-4e05-a7b5-4c11d96837d8.png)

**Comment by Overtorment** [comment]
etherium kek


cc @ncoelho

**Comment by ncoelho** [comment]
Wrote that some years ago. lgtm, that's what keywords are for. Onboarding an etherium user one search at the time 💪

**Comment by pysiak** [comment]
ooh ok :-) happy to close the issue

**Comment by jesterhodl** [comment]
:-)
