### ISSUE TITLE
Send small change to lightning wallet

### ISSUE THREAD

**Issue by allthegoodnamesweret4ken** [BlueWallet/BlueWallet#489]
I don't know if this is feasible, but wouldn't it be beneficial if you could define a threshold, and whenever the change amount from an on-chain tx is below the threshold it automatically gets sent to your lightning wallet. On one hand, it would improve privacy by spending the entire output, instead of using the change in a future tx, on the other hand it allows you to top up your lightning wallet without the need for an on-chain tx.
Or am I missing something?
You could implement it as an automatic rule (with a threshold), or maybe also as a (checkmark) option when sending an on-chain tx.

**Comment by Overtorment** [comment]
Thats actually a good idea. Will think about it
