### ISSUE TITLE
Fast speed should be at minimum 2sat/bytes

### ISSUE THREAD

**Issue by Transisto** [BlueWallet/BlueWallet#4902]
Because 2 sat/bytes currently $ value is very low I think FAST should be at minimum 2sat/bytes. 

Now for example in the last 5 hours there were multiple times where 1sat/byte would not have been enough.

![image](https://user-images.githubusercontent.com/388716/180861259-99a4dbd5-94af-4090-8287-8beb49d2b385.png)

But BLUE isn't suggesting more than 1sat for fast speed.

![image](https://user-images.githubusercontent.com/388716/180861336-66a14135-2443-40c9-b375-28c767f3782a.png)

I suggest to override the fee calculation so that fast is never lower than 2

**Comment by ncoelho** [comment]
The fee algo is done for realtime data. Not historical data or forecast. So
its the best fee you can get right now. If you refresh it it will change.

**Comment by Transisto** [comment]
1 is the lowest fee nodes will relay.
There is a huge amount of transaction defaulting to this rate.

Minimum for FASTEST could be 1.1 sat/byte or anything higher than the very
minimum.

**Comment by Transisto** [comment]
1 is the lowest fee nodes will relay.
There is a huge amount of transaction defaulting to this rate.

Minimum for FASTEST could be 1.1 sat/byte or anything higher than the very
minimum.

**Comment by tadeubas** [comment]
To customize every single sat used as Fee on BW do the following:

On the `Send` screen, the `Fee` will appear at the bottom, select `1 sat/vByte`, click on the 3 dots (`...`), select `Coin Control`, select the coins you want to use. Enter the amount to be transferred and the receiving address... check the Fee after entering the amount. If you want to change the Fee, click again on the 3 dots (`...`), select `Add Recipient` and enter the amount to be transferred and your receiving address... only the remaining amount will be used to increase the Fee... double-check the Fee after entering the amount.

**Comment by Overtorment** [comment]
implementing  feerate 2 for priority tx here: https://github.com/BlueWallet/BlueWallet/pull/5253
