### ISSUE TITLE
Feature Request: Help a no-coiner receive his first lightning sats

### ISSUE THREAD

**Issue by ozomer** [BlueWallet/BlueWallet#4923]
Suppose I'm going to a barber or taking a taxi. After a long talk I've convinced the guy that he needs to get some Bitcoin. I want to give him some tip in sats, but neither of us have the time to install a wallet on phone and follow the instructions. Furthermore, it's a bad practice to setup a wallet when somebody else is watching over your shoulder...

What I want is to create a short-link/QR-code that he could take a photo of, then open it at the end of the day after work.
The page that he'll open should show instructions how to install BlueWallet, and a short gift code.
After installation, he could enter the gift code and receive the tip.
(It would be nice that if we could find out that he installed the app directly from my link, the app will automatically give him the gift).

The amount of sats should be decided when I create the link and deducted from my wallet. If he did not use the gift code within 48 hours, the amount should return to my balance. The link page could show him a countdown of the time left to redeem his sats. 

What do you think?

**Comment by Overtorment** [comment]
you need https://lightning.gifts

**Comment by ozomer** [comment]
@Overtorment Nice! I didn't know about that. Would be nicer to combine with a url-shortener so I could write the address on a piece of paper (for example, as a restaurant tip), and if there was a direct link to download a wallet  app.
It would also be easier for the redeemer to type a 6 digits code instead of taking a screenshot of the QR code. This could be implemented as a rotating code that changes every few minutes, like in the 2FA Authenticator app, to prevent hackers from trying all the codes.

**Comment by Overtorment** [comment]
out of our scope
