### ISSUE TITLE
Support paying BIP21 based unified bitcoin QR codes

### ISSUE THREAD

**Issue by MichaelRihani** [BlueWallet/BlueWallet#4931]
**From the main BlueWallet scanner**
I'm getting those two error messages when I scan a [unified bitcoin QR code](https://bitcoinqr.dev/):
![bluewallet-mixed-case](https://user-images.githubusercontent.com/2050650/182798926-f1ca3f90-60b0-4fbf-b270-11542685ea24.png)
![bluewallet-and-symbol](https://user-images.githubusercontent.com/2050650/182798947-9364a8fc-3b07-44cc-aad2-794a519b8594.png)

**From the BIP21 spec:**
"The scheme component (“bitcoin:“) is case-insensitive, and implementations must accept any combination of uppercase and lowercase letters."

Can BlueWallet accept mixed case lightning invoices and also support QR codes with an "&" in them, as described in [BIP21](https://github.com/sbddesign/bip21-site) and [Unified QRs for Bitcoin](https://bitcoinqr.dev/)?

Happy to chat more ([Twitter DMs](https://twitter.com/MichaelRihani) are open) or jump on a call if helpful. Would love for BlueWallet to work seamlessly when we roll out our new unified QR codes at Cash App soon.

**Comment by ncoelho** [comment]
Can you provide an example with the error?

This was [implemented here](https://github.com/BlueWallet/BlueWallet/issues/257) 4 years ago :)

And testing this QR code from the website example works flawlessly on my side.

![image](https://user-images.githubusercontent.com/1238429/182801139-ea3b4126-7265-4671-ad17-1d104f3c30d0.jpeg)

**Comment by Overtorment** [comment]
for reference, test page witl different QRs: https://bluewallet.io/testpage/

**Comment by Samiraelrhoudri** [comment]
Grazie

**Comment by MichaelRihani** [comment]
Ah – my apologies for not being more clear or providing the actual text/QR code examples.

Below are 3 examples (2 fail; 1 works).

**Steps to Reproduce**
1. Open BlueWallet
2. Press Scan
3. Scan QR codes below

**Example 1 - Mixed-case string error (error alert)**
![Mixed-case string error](https://user-images.githubusercontent.com/2050650/187057616-d838fad2-758f-4766-9212-52af7bb504f3.png)
QR code encoded with = `bitcoin:bc1q8flg3jcnv6x6mpjrqty8h8h9mg0shgp5jc9smk?lightning=LNBC1P3WKFY3DQQPP5030V53XSDHSGJKZELYLE7EKTMEM38974498VNQDT2JAZ24TRW39QSP502JQJ4K6NR7AXQYMHKF3AX70JXFX6JZA4JYGVC66NJZHFS4TSA2Q9QRSGQCQPCXQY8AYQRZJQV06K0M23T593PNGL0JT7N9WZNP64FQNGVCTZ7VTS8NQ4TUKVTLJQZ2ZHYQQXQGQQSQQQQQQQQQQQQQQ9GRZJQTSJY9P55GDCEEVP36FVDMRKXQVZFHY8AK2TGC5ZGTJTRA9XLAZ97ZKCYVQQPRSQQVQQQQQQQQQQQQQQ9GY3X4N6RV6RCN53LDEV96AURLS3C66KPX74WA4UWCWU92JGKTPQE8NCQPZJ8JG6SUNYGZM320CDUTNVGSRC6XV286EVHRXEFSXXUZ0SSQWTM6DQ&amount=0`

![Alert1](https://user-images.githubusercontent.com/2050650/187057769-50ae5ad9-b1f9-4b2f-9a49-32484e285e9c.PNG)

**Example 2 - Unknown character & (error alert)**
![Unknown character](https://user-images.githubusercontent.com/2050650/187057699-79c2b5e0-0325-430e-9d9f-94863f1197e8.png)
QR code encoded with = `bitcoin:bc1q8flg3jcnv6x6mpjrqty8h8h9mg0shgp5jc9smk?lightning=lnbc1p3wkfy3dqqpp5030v53xsdhsgjkzelyle7ektmem38974498vnqdt2jaz24trw39qsp502jqj4k6nr7axqymhkf3ax70jxfx6jza4jygvc66njzhfs4tsa2q9qrsgqcqpcxqy8ayqrzjqv06k0m23t593pngl0jt7n9wznp64fqngvctz7vts8nq4tukvtljqz2zhyqqxqgqqsqqqqqqqqqqqqqq9grzjqtsjy9p55gdceevp36fvdmrkxqvzfhy8ak2tgc5zgtjtra9xlaz97zkcyvqqprsqqvqqqqqqqqqqqqqq9gy3x4n6rv6rcn53ldev96aurls3c66kpx74wa4uwcwu92jgktpqe8ncqpzj8jg6sunygzm320cdutnvgsrc6xv286evhrxefsxxuz0ssqwtm6dq&amount=0`

![Alert2](https://user-images.githubusercontent.com/2050650/187057773-e18b3246-b27f-43ed-b1bc-14f54e1b3573.PNG)

**Example 3 - All `lowercase` and removing `&amount=0` then works (success)**
![Success](https://user-images.githubusercontent.com/2050650/187057704-59c1ce00-b1b9-463f-a0bd-e7318d959970.png)
QR code encoded with = `bitcoin:bc1q8flg3jcnv6x6mpjrqty8h8h9mg0shgp5jc9smk?lightning=lnbc1p3wkfy3dqqpp5030v53xsdhsgjkzelyle7ektmem38974498vnqdt2jaz24trw39qsp502jqj4k6nr7axqymhkf3ax70jxfx6jza4jygvc66njzhfs4tsa2q9qrsgqcqpcxqy8ayqrzjqv06k0m23t593pngl0jt7n9wznp64fqngvctz7vts8nq4tukvtljqz2zhyqqxqgqqsqqqqqqqqqqqqqq9grzjqtsjy9p55gdceevp36fvdmrkxqvzfhy8ak2tgc5zgtjtra9xlaz97zkcyvqqprsqqvqqqqqqqqqqqqqq9gy3x4n6rv6rcn53ldev96aurls3c66kpx74wa4uwcwu92jgktpqe8ncqpzj8jg6sunygzm320cdutnvgsrc6xv286evhrxefsxxuz0ssqwtm6dq`

**Comment by MichaelRihani** [comment]
Following up here, anything else I can provide to help?

**Comment by Overtorment** [comment]
oh, it slipped my mind. ill take a look
