### ISSUE TITLE
Unable to delete a multisig wallet I imported from blue wallet desktop QR code

### ISSUE THREAD

**Issue by moranda3** [BlueWallet/BlueWallet#4935]
## Are you reporting a bug?

Please provide:

* your phone model and OS version: 
* iPhone 12 Pro, iOS 15.6
* 
* BlueWallet app version (settings->about->scroll down)
* 6.3.1 (build 1656866507 master)
* 
* self-test passes? Open settings->about->scroll down, tap "Run self-test"
* Yes
* 
* unique ID for our crash reporting service (settings->about->scroll down, tap "copy")
* userId:7F64C124-065F-4AB9-8B5C-682E429341A1

I am having the same exact issue as described in this previously closed post:
https://github.com/BlueWallet/BlueWallet/issues/4255

The difference is that I used the export/backup QR code generated from the desktop version of Blue Wallet to import it to my phone.  Unable to delete the wallet. Have tried deleting iCloud backups, local phone cache data, reinstalled, restarted, etc.

Please help, thank you!

**Comment by ncoelho** [comment]
Add a password to encrypt. Then fail the password 10x at startup and it
asks if you want to restore the storage.

**Comment by moranda3** [comment]
Awesome, that worked! thank you!
