### ISSUE TITLE
Sign/Verfiy Message Problems

### ISSUE THREAD

**Issue by BeatGubser** [BlueWallet/BlueWallet#4946]
I have created a wallet with BlueWallet.
I need to sign a message for an application.
When i sign it with BlueWallet the Signature is NOT accepted.
When i import the Wallet in Electrum and sign it there the Signature is accepted.
The BlueWallet and the Electrum Signatures are different.
Is there a bug in the BlueWallet?
Thank you in advance!

**Comment by Overtorment** [comment]
cc @limpbrains

**Comment by limpbrains** [comment]
@BeatGubser 
What type of wallet do you have? Does text contain any Non-ASCII symbols? Can you share text and signatures? Maybe privately?

**Comment by BeatGubser** [comment]
@limpbrains 
The wallet type is
HD SegWit (BIP84 Bech32 Native)
and the derivation path is
m/84'/0'/0'
The wallet is empty, I can give you the seed, but how can I do that privately?

**Comment by BeatGubser** [comment]
@limpbrains 
The seed has only ascii chars a-z

**Comment by BeatGubser** [comment]
@limpbrains 
According to an ascii online validator is the message text valid ascii ...

**Comment by limpbrains** [comment]
I'm @limpbrains in Telegram
Or email ivan.vershigora@gmail.com

**Comment by BeatGubser** [comment]
@limpbrains 
Email is on the way ...

**Comment by limpbrains** [comment]
There are 2 competing standards of signing messages with Segwit addresses. BlueWallet uses one by Trezor team.
That is why signatures are different. Produced signature is still correct. BW can verify both variants. 

I don't know which variant is more popular, we can switch to use Electrum variant by default if needed. 

https://github.com/BlueWallet/BlueWallet/pull/2770

**Comment by Overtorment** [comment]
@limpbrains maybe put a checkbox, "i want electrum signature" ?

**Comment by BeatGubser** [comment]
Thank you very much for the analysis @limpbrains !
In my opinion it would be desirable to have the Electrum signature as default, because BlueWallet ist based on the Electrum Server Network.
And under "Settings" there could be somewhere an option like "Signing Algorithm" with the values "Electrum" and "Trezor".
Of course would a simpler solution like the proposal from @Overtorment already help too.
