### ISSUE TITLE
ypub from trezor does not update

### ISSUE THREAD

**Issue by coolcash** [BlueWallet/BlueWallet#495]
Imported my ypub address from my Trezor Standard accounts (BIP49). Initial import worked, but its not refreshing with new transactions or balance.  Version 4.01 (build 1557875989) IOS.

**Comment by Overtorment** [comment]
Have you tried pull-to-refresh..?
Do you know if you have gaps in addresses? (bw has gaplimit 3 atm)

**Comment by coolcash** [comment]
I have no gaps. I have tried pull-to-refresh and also fully closed the app and reopened.
