### ISSUE TITLE
"LDK init error: channel_mananger_constructor init Failed" on startup

### ISSUE THREAD

**Issue by tanx** [BlueWallet/BlueWallet#4954]
## Are you reporting a bug?

Please provide:

* your phone model and OS version:
iPhone 13 mini, iOS 15.6
* BlueWallet app version (settings->about->scroll down):
v6.3.1 (ldk binary:  v0.0.106.2-dirty)
* self-test passes? Open settings->about->scroll down, tap "Run self-test"
yes
* unique ID for our crash reporting service (settings->about->scroll down, tap "copy")
userId:854BCD0E-3BD8-4784-A6E6-4061DDE38AC1

I've been playing around with the hidden LDK wallet and found BlueWallet crashes sometimes when trying to persist channel manager. After the crash, I reopen BlueWallet and see this error message: 

![IMG_B0DA7F110092-1](https://user-images.githubusercontent.com/1374174/184627353-147aab62-9e27-4c0d-ae7d-f5bb6c47eb30.jpeg)

The channel displays as pending even though there are more than 3 confirmations. It never shows as opened, even after restarting a few times.

I try to delete the LDK wallet and restore from seed. The channel doesn't display anymore. I get the same error message as above on every start.

This issue has resulted in loss of funds on two occasions.

**Comment by Overtorment** [comment]
you can email me your seed & I can manually extract channel manager & channels data from net storage, and try to recover them
i@bluewallet.io

i will be bumping ldk binaries soon, so hopefully those errors will go away
