### ISSUE TITLE
Question: how to migrate settings?

### ISSUE THREAD

**Issue by jbrepogmailcom** [BlueWallet/BlueWallet#4961]
Hello. I need to transfer the BW to a new phone and I do not want to use Google's and vendor's migration tools. Is there any other option how to transfer impirted wallets? Thank you

**Comment by ncoelho** [comment]
That’s what your seed is for.

https://bluewallet.io/docs/import-wallet/

**Comment by jbrepogmailcom** [comment]
Sorry I was not clear in my question. I have many wallets and I would like to migrate them all at once. Thanks

**Comment by Overtorment** [comment]
> Sorry I was not clear in my question. I have many wallets and I would like to migrate them all at once. Thanks

one-by-one.
go to walelt details->export (it shows QR code) -> scan this QR code with other device

dont forget, that your seeds should also be backed up on paper somewhere
