### ISSUE TITLE
Bitcoin wallet Send dialog turns black when dragging down on dialog window

### ISSUE THREAD

**Issue by BrotherCreamy** [BlueWallet/BlueWallet#4971]
Phone: iPhone SE 2nd gen, iOS 15.6
App version: 6.3.1
Self-test: Pass

In the Send dialog (for Bitcoin wallet only), if I drag down on the dialog window, it initially turns the Send title bar black, then the entire contents of the dialog window. App does not crash when this happens. If you reopen the Send dialog the problem disappears.

Upon opening Send dialog:
![IMG_6661](https://user-images.githubusercontent.com/5473845/185779369-9255101f-9a86-4160-8ad5-d4cc22a2eda8.PNG)

Sent title bar turns black shortly after dragging down slightly on the dialog window (interestingly doesn't happen when dragging up):
![IMG_6662](https://user-images.githubusercontent.com/5473845/185779372-6d793a85-925d-4865-bf34-e5c22562e193.PNG)

Entire contents of dialog window turn black shortly after dragging down slightly on the dialog window a second time:
![IMG_6663](https://user-images.githubusercontent.com/5473845/185779376-44678e70-74c8-48c8-92b8-885fe6196cbd.PNG)

If I touch anywhere in the dialog window at this point, I get this context menu pop up:
![IMG_6664](https://user-images.githubusercontent.com/5473845/185779521-0b716294-ef57-482e-9834-9b137c1fd985.PNG)

**Comment by marcosrdz** [comment]
Reproduced. Thanks for the report. Will take a look at it
