### ISSUE TITLE
Feature request: UX - Re-ordering of wallets in wallet stack without a separate dialog.

### ISSUE THREAD

**Issue by BrotherCreamy** [BlueWallet/BlueWallet#4972]
Rather than opening up a separate 'Re-order wallets' dialog where the user is able to drag wallets around to reorder, the dragging functionality should just be integrated directly into the wallet stack.

**Comment by Transisto** [comment]
Maybe you can suggest how the feature should look like. 
I don't think that should be any priority given most users use a single wallet.

**Comment by BrotherCreamy** [comment]
Thanks for your reply.

I agree it's not a priority.

Basically the same drag and drop functionality that is exhibited on the "re-order wallets" dialog, but the drag and drop happens in place.

i.e. you press and hold on the wallet card you wish to move, it enters the "picked up" state, and then you drag it to the position you want directly in the main wallet stack and let go to drop.

**Comment by puck2** [comment]
I use multiple wallets, and imagine many do. The current recording does not work on my Android 13, Samsung S22 phone
