### ISSUE TITLE
Ability to send "MAX" is disabled after scanning QR code

### ISSUE THREAD

**Issue by dav1dpgit** [BlueWallet/BlueWallet#4985]
In the iphone most recent OS, BlueWallet version 6.3.1...

The ability to send a full balance is removed after scanning a QR code.

I encounter the problem when sending MAX bitcoin in BlueWallet selecting "Use full balance" first (MAX) and afterwards scanning a QR code to send to.

The aforementioned process changes the MAX to 0 bitcoin being sent, and removes the ability to send MAX (no dots available at the top of the send screen.)  I would have expected to continue to send MAX after scanning a QR code

**Comment by marcosrdz** [comment]
Replicated. Will take a look

**Comment by Overtorment** [comment]
same. replicated. whole multidot menu disappears
