### ISSUE TITLE
Bluewallet imports SegWit watch-only wallet as legacy

### ISSUE THREAD

**Issue by seedhammer** [BlueWallet/BlueWallet#4993]
I'm scanning this watch-only xpub with derivation path and master fingerprint. Bluewallet seems to accept the 84' path but then proceeds to generate legacy addresses (1...) contrary to the specification that 84 is used for native segwit addresses (bc1...)

QR: 
![QR](https://user-images.githubusercontent.com/93251679/187401685-911cabe3-1110-4211-90cb-641dfe502e9d.jpg)

[dafedf1c/84h/0h/0h]xpub6DFMZMLizqqnyyHoWTG7qzmCR1irpiDEGT4JQX7ubeoFtV838ABKPfgAPQbM1TEekEyCuJF1BrmnA7JPrnzqi2VbycD3tVE3v5xsDQqYA3A

How to reproduce:

1. Open BlueWallet -> Add Wallet (Add now) -> Import wallet -> Scan or import file -> Scan the  QR
2. Open the freshly imported watch only wallet -> Tap "..." in upper right corner -> Show addresses
3. A series of legacy addresses are shown (1...)

**Comment by hugoender** [comment]
@seedhammer can you explain in detail how you formatted the zpub to get it working? I'm having the same issue but in my case I'm just importing the xpub without the preceding master fingerprint or derivation path.

**Comment by hugoender** [comment]
Disregard my previous comment. I just used the zpub address and it worked.

**Comment by Nounou-M** [comment]
Hello , is bluewallet country restricted ?

**Comment by seedhammer** [comment]
What is schedule deploy of fix to this issue?

**Comment by Overtorment** [comment]
prepared a fix.

@seedhammer can you pls confirm, that for the given example zpub would be `zpub6rutAggZJCvkgZg3BAqNGAxCkx1khxCE6g6jyJugMfZ1zgkVdUWSdnzSRpWX1GYVZXCpQFS87BUsvgXXJBpsJVroiHbu4Js2TY69zbWcTNb` and first address on the hierarchy would be `bc1q68y6r45k4kvxe42xl37dgjueg2suqwnh4ze0sr`..?
(added it in a testcase)

**Comment by seedhammer** [comment]
Thank you very much, @Overtorment! I can confirm your zpub and first address matches our example xpub.
