### ISSUE TITLE
Specifying IPv6 Electrum server address requires Local Network access on iOS

### ISSUE THREAD

**Issue by jimbojw** [BlueWallet/BlueWallet#4995]
When specifying a custom Electrum server, BlueWallet will allow an IPv6 address. However, on iOS, this prompts the user to allow BlueWallet to access the Local Network, even if the IPv6 address is non-local.

If the user declines the Local Network popup, the Electrum configuration dialog will not allow an IPv6 address. Restarting the app will NOT help in this case. The app only shows the allow Local Network popup once. The only way to use IPv6 in this case is to go into the iOS Settings app, choose BlueWallet, then toggle the Local Network setting to turn it on.

If the user DOES permit BlueWallet to access the Local Network, the Electrum configuration dialog will accept an IPv6 address. Once this setting has been saved, the user may disallow Local Network permission in the iOS Settings for BlueWallet without consequence. Connecting to the IPv6 Electrum server will work even with the Local Network access toggled off. Enabling it only matters for setting the Electrum server location, not for actually accessing the Electrum server.

Desired behaivor: BlueWallet should NOT require Local Access permission on iOS to accept an IPv6 address.

Device details:
* Model: iPhone 12
* iOS version: 15.6
* BlueWallet app version: 6.3.1 (build 1656866507 master)
* Self-test: OK

**Comment by marcosrdz** [comment]
This is a limitation by Apple. We have no way of controlling this behavior.

**Comment by marcosrdz** [comment]
https://developer.apple.com/documentation/bundleresources/information_property_list/nslocalnetworkusagedescription
