### ISSUE TITLE
BTC transfer to Lightning does not clear

### ISSUE THREAD

**Issue by qze69** [BlueWallet/BlueWallet#500]
I’ve transferred BTC from my regular BTC walled to Lightning. Transaction is visible on both ends (in operations), but balance on Lightning does not top up.
![961BF02A-0A7C-4FE6-BD27-D3BAF79914B0](https://user-images.githubusercontent.com/50922927/58192163-67e2e980-7cc0-11e9-85f8-9a8d8e8597c4.png)

**Comment by Overtorment** [comment]
Might be cache. Try pull-to-refresh couple of times

**Comment by qze69** [comment]
Pull-to-refresh works on transactions. Balance did not get refreshed

**Comment by qze69** [comment]
Also tried exporting, deleting an app, installing, importing - did not help. Any suggestions?

**Comment by Overtorment** [comment]
Ok, looks like Ill have to investigate. Pls send wallet export to
bluewallet@bluewallet.io Ill take a look
