### ISSUE TITLE
Use of $ symbol is ambiguous

### ISSUE THREAD

**Issue by BrotherCreamy** [BlueWallet/BlueWallet#5007]
$ symbol can represent many different currencies (USD, AUD, ARS, CAD, CLP, COP, MXN, NZD...)

While using the app, especially if you're from a non-US country that has a dollar currency, it can get confusing.

Suggest putting the currency code next to the symbol - e.g. USD $ - or just using the code rather than the symbol to avoid this ambiguity.

**Comment by Transisto** [comment]
https://github.com/BlueWallet/BlueWallet/issues/4259

Very obvious one.

**Comment by Overtorment** [comment]
closingas duplicate
