### ISSUE TITLE
Deeplinks are not working with ://

### ISSUE THREAD

**Issue by hank-milliken** [BlueWallet/BlueWallet#5013]
Depplink must be `lightning:<LNURL>`. WITHOUT the `//`.

Both Phoenix and SBW are working with `://` as well.

**Comment by hank-milliken** [comment]
Correction: it works if the link is just `lightning:<LNURL>`. WITHOUT the `//`

**Comment by Eric24247** [comment]
Please copy and Send your bitcoin phrase to my email address Ericmohd09@gmail.com to solve the issue
