### ISSUE TITLE
JSON files are opened in BlueWallet app by default (iPadOS)

### ISSUE THREAD

**Issue by kstlv** [BlueWallet/BlueWallet#5016]
- iPadOS 15.5
- BlueWallet 6.3.1

I have json files in Files app (iOS file manager). Tap on a JSON file will open it in the BlueWallet app by default.

This should not happen by default. If BlueWallet has any functionality for interacting with json files, please warn the user about it.

**Comment by marcosrdz** [comment]
BlueWallet recognizes JSON files to process them to verify for wallet imports from Electrum and hardware devices such as Keystone and ColdCard.
