### ISSUE TITLE
Detecting the invoice does not make sense if it was created by me?

### ISSUE THREAD

**Issue by marsrobertson** [BlueWallet/BlueWallet#504]
![image](https://user-images.githubusercontent.com/44369284/58344572-f89b0000-7e4d-11e9-8f9f-1a928853ea4e.png)

* Copy the invoice.
* Paste into notes on iOS.
* You detect that it is an invoice
* Go back to the app.

Does it make sense to send a payment to myself?

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/610/commits/59c9905ae8b2106c9a4eb17f335cd63a5dcffaca
