### ISSUE TITLE
Allow cleartext traffic (http) for local ip addresses

### ISSUE THREAD

**Issue by JssDWt** [BlueWallet/BlueWallet#5082]
## Are you reporting a bug?

Please provide:

* Nokia 5.3, Android 11
* BlueWallet version 6.3.1 (build 1656883322 master)
* self-test passes? Yes
* unique ID: 5ff9efe40c793e3c

I'm getting 'Network request failed' instantly when trying to connect to LndHub on a local ip address.
This happens when I try to create an invoice or send a payment. Also when I try to import the wallet again.
- I confirmed I'm able to access LndHub on the device.
- I confirmed I'm able to connect and add invoices and send payments with the same credentials through Postman.
- I was able to connect to the same LndHub instance 4 months ago.
- LndHub is up-to-date with master.
- My connection string is in the form of `lndhub://username:password@http://192.168.x.x:3000`

**Comment by JssDWt** [comment]
I'm guessing this happens because it is a `http` url and not `https`

**Comment by JssDWt** [comment]
I verified this happens because in `android/app/src/main/res/xml/network_security_config.xml` cleartext traffic is only permitted for 10.0.2.2, localhost, onion and tailscale.net. So for my local ip address it's not allowed to do http traffic. Is that something you no longer support? What would be an alternative?

**Comment by Overtorment** [comment]
@JssDWt youve solved it!
i'd say its safe to assume that with local addresses like 192.168.x.x people know what they are doing, so we can make a cleartext traffic exception

can we put wildcards there? @JssDWt do some research and make a PR - ill merge it
