### ISSUE TITLE
API failure: Error undefined

### ISSUE THREAD

**Issue by Stay-Ugly** [BlueWallet/BlueWallet#5089]
Hi, I was trying to send some bitcoins and every time I was getting the error "API failure: Error undefined". So I tried to uninstall and install but the error keep happening when I try to import my wallet. 

* phone model and OS version:
 Xiaomi Redmi Note 11, Android 12
 
* BlueWallet app version: 6.3.1

* self-test passes? Open settings->about->scroll down, tap "Run self-test"
![blue2](https://user-images.githubusercontent.com/76099999/194422238-561985ed-b6d7-43cf-9dbc-2ac1885a7730.jpg)

* unique ID for our crash reporting service
userId:3473db9d82926f62

![blue](https://user-images.githubusercontent.com/76099999/194422089-5d2231cd-4575-469c-97aa-d7ab4d9af2e6.jpg)

**Comment by Overtorment** [comment]
you probably caught the period when lndhub was down

**Comment by ZedZeroth** [comment]
> you probably caught the period when lndhub was down

Sorry to necro this, but is lndhub currently down as I'm getting the same error? Thanks

**Comment by ZedZeroth** [comment]
Relevant links for other people who end up here:

https://bluewallet.io/sunsetting-lndhub/

https://bluewallet.io/docs/recover-lndhub/
