### ISSUE TITLE
Can't add any wallet with custom LndHub node

### ISSUE THREAD

**Issue by clonmac** [BlueWallet/BlueWallet#509]
When clicking the button to add a new wallet, it just sits there and spins indefinitely. This only seems to happen when you have a custom LndHub node specified in the Lightning Settings. I've tried this on both the latest versions of iOS and Android. If I clear out the LndHub Lightning Settings and just go with the default Bluewallet node, adding a wallet works just fine. This seems to have just stopped working recently, though I'm not sure which version exactly it started with. I've had a lighting wallet created with my own person LndHub server and it continues to work just fine. I just can't create any new wallets with personal LND node settings filled in.

**Comment by Overtorment** [comment]
Sorry I broke it accidentally. Fixed here
https://github.com/BlueWallet/BlueWallet/pull/508
 Will be out in 4.0.3 this week

**Comment by clonmac** [comment]
No worries. Very cool. Thank you.
