### ISSUE TITLE
Tx confirmations bug report

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#51]
Reported by a tester:

> I received a transaction.  It says "confirmations: 7" on the "transaction details" page.  That's not possible, I just sent it
> (and I checked).  The balance did not update in the colored box.  I can't get it to update by switching wallets and switching back
> or refreshing transactions.  I have no Send button.  If this was a big transaction, I would be panicking.

**Comment by marcosrdz** [comment]
Fixed in commit ca365a5615f260d9adfc5f6a6ccb78364109422b
