### ISSUE TITLE
Traditional Chinese is not supported

### ISSUE THREAD

**Issue by EthereumD** [BlueWallet/BlueWallet#510]
Chinese is divided into traditional Chinese simplified Chinese.I hope that you can support Traditional Chinese in the future.

**Comment by lychees** [comment]
Where is the i18n source file?

**Comment by ncoelho** [comment]
Here's the english version
https://github.com/BlueWallet/BlueWallet/blob/master/loc/en.js

And the Chinese version we have at the moment
https://github.com/BlueWallet/BlueWallet/blob/master/loc/zh_cn.js

**Comment by ChenPoWei** [comment]
> Here's the english version
> https://github.com/BlueWallet/BlueWallet/blob/master/loc/en.js
> 
> And the Chinese version we have at the moment
> https://github.com/BlueWallet/BlueWallet/blob/master/loc/zh_cn.js

The Chinese js file inside is Simplified Chinese.
I am doing a traditional Chinese js file and pushing it up.

**Comment by ncoelho** [comment]
Great, if you can change the description labels on the menu to indicate both versions as well, even better
