### ISSUE TITLE
bech32 wallet: TypeError when transaction input has no witness

### ISSUE THREAD

**Issue by peterdmv** [BlueWallet/BlueWallet#512]
https://github.com/BlueWallet/BlueWallet/blob/57f1296ee225074d4ad588e25c70cac9e49b7959/BlueElectrum.js#L133

```javascript
YellowBox.js:67 TypeError: Cannot read property '1' of undefined
    at Object.getTransactionsFullByAddress$ (BlueElectrum.js:133)
    at tryCatch (runtime.js:45)
    at Generator.invoke [as _invoke] (runtime.js:271)
    at Generator.prototype.<computed> [as next] (runtime.js:97)
    at tryCatch (runtime.js:45)
    at invoke (runtime.js:135)
    at runtime.js:145
    at tryCallOne (core.js:37)
    at core.js:123
at JSTimers.js:298

```

It happens when trying to import a bech32 wallet with zpub and the first transaction has an input from a legacy address (no witness). This issue might very well be related to #490  and #501.

**Comment by Overtorment** [comment]
Thanks!
How do I reproduce? Create new bip84, and deposit some btc from legacy (1abc.......) address..?
Or can you share your zpub to **i at bluewallet dot io**?

**Comment by Overtorment** [comment]
Ok reproduced. Indeed had to send to my BIP84 a tx from legacy address

**Comment by Overtorment** [comment]
Will fix asap

**Comment by Overtorment** [comment]
https://github.com/BlueWallet/BlueWallet/pull/514

**Comment by Overtorment** [comment]
should be fixed  in https://github.com/BlueWallet/BlueWallet/pull/514.
will rollout in v4.0.4

**Comment by peterdmv** [comment]
Tested on master it works! Thanks for the fast fix!
