### ISSUE TITLE
Bluewallet can't read QR-Code from BTCPAYSERVER correctly

### ISSUE THREAD

**Issue by thmsmullee** [BlueWallet/BlueWallet#5120]
* Many Phones tested
* BlueWallet app version  6.3.1
* self-test passes? yes

QR Code INVOICE from BTCPAYSERVER (Lighning) says 6€
Scanning with Bluewallet retrieves 5,68 €
After sending I get the attached error
With "Wallet of Satoshi" it works fine

![Screenshot_20221015-102839](https://user-images.githubusercontent.com/97939631/195979054-e87aff88-8dcc-41b1-b501-15f3cc5dfc33.png)
![Screenshot_20221015-102905](https://user-images.githubusercontent.com/97939631/195979055-b670ba8e-d930-4787-9cb2-9231b09d65a4.png)

**Comment by Overtorment** [comment]
where can i test this? 
any specific shop i can go to and try to pay?

**Comment by thmsmullee** [comment]
Hi, thanks for the reply.  It's a printed QR Code. But I can send you also
a link to my btcpayserver. Right now I'm in testing phase, so I don't have
any Channels. But the QR Code should work anyway!??
When I'm at home I will send you a link for testing.
Thanks

Overtorment ***@***.***> schrieb am Sa., 15. Okt. 2022, 14:30:

**Comment by thmsmullee** [comment]
I don't want to post the link to BTCPAYSERVER online, where can I send it ? THANKS

**Comment by Overtorment** [comment]
send it to i@bluewallet.io

**Comment by thmsmullee** [comment]
Where is the solution ? ;-)
I don't get it!
It still doesnt't work. If I scan the QR Code with "Wallet of Satoshi", the amount is right, if I scan with Bluwallet it's only 5,81€, not 6€.
What do I have to do ?
Greetings

**Comment by Overtorment** [comment]
@thmsmullee the fix was merged to master in https://github.com/BlueWallet/BlueWallet/pull/5130
you can try apk from there or wait for appstore/googleplay release
