### ISSUE TITLE
Where is my Coin?

### ISSUE THREAD

**Issue by Ready4ever101** [BlueWallet/BlueWallet#5132]
I have sent screenshots to your email, I am sad and depressed due to the inconvenience caused by this. 
TRANSACTION ID: 566291f374cd1c315be005a14e298929408fdc856d006bec2aac4118d940ed96

**Comment by Ready4ever101** [comment]
Legacy (P2PKH)

**Comment by Ready4ever101** [comment]
Someone help, I’m a total noob. Support is not responding.

**Comment by Overtorment** [comment]
did you import a watch-only wallet someone gave you?
and it got drained?

in that case, im afraid you were scammed. go to the police.
