### ISSUE TITLE
npm run test variables

### ISSUE THREAD

**Issue by ZainAliSyed24** [BlueWallet/BlueWallet#5133]
##  name: Run tests
      run: npm test || npm test || npm test
      env:
        HD_MNEMONIC: ${{ secrets.HD_MNEMONIC }}
        HD_MNEMONIC_BIP49: ${{ secrets.HD_MNEMONIC_BIP49 }}
        HD_MNEMONIC_BIP49_MANY_TX: ${{ secrets.HD_MNEMONIC_BIP49_MANY_TX }}
        HD_MNEMONIC_BIP84: ${{ secrets.HD_MNEMONIC_BIP84 }}
        HD_MNEMONIC_BREAD: ${{ secrets.HD_MNEMONIC_BREAD }}
        FAULTY_ZPUB: ${{ secrets.FAULTY_ZPUB }}
        MNEMONICS_COBO: ${{ secrets.MNEMONICS_COBO }}
        MNEMONICS_COLDCARD: ${{ secrets.MNEMONICS_COLDCARD }}

Please provide:

Can you please share these **variable values** if possible or **.env** file if you have

**Comment by Overtorment** [comment]
no, those are real life seeds with some bitcoin
