### ISSUE TITLE
Wrong fiat price updates in EUR from Coindesk API

### ISSUE THREAD

**Issue by jpelayo** [BlueWallet/BlueWallet#5137]
iPhone SE3 iOS 15.7 BlueWallet 6.3.1 (Self Test OK)

This applies to: Settings -> Currency view.

2022-10-22 15:32 CEST 
Bitcoin fiat price from CoinDesk within BlueWallet in EUROS (allegedly updated) -> 18727.98€
Bitcoin fiat price at CoinDesk website in EUROS same hour -> 19487.11€
USD price -> 19205,46$

Change to USD -> all ok
Change back to EUR -> wrong again

Settings -> Currency: EURO fiat price translation is not well calculated by Coindesk API (or updates are not being well processed).

**Comment by Overtorment** [comment]
could not reproduce

this is what API returns:
![image](https://user-images.githubusercontent.com/1913337/197381983-32547831-4113-41f5-9da0-c37b33a2bed2.png)

and this is what app currency module returns

![image](https://user-images.githubusercontent.com/1913337/197381994-3e5255dd-73e2-4d7c-9f59-674f1e77d9bb.png)

**Comment by jpelayo** [comment]
Well, what this shows you is that the API returns the wrong EUR value for Bitcoin. 

18677 is not the current 19173 EUR-USD exchange, as it is almost on-par.

Wrong fiat price provider.

**Comment by Overtorment** [comment]
aah

![image](https://user-images.githubusercontent.com/1913337/197386765-dc4954a2-4b2e-4c39-9a38-bee55d9f7ed2.png)

**Comment by Overtorment** [comment]
duplicate https://github.com/BlueWallet/BlueWallet/issues/5153
