### ISSUE TITLE
Network request faild

### ISSUE THREAD

**Issue by rifesama** [BlueWallet/BlueWallet#5161]
Hi, the wallet was working well untill 10/02/2022,but now I have a problem with my lightning wallet, I can't send or receive Satoshis, I tried to restore the wallet on another cell phone and I couldn't either, I always get this error "network request failed" attached screenshot.

I already sent an email to bluewallet@bluewallet.io but they have not given me support.

![photo1667143678](https://user-images.githubusercontent.com/116823776/198887431-a009c98f-bc89-41dc-9b63-2ca4419d1e3a.jpeg)
![photo1667143658](https://user-images.githubusercontent.com/116823776/198887445-e5957e6a-ad19-4275-b12f-1f12f972e808.jpeg)
![1](https://user-images.githubusercontent.com/116823776/198887463-08a52a1c-3aa8-4a84-84fe-288d8e8c87c1.jpg)

* Redmi N OTE 10S -  OS Android 12
* BlueWallet 6.3.1  
* self-test passes? yes
* userId:dff8532a6695a0ea

**Comment by Overtorment** [comment]
to your backup string like `lndhub://username:password` try adding `@http://lndhub.io`

so it looks like `lndhub://username:password@http://lndhub.io`

**Comment by rifesama** [comment]
Hi, thanks for answer.

yes. my backup looks like lndhub://username:password@http://lndhub.io

but when I try to import the wallet I get this error (import error - networ request faild)
![Uploading import wallet.jpg…]()

**Comment by Overtorment** [comment]
correction: there should be `https`, NOT `http`
can you open https://lndhub.io from your phone browser? its not blocked or smth?

**Comment by rifesama** [comment]
thank you, that was the issue. 

I just added an S to http and I could restore the wallet
