### ISSUE TITLE
I've got scammed and my wallet it's just watch only and I've paied a lot of money to get a card that unblock it, But i can't get my wallet back

### ISSUE THREAD

**Issue by Leticiaamfaria** [BlueWallet/BlueWallet#5168]
## Are you reporting a bug?

Please provide:

* your phone model and OS version
* BlueWallet app version (settings->about->scroll down)
* self-test passes? Open settings->about->scroll down, tap "Run self-test"
* unique ID for our crash reporting service (settings->about->scroll down, tap "copy")

## Proposing a feature?

Go right ahead

**Comment by ncoelho** [comment]
- Sorry about that. But this issue is not related to Bluewallet.
