### ISSUE TITLE
[Feature]  Generate uniformly random data: Removing the bias from crypto.randomBytes

### ISSUE THREAD

**Issue by tadeubas** [BlueWallet/BlueWallet#5169]
The current version of BlueWallet uses Node.js crypto ([here](https://github.com/BlueWallet/BlueWallet/blob/master/class/rng.js#L17)) library that is ["a wrapper for OpenSSL cryptographic functions"](https://nodejs.org/en/knowledge/cryptography/how-to-use-crypto-module/). The OpenSSL, as any library, is susceptible to bugs and it is worth mentioning that the dependency was already been removed from Bitcoin-Core. And we all know that no library can provide true random data, but [just pseudorandom](https://nodejs.org/api/crypto.html#cryptorandombytessize-callback)

But [this article](https://pit-claudel.fr/clement/blog/generating-uniformly-random-data-from-skewed-input-biased-coins-loaded-dice-skew-correction-and-the-von-neumann-extractor/) shows that it is possible and simple to remove bias from any stream of random bits using Von Neumann's bias-suppressing algorithm. The idea is just "pack digits two-by-to, discard any pair of two equal digits (00 or 11), and finally convert 01 to 0 and 10 to 1".

![image](https://user-images.githubusercontent.com/5518496/200173002-13b7506a-56f3-405d-8247-e1fc7b66756b.png)

The only inconvenient of this method is the need to generate more pseudorandom data than you need to end up with sufficient data to remove the bias (but a simple loop can check if more pseudorandom data needs to be generated).

**Comment by Overtorment** [comment]
original `crypto` module is only used in nodejs environment, and thats used only for unit tests.
in react native environment  `crypto` doesnt exist so we shim it using react-native-crypto  https://github.com/BlueWallet/BlueWallet/blob/9774b40c6320c056ed8c724fe14462e8f4731c51/package.json#L202 and actual `randomBytes` call is implemented by `react-native-randombytes`

**Comment by tadeubas** [comment]
I've followed the references and `react-native-randombytes` ([here](https://github.com/BitGo/react-native-randombytes/blob/master/app/src/main/java/com/bitgo/randombytes/RandomBytesModule.java#L9 )) uses Java [SecureRandom Class](https://docs.oracle.com/javase/8/docs/api/java/security/SecureRandom.html), "This class provides a cryptographically strong random number generator (RNG)" that "complies with [...]  [FIPS 140-2, Security Requirements for Cryptographic Modules](https://csrc.nist.gov/Projects/cryptographic-module-validation-program/announcements/announcements-archive)" and "produce non-deterministic output [...] and all SecureRandom output sequences must be cryptographically strong, as described in [RFC 1750: Randomness Recommendations for Security](http://www.ietf.org/rfc/rfc1750.txt)".

So this is much better than I thought... the `setSeed()` method for example "Reseeds this random object. The given seed supplements, rather than replaces, the existing seed. Thus, repeated calls are guaranteed never to reduce randomness."

So I think the usage of Von Neumann's bias-suppressing algorithm is useless in this case, so I am closing the issue
