### ISSUE TITLE
Interface issues on iOS for iPhone SE (4inch screen size)

### ISSUE THREAD

**Issue by pavaopahljina** [BlueWallet/BlueWallet#518]
Hey!

I'd just love for you to look at the app on 4inch screen size, it has several items not sizing properly, and tap area for some buttons is hard to tap.

Thank you!

**Comment by marcosrdz** [comment]
Thank you for reporting this. Will look into it.

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/commit/23ebcd49874d72a0503f84131aa9d8ac853f05b4
