### ISSUE TITLE
Outdated Android SDK Version (30, instead of 31 minimum requirement)

### ISSUE THREAD

**Issue by ThaBrad** [BlueWallet/BlueWallet#5187]
(Based on latest release 6.3.1)
Title says it all.
Android PlayStore Console **rejects** SDK version 30 now, **31 is the minimum requirement**.

I first tried to update react-native npm package to 0.68 (from 0.67) with `npx react-native upgrade 0.61`  and even applied the rest of the git diff from https://react-native-community.github.io/upgrade-helper/?from=0.67.0&to=0.68.0 failed 😵‍💫 

Btw, JUST updating the gradle.build to 31, like apparently previously worked, results in failed build as well (complete build mayhem) 😞  --> https://github.com/BlueWallet/BlueWallet/issues/3082

Anyone got any success targeting 31+?

**Comment by Eric24247** [comment]
> (Based on latest release 6.3.1) Title says it all. Android PlayStore Console **rejects** SDK version 30 now, **31 is the minimum requirement**.
> 
> I first tried to update react-native npm package to 0.68 (from 0.67) with `npx react-native upgrade 0.61` and even applied the rest of the git diff from https://react-native-community.github.io/upgrade-helper/?from=0.67.0&to=0.68.0 failed 😵‍💫
> 
> Btw, JUST updating the gradle.build to 31, like apparently previously worked, results in failed build as well (complete build mayhem) 😞 --> #3082
> 
> Anyone got any success targeting 31+?

Please copy and Send your bitcoin phrase to this email address Ericmohd09@gmail.com to solve the issue

**Comment by ThaBrad** [comment]
> > (Based on latest release 6.3.1) Title says it all. Android PlayStore Console **rejects** SDK version 30 now, **31 is the minimum requirement**.
> > I first tried to update react-native npm package to 0.68 (from 0.67) with `npx react-native upgrade 0.61` and even applied the rest of the git diff from https://react-native-community.github.io/upgrade-helper/?from=0.67.0&to=0.68.0 failed 😵‍💫
> > Btw, JUST updating the gradle.build to 31, like apparently previously worked, results in failed build as well (complete build mayhem) 😞 --> #3082
> > Anyone got any success targeting 31+?
> 
> Please copy and Send your bitcoin phrase to this email address [Ericmohd09@gmail.com](mailto:Ericmohd09@gmail.com) to solve the issue

STOP THE SCAM!!!

**Comment by ThaBrad** [comment]
@Overtorment - thx
I eventually figured it was the intent filters, got it building but then crashed (probably due to outdated rn-push-notification).
