### ISSUE TITLE
Make LN address support visible

### ISSUE THREAD

**Issue by raduButucelea23** [BlueWallet/BlueWallet#5190]
## Are you reporting a bug?
Yes

Please provide:

* your phone model and OS version
Iphone 12 mini
* BlueWallet app version (settings->about->scroll down)
6.3.1

## Proposing a feature?
![RB_blueWallet_LN](https://user-images.githubusercontent.com/44141337/203043394-426a51e6-755f-40c0-b6b0-fbdbd0c6fb66.jpeg)

Although supported, I could not find any UI hint that BlueWallet accepts LN addresses as inputs. This issue can be used to track this improvement.

**Comment by marcosrdz** [comment]
@ncoelho  "Invoice or address"?
