### ISSUE TITLE
Allow Updating URL

### ISSUE THREAD

**Issue by gohenderson** [BlueWallet/BlueWallet#5197]
Allow updating the URL in the Android app? Would be helpful in server domain name changes or port number changes.

**Comment by Overtorment** [comment]
what url?

**Comment by gohenderson** [comment]
A self hosted instance/url. Not the official LndHub.io instance.

**Comment by gohenderson** [comment]
So, the URL under Network/Lightning Settings.

**Comment by marcosrdz** [comment]
@Overtorment  I believe he means being able to update the server in the wallet details. Perhaps you migrated your server to a different domain. Eliminating the need to reimport the wallet (which would lead to losing the label, unit preference and more)

**Comment by blob42** [comment]
I have the same issue. When I try to export and reimport the wallet using the new lndhub url I get `bad auth (code 1)`

How can I recover a wallet where the lndhub url is not the same ?

**Comment by Overtorment** [comment]
if you need to change url of a conenction in self-hosted lndhub wallet, deleting and re-importing is what works.
making a feature to change it on the fly is too much work for a too narrow use case.

if you have funds stuck at default lndhub that is now shut down, follow this link: https://bluewallet.io/docs/recover-lndhub/

**Comment by blob42** [comment]
> deleting and re-importing is what works.
@Overtorment thanks for the reply. Do you mean deleting the wallet then reimporting from a backup ?
