### ISSUE TITLE
Error: Unable to resolve module ../../release-notes from H:\BlueWallet\screen\settings\releasenotes.js: ../../release-notes could not be found

### ISSUE THREAD

**Issue by BenGWeeks** [BlueWallet/BlueWallet#5201]
* Android Studio > Pixel XL API 31
* Windows 11
* react-native version: 6.4.0
* node version: 16.15.0
* npm version: 9.1.2

Hi there, I am looking to get this emulated on Windows 11 (steps added [here](https://github.com/BlueWallet/BlueWallet/issues/4416)). Have made good progress, although I am receiving the following:

![image](https://user-images.githubusercontent.com/5950171/203953804-1168b8a9-76ac-4422-b2ed-855a60967729.png)

Also related:

![image](https://user-images.githubusercontent.com/5950171/204090234-c13949c6-3c83-42e7-a95c-7d47ed879993.png)

Any ideas much appreciated.

Related: https://github.com/facebook/react-native/issues/29977

Thanks.

Ben

**Comment by Overtorment** [comment]
release notes are generated by a postinstall script.
check if they actually generated and the file `release-notes.json` is there.

**Comment by BenGWeeks** [comment]
There is a `releasenotes.js` in `*:\BlueWallet\screen\settings`, but no `release-notes.json`.

NB I have run the following:

```
$ ./release-notes.sh
* Update dependency @keystonehq/bc-ur-registry to v0.5.3
* REF: bump targetSdkVersion
* REF: bump targetSdkVersion
```

(The dependency note is odd since we have `"@keystonehq/bc-ur-registry": "0.5.3"` in `package.json`).

I have also tried remove the contents of `node_modules` and rebuilding.

There is no folder `node_modules\release-notes`.

Should `release-notes` be listed in package.json and or `npm i release-notes` be run?

**Comment by Overtorment** [comment]
`/release-notes.sh` is a script that just prints all commit logs since the last tagged release.

`npm run releasenotes2json` actually takes this script output and puts it into `release-notes.json`

worst case scenario you just manually create `release-notes.json` file and put smth like `[]` in there
