### ISSUE TITLE
Can't properly import multisig from Nunchuck, then can't delete it

### ISSUE THREAD

**Issue by AngusP** [BlueWallet/BlueWallet#5228]
Please provide:

* your phone model and OS version
    * iPhone 14 Pro, iOS 16.1.2
* BlueWallet app version (settings->about->scroll down)
    * 6.3.2
* self-test passes? Open settings->about->scroll down, tap "Run self-test"
    * Yes, "OK"
* unique ID for our crash reporting service (settings->about->scroll down, tap "copy")
    * `userId:63EB5136-20D1-46ED-9D49-AEE484696275`

---

Related issues: 
* #4255
* #4935
* #4396

---

I've created a dummy wallet to reproduce an issue I had with an *actual* multisig wallet.

Trying to import watch-only a BSMS for a 2-of-3 multisig I created in Nunchuck:

```
BSMS 1.0
wsh(sortedmulti(2,[3f5e4e09/48'/0'/0']xpub6BtEVX9WezWA2EYa8Wf1rJTokXpF96Rmqr4JKoR3SbjGw1vCa3Qb91mKN1AqJnBzSpqy44tEMB27Khne6KBmNzurXigfis7F28X5dRLWGoY/**,[b96bc7c7/48'/0'/0']xpub6CzCTuwFmAcBoxsfPLgiKfkJ2W3GbW1zxFKvCamZQ1J2XMobJR1gMNqP64pcFsy65ST4WcZtrCn99WXgLcWM6bqw6iFneAPTgJuLHggHD5S/**,[44437f41/48'/0'/0']xpub6Cn4cYgRhXKnvNjE4ULP2mzWHFw4WtCyp1nBuE97SyZVTPwq5xWkKsTVe9c16XSTr6V9AKMDgizav7z69j4AREaMKoFzUDbdcZhVq5xaKMU/**))
/0/*,/1/*
bc1qjppd555998lvpgdew30kdrvu2qg90n5gg684khrc2u5g7kj8cnuqujvz3p
```

I can share the seed words of the three keys too if that's useful.

Imports as a **Vault**, but you get a few issues, the first being that BlueWallet says *"Don't know how to make address"*.

Here's the coordination Export that BlueWallet comes up with:

```
# BlueWallet Multisig setup file
# this file contains only public keys and is safe to
# distribute among cosigners
#
Name: Multisig vault
Policy: 2 of 3
Derivation: m/48'/0'/0'
Format: unknown
# derivation: m/48'/0'/0'
3F5E4E09: xpub6BtEVX9WezWA2EYa8Wf1rJTokXpF96Rmqr4JKoR3SbjGw1vCa3Qb91mKN1AqJnBzSpqy44tEMB27Khne6KBmNzurXigfis7F28X5dRLWGoY
# derivation: m/48'/0'/0'
B96BC7C7: xpub6CzCTuwFmAcBoxsfPLgiKfkJ2W3GbW1zxFKvCamZQ1J2XMobJR1gMNqP64pcFsy65ST4WcZtrCn99WXgLcWM6bqw6iFneAPTgJuLHggHD5S
# derivation: m/48'/0'/0'
44437F41: xpub6Cn4cYgRhXKnvNjE4ULP2mzWHFw4WtCyp1nBuE97SyZVTPwq5xWkKsTVe9c16XSTr6V9AKMDgizav7z69j4AREaMKoFzUDbdcZhVq5xaKMU
```

`Format: unknown` suggests to me an import error and BlueWallet got most of it right but hasn't worked out that it's P2WSH -- with another test Vault I created for comparison in BlueWallet instead of Nunchuck has this field as `Format: P2WSH`.

**Summary of issues:**

* "Don't know how to make address"

<img src="https://user-images.githubusercontent.com/1328814/206765789-48387a65-b5df-4f0e-91f0-f802c4bb078b.PNG" width=300 />

* Tapping on "Wallet Options" -> "Show Addresses" causes an app crash
* Tapping on "Send" causes an app crash
* Tapping in "Receive" gets stuck loading

<img src="https://user-images.githubusercontent.com/1328814/206765610-c4e8d8bd-1dd3-4842-870c-f6e0b7fb0bb3.PNG" width=300 />

* Can't delete the Vault - gets stuck on a shade showing a loading spinner when you try.
    * The hack for getting past this from #4255 by encrypting the app storage and then getting the password wrong ten times also didn't work for me. It asked to delete, I tapped "Ok" but delete didn't seem to happen.

<img src="https://user-images.githubusercontent.com/1328814/206765661-fa1a609b-3315-4cc7-9dfa-f4ce17bb84d2.PNG" width=300 />

* Trying to import a multisig wallet with the same xpubs **but** different derivation paths fails with *"This wallet has previously been imported"*
     * *If* I'm understanding the Coldcard format correctly and you just repeat the `Derivation ...` line but use the same xpub and fingerprint?

I also tried importing the same multisig wallet as the initial BSMS but using a different import file I crafted in the format that a [Coldcard](https://coldcard.com/docs/multisig)'s docs say it makes:

```
# Coldcard Multisig setup file (exported from 3F5E4E09)
#
Name: multisig-test
Policy: 2 of 3
Derivation: m/48'/0'/0'
Format: P2WSH
3F5E4E09: xpub6BtEVX9WezWA2EYa8Wf1rJTokXpF96Rmqr4JKoR3SbjGw1vCa3Qb91mKN1AqJnBzSpqy44tEMB27Khne6KBmNzurXigfis7F28X5dRLWGoY
B96BC7C7: xpub6CzCTuwFmAcBoxsfPLgiKfkJ2W3GbW1zxFKvCamZQ1J2XMobJR1gMNqP64pcFsy65ST4WcZtrCn99WXgLcWM6bqw6iFneAPTgJuLHggHD5S
44437F41: xpub6Cn4cYgRhXKnvNjE4ULP2mzWHFw4WtCyp1nBuE97SyZVTPwq5xWkKsTVe9c16XSTr6V9AKMDgizav7z69j4AREaMKoFzUDbdcZhVq5xaKMU
```

Buuut this gets a *"This wallet has previously been imported"* error.

As a sidenote, my actual multisig has slightly different derivation paths than those above, though those were correctly imported judging by the coordination export for it.

I'm happy to help try fix this if you can point me at the right place, caveat being I've not touched a React native app in a while!

**Comment by AngusP** [comment]
> Buuut this gets a "This wallet has previously been imported" error.

I'm guessing this is because wallets are identified by the cosigner's fingerprints and fingerprints, but the derivation path isn't included in the ID. Feels to me like a valid if somewhat rare/odd/inadvisable use-case to have multiple multisig wallets with the same signers but different paths?

https://github.com/BlueWallet/BlueWallet/blob/b1122f58423f5a48df2a5b157cf9ef2fb276b52f/class/wallets/multisig-hd-wallet.js#L957-L960

**Comment by AngusP** [comment]
On the delete failure for Vaults that haven't imported correctly, my guess is

https://github.com/BlueWallet/BlueWallet/blob/b1122f58423f5a48df2a5b157cf9ef2fb276b52f/screen/wallets/details.js#L443

The `wallet.getBalance()` call returns `0` ok but `canSend()` always is `true` for the `MultisigHDWallet`.

https://github.com/BlueWallet/BlueWallet/blob/afab9b85379ae623fb424369cc97d77dcd7fca50/class/wallets/multisig-hd-wallet.js#L932-L934

So you try and warn the user that the wallet may have a balance:

https://github.com/BlueWallet/BlueWallet/blob/b1122f58423f5a48df2a5b157cf9ef2fb276b52f/screen/wallets/details.js#L237

And then get stuck trying to work out the balance when the app is unable to do that because it can't make any of the addresses to check

**Comment by AngusP** [comment]
Taking a look at this again, wondering if it might just be as simple as

```patch
diff --git a/screen/wallets/details.js b/screen/wallets/details.js
index 7d88b283..e268c9b5 100644
--- a/screen/wallets/details.js
+++ b/screen/wallets/details.js
@@ -227,7 +227,9 @@ const WalletDetails = () => {
 
   const navigateToOverviewAndDeleteWallet = () => {
     setIsLoading(true);
-    Notifications.unsubscribe(wallet.getAllExternalAddresses(), [], []);
+    try {
+      Notifications.unsubscribe(wallet.getAllExternalAddresses(), [], []);
+    } catch (_) {}
     popToTop();
     deleteWallet(wallet);
     saveToDisk(true);

```

Also, `Notifications.unsubscribe` returns a `Promise`, presumably it's OK/still works despite not being awaited?

---

I've tried getting the code to run but no success yet, neither Android nor iOS working for me. Not sure why, but I have newfound respect for app devs that put up with this crap tooling and faff all day

**Comment by AngusP** [comment]
Also just noticed it looks like the Watch app has got stuck, shows stale (~month old) state and doesn't show the broken imported multisig wallets

**Comment by Overtorment** [comment]
ive created a fix for import and added provided example as a testcase for unit tests (btw that helped a lot, thanks)
https://github.com/BlueWallet/BlueWallet/pull/5284

meanwhile, let me look what i can do with already broken wallets.
