### ISSUE TITLE
iOS App crashes when scaning QR Code

### ISSUE THREAD

**Issue by emilengler** [BlueWallet/BlueWallet#523]
Hello, when I scan a QR code with this content
` bitcoin:1NS17iag9jJgTHD1VXjvLCEnZuQ3rJED9L?amount=20.3X8&label=Luke-Jr`, my BlueWallet app crashes.
It is able to detect the QR Code because the screen gets white then and after 5 seconds the whole app crashes.
I am on iOS 12 on an iPhone 7 and I use BlueWallet 4.1.0

**Comment by emilengler** [comment]
No response yet, I will close now.
Please re-open if necessary.

**Comment by Overtorment** [comment]
Ack

**Comment by Overtorment** [comment]
![image](https://user-images.githubusercontent.com/1913337/60687881-69035b00-9ea9-11e9-8a22-099c471befcb.png)

**Comment by Overtorment** [comment]
@marcosrdz can u ps take a look..?

**Comment by Overtorment** [comment]
Ok, here's the problem: amount is `20.3X8` which is not a valid number. Not sure how is it supposed to be parsed. 
Anyway, we should make it not crash in such occasions

**Comment by marcosrdz** [comment]
I think we should ignore “amount” value in such cases and leave the default on (0 sats)

**Comment by Overtorment** [comment]
Maybe parseFloat..? Its btc transaction

**Comment by marcosrdz** [comment]
the bip21 decoder fails due to an invalid amount. Other wallets follow the approach I suggested.

**Comment by Overtorment** [comment]
Ok

**Comment by marcosrdz** [comment]
38d9416
