### ISSUE TITLE
Improve scanning for QR devices by implementing BC-UR fountain-code fragments

### ISSUE THREAD

**Issue by bitcoinhelp** [BlueWallet/BlueWallet#5240]
_(This was posted by the Jade team on nunchuk's repo, adding here as well as it would help all QR based signing devices)_

I notice that the UR fragment creation stops when encoder.is_complete(). ie. you produce the minimum number of fragments to convey the data payload, and no more - you don't produce any fountain-code fragments whatsoever.
This is bad for scanning devices as it leads to the 'coupon collectors problem' (where we have to play through the animation of N frames when we only need one particular frame/fragment).
The addition of fountain code fragments (as intended by BC/UR) addresses this issue, as reading a fountain-code fragment allows the scanner to reconstitute virtually any missing frame.
eg. as it stands, if a psbt needs say 10 fragments, but I miss one or two fragments, I have to watch the entire cycle again hoping to catch those fragments next time around. If not, we have to play the sequence again ...
With fountain-code frames, you may produce say 20 fragments (10 'pure data' [as currently], and 10 'fountain codes'), and again I miss one or two frames ... so long as I successfully scan (pretty much) any one or two of the following fountain-code fragments I will be able to reconstitute the missing fragment(s) and complete. ie. you produce 20 frames but the scanner only needs to pick up any 10 of them.
This is all handled by the BC-UR lib and needs no additional code in-app, other than deciding how many fountain-code frames to append.

This means we have to collect every single frame/fragment (rather than say, any 60% of them).

**Comment by Overtorment** [comment]
so far no one complains about it, so wont do anything about it
