### ISSUE TITLE
Icon Size MacOS

### ISSUE THREAD

**Issue by LucaBertoni08** [BlueWallet/BlueWallet#5246]
I don't know if the desktop app is still supported, anyway the icon size is bigger then it should be on macOS Ventura

**Comment by Overtorment** [comment]
@marcosrdz

**Comment by marcosrdz** [comment]
Should be resolved once a new macOS build is generated using the latest Xcode.

**Comment by LucaBertoni29** [comment]
Hi, the icon size is still too big

**Comment by ghqe** [comment]
Same here

**Comment by Overtorment** [comment]
@marcosrdz
