### ISSUE TITLE
Unable to close Lightning Network channel or retrieve funds from it

### ISSUE THREAD

**Issue by jbrepogmailcom** [BlueWallet/BlueWallet#5275]
## Are you reporting a bug?
Yes

Please provide:

* your phone model and OS version
* BlueWallet app version (settings->about->scroll down) 6.3.2
* self-test passes? Open settings->about->scroll down, tap "Run self-test"
* unique ID for our crash reporting service (settings->about->scroll down, tap "copy")

## Proposing a feature?

Go right ahead

Hello I am unable to close LN channell or retrieve funds by any other way. How to do it please? Thank you

**Comment by Overtorment** [comment]
Send your lightning funds somewhere else

**Comment by jbrepogmailcom** [comment]
Hello, thanks for advice, but I do not quite understand it. How do I close channell and retrieve the funds by sending it somewhere else? Thank you
