### ISSUE TITLE
Bluewallet registers itself with bankid and swish schemes.

### ISSUE THREAD

**Issue by NickeZ** [BlueWallet/BlueWallet#5310]
Hello,

I've noticed that BlueWallet registers itself as a handler for events which it cannot handle, like identification with Swedish BankID and paying with Swedish Swish.

In other apps, when I'm supposed to be forwarded to BankID or Swish, Android suggests either BankID/Swish or BlueWallet. In all those cases I want to open the app that can actually handle the authentication and/or payment flow.

I think this PR introduced the bug: 

https://github.com/BlueWallet/BlueWallet/pull/4246

I'm not sure if ios is affected or if it is only Android.

**Comment by Overtorment** [comment]
indeed, we have a handling of that deeplink specifically for Safello fiat-onramp, see
https://github.com/BlueWallet/BlueWallet/wiki/Deeplinking#safello-flow
that simplified buying and KYC for Swedish citizens.

since we remove fiat onramps i should be removed as well

**Comment by NickeZ** [comment]
I see, not sure exactly what is the best practice here. But hijacking other apps url-schemes is probably not right.

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/5338
