### ISSUE TITLE
Payjoin error message

### ISSUE THREAD

**Issue by yashrajd** [BlueWallet/BlueWallet#5313]
## Do you need support? Just email bluewallet@bluewallet.io
Need tech support

## Are you reporting a bug?
No(t that I know of)

Please provide:

* recent iPhone on iOS16.x

## Proposing a feature?
Seeking clarification 

When sending to a payjoin receiver, I encountered an error, with this message (screenshot):
![IMG_5420](https://user-images.githubusercontent.com/114083781/219226013-b7ac472a-be75-439d-b75f-92a1fd5e4953.PNG)

What does it mean?

**Comment by NicolasDorier** [comment]
If a payjoin fail, it shouldn't have impact and falback to normal broadcast. I think this should be fixed at blue wallet level.

**Comment by DanGould** [comment]
Yes, it could also try payjoin by default instead of requiring the toggle. As far as I've tested, bluewallet's payjoin integration is broken and won't work with any https endpoints.

**Comment by Overtorment** [comment]
reproduce: https://hrf.org/payjoin

**Comment by DanGould** [comment]
@Overtorment I think I found the bug🐛

`PayjoinClient` constructor requires a parameter called `wallet`

https://github.com/bitcoinjs/payjoin-client/blob/b15b03f6d9552c278a867b2b0d61f08d4e319311/src/client.js#L7-L12

but is being passed `payJoinWallet` instead

https://github.com/BlueWallet/BlueWallet/blob/bd7ea23d9719ddcac489fb1cd5551e2b5cb18ab8/screen/send/confirm.js#L141-L151

The test does not make the same mistake so it passes:

https://github.com/BlueWallet/BlueWallet/blob/bd7ea23d9719ddcac489fb1cd5551e2b5cb18ab8/tests/unit/payjoin-transaction.test.js#L57-L61
