### ISSUE TITLE
Help me, I get an error when importing my lightining wallet

### ISSUE THREAD

**Issue by Lucas-Ed** [BlueWallet/BlueWallet#5328]
hello, I need to remove some satochis from my lighting wallet from the blue wallet, because of the deactivation of lndhub, however, my wallet lighting, I am not able to restore it in the bluewallet, I don't know if it's an import error or my typing, here is an example of how I saved the key here for example:

##------------------------------------------##
lndhub://346fdgbtht5667:a68hdshhh778gh

-@https://lndhub.io
##------------------------------------------##
however when I import I put: https://lndhub.io/346fdgbtht5667:a68hdshhh778gh

and the error, I tried in several ways to import but as the creation of a new lighting wallet is disabled
inside the blue wallet, I don't know how to import, help me please!

**Comment by Lucas-Ed** [comment]
I found out here how to type correctly with this tutorial: https://www.youtube.com/watch?v=6KL6JHU_GfY&t=106s
however, there is an error when importing the lghtining wallet, in bluewallet, this error appears on the screen:
import error
network request failed

**Comment by IntinteDAO** [comment]
I have PHP script to withdraw funds if you want. But sadly I don't know how to check how many funds do you have, but you can pay invoices XD

**Comment by IntinteDAO** [comment]
```
<?php

error_reporting(E_ALL);

function get_json($url, $content=null, $method='POST') {

	global $access_token;

	$opts = array(
	        'http'=>array(
		                'method'=>$method,
		                'header'=>'Content-Type: application/json'
	        )
	);

	        if($content !== null) {
		                $opts['http']['content'] = $content;
	        }

	        if($access_token)$opts['http']['header'].="\r\n".'Authorization: Bearer '.$access_token;

	        $context = stream_context_create($opts);
	        $body=@file_get_contents($url,false,$context);

	        if($body) {
		                return json_decode($body,true);
	        }

		                return false;
}

$url='https://lndhub.io/';

$lndhub_user = '9a8155c00def56bcfd93';
$lndhub_pass = '06386755a184a20ae3a3';

	// Authorize
	$params = new stdClass();
	$params->login = $lndhub_user;
	$params->password = $lndhub_pass;
	$json = get_json($url."auth?type=auth",json_encode($params));
	$access_token = $json['access_token'];


function payinvoice($invoice) {

	global $url;
	$params = new stdClass();
	$params->invoice = $invoice;
	$json = get_json($url."payinvoice",json_encode($params));
	return $json;

}

$invoice = 'lnbc100n1p3l4xynpp5jnuatqd8ptdd86ec2gp60perl645w6yhqnxrqf4qyahms5mpcpdqdqltfshq5n9v9jzucm0d5sxgetsdaekjaqcqzpgxqrrsssp5wt4eq68xuxyrevqja0t57d83plt2d4ftpt6td4lwu23yw2p72m0s9qyyssqh35qk4qz47cuuhchfe6lnk4cgvay8senzgcwku5lplaxxl7y732k2g9683jz4calrrc8zqa2le9ncswmcxplww6y5570hrsafmw56hqqv9hmv8';

print_r(payinvoice($invoice));

```

Maybe you can withdraw few sats. In short in invoice you set invoice xD and login / pass is your login and password. Good luck

I don't know how to check how many sats are in account, but if you know that you have more than for example 100k, try to withdraw it (for Zapread for example). If it is successful, try on new invoice. If fail, reduce amount etc.

**Comment by Lucas-Ed** [comment]
thanks for sharing the script; so I don't remember how much is in wallet lighting, it's not more than 10,000 sats, I'll try here, but it clears my doubts,
let's say my import lighining key is: lndhub://346fdgbtht5667:a68hdshhh778gh

in the script would only change the:
$lndhub_user = '9a8155c00def56bcfd93';
$lndhub_pass = '06386755a184a20ae3a3';

per:

$lndhub_user = '346fdgbtht5667';
$lndhub_pass = 'a68hdshhh778gh';


and would you also change the $invoice to the address I want to send?

in case he would send the total balance?
would need to change the script to send a specific amount of sats right?

**Comment by Lucas-Ed** [comment]
hello, thank you very much, I managed to remove the satochis, with the script that you shared with me, it worked !!

**Comment by TommyBuho** [comment]
> ```
> <?php
> 
> error_reporting(E_ALL);
> 
> function get_json($url, $content=null, $method='POST') {
> 
> 	global $access_token;
> 
> 	$opts = array(
> 	        'http'=>array(
> 		                'method'=>$method,
> 		                'header'=>'Content-Type: application/json'
> 	        )
> 	);
> 
> 	        if($content !== null) {
> 		                $opts['http']['content'] = $content;
> 	        }
> 
> 	        if($access_token)$opts['http']['header'].="\r\n".'Authorization: Bearer '.$access_token;
> 
> 	        $context = stream_context_create($opts);
> 	        $body=@file_get_contents($url,false,$context);
> 
> 	        if($body) {
> 		                return json_decode($body,true);
> 	        }
> 
> 		                return false;
> }
> 
> $url='https://lndhub.io/';
> 
> $lndhub_user = '9a8155c00def56bcfd93';
> $lndhub_pass = '06386755a184a20ae3a3';
> 
> 	// Authorize
> 	$params = new stdClass();
> 	$params->login = $lndhub_user;
> 	$params->password = $lndhub_pass;
> 	$json = get_json($url."auth?type=auth",json_encode($params));
> 	$access_token = $json['access_token'];
> 
> 
> function payinvoice($invoice) {
> 
> 	global $url;
> 	$params = new stdClass();
> 	$params->invoice = $invoice;
> 	$json = get_json($url."payinvoice",json_encode($params));
> 	return $json;
> 
> }
> 
> $invoice = 'lnbc100n1p3l4xynpp5jnuatqd8ptdd86ec2gp60perl645w6yhqnxrqf4qyahms5mpcpdqdqltfshq5n9v9jzucm0d5sxgetsdaekjaqcqzpgxqrrsssp5wt4eq68xuxyrevqja0t57d83plt2d4ftpt6td4lwu23yw2p72m0s9qyyssqh35qk4qz47cuuhchfe6lnk4cgvay8senzgcwku5lplaxxl7y732k2g9683jz4calrrc8zqa2le9ncswmcxplww6y5570hrsafmw56hqqv9hmv8';
> 
> print_r(payinvoice($invoice));
> ```
> 
> Maybe you can withdraw few sats. In short in invoice you set invoice xD and login / pass is your login and password. Good luck
> 
> I don't know how to check how many sats are in account, but if you know that you have more than for example 100k, try to withdraw it (for Zapread for example). If it is successful, try on new invoice. If fail, reduce amount etc.



> ```
> <?php
> 
> error_reporting(E_ALL);
> 
> function get_json($url, $content=null, $method='POST') {
> 
> 	global $access_token;
> 
> 	$opts = array(
> 	        'http'=>array(
> 		                'method'=>$method,
> 		                'header'=>'Content-Type: application/json'
> 	        )
> 	);
> 
> 	        if($content !== null) {
> 		                $opts['http']['content'] = $content;
> 	        }
> 
> 	        if($access_token)$opts['http']['header'].="\r\n".'Authorization: Bearer '.$access_token;
> 
> 	        $context = stream_context_create($opts);
> 	        $body=@file_get_contents($url,false,$context);
> 
> 	        if($body) {
> 		                return json_decode($body,true);
> 	        }
> 
> 		                return false;
> }
> 
> $url='https://lndhub.io/';
> 
> $lndhub_user = '9a8155c00def56bcfd93';
> $lndhub_pass = '06386755a184a20ae3a3';
> 
> 	// Authorize
> 	$params = new stdClass();
> 	$params->login = $lndhub_user;
> 	$params->password = $lndhub_pass;
> 	$json = get_json($url."auth?type=auth",json_encode($params));
> 	$access_token = $json['access_token'];
> 
> 
> function payinvoice($invoice) {
> 
> 	global $url;
> 	$params = new stdClass();
> 	$params->invoice = $invoice;
> 	$json = get_json($url."payinvoice",json_encode($params));
> 	return $json;
> 
> }
> 
> $invoice = 'lnbc100n1p3l4xynpp5jnuatqd8ptdd86ec2gp60perl645w6yhqnxrqf4qyahms5mpcpdqdqltfshq5n9v9jzucm0d5sxgetsdaekjaqcqzpgxqrrsssp5wt4eq68xuxyrevqja0t57d83plt2d4ftpt6td4lwu23yw2p72m0s9qyyssqh35qk4qz47cuuhchfe6lnk4cgvay8senzgcwku5lplaxxl7y732k2g9683jz4calrrc8zqa2le9ncswmcxplww6y5570hrsafmw56hqqv9hmv8';
> 
> print_r(payinvoice($invoice));
> ```
> 
> Maybe you can withdraw few sats. In short in invoice you set invoice xD and login / pass is your login and password. Good luck
> 
> I don't know how to check how many sats are in account, but if you know that you have more than for example 100k, try to withdraw it (for Zapread for example). If it is successful, try on new invoice. If fail, reduce amount etc.

Is this still functional? I can not make it work. Help possible?
