### ISSUE TITLE
Accidental fund loss protection 

### ISSUE THREAD

**Issue by marcosrdz** [BlueWallet/BlueWallet#536]
If user is sending 1/4, or more, of their balance, provide a warning to let them know so. Ive read many horror stories of people not paying attention and sending a huge amount of BTC to an address. This horror story can be prevented by giving indicators of how much money you are about to send versus your balance.

**Comment by Overtorment** [comment]
Good idea. I was thinking about making some kind of sanity check during
send. Also, doublecheck that anount sent is greater than fee, or that fee
itself is not super huge

**Comment by ncoelho** [comment]
Yep, good idea! Like it
