### ISSUE TITLE
Use bip329 Wallet Label Export Format in BlueWallet

### ISSUE THREAD

**Issue by yoshimo** [BlueWallet/BlueWallet#5360]
## Proposing a feature?
Coin Control as well as keeping record of old transactions a common format for labels is helpful to move between wallets.
I therefore would like to have https://github.com/bitcoin/bips/blob/master/bip-0329.mediawiki used in BlueWallet

> Motivation
> 
> The export and import of funds across different Bitcoin wallet applications is well defined through standards such as BIP39, BIP32, BIP44 etc. These standards are well supported and allow users to move easily between different wallets. There is, however, no defined standard to transfer any labels the user may have applied to the transactions, addresses, public keys, inputs, outputs or xpubs in their wallet. The UTXO model that Bitcoin uses makes these labels particularly valuable as they may indicate the source of funds, whether received externally or as a result of change from a prior transaction. In both cases, care must be taken when spending to avoid undesirable leaks of private information. Labels provide valuable guidance in this regard, and have even become mandatory when spending in several Bitcoin wallets. Allowing users to import and export their labels in a standardized way ensures that they do not experience lock-in to a particular wallet application.

**Comment by Overtorment** [comment]
duplicate https://github.com/BlueWallet/BlueWallet/issues/5272
