### ISSUE TITLE
Make QR code on receive screen accessible

### ISSUE THREAD

**Issue by GBKS** [BlueWallet/BlueWallet#5388]
A blind person has no indication that there is a QR code on the screen - it does not exist for them. A blind bitcoiner actually just told me this, he was wondering why he was never able to use QR code features in Blue Wallet (a bunch of wallets don't get this right).

The solution should be straightforward, but I am not familiar with React Native and currently cannot get the local dev environment running, so I'd love some help on this. From looking the code, it appears that the QR code is rendered as an SVG. This SVG might need to be wrapped (maybe a View?). This wrapper should be made accessible (probably via `accessibilityRole="image"`), and a text label (probably via `accessibilityLabel`), for example `QR code of the receive address`. Maybe the SVG could also receive those attributes, not sure. This would allow the user to select the QR code via tabbing, and the screen reader would read out the label.

In the screenshot below you can see what a screen reader knows about what's on the screen. The QR code has no grey tooltip, meaning there's no information about it available.

![IMG_3777](https://user-images.githubusercontent.com/695901/226272426-c683889f-3646-4d9a-a5d7-c7a93e24bc15.PNG)

A consideration could be to wrap this more accessible functionality in a component somehow, so QR codes elsewhere in the app also get this update. A future addition could be to make the QR codes tappable to copy the address.

**Comment by GBKS** [comment]
If you'd like to test this functionality yourself on an iPhone, here are two short videos that show how to set up and test:
- [iPhone setup](https://www.youtube.com/watch?v=Ca1H6wF348g)
- [Test example](https://www.youtube.com/watch?v=n9FvI5SfpoU)

**Comment by soustab10** [comment]
I think if during setup of the wallet, the user identifies themselves as blind then an accessibility mode should open and prompt the user using audio about the content on the screen.

**Comment by GBKS** [comment]
@soustab10 I don't think that is necessary. Operating systems already provide plenty of accessibility options. People with those needs configure their OS accordingly, and applications need to support the settings.

I just tested on Android, and turns out the QR code is selectable there (but not on iOS). Still, the screen reader does not announce anything. So you select something but have no idea what it is. An interesting difference in behavior between iOS and Android.
