### ISSUE TITLE
Bluewallet worst problems

### ISSUE THREAD

**Issue by nostitos** [BlueWallet/BlueWallet#5406]
- Coin selection is dumb as a rock / broken
- 
- Manual coin selection only show fiat amounts.
- 
- Manual coin selection doesn't sort coins by anything, not even fiat amounts.
- 
- The display of the send amount get buggy often, especially when scanning a QR with an amount.
- 
- Exchange rates are off by 3-5% on many fiat currencies like the euro.
- 
- The fiat denomination only use $ so there's no way to know if it's CAD or USD for example.

**Comment by ncoelho** [comment]
Coin control (and all features) use the denomination you have selected on your wallet. If you use fiat, it shows fiat, if you use bitcoin it shows bitcoin.

**Comment by nostitos** [comment]
Good, half of an issue is done, 

Can we sort UTXO by BTC amount so that we can easily find the right size we need?
