### ISSUE TITLE
Bug: The Bitcoin Euro rate from Coindesk is not correct

### ISSUE THREAD

**Issue by GerdOpp** [BlueWallet/BlueWallet#5423]
The Bitcoin Euro rate from Coindesk displayed under settings:currency is not correct. It is always about 5% too high.

**Comment by marcosrdz** [comment]
This was fixed in: https://github.com/BlueWallet/BlueWallet/commit/38a8a02459cbe887be6cc08ca0a82933a2d48ca4 by @Overtorment
