### ISSUE TITLE
Apple Watch app not working

### ISSUE THREAD

**Issue by stylishgadgets0p** [BlueWallet/BlueWallet#5470]
Hello, i downloaded app for apple watch but app not working, it shows: “no wallet available, please add one by opening bluewallet on your iphone”, 
iOS app works fine, wallet is update, can you please help me? i try remove app, restart apple watch but nothing work.

Thank you.

AW 4, watchOS 9.4

**Comment by Overtorment** [comment]
@marcosrdz

**Comment by dvennikov** [comment]
Happening now to me as well.
AW 10. watchOS 11.1
