### ISSUE TITLE
Mismatch in release version and file name

### ISSUE THREAD

**Issue by kiblik** [BlueWallet/BlueWallet#5501]
## Do you need support? Just email [bluewallet@bluewallet.io](mailto:bluewallet@bluewallet.io)
No

## Are you reporting a bug?
Yes

## Information:
- Any MacOS
- BlueWallet version 6.4.1

## Bug

Latest release `6.4.1` https://github.com/BlueWallet/BlueWallet/releases/tag/v6.4.1 contains files with assets for different OS.
Unfortunately, files for MacOS (`.dmg` and `.dmg.sig`) have `6.4.2` in the filename.

Because of this, package managers (like `homebrew`) are broken because they expect that release name and file name will match:
```ruby
  url "https://github.com/BlueWallet/BlueWallet/releases/download/v#{version}/BlueWallet.#{version}.dmg",
```
https://github.com/Homebrew/homebrew-cask/blob/master/Casks/bluewallet.rb#L5

_How it fails:_
```bash
==> Upgrading bluewallet
==> Purging files for version 6.4.1 of Cask bluewallet
Error: bluewallet: Download failed on Cask 'bluewallet' with message: Failure while executing; `/usr/bin/env /usr/local/Homebrew/Library/Homebrew/shims/shared/curl ... --head --request GET https://github.com/BlueWallet/BlueWallet/releases/download/v6.4.1/BlueWallet.6.4.1.dmg` exited with 22. Here's the output:
curl: (22) The requested URL returned error: 404
```

In my opinion, this should not be fixed on Package manager site but in releases in this repository.

**Comment by Overtorment** [comment]
@marcosrdz
