### ISSUE TITLE
Android Lightning Invoice Payments Are Editable

### ISSUE THREAD

**Issue by jackeveritt** [BlueWallet/BlueWallet#552]
Problem:  The invoice amount on the pay screen is editable on Android (Not editable on iOS)

When opening Bluewallet on android via an Intent from another app to pay an invoice:

Uri lightningLink = Uri.parse("lightning:some invoice id goes here");
Intent lightningIntent = new Intent(Intent.ACTION_VIEW, lightningLink);
activity.startActivity(lightningIntent);

This opens the pay screen on BlueWallet.  It is possible for the user to edit the payment amount (See attached video - I changed the invoice amount to 100 sats from 10).

When the user changes the amount, only the original amount is paid, not the amount they changed it to. (See attached photo, where the latest transaction went through as 10 sats, not the 100 I changed it to).

I would expect android to behave the same as iOS and the field be un editable.
[Bug.zip](https://github.com/BlueWallet/BlueWallet/files/3430907/Bug.zip)

**Comment by ncoelho** [comment]
I believe this is fixed
