### ISSUE TITLE
Reorder screen broken

### ISSUE THREAD

**Issue by djkazic** [BlueWallet/BlueWallet#5529]
Please provide:

* your phone model and OS version: Pixel 6 android 13
* BlueWallet app version (settings->about->scroll down): 6.4.4
* self-test passes? Open settings->about->scroll down, tap "Run self-test": yes
* unique ID for our crash reporting service (settings->about->scroll down, tap "copy"): userId:acd295c774ae5e33

When I try to reorder the wallets it just pins the selected wallet via long click to the top and it is seemingly pinned there. When I let go my change is reverted so no reordering of wallets is achieved.

**Comment by puck2** [comment]
Same Issue:


    your phone model and OS version: Samsung Galaxy S22
    BlueWallet app version (settings->about->scroll down): 6.4.4
    self-test passes? Open settings->about->scroll down, tap "Run self-test": yes
    unique ID for our crash reporting service (settings->about->scroll down, tap "copy"): userId:d64fc267bedba4ee

**Comment by marcosrdz** [comment]
Does this still occur when using version 6.5.1?

**Comment by puck2** [comment]
No. Works now!.Thanks!Sent from a small glowing rectangle
-------- Original message --------From: Marcos Rodriguez Vélez ***@***.***> Date: 2/7/24  6:37 PM  (GMT-05:00) To: BlueWallet/BlueWallet ***@***.***> Cc: puck2 ***@***.***>, Comment ***@***.***> Subject: Re: [BlueWallet/BlueWallet] Reorder screen broken (Issue #5529) 
Does this still occur when using version 6.5.1?
