### ISSUE TITLE
Navigation heander doesn't change color when use multiple wallet types on Desktop

### ISSUE THREAD

**Issue by limpbrains** [BlueWallet/BlueWallet#5534]
<img width="657" alt="image" src="https://github.com/BlueWallet/BlueWallet/assets/155891/47b99e96-2cad-4c17-a15b-15474df68450">

* Macos 13.3.1
* BlueWallet Version 6.4.4 (714)

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/5981
