### ISSUE TITLE
BUG: Scan of descriptor QR from Sparrow Wallet not working

### ISSUE THREAD

**Issue by seedhammer** [BlueWallet/BlueWallet#5539]
BlueWallet (iOS v. 6.4.4) does not seem to import the standard descriptor exported from Sparrow Wallet.

- In BW: Add Wallet -> Import Wallet
- In BW: Scan or import a file
- In Sparrow: Open a multisig wallet and press the QR icon. <img width="467" alt="image" src="https://github.com/BlueWallet/BlueWallet/assets/93251679/83aed21f-c0b1-4352-9eed-86f39f459c7d">

- In BW: Now try to scan the animated standard QR from Sparrow.

Alternatively download the descriptor as PDF - this does not scan as well:
![image](https://github.com/BlueWallet/BlueWallet/assets/93251679/7263017b-4029-4bdf-8953-9248440a175b)

Sparrow export in the UR split descriptor format. 

https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-005-ur.md is the QR format.

https://github.com/BlockchainCommons/Research/blob/master/papers/bcr-2020-010-output-desc.md is the particular encoding for the descriptor.

**Comment by seedhammer** [comment]
Any timeframe ?

**Comment by mineracks** [comment]
Plus one from us

**Comment by FREEBORN-MAN** [comment]
Plus one from me
