### ISSUE TITLE
Cannot Access App When Authentication Prompt Flashes Repeatedly

### ISSUE THREAD

**Issue by chota** [BlueWallet/BlueWallet#5546]
Description. When opening BlueWallet on macOS ("Ventura 13.3.1 (a)" is listed in "About this Mac...") I am greeted with the authentication dialog, yet it flashes off and on repeatedly until I exit the program (with Command-Tab-Q). What's up?

Reproduction. Open BlueWallet.app from the "Open" button in its App Store entry or directly from the Finder.

Expected Result. App opens and authentication is prompted once, then I authenticate and the app proper opens.

Actual Result. See attached. The authentication prompt flashes on and off repeatedly and I am able to quit the program via the task switcher (Command-Tab), selecting the app in that displayed array, and pressing "Q."

**Comment by marcosrdz** [comment]
Is this still happening with 6.5.7?

**Comment by chota** [comment]
Nope, works now!
