### ISSUE TITLE
White screen on Android Emulator when app is launched with react-native run-android

### ISSUE THREAD

**Issue by jogamod** [BlueWallet/BlueWallet#557]
Building passed without errors but when app is launched on emulator it stucks on blank white screen.

**Comment by marcosrdz** [comment]
Open index.js,  change 

```
  render() {
    return this.state.isMigratingData ? <WalletMigrate onComplete={this.setIsMigratingData} /> : <App />;
  }
```

to:

 ```
 render() {
    return <App />;
  }
```

re-run the app and let us know what is the result.

**Comment by Overtorment** [comment]
Emulator logs would be helpful. Particularly lines related to ReactNative
