### ISSUE TITLE
Alert: Payment is in transit

### ISSUE THREAD

**Issue by jonathancross** [BlueWallet/BlueWallet#5574]
## Bug

* Pixel 4a Graphene OS
* v6.4.5
* self-test passes? YES
* unique ID: `8b6cbdafdd1fbc7e`

I saw issues related to this in 2019, but nothing recent.
When trying to pay a lightning invoice, this error appears: "Alert: Payment is in transit"
The payment does not appear in the **Transations** list and never arrives at receiving end.

**Comment by vmpyre** [comment]
Witnessing the same issue.

**Comment by Johnnyrickk** [comment]
Same thing happened to me but thanks to Blackhathacker111 who helped me recover all my funds,message him on telegram his telegram username is  https://t.me/Blackhathacker111

**Comment by AbhinavMir** [comment]
It's a server error I assume, a 503 occurring here: https://github.com/BlueWallet/BlueWallet/blob/96a4104474d78a9baa924b273c11c56749e88754/class/wallets/lightning-custodian-wallet.js#L136

**Comment by tassioluz** [comment]
Was your transaction fulfilled?
What should we do to fix it?!

**Comment by olliethedev** [comment]
Same issue here! Started happening recently.

**Comment by kaburkett** [comment]
Can you guys check the lightning node your wallet is connected to. I am receiving the same error but my wallet is connected to

http://lndhb.herokuapp.com/

It was connected here by default and as you can see it no longer exists. I think that's the reason for my own error.

**Comment by tassioluz** [comment]
Mine is connected with: https://github.com/BlueWallet/LndHub
But the error persists.
Which one should I connect to?

**Comment by jonathancross** [comment]
> Mine is connected with: https://github.com/BlueWallet/LndHub

You need to connect to an actual running lnd node for anything to work.
Are you saying that you are running your own instance of LndHub, or that you put in that actual URL in node configuration?

Anyhow, personally I'm giving up on BlueWallet as it doesn't seem like a stable choice for new users I'm onboarding.

**Comment by olliethedev** [comment]
Mine is connected to lndhub.io

**Comment by olliethedev** [comment]
For the record, I didnt change any settings, BW lighting transaction just stopped working all of a sudden couple weeks back.

**Comment by olliethedev** [comment]
Lookslike lndhub was shutdown:
https://bluewallet.io/sunsetting-lndhub/
