### ISSUE TITLE
ios version CANNOT build and run in xcode

### ISSUE THREAD

**Issue by LucasDvp** [BlueWallet/BlueWallet#558]
Hi guys,
I try to download and build ios version in XCode. My steps are:

1. `clone repo & cd repo`
2. `yarn install`
3.  open `BlueWallet.xcodeproj` project and change `profile`

Then I run build, but the **error message** is like:
```log
:-1: BlueWallet/ios/Pods/Target Support Files/Pods-BlueWalletWatch Extension/Pods-BlueWalletWatch Extension.debug.xcconfig: unable to open file (in target "BlueWalletWatch Extension" in project "BlueWallet") (in target 'BlueWalletWatch Extension')
```
And I found this file does not exist, please help me with this problem, thanks😭

**Comment by marcosrdz** [comment]
cd ios && pod update

Open BlueWallet.xcworkspace

**Comment by LucasDvp** [comment]
@marcosrdz Thank you bro
But it still failed, after I run `pod update`, it shows the error like this: 

```log
[!] The `RNWatch` pod failed to validate due to 1 error:
    - ERROR | attributes: Missing required attribute `summary`.
```

**Comment by marcosrdz** [comment]
Ok. Ill look into that error. In the mean time, can you run:
rm -fr node_modules && npm install

We havent tested the app with yarn, so I just want to confirm it also occurs with npm

**Comment by LucasDvp** [comment]
@marcosrdz Thank you so much, Ill let you know if `npm` worked

**Comment by LucasDvp** [comment]
@marcosrdz it's `yarn` problem, I using `npm`, everything is normal.
Close this issue now 😂
