### ISSUE TITLE
Cannot connect Blue Wallet to LNDhub

### ISSUE THREAD

**Issue by cristi134** [BlueWallet/BlueWallet#5580]
Trying to connect to my Lightning node on Umbrel, after I go to Network - Lightning Settings, I scan the qr code in LNDhub i get a "onion not enabled" in the address field. Orbot is started, i have Blue Wallet in Tor enabled apps, Blue wallet connects to Electrum server. Restarted, force stopped both apps, nothing seems to work.

*MIUI 14.0.3
* BlueWallet 6.4.4
* self-test passes? Error: Linking can not open https url

**Comment by serik1256** [comment]
I opened an issue in Umbrel and provided some details https://github.com/getumbrel/umbrel/issues/1689
I guess it is not BlueWallet LNDhub issue.
