### ISSUE TITLE
Lightning Problems in iOs App

### ISSUE THREAD

**Issue by Pornograf** [BlueWallet/BlueWallet#5586]
Hallo,

i have Problems with Lightning in iOs App

iPhone 12
iOs 16.5

![IMG_5211](https://github.com/BlueWallet/BlueWallet/assets/137263445/268b459f-f617-4790-ac66-7c5c05588d7d)

![IMG_5210](https://github.com/BlueWallet/BlueWallet/assets/137263445/e88bc640-2103-4027-80b3-aaf07950097b)

**Comment by mezagama** [comment]
I get the same error and in the desktop app the following:

API failure: Error {"type":"default","status":503,"ok":false,"statusText":"","headers":{"map":{"cache-control":"no-cache, no-store","connection":"keep-alive","content-length":"506","content-type":"text/html; charset=utf-8","date":"Wed, 02 Aug 2023 13:51:06 GMT","server":"Cowboy"}},"url":"https://lndhub.herokuapp.com/addinvoice","bodyUsed":false,"_bodyInit":{"_data":{"size":506,"offset":0,"blobId":"87780B79-3031-4382-A525-B88CD879B45A","type":"text/html","name":"addinvoice.html","__collector":{}}},"_bodyBlob":{"_data":{"size":506,"offset":0,"blobId":"87780B79-3031-4382-A525-B88CD879B45A","type":"text/html","name":"addinvoice.html","__collector":{}}}}

**Comment by Overtorment** [comment]
default LNDhub is shut down
