### ISSUE TITLE
Bluewallet Vault 2-3 MultiSig recreate IOS error

### ISSUE THREAD

**Issue by DFXAdmin** [BlueWallet/BlueWallet#5617]
## Reporting a bug

I have made some test and now I can definitely state the following:

With Android it works, but with IOS, so Iphone and Mac M1 it does not work. 

Another user has reported that it works for him with an IOS 5. But IOS 13 definitely does not work. 
https://t.me/bluewallet/85501

Description:
When I try to inport an xPub, I get an error message. The same xPub with Android works. 

Exact error message:
"Invalid cosigner data"

I have used several different devices and always the latest IOS version and the latest Bluewallet version.

![photo_2023-07-24 16 11 14](https://github.com/BlueWallet/BlueWallet/assets/91702691/07c46556-91f6-4302-95f0-6c0d6ece8f7b)
![photo_2023-07-24 16 11 15](https://github.com/BlueWallet/BlueWallet/assets/91702691/af1eab5b-c2c6-43f0-9bbf-dc697dd589db)
![photo_2023-07-24 16 11 16](https://github.com/BlueWallet/BlueWallet/assets/91702691/10edb5bc-0f09-4c23-9d04-37385784d325)
![photo_2023-07-24 16 11 18](https://github.com/BlueWallet/BlueWallet/assets/91702691/9adf9d6a-5bd2-4cec-806e-5c7d3ac517db)

**Comment by DFXAdmin** [comment]
Edit:

I have found it is not IOS or Android but the wallet version number. 

My andoid was outdated to 6.4.4, so it works.
With 6.4.6 it no longer works.

**Comment by Overtorment** [comment]
should be fixed in https://github.com/BlueWallet/BlueWallet/pull/5618
