### ISSUE TITLE
Não reconhece transações assinadas na Electrum

### ISSUE THREAD

**Issue by rhmmgit** [BlueWallet/BlueWallet#5635]
## Are you reporting a bug?

Caros,
Criei 3 chaves diferentes (Ledger, Seed Sign e Bluewallet).
Usando o Tails e a Electrum, criei uma Multisig usando essas três chaves e acrescentei um passphrase para cada chave.
Exportei essa MultiSig para a Bluewallet.
Conferi se todas as zpub e os endereços estava iguais tanto na Bluewallet quanto na Electrum.
Tudo ok!
Gerei um endereço de recebimento na Bluewallet.
Transferi uns satoshis.
O saldo apareceu tanto na Bluewallet quanto na Electrum.
Depois, na Bluewallet gerei uma psbt para gastar esses satoshis.
Coloquei em um pendrive.
Na Electrum do Tails, assinei a transação (2 assinaturas de 3 possíveis).
Gerei a txn.
Gerei o QR Code pra Bluewallet ler, mas a bluewallet não reconheceu.
Coloquei a txn no pendrive.
Restartei com o Windows.
Passei a txn do pendrive para o One Drive.
No celular, abri a Bluewallet e importei o txn.
A Bluewallet acusou o mesmo erro.
Não lembro a mensagem do erro agora.
Mas não reconhece a transação de forma nenhuma.
Pra tirar a dúvida, abri a Electrum do Tails e importei a txn.
Cliquei em Transmitir e foi.
A transação foi transmitida sem erros.

Porque a Bluewallet não está reconhecendo a transação como válida?

Please provide:

* your phone model and OS version

MQ553BE/A
16.5.1 (c)

* BlueWallet app version (settings->about->scroll down)

ver 6.4.8 (26/07/2023 21:46:23 GMT)

* self-test passes? Open settings->about->scroll down, tap "Run self-test"

Todos os testes internos funcionam bem. A carteira funciona bem.

* unique ID for our crash reporting service (settings->about->scroll down, tap "copy")

userid:F96757DE-C053-4874-A5C1-5A0F17D79594

## Proposing a feature?

Go right ahead

**Comment by onolox** [comment]
Coloca isso em inglês.

**Comment by Overtorment** [comment]
нихуя непонятно
