### ISSUE TITLE
iOS build fails on M1 Macbook

### ISSUE THREAD

**Issue by thecodingcrow** [BlueWallet/BlueWallet#5636]
## The issue:

I was able to get the app running and started working on a new feature for one my customers. After a week of working I somehow managed to break my dev environment and cannot get the app running again. 
The issue could be pinned down to this error:
```
❌  /Users/thedoc/LC/src/BlueWallet/node_modules/rn-ldk/ios/RnLdk.swift:2:8: no such module 'LDKFramework'
```

Since I was not able to get build running again I tried to clone a fresh version of the repo, but it resulted in the exact same error as above. I assume it has something to do with my dev setup. 

I am new to mobile app development and would greatly appreciate any help!

## My Setup:

* iOS 13, any Iphone (Tried iPhone 14 and iPhone SE (3rd Gen)
* M1 macOS Ventura 13.5
* I started from master branch of the BlueWallet, BlueWallet version should be 6.4.8
* Node v16.20.0
* npm v8.19.4
* Ruby (System) 3.2.2
* Ruby (via rbenv) 2.7.6 
* Xcode v14.2 with command line tools 14.2

* Terminal is opened via Rosetta
* Xcode is openend via Rosetta

I am more than happy to provide more information, please just let me know what you need.

**Comment by thecodingcrow** [comment]
![Uploading image.png…]()

**Comment by thecodingcrow** [comment]
Update: 

I was able to resolve the mentioned error by adding ‘arm64’ to excluded Architectures for the **Pods** project as well.

Now Im stuck at this error:

![Uploading image.png…]()

**Comment by thecodingcrow** [comment]
Found a new error, this time its:

<img width="631" alt="image" src="https://github.com/BlueWallet/BlueWallet/assets/53899975/7dd68d1e-27bc-4437-8161-fd1edb0ea729”>

@Overtorment @marcosrdz I would really appreciate some guidance here

**Comment by thecodingcrow** [comment]
My `react-native info` output:

```
System:
    OS: macOS 13.5
    CPU: (8) arm64 Apple M1
    Memory: 96.47 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.15.0 - ~/Library/Caches/fnm_multishells/87346_1691144180980/bin/node
    Yarn: 3.5.0 - /opt/homebrew/bin/yarn
    npm: 9.5.0 - ~/Library/Caches/fnm_multishells/87346_1691144180980/bin/npm
    Watchman: 2023.07.24.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /Users/thedoc/.rbenv/shims/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.2, iOS 16.2, macOS 13.1, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 29, 30, 31, 33
      Build Tools: 29.0.2, 30.0.2, 30.0.3, 31.0.0, 34.0.0
      System Images: android-29 | Google APIs ARM 64 v8a, android-31 | Google APIs ARM 64 v8a, android-33 | Google APIs ARM 64 v8a, android-33 | Google APIs Intel x86_64 Atom, android-34 | Google APIs ARM 64 v8a
      Android NDK: Not Found
  IDEs:
    Android Studio: 2022.2 AI-222.4459.24.2221.10121639
    Xcode: 14.2/14C18 - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.19 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.11 => 0.71.11 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

**Comment by TaprootFreak** [comment]
Here the same problem  🙋‍♂️

**Comment by Overtorment** [comment]
@marcosrdz ?

**Comment by Overtorment** [comment]
@marcosrdz do we have a doc somewhere with a detailed guide how to compile for ios on mac?

**Comment by TaprootFreak** [comment]
@Overtorment Note: The problem exists for me only on an M1 device. I used an old Intel device from Apple a year ago for testing and it worked.

**Comment by marcosrdz** [comment]
You need to use a Rosetta-enabled simulator. You might need to manually add one via xcode

**Comment by davidleomay** [comment]
@marcosrdz, thanks for the hint, this works!

It seems like we cannot run it with `react-native run-ios` though, as the currently used React Native CLI doesn't support specifying the destination yet (see https://github.com/facebook/react-native/issues/36901 and https://github.com/react-native-community/cli/issues/1918).

**Comment by Uter1007** [comment]
any update here ?

**Comment by marcosrdz** [comment]
> any update here ?

Its been "fixed" by enabling the Rosetta destinations under the Build menu.

**Comment by redpredator8** [comment]
can u give a better explanation please
