### ISSUE TITLE
BUG: Scan of singlesig descriptor QR from Sparrow Wallet not working

### ISSUE THREAD

**Issue by seedhammer** [BlueWallet/BlueWallet#5637]
This descriptor QR export from @SparrowWallet is not imported:

<img width="448" alt="image" src="https://github.com/BlueWallet/BlueWallet/assets/93251679/d5d42ff3-a1a5-49bb-9ea9-d2e5d5e259be">

**Comment by Overtorment** [comment]
just to verify, whats the first external address for this wallet?

**Comment by seedhammer** [comment]
bc1qr0y5c96xtfeulnzxnjl086f2njcmf8qmhenvpp
