### ISSUE TITLE
Add Transaction authorization 

### ISSUE THREAD

**Issue by earlydev** [BlueWallet/BlueWallet#565]
Add second password for transaction authorization purpose. In case someone (could be a close family member who guessed your password right- wife😁 for example) actually got access to unlock BlueWallet make it difficult to send transaction or view backup phrase by adding second password and also it can be optional

**Comment by Overtorment** [comment]
I think that might be a good case to use biometrics. While biometrics
unlock is not secure enough to protect your private key, It might be
sufficient to just prevent random 3rd party from accidentally making a
transaction.

**Comment by earlydev** [comment]
That’s a cool idea am loving bluewallet already

**Comment by ncoelho** [comment]
yep, biometrics after a password entering on first start can be used. Both for actions or even to access the app it self.

**Comment by marcosrdz** [comment]
Assigned to self. Will work on it.

**Comment by Overtorment** [comment]
Make it optional, so you would have to manually turn on biometric security
in settings

**Comment by ncoelho** [comment]
> Make it optional, so you would have to manually turn on biometric security in settings

Yes, I would propose to improve the security settings. At the moment there's a lot of users activating "plausible deniability" by mistake and getting stuck there.

We can make a simple structure like this.

|- Security
|- - Encryption
|- - Biometrics
|- - Plausible deniability

Options should be visible but inactive till encryption gets activated. And at the same time the other options are in separate menus avoiding errors on activating them.

**Comment by ncoelho** [comment]
implemented!
