### ISSUE TITLE
Import Multisig TESTNET Descriptor not displaying addresses correctly

### ISSUE THREAD

**Issue by frontrun** [BlueWallet/BlueWallet#5656]
When scanning a Multisig Descriptor from a Testnet wallet (tbc1 address) it does not display testnet addresses.
![Screenshot 2023-08-14 213350](https://github.com/BlueWallet/BlueWallet/assets/127260761/94a2f9ad-3c30-49cb-a1d1-3a82ed9955bd)
![Screenshot 2023-08-14 213426](https://github.com/BlueWallet/BlueWallet/assets/127260761/0db18d97-5664-4208-becc-7201c376d386)

**Comment by frontrun** [comment]
![IMG_4063](https://github.com/BlueWallet/BlueWallet/assets/127260761/fb381ba5-662d-4b2a-8249-7f82adbbde01)
![IMG_4062](https://github.com/BlueWallet/BlueWallet/assets/127260761/ba63c5a7-c042-4bc6-b3c6-e4a2a2890a56)

**Comment by Overtorment** [comment]
testnet is not supported
