### ISSUE TITLE
Email not functioning, how do I contact

### ISSUE THREAD

**Issue by setavenger** [BlueWallet/BlueWallet#5658]
## Do you need support? Just email bluewallet@bluewallet.io
This email is not working

## Are you reporting a bug?

Please provide:

* your phone model and OS version
* BlueWallet app version (settings->about->scroll down)
* self-test passes? Open settings->about->scroll down, tap "Run self-test"
* unique ID for our crash reporting service (settings->about->scroll down, tap "copy")

## Proposing a feature?

Go right ahead

**Comment by Overtorment** [comment]
fixed the email
