### ISSUE TITLE
Display Total Bitcoin within App 

### ISSUE THREAD

**Issue by Blockgazer** [BlueWallet/BlueWallet#566]
I also suggest the price of Bitcoin be displayed somewhere in the app and in case some have multiple wallet in the app add total btc holding.

**Comment by marcosrdz** [comment]
@ncoelho  design?

**Comment by ncoelho** [comment]
Discussion on this topic
https://twitter.com/nvcoelho/status/1242133033899229185

Priority to display total balance for now. As it provides more value for users with many wallets.

So far this is the version we are leaning towards to:
![Home - v3 - 0](https://user-images.githubusercontent.com/1238429/77351933-b62ca300-6d3e-11ea-9a6a-a1b6d6e899db.png)

**Comment by Overtorment** [comment]
my 2 cents: I never ever needed to display total of my wallets

**Comment by brainharrington** [comment]
I like the idea of displaying total, my wife and I would use it when we have our weekly budgeting meeting, I already add up both manually and would be cool to just see the total listed easily. Love all the updates, the Blue Wallet team is crushing it!

**Comment by limpbrains** [comment]
How about this: you pull wallets list to the right and can see summary of all wallets in BTc and local currency. When you release the finder, it closes  automatically 

![image](https://user-images.githubusercontent.com/155891/95791758-aed4e300-0cea-11eb-8b56-b52d515cdff7.jpeg)

**Comment by Overtorment** [comment]
> How about this: you pull wallets list to the right and can see summary of all wallets in BTc and local currency. When you release the finder, it closes automatically
> 
> ![image](https://user-images.githubusercontent.com/155891/95792038-5225f800-0ceb-11eb-9ec3-4122e6062b7f.jpeg)

that's clever!
