### ISSUE TITLE
Multisig wallet watch-only (not all seeds) transaction details crashes

### ISSUE THREAD

**Issue by setavenger** [BlueWallet/BlueWallet#5661]
## Are you reporting a bug?

Please provide:

* your phone model and OS version
iPhone 13 pro
* BlueWallet app version (settings->about->scroll down)
ver 6.4.8 (build 1690407983 master)
* self-test passes? Open settings->about->scroll down, tap "Run self-test"
ok
* unique ID for our crash reporting service (settings->about->scroll down, tap "copy")
userId:D2ACE65F-8648-43B5-9F97-84A930658FA1

Using a MultiSig wallet with not all seeds present (e.g. 2 of 3 seeds and 1 zpub). When going to the transaction details the app crashes.

## Proposing a feature?

Go right ahead

**Comment by Overtorment** [comment]
so, youve made a ms transaction successfully, but trying to open tx of this wallet you get a crash?

**Comment by setavenger** [comment]
I sent a transaction to this wallet. Now I can’t open the details page of the transaction

**Comment by Overtorment** [comment]
crash reporting service logged a bunch of these:

![image](https://github.com/BlueWallet/BlueWallet/assets/1913337/01440d51-092f-4603-94d6-f10507d958a6)


is there a watch-only wallet involved..?

**Comment by setavenger** [comment]
I think this is a separate issue that I'm also having. I get an error in a watch-only wallet that was created from the QR-code in the multisig setup phase. I also can't delete these wallets because settings crashes.

**Comment by Overtorment** [comment]
acknowledged

**Comment by Overtorment** [comment]
addressing undeletable wallets here: https://github.com/BlueWallet/BlueWallet/pull/5703/files

gona try to reproduce tx-details related crashes...

**Comment by Overtorment** [comment]
could not reproeduce. 
is it reproduceable if you delete and reimport the app?
can you share the backup to i@bluewallet.io ?
