### ISSUE TITLE
Lightning wallet [Create] button is greyed out 

### ISSUE THREAD

**Issue by Git-Forked** [BlueWallet/BlueWallet#5673]
## Are you reporting a bug?
Yes.
When trying to create a Lightning wallet the [Create] button is greyed out and cannot be click. As well the advanced options are open and requests:  "Connect to your LNDHub".
Cannot proceed to create a Lightning wallet.

Please provide:

* your phone model and OS version
SM-S111DL - Android 10
* BlueWallet app version (settings->about->scroll down)
6.4.8 - (build 1690407983)
* self-test passes? Open settings->about->scroll down, tap "Run self-test"
Yes
* unique ID for our crash reporting service (settings->about->scroll down, tap "copy")
7575264cc35b4cd7

**Comment by marcosrdz** [comment]
You need to provide the URL of the wallet instance and server you wish to connect to.
