### ISSUE TITLE
Importing skeleton electrum from Cold Card MK4 to android version of bluewallet does not work

### ISSUE THREAD

**Issue by flurb789** [BlueWallet/BlueWallet#5681]
## Are you reporting a bug?
yes

Please provide:

* your phone model and OS version
OnePlus Nord N300
Android version 13, security update July 5, 2023

* BlueWallet app version (settings->about->scroll down)
Version 6.4.8

* self-test passes? Open settings->about->scroll down, tap "Run self-test"
I do not see this option on my phone

* unique ID for our crash reporting service (settings->about->scroll down, tap "copy")
n/a

## Proposing a feature?
no

I am trying to import a skeleton electrum wallet to my bluewallet android app.  when i insert the SD card and select the appropriate file to import, the phone's camera viewfinder shows and nothing is imported. i've tried this many times, reinstalled the app, changed SD cards, etc. it does not work.
any ideas?

**Comment by beenjamin7** [comment]
I am having the exact same issue.  Blue wallet unable to recognize electrum skeleton wallet.

**Comment by tboneBPM** [comment]
Exactly the same issue here. Samsung A14, Android 13

**Comment by battyboy1** [comment]
Any solutions to this? Having same problem...

**Comment by tboneBPM** [comment]
I managed to get it to work. If I remember correctly , you need to open the file that is on your sd card, copy the text and use the text copied in your clipboard to import it

**Comment by Overtorment** [comment]
After pressing "Scan or import file" you need to tap this icon to choose a file:

![image](https://github.com/BlueWallet/BlueWallet/assets/1913337/f5a41d49-97de-4b10-86a4-c307d34b32e7)

**Comment by Overtorment** [comment]
not all formats from coldcard mk4 work with BW now,  Electrum export format definately works.

Ill be working on adding support for others
