### ISSUE TITLE
Bug:  CNY price is wrong

### ISSUE THREAD

**Issue by xiaod-dev** [BlueWallet/BlueWallet#5705]
## bug
The BTC price for currency `CNY` is not correct! 
![image](https://github.com/BlueWallet/BlueWallet/assets/21277644/9c44dfe4-9593-481b-823e-38ebc733d91c)

**Suggestion**:
 consider using another **public free** data provider : [coinbase](https://docs.cloud.coinbase.com/sign-in-with-coinbase/docs/api-prices)

```shell
$ curl https://api.coinbase.com/v2/prices/BTC-CNY/buy | json_pp

{
   "data" : {
      "amount" : "195998.769106000040294695",
      "base" : "BTC",
      "currency" : "CNY"
   }
}
```

## environment
- iPhone 12 iOS 17
- BlueWallet v6.4.8

**Comment by Overtorment** [comment]
@marcosrdz wana handle it?
