### ISSUE TITLE
[Feature request] Add Night mode (Dark/Black theme) 

### ISSUE THREAD

**Issue by Ero-gamer** [BlueWallet/BlueWallet#5709]
I had to create a a github account just to submit this. I can't seem to find night mode (Dark/Black theme) anywhere on app settings, maybe it's available on Android 11+ dynamic theme? I can't test this as I have Android 9. So how come BlueWallet app doesn't have basic feature (night mode) in 2023 is beyond me.

**Comment by Overtorment** [comment]
i think we have one? it just switches automatically

**Comment by marcosrdz** [comment]
The app has had dark mode for a while now. Its automatic based on system settings.
