### ISSUE TITLE
If there is a lightning or Bitcoin address on the clipboard, you should be able to clear your clipboard

### ISSUE THREAD

**Issue by mikethetike** [BlueWallet/BlueWallet#573]
[Android] Currently if I have an address copied and I switch to the app, it asks me if I'd like to create a transaction with the address. It can be a bit annoying every time I switch to the app and the only way to get rid of it is to go to another app and copy something. 

I suggest that the options in the "Would you like to use it for a transaction" dialog should be "Cancel", "OK" and "Clear it from clipboard"

**Comment by ncoelho** [comment]
Thanks for reporting.

Just to make it clear, I'm without any android device at the moment. When you tap cancel, and after you enter the app again, it will ask you again if you want to create a transaction?

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/610/commits/59c9905ae8b2106c9a4eb17f335cd63a5dcffaca
