### ISSUE TITLE
Privacy Mode ✅ 

### ISSUE THREAD

**Issue by whiteyhat** [BlueWallet/BlueWallet#574]
## Introduction
According to this #364 and specifically https://github.com/BlueWallet/BlueWallet/pull/364/commits/f6a99a88de6d4013913228c755826ea3e3eb4f6c can we have some privacy mode when using BlueWallet?

## Context
When using the wallet in public, I don’t want people around my area to be able to sniff into my assets from BlueWallet, hence I propose a privacy mode that enables the balances from each transaction and the main balance when turned on.

### UX implementation
An example to enhance this mode, would the same way as N26 has it, leave a constant input in the front camera and when it detects the user's hand moving around the camera it switches to the privacy mode, when it does it again it toggles back to normal mode.

#### Example
![example](https://images.ctfassets.net/q33z48p65a6w/3BvxQBoGA1sCmOiNg9Q9q4/4670a6364b45b7d18d9d677122003c24/1904_DiscreetMode_Gif1_lossy.gif)
More information about this example at https://n26.com/en-es/blog/discreet-mode

### PRIVACY MODE OFF
![photo_2019-08-07 21 42 44](https://user-images.githubusercontent.com/31220861/62652726-51ae0680-b95c-11e9-872c-e9316133cec3.jpeg)
### PRIVACY MODE ON
![photo_2019-08-07 21 42 48](https://user-images.githubusercontent.com/31220861/62652728-51ae0680-b95c-11e9-8771-c82c4e29f6af.jpeg)

**Comment by marcosrdz** [comment]
The next release will have privacy for the balance. It is merged into master. I’ll add it to the transactions.

**Comment by ncoelho** [comment]
That N26 approach is slick, thanks for sharing @whiteyhat 

We have a first version on master already, that @marcosrdz is point out, close enough for a first version :D
https://github.com/BlueWallet/BlueWallet/pull/561
