### ISSUE TITLE
Azteco Redeem URL in QR Code

### ISSUE THREAD

**Issue by pfergi42** [BlueWallet/BlueWallet#5742]
Currently, scanning the QR code on Azteco On-Chain vouchers is broken.

In the past, Azteco on-chain vouchers included a QR code with the following URL format:
https://azte.co?c1=1111&c2=2222&c3=3333&c4=4444

The new URL format in the QR code is:
https://azte.co/redeem?code=1111222233334444

**Comment by Overtorment** [comment]
fixed in https://github.com/BlueWallet/BlueWallet/pull/5797
thanks!

will rollout in next release
