### ISSUE TITLE
Coin Control Feature

### ISSUE THREAD

**Issue by earlydev** [BlueWallet/BlueWallet#575]
If i have recently received BTC in Bluewallet using 2 different addresses. In address 1 i have for example 0.01BTC in Address 2 i have 0.1 wallet will display 0.11 as coin balance. Now i want to send 0.05BTC to a 3rd party, the 2 addresses are then merged as input(WHich might not be good for privacy) with coin control users can choose which of the 2 address they wish to send the 0.05BTC from. would it be ok to add some kind of option for coin control? its kinda a cool feature

**Comment by Overtorment** [comment]
Are you talking about HD wallet?
Anyway, yes this is a cool feature but kinda hard to make. I can tell you for sure that different coin select strategies are planned (like, a strategy to minimize dust or a strategy to minimize fee), but an option to completely choose which inputs to use - that will have to wait.

**Comment by earlydev** [comment]
Alright

**Comment by nighttimeBIT** [comment]
this is one of many privacy supporting features for a bitcoin wallet & i think it‘s necessary to at least start working on it. Maybe look @ WasabiWallet for Inspiration?

**Comment by ncoelho** [comment]
work going on here https://github.com/BlueWallet/BlueWallet/issues/1049
