### ISSUE TITLE
Feature request: signing text with bitcoin address

### ISSUE THREAD

**Issue by lessless** [BlueWallet/BlueWallet#576]
Hi,

Having an ability to sign a text string with a bitcoin address can help to build 2FA authentication flows.

References:
1.  http://support.vaultoro.com/knowledgebase/articles/536758-how-do-i-sign-a-message-with-my-bitcoin-wallet
2. https://www.reddit.com/r/Monero/comments/brty9r/stop_simhack_attacks_with_monero/

For small services that operate only with BTC there is no need to build that expensive sign up/log in/password restore logic attached to email addresses. 

Hope that this can be a game changer.

**Comment by Overtorment** [comment]
That's a feature I wanted to build for a long time. I'm still in the process of collecting ideas, but will probably soon move to implement it.

Do you have a spec for that? I mean whats the BIP number..?

**Comment by lessless** [comment]
@Overtorment fantastic! I've found this https://github.com/bitcoin/bips/blob/master/bip-0322.mediawiki but not sure that it's not some kind of an extension to the original functionality.

**Comment by Overtorment** [comment]
Ack. Will look into that. Thanks
