### ISSUE TITLE
feature: add total wallet price in local currency

### ISSUE THREAD

**Issue by sudowanderer** [BlueWallet/BlueWallet#5777]
## Proposing a feature

I can't clearly see how much my BTC is worth in local currency... It's quite inconvenient. 

Suggest add a small text bar to display this information. Like below:

![image](https://github.com/BlueWallet/BlueWallet/assets/21277644/7b3ff23a-54cf-4d63-9206-a35c9ffb72f9)

**Comment by Silvergreenim** [comment]
### 1844

**Comment by Silvergreenim** [comment]
Prepaid

**Comment by Overtorment** [comment]
open wallet and tap the unit, it will switch from btc->fiat->sat
