### ISSUE TITLE
Testing WebLN in lapp browser

### ISSUE THREAD

**Issue by dmidnight** [BlueWallet/BlueWallet#578]
It should be possible to change the url in the lapp browser to enable lapp development & testing.

Maybe hide it behind the advanced toggle...

I am developing a lapp, which is meant specifically for mobile users, but I cannot test it in your browser.

**Comment by Overtorment** [comment]
Use deeplink: `bluewallet://openlappbrowser?url=https%3A%2F%2Fsat2.io%2F` and put your urlencoded link.

Eventually we will make address field in browser editable as well.

**Comment by dangermidnight** [comment]
Thanks for the quick answer. That will certainly work for now.

**Comment by dmidnight** [comment]
This does not work in the latest release.

See https://coinfluent.io demo page

**Comment by dmidnight** [comment]
Actually, after testing a bit more:
- It does not load the app if I had left the Lapp browser open previously
- If I have not left the lapp browser open previously then it will open the URL, but does not successfully load WebLN (thus the "requires lightning" screen)

**Comment by Overtorment** [comment]
I have just tried it on iOS and Andr. It deeplinks fine, but the webpage says 'This app requires a Lightning wallet'. The home icon turns green tho - this is an indicator that webln was actually called and initialized.

This is a hint that something is not right on your side. I cant check your js code since its minimized, but I suggest you probe for webln several times, with interval of 1 sec or something like this, since this whole injecting thing is a rather tricky business. You are simply not detecting webln.

I personally do it like this. Works 10 times out of 10. Check out https://sat2.io for an example

```
     let mywebln;

      $(function() {
          console.log( "ready!" );
          let installTriggered = false;

          // probing for WEBLN every 1 sec
          let interval = setInterval(async () => {
              let noErr = true;

              try {
                  if (WebLN && WebLN.requestProvider) mywebln = await WebLN.requestProvider();
              } catch(Err) {
                  noErr = false;
                  console.log(Err);
              }
              if (noErr) {
              	// got webln! user can receive sats
                clearInterval(interval);
                $("#ready2receive").show();
                $("#alreadyhavebwinstalled").remove();
              } else {
              	// no webln. asking user to install wallet
              	$("#youneedawallet").show();
              }
          }, 1000);
      });
```

**Comment by Overtorment** [comment]
![image](https://user-images.githubusercontent.com/1913337/63966380-0d151700-ca93-11e9-8255-ef3626742b36.png)

**Comment by dmidnight** [comment]
Thanks for looking @Overtorment .

I have been developing it locally using the Joule browser plugin, and the first thing it attempts is to use the webln.getInfo() method. If that throws an error, then the page above is shown...

I will retry it in a loop a few times and see what happens.

Thanks,
 ~ D.

**Comment by Overtorment** [comment]
I havent checked webln specs in a while, maybe recommended way to test for webln is changed.
Keep me posted.

**Comment by dmidnight** [comment]
I added some alerts to the page to debug...

```const webln = await requestProvider()``` is working, no error there.

When it proceeds to the next step, and does:
```const walletInfo = await webln.getInfo()``` it throws an error "not implemented".

https://webln.dev/#/api/get-info

I was using this method to identify the user (they are prompted to allow this the first time in Joule).

Any ideas why that is missing in BlueWallet?

**Comment by Overtorment** [comment]
Was not needed, till now. Ill take a look at spec, if its nothing serious I
might add it in next BW build

**Comment by dmidnight** [comment]
That would be great...

The general idea I was pursuing is to use the pubkey as the identity, and then use the other webln method to sign a message to authenticate. I havent completely implemented this yet, but I was already using the pubkey to mark which invoices were for whom. For example, a user could sign the CSRF from a login form, and use that to create a session, or could possibly add a signature to each http request header.

It is a bit clunky in Joule, as it alerts you to sign the message each time. This app is intended to be used 100% on mobile though, so it is really your implementation that matters ;) (This app/service is for enabling POS vendors and Payment Processors to integrate Lightning payments for retail, providing checkout flows that match their existing hardware, infrastructure, and requirements)

Without this ability, I would have to fall back to a more traditional auth strategy, and forego the benefits of public/private keys.... Emails and passwords, blah.

**Comment by dmidnight** [comment]
Actually after reading up a bit more on signMessage and verifyMessage, I am not sure my use case works, so you can disregard this last request. I will rip out the getInfo() call. It would still be nice to see full WebLN support in BW, but at this point it's not something that I am concerned with.

Thanks for all of your help otherwise.

**Comment by dmidnight** [comment]
For reference: https://github.com/lightningnetwork/lnd/issues/2510

**Comment by dmidnight** [comment]
So, using the backend verifyMessage for authentication may not work well, as explained in lightningnetwork/lnd#2510, however, using a pure JS implementation to verifyMessage would work well.

For this to work, I would need BlueWallet to support webln.signMessage(), which is currently also not implemented.

There is an implementation available at https://github.com/nerddan/ln-crypto for reference.

It would be amazing if you could add this functionality to a future BW release.

**Comment by wbobeirne** [comment]
@dmidnight BlueWallet may not actually work for what you're going for, as it's custodial by default. This means that multiple users would all share a single public key. I don't believe the backend for BlueWallet (lndhub) even supports signing, likely for this reason.

To my knowledge, no non-custodial mobile wallets support WebLN yet, so you may be out of luck on mobile for now.

**Comment by dmidnight** [comment]
Ouch. Well, nevermind then.

**Comment by Overtorment** [comment]
Doable, but with few gotchas. Lndhub will have to generate pub and priv
keys for each user, and use them for signing. Suck pubkeys wont be visible
as ln nodes, so you can't pay them, wont be visible on 1ml etc.

**Comment by dmidnight** [comment]
That would be enough to provide the missing WebLN methods getInfo(), signMessage(), and verifyMessage(). The fact that they aren't payable seems fine to me. What do you think @wbobeirne?

For my retail use-case, I can't imagine having a user standing in line at a POS, and having to type in a username and password to authenticate. It would just be too slow. Being able to use key auth seems to be ideal...

OTOH, the BW app itself has keys locally. Not sure how you'd determine which one to use when there are multiple wallets, but maybe those keys could be used instead of new lndhub keys?

**Comment by Overtorment** [comment]
I have another proposal. In case you forgot, BW is fully featured
non-custodial offchain btc wallet in the first place.
Ive been planning to add signing to regular offchain wallet for a long
time. So when webln asks to sign something I can give user a cute wallet
selector so he can choose what wallet he wants to use for signing.
That way user fully controls his keys, and can even port them to
another wallet ( signing scheme is somewhere in BIPs, so it’s standardized)

**Comment by niahmiah** [comment]
i hate to use this reference, but the Copay wallet APi uses path m/1’/0 as the identity when signing requests for an HD wallet.

then each hd wallet = 1 identity

**Comment by dmidnight** [comment]
@Overtorment I love the idea, and that is pretty much what I was envisioning when I made the "OTOH" comment above. 

Regarding the signing scheme, this repo has a reference implementation, so it should be rather quick and easy to adopt without digging through BIPs  https://github.com/nerddan/ln-crypto

I'll keep this open to continue to track, and hopefully continue testing this feature.

**Comment by dmidnight** [comment]
Sounds a lot like your issue at https://github.com/joule-labs/webln/issues/22 too

**Comment by dmidnight** [comment]
The browser seems to have been removed in IOS now. What happened?

**Comment by marcosrdz** [comment]
Apple happened.

**Comment by dmidnight** [comment]
I do not believe that Apple would prevent you from providing a WebLN enabled browser in the app, as Coinbase wallet has a fully functional dApp browser.

I think the problem is likely due to calling it a "marketplace".

Do you guys plan to keep it hidden permanently, or can you re-release it as a generic WebLN browser and remove the "marketplace" wording?

**Comment by Overtorment** [comment]
We temporarily hid the button as Apple gave us 1 week to comply. Lapp
browser is not going anywhere, you can still deeplink to it from your
project. We are looking into getting it back for everyone, probably will
rename it to Lapp Browser and make it open blank page by default, while
real marketplace will be opened in external browser. Any thoughts on this?

**Comment by dmidnight** [comment]
The ability to bookmark would be ideal, so that users can quickly get back to things they tend to use, and sort them to their own priority.
