### ISSUE TITLE
TLS for Electrum

### ISSUE THREAD

**Issue by clonmac** [BlueWallet/BlueWallet#579]
With the addition of being able to connect BlueWallet to Electrum Server, is it possible to connect it to an Electrum Personal Server ([EPS](https://github.com/chris-belcher/electrum-personal-server)) as well? I have one up and running with my Bitcoin full node and I'm able to successfully connect my Electrum wallet to it, but if I try and connect BlueWallet to it (same MPKs and addresses), it fails to connect.

**Comment by Overtorment** [comment]
Should work, EPS implements standard Electrum protocol. My guess is you have a connectivity issue from your phone to where your EPS is hosted.

**Comment by clonmac** [comment]
That's what I thought, I wasn't sure if BlueWallet was doing anything specific with its calls that required a full server backend or not. So I ran a tcpdump on the EPS server while I tried setting up the configuration in BlueWallet and I can see the packets and responses hitting EPS. Also, as I said, an actual Electrum software wallet residing on my LAN (same network as my phone w/BW app) connects just fine. EPS is set up to allow connections from any IP.

What validations are performed when saving the configuration on the phone side?

Let me know if there is something I can do to test further on my end. I don't have any mobile debugging tools, but I can troubleshoot anything on the EPS side of things if needed.

**Comment by Overtorment** [comment]
Here's the exact code that tests electrum server: https://github.com/BlueWallet/BlueWallet/blob/master/BlueElectrum.js#L395

Wild thought: maybe EPS doesn't implement protocol version `1.4`..?
Also, what port youre trying to use? Should be TCP (no ssl)

You can test that BW connects to random public electrum server ( https://1209k.com/bitcoin-eye/ele.php )

When I have some free time Ill try EPS myself

**Comment by clonmac** [comment]
Ah, I think that is the issue then. [EPS only accepts connections using SSL.](https://github.com/chris-belcher/electrum-personal-server/blob/master/electrumpersonalserver/server/common.py#L529)

**Comment by Overtorment** [comment]
Ssl planned, but not nearest time

**Comment by Overtorment** [comment]
https://github.com/tablexi/react-native-tcp
https://github.com/staltz/react-native-tcp

Current https://github.com/aprock/react-native-tcp doesnt support tls

**Comment by ncoelho** [comment]
TLS for Electrum implemented here and it will be released on next update.
https://github.com/BlueWallet/BlueWallet/commit/6b188d24ca45b15db26e4f014ae5f9359b3cb2ad
