### ISSUE TITLE
API Error: Error underfined -> Can't import, can't send.

### ISSUE THREAD

**Issue by wildernessfamily** [BlueWallet/BlueWallet#5819]
## Do you need support? Just email bluewallet@bluewallet.io
I already have

## Are you reporting a bug?
I have a BlueWallet, and when trying to send my sats from my Lightning funds I receive the error API failure: undefined. 
I click on Export I then try to import to another BlueWallet on another device and I receive the same error. I can't do anything with my sats.

Please provide:
MacBookPro
Google Pixel 6
iPad7
I have tried on all these devices with the same problem.
Version 6.2.18 (701)
Self test comes back okay.

## Proposing a feature?

Go right ahead

**Comment by Luser1337galore** [comment]
Same problem and have been seeing more people post about this problem since more then a year.

Its starting to look like a really stinky dumpster fire at bluewallet.

Hope u didnt put too many sats in to this noob tech, for me its just 10 bucks.

**Comment by wildernessfamily** [comment]
I did a search, and seems like forum post after forum post with this same error with no answer. I emailed BlueWallet, and of course, no response. Luckily, I just had about $4.00 in the wallet.

**Comment by wildernessfamily** [comment]
Write after I wrote my comment, BlueWallet responded.
They gave this link at the solution.
https://bluewallet.io/docs/recover-lndhub/

**Comment by wildernessfamily** [comment]
Write after I wrote my comment, BlueWallet responded.
They gave this link at the solution.
https://bluewallet.io/docs/recover-lndhub/
