### ISSUE TITLE
App Shuts Down While Trying to Scan qr code

### ISSUE THREAD

**Issue by earlydev** [BlueWallet/BlueWallet#583]
Each time i try to scan BTC Address using QR scanner the app shuts down

**Comment by marcosrdz** [comment]
Can you provide a QR Code that we can use to test?

**Comment by earlydev** [comment]
I tried again it worked

**Comment by marcosrdz** [comment]
Can you provide us with the problematic QR?

**Comment by earlydev** [comment]
No need it’s been stable
