### ISSUE TITLE
Failing to open Camera Screen when Scanning to Import (iOS)

### ISSUE THREAD

**Issue by godSaysHODL** [BlueWallet/BlueWallet#5831]
## Are you reporting a bug?
Yes
Please provide:

* iOS 14 iphone
* BlueWallet 6.4.10
* self-test passes? Yes
* unique ID for our crash reporting service: userId:2708E6AA-4561-45B3-AE27-361675772607

Bug: when creating a multisig with my friends iPhone, trying to import a vault key, the camera scanner fails to open. Normal scan feature and import wallet scan for single sig flow work fine. But importing Vault Key and scanning fails to open camera and does nothing

**Comment by weil** [comment]
same issue still happening.  the bug was not fully fixed yet.
