### ISSUE TITLE
There is a bug when using the scanning function when creating a multi-signature signature

### ISSUE THREAD

**Issue by xiejiajin** [BlueWallet/BlueWallet#5869]
While creating a multi-signature wallet, I wanted to click on SCAN, but realized that the camera is not called immediately, but only when the creation page is closed. See the how-to video for more details.

Found an issue in version 6.4.10, iOS version 17.2 beta

![w20231129095504](https://github.com/BlueWallet/BlueWallet/assets/12896393/17e5e780-ffbd-4794-98c8-79d855d52f46)

**Comment by Greenbirdy00** [comment]
I have encountered the same problem. If i hold my phone up to the QR it works. So the scanning feature works i just do not see the camera
