### ISSUE TITLE
XPUB import

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#59]
> When I scan a QR code export (BIP39) on one Blue Wallet with another Blue Wallet in import mode, I get the error:  "Alert  Bad WIF"
> As best as I can tell, the export QR code is correct, so I think there is a problem with import.

**Comment by Overtorment** [comment]
cant reproduce

**Comment by lobsterpub** [comment]
Getting this as well on iOS version when trying to import an xpub.

**Comment by Overtorment** [comment]
Oh, xpubs dont work yet in import. They were forgotter. Should be trivial to add.
TBD.
