### ISSUE TITLE
iOS version 6.4.11 app crashes after update 

### ISSUE THREAD

**Issue by libertyluminary** [BlueWallet/BlueWallet#5929]
Bug after updating to iOS version 6.4.11. Lightning crashes the app anytime selected. Also, when using a Bitcoin wallet, if trying to change denomination from sats to anything else, app crashes.

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/commit/1867961be1459b1a9cf0f9de33682467bfbe7b01

**Comment by libertyluminary** [comment]
What did you do to correct it?

**Comment by marcosrdz** [comment]
> What did you do to correct it?

Update has been pushed to the App Store review team. version 6.4.12

**Comment by libertyluminary** [comment]
Thank you!!
