### ISSUE TITLE
iOS7.2.1 app ver. 6.4.11 crashes when select imported wallet.

### ISSUE THREAD

**Issue by Nymphetamine79** [BlueWallet/BlueWallet#5930]
*iPhone 14 Pro / ios 7.2.1
*Blue Wallet version : 6.4.11
* Self-test passed
* Unique ID: 239E9C33-4B66-4E06-A3C9-E999ACDA9C98

ios app crashes when select an imported encrypted wallet. You can create new wallet and open it.

**Comment by chrisswanda** [comment]
Can confirm the same behavior on my device.  

iOS 17.2.1
Blue Wallet version - 6.4.11

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/commit/1867961be1459b1a9cf0f9de33682467bfbe7b01

**Comment by Overtorment** [comment]
duplicate https://github.com/BlueWallet/BlueWallet/issues/5929
