### ISSUE TITLE
TOR option missing in ios app version 6.4.11

### ISSUE THREAD

**Issue by doctorspecs** [BlueWallet/BlueWallet#5931]
I just updated to Bluewallet ios version 6.4.11 and I have noticed the TOR option (settings > network > TOR) is now missing. Because of this, user is no longer able to connect to their own electrum server

iphone 14pro, ios 17.2.1
Bluewallet ios version 6.4.11

**Comment by QuimBarraca** [comment]
same issue

**Comment by KHP86** [comment]
Also same issue here. Unable to connect to tor based electrum server.

**Comment by eleaner** [comment]
the same here

**Comment by eleaner** [comment]
it seems to be able to connect if you run orbot before (as a workaround)

**Comment by jviki** [comment]
It seems there is a very silent removal here of Tor: https://github.com/BlueWallet/BlueWallet/commit/6ae3572aca0ff25d5e8512a21c949c70e1ef6d11. It is not mentioned anywhere in release notes... It just broken my wallet setup, thx.

**Comment by jviki** [comment]
Done via PR: https://github.com/BlueWallet/BlueWallet/pull/5913. But again, no clear explanation, maybe due to some security concerns.

**Comment by fabula220** [comment]
Same, broken wallet…

**Comment by bedair81** [comment]
same issue on android 6.4.12. is tor no longer supported?

**Comment by davidohayon669** [comment]
did bluewallet remove tor support?

**Comment by Overtorment** [comment]
Tor support removed because dependency that provided Tor stopped being maintained. One year out of date and its not compatible with newer versions of ReactNative.

Meanwhile some options are Orbot & VPNs (like Tailscale).
Will reconsider if situation with Tor for ReactNative improves.

**Comment by davidohayon669** [comment]
@Overtorment what tor got to do with React-Native? it's probably just a thin wrapper around native code that can be improved easily

**Comment by Overtorment** [comment]
@davidohayon669 notexactly, heres the package https://github.com/Sifir-io/react-native-tor and it containsfull Tor implementation under the hood with some rust cross-compiling magic

**Comment by eleaner** [comment]
@Overtorment 
I guess no one can force BlueWallet to fix it if they don't want
but I guess a few things would be nice:
1. a clear info in a release notes
2. a valid explanation why not and why now
3. heads-up for those of us who would try to search another wallet instead

**Comment by davidohayon669** [comment]
@Overtorment are there specific bugs that made problems or missing features? maybe it's worth it to fix them and keep using this, i really liked this feature not needing to mess with orbot

@eleaner agree regarding some warning or better messaging. all LNDhub instances that run on umbrels are dependent on this

**Comment by jviki** [comment]
How can I configure BlueWallet to use Orbot? I cannot use Orbot as VPN at the moment. If I configure Orbot to run in non-VPN mode and mark BlueWallet to use it, in BlueWallet, I cannot connect my Electrum server behind tor. Is there some hidden proxy setting or something?

**Comment by davidohayon669** [comment]
@jviki why can't run it as a VPN?

in my experience the iOS orbot is terrible. on android it's usable enough

**Comment by davidohayon669** [comment]
@jviki i have no idea. i think it was very good that the tor was embedded into the app, it's better to improve these tools and reintroduce it to bluewallet

**Comment by Overtorment** [comment]
@eleaner agree, communication could have been better

**Comment by j4Hu** [comment]
> @Overtorment I guess no one can force BlueWallet to fix it if they don't want but I guess a few things would be nice:
> 
>     1. a clear info in a release notes
> 
>     2. a valid explanation why not and why now
> 
>     3. heads-up for those of us who would try to search another wallet instead

exactly, and it is really hard to find, if it is closed wontfix issue.
very sad
