### ISSUE TITLE
Newly added Ron currency does not display correct value of transactions. 

### ISSUE THREAD

**Issue by lorinbute** [BlueWallet/BlueWallet#5940]
On 6.4.12 version the Ron currency was added. When selected from the menu I can see the value of the dollar in Ron, so the exchange value is retrieved correctly. However, when looking at the list of transactions I can see very small amounts of Ron. For example: a 300 dollar transaction is displayed as 0,05 Ron. That is obviously incorrect. This happens on the iPhone 13 Pro Max, iOS 17.3.

**Comment by Overtorment** [comment]
@marcosrdz wana take alook? you added RON, right..?

**Comment by marcosrdz** [comment]
Yes. Ill take a look.
