### ISSUE TITLE
Can’t connect to Electrum server anymore 

### ISSUE THREAD

**Issue by MyAnonymousGitHubProfile** [BlueWallet/BlueWallet#5948]
I’ve been using BW without issue for months but now I get an error message that it can’t connect to my electrum servers (over Tor) anymore. I’ve tried different electrum servers (on different nodes) to make sure the problem wasn’t with my ES and I get the same issue: « can’t connect to the provided electrum server ».  I’ve tried to unstalling/reinstalling BW but getting the same issue.  My Electrum servers work with other clients (eg: Sparrow)

* your phone model and OS version: iPhone 14 Pro, iOS 17.2.1
* BlueWallet app version: 6.4.12
* self-test passes?: yes, OK
* unique ID for our crash reporting service: userid:3D744C3C-7A14-4D81-A04C-2E46A2986561

**Comment by nickshredaway** [comment]
Came here to post this exact issue. Confirmed it’s not my electrum server as I can connect to it using other apps/devices.

**Comment by Overtorment** [comment]
Tor support removed for now: https://github.com/BlueWallet/BlueWallet/issues/5931

**Comment by j4Hu** [comment]
"I guess no one can force BlueWallet to fix it if they don't want
but I guess a few things would be nice:

    a clear info in a release notes
    a valid explanation why not and why now
    heads-up for those of us who would try to search another wallet instead
"

it is really hard to find, if it is closed wontfix issue :((
