### ISSUE TITLE
Emergency shutdown of the app during restore/import [Android 9]

### ISSUE THREAD

**Issue by TheFuzzStone** [BlueWallet/BlueWallet#595]
Androd One (9.0)

I choose "_Create a wallet_", then "_Import Wallet_", I see a window where I need to enter a private key/mnemonic phrase to restore the wallet, I start typing and here it begins:

1. The wallet starts acting weird after I enter the second letter. It's weird, but the cursor jumps back one position;

2. If I start deleting letters from the right side, the application closes unexpectedly.

---
BlueWallet ver 4.2.0 (build 1563817231)

**Comment by marcosrdz** [comment]
Thanks for reporting this issue. Will be taking a look.

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/622/commits/f7d8b8a5476f0d627cb67f2146309e97cd0582c3
