### ISSUE TITLE
Tor option disappeared from settings.

### ISSUE THREAD

**Issue by Nothro** [BlueWallet/BlueWallet#5950]
For some reason, in my Settings, the tor option has disappeared and now my wallet, can't connect to my electrum server which uses an onion address. Why would Tor just disappear for no reason?

**Comment by frettor** [comment]
+1
iOS version

**Comment by davidohayon669** [comment]
@Nothro is was removed since the library wasn't maintained https://github.com/BlueWallet/BlueWallet/issues/5931

i think it's an opportunity to see what is lacking in these dependencies and try to improve them
https://github.com/BlueWallet/BlueWallet/issues/5931#issuecomment-1868360895

**Comment by nickshredaway** [comment]
> @Nothro is was removed since the library wasn't maintained #5931
> 
> i think it's an opportunity to see what is lacking in these dependencies and try to improve them [#5931 (comment)](https://github.com/BlueWallet/BlueWallet/issues/5931#issuecomment-1868360895)

Are you aware of any good alternatives to remote connect to electrum on iOS over tor?

**Comment by davidohayon669** [comment]
@nickshredaway you can always put a VPN on your machine like wireguard

**Comment by Nothro** [comment]
I ended up using Orbot to connect to tor on my iOS device. It worked out. Thanks to all for the input.

**Comment by FREEBORN-MAN** [comment]
+1 iOS device
Fixed by using Tailscale but I'm hoping the tor support comes back.

**Comment by ErBuitre** [comment]
Tailscale only for Electrum server, LNDhub not supported with Tailscale. Is that right? I could only connect my node with onchain wallet using Tailscale.

**Comment by Overtorment** [comment]
Lndhub should work with Tailscale, should be no difference between how electrum and lndhub work

**Comment by ErBuitre** [comment]
On the lightning configuration should I use
https://100.124.XX.XXX:50001 ??
Not working with this
