### ISSUE TITLE
Cannot read property 'broadcastTx' of undefined

### ISSUE THREAD

**Issue by TheBrownGent** [BlueWallet/BlueWallet#5960]
I'm on an iPhone 15 Pro (iOS 17.1.1) and get this error whenever I try to send BTC to another address after authenticating from a hardware wallet (Keystone 3 Pro ) and scanning the signed transaction in the app.

Bluewallet version: 6.4.13
Self-tests passed

**Comment by Overtorment** [comment]
should be fixed in .14

**Comment by karma247** [comment]
I am trying to send BTC from my blue wallet to another wallet using an offline signing device. I keep getting this error message "Cannot read property 'broadcastTx' of undefined"
Anyone having this issue
