### ISSUE TITLE
Cannot build past 42966ea

### ISSUE THREAD

**Issue by 3bitcoins** [BlueWallet/BlueWallet#5987]
Running `npx react-native run-android` on any commit after or including 42966ea fails with 

```
> Task :react-native-camera-kit:compileDebugKotlin FAILED

> Task :react-native-localize:compileDebugJavaWithJavac

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.6.3/userguide/command_line_interface.html#sec:command_line_warnings
426 actionable tasks: 11 executed, 415 up-to-date
e: file:///E:/bluee/BlueWallet/node_modules/react-native-camera-kit/android/src/main/java/com/rncamerakit/CKCamera.kt:183:17 'onScale' overrides nothing
Note: E:\bluee\BlueWallet\node_modules\react-native-localize\android\src\main\java\com\zoontek\rnlocalize\RNLocalizeModuleImpl.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-camera-kit:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 44s
```

I've been able to determine that the issues don't have to do with the new `scripts/react-native-camera-kit.patch`, as removing it and the references to it in `package.json` don't resolve the error. Moreover, it doesn't have to do with the changes in `package-lock.json` regarding adding a "resolved" url relating to the camerakit. 

As far as I can tell, all this leaves are the changes in `android/build.gradle` regarding android/kotlin versions. Indeed, when I revert these changes on their own, I hit a new error about the updated dependencies now being incompatible, and don't see anything about react-native-camera-kit beforehand. 

I'm guessing then that bumping the version numbers in `android/build.gradle` is causing issues with compilation of react-native-camera-kit, but it's odd that this is only occurring for me and nobody else has noticed it for 2 months.

**Comment by marcosrdz** [comment]
Remove node_modules folder and run "npm i" again

**Comment by 3bitcoins** [comment]
> Remove node_modules folder and run "npm i" again

I did this everytime I switched versions when finding the breaking commit; this does not solve the issue.

**Comment by marcosrdz** [comment]
Do you get the same result when trying to compile via Android Studio instead of terminal?

**Comment by 3bitcoins** [comment]
> Do you get the same result when trying to compile via Android Studio instead of terminal?

Not familiar with android studio.. how would I do that in this case? Is it possible to build react native apps from it? Or to somehow just test the building of camerakit?

**Comment by marcosrdz** [comment]
Open Android studio, click open project and select the android folder. Wait for to process and then click the green debug button

**Comment by 3bitcoins** [comment]
> Open Android studio, click open project and select the android folder. Wait for to process and then click the green debug button

The same issue occurs in android studio

**Comment by Overtorment** [comment]
we have a script that nukes all caches if there are some weird build issues:  `npm run clean`. not sure if itll work on windows. i'd say, start with installing linux first.

**Comment by marcosrdz** [comment]
I dont think we've ever tried building the code on Windows. We use Linux and macOS.

**Comment by Overtorment** [comment]
yeah otherwise bw builds great on CIs both android & ios.
