### ISSUE TITLE
How to see payment hash?

### ISSUE THREAD

**Issue by danbadjar** [BlueWallet/BlueWallet#600]
Hello,
is there a way to see the lightning payment hash made by Bluewallet?
If I click on the details of the payment I can see only the preimage.

Thanks

**Comment by Overtorment** [comment]
No. You can take preimage and hash it yourself tho

**Comment by pavlowd** [comment]
echo -n "{payment_preimage here}" | xxd -ps -r | sha256sum 
as result we have payment hash
