### ISSUE TITLE
Please use 8 decimal places for Bitcoin amounts

### ISSUE THREAD

**Issue by deardeardear1** [BlueWallet/BlueWallet#6009]
The random number of decimal places that Bluewallet uses in displaying Bitcoin amounts is a well known UX fail. Is it really that hard to fix? 

And if because of a necessity for sub-sat precision you must use >8 decimal places then ok that's fine but just use your imagination in highlighting this non-standard number of digits eg. commas, colors etc. As for using <8 decimal places that should absolutely never happen. Never ever.

Most wallets are recognising this and updating. You are lagging despite it being a really simple and powerful UX improvement.

**Comment by edjanx** [comment]
I agree that not having 0 characters makes it easier to mistake the number of Satoshis. I hate when trailing zeros are cut. Major usability fail IMHO and especially as a certified usability analyst from Human Factors International

**Comment by Overtorment** [comment]
we like it the way it is
