### ISSUE TITLE
Screenshot (Jan. 25, 2024 7:48:30 p.m.) BTC GeorgetteLeahCalahasen 1 B

### ISSUE THREAD

**Issue by calahasengleah13** [BlueWallet/BlueWallet#6053]
![Screenshot_20240125-194830.png](https://github.com/BlueWallet/BlueWallet/assets/118034563/270827b8-ee6f-4f96-a6a8-067d9a731459)

Hi I like to sign and create wallet to be able to send receive, do transfers and all that? First time programming My wallets? Depositing and withdrawing? I just like to make sure I have that when He shows, ThankYou. As well ...

**Comment by calahasengleah13** [comment]
I like to make sure that all My wallets are not watch only

**Comment by Overtorment** [comment]
its impossible to convert watch-only wallet to normal wallet without a private key.
if someone told you to import a watch-only wallet - you probably got scammed.
