### ISSUE TITLE
Feature Request: Saving PSBT in app for later signage

### ISSUE THREAD

**Issue by btsvr** [BlueWallet/BlueWallet#6054]
Wouldnt it be nice to be able to create and save psbt's (for multisig wallet)?

When signing a psbt in a multisig wallet it isnt saved in the app. Suppose i want to sign from multiple locations while using the app via my phone, i am forced to keep my app open in the meantime or my n/N signed psbt would be last. 
WHile having your keys distributed and not wanting to come toghether this is a challenge.

**Comment by Overtorment** [comment]
you __can__ export psbt as a file,and then import it in bluewallet on other device to finish signing:

![image](https://github.com/BlueWallet/BlueWallet/assets/1913337/c53e9685-4ba5-484f-a537-27b62fe07ebf)
![image](https://github.com/BlueWallet/BlueWallet/assets/1913337/3bd7f53f-4026-457b-8b98-7e5dd9898f99)
![image](https://github.com/BlueWallet/BlueWallet/assets/1913337/581eb8b2-b783-4163-b58a-8c4eee57944e)



on other device you need to go to Send->Top right menu ->import transaction


![image](https://github.com/BlueWallet/BlueWallet/assets/1913337/e7443705-cb64-443b-98ea-094b744a5dbc)

**Comment by btsvr** [comment]
Thanks for you quick response.

I understand it is possible to manually save/export the psbt. However from a user experience point of view, it would be better if the psbt is saved to app storage automatically upon creation of the transaction.

That way the psbt (e.g. 2/3 multisig with one signed with 1 signature) could still be listed in the app after closing and reopening the app. The user won't have to export and import the psbt manually.

Thanks for your consideration.

**Comment by Overtorment** [comment]
well that introduces a whole file management workflows in the app. its true what they say, every successfull software product given enough time mutates into Operating  System...
