### ISSUE TITLE
Change language name بختیاری in the file language.ts

### ISSUE THREAD

**Issue by hosseinabaspanah** [BlueWallet/BlueWallet#6067]
please change language name بختیاری to لۊری بختیاری

**Comment by marcosrdz** [comment]
Im not familiar with the language nor the locale. Please open a PR for review.

**Comment by hosseinabaspanah** [comment]
@marcosrdz I only need a language name change in the language.ts file, nothing else...

Because the original name of the Luri language is Bakhtiari, and this is how it is determined that it is a part of the Luri language...
