### ISSUE TITLE
plus/minus icon in quorum settings is reversed 

### ISSUE THREAD

**Issue by pointbiz** [BlueWallet/BlueWallet#6085]
* your phone model and OS version
Android Samsung S22 
* BlueWallet app version (settings->about->scroll down)
6.5.0

https://github.com/BlueWallet/BlueWallet/assets/1024428/3b839e00-7b59-4fe9-932f-dbd3c108923a

Plus reduces the number. Expecting plus icon to increase the number. 

Minis increases the number. Expecting minus icon to reduce the number.

Advanced mode is on in the settings. This is during Vault creation.

**Comment by weezyb0893** [comment]
5774e57115d075705fe36cbe6600e2e60a094cea

**Comment by weezyb0893** [comment]
5774e57115d075705fe36cbe6600e2e60a094cea
