### ISSUE TITLE
QR code scanner fails on quorum scan of xpub

### ISSUE THREAD

**Issue by pointbiz** [BlueWallet/BlueWallet#6105]
## Are you reporting a bug?

Please provide:
* your phone model and OS version
Android Samsung S22 
* BlueWallet app version (settings->about->scroll down)
6.5.1
* self-test passes? Open settings->about->scroll down, tap "Run self-test"
Yes

Setup a 2-of-2 vault quorum. 
Key 1 import 12-word phrase 
Key 2 import xpub via scanner (or static image) by sharing on a secondary phone that you inputted the Key 2 12-word mnemonic. The scanning fails.

The QR code with "ur:crypto-account" doesn't scan, the camera just stays open trying to scan.

If you open this QR code as an image then it loads a black screen with a loading indicator and it's stuck in a loop.

If I try to paste the "ur:crypto-account" in the import box it says invalid mnemonic. If I paste the xpub in wallet descriptor format like shown below it says invalid. 
[Abcdabcd/48'/0'/0'/2']Zpub6525
I expect it to be smart enough to accept this wallet descriptor format.

If I paste just the Zpub in the import box then it recognizes it and prompts me for the fingerprint then prompts me for the derivation path.

Please investigate.

**Comment by Overtorment** [comment]
thank you for the report!

can you pls provide all the qr codes that you are trying to import?  and the whole wallet setup.
could be a dummy ms wallet created just forthe purpose of demoingthis bug.

**Comment by pointbiz** [comment]
![Screenshot_20240212_171159_BlueWallet](https://github.com/BlueWallet/BlueWallet/assets/1024428/b570add1-fb5c-4f34-a7d0-a2f133551867)
![Screenshot_20240212_171224_BlueWallet](https://github.com/BlueWallet/BlueWallet/assets/1024428/7a7a0d2d-8b22-4504-b7fb-7032cdb4b9c9)
![Screenshot_20240212_171456_BlueWallet](https://github.com/BlueWallet/BlueWallet/assets/1024428/070785b0-6139-47fa-8d48-64a0b779c1ca)
![Screenshot_20240212_171630_BlueWallet](https://github.com/BlueWallet/BlueWallet/assets/1024428/ac35ceb2-88fe-4399-8ba4-c78b8939f9b4)

**Comment by pointbiz** [comment]
I'm creating a new 2 of 2 quorum.
Key 1 using seed by clicking import and typing in 12 words (or scanning QR but scanning doesn't work)
Key 2 using xpub QR above by clicking import and scanning.

These are dummy seeds.
Seed A 
pipe goose bottom run seed curious thought kangaroo example family coral success
Seed B
offer immense convince between club enroll mammal invest planet shed laptop segment

Anything else you need? Are you able to reproduce?

**Comment by sergio-quintero** [comment]
I have the same problem in 6.5.5. I had to downgrade to 6.4.8 and it works fine. I've not tested any other versions other than these two.

**Comment by niko-underwood** [comment]
I am using 6.5.5 as well. I'm also trying to create a 2 of 3 Multisig vault. I'm trying to import the key vs scanning with a QR code. When I select import file, select the key generated from the other wallet, BlueWallet just brings me back to the camera looking to scan a QR code. 

I've replicated the on the MacOS desktop running BW 6.5.5 as well as other iOS devices running 17.3.1

Thanks

**Comment by Overtorment** [comment]
@pointbiz thanks that was very helpful! was able to reproduce and submitted a fix
