### ISSUE TITLE
LDK Wallets no longer work for authentication

### ISSUE THREAD

**Issue by arbadacarbaYK** [BlueWallet/BlueWallet#6109]
## Are you reporting a bug?
yes

Please provide:

* your phone model and OS version
Android

* BlueWallet app version (settings->about->scroll down)
6.5.1 (auto-update to double icon first, now only one again)

* self-test passes? Open settings->about->scroll down, tap "Run self-test"
no, Error: Linking can not open https url

* unique ID for our crash reporting service (settings->about->scroll down, tap "copy")
f6b1970f12f5f36d

## Proposing a feature?
no

After auto-update the LDK wallet i had no longer works for authentication. When i open the wallet BlueWallet crashes

**Comment by Overtorment** [comment]
issuse identified: https://app.bugsnag.com/bluewallet/bluewallet/errors/62e77e4f9fa328000a0077d9?filters[event.since]=30d&filters[user.id]=f6b1970f12f5f36d

![image](https://github.com/BlueWallet/BlueWallet/assets/1913337/f99e2869-789b-48c2-b27e-a8af4e1c465f)

**Comment by arbadacarbaYK** [comment]
Thank you sirs !

**Comment by Overtorment** [comment]
will be rolled out in the next release. pls reopen if the fix isnot working

**Comment by arbadacarbaYK** [comment]
> will be rolled out in the next release. pls reopen if the fix isnot working

worked yesterday the whole day now again not working
