### ISSUE TITLE
Prevent Android Screenshot / screen sharing (FLAG_SECURE)

### ISSUE THREAD

**Issue by jurjendevries** [BlueWallet/BlueWallet#6128]
Feature request:

Most banking apps prevent screen sharing / taking a screenshot, also to avoid malware to look into the screen.

For example see a screenshot of my banking app and bluewallet, as you can see the banking app is blocking the screen, while bluewallet is showing the screen. This is even happening when using the export/backup seed function.
![Screenshot_protection](https://github.com/BlueWallet/BlueWallet/assets/355488/892dde5b-22d5-43c5-947e-7d2499d4856e)

For this on Android please see the display FLAG_SECURE api https://developer.android.com/reference/android/view/Display#FLAG_SECURE

Optionally you can let the user choose at the setting to have to enabled/disabled.

Thanks and keep up the good work.

**Comment by Pleb4Fun** [comment]
Ok - I see we now have that "feature" to block screenshots of the Wallet Export Screen. 
I understand the intention but where can it be disabled?!
I searched for an option in the privacy settings etc. but couldn't find anything.

I used that feature in the past - and I REALLY want to make a screenshot in my case knowing the risks.
(It's a hot wallet for a small gift on a vanitygen address and I want to print that nice QR Code - my screenshots never go into the cloud - and it will only be funded with a small amount)
 
Now I even installed the Dektop Version (MacOS) as screenshots will not be blocked there - but there the export screen has a stupid scroll bar that not all the Info incl. public and private keys fit in one screen... Arrrgh...

**Comment by marcosrdz** [comment]
> Ok - I see we now have that "feature" to block screenshots of the Wallet Export Screen. 
> 
> I understand the intention but where can it be disabled?!
> 
> I searched for an option in the privacy settings etc. but couldn't find anything.
> 
> 
> 
> I used that feature in the past - and I REALLY want to make a screenshot in my case knowing the risks.
> 
> (It's a hot wallet for a small gift on a vanitygen address and I want to print that nice QR Code - my screenshots never go into the cloud - and it will only be funded with a small amount)
> 
>  
> 
> Now I even installed the Dektop Version (MacOS) as screenshots will not be blocked there - but there the export screen has a stupid scroll bar that not all the Info incl. public and private keys fit in one screen... Arrrgh...

Go to Settings - general - privacy. Tap the sentence underneath Read Clipboard 10 times.

**Comment by Pleb4Fun** [comment]
Man I love you! 🧡 
Already frickled around with the Desktop Screenshot but now I made it on mobile and have the one I wanted.

Why don't you/we just put that option like a regular option in the menu? Even the mentioned ING App in the first post lets me just enable that feature with a toggle...

**Comment by marcosrdz** [comment]
> Man I love you! 🧡 
> 
> Already frickled around with the Desktop Screenshot but now I made it on mobile and have the one I wanted.
> 
> 
> 
> Why don't you/we just put that option like a regular option in the menu? Even the mentioned ING App in the first post lets me just enable that feature with a toggle...

Done

https://github.com/BlueWallet/BlueWallet/pull/6909

**Comment by Pleb4Fun** [comment]
Wow @marcosrdz - that was quick. 🙏 
I will remember you the next time I "need" that feature. 🧡  

(Also a bit proud on myself that I triggered that instant famous toggle button. 😮 )
