### ISSUE TITLE
Import button not visible on version 6.5.1 android

### ISSUE THREAD

**Issue by jurgen2005** [BlueWallet/BlueWallet#6133]
Android 13 v 6.5.1
Import button not visible on version 6.5.1 android for Bitcoin wallet, not able to scroll down

**Comment by marcosrdz** [comment]
Please provide a screenshot

**Comment by klutzer** [comment]
Same here. This happens just in advanced mode. So right now is not possible to import a wallet with a passphrase because it's just enabled in advanced mode.

**Comment by marcosrdz** [comment]
Please provide a screenshot. Im confused as its all working on my end

**Comment by jurgen2005** [comment]
![Screenshot_2024-02-17-23-44-08-93_33d451c556a6e6f31d43996663571c40](https://github.com/BlueWallet/BlueWallet/assets/6307085/a724c523-8ea2-438a-bccd-78fdb7eb3242)

**Comment by jurgen2005** [comment]
Import button is not visible at the bottom, scrolling is not possible.
