### ISSUE TITLE
6.5.3 crashes at startup on macOS 10.15.7

### ISSUE THREAD

**Issue by robster7674** [BlueWallet/BlueWallet#6141]
## Are you reporting a bug? Yes.

Please provide:

* your phone model and OS version: MacBook Pro
* BlueWallet app version (settings->about->scroll down) 6.5.3
* self-test passes? Open settings->about->scroll down, tap "Run self-test" No
* unique ID for our crash reporting service (settings->about->scroll down, tap "copy") n/a

Crash log:
[macos_blue_crash.txt](https://github.com/BlueWallet/BlueWallet/files/14312938/macos_blue_crash.txt)

**Comment by marcosrdz** [comment]
Minimum required is Big Sur
