### ISSUE TITLE
Unauthorized iCloud Sync!!

### ISSUE THREAD

**Issue by tysecure** [BlueWallet/BlueWallet#6152]
Why is BlueWallet syncing to iCloud without permission, and how can we halt this unauthorized activity? 

Currently, there are no accessible settings to address this issue, and BlueWallet is not listed among the apps syncing to iCloud. Moreover, during the process of deleting and reinstalling the app, it automatically links to a public node, negating the privacy benefits of connecting to a private one. How can we fix this and ensure user control over syncing preferences?

This is a serious problem! Version 6.5.4 on latest iOS 17.3.1

**Comment by Danswar** [comment]
@tysecure I'm intrigued, how can I check this on my end?

**Comment by tysecure** [comment]
Install BlueWallet
Connect to a private Electrum Server
Add a Watch only Wallet and wait for it to be up to date.
Delete BlueWallet from your phone
Re-install BlueWallet

Instead of having a blank BlueWallet, all your data is still there.

**Comment by Danswar** [comment]
> Install BlueWallet Connect to a private Electrum Server Add a Watch only Wallet and wait for it to be up to date. Delete BlueWallet from your phone Re-install BlueWallet
> 
> Instead of having a blank BlueWallet, all your data is still there.

I was able to reproduce this on my end, although I'm not entirely sure about whether this is for using iCloud. I searched iCloud.com and I see no data related to Bluewallet on my account, I also don't see any data being loaded when I install Bluewallet on another device connected with my iCloud.

Maybe some of the owners can explain what's going on here. I guess the app is using the storage of the phone.

**Comment by tysecure** [comment]
I don't see anything on iCloud either which is even more concerning if I consider the data might be saved elsewhere unauthorized. I also entertained the possibility that the data isn't being properly removed when deleting the app but I have never come across this issue with any other app so its unlikely. In the meantime, I have deleted all wallets from BlueWallet for reasons of security and privacy. I hope this issue gets resolved promptly so I can do back to trusting and recommending this app.

**Comment by Danswar** [comment]
In my phone if I go to Settings -> AppleID -> then tap on my phone -> iCloud Backup -> my phone again -> Show all apps, I see that there is a backup of BlueWallet, but so is for a bunch of other apps I don't remember to give any access. 

The thing is that disabling that application does not delete the 1.4MB of that backup. I also haven't found a way to see what data is stored in that backup. Still not sure if that is where the data persists between reinstalls.

**Comment by marcosrdz** [comment]
The data is for preferences. The wallets are not backed up on iCloud. The iOS Keychain is what's keeping the data on the device. @tysecure

**Comment by marcosrdz** [comment]
In order for an app to have iCloud capabilities you must add such capability under the project settings. The code is open source, you can confirm my statement by opening ios/BlueWallet.xcworkspace. Navigate to Signing & Capabilities. You won't find iCloud in that list

**Comment by Danswar** [comment]
> In order for an app to have iCloud capabilities you must add such capability under the project settings. The code is open source, you can confirm my statement by opening ios/BlueWallet.xcworkspace. Navigate to Signing & Capabilities. You won't find iCloud in that list

Thanks for the answer @marcosrdz , I confirmed this and it is correct, do you know a method for removing that data from the iOS keychain?

**Comment by marcosrdz** [comment]
Sadly, Apple doesn't offer an interface to wipe the device keychain. You have to manually delete all the wallets in the app

**Comment by tysecure** [comment]
Marco, thank you for clarifying all this. Does disabling the iCloud Keychain Sync stop this behaviour?

**Comment by marcosrdz** [comment]
Apple doesnt have access to the content due to it being encrypted.

**Comment by Overtorment** [comment]
for context, keystore/keychain is a dedicated secure chip thats present on all modern ios/android devices.  this is where all apps save their passwords and other secure data.
its isolated from other storage, and it survives if app is deleted and installed again.

**Comment by Danswar** [comment]
Thanks for the insights, I performed my own research over the code and confirmed that what you described is correct. Everything is fine in my opinion. Thanks for your time guys @Overtorment @marcosrdz. 

I have no arguments for closing this issue, it's up to you @tysecure, thanks for raising this concern.

**Comment by tysecure** [comment]
I'm good guys. Thank you very much for you quick help on this.
