### ISSUE TITLE
Deskop App / Linux version

### ISSUE THREAD

**Issue by robster7674** [BlueWallet/BlueWallet#6155]
## Proposing a feature?

It would be great to have BlueWallet as desktop app, see also https://github.com/BlueWallet/BlueWallet/issues/676. Having it available on Linux would be great in context of the freedom stack.

What would it take to make this a reality?

**Comment by robster7674** [comment]
Just realized that it actually runs on (fairly) recent macOS. What about Linux?

**Comment by marcosrdz** [comment]
The app is based on React Native. There is no Linux version for React Native apps. Hopefully one day there will be.
