### ISSUE TITLE
Verify change address when co-signing multisig transaction

### ISSUE THREAD

**Issue by TimYorke** [BlueWallet/BlueWallet#6156]
Glancing through the code, I don't see anywhere that checks that the change address of a transaction to be co-signed belongs to the wallet. 

If there's no check then it makes a multi-sig wallet vulnerable to attack by a comprised device that creates the transaction sending bitcoin to the address specified (easily checked by eye), but redirecting the change to the attackers wallet which would not be at all obvious. 

Would someone consider adding this check to the signing process, along with a warning (with possible implications) if the change address is found to be one not owned by the multi-sig wallet?

**Comment by Overtorment** [comment]
good point.

on the other hand, BW calculates differencve between inputs & __owned__ outputs to get the exact amount transaction spends, so the user can actually how much is being spent and if it is exactly as he intended.

checking change is a tricky subject, cause  its perfectly legis scenario to spend all inputs and split them between multiple destinations so there is no change

**Comment by TimYorke** [comment]
Great to hear that the change addresses are checked in order to calculate the total amount. As far as I'm concerned that makes my request unnecessary - the user just needs to check the destination and amount on the offline signing device (as they should do anyway) and can then be confident that the change address is as it should be.
