### ISSUE TITLE
Importing watch-only via QR code is broken

### ISSUE THREAD

**Issue by BitcoinQnA** [BlueWallet/BlueWallet#6159]
iPhone 12 running iOS 17.2.1 (replicating on Android too)
BlueWallet version 6.5.4
Self test passing
No crashing

When trying to pair a QR based hardware wallet, Blue get stuck at 99% scanned. I have replicated this on the iOS and Android versions of the app, as well as using both the Passport and Jade hardware wallets in single and multisig export options. I have documented the experience in [this video](https://drive.google.com/file/d/1h1Z6Yb_Nzaz9ngCZmhGDqi57_90JLgC5/view?usp=sharing).

The Passport is running firmware version 2.2.0 and the Jade 1.0.21.

![IMG_0290](https://github.com/BlueWallet/BlueWallet/assets/64638670/86da218e-cb85-4558-ae78-e2775401d645)

**Comment by marcosrdz** [comment]
Does this still occur on 6.5.7?

**Comment by BitcoinQnA** [comment]
This is fixed in iOS 6.5.7, thank you.
