### ISSUE TITLE
Export wallet improvement

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#62]
On the export page, we should warn users about how important the safety of their keys are and make some simple recommendations about not screen shooting the keys/seeds or recording them online.

**Comment by mritzmann** [comment]
I would like to store the Private Key in my Password Manager, as a backup. Unfortunately there is no Copy & Paste function on the export screen.

> about not screen shooting the keys/seeds

So I have to take a screenshot.
