### ISSUE TITLE
Add warning to or restrict delete wallet option when it has balance

### ISSUE THREAD

**Issue by brmdbr** [BlueWallet/BlueWallet#620]
So today I wanted to transfer my lightning balance back onchain, I could not find an option to do that so I guessed that would happen or be at least asked for when removing the wallet within blue. < but It didn't, without a proper warning my lightning wallet was removed and I'm not capable to get my funds back without a backup. 

Then clicking delete inside a wallet it should at least show a warning that the wallet is gonna be gone and the funds too, maybe wallets with balance shouldn't even be allowed to be removed.

Issue created after talking to: @ncoelho

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/623/commits/bf78165780893934c755781f368de612c2adb3a5
