### ISSUE TITLE
Latest iOS version has issue accessing the security menu

### ISSUE THREAD

**Issue by lorinbute** [BlueWallet/BlueWallet#6209]
On the latest iOS version if you tap the 3 dots in the top right corner to access the menu and then tap on Security it does not open the security menu. If you go back one view and try to tap anything else it does not register the tap. I have to quit the app. I understand this is an open source project but can you at least make sure the basic stuff works? Can you have some regression testing? Automated of course. Seems like I have to report an issue with each release.

**Comment by Overtorment** [comment]
We have that scenario covered in e2e test ( tests/e2e/bluewallet.spec.js:49 ), and separate full e2e tests for security functionality, but tests run only on very specific version on Android.

What device are you on?
