### ISSUE TITLE
Can't obtain currency rate for USD

### ISSUE THREAD

**Issue by mikeyb233** [BlueWallet/BlueWallet#6234]
OnePlus 7 pro, Android 12
BlueWallet version 6.5.7
Self Test passes

When trying to select USD in the currency settings I receive the following pop up error message:

Alert
There was an error while obtaining the rate for the selected currency.: Could not update rate from Bitstamp for USD: JSON Parse error: Unexpected character: <}

**Comment by marcosrdz** [comment]
What are the network conditions? Are u using a vpn? Clearnet? Orbot?

**Comment by mikeyb233** [comment]
This is using Orbot. 

Also many of the other currencies work just fine.

**Comment by marcosrdz** [comment]
Related: https://github.com/BlueWallet/BlueWallet/issues/6222

**Comment by Overtorment** [comment]
what can we do here?  api doesnt want to work through Tor

**Comment by marcosrdz** [comment]
Does AED work for you when using Orbot? @mikeyb233

**Comment by mikeyb233** [comment]
Yes it does. And others from Coindesk, CoinGecko, Yadio seem to work as well.
