### ISSUE TITLE
HD wallet restore restores only first wallet

### ISSUE THREAD

**Issue by aseidlitz** [BlueWallet/BlueWallet#624]
v4.4.1 wallet iOS. I am restoring BTC HD wallet created in Copay iOS app v. 6.2.1. The same seed is used to create two separate P2PKH wallets. One uses m/44’/0’/0’ derivation path and another uses m/44’/0’/1’. Only the first wallet is restored. 

Expected behavior is to ask for (optional) derivation path and restore additional wallets if required.

**Comment by Overtorment** [comment]
https://github.com/BlueWallet/BlueWallet/issues/1989
