### ISSUE TITLE
Add: Bitcoin-accepting Stores to On-Chain Marketplace 

### ISSUE THREAD

**Issue by nighttimeBIT** [BlueWallet/BlueWallet#625]
since there's already a bunch of shops on the integrated LN Marketplace, i thought adding a few stores that accept Bitcoin would be the logical step

Proposal/Examples:

Bitrefill.com 
Travala.com
TravelByBit.com
Bitcoinpike.com

More Stores welcome!

**Comment by Overtorment** [comment]
https://github.com/BlueWallet/Website/commit/b327b90d2fc918f02aa1d235484eac083f136df6

**Comment by Overtorment** [comment]
https://github.com/BlueWallet/Website/commit/eb7a1ba5fe51d2f0312005a19bb76627459d49c5
