### ISSUE TITLE
Add: Address Book

### ISSUE THREAD

**Issue by nighttimeBIT** [BlueWallet/BlueWallet#626]
instead of copy & pasting Bitcoin Addresses everytime you want to send, it should be possible to save a certain Address and attach a Name to it, then save it on some type of Address Book in-app.

this is especially practical if you want to donate to Non-Profits & Individuals working on Bitcoin Products & Education internationally.

So you can contribute to your Favourite Bitcoin Product/Educator by donating to them/him/her by having saved their onchain donation address.

**Comment by marcosrdz** [comment]
@ncoelho

**Comment by Overtorment** [comment]
Address book is tricky in btc space since the obvious way to implement this is address reuse, and that is not very good

**Comment by nighttimeBIT** [comment]
@overtorment

still, some people or companies use static addresses as donation source.

also, it would be possible to implement „pay to X/Y/Zpub
so you can save a contact, without the funds going to a static address everytime.

**Comment by ncoelho** [comment]
Closing this issue for now
