### ISSUE TITLE
Parece que há um problema no layout na recuperação da seed

### ISSUE THREAD

**Issue by ricaum** [BlueWallet/BlueWallet#6263]
Na opção de importar wallet/scan or import a file  não apareceu a opção "Use um caminho de derivação personalizada".
              Tive a impressão que quando fui recuperar a seed no modo off-line apareceu um gif girando (loding) e a opção (Use um caminho de derivação personalizada) foi para baixo e ficou escondida.

https://user-images.githubusercontent.com/162527440/311904948-2b86ad4c-4aeb-4f6e-b484-6827856d3ee1.mp4

_Originally posted by @ricaum in https://github.com/BlueWallet/BlueWallet/issues/6232#issuecomment-1986101386_

**Comment by Overtorment** [comment]
english only
