### ISSUE TITLE
Connecting to LNDHUB - Network request failed - Known React Native issue with private Certificate Authority 

### ISSUE THREAD

**Issue by bitcoinlizard** [BlueWallet/BlueWallet#6285]
## Are you reporting a bug?
Yes however it's a bug with React Native.  BlueWallet may be able to work around the issue.

Please provide:

* Phone - Graphene OS - Pixel 6a 
* BlueWallet Version - 6.5.9
* self-test passes? Yes

## Proposing a feature?
No

If you attempt to connect to LNDHUB with a non-public Certificate Authority you will get the rather ambiguous error of "Network request failed" even if you have added the CA Certificate to the trusted CA certificate store in Android.  This is not really a BlueWallet issue, rather it is an long standing issue with React Native discussed in detail here:

https://github.com/facebook/react-native/issues/32931

The linked issue discusses work arounds for this issue.

For context, I'm able to successfully connect to the same LNDHUB instance with certificate verification turned on (and the non-public CA certificate installed in the Android certificate store) with Zeus Wallet.  

Is this something that the BlueWallet development team would be willing to provide a workaround for in the BlueWallet code?  If not I can work around the issue with Let's Encrypt certificates.  

Either way I thought it would be good for this issue to be documented somewhere on the internet as it took me a fair amount of time to put the pieces together and figure out exactly what was going wrong.

**Comment by bitcoinlizard** [comment]
"If not I can work around the issue with Let's Encrypt certificates."

Just a quick follow up.  Indeed, if I use a publicly trusted certificate like a Let's Encrypt certificate, BlueWallet is able to connect to my LNDHUB instance without issue.

**Comment by bitcoinlizard** [comment]
I understand that development time shouldn't really be spent on this corner case.  This is really a bug or lack of proper functionality in React Native and although it might be possible for BlueWallet to incorporate a work around, this should really be solved in React Native.  

As it took me a while to figure out why I couldn't connect to my LNDHUB and the error from React Native is not helpful, I thought it might help someone if this was documented somewhere and that has now been done.  

BlueWallet will display the error message "Network request failed" if you attempt to connect to an LNDHUB instance secured by certificates generated by your own trusted CA instead of a publicly trusted CA.  

Closing issue.

**Comment by luisschwab** [comment]
I'm also experiencing this issue using a self-signed cert. Perhaps propagate RN's error message to the user?

**Comment by Overtorment** [comment]
> I'm also experiencing this issue using a self-signed cert. Perhaps propagate RN's error message to the user?

i looked into that some years ago, but wasnt doable at the time. decided to leave as is
