### ISSUE TITLE
Dark Mode & Color-Change Proposal for LN Wallets

### ISSUE THREAD

**Issue by nighttimeBIT** [BlueWallet/BlueWallet#630]
add dark-mode (preferred Feature on literally any app) & change the Lightning Wallets *Card* to Purple-ish, instead of Yellow. 

Brings more Contrast and doesn‘t blend Users Eyes, also stays true to the Title *BLUE*Wallet
would propose colour hex #7027c3 for that.

**Comment by strowger** [comment]
Yup the spend screen is confusing (white text on light grey background) at the moment if an IOS user has systemwide dark mode selected.

**Comment by limpbrains** [comment]
Dark mode implemented
