### ISSUE TITLE
Importing mixed BIP44/49/84 wallets impossible

### ISSUE THREAD

**Issue by hgmichna** [BlueWallet/BlueWallet#631]
A Mycelium HD wallet imported into BlueWallet via the 12 seed words can yield a deviating balance, apparently when some transactions involve Bech32 addresses. See here:

https://github.com/mycelium-com/wallet-android/issues/483

In short, Mycelium uses a mixed approach, combining BIP 44, 49, and 84 into one HD wallet. Some other wallets do this too, but hardware wallets cannot do it, and BlueWallet has apparently also taken a different path, probably separate wallets.

To import a mixed wallet, I should be able to import the same wallet twice, once as a BIP49 wallet and once more as a BIP84 wallet. However, after importing it once, BlueWallet refuses to import from the same seed words again, although I choose different wallet styles (BIP49 and BIP84) for the two imports. This looks like a defect to me.

**Comment by Overtorment** [comment]
Acknowledged. BW imports only single scheme, like BIP84 only, or BIP49 only.
I will add option to import several schemes with same mnemonics when I will be refactoring import procedure.

**Comment by clonmac** [comment]
Is there a current priority or preference that BW takes when importing a mnemonic seed that utilizes multiple derivation paths? Does BIP84 take precedence over BIP44, for example?

**Comment by Overtorment** [comment]
First of all, BW tries to fetch transactions list, and whichever first has
non-zero transactions is imported. Its a cascade of ele-ifs and there is
some priority there obviously.

If no transactions were found, then if I remember correctly it is imported
as BIP49 at the moment (will be changed to BIP84 when we will make BIP84
the default wallet type).
The whole code that handles import is messy and I plan to refactor it
massively soon.

**Comment by clonmac** [comment]
Thanks for the response. That sounds like what I was hoping you'd say. I'm assuming when you say whichever first has non-zero transactions, that means scanning from the most recent block backward in time, correct (most recent txn)? That would be ideal and can at least be gamed to allow for importing of the proper derivation scheme that is needed or being used most recently.

**Comment by Overtorment** [comment]
Sorry for late reply.
Not exactly, BW uses electrum server, so we can instantly see which address
has transactions. So we just take a batch of about 20 addresses in each
hierarchy (BIP84, BIP49, BIP44), and check which hierarchy has any
transactions.

**Comment by clonmac** [comment]
> Sorry for late reply. Not exactly, BW uses electrum server, so we can instantly see which address has transactions. So we just take a batch of about 20 addresses in each hierarchy (BIP84, BIP49, BIP44), and check which hierarchy has any transactions.
>

No worries. I was having a look around myself as well. It looks like according to [here](https://github.com/BlueWallet/BlueWallet/blob/master/screen/wallets/import.js) it looks for any current balances first (BIP84, BIP49, BIP44 respectively), then if no balances, it will check for transactions in that order. I can work with that. Thanks!

**Comment by benjaminmcdonald** [comment]
This also applies to importing mycelium pubkeys. Mycelium uses both xpub, ypub and zpub for public keys (m/44'/0', m/49'/0', m/84'/0'). You can import these individually.

Ideally, these would be shown in the UI as one wallet
And the user should only need to import the key once in the interface

**Comment by Overtorment** [comment]
I never used mycelium, do you have a mycelium backup I can use for tests? maybe some old wallet that's empty and not used anymore? --> i@bluewallet.io

**Comment by benjaminmcdonald** [comment]
mycelium has a testnet wallet on the Android playstore that can be used for testing

https://play.google.com/store/apps/details?id=com.mycelium.testnetwallet

**Comment by Overtorment** [comment]
that wont work for me

**Comment by limpbrains** [comment]
With the new BlueWallet import workflow you can now have multiple wallets with same seed, but different derivation paths or wallet types
