### ISSUE TITLE
Offline Import-wallet issue

### ISSUE THREAD

**Issue by rubber93duck** [BlueWallet/BlueWallet#6314]
When I try to import a wallet while offline, I get the error message (as expected) and then after closing it the "Use a customised derivation path" option doesn't appear. 
I had the impression that when I went to retrieve the seed in offline mode, a rotating gif appeared (loding) and the option (Use a customised derivation path) went down and was hidden.

I'm using Android 7v;
BlueWallet I've tried any versions 6.2.17 above;

![Captura de tela 2024-03-22 163642](https://github.com/BlueWallet/BlueWallet/assets/164556937/93cc49a7-8962-4afd-b076-0a81fc591b8d)

**Comment by Overtorment** [comment]
@limpbrains

**Comment by ricaum** [comment]
The custom derivation option does not appear.

It seems like it's a layout problem when retrieving the seed in offline mode. A rotating (hosting) gif appears and the option (Use a custom branch path) goes down and the option is hidden.

**Comment by rubber93duck** [comment]
Hey all.

I managed to get the "Use a customised derivation path" option to appear. I tried so many ways that I succeeded, doing the following steps:

1. After opening the app I created a new wallet, copied the seeds from this and then deleted the wallet. 

2. I went to restore and entered the seeds from this newly created wallet, and then the option finally appeared. 
 3. After doing this I simply deleted the newly created wallet and went to restore again to get my real wallet and... the "Use a customised derivation path" option was there. 

I don't know exactly why, but currently the option is there and has remained there, it seems some validation bug, but by doing this process the "Use a customised derivation path" option has been "unblocked"

**Comment by limpbrains** [comment]
"Use custom derivation path" button only appears if the input is a correct BIP39 seed. 
I believe you simply made a typo, which is why the button was missing.

**Comment by ricaum** [comment]
In the offline wallet, there is no option to import if the seed is generated outside the app.

https://github.com/BlueWallet/BlueWallet/assets/162527440/2b3f1849-155c-4c6d-b17f-3fa8c928628f

**Comment by limpbrains** [comment]
@ricaum Custom Derivation Path indeed not available when you are importing XPUB. We should probably add it

@rubber93duck ate you also trying to import XPUB?

**Comment by xshifty** [comment]
> In the offline wallet, there is no option to import if the seed is generated outside the app.
> 
>  536d1433-dbcf-46e4-a2d6-8c29ad2f9531.mp4

I'm facing this same problem.

**Comment by rubber93duck** [comment]
It's working as expected now using the latest version (6.6.2).
As @limpbrains said it could be a typo, but anyway it's working now.
