### ISSUE TITLE
Wallet import text box - jumping cursor and crashes

### ISSUE THREAD

**Issue by hgmichna** [BlueWallet/BlueWallet#632]
When importing a wallet through the 12 seed words I copy-paste a deliberately incorrect string into the import text box, then correct it by editing (to avoid a valid seed in the clipboard).

Editing is awkward, because the cursor keeps jumping left or right, usually by one character.

When I first try to delete the very last letter, the app crashes.

**Comment by marcosrdz** [comment]
This issue has been fixed and will be available on 4.5.0
