### ISSUE TITLE
Can't sign transaction from watch-only wallet

### ISSUE THREAD

**Issue by Jikoun** [BlueWallet/BlueWallet#6325]
Hello,
Could you please help me with small problem?

I imported coldcard (native segwit) to sparrow, then I imported xpub (legacy by mistake) to bluewallet watch-only and there I generated receive address and send some sats there, but then I realized I should have imported zpub (bc addresses). And now I cannot sign the transaction in bluewallet so I can't send it to bc address. Where am I going wrong, please? 

Thanks.  
![Uploading IMG_2330.jpg…]()

**Comment by captJiri** [comment]
I have the same problem with Jade HW. Watch only stopped working with PSBT (air tx). Also blue wallet can't connect via tor to my node (umbrel) electrum server anymore, so using default ES. But f.ex. green wallet still connects to the same ES link. Problems started probably with some update some months ago.

**Comment by Overtorment** [comment]
@Jikoun BW cant sign anything if it imported a watch-only (via xpub).

you should create transaction in BW, sign it with coldcard, and then broadcast.


let me know which steps are failing for you, and post some screenshots pls

**Comment by Jikoun** [comment]
Transaction creatd, coldcard wasn’t able to sign it. Passphrase correct and tested, wallet correct. 
![Uploading IMG_2330.jpeg…]()

**Comment by Overtorment** [comment]
not a correct uploaded screenshot

**Comment by Overtorment** [comment]
what was the error on coldcard?

**Comment by Overtorment** [comment]
my guess, is that fingerprint was not imported with the xpub (coldcard checks it when signing the transaction).
check if youve got the correct one in wallet->details

**Comment by Jikoun** [comment]
Xpub in sparrow is the same as in bw. Coldcard shows as attached. 
![Uploading IMG_2330.jpeg…]()

**Comment by Jikoun** [comment]
I do not know if it is attached. It writes Path m 44’0’0’0 led to wrong pubkey for input #0

**Comment by Overtorment** [comment]
1) what fingetprint your watch-only wallet displays?
2) go to https://jlopp.github.io/xpub-converter/ and convert your xpub to zpub. is it the same what coldcard gives you? (if thats the case, you used wrong path, you will just need to reimport watch-only but with `m/84/...` path for coldcard to "see" it)

**Comment by Jikoun** [comment]
1. Both have the same in sparrow. In bw I cannot view fingerprint. 
2. I converted it and showed me balance that I normally see, but not the one I need to see and sign in xpub (legacy address). I do not know if I understand it well, seems not. Nothing works.

**Comment by Overtorment** [comment]
you can view FP in bluewallet if you go to wallet details screen. make sure its not `00000000`

so looks like to spend your coins you need to import  your zpub (as segwit native wallet), but specify the custom path for legacy wallet (m/44 etc).

you can use any wallet for this, not necessarily bluewallet.

**Comment by mikeyb233** [comment]
I have tried exporting the xpub with both coldcard (doesn't provide fingerprint) and jade (does provide fingerprint) and both give the error "Should not be used in watch-only HD wallets"  even after enabling the "Use with Hardware Wallet" toggle. This occurs in the latest Android version 6.6.5 as well as the previous.

**Comment by tiagodread** [comment]
I could reproduce the same error, in this case, using BW and JADE. What happened was that the watch only wallet previously on BW had the fingerprint `00000000` since it was imported used plain `xpub` text. By trying to sign a PSBT created from BW on Jade wouldn't work since the fingerprint is different on Jade. After removing the watch only wally from BW and re-importing again (this time using xpub from Jade) I could see that the fingerprint is different from `00000000` and could create again the PSBT and sign it successfully on jade to be broadcasted.

**Comment by Overtorment** [comment]
@tiagodread how did you get this error?
to my understanding, BW should create a PSBT with `00000000` fp, and _THEN_hw wallet refuses to sign it because fp doesnt match.
