### ISSUE TITLE
Generate seed with 12 words using entropy

### ISSUE THREAD

**Issue by Mikael-R** [BlueWallet/BlueWallet#6344]
I have try generate a seed using 12 words with entropy and got a issue that I cant do that, because its on hard code to generate only 24 words size

![image](https://github.com/BlueWallet/BlueWallet/assets/60241602/b4955c89-46b6-4906-944c-2e4ce9e04503)
![image](https://github.com/BlueWallet/BlueWallet/assets/60241602/1be282d8-0096-4ab4-bcbb-85702fcb4642)
![image](https://github.com/BlueWallet/BlueWallet/assets/60241602/6840316a-3bf8-48af-9ae3-29d7820feb27)

**Comment by Overtorment** [comment]
i think it boils down to same debate 24 vs 12 words.

i think in this particular case,  since user can shoot himself in the foot providing low quality entropy, we want  to add system entropy as much as possible, thus, 24 words.

@limpbrains thoughts?

**Comment by Mikael-R** [comment]
> i think it boils down to same debate 24 vs 12 words.
> 
> i think in this particular case, since user can shoot himself in the foot providing low quality entropy, we want to add system entropy as much as possible, thus, 24 words.
> 
> @limpbrains thoughts?

Ok its a good question but lets make this clear for users, like add an alert saying caution with low entropy and 12 words, and check user entropy is weak or strong

**Comment by limpbrains** [comment]
I think we should add this feature. Demanding 24 words doesn't make the process more secure.

**Comment by Overtorment** [comment]
@limpbrains simple checkbox switch? 12/24 words?

**Comment by limpbrains** [comment]
Alert with 2 buttons :)
