### ISSUE TITLE
on android doesn't highlight addresses that belong to user in tx details

### ISSUE THREAD

**Issue by pony-montana** [BlueWallet/BlueWallet#6348]
Hi, when click on tx details I see inputs and outputs of a tx. It would be great to highlight the address that belong to the wallet of the user.
Electrum does that coloring in green the receive addresses, in yellow the change addresses, and leaving in grey the address that don't belong to the user wallet.

**Comment by Overtorment** [comment]
we do that already, own addresses are bold.

**Comment by pony-montana** [comment]
then something is wrong on android (only view only wallet tested):
![Screenshot_20240328-215311](https://github.com/BlueWallet/BlueWallet/assets/96387969/c512cb09-b350-40b5-98e3-1bcce693f25c)

in this case "my address" is the one sending the tx.
This is not my transaction, I just imported the first tx I found mined recently, not mine nor any private informations here, just picked public timechain data.

I also tested with other transactions and addresses are never highlighted.

**Comment by Overtorment** [comment]
hmm, indeed, this is how deposit tx looks on android:

![image](https://github.com/BlueWallet/BlueWallet/assets/1913337/fa9ba358-3256-45dc-8af7-d4e177c2bd19)

**Comment by Overtorment** [comment]
![image](https://github.com/BlueWallet/BlueWallet/assets/1913337/3522793a-ea10-4387-bfcc-f388a62c0be6)

And this is ios

**Comment by Overtorment** [comment]
@marcosrdz wana look into it? text is not bold on android for some reason

PS. for spend transactions, there is no point in bolding inputs as they are generally all belong to you

**Comment by pony-montana** [comment]
could be some updated react-native module used to highlight text?

**Comment by Overtorment** [comment]
OTOT, we do support payjoin, so sometimes not allinputs will belong to you... but lets worry about that another day
