### ISSUE TITLE
Improve accessibility: Join the Bitcoin Design Community with Global Accessibility Awareness Day

### ISSUE THREAD

**Issue by mouxdesign** [BlueWallet/BlueWallet#6352]
Hey Blue Wallet team,
Over at the Bitcoin Design Community we are participating in Global Accessibility Awareness Day by inviting builders for a quick one hour session with the community to learn about how to test for and improve accessibility. We would be super grateful if one person or a few people from the team could join. We'll keep things very hands on and practical during the session.

Its on the 16th of May at 7:00 UTC. [Event Link](https://github.com/BitcoinDesign/Meta/issues/655)

Also a link here for the page we added to the [Bitcoin Design Guide](https://bitcoin.design/guide/designing-products/accessibility/) about Accessibility.

![303594583-2316b9c3-d6c6-4004-867f-a0a75310f907](https://github.com/BlueWallet/BlueWallet/assets/90313394/39995726-2c1c-4834-8bc0-5a9f1eceec06)

**Comment by Overtorment** [comment]
@ncoelho

**Comment by mouxdesign** [comment]
This was a great event which was well attended and received. Thanks for all who joined and looking forward to organizing another one next year.
