### ISSUE TITLE
Seed words not displayed in full length!

### ISSUE THREAD

**Issue by elkimek** [BlueWallet/BlueWallet#638]
Hi, when creating the a onchain wallet seed words are not displayed in their full length. I think this is serious bug which can occur in loose of funds.

See words 13. and 23.

Happens on iPhone SE.

<a href="https://postimg.cc/0MTDTsB7" target="_blank"><img src="https://i.postimg.cc/0jQnJ5GX/AD47-CDD2-CB94-45-FB-AAD2-4-BECF018553-D.png" alt="AD47-CDD2-CB94-45-FB-AAD2-4-BECF018553-D"/></a><br/><br/>
<a href="https://postimg.cc/bDD1VJ3z" target="_blank"><img src="https://i.postimg.cc/Y9889LFm/28541841-9-B13-4-A5-E-856-E-AF2-F62110728.png" alt="28541841-9-B13-4-A5-E-856-E-AF2-F62110728"/></a><br/><br/>

**Comment by Overtorment** [comment]
Valid point. Will be fixed. We didnt really test it on iphone se.
To be fair, funds cant be lost, there are only 2048 words and they are
specifically chosen to be as distinct as possible. So its possible to
lookup correct word knowing only first couple of letters.

**Comment by ncoelho** [comment]
This PR should fix it https://github.com/BlueWallet/BlueWallet/pull/496

Meanwhile, if you want to see your full words you can to your wallet top right options and tap on "backup/export"

**Comment by Overtorment** [comment]
Actually, I think we can embed correction to the import procedure so even
mistyped mnemonic like you just showed will be imported correctly

**Comment by elkimek** [comment]
Agree it's possible to find out the correct words but might be bad experience for noob users.

**Comment by ncoelho** [comment]
Fixed awhile ago, closing this issue.
