### ISSUE TITLE
Error: can not add duplicate data to array

### ISSUE THREAD

**Issue by bitboba** [BlueWallet/BlueWallet#6381]
I created 3 same seed phases with 3 different passcodes on Coinomi, and used them to generate multisig vault on bluewallet. I was able to send fund but when i withdraw, this error popped up : “ can not add duplicate data to array.” Is there anyway I can retrieve the fund ? Thank you.

**Comment by Overtorment** [comment]
okay BW was incorrectly handling such case (same seed but different passphrase), resulting in wring addresses derived.

fix is in progress here: https://github.com/BlueWallet/BlueWallet/pull/6382

you will have to reimport the wallet, but it wont see the funds you sent already, this wallet will derive totally different addresses.

im looking into how to recover funds, should be relatively easy, bear with me

**Comment by bitboba** [comment]
Thank you so much for putting efforts in helping me with this . Appreciate
it.

**Comment by Overtorment** [comment]
for the record, the patch in BW to recover funds stuck in multisig with same pubkeys

```
diff --git a/class/wallets/multisig-hd-wallet.ts b/class/wallets/multisig-hd-wallet.ts
index 723226e5d..30f56035d 100644
--- a/class/wallets/multisig-hd-wallet.ts
+++ b/class/wallets/multisig-hd-wallet.ts
@@ -235,7 +235,7 @@ export class MultisigHDWallet extends AbstractHDElectrumWallet {
 
     if (fingerprint && this._cosignersFingerprints.indexOf(fingerprint.toUpperCase()) !== -1 && fingerprint !== '00000000') {
       // 00000000 is a special case, means we have no idea what the FP is but its okay
-      throw new Error('Duplicate fingerprint');
+      // throw new Error('Duplicate fingerprint');
     }
 
     const index = this._cosigners.length;
diff --git a/tests/unit/multisig-hd-wallet.test.js b/tests/unit/multisig-hd-wallet.test.js
index 5c6c101c0..37238de82 100644
--- a/tests/unit/multisig-hd-wallet.test.js
+++ b/tests/unit/multisig-hd-wallet.test.js
@@ -4,6 +4,20 @@ import Base43 from '../../blue_modules/base43';
 import { BlueURDecoder, decodeUR, encodeUR } from '../../blue_modules/ur';
 import { MultisigHDWallet } from '../../class/';
 import { MultisigCosigner } from '../../class/multisig-cosigner';
+import * as BlueElectrum from '../../blue_modules/BlueElectrum';
+
+jest.setTimeout(90 * 1000);
+
+afterAll(async () => {
+  // after all tests we close socket so the test suite can actually terminate
+  BlueElectrum.forceDisconnect();
+});
+
+beforeAll(async () => {
+  // awaiting for Electrum to be connected. For RN Electrum would naturally connect
+  // while app starts up, but for tests we need to wait for it
+  await BlueElectrum.connectMain();
+});
 
 const fp1cobo = 'D37EAD88';
 const Zpub1 = 'Zpub74ijpfhERJNjhCKXRspTdLJV5eoEmSRZdHqDvp9kVtdVEyiXk7pXxRbfZzQvsDFpfDHEHVtVpx4Dz9DGUWGn2Xk5zG5u45QTMsYS2vjohNQ';
@@ -1951,6 +1965,38 @@ describe('multisig-wallet (native segwit)', () => {
     assert.strictEqual(w.getCosignerPassphrase(3), w2.getCosignerPassphrase(3));
   });
 
+  it.only('can recover funds from multisig with same pubkeys', async () => {
+    const path = "m/48'/0'/0'/2'";
+    const w = new MultisigHDWallet();
+    w.addCosigner(
+      'abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about',
+      undefined,
+      undefined,
+      '1',
+    );
+    w.addCosigner(
+      'abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about',
+      undefined,
+      undefined,
+      '1',
+    );
+    w.setDerivationPath(path);
+    w.setM(2);
+
+    await w.fetchBalance();
+    console.log(w.getBalance());
+    await w.fetchUtxo();
+
+    const { tx } = w.createTransaction(
+      w.getUtxo(),
+      [{ address: '13HaCAB4jf7FYSZexJxoczyDDnutzZigjS' }],
+      10,
+      '13HaCAB4jf7FYSZexJxoczyDDnutzZigjS',
+    );
+
+    console.warn(w._getExternalAddressByIndex(0), tx.toHex());
+  });
+
   it('can work with passphrases when seeds are the same but passwords differ', () => {
     // test case from https://github.com/BlueWallet/BlueWallet/issues/3665#issuecomment-907377442
     const path = "m/48'/0'/0'/2'";

```




also in `node_modules/bip174/src/lib/utils.js`  comment out  line 90 so its not throwing an error:

```
          if (!data.every(v => canAddToArray(arr, v, dupeCheckSet))) {
            //throw new Error('Can not add duplicate data to array');
          }
```

**Comment by Overtorment** [comment]
i was able to recover my own funds successfully from test wallet that i specifically created for this purpose.

if youre not good with scripts i can recover for you if you share seed & passwords privately
i@bluewallet.io

otherwise i can walk you through the process so you can recover on your own PC

**Comment by bitboba** [comment]
I want to learn more about this. Can you guide me through the steps with PC. Thank you.

**Comment by Overtorment** [comment]
you would need to clone BW repository

```
git clone https://github.com/BlueWallet/BlueWallet.git
cd BlueWallet
npm install
```

so that you can run tests for bluewallet

`./node_modules/.bin/jest  tests/unit/multisig-hd-wallet.test.js`


once you  have that running you can copypaste the script that i wrote into the file `tests/unit/multisig-hd-wallet.test.js`  and put your own mnemonic seed

**Comment by bitboba** [comment]
sorry. I tried to do it myself, but couldnt figure out how to recover my fund. Would you help me retrieve my fund? Thanks

**Comment by Overtorment** [comment]
> sorry. I tried to do it myself, but couldnt figure out how to recover my fund. Would you help me retrieve my fund? Thanks

wow, its been 1.5 years, i forgot how i did it. ok. how many coins do you need to recover? if its not much email me the seed,  ill try. otherwise you need someone who knows nodejs development

**Comment by bitboba** [comment]
thankyou. it is about 0.014. Can you help me recovering it ?

**Comment by bitboba** [comment]
> the seed

yea time flies. I tried to navigate github but couldnt do it myself. recently I tried to send the fund from Bluewallet again, a different error message popped up :"witness script for input #0 doesnt match the scriptpubkey in the prevout." I has about 0.0148 in that wallet.

**Comment by bitboba** [comment]
> > sorry. I tried to do it myself, but couldnt figure out how to recover my fund. Would you help me retrieve my fund? Thanks
> 
> wow, its been 1.5 years, i forgot how i did it. ok. how many coins do you need to recover? if its not much email me the seed,  ill try. otherwise you need someone who knows nodejs development

yea time flies. I tried to navigate github but couldnt do it myself. recently I tried to send the fund from Bluewallet again, a different error message popped up :"witness script for input #0 doesnt match the scriptpubkey in the prevout." I has about 0.0148 in that wallet.
