### ISSUE TITLE
Generating different seed from ian coleman but using the same entropy

### ISSUE THREAD

**Issue by Mikael-R** [BlueWallet/BlueWallet#6404]
I've generated a seed with these dice rolls in the blue wallet and also in ian coleman however the seed generated in the blue wallet is different from the one generated in ian coleman but they should have the same as they were generated with the same entropy

Dice rolls:
111111111222222222333333333444444444555555555666666666111111111222222222333333333444444444555555555

Seed generated in blue wallet:
abandon absent fetch relief primary zoo winter avocado scale ability fetch pull primary lend yellow advance useless abandon fetch prize primary garment zone appear

Seed generated in ian coleman:
test bracket rubber during sentence picture ramp only wild valley grid busy boat term hero maximum breeze sting task relax adjust ancient hunt erupt

![image](https://github.com/BlueWallet/BlueWallet/assets/60241602/b8c6232f-cc11-4fbd-9fed-b6d784c77188)

Code to generate seed entropy
```
num = 1
entropy = ""

while (len(entropy) < 99):
  if (num == 7):
    num = 1
  entropy += str(num) * 9
  num += 1

print(entropy)
```

Why these seeds are different but both generated with same entropy?

**Comment by Overtorment** [comment]
iirc BW mixes system entropy as well so a user won't shoot himself in the foot

**Comment by Mikael-R** [comment]
> iirc BW mixes system entropy as well so a user won't shoot himself in the foot

So BW adds entropy on top of the provided entropy, thus creating an extra layer of protection?

**Comment by Mikael-R** [comment]
![tenor](https://github.com/BlueWallet/BlueWallet/assets/60241602/53226b55-43cb-46cc-8700-42e74bc8f15e)
