### ISSUE TITLE
SLIP39: Single threshold schemes not importing

### ISSUE THREAD

**Issue by sime** [BlueWallet/BlueWallet#6417]
## Are you reporting a bug?

Importing 1 of x SLIP39 shares fails. Shards generated from https://iancoleman.io/slip39/

1of1
```
object recover academic academic bedroom predator grief goat carbon dictate repair suitable pile kidney clogs shame receiver cluster sweater mild
```
1of2
```
column isolate academic easy august speak knit rhythm havoc junior civil aide shelter depict scholar item plan iris luck axis

column isolate away easy august speak knit rhythm havoc junior civil aide shelter depict scholar item plan grocery party order
```
1of3
```
viral extend academic leader center else mobile recall deliver justice revenue false exercise veteran style vegan glance timely enemy steady

viral extend away leader center else mobile recall deliver justice revenue false exercise veteran style vegan glance voice glen finance

viral extend category leader center else mobile recall deliver justice revenue false exercise veteran style vegan glance scandal artwork romp
```

Whereas 2of3, 3of3, 2of4, 3of4, 4of4 shards can successfully import.

Please provide:
### Mobile
* Asus Zenfone 8, Android 13
* BlueWallet app version 6.6.2

### Desktop 
* macOS, 13.6.5
* Version 6.6.2 (1703119050)

**Comment by onvej-sl** [comment]
My guess is that this is caused by [this](https://github.com/BlueWallet/BlueWallet/blob/a2fbbecce50541d3ba7344a2e465305ae7819b15/class/wallet-import.ts#L387C1-L387C31) line. You expect that a slip39 mnemonic consist of at least 2 shares.

**Comment by limpbrains** [comment]
Thank you @sime @onvej-sl
