### ISSUE TITLE
Display funds also in selected currency

### ISSUE THREAD

**Issue by Meisterzunge** [BlueWallet/BlueWallet#6426]
# Description

Show funds not only in `BTC` or `SATS` but additionally in the selected currency.

If i recommend bluewallet to family and friends they feel inconvenient with some value, displayed in e.g. `SAT`.

# Proposal

Where ever funds are displayed (in `BTC` or `SAT),` also display the converted amount (in e.g. `USD` or `EUR`) right below.

**Comment by Overtorment** [comment]
will clog UI, our ux  director wont approve this

**Comment by Meisterzunge** [comment]
How to clog this UI?
![grafik](https://github.com/BlueWallet/BlueWallet/assets/16259805/0f21100d-06a6-49df-aa32-a0d3ccbbe7f3)

Most apps are able to convert funds into desired currencies. I would say this is a standard feature?!
