### ISSUE TITLE
iphone widget for balance is always 0 

### ISSUE THREAD

**Issue by weil** [BlueWallet/BlueWallet#6430]
## Are you reporting a bug?
yes
Please provide:
when you add the bluewallet widget for balance, it shows a 0 balance recently.  It used to work in my iphone.
 
* your phone model and OS version  : iphone 14 pro.  ios 17.4.1
* BlueWallet app version (settings->about->scroll down)
* self-test passes? Open settings->about->scroll down, tap "Run self-test"
* unique ID for our crash reporting service (settings->about->scroll down, tap "copy")

## Proposing a feature?

Go right ahead

**Comment by weil** [comment]
Hi, this issue is still not fixed.  It is still showing 0 balance from the bluewallet widget.  I am using ios.

**Comment by marcosrdz** [comment]
> Hi @marcosrdz , this issue is still not fixed.  It is still showing 0 balance from the bluewallet widget.  I am using ios.

Do you have storage encrypted enabled? In settings - security

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/6568
