### ISSUE TITLE
Splash screen animation

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#644]
Here's a proposal for an animation on the splash screen.

<p align="center">
<img src="https://user-images.githubusercontent.com/1238429/64994554-329a8100-d8d9-11e9-9203-e382a12faea6.gif" />
</p>

json (lottie)
[bluewalletsplash.json.zip](https://github.com/BlueWallet/BlueWallet/files/3618264/bluewalletsplash.json.zip)

`<LottieView source={require('../../assets/bluewalletsplash.json')} autoPlay loop={false} />
`

**Comment by marcosrdz** [comment]
b3f39e5fa2e1eccaf9a3d0e376e4da59fc776cf5
