### ISSUE TITLE
JSON parsing error for CoinGecko

### ISSUE THREAD

**Issue by killer21m** [BlueWallet/BlueWallet#6470]
Using latest version 6.6.2 build 1713028458

When selecting USD from the currency menu in settings, it gives a JSON parsing error.

![BlueWalletError](https://github.com/BlueWallet/BlueWallet/assets/154687585/8fcfcabc-6f82-4c14-876a-bb6357c88627)

**Comment by Overtorment** [comment]
can you check following url in browser?

https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd

it spossible that your ip/provider is banned or smth
