### ISSUE TITLE
import and HD address

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#65]
Tester feedback

> Some wallets have options to import using a private key (perhaps from paper wallets, or some very old wallets).  Years ago, they might have maintained that as spendable address, however all recent wallets would import those funds into an HD address in the wallet using a transaction to move the funds.

**Comment by ncoelho** [comment]
@Overtorment Can you give me more context on what is the technical issue with this one?

**Comment by Overtorment** [comment]
In BlueWallet, when you import WIF it creates a single-address wallet.
While other wallets offer user to "sweep" the private key - meaning sending all funds from WIF to one of the addresses of HD wallet, and not giving option to reuse this WIF/its address.

I want to maintain maximum flexibility. If user wants to reuse single address - its his choice. If not - user can import single address wallet, and manually send all funds to HD wallet, then delete single address wallet.
