### ISSUE TITLE
iOS error on initial build

### ISSUE THREAD

**Issue by soonoo** [BlueWallet/BlueWallet#6509]
Following below commands on README,
```
npm install
npmr run start
npx react-native run-ios
```

I got error messages about profile. What should I do to fix this?
```
/Users/soonoo/dev/BlueWallet/ios/BlueWallet.xcodeproj: error: No profile for team 'A7W54YZ4WU' matching 'match Development io.bluewallet.bluewallet.MarketWidget' found: Xcode couldn't find any provisioning profiles matching 'A7W54YZ4WU/match Development io.bluewallet.bluewallet.MarketWidget'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the Signing & Capabilities tab of the target editor. (in target 'WidgetsExtension' from project 'BlueWallet')
```

I changed team to my own accountin `Signing` section but it has not effect.
<img width="858" alt="스크린샷 2024-05-04 오후 5 15 06" src="https://github.com/BlueWallet/BlueWallet/assets/5436405/e61f7aec-c4f0-40fa-8970-5e9604e6b89b">

**Comment by Overtorment** [comment]
@marcosrdz

**Comment by marcosrdz** [comment]
You have to apply those changes to all related targets. Such as WidgetExtension.

**Comment by soonoo** [comment]
@marcosrdz Thank you! When I changed the signing settings for all targets, another error occurred.
```
** BUILD FAILED **


The following build commands failed:
	ValidateEmbeddedBinary /Users/soonoo/Library/Developer/Xcode/DerivedData/BlueWallet-elgcrwasxvdlwvhjjojxzratdkzu/Build/Products/Debug-watchos/BlueWalletWatch.app/PlugIns/BlueWalletWatch\ Extension.appex (in target 'BlueWalletWatch' from project 'BlueWallet')
(1 failure)

```

After removing Watch app from the target list, iPhone build worked fine. Is it okay to proceed like this?"

**Comment by marcosrdz** [comment]
> @marcosrdz Thank you! When I changed the signing settings for all targets, another error occurred.
> 
> ```
> 
> ** BUILD FAILED **
> 
> 
> 
> 
> 
> The following build commands failed:
> 
> 	ValidateEmbeddedBinary /Users/soonoo/Library/Developer/Xcode/DerivedData/BlueWallet-elgcrwasxvdlwvhjjojxzratdkzu/Build/Products/Debug-watchos/BlueWalletWatch.app/PlugIns/BlueWalletWatch\ Extension.appex (in target 'BlueWalletWatch' from project 'BlueWallet')
> 
> (1 failure)
> 
> 
> 
> ```
> 
> 
> 
> After removing Watch app from the target list, iPhone build worked fine. Is it okay to proceed like this?"

Yeah that wont be an issue for doing any coding or using the app

**Comment by soonoo** [comment]
It works fine on the real device, but when I try to run it on the simulator, this error comes up. Is there anything you know to fix this?
```bash
$ npm run ios -- --simulator="iPhone 13 mini"
The following build commands failed:
	SwiftEmitModule normal arm64 Emitting\ module\ for\ rn_ldk (in target 'rn-ldk' from project 'Pods')
(1 failure)
]

```

**Comment by marcosrdz** [comment]
> It works fine on the real device, but when I try to run it on the simulator, this error comes up. Is there anything you know to fix this?
> 
> ```bash
> 
> $ npm run ios -- --simulator="iPhone 13 mini"
> 
> The following build commands failed:
> 
> 	SwiftEmitModule normal arm64 Emitting\ module\ for\ rn_ldk (in target 'rn-ldk' from project 'Pods')
> 
> (1 failure)
> 
> ]
> 
> 
> 
> ```

The README file shows the steps for addressing that issue. Look for "noLDK"

**Comment by soonoo** [comment]
I should have checked it one more time. Thank you!
