### ISSUE TITLE
Floating buttons overflow screen in wallet page.

### ISSUE THREAD

**Issue by soonoo** [BlueWallet/BlueWallet#6529]
Hi, floating buttons overflow screen slightly in wallets page. I wonder if it was intentional.

<img width="684" alt="스크린샷 2024-05-07 오후 10 51 04" src="https://github.com/BlueWallet/BlueWallet/assets/5436405/0690b02b-1de7-42db-8a2e-658948a3814f">

**Comment by marcosrdz** [comment]
What device and OS version?

**Comment by soonoo** [comment]
iPhone 15on iOS 17.4.1

Just found that this is due to device's font size settings, and is not a BlueWallet issue.

**Comment by Overtorment** [comment]
closed then

**Comment by marcosrdz** [comment]
Its definitely a bluewallet issue. The app should handle scenarios like these
