### ISSUE TITLE
PSBT-Scan successful, signed and immediately sent to network without user confirmation 

### ISSUE THREAD

**Issue by silkroadnomad** [BlueWallet/BlueWallet#6557]
I recently experimented with scanning PSBTs. I prepared a transaction on a website, which produced a QR code.

Upon scanning the QR code, the window unexpectedly closed without any feedback. I repeated the scan two or three more times, each time with the same result. Later, I discovered that my PSBT was scanned, signed, and successfully broadcasted to the network three times. While I was pleased with the successful broadcasting, I believe the process can be improved. Here are my suggestions:

1. Transaction Confirmation: Users should confirm the transaction before it is signed and broadcasted.
2. Transaction Details Screen: Users should see a screen displaying the amount of BTC being sent from their wallet and the outputs.
3. MultiSig PSBT Handling: Scanning a MultiSig PSBT should result in a signed hex with the option to scan or save the signed hex for use with another device or MultiSig wallet (I didn't tested this yet) 
4. BBQR Integration: Implementing BBQR might be necessary for this functionality (see [Issue #6311](https://github.com/BlueWallet/BlueWallet/issues/6311)).

**Comment by Overtorment** [comment]
thats weird. we support the whole flow of (co)signing ms transactions via psbts, there should be confirmations all steps of  the  way.

whats your uniqID (settings->about)? ill look it up on our crash reporting service

**Comment by silkroadnomad** [comment]
I need to double check this. Until then I close the issue in order to reduce noise.
