### ISSUE TITLE
Alert on my wallet when clicking on almost anything with iPhone 15 pro; newest version of blue wallet

### ISSUE THREAD

**Issue by orangepeel245** [BlueWallet/BlueWallet#6575]
![image](https://github.com/BlueWallet/BlueWallet/assets/170146186/20ad0784-04ab-4fbb-ba32-4978e56d1e67)

**Comment by Overtorment** [comment]
this is a very low-level error. feels like database files were ported (restored?) and the encryption key doesnt match.
probably best to delete the appand reinstall it
