### ISSUE TITLE
Problem with IPhone 15 pro OS 17.3.1, most recent version of blue wallet. Keep seeing this alert and do not know what it means or how to solve the issue.

### ISSUE THREAD

**Issue by orangepeel245** [BlueWallet/BlueWallet#6577]
![image](https://github.com/BlueWallet/BlueWallet/assets/170146186/86478fd5-607a-4bcf-a742-611edb2c26cd)

**Comment by marcosrdz** [comment]
Realm file seems to be corrupted. Fastest way to solve this is by uninstalling the app and then reinstalling. Make sure you have a backup of all ur wallets prior to doing this.

**Comment by orangepeel245** [comment]
Got it thank you!
