### ISSUE TITLE
Widget does not show total balance (IOS)

### ISSUE THREAD

**Issue by wladimirgrf** [BlueWallet/BlueWallet#6591]
After the last update to version 6.6.6. One of the widgets stopped working.

The square that displays the total balance in both the chosen currency and BTC has a zero balance, while another widget displays the data normally.

![WhatsApp Image 2024-05-21 at 09 22 05](https://github.com/BlueWallet/BlueWallet/assets/20077278/61ff4f80-0e82-4dcc-86cf-abfe57e9873d)

* your phone model and OS version: __Iphone 15, IOS 17.5__
* BlueWallet app version: __6.6.6__
* self-test passes?: __Yes__
* unique ID for our crash reporting service: __userId:DF73A4C5-7304-43ED-A48D-B848933F1B8B__

**Comment by Overtorment** [comment]
@marcosrdz

**Comment by marcosrdz** [comment]
Does the issue still occur if you go to settings - general - privacy and toggle widget balance?

**Comment by wladimirgrf** [comment]
> Does the issue still occur if you go to settings - general - privacy and toggle widget balance?

I was not aware that this configuration had been added. 
Activating it has restored the widget to its normal state. 
Thank you.
