### ISSUE TITLE
Migration to Yarn

### ISSUE THREAD

**Issue by marcosrdz** [BlueWallet/BlueWallet#6594]
npm scripts are hardcoded

**Comment by limpbrains** [comment]
Yarn? Maybe pnpm. I've heard it is the fancier one.

**Comment by marcosrdz** [comment]
> Yarn? Maybe pnpm. I've heard it is the fancier one.

RN 0.74 now favors Yarn

**Comment by Overtorment** [comment]
i tried to migrate to yarn and failed.

the issue seem to be in `legacy-peer-deps=true`  in `.npmrc`, which means if deps have incorectly specified peerDependencies - they are ignored.

yarn throws errors like
`react is listed by your project with version 18.2.0 (peb028), which doesn't satisfy what @react-native-clipboard/clipboard and other dependencies requ
est (but they have non-overlapping ranges!).`

and for some reason, when I specify 

```
  "resolutions": {
    "react": "18.2.0"
  },
```


in `package.json` it still doesnt work.



anyone wants to give it a try..?

**Comment by marcosrdz** [comment]
Did you remove package-lock.json prior to running yarn?
