### ISSUE TITLE
Improve broadcasting experience

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#66]
Tester feedback

> As a somewhat knowledgeable user, I understand the concept of creating a signed transaction and then broadcasting it to the network, however not all users will understand those details.  You can make it less confusing by including more explanation or by using simpler terms such as "Continue" and "Send" or "Confirm".

**Comment by ncoelho** [comment]
This is what we have at the moment.

Modal with signed Hex TX, user confirm or copy for later.
Confirmation screen

https://app.zeplin.io/project/5b252c1057a0c54542fe1f02/screen/5bcb5750393bb37a2c278dde
https://app.zeplin.io/project/5b252c1057a0c54542fe1f02/screen/5bcb574f33a8342f1cff6e21
https://app.zeplin.io/project/5b252c1057a0c54542fe1f02/screen/5bcb574f7543ed09a001bc71

**Comment by marcosrdz** [comment]
Fixed in https://github.com/BlueWallet/BlueWallet/pull/107
