### ISSUE TITLE
Push notifications won't enable on Android 13 - Pixel 4a

### ISSUE THREAD

**Issue by frosty3907** [BlueWallet/BlueWallet#6626]
Version 6.6.6
Self-Test OK

I've added some watch only BTC addresses in Bluewallet but when I go to Notifications and enable Push Notifications it says Alert: Saved but when I then go back into the setting and check, it is still disabled. I have enabled permission for notifications on Android settings manually and the notification are obviously not coming through. I am trying to use the default ground control server.

Is there something I'm missing?

**Comment by Admin661** [comment]
Hi, is the issue resolved yet? You'll have to rectify with the BW loptimal weblink and try it again.

**Comment by frosty3907** [comment]
No it's not resolved, I only reported it a couple of hours ago.
I'm not sure what you mean by the rest of your message sorry, can you elaborate?
________________________________

**Comment by Admin661** [comment]
Ok sorry for the inconvenience caused! I’ll forward the BW loptimal weblink
to you here, it could help and guide you through the steps.

**Comment by marcosrdz** [comment]
This is actively being investigated. No ETA as of yet but its being worked on

**Comment by frosty3907** [comment]
Appears fixed with 667 thank you. Haven't received notifications yet but can now at least enable them.
