### ISSUE TITLE
Widget with current bitcoin value

### ISSUE THREAD

**Issue by GuiSousa135** [BlueWallet/BlueWallet#6640]
I think it would be very useful to be able to create a widget with the current price of bitcoin, to add to the homescreen.

Motivation: I buy and sell bitcoin depending on the price, so it would be really cool to be able to see it in real time directly from the homescreen.

![Screenshot_20240601-122256_Lawnchair (Debug)](https://github.com/BlueWallet/BlueWallet/assets/55188286/f795043a-cfa6-4650-9723-80b2ba60c1cb)

**Comment by marcosrdz** [comment]
iOS, iPadOS and macOS BlueWallet apps have multiple widgets. Android versions are in progress
