### ISSUE TITLE
Slow/no updates to watch only addresses

### ISSUE THREAD

**Issue by frosty3907** [BlueWallet/BlueWallet#6643]
Previously had issue #6626 which is now resolved using version 6.6.7 however the addresses I'm watching (which I've tried adding more since) do not seem to update, unless I open the app, drag down on them and wait several minutes. 

Pixel 4a Android 13.
Opening the app takes a few seconds and then there's a double vibrate, sometimes the watch addresses say "pull down to update" and if I do then they are "updating" for a long time (5 minutes?) Sometimes they say something like "last transaction 4 days ago".
These are segwit btc addresses, beginning with 3, if that could be related...
Self test ok.

Thanks

**Comment by marcosrdz** [comment]
Go to Settings  > network > electrum. Verify if the issue is the server the device is connected to. It might have limits server-side

**Comment by frosty3907** [comment]
It connected about immediately. And the 3 test addresses I'm using only receive maybe 2-3 transactions a week so I don't think it could be rate limited.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by frosty3907** [comment]
Performance score is 367.. if that's relevant

**Comment by frosty3907** [comment]
It's basically unusable, still waiting on transactions that came through 3 days ago to show up.
Do you want be to private message you since addresses to test to see if that's the issue? Or is there a known good address I can test to see if that updates normally?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Overtorment** [comment]
cant help with anything this specific user.
experiece will always be shite with poor connectivitym, heavy addresses & occasional downtime of public electrum servers BW uses
