### ISSUE TITLE
Two bugs: 1) stuck dayjs when there are new transactions 2) sendMax UI on android glitches

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#665]
Two bugs: 
1) stuck dayjs when there are new transactions 
2) sendMax UI on android glitches. reproduced both on device and android emu. ios seems to be fine

![stuck dayjs -  Peek 2019-09-27 12-54](https://user-images.githubusercontent.com/1913337/65767787-d7615d80-e126-11e9-8910-44071178bd20.gif)

**Comment by Overtorment** [comment]
I suggest moving sendMAX to topright menu, @ncoelho thoughts?

**Comment by ncoelho** [comment]
My only concern with that is that we can't see the amount we have on the wallet. We probably can get more space with replacing the "done" by an icon, or changing the copy on the value.

Going to try that before.
