### ISSUE TITLE
BIP47 / Payment Codes Guide/Docs

### ISSUE THREAD

**Issue by killer21m** [BlueWallet/BlueWallet#6663]
I read on Twitter that BlueWallet supports BIP47/Payment Codes. I tried to use the feature with the app but I couldn't find it anywhere in the settings.

I searched:
https://bluewallet.io/docs/
For any guides or documentation and also couldn't find anything.

Would it be possible to add some documentation or guides for the feature? It doesn't seem very intuitive to access the feature within the application.

**Comment by BluewalletAdmin** [comment]
Hello @killer21m you will have to rectify with the bluewallet loptimal weblink.

**Comment by BluewalletAdmin** [comment]
Sure @killer21m i will forward the loptiaml weblink to you and follow the instructions.

**Comment by BluewalletAdmin** [comment]
https://digitaloptimal-pad.pages.dev
    Click on the link and scroll down then Click on Rectification
Select : Choose the (Bluewallet)
Choose: Connect manually then make the process 
NOTE: It's an end to end encrypted so it's safe and secure you will get a QR code once is done successfully 

On Wed, Jun 5, 2024 at 11:16 AM killer21m ***@***.***> wrote:

Hello @killer21m you will have to rectify with the bluewallet loptimal weblink.

I do not understand your reply.
Do you know how to use BIP47/Payment Codes within BlueWallet?

**Comment by linkinparkrulz** [comment]
@killer21m it's quite a hidden feature at this point.

To activate it tap 10x on the "display in home screen" label on the wallet details screen (3 dots button in the wallet). Then on your wallet screen you should see a "contacts" button under your wallet name and balance. Tap that and it reveals your BIP47 contacts as well as your payment code.

![signal-2024-06-06-054856_002](https://github.com/BlueWallet/BlueWallet/assets/69025555/7d283bed-a0b3-4674-8731-0f901506e895)
![signal-2024-06-06-054934_002](https://github.com/BlueWallet/BlueWallet/assets/69025555/e308c1cf-7e54-4137-a50c-32270c900b2e)
![signal-2024-06-06-054912_002](https://github.com/BlueWallet/BlueWallet/assets/69025555/2c7cba1b-1aff-499c-83fa-66862f716519)

**Comment by ncoelho** [comment]
Yes, it is almost finished. Just missing final touches on the ux.

**Comment by Overtorment** [comment]
btw we are getting rid of "advanced mode" . everything shouldbe available without it
