### ISSUE TITLE
Add support for Tor connections via Orbot

### ISSUE THREAD

**Issue by tehelsper** [BlueWallet/BlueWallet#668]
I'd like to be able to use Blue Wallet via Tor. When running Orbot in VPN mode on Android, the traffic from BlueWallet to LNDHub should be going over Tor, but that doesn't seem to be working. I'm running Tor on port 3000 on my myNode device, but I'm getting an error in Blue Wallet saying the URL isn't valid.

Do you know why this might not be working properly?

**Comment by SamuraiXa** [comment]
I'm trying to connect Blue wallet to my Umbrel node via Tor(orbot) getting "Can't connect to the provided Electrum server" 

Note that it does work with Zap wallet.

**Comment by ncoelho** [comment]
> I'm trying to connect Blue wallet to my Umbrel node via Tor(orbot) getting "Can't connect to the provided Electrum server"
> 
> Note that it does work with Zap wallet.

- Open Orbot
- Tor enabled apps
- Select BlueWallet
- Toggle on VPN Mode
- Force Quit both Orbot and BlueWallet
- Start Orbot (wait for it to connect)
- Start BlueWallet
- Now all BlueWallet traffic should be routed through Tor

**Comment by SamuraiXa** [comment]
> > I'm trying to connect Blue wallet to my Umbrel node via Tor(orbot) getting "Can't connect to the provided Electrum server"
> > Note that it does work with Zap wallet.
> 
> 1. Open Orbot
> 2. Tor enabled apps
> 3. Select BlueWallet
> 4. Toggle on VPN Mode
> 5. Force Quit both Orbot and BlueWallet
> 6. Start Orbot (wait for it to connect)
> 7. Start BlueWallet
> 8. Now all BlueWallet traffic should be routed through Tor

Thanks for the quick reply! But I get the same result.

**Comment by ncoelho** [comment]
Make sure you force quit both apps, otherwise won't work.

**Comment by SamuraiXa** [comment]
> Make sure you force quit both apps, otherwise won't work.

That's what I did. "Force Stop" in "App Info"
