### ISSUE TITLE
Keep balance and units in BTC

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#67]
We should keep all units in BTC at the moment, for the sake of simplicity for users. 

All BTC balances on wallet UI components should use `adjustsFontSizeToFit`
https://facebook.github.io/react-native/docs/text.html#adjustsfontsizetofit

**Comment by Overtorment** [comment]
was that a strict requirement..?
should we implement it for wallet cards asap? now it displays mBTC if value < 0.1

![image](https://user-images.githubusercontent.com/1913337/49704752-f847d900-fc0e-11e8-841b-f2797eb6a60b.png)

**Comment by Overtorment** [comment]
@ncoelho ^^^

**Comment by ncoelho** [comment]
Let's keep default balance on BTC
If too big, the number should shrink
We keep the tap to change inside wallet, for convenience on converting.
