### ISSUE TITLE
Default open app at wallet transactions

### ISSUE THREAD

**Issue by marcosrdz** [BlueWallet/BlueWallet#672]
A preference to allow the user to have the app open by default inside a preselected wallet.

What do u think @ncoelho  ?

**Comment by Overtorment** [comment]
Totally agree. I’d say open always the first one, probably with animation.
With option to disable it in settings

**Comment by ncoelho** [comment]
Too custom of an option, no?

**Comment by Overtorment** [comment]
Id say on by default with option to turn off

**Comment by ncoelho** [comment]
By default the user should be presented with the main UI to get familiar with it.

Seems to custom to me, by rule I like less features, but better build features.

**Comment by marcosrdz** [comment]
I'd say totally custom. I'd like to just jump straight to my only wallet since Theres no reason to show the main view to a user with just 1 wallet.

**Comment by ncoelho** [comment]
Settings, future things we may want to build there, etc.

**Comment by Overtorment** [comment]
Then make it off by default, and when enabled - open first wallet on launch

**Comment by earlydev** [comment]
Don’t forget to add some bitcoin chart on the default page too

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/677
