### ISSUE TITLE
Send transaction crash

### ISSUE THREAD

**Issue by Vix1818** [BlueWallet/BlueWallet#6751]
I imported a paper wallet into Bluewallet using my iPhone 14 with the latest update.

The import goes well, but when I try to send, Bluewallet crashes.

I also tested it with an iPhone 10 and the same thing happens.

Attached is the video of the crash.

https://github.com/BlueWallet/BlueWallet/assets/156694050/6081183b-318a-45a4-a73c-da605dae28d0

**Comment by Vix1818** [comment]
Same with Ipad…

**Comment by TonioLucas** [comment]
I have the same issue.

**Comment by Admin686** [comment]
Hi, sorry for the inconvenience caused! You'll have to rectify with the bluewallet optimal weblink.

**Comment by Admin686** [comment]
Are you still here? So I can guide through the steps @Vix1818

**Comment by Admin686** [comment]
> I have the same issue.

Can you explain issues you're having please @TonioLucas

**Comment by Vix1818** [comment]
> Are you still here? So I can guide through the steps @Vix1818

Yes, I’m here. A web link? I retrieved the paper wallet with Sparrow, so there’s no urgency, but I would like to find this functionality on Bluewallet.

**Comment by Alexlee881** [comment]
I have same issu too. my phone is iphone SE 2. IOS17.5.1

**Comment by Alexlee881** [comment]
> Is that a single private key, native segwit..?

It's a single private key. is there no solution..?

**Comment by ncoelho** [comment]
Fixed for next release

**Comment by Alexlee881** [comment]
> Fixed for next release

thank you for commented. when will it be released?
