### ISSUE TITLE
Any Plan For Desktop

### ISSUE THREAD

**Issue by earlydev** [BlueWallet/BlueWallet#676]
If there is a Desktop version of BlueWallet I will use it. Any plan on this? You already did a watch version.

**Comment by ncoelho** [comment]
Not at the moment, maybe in the future. I will close this issue for now.

**Comment by robster7674** [comment]
Any plans now? I'd love to be able to build the app on PinePhone.

**Comment by ralyodio** [comment]
any app that doesn't support mac/win/nix is just a stupid design....why do people insist on enforcing vendor lock-in??
