### ISSUE TITLE
Weird styling on inputs

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#68]
Weird styling on inputs, on iPhoneX and iOS 12

![whatsapp image 2018-09-17 at 22 48 52](https://user-images.githubusercontent.com/1238429/45650313-303af680-bace-11e8-8aeb-8dd4334116b3.jpeg)
![whatsapp image 2018-09-17 at 22 48 59](https://user-images.githubusercontent.com/1238429/45650316-316c2380-bace-11e8-86bc-b5a8011969d9.jpeg)

**Comment by marcosrdz** [comment]
Fixed ff8b13c6809f4f170b0501cdf187442301cdb25d
