### ISSUE TITLE
Add support for Lightning invoices without amount

### ISSUE THREAD

**Issue by kristapsk** [BlueWallet/BlueWallet#682]
Reently at the HCPP19 conference in Prague, there were two kind of ATMs with Lightning support (General Bytes and [bleskomat](https://github.com/samotari/bleskomat)), both of which has a workflow to first scan Lightning invoice and only then put the cash bills inside the machine. Currently it's impossible to use them with Blue Wallet, as they require you to generate a Lightning invoice without amount.

**Comment by ncoelho** [comment]
https://twitter.com/btcsocialist/status/1176206194333147136?s=21

If they want to proper build that they should use lnurl and not empty invoices.

**Comment by Overtorment** [comment]
Zero amount invoices are still unsafe, aren’t they?

**Comment by ncoelho** [comment]
https://github.com/ottosuess/ottosuess.github.io/blob/master/zero-amount-payments.md

**Comment by kristapsk** [comment]
Didn't know about this issue with zero amount invoices.

**Comment by aoufa** [comment]
I use it on tippin.me ( 0 amount invoices) all the time. Works fine for me.
