### ISSUE TITLE
Feature request: backup to SLIP-39

### ISSUE THREAD

**Issue by limpbrains** [BlueWallet/BlueWallet#6828]
With the recent update of SLIP39, it is now possible to back up an existing wallet without needing to re-create it. 
I think this is a nice and powerful way to boost your wallet's security without having to re-create it and move your funds.

**Comment by Overtorment** [comment]
is there a link to docs?

**Comment by limpbrains** [comment]
I was wrong, it is only possible to migrate from 1 share SLIP38 seed to multiple shares.
