### ISSUE TITLE
Iphone UI inconsistently uses Sats and BTC

### ISSUE THREAD

**Issue by strowger** [BlueWallet/BlueWallet#693]
Hi,

The iphone app seems to be inconsistent about whether values are displayed in BTC or sats.

In this screenshot you can see I have some transactions displayed in sats (transfer in from another btc wallet, and then from btc wallet to lightning wallet), and some in btc (transfers to and from LN wheel of fortune).

![image](https://user-images.githubusercontent.com/12798147/66901018-c99c4b00-eff5-11e9-846a-509926126381.png)

Cheers

**Comment by ncoelho** [comment]
Hi there, it can be a bug, we need to double check. For each wallet you can define the denomination, so this can also happen.

**Comment by strowger** [comment]
Oh. I guess I probably selected something stupidly during setup, and now can't change it then.

**Comment by strowger** [comment]
Thank you!
