### ISSUE TITLE
Need BROADCAST page for BIP84 wallets

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#697]
Should be in wallets settins (where export xpub resides as well). Should be separate 
page with text input and `broadcast` button. Expect HEX, broadcast hex on button click.
Broadcast example can be found in other screens (`CPFP.broadcast`)

**Comment by marcosrdz** [comment]
Would it "make more sense"  to have it as an option inside the screen screen? inside the advanced menu with "Broadcast a Transaction" (maybe Existing Transaction?) and have it read your clipboard (if nothing is in the clipboard, show an alert). After that, it takes you to the screen where you preview the tx.

**Comment by Overtorment** [comment]
not sure. anyway is quite easy to move it later

**Comment by ncoelho** [comment]
Implemented!
