### ISSUE TITLE
Android: JSON Parse error: Unexpected character: <

### ISSUE THREAD

**Issue by Jonas-Meyer97** [BlueWallet/BlueWallet#6998]
I am encountering the following error: `JSON Parse error: Unexpected character: <` under the following conditions:

1. **Wallet -> Receive:**  
   - Enter any amount  
   - Press "Create Invoice"  
   - Error occurs  

2. **Wallet -> Send:**  
   - Enter an address  
   - Enter any amount  
   - Press "Pay"  
   - Enter any comment  
   - Error occurs  

Basically, I am unable to receive or withdraw any funds. I haven't used my wallet for 3 years, and I'm unsure if this is related to the issue.

**Device Information:**

- **Device:** Samsung Galaxy S9 (SM-G960F)  
- **Android Version:** 10  
- **BlueWallet Version:** 7.0.2 (Build 1724347484 master)  
- **Self-Test:** OK  
- **User ID:** ab6dcada029390fe  

![Screnshot error](https://github.com/user-attachments/assets/26fa68fb-95d2-4a14-8b6d-79c0d066476b)

**Comment by ghdegraaff** [comment]
I have exactly the same issue on an IOS device, also did not use the wallet for 2 years

**Comment by Jonas-Meyer97** [comment]
@ghdegraaff 
I found the cause of the error, at least in my case. It turns out that LNDHub was shut down. You can recover your funds using the instructions provided here: https://bluewallet.io/docs/recover-lndhub/.

I think it would be best if the app informed the user that LNDHub was shut down and provided a link to the recovery page instead of displaying this JSON error. Therefore, I will leave this issue open. If this suggestion is not feasible, feel free to close the issue.

**Comment by Clarevero1** [comment]
> I have exactly the same issue on an IOS device, also did not use the wallet for 2 years

@ghdegraaff Has your issue already been escalated?

**Comment by Jonas-Meyer97** [comment]
The issue still exists in version 7.0.3

**Comment by Overtorment** [comment]
@Jonas-Meyer97 you need to follow instructions here: https://bluewallet.io/docs/recover-lndhub/
and then delete the wallet
