### ISSUE TITLE
Add native support for .onion endpoints (Tor addresses) for Android AND iOS

### ISSUE THREAD

**Issue by wanxewoj** [BlueWallet/BlueWallet#700]
This feature request is somewhat similar to https://github.com/BlueWallet/BlueWallet/issues/668, except that it requests `.onion` support for both - Android and iOS. Onion endpoints are needed for:
- Electrum endpoint
- LndHub endpoint

How? Orbot is not available for iOS, right!? Have a look at the Blockstream Green Wallet, which comes with native Tor support for iOS and Android now. Tor support is implemented in their cross-platform GDK (Greenwallet Development Kit): https://github.com/Blockstream/gdk

The suggestion is to look at the Blockstream approach to ship Tor natively in the app instead of using Orbot, which would be available on Android only.

Here are more details on the GDK Tor implementation:
- Tor is compiled from the sources at build time: https://github.com/Blockstream/gdk/blob/master/tools/buildtor.sh
- Wrapper for iOS (Swift): https://github.com/Blockstream/gdk/blob/master/src/swift/GreenAddress/Sources/GreenAddress/GreenAddress.swift
- Wrapper for Android (JNI/SWIG): https://github.com/Blockstream/gdk/tree/master/src/swig_java

**Comment by carlosmassa** [comment]
Is this in the roadmap for iOS? Would be nice to have the capability to connect to umbrel full node via Tor on iOS.

**Comment by garroch** [comment]
+1 for this issue. This would be really nice.

**Comment by ascisco** [comment]
+1 this is a must have for both android and iphone.
