### ISSUE TITLE
Select Wallet screen missing lightning wallets

### ISSUE THREAD

**Issue by BrunswickBTC** [BlueWallet/BlueWallet#7004]
* Pixel 6 pro, Graphene Android 14, latest (20240831)
* BW 7.0.2 build 1724347484 master
* self-test passes? No
"Error: Linking cannot open https url"
Save and import succeeds
* unique ID userId:e3cb97354ef49edb

About 9 months to a year ago, BW had a major release. This problem appeared then, and was not present in any public releases.

The bitcoin onchain wallets appear in the "select wallet" dialog, visible as a text link at the bottom of a "Receive" or "Send" screen, but the lndhub lightning wallets do not appear in the list. This means one must back-out of whatever payment screen you happen to be in, then scroll to the correct wallet, then past the invoice into that wallet's send screen. Though this is not dehabilitating in most cases, it can be a problem if BW is launched with a lightning invoice and the default wallet is not the desired wallet to send from.

**Comment by marcosrdz** [comment]
Yes. The chain types  have their own Send/Pay screen as their mechanism are vastly different. Do you have a screen recording you can provide with this issue occurring?

**Comment by BrunswickBTC** [comment]
This request is quite a privacy leak if I provided such a recording. Your response seems to indicate you didn't understand what I wrote.

**Comment by marcosrdz** [comment]
That's correct. If possible, provide blurred screenshots as for the whole flow, from tapping the link, to a cold boot of BlueWallet. it will help to debug

**Comment by marcosrdz** [comment]
Ok let's try something. Kill the app, tap the link and describe to me with as much detail as possible the flow you see In BW...from the logo to the final screen

**Comment by BrunswickBTC** [comment]
+ Tap link
- bluewallet splash screen
- "enter password" for storage
+ enter password
+ press 'ok'
- proceeds to wallet selection screen
- multiple lightning wallets and multiple view-only onchain wallets swipable
+ tap first lightning wallet
- show orange header with lightning wallet balance. Transaction history below. Send and Receive buttons overlayed over transaction history
+ Tap send
- send screen appears. 'Send' label at top left, 'X' top right, 0 sats, $0.00 in upper center, 'invoice or address' field with embedded "scan" button on lower center, "select wallet >" and name of present lightning wallet at bottom of screen.
+ Tap "select wallet >" at bottom of screen
- "Select wallet" at top of screen, remainder of screen contains selectable and scrollable "wallet cards", but only on-chain wallets are visible.

Expect: list of lightning wallets should populate this screen, not on-chain wallets.

**Comment by marcosrdz** [comment]
Thank you! Replicated. Will fix

**Comment by BrunswickBTC** [comment]
Fixed in latest release
Thank you!
