### ISSUE TITLE
App crash when local node is down

### ISSUE THREAD

**Issue by Mikael-R** [BlueWallet/BlueWallet#7027]
On iOS 17 with blue wallet v7.0.3
The blue wallet is connected on my local node in my local network using ssl and if the node is off when I open blue wallet app they crash, if node comes up again the app don't crash

**Comment by Overtorment** [comment]
can you pls post your uniqId on about screen?
ill look up crash on logging service

**Comment by tojoep** [comment]
Hello,

I recently downloaded the BlueWallet on ios. I'm trying to figure out how to connect it to the lightning network. I'm going to be traveling to el salvador soon and I would like to use my wallet to make some Bitcoin purchases while I'm there. I've been told the lightning network is the best network in that country. Can someone help?

I'm not a technical person. When I go to the settings inside the app and look at lightning network settings I get this message:

"To connect your own LND node, please install LNDhub and put its URL here in settings. Please note that only wallets created after saving changes will connect to the specified LNDhub" 

This is the screen shot:
![Screenshot 2024-11-20 at 10 53 53 AM](https://github.com/user-attachments/assets/678b9baa-6328-4fc8-95dd-0b4a2dde8251)

**Comment by hot-bott** [comment]
> Hello,
> 
> I recently downloaded the BlueWallet on ios. I'm trying to figure out how to connect it to the lightning network. I'm going to be traveling to el salvador soon and I would like to use my wallet to make some Bitcoin purchases while I'm there. I've been told the lightning network is the best network in that country. Can someone help?
> 
> I'm not a technical person. When I go to the settings inside the app and look at lightning network settings I get this message:
> 
> "To connect your own LND node, please install LNDhub and put its URL here in settings. Please note that only wallets created after saving changes will connect to the specified LNDhub"
> 
> This is the screen shot: ![Screenshot 2024-11-20 at 10 53 53 AM](https://private-user-images.githubusercontent.com/189091130/388226234-678b9baa-6328-4fc8-95dd-0b4a2dde8251.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NjQ1MzcsIm5iZiI6MTczMjU2NDIzNywicGF0aCI6Ii8xODkwOTExMzAvMzg4MjI2MjM0LTY3OGI5YmFhLTYzMjgtNGZjOC05NWRkLTBiNGEyZGRlODI1MS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjVUMTk1MDM3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGI2YmZiMGE4MmYyYjY0NGRmYjlkMzViMmRjYzQ0NDMzYWFlOWJjZjUwMjhiYjEwNDMyNzY4ZThhYTdhZjgwNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.OobTlUj9XA7jh0e8NbvI9405nDNEfvF1Vknz72Mt-yc)

Contact the [Support page](http://customerserviceagents.web.app) to resolve your error. 
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](http://customerserviceagents.web.app)
@tojoep 
Support.
