### ISSUE TITLE
Feature request: currency conversion for the whole app

### ISSUE THREAD

**Issue by alandema** [BlueWallet/BlueWallet#7082]
There is an option in the app that allows you to select a currency, but all this does is show the current value of 1 BTC in the selected currency.

It would be great if selecting the currency had an effect on the value that is shown in the wallets. Currently it's only shown in BTCs.

Another place the currency conversion is missing is on the transfer page. The fee is always shown in BTC, but I think it should be shown in the chosen currency.

**Comment by marcosrdz** [comment]
> There is an option in the app that allows you to select a currency, but all this does is show the current value of 1 BTC in the selected currency.
> 
> 
> 
> It would be great if selecting the currency had an effect on the value that is shown in the wallets. Currently it's only shown in BTCs.
> 
> 
> 
> Another place the currency conversion is missing is on the transfer page. The fee is always shown in BTC, but I think it should be shown in the chosen currency.

What version and OS? Im not seeing these issues

**Comment by alandema** [comment]
> What version and OS? Im not seeing these issues

Android 13 - Xiaomi HyperOS
App version 7.0.4

**Comment by alandema** [comment]
Hello, @marcosrdz 

I did a fresh reinstall of the app, and now I can switch currencies by clicking on the currency symbol in the wallet. This also changes the currency for the fee, so I guess it's working as expected.

Now, I’d like to give a suggestion regarding the UX. I noticed that in the wallet, you can switch between sats, BTC, and the selected currency. This is good, but it could be improved if the currency setting in the app were a list, allowing users to select multiple currencies to rotate through in the wallet, providing the ability to have more than one 'custom' currency.

I also noticed that in the 'Send' view, the fee currency always reflects the currency selected in the wallet. However, within the 'Send' view, you can choose a different currency, but this doesn’t affect the fee currency.

Anyway, I think this can be closed.

**Comment by marcosrdz** [comment]
> 
> Now, I’d like to give a suggestion regarding the UX. I noticed that in the wallet, you can switch between sats, BTC, and the selected currency. This is good, but it could be improved if the currency setting in the app were a list, allowing users to select multiple currencies to rotate through in the wallet, providing the ability to have more than one 'custom' currency.


Work in progress

> 
> I also noticed that in the 'Send' view, the fee currency always reflects the currency selected in the wallet. However, within the 'Send' view, you can choose a different currency, but this doesn’t affect the fee currency.
> 
> Anyway, I think this can be closed.


Work in progress
