### ISSUE TITLE
Cannot Import Secret/Private Key in Offline Mode

### ISSUE THREAD

**Issue by Vicentesan** [BlueWallet/BlueWallet#7099]
## Cannot Import Secret/Private Key in Offline Mode

* Samsung Galaxy A03 Core | Android 11
* 7.0.4 (build 1726095882)
* cannot run self tests in offline device with offline electrum mode on
* userId: 95c8730fcecbe9b6

Hey there, im currently trying to import a BIP 84 SK with 24 keys + passphrase, generated using IanColeman in a Offline notebook. But when I tried to import the "Account Extended Private Key" or a single SK from any Public Address in the offline Mobile device it throws the following error:

![blue-wallet-issue (2)](https://github.com/user-attachments/assets/20f8c140-486e-4e64-bdfc-b21b8b96ef81)
![blue-wallet-issue (1)](https://github.com/user-attachments/assets/822599e5-d6a9-4d0e-9021-d3678b278e58)

If you guys need any more information, just tell me! tysm

**Comment by Vicentesan** [comment]
@Overtorment @limpbrains waiting for follow-up, if you guys need any information, just tell me

**Comment by MatVzn** [comment]
i'm having the same problem

**Comment by avitorio** [comment]
Hey @Vicentesan and @MatVzn 

I was having the same problem but figured out you can:
- Click on: Use custom derivation path
- Wait until the options stop loading
- Select `HD SegWit (BIP84 Bech Native)`
- Click on "Import"

I know it's not optimal, and on my phone it takes forever, but at least it works.

**Comment by Vicentesan** [comment]
Oh, thats great! I will use it until they fix it. TYSM

**Comment by raulpacheco2k** [comment]
> * Click on: Use custom derivation path
> * Wait until the options stop loading
> * Select `HD SegWit (BIP84 Bech Native)`
> * Click on "Import"
> 
> I know it's not optimal, and on my phone it takes forever, but at least it works.

Yes, this works perfectly. This is shown in many tutorials.

**Comment by chidinmmauchenna** [comment]
Oh I will use it till the fixe it
