### ISSUE TITLE
remove [bitcoin:] and [lightning:] in front of addresses/invoices

### ISSUE THREAD

**Issue by nighttimeBIT** [BlueWallet/BlueWallet#711]
if you copy a bitcoin address or lightning invoice in Blue, you will copy it with "bitcoin:" / "Lightning:" in front of it. This can be confusing, because if you paste it elsewhere, and don't see the beginning of the address/invoice after you pasted it, then most wallets will give you an error, leaving especially beginners wondering, what they did wrong.

**Comment by marcosrdz** [comment]
It gets copied with the schema when you tap Share. If you tap the address/invoice it will get copied without the schema.

**Comment by nighttimeBIT** [comment]
@marcosrdz that doesn't really change anything about the concern, as it is way more easier/obvious to click the "share" button, than to click on the address itself.

**Comment by ncoelho** [comment]
Will take a look, it's a shame that wallets don't automatically identify the schema, this is their lack of development. Sharing with the schema is the correct way because it allows to make cross device compatible to identify the protocols and open wallets.

**Comment by ncoelho** [comment]
Closing this issue for now
