### ISSUE TITLE
Send Max Dont show IOS iphone 5se

### ISSUE THREAD

**Issue by atoma01** [BlueWallet/BlueWallet#712]
Hi
I dont see, or get the option to send max, or send all funds from a btc wallet on my iphone 5se
Had to calculate exact fee to clean out my old wallet. Rinning version 4.7.0 build 1571572327

**Comment by ncoelho** [comment]
when you tap the balance, the keyboard goes up. Then you see your total amount in the keyboard helper and tap on the total amount.

**Comment by atoma01** [comment]
Ok thanks. I did not know that. I dont have any bitcoin in my wallet to test and confirm this atm. But will give it a try next time i need the feature.

**Comment by ncoelho** [comment]
no worries, we need to make more obvious. Thanks for the feedback!
