### ISSUE TITLE
Forever lost funds with JSON Parse error?!

### ISSUE THREAD

**Issue by langsterpro** [BlueWallet/BlueWallet#7128]
Hello! 

I’d really appreciated any help…

My Lightning sats are totally inaccessible. I can’t send from within the app and I’ve tried restoring on a new phone, each time I get the same error message:

JSON Parse error: Unexpected
character: <

When I download the CSV it reads ‘expired’. 

The transaction in the wallet is over two years old (I was saving it for a rainy day!)

Have I lost my money???

Any advise or help would be greatly appreciated. 

Many thanks in advance.

**Comment by Jomossey** [comment]
@langsterpro

Since the transaction is over two years old, it’s possible that the wallet service or the specific transaction might have issues due to changes in the network or wallet software. 
Has it been solved yet ?

**Comment by langsterpro** [comment]
Thanks for the reply, Jomossey. 

No, not resolved yet. 

There’s not even an option to create a Lightning wallet within the latest version of the BlueWallet iOS app anymore (there’re just two options now, Bitcoin’ and ‘Multisig Vault’). I could swear that when I set the wallet up a couple of years ago there were 3 options - a Lightning one as well. 

I’ve even tried to scan the back-up QR code generated in the original wallet to a couple of different apps - Wallet of Satoshi and Strike, but neither worked. 

I don’t suppose you know of another Lightning app that’s compatible with Blue’s back-up codes? Sorry if that’s a stupid question… up until recently I thought a Lightning wallet could be backed up and restored just like a regular Bitcoin one.  

Thanks.

**Comment by Jomossey** [comment]
@langsterpro

It's frustrating to encounter these issues with your Lightning sats and the changes in the BlueWallet app. The missing Lightning wallet option and the difficulty transferring your backup to other apps can be really confusing.

Regarding your question, it's not silly at all! It's totally normal to expect a Lightning wallet to be backed up and restored like a regular Bitcoin wallet. Compatibility between different Lightning wallets can vary, especially with backup codes.

**Comment by Jomossey** [comment]
@langsterpro  all you just want is to be solve?

**Comment by Jomossey** [comment]
@langsterpro I'll have to refer you to the official support live chat with the ticket ID BLU07638
Please see the link below to our dedicated support line:
[Bluewallet Network DApps Support Ticket Requests.](http://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by ncoelho** [comment]
The person replying was a scammer.

Just contact support, the email is working.

**Comment by langsterpro** [comment]
Thanks very much, ncoelho. Those last couple of messages of theirs did seem dodgy! 

I’ve tried the official support email twice, bluewallet@bluewallet.io , and both times I received the following from ‘Mail Delivery System’ 

Undelivered Mail Returned to Sender

This is the mail system at host eforward.registrar-servers.com.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

The mail system

<bluewallet@msgrtr.com> (expanded from <bluewallet@bluewallet.io>): Host or
domain name not found. Name service error for name=msgrtr.com type=A: Host
not found

Do you know of any other contact emails, please? 

Thanks.

**Comment by ncoelho** [comment]
Maybe try with a different email.

Anyway, you need to follow the steps here and wait for the transaction to arrive:
https://bluewallet.io/docs/recover-lndhub/

**Comment by langsterpro** [comment]
Thank you, ncoelho. 

I must’ve overlooked that in my panic (it’s only a small amount, but it’s a lot to me at the moment). 

I’ve just completed the form. It says that they usually process batch payments at the beginning of the month, so with it being the first today, fingers crossed I can get it soon. 

Thanks again.

**Comment by Overtorment** [comment]
withdrawals are processed every few months, because there are very few applicants now. 
if you didnt get it - ping support to look up why your submission wasnt processed - its often typos

**Comment by paricheh** [comment]
same problem toooooo
