### ISSUE TITLE
wrong segwit import 

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#718]
1) Segwit address created on bluewallet
2) Exporting this wallet with the QR code method provided
3) Scanning the QR code on my other phone -> it imports the wallet, but the Legacy address

**Comment by josephbedminster** [comment]
Hello,
As mentioned when submitting this issue, the import with the QR code provided doesn't work.
So I also tried to import the private key with the text method, same result.
Best,
Joseph

**Comment by Overtorment** [comment]
Cant reproduce, not with empty segwit p2sh-wrapped, not with used one. Possibly got fixed when we were refactoring import procedure.
Closing. Create a new ticket if smth is not right. 
Thanks!
