### ISSUE TITLE
Unable to switch off push notifications on iPhone

### ISSUE THREAD

**Issue by nkud90** [BlueWallet/BlueWallet#7202]
Hi there,

When I turn off push notifications, it stays in the 'OFF' position when I go back to the settings menu, but returns to 'ON' when I go back to the main wallet screen. It also returns to 'ON' when I restart the app. 

Although the 'Save' button on the push notifications screen appears to be related to the Ground Control server, pressing this button is also tested and doesn't help. 

- iPhone 14 Pro Max (also tested on a friend's iPhone 13)
- iOS v.17.5.1 (also tested on iOS v.16.1.1)
- BlueWallet v.7.0.4
- Successfully passed self-test

**Comment by Dappsnode** [comment]
@nkud90 Since you're having trouble with the BlueWallet app, it might be best to contact support team.I'll have to refer you to the official support live chat with the ticket ID BLU07638
Please see the link below to our dedicated support line:
[Bluewallet Network DApps Support Ticket Requests.](https://thedappsupport.com/
)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by chidinmmauchenna** [comment]
Please accept

**Comment by Overtorment** [comment]
reproduced. 
@marcosrdz the issue is that when  user disables pushes in the app,  the app then  proceeds to acquire a new push token, for which of course the notifications on server are enabled.
@marcosrdz do you want to tackle it..?

**Comment by nkud90** [comment]
Let me add the reasoning behind this so that everyone can better understand the priority:

With Umbrel, it has now become relatively easy for an average user to improve their privacy when using BlueWallet by running their own Bitcoin node and Electrum server and connecting BlueWallet to it. 

As there is currently no GroundControl app in Umbrel's app store, push notifications remain a privacy breach and should be easily turned off for now. 

I've [posted a suggestion](https://community.umbrel.com/t/what-apps-would-you-like-to-be-added-to-the-umbrel-app-store/235/164?u=nkud) on the Umbrel community forum to add GroundControl to Umbrel's default app store. If you have any information about other ways to run GroundControl on Umbrel - it would be highly appreciated.

In my opinion, with the addition of GroundControl to Umbrel, this issue will become less of a priority as self-hosted GroundControl becomes a more mainstream option. But for now, the priority is relatively high.
