### ISSUE TITLE
Import Error: JSON Parse Error

### ISSUE THREAD

**Issue by quietdog4213** [BlueWallet/BlueWallet#7203]
* iPhone 16 Pro Max - IOS 18.0.1
* BlueWallet app version 7.0.4
* self-test passes? yes

When importing a lightning wallet from one iPhone to another by scanning the QR code, I am greeted with this JSON parsing error. 

![IMG_9483](https://github.com/user-attachments/assets/9efaaf12-d697-4893-8d44-bc8da49ad567)

**Comment by marcosrdz** [comment]
Are you connected to a VPN?

**Comment by quietdog4213** [comment]
No, no VPN

**Comment by marcosrdz** [comment]
If you have notifications enabled for BlueWallet, disable them in the app and in system settings. Then try again to see if you get the error

**Comment by Overtorment** [comment]
https://bluewallet.io/docs/recover-lndhub/

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/7215
