### ISSUE TITLE
Issue creating a LN invoice for 0 sats

### ISSUE THREAD

**Issue by slioch5** [BlueWallet/BlueWallet#727]
Currently you can enter 0 sats when creating a LN invoice and the disabled create button becomes clickable which when clicked gives the error 'API error: Bad arguments (code 8). A small UX/UI improvement would be to keep the create button disabled if 0 sats is entered.

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/729
