### ISSUE TITLE
UX/UI Improvement - Change create button on Receive LN payment should be create invoice

### ISSUE THREAD

**Issue by slioch5** [BlueWallet/BlueWallet#728]
A small UX/UI improvement would be to have the 'Create' button on the invoice creation page in your LN wallets say 'Create Invoice' to communicate more clearly what it is the user is creating. 

This might seem self explanatory to most but for complete noobs the idea of an Invoice is more understandable.

**Comment by marcosrdz** [comment]
@ncoelho  thoughts?

**Comment by ncoelho** [comment]
Yep, good one!

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/730
