### ISSUE TITLE
Unable to sign PSBT with Coldcard

### ISSUE THREAD

**Issue by clonmac** [BlueWallet/BlueWallet#733]
I'm trying to test out PSBT transactions with Bluewallet and Coldcard and am having several issues. The primary issue is that after importing my zpub into Bluewallet, it derives all the addresses properly, but after creating a PSBT and transferring it to my Coldcard for signing, I receive a failure on the Coldcard due to the master key fingerprint being incorrect. Bluewallet automatically sets the master key fingerprint as 00000000, but that is not what the Coldcard is using for its wallet.

The second issue is that Bluewallet creates PSBTs as a string that gets copied whereas the Coldcard requires the PSBT to be a raw data file. I can work around that by transferring the string to FullyNoded app and converting it to raw data there.

But the master key fingerprint is a full stop to using Bluewallet with Coldcard for PSBTs. Maybe I'm doing something wrong on BW import, if so please advise. Thanks.

**Comment by ncoelho** [comment]
The hw integration with PSBT is supporting cryptoadvance wallet only at the moment (which is not in the market yet).

We haven’t start testing it with coldcard yet.

**Comment by clonmac** [comment]
Ahh, ok. Good to know.  👍🏻

**Comment by Overtorment** [comment]
Reopening it as Im gona work on it soon. Finally got my hands on Coldcard device.

**Comment by reardencode** [comment]
I believe coldcard updated their firmware to be more flexible about PSBT encoding (accepting hex, base64 and raw now).

**Comment by Overtorment** [comment]
Hey, Coldcard integration is almost done, @marcosrdz is finalizing it at the moment.
You can already try debug build apk (posted here: https://github.com/BlueWallet/BlueWallet/pull/793)
I'm closing this issue for now.
