### ISSUE TITLE
Illegible font color of text input fields

### ISSUE THREAD

**Issue by abhiShandy** [BlueWallet/BlueWallet#735]
On my iPhone SE, text fields of Lightning settings, Electrum server and address fields for sending/receiving have font color set to white which is difficult to read.

**Comment by ncoelho** [comment]
Yes, this is a known issue due to dark mode being active.

**Comment by abhiShandy** [comment]
Should I close it then?

**Comment by marcosrdz** [comment]
Yes. We currently have an open ticket for dark mode implementation. It’s going to be worked on.
