### ISSUE TITLE
7.0.5: adresses not shown

### ISSUE THREAD

**Issue by Rob0xFF** [BlueWallet/BlueWallet#7359]
## Are you reporting a bug?

Please provide:

* your phone model and OS version -> latest iOS on iPhone/iPad
* BlueWallet app version (settings->about->scroll down) -> 7.0.5
* self-test passes? Open settings->about->scroll down, tap "Run self-test" -> seems not to work
* unique ID for our crash reporting service (settings->about->scroll down, tap "copy")

I am on latest iOS version, and on update of the app, show adresses stopped showing adresses, both receive adresses and exchange adresses are empty. I am on a watch only wallet. Transactions and balance show up right.

**Comment by Zoekerin** [comment]
Hello @Rob0xFF 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID BLU07638
Please see the link below to our dedicated support line:
[Bluewallet Network DApps Support Ticket Requests.](https://thedappsupport.com/)
 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
