### ISSUE TITLE
Addresses not showing on the newest version

### ISSUE THREAD

**Issue by Luan-da-Silva** [BlueWallet/BlueWallet#7363]
## Are you reporting a bug?

Please provide:

Samsung A20 - android 14
* Version 7.0.5. build 1732553664 master 
* self-test passes? Yes. However for my zpub and others  Wallet>'Show addresses'  not shows any address at all, being the 
only exception the address created in Blue Wallet itself. 
* unique ID: userId:79632a1b8edc3462

**Comment by ismaeldf** [comment]
The same problem on iphone ios 18

**Comment by Bts63** [comment]
I noticed that this week the wallet started showing an error when displaying addresses in whatch-only wallet mode. When the wallet is activated, the screen opens blank. It does not show Receive and Change addresses.
