### ISSUE TITLE
Can't enter settings on mac version

### ISSUE THREAD

**Issue by LOCHER-21** [BlueWallet/BlueWallet#7368]
BlueWallet ver 7.0.5 (1703136699)
macOS 15.1.1 (24B91) on Mac Pro and MacBook Pro

Setting page can't be open anymore on both of my machines. menu bar -> BlueWallet -> Settings = nothing happens. Reproduced on two different macs. Same issue.

**Comment by jurgen2005** [comment]
Same here

**Comment by maltokyo** [comment]
this is fixed in latest release (according to release notes) but there is no DMG in the assets section, could someone please let me know how to reflect this fix?

**Comment by jurgen2005** [comment]
its available in the app store

**Comment by marcosrdz** [comment]
> this is fixed in latest release (according to release notes) but there is no DMG in the assets section, could someone please let me know how to reflect this fix?

Its on the Mac App Store. The DMG will be published in 2hrs

**Comment by marcosrdz** [comment]
Sometimes the reviewers catch a bug we didnt see.
