### ISSUE TITLE
Widgets do not work any longer on iOS and macOS

### ISSUE THREAD

**Issue by LOCHER-21** [BlueWallet/BlueWallet#7380]
iOS 18.1.1 (22B91) iPhone 15 Pro
BlueWallet ver 7.0.5 (1732553778)

macOS 15.1.1 (24B91) on Mac Pro and MacBook Pro
BlueWallet ver 7.0.5 (1703136699)

Widgets do not work any longer on iOS and macOS till update to BlueWallet 7.0.5.
![bw_widget](https://github.com/user-attachments/assets/d7731b8e-54a2-495d-a4c1-c959dba4299e)

**Comment by Dan-Foord** [comment]
I am having the same experience on app version7.0.6 1732999017, iOS version 18.1.1

**Comment by marcosrdz** [comment]
> iOS 18.1.1 (22B91) iPhone 15 Pro
> 
> BlueWallet ver 7.0.5 (1732553778)
> 
> 
> 
> macOS 15.1.1 (24B91) on Mac Pro and MacBook Pro
> 
> BlueWallet ver 7.0.5 (1703136699)
> 
> 
> 
> Widgets do not work any longer on iOS and macOS till update to BlueWallet 7.0.5.
> 
> ![bw_widget](https://github.com/user-attachments/assets/d7731b8e-54a2-495d-a4c1-c959dba4299e)

Update to 7.0.6 to see if you face the same issue.


Also, please provide the fiat currency so we can narrow down the issue

**Comment by LOCHER-21** [comment]
BlueWallet ver 7.0.6 (build 1732999017 master)
BlueWallet ver 7.0.6 (build 1703136799 master)

Same issue

**Comment by LOCHER-21** [comment]
Tried to restart and reinstall BlueWallet. No success. All other widgets running fine. Same behavior on several devices.
