### ISSUE TITLE
Enable notifications won't stay on

### ISSUE THREAD

**Issue by redstone99** [BlueWallet/BlueWallet#7390]
Hi, on my Pixel 6 running Android 15, I just downloaded BlueWallet (v7.0.6), and
if I got to Settings -> Network -> Notifications and then click on the "Notifications" slider, it turns on. However, if I leave that view by pressing the back button or pressing the "System Settings" button, and then return to the Notifications screen, the slider for Notifications immediately turns off.    I've given the app permissions to notify, and the self-test passes.

**Comment by marcosrdz** [comment]
Android 15 was just released a few days ago. The package used for push notifications most likely needs to be updated to support 15. Will check regardless
