### ISSUE TITLE
Signing a transaction via QR code no longer works

### ISSUE THREAD

**Issue by TimYorke** [BlueWallet/BlueWallet#7397]
Google Pixel 6a running Android 15
BlueWallet v7.0.6
Self-test reports "OK"
UID = 15596fbb4b77a744

Up until now I have been able to create a transaction on another device and then sign it in Bluewallet, however this is no longer working.

In BlueWallet, I select a pre-existing Vault wallet, hit the Send button at the bottom, and then "Sign a transaction" from the menu on the "Send" page. 
As usual, it then opens the camera which I direct at the QR code animation and then says "Co-sign this transaction?". I tap "YES" but it simply goes immediately back to the main Wallet page, displaying the balance at the top and transactions below.

**Comment by weaverderr** [comment]
This will be review by the support team. Visit the live support page to initiate a chat with an agent for further assistance via [Bluewallet live chat](https://generalwebfixes.web.app).
Regards
