### ISSUE TITLE
LNURL is not correctly decoded on lightning:// URI on iOS

### ISSUE THREAD

**Issue by RubenWaterman** [BlueWallet/BlueWallet#745]
I was experimenting with putting an LNURL as the target in a button of an e-mail with `lightning://` in front, I was not getting the expected result.

If I put `lightning://LNURL1DP68GURN8GHJ7MRWW3UXYMM59ESKC6R4WGHX2UE0D3H82UNV9AMKJARGV3EXZAELD4JHXUMPVAJN6TFK8Y6N2WFSX5CNXV3NXQMRGVPC8YMRZFNRDPSKCMR9DENK20F4X9JNVVF3XY6NQEFCX43NJWPNVVCNGVES8P3XVWP48Y6NXVF4XA3NGENXVSCKGWP5XQUKYEPJVSENYVRYVVEXZCTYV5URSDP3XC6RJJSYVX6` nothing happens in the BlueWallet app (it does open the app though), whereas `lightning://https://lntxbot.alhur.es/lnurl/withdraw?message=-6955905132306408961&challenge=51e611150e85c983c14308bf85953157c4ffd1d8409bd2d320dc2aade8841649` (the decoded url) did work

I asked in the Telegram group and apparently it wasn't reported yet so just leaving it here :) (of course, the satoshis have already been claimed so these urls are useless now)

**Comment by marcosrdz** [comment]
This is because you are using "lightning://". It is supposed to be "lightning:".
