### ISSUE TITLE
[Docs] Can't run the app from source

### ISSUE THREAD

**Issue by bolatovumar** [BlueWallet/BlueWallet#759]
I followed the steps in README to build and run the app from source. I ran:

```
git clone https://github.com/BlueWallet/BlueWallet.git
cd BlueWallet
npm install
``` 

I then ran:

```
npm start android
```

At this point I see this in my console:

![Screen Shot 2019-12-13 at 9 04 20 PM](https://user-images.githubusercontent.com/1934678/70843772-cbfc0500-1dec-11ea-8cac-04b383b42aea.png)

At this point I'm not sure what to do. How do I actually get to see the app running? Do I need to install additional software? Or is there something else I'm missing? It would be nice to have the README file updated with additional steps if there are more steps.

**Comment by marcosrdz** [comment]
First, open an Android Emulator/Connect an Android device and then run:

react-native run-android

You should see the app compile, and then install on the device.

**Comment by bolatovumar** [comment]
@marcosrdz ok, so I need to download Android Studio and launch an emulator from there? I downloaded Android Studio and opened the `build.gradle` file (is this correct?), I'm assuming I need to add a configuration for the emulator now? I click on "Add Configuration..." and see this screen:

![Screen Shot 2019-12-14 at 7 09 57 PM](https://user-images.githubusercontent.com/1934678/70857558-9109d800-1ea5-11ea-8ef5-746a1acd5fc5.png)

There are a lot of options here and I'm not sure how to proceed from here. Ideally all of this would be documented and I hope the outcome of this issue will be updated documentation.

I'm assuming there are similar steps for the iOS version of the app but with XCode instead of Android Studio?

**Comment by bolatovumar** [comment]
@marcosrdz am I asking a stupid question here? Let me know if what I'm asking above doesn't make sense.

**Comment by Giszmo** [comment]
You can start the AVM from AS but you don't need to install AS to do so. You just go to Tools -> AVD manager -> Create Virtual Device. That device you can then start with the play button. From there you continue with the commandline: npm start android.

The easier way usually would be to plug in an actual android device instead of emulating one.

**Comment by bolatovumar** [comment]
@Giszmo unfortunately my phone has a USB-C port and none of my computers have a USB-C port so can't connect my phone. While I'm waiting for a USB-C to USB dongle I'm trying to use an emulator.

I was able to get an emulated device running using AVD manager as you described. I'm then running `npm start android` but nothing happens on the emulated device. All I see is `Loading dependency graph, done.` in the console:

![Screen Shot 2019-12-28 at 8 29 22 PM](https://user-images.githubusercontent.com/1934678/71552388-34341480-29b1-11ea-8e36-95b4e314cd90.png)

Any ideas what's wrong here?

**Comment by marcosrdz** [comment]
react-native run-android

It should compile the app, install on the booted Emulator, and then launch it.

You can also install the app through WiFi.

https://codetheory.in/android-debug-bridge-adb-wireless-debugging-over-wi-fi/

**Comment by bolatovumar** [comment]
@marcosrdz running `npx react-native run-android` worked for me, thanks.

I will make a PR to update the build instructions for Android to be clear about this as the build steps don't mention this command at all and just say to run `npm start android`.
