### ISSUE TITLE
bip49 transaction history

### ISSUE THREAD

**Issue by vix184** [BlueWallet/BlueWallet#765]
the transaction history on the bip49 wallets is not updated.  I have received invisible transactions in the history, but the total balance is updating correctly.

**Comment by Overtorment** [comment]
Might be tricky transactions that BW could not parse.
Can you share your xpub privately to i@bluewallet.io ?

**Comment by Overtorment** [comment]
Ok, sometimes batch transactions from exchanges can be too big, so batch request to electrum fails because response exceeds 1Mb. I committed some fixes to master to try to mitigate this, but its not 100% solved yet. I will be thinking on long term solution. Closing ticket for now.
