### ISSUE TITLE
Bug: save empty name of a wallet card and get weitd behavior

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#769]
STR:

* Create (ln?) wallet
* open settings
* delete wallets name
* save

![image](https://user-images.githubusercontent.com/1913337/71311788-ecdede80-241a-11ea-9aa6-b0eda91b4307.png)

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/new/issue769
