### ISSUE TITLE
iOS UI Element

### ISSUE THREAD

**Issue by nickycutesc** [BlueWallet/BlueWallet#773]
![IMG_2977](https://user-images.githubusercontent.com/24903257/71332836-c5b10b80-2505-11ea-96a9-d87b5b3178f5.jpeg)

I'm getting this cut-off UI overlap issue on iOS 13.3 for iPhone X when I'm creating a new Bitcoin wallet.

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/774
