### ISSUE TITLE
Biometrics unlock

### ISSUE THREAD

**Issue by marcosrdz** [BlueWallet/BlueWallet#79]
Enable the use of Touch ID and Face ID to unlock wallets.

**Comment by Overtorment** [comment]
TLDR: bad idea, not secure. Worth exploring tho

**Comment by ncoelho** [comment]
Everything? I understand the face ID has flaws, but touch ID compared with a password...?

**Comment by Overtorment** [comment]
It’s too easy to force an induvidual to touch his fingerprint (immigration
officers at us border are legally alllowed to do that for example). Also,
this does not allow plausible deniability. Also, this does not imply
encryption of data, only some thin layer which says whether someone allowed
to access something, which can be easily bypassed.

**Comment by pajasevi** [comment]
Definitely not a good idea now when master fingerprints can be created: https://boingboing.net/2018/11/15/masterprints.html

**Comment by cauerego** [comment]
i've stumbled upon blue wallet 7 days ago. needing something my mom can use.

this, right here, is way far from such a thing.

there are many definitions for what security can even mean, beyond technical ones.

fingerprint biometric is as stupid as it gets, technically. but in practice, it works. while passwords don't. there's a reason why no Bank can legally lock us out of our accounts for forgetting passwords, and it's also why passwords are a bigger failure.

passwords lock ourselves out of our accounts.

think about it.

i won't come back here or use blue wallet again. no need to bother.

my mom will never be able to use this.

this is just my first impressions hello and feedback goodbye.

cheers.

**Comment by ncoelho** [comment]
Hi there @cauerego , 

If you can provide proper feedback on where the problems exist, we can try to improve. Is it the passwords? Didn't quite get where you angry towards our open-source free to use project is. If you want to use it, cool. If you don't, cool as well. No need to be rude here.

I don't think we advertise anywhere that this is a wallet your mother can use... 

> i've stumbled upon blue wallet 7 days ago. needing something my mom can use.
> 
> this, right here, is way far from such a thing.
> 
> there are many definitions for what security can even mean, beyond technical ones.
> 
> fingerprint biometric is as stupid as it gets, technically. but in practice, it works. while passwords don't. there's a reason why no Bank can legally lock us out of our accounts for forgetting passwords, and it's also why passwords are a bigger failure.
> 
> passwords lock ourselves out of our accounts.
> 
> think about it.
> 
> i won't come back here or use blue wallet again. no need to bother.
> 
> my mom will never be able to use this.
> 
> this is just my first impressions hello and feedback goodbye.
> 
> cheers.

**Comment by benfavre** [comment]
Sorry for your mom. Actually no, not sorry. No one cares.

Now, regarding the issue topic, "Biometrics unlock", maybe it should be used for an extra "lock" that would then allow the app to open.

**Comment by hishak** [comment]
BlueWallet recommends small amounts in wallets. So US immigration officer forces me to unlock my phone. Sees $5 in wallet. Not a big deal to me. Worth it for convenience and extra security of faceId on iOS.
