### ISSUE TITLE
Question: is there an expected Node/npm version for development?

### ISSUE THREAD

**Issue by bolatovumar** [BlueWallet/BlueWallet#792]
I ran `npm i` and my `package-lock.json` was modified significantly from what's in the repo. This generally happens if you run `npm i` using a different version of npm from what was used when `package-lock.json` was last updated. I'm using Node v12.7.0 and npm v6.13.1.

 I looked into `package.json` file hoping to find the [engines](https://docs.npmjs.com/files/package.json#engines) field which would tell me what version of Node and npm is expected but didn't find it.

Suggestion: specify expected version of Node and npm in `engines` field of `package.json`.

**Comment by marcosrdz** [comment]
I am using 6.9.0

**Comment by bolatovumar** [comment]
Update: just did it again to verify that it replicates and got the same result.

@marcosrdz npm v6.9.0? And what node version are you using?

**Comment by marcosrdz** [comment]
v10.16.0

**Comment by bolatovumar** [comment]
@marcosrdz thanks.

@Overtorment what versions of npm and Node are you using when developing? If it's the same as what @marcosrdz, would it make sense to include this info in the `engines` field as I described above.

**Comment by marcosrdz** [comment]
Not sure how it would affect the build service since I have never version locked those. 

The devDependencies are the only packages that probably differ in versions since those arent version locked. The package dependencies are locked.

**Comment by bolatovumar** [comment]
@marcosrdz it just feels strange to me that when I run `npm i` my `package-lock.json` ends being different than what's in the repo already. This shouldn't happen IMO hence why I'm trying to get to the bottom of it.

**Comment by marcosrdz** [comment]
@marcosrdz it will be different since the devDependencies aren't version locked at the moment. This will result in you probably having a newer eslint, or a newer jest. Which will result in a different package-lock.json.
