### ISSUE TITLE
README.md building on console error

### ISSUE THREAD

**Issue by nickycutesc** [BlueWallet/BlueWallet#802]
I'm following the directions to build BlueWallet on the console:

git clone https://github.com/BlueWallet/BlueWallet.git
cd BlueWallet
npm install

However, I'm running into the following error:

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.2.9/fse-v1.2.9-node-v79-darwin-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for fsevents@1.2.9 and node@13.5.0 (node-v79 ABI, unknown) (falling back to source compile with node-gyp) 
Traceback (most recent call last):
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 50, in <module>
    sys.exit(gyp.script_main())
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 554, in script_main
    return main(sys.argv[1:])
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 547, in main
    return gyp_main(args)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 532, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 2215, in GenerateOutput
    part_of_all=qualified_target in needed_targets)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 802, in Write
    self.WriteCopies(spec['copies'], extra_outputs, part_of_all)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1145, in WriteCopies
    env = self.GetSortedXcodeEnv()
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/generator/make.py", line 1885, in GetSortedXcodeEnv
    additional_settings)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1616, in GetSortedXcodeEnv
    additional_settings)
  File "/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/xcode_emulation.py", line 1527, in _GetXcodeEnv
    if XcodeVersion() >= '0500' and not env.get('SDKROOT'):
TypeError: '>=' not supported between instances of 'tuple' and 'str'
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:305:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.2.0
gyp ERR! command "/usr/local/Cellar/node/13.5.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/Users/nicholaschen/Documents/Github/BlueWallet/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node" "--module_name=fse" "--module_path=/Users/nicholaschen/Documents/Github/BlueWallet/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64" "--napi_version=5" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v79"
gyp ERR! cwd /Users/nicholaschen/Documents/Github/BlueWallet/node_modules/fsevents
gyp ERR! node -v v13.5.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/13.5.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/nicholaschen/Documents/Github/BlueWallet/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node --module_name=fse --module_path=/Users/nicholaschen/Documents/Github/BlueWallet/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/nicholaschen/Documents/Github/BlueWallet/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:305:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1028:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Darwin 19.2.0
node-pre-gyp ERR! command "/usr/local/Cellar/node/13.5.0/bin/node" "/Users/nicholaschen/Documents/Github/BlueWallet/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/nicholaschen/Documents/Github/BlueWallet/node_modules/fsevents
node-pre-gyp ERR! node -v v13.5.0
node-pre-gyp ERR! node-pre-gyp -v v0.12.0
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/Cellar/node/13.5.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/Users/nicholaschen/Documents/Github/BlueWallet/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64/fse.node --module_name=fse --module_path=/Users/nicholaschen/Documents/Github/BlueWallet/node_modules/fsevents/lib/binding/Release/node-v79-darwin-x64 --napi_version=5 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v79' (1)

> BlueWallet@4.8.1 postinstall /Users/nicholaschen/Documents/Github/BlueWallet
> rn-nodeify --install buffer,events,process,stream,util,inherits,fs,path --hack; npm run releasenotes2json; npm run podinstall; npx jetify

not overwriting "buffer"
not overwriting "events"
not overwriting "process"
not overwriting "stream-browserify"
not overwriting "util"
not overwriting "react-native-level-fs"
not overwriting "path-browserify"
not overwriting "readable-stream"
not reinstalling inherits
not overwriting shim.js. For the latest version, see rn-nodeify/shim.js

> BlueWallet@4.8.1 releasenotes2json /Users/nicholaschen/Documents/Github/BlueWallet
> ./release-notes.sh > release-notes.txt; node -e 'console.log(JSON.stringify(require("fs").readFileSync("release-notes.txt", "utf8")));' > release-notes.json

> BlueWallet@4.8.1 podinstall /Users/nicholaschen/Documents/Github/BlueWallet
> ./podinstall.sh

AppCenter XCode Project: 

Jetifier found 1507 file(s) to forward-jetify. Using 4 workers...

> BlueWallet@4.8.1 prepare /Users/nicholaschen/Documents/Github/BlueWallet
> ./patches/fix_mangle.sh; git apply patches/minifier.js.patch; git apply patches/minify.js.patch

fix_mangle.sh done
npm WARN eslint-plugin-react@7.12.4 requires a peer of eslint@^3.0.0 || ^4.0.0 || ^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/eslint-plugin@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @typescript-eslint/parser@1.13.0 requires a peer of eslint@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-react-native@3.6.0 requires a peer of eslint@^3.17.0 || ^4 || ^5 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-elements@0.19.0 requires a peer of react-native-vector-icons@^4.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-level-fs@3.0.1 requires a peer of asyncstorage-down@>=3.0.0 <5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-obscure@1.2.1 requires a peer of react-native@^0.41.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-qrcode-svg@5.1.2 requires a peer of react-native-svg@^6.5.2 but none is installed. You must install peer dependencies yourself.
npm WARN react-native-webview@6.9.0 requires a peer of react-native@>=0.57 <0.60 but none is installed. You must install peer dependencies yourself.
npm WARN react-shallow-testutils@2.0.0 requires a peer of react@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-shallow-testutils@2.0.0 requires a peer of react-addons-test-utils@^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-test-render@1.1.2 requires a peer of react@15.x.x but none is installed. You must install peer dependencies yourself.
npm WARN react-test-render@1.1.2 requires a peer of react-addons-test-utils@15.x.x but none is installed. You must install peer dependencies yourself.
npm WARN BlueWallet@4.8.1 No repository field.
npm WARN BlueWallet@4.8.1 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 install: `node install`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

audited 956497 packages in 199.825s

15 packages are looking for funding
  run `npm fund` for details

found 7 vulnerabilities (5 low, 2 moderate)
  run `npm audit fix` to fix them, or `npm audit` for details

I found a similar issue: https://github.com/BlueWallet/BlueWallet/issues/759

Am I missing any dependencies or configurations?

**Comment by marcosrdz** [comment]
I see 404 in that log. Probably a connection issue?

**Comment by nickycutesc** [comment]
I'm clicking that link and it's displaying this message:

This XML file does not appear to have any style information associated with it. The document tree is shown below.

Is this link outdated or misdirected?

**Comment by marcosrdz** [comment]
Have you installed xcode? I see some xcode errors there

**Comment by nickycutesc** [comment]
Yes, I have Xcode installed and the command line tools installed as well.

**Comment by bolatovumar** [comment]
@nickycutesc i just ran `npm install` with my npm cache cleared to verify this issue. I don't get the same 404 you are getting which I'm guessing is the problem here. It could be a temporary issue. Could you try running `npm install` again? If that doesn't work then check you `node` and `npm` versions to make sure `node` version is `>=10.16.0` and `npm` version `>=6.9.0`. I'm using `node v12.7.0` and `npm v6.13.1`.

**Comment by nickycutesc** [comment]
@bolatovumar thanks for the advice. I ran 'nom install' and I'm still getting that error. 

npm = 6.13.4
node = 13.5.0

**Comment by bolatovumar** [comment]
@nickycutesc odd versions of node are not stable. I would recommend installing node v12.x.x or v10.x.x and trying again.

**Comment by nickycutesc** [comment]
No more errors, thanks so much @bolatovumar ! Below is what I'm supposed to be seeing, right:

Changed the version of node locally and looks like we're good to go!


> fsevents@1.2.9 install /Users/nicholaschen/Documents/Github/BlueWallet/node_modules/fsevents
> node install

node-pre-gyp WARN Using request for node-pre-gyp https download 
[fsevents] Success: "/Users/nicholaschen/Documents/Github/BlueWallet/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node" is installed via remote

> BlueWallet@4.8.1 postinstall /Users/nicholaschen/Documents/Github/BlueWallet
> rn-nodeify --install buffer,events,process,stream,util,inherits,fs,path --hack; npm run releasenotes2json; npm run podinstall; npx jetify

not overwriting "buffer"
not overwriting "events"
not overwriting "process"
not overwriting "stream-browserify"
not overwriting "util"
not overwriting "react-native-level-fs"
not overwriting "path-browserify"
not overwriting "readable-stream"
not reinstalling inherits
not overwriting shim.js. For the latest version, see rn-nodeify/shim.js
removing browser exclude node_modules/fsevents/node_modules/readable-stream/package.json util
normalized "main" browser mapping in readable-stream, fixed here: https://github.com/facebook/metro-bundler/pull/3
hacking /Users/nicholaschen/Documents/Github/BlueWallet/node_modules/fsevents/node_modules/iconv-lite/package.json
hacking /Users/nicholaschen/Documents/Github/BlueWallet/node_modules/fsevents/node_modules/readable-stream/readable.js

> BlueWallet@4.8.1 releasenotes2json /Users/nicholaschen/Documents/Github/BlueWallet
> ./release-notes.sh > release-notes.txt; node -e 'console.log(JSON.stringify(require("fs").readFileSync("release-notes.txt", "utf8")));' > release-notes.json


> BlueWallet@4.8.1 podinstall /Users/nicholaschen/Documents/Github/BlueWallet
> ./podinstall.sh

AppCenter XCode Project: 


Jetifier found 1507 file(s) to forward-jetify. Using 4 workers...

> BlueWallet@4.8.1 prepare /Users/nicholaschen/Documents/Github/BlueWallet
> ./patches/fix_mangle.sh; git apply patches/minifier.js.patch; git apply patches/minify.js.patch




If this is correct, I can help to update the documentation.

**Comment by bolatovumar** [comment]
@nickycutesc looks better now that you don't have a 404 anymore. I would recommend deleting the local repo and cloning it again and running `npm install` fresh again. I sometimes find that if you have already run `npm install` and it failed previously it can fail again if you try to run it afterwards.

**Comment by nickycutesc** [comment]
Ok, after running the npm install in a fresh local repo, I'm noticing a small error:

[server error] Cannot load the stats for react-native-elements – please try again later

**Comment by bolatovumar** [comment]
@nickycutesc that stats error doesn't seem to be significant. I would say you can proceed with other steps now.

**Comment by nickycutesc** [comment]
Ok, sounds good. Thanks so much for helping me out debugging through this! Should I file a PR to update the install build installations and ensure that users only use the even-numbered npm and node versions for macOS?

**Comment by bolatovumar** [comment]
@nickycutesc There is an `engines` field in `package.json` file which specifies which versions of node and npm are needed.

Also, I'm not 100% sure about odd-vs-even versions of node. It is true that the odd versions of node aren't considered stable and only even versions are considered LTS but I can't say for sure that it wasn't something else that was the issue in your case.

**Comment by limpbrains** [comment]
Looks like switching to stable nodejs resolved the issue, I'm closing the ticket
