### ISSUE TITLE
Test build 4.9.2 (989)

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#812]
- [ ]  Glitch (pressed) on wallets card when coming back from wallet
- [x]  Crash on scan in wallets import when closing the view
- [x]  Expire (lightning) hardcoded on lightning, not 1 hour anymore
- [x]  Random "esocket error" appearing
- [x]  There's two refresh icons on the main view, when you pull-to-refresh

**Comment by usef8000** [comment]
This test version Not solve my problem!
https://github.com/BlueWallet/BlueWallet/issues/811

**Comment by marcosrdz** [comment]
Expire (lightning) hardcoded on lightning, not 1 hour anymore

Still occurs? Not seeing it.

**Comment by Overtorment** [comment]
fixed expiry on lndhub side: https://github.com/BlueWallet/LndHub/compare/b56064a7...0f6a4d8c

**Comment by ncoelho** [comment]
From this list it is just the wallet glitch missing? @marcosrdz

**Comment by ncoelho** [comment]
@marcosrdz bump (the glitch thingy is so annoying)

**Comment by Overtorment** [comment]
summon the almighty @marcosrdz
