### ISSUE TITLE
QR reader not parsing the address

### ISSUE THREAD

**Issue by grmkris** [BlueWallet/BlueWallet#822]
When scanning qr code to fund spark-wallet (https://github.com/shesek/spark-wallet) (bech32 wallet)
The scanner reads empty string. When scanning regular address everything was working properly.

I am thinking the problem is with spark-wallet generating qr codes for bech32 addresses. But sadly I do not have another wallet installed to test it out.

**Comment by Overtorment** [comment]
Can you post an example?

**Comment by Overtorment** [comment]
i think its fixed now. i was refactoring address scanned some time ago
