### ISSUE TITLE
Is it my address?

### ISSUE THREAD

**Issue by marcosrdz** [BlueWallet/BlueWallet#829]
Create simple tool that allows me to paste an onchain address to verify if it belongs to one of my wallets.

**Comment by Overtorment** [comment]
I wanted to create same issue but luckily I used search on github and this ticket already exits kek

**Comment by Overtorment** [comment]
should be EZ to build. 
there should be an option on wallets/details page to check "is this my address?"
there should be text input and QR scanner.

every wallet object has `weOwnAddress()` method

**Comment by ncoelho** [comment]
Could it be a global tool instead?

Input address > magic happens > select wallet screen > wallet

**Comment by limpbrains** [comment]
I agree with @ncoelho it should be global. And after you found the address you can sign a message with it #393
