### ISSUE TITLE
wallet cards shadow values

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#83]
<img width="208" alt="screen shot 2018-09-29 at 20 35 12" src="https://user-images.githubusercontent.com/1238429/46249317-4bd7c280-c427-11e8-8fc3-4013842afa3f.png">
<img width="209" alt="screen shot 2018-09-29 at 20 35 02" src="https://user-images.githubusercontent.com/1238429/46249318-4bd7c280-c427-11e8-9e52-a53211f662a2.png">

y:4
x:0
blur:10

rgba (0,0,0,18)

**Comment by marcosrdz** [comment]
Fixed in f0ec8f544b61265ebcfcb496934a9fe5448b2fc1
