### ISSUE TITLE
Error displaying wallet balance

### ISSUE THREAD

**Issue by dimaatmelodromru** [BlueWallet/BlueWallet#830]
![CB24E038-8E90-47E0-9469-E10DBA83BA70](https://user-images.githubusercontent.com/4951450/73637838-39544580-467a-11ea-8985-ba80f46bdcd0.png)
![CFD61292-08A3-4AC7-BCA8-5932C222AF9A](https://user-images.githubusercontent.com/4951450/73637839-39ecdc00-467a-11ea-94f2-c85be98dc88e.png)

**Comment by Overtorment** [comment]
Can you privately share your xpub to i@bluewallet.io ?
Breadwallet wallet format is quite old and not used much nowadays.

**Comment by ncoelho** [comment]
closing this one, follow up here https://github.com/BlueWallet/BlueWallet/issues/977
