### ISSUE TITLE
last character missing on amount

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#837]
Reported on twitter
https://twitter.com/FanisMichalakis/status/1228208847686234114

Device/OS: OnePlus 5T, OxygenOS 9.0.10

![EQt5bp_UwAANPqf](https://user-images.githubusercontent.com/1238429/74523296-20bb1980-4f1d-11ea-90d2-8a901342743e.jpeg)

**Comment by limpbrains** [comment]
Fixed in #3479
