### ISSUE TITLE
Failure to capture address of a QR code

### ISSUE THREAD

**Issue by dav1dpgit** [BlueWallet/BlueWallet#838]
Using BlueWallet in an iPhone XSMax, trying to send BTC to an Android Samourai Wallet.
Both BlueWallet and Samourai Wallet are Bech32.

Everything opens and loads fine on both wallets.  I select receive on Samourai and a QR code is generated (I do not add additional information into the QR code). On BlueWallet I select send, then scan. Pointing the camera on the iPhone to the QR code on the Android, BlueWallet switches from the camera mode back to the send page, but no address is loaded.  Retry multiple times without success.

Testing:  Open another wallet (RedWallet) on the iPhone, select send and point the iPhone camera at the same QR code on the Android and the address loads fine.

Testing2:  Select send on BlueWallet and point to a PC-based wallet QR code that is not Bech32; the address loads into BlueWallet without issues.

BlueWallet is version 4.9.4

**Comment by pajasevi** [comment]
Samourai uses all uppercase letters in their QR codes (which is valid bech32 address format). BLW apparently does not expect this.
