### ISSUE TITLE
Migrate from UIWebView

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#844]
Dear Developer,

We identified one or more issues with a recent delivery for your app, "BlueWallet - Bitcoin wallet" 5.0.0 (1582826524). Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs starting from December 2020 . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

After you’ve corrected the issues, you can upload a new binary to App Store Connect.

Best regards,

The App Store Team

**Comment by marcosrdz** [comment]
We use webkit. However; the RN package includes code for both. Thats why that email was triggered.

**Comment by Overtorment** [comment]
yeah, we need to update that dep and test it carefully (lapp browser mostly)
