### ISSUE TITLE
Multi-signature wallets 

### ISSUE THREAD

**Issue by Derad6709** [BlueWallet/BlueWallet#851]
### Hi. I think you should implement [multisig addresses](https://en.bitcoin.it/wiki/Multisignature)  in BlueWallet🙂
You can ask me why. For real. 
There’s a lot of reasons.
- It is too safe. You need to sign transaction several times.
- It is very useful. You can store your keys in different places. For example, you can store one key at your home, second key will keep your lawyer, and third will stored at bank vault. 
- You can lose one key and still able have access to your wallet.
- You can create transactions with middleman. Firs key will be yours, second key will keep your counter-party and the third will keep middleman. For broadcasting transactions must be signed twice. 
### But I thinks you can implement this better than [another projects](https://coinb.in/multisig/) or [this](https://carbonwallet.com/)(I can’t trust them, this is the website and not fully transparent😥). Same as your wallet 👍😁
 I think it should contain some features, like 
- Generation at the another side (I can invite my middle man by the link, and he will generate the wallet, but I don’t know his seed)
- Signing without storing keys. My wallet balance should be shown according public keys and after creating transaction i should paste privkey or scan QR from my paper. Just imagine, you can scan your keys from paper, or another ways to receive private key, maybe NFC tag, just scan it and send your money.😁
- But if you want you can store both keys on your phone.
- More than 4 keys and any threshold.
- Receiving private key by other ways, such hardware wallets or store it on the device or remote server and decrypting by OTP code or second password.

**Comment by Overtorment** [comment]
Multisig is on our roadmap, but specific feature requests you provided look really interesting, thanks!

**Comment by Overtorment** [comment]
ok, multisig is implemented and basically shipped (shadow release, hidden behind a backdoor for beta testing)
