### ISSUE TITLE
Incorrect balance in hd legacy breadwallet wallet

### ISSUE THREAD

**Issue by dimaatmelodromru** [BlueWallet/BlueWallet#854]
![D1BA9FE2-7A92-4F83-99B5-5117570C37E1](https://user-images.githubusercontent.com/4951450/75743495-41a7ab00-5d22-11ea-8263-5c41810918f8.jpeg)

**Comment by Overtorment** [comment]
On my TODO list :-)

**Comment by ncoelho** [comment]
@Overtorment was this fixed on the latest release?

**Comment by Overtorment** [comment]
hard to say, I did some refactoring that was supposed to. lets assume yes
