### ISSUE TITLE
Inaccurate connectivity status when using personal Electrum Server (ElectrumX)

### ISSUE THREAD

**Issue by maxtannahill** [BlueWallet/BlueWallet#856]
Tested with BlueWallet version 5.0.0 iPhone X running iOS 13.3.1 on internal network connection.

Steps to reproduce:

1) Connect BlueWallet to Electrum server
2) Valid connection achieved. Close BlueWallet.
3) Shut down Electrum Server, open BlueWallet.
4) BlueWallet will show Electrum as not connected in Electrum Sever section in BlueWallet settings.
5) Exit, go to currency tab, exit currency tab and go back to Electrum Server section. Connection will show as not connected. Exit again, go to currency tab, exit currency tab and go back to Electrum Server section. Connection will now show incorrectly as connected.

**Comment by Overtorment** [comment]
fixed in https://github.com/BlueWallet/BlueWallet/pull/921 & https://github.com/BlueWallet/BlueWallet/pull/913

should be out in 5.2.0+

please reopen if the problem persists
