### ISSUE TITLE
Connecting to an Electrum backend through SSH

### ISSUE THREAD

**Issue by vedran6** [BlueWallet/BlueWallet#876]
Currently, an Electrum backend needs to be exposed to the Internet in order for Bluewallet integration to work. That sort of setup isn't very secure and some people prefer to tunnel into the server hosting their Electrum backend via SSH for added security.

Would it be possible to add SSH connectivity where BlueWallet would create a local port forwarding from localhost:50002 on the phone to localhost:50002 on the remote server via SSH, and then simply tunnel through?

The equivalent SSH command is `ssh username@host -L 50002:localhost:50002`.

**Comment by Overtorment** [comment]
ssh in a mobile app is a bit of an overkill.
what's the problem with electrum backend?  theoretically, if its in the same network, it should connect o. if not on the same network - VPN is the solution.
