### ISSUE TITLE
Cannot import BIP49 P2SH Wallet

### ISSUE THREAD

**Issue by CryptoIOTA** [BlueWallet/BlueWallet#890]
After installing BlueWallet on a new phone, I'd need to import my BIP49 P2SH wallet seed (previously exported with an older version of BlueWallet), but I see no option for selecting the BIP49 P2SH on the import phase. By default it is importing the seed for a BIP84 Bech32 Native wallet. 
In other words, wallet type selection is only available when creating a new wallet, not when importing the seed.
I'm using BlueWallet ver 5.0.0.

![Import](https://user-images.githubusercontent.com/34274886/76710536-a0006080-6708-11ea-912a-fe81ad3db049.jpeg)

**Comment by Overtorment** [comment]
It shoud detect bip49  during import.
It might fail if there’s no internet, and fallback to bip84. Just try again.
Will test tomorrow just for any case.

**Comment by CryptoIOTA** [comment]
After multiple tests with other seeds and wallet, I suspect my seed was already a BIP84.
I tried with another seed that for sure is BIP49 and bluewallet correctly imported it.
I think we can then close this issue. Even though it would be nice to select the walled standard when importing a seed to avoid this kind of confusion. I'll close the the issue, and thanks for you prompt reply.
