### ISSUE TITLE
elaborate bluewallet: deeplink for sendflow applications (like bitcoin: & lightning:)

### ISSUE THREAD

**Issue by Mvfaassen** [BlueWallet/BlueWallet#892]
Current bluewallet: deeplinking schemes support the Lappbrowser. However, it would be nice if this could be elaborated with the sendflow functionalities of the standard lightning: & bitcoin: schemes, and avoid the IOS errors when there are more than 1 lightning: or bitcoin: scheme. 

proposed:

bluewallet:lightning:{invoice} 
& 
bluewallet:bitcoin:{address}

**Comment by Overtorment** [comment]
makes sense. for reference https://github.com/BlueWallet/BlueWallet/wiki/Deeplinking

**Comment by Mvfaassen** [comment]
Hi @Overtorment . Wanted to see if you (or the team) could add this functionality in the next release.

**Comment by Overtorment** [comment]
hi @Mvfaassen, on-hold for now but planned. unless @marcosrdz wants to implement? but he is busy as well. stay tuned

**Comment by Mvfaassen** [comment]
Okay! Let me know when, we're eager to add you to the invoicing platform https://coinrequest.io. Are waiting for you guys to add lightning :).

**Comment by Mvfaassen** [comment]
Hi, 

Wanted to check if there is any update @Overtorment ? We're ready and would love to start lightning support with you guys.

**Comment by Overtorment** [comment]
will probably work on it this week

**Comment by Overtorment** [comment]
updated https://github.com/BlueWallet/BlueWallet/wiki/Deeplinking
