### ISSUE TITLE
VPN blocked - not able to generate new addresses

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#895]
Reports that some VPNs are not able to generate addresses, meaning requests are being blacklisted.

E.g. ProtonVPN - All free locations

**Comment by limpbrains** [comment]
If you have connection issues, you can use Tor support now.
If you don't have internet connection, you can use Address Explorer to get new receiving addresses. 
I think this issue can be closed

**Comment by Overtorment** [comment]
we also have a timeout, so even if request hangs - after a timeout we should display at least something
