### ISSUE TITLE
Not transferring funds

### ISSUE THREAD

**Issue by cyberkeltic** [BlueWallet/BlueWallet#898]
I transferred bitcoin to the blue wallet no problem but I have been waiting over an hour for it to be transferred to the Lightening wallet and it still appears to be pending. What is going on?!?! I’m new to this stuff. Please help!!!

**Comment by ncoelho** [comment]
It takes 3 confirmations on the onchain to lightning transaction.

https://bluewallet.io/lightning/

Just refresh and wait till it is confirmed. To get support please use the email bluewallet@bluewallet.io

Closing this issue as this is not related with a development bug.
