### ISSUE TITLE
Get rid of Frisbee

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#905]
rewrite on react native fetch and remove dependency

**Comment by Overtorment** [comment]
actually, now I think its best to just update frisbee.
frisbee is isomorphic, works nicely in rn & nodejs cli, and potentially in browser (if we ever need it)

**Comment by limpbrains** [comment]
I want to work on this
Should be pretty straightforward
According to https://github.com/niftylettuce/frisbee/releases frisbee 3 doesn't have any breaking changes
plan:
- upgrade package
- make sure tests works
- test some functionality which depends on it. Hodl Hodl integration, lightning

Correct?
