### ISSUE TITLE
Sweep bech32 paper wallet

### ISSUE THREAD

**Issue by JijoBose** [BlueWallet/BlueWallet#911]
I create a paper wallet (bech32 format) https://segwitaddress.org/bech32/
And it generates a wallet address starting from **bc1**

But after importing this address by scanning the private key, the receiving address is changed from **3Q** instead of **bc1**

Wallet details in the App displays as
- address: ' 3Qi '
- _type:_ **Segwit (P2SH)**

Shouldn't the receiving address format be the same ( starting from 'b1')?

**Comment by ncoelho** [comment]
ACK. Manage to reproduce.

**Comment by Overtorment** [comment]
Ack. Will try to fix it in 5.3.0

**Comment by Overtorment** [comment]
noice. ticket `911`

**Comment by Overtorment** [comment]
done. unfortunately ,single-address bech32 wallets wont be able to send for now, that's to be done.

**Comment by anandks111** [comment]
I was trying to transfer my coins through segwitaddress.org. My address 3KakYMjfxrgPe5DxZAiBeysT2oJs7SAjJH was created using this website. I tried to transfer the coins to 3PX1ZA9YyuCvCQQ97WwVYGQquaPCd54AeT. But the receiving address automatically changed to 3NwY8o1s3xPA2eJ137xtABafaPa6d1QGaQ and my coins are lost. Can anyone help?
