### ISSUE TITLE
Duplicate input detected on p2sh

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#912]
5+ reports of this issue. Users are reporting that they have to delete the wallet and import again for it to work.

![photo_2020-03-26_12-26-20](https://user-images.githubusercontent.com/1238429/77641921-1dc03980-6f5d-11ea-80ec-e483dc7b843d.jpg)

![Image](https://user-images.githubusercontent.com/1238429/77642309-bc4c9a80-6f5d-11ea-9739-20b20883102e.jpg)

![photo_2020-03-26_12-30-58](https://user-images.githubusercontent.com/1238429/77642316-c1114e80-6f5d-11ea-80c6-d4ee1ca8cfa8.jpg)

**Comment by Overtorment** [comment]
fixed, that was a stupid bug. 
but still, someone has to refactor sending in old wallets...

**Comment by Overtorment** [comment]
will be out in 5.3.0+
