### ISSUE TITLE
Error in back button - Marketplace

### ISSUE THREAD

**Issue by JijoBose** [BlueWallet/BlueWallet#922]
<img src="https://user-images.githubusercontent.com/13100108/77822107-b6011e80-7115-11ea-8224-5c439cecc42b.gif" alt="drawing" height="500"/>

Error when closing "Marketplace" using the header "close button" and then using the system back button to go back to main page

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/923/commits/61f658e10d94cda6fa7238566221aee222af456b
