### ISSUE TITLE
Impossible to enter lndhub url at new wallet dialog

### ISSUE THREAD

**Issue by dimaatmelodromru** [BlueWallet/BlueWallet#943]
Impossible to enter lndhub url at new wallet dialog on iPhone SE
Keyboard covers the input field.
Cannot paste.
@
![A4B880F1-ACD0-49F9-A534-A89FB2713004](https://user-images.githubusercontent.com/4951450/78422282-e3465300-7666-11ea-8ec5-c8f3fbbc3e86.png)

**Comment by ncoelho** [comment]
Fixed on https://github.com/BlueWallet/BlueWallet/pull/945
