### ISSUE TITLE
Status bar is broken at new wallet dialog

### ISSUE THREAD

**Issue by dimaatmelodromru** [BlueWallet/BlueWallet#944]
iPhone SE
![3CCB5460-53DF-4F23-9A4A-B6D501AFB0CA](https://user-images.githubusercontent.com/4951450/78422344-42a46300-7667-11ea-9826-5d95707b9333.png)

**Comment by ncoelho** [comment]
what is the OS version?

**Comment by dimaatmelodromru** [comment]
13.3.1

**Comment by ncoelho** [comment]
Closing can't reproduce
