### ISSUE TITLE
UI BUG: Unable to paste invoice, keyboard covers the popup

### ISSUE THREAD

**Issue by thorie7912** [BlueWallet/BlueWallet#947]
Here's a video

https://www.youtube.com/watch?v=Vvdr9CndK0c&feature=youtu.be

As soon as I tap and hold to get the copy/paste menu, the keyboard covers the entire area and I can't select paste.

**Comment by ncoelho** [comment]
Thanks for reporting. Fixed here https://github.com/BlueWallet/BlueWallet/pull/949
