### ISSUE TITLE
Home view navigation

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#95]
Depends on https://github.com/BlueWallet/BlueWallet/issues/41

Main view should:
1 - Display all wallets in the carrousel
2 - Display all transactions from all wallets

Expected main interaction:
![bluewallet 2](https://user-images.githubusercontent.com/1238429/46574670-2f97d080-c9a7-11e8-950c-5457821724d7.gif)

**Comment by Overtorment** [comment]
in progress in https://github.com/BlueWallet/BlueWallet/pull/96
