### ISSUE TITLE
Bluewallet won't accept .onion URI

### ISSUE THREAD

**Issue by otaviobps** [BlueWallet/BlueWallet#953]
I'm running LndHub on my server. This server is behind a NAT, however Tor is configured and `bitcoind`, `lnd` and `LndHub` are running over Tor.

On a second server I have an OpenVPN server running, routing all traffic thru Tor. This is the scheme:

`Mobile Phone -> VPN Server -> Tor -> LndHub (running over Tor)`

I created this configuration because Orbot is not available for iOS.

On my Android device, I could connect to my VPN and paste my `LndHub` URI (ending in .onion) and it worked fine.

However on iOS, an alert saying "Not a valid LndHub URI" is shown. I believe that it's not even trying to connect, because it fails the URI check first. This device is connected to the Tor network and routing all its traffic thru it, so it would be able to connect to the LndHub over Tor.

Is it possible to bypass this URI check?

**Comment by Overtorment** [comment]
ios/android code is the same, so if URL is valid for android then it is valid for ios.
network layer is different deal, so yeah it is possible that ios cant resolve `.onion` URL, but android can.
bw actually tries to make a HTTP request to validate url.

wild guess: ios needs DNS tuning so `.onion`  URLs can be resolved.

**Comment by otaviobps** [comment]
Yes I can confirm this. I also tested with my Macbook other onion sites, routing the DNS query thru my VPN server connected to Tor, and found out that for some reason Apple doesn't allow the OSX and iOS to resolve `.onion` addresses, unless using SOCKS5. I'm gonna close this issue, since it does not belong to Bluewallet
