### ISSUE TITLE
Bluewallet fails to import Electrum wallet (Legacy Addresses) from wallet's seed and key

### ISSUE THREAD

**Issue by AMDBartek** [BlueWallet/BlueWallet#954]
I recently got Bluewallet and it fails to import my Electrum wallet from the wallet's seed or key. This would be an extremely useful feature to have as most of my wallets are on Electrum.

The wallet type is BIP32 with multiple addresses (legacy addresses).

I have not tried importing a SegWit address yet, but I do not use SegWit addresses. I prefer to use legacy addresses as they are more compatible.

I am not sure if this is a bug or a compatibility issue but it would be good to have working compatibility with Electrum wallets.

**Comment by Overtorment** [comment]
Hi, can I ask you a favor? Can you create a wallet in electrum, fund it, remove all funds so it's empty and send me mnemonics privately at i@bluewallet.io ? That would same me a lot of time to add support for Electrum format 🙏🏻

**Comment by AMDBartek** [comment]
@Overtorment I have sent an email with a newly created Electrum wallet seed. I would be very grateful if BlueWallet was Electrum-compatible.
