### ISSUE TITLE
iOS widget not working

### ISSUE THREAD

**Issue by oparex** [BlueWallet/BlueWallet#962]
**Describe the problem/bug**
iOS widget does not display any price. It does not update even after one day.

**Your environment**
* bluewallet version v5.2.0
* iPhone 7
* iOS version 13.3.1

**To Reproduce**
1. Have bluewallet installed on your iphone
2. Go to widget screen, click edit and add bluewallet to widgets
3. Go back to widget screen

**Expected behavior**
Bluewallet widget with bitcoin price and last updated fields populated with values

**Actual behavior**
Bluewallet widget with bitcoin price and last updated fields populated with ...

**Screenshots/Links**
![bluewalletwidget](https://user-images.githubusercontent.com/3031967/78756280-d1242780-797a-11ea-8a64-6b29fa13b4c9.jpg)

**Additional context**
The widget does not update even if I change the currency in settings.

**Comment by ncoelho** [comment]
Thanks for reporting. Anyway you can build the app and run it on your phone to debug this?

It works on the iPhone 7 simulator, and it seems that on the iPhone 7 physical device is not working.

**Comment by oparex** [comment]
Tried to build with node v10.1.0 and npm and got a bunch of errors. Tried to upgrade, got some more errors... will need some time to sort node, have not been working with it for some time. Will let you know. Is there another way for me to get a build for iOS that would enable me to check some debug messages?

**Comment by ncoelho** [comment]
install nvm (node manager)

```
$ nvm install 8
$ nvm use 8
```

then run npm
`npm i  && npm start`

if you are getting problems on the installation
`rm -fr node_modules && rm -fr ios/Pods && npm i && cd ios && pod update && cd ..`

then run react 
`react-native run-ios`

to install on a physical device run it through xcode
`from the bluewallet/ios/BlueWallet.xcworkspace`

**Comment by oparex** [comment]
still not working. I get error at npmi && npm start

```
error: patch failed: node_modules/metro-minify-uglify/src/minifier.js:67
error: node_modules/metro-minify-uglify/src/minifier.js: patch does not apply
error: patch failed: node_modules/uglify-es/lib/minify.js:51
error: node_modules/uglify-es/lib/minify.js: patch does not apply
```

**Comment by marcosrdz** [comment]
https://github.com/BlueWallet/BlueWallet/pull/975/commits/2dc792f9c179e9d1936a9b0a267d95d486b380f8
