### ISSUE TITLE
Incorrect confirmations when using EPS

### ISSUE THREAD

**Issue by clonmac** [BlueWallet/BlueWallet#965]
I have my Bluewallet set up to use my Electrum Personal Server, but any new transaction I receive shows negative confirmations. Upon a transaction's first confirmation, it will show that it has -63 transactions and as new blocks come in it will count up from there -62, -61, -60... I've tried numerous wallets that are configured in my Electrum Personal Server and tested transactions with all of them and they all have the same issue. Connecting the actual Electrum client to the same EPS instance works fine.

All other functionality with BlueWallet and EPS appears to be fine (broadcasting transactions, transaction history, etc).

**Comment by Overtorment** [comment]
Ack. Tip of blockchain estimator (which is based on device time) is off.
Will fix
