### ISSUE TITLE
Refactor classes

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#972]
Wallets go to a separate folder.
Camelcase filenames change to snake case

**Comment by mgurzenski** [comment]
I can work on this.

**Comment by mgurzenski** [comment]
For "wallets go to a separate folder" - are you thinking the "wallets" folder would be a child or a sibling to the "class" folder?

For "camelcase filenames change to snake case":

1. Do you want just the files in the folder named "class" renamed or all files in the project (i.e. files within the models, screens, tests folders also)?
2. Should kebab-case filenames also be changed to snake_case (i.e. legacy-wallet.js -> legacy_wallet.js)?

**Comment by Overtorment** [comment]
Oh I actually meant kebab-case. Most of them already are.
And “wallets/“ should be inside “classes/“.
🙏 thanks!

**Comment by Overtorment** [comment]
https://github.com/BlueWallet/BlueWallet/pull/1142
