### ISSUE TITLE
BW SIGNER: One BW (watch-only) creates tx, other BW (with priv keys, but always offline) signs it

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#976]
Do all through PSBT, inspired by https://github.com/paritytech/parity-signer
This is _not_ a separate app

Similar to coldcard integration

**Comment by Overtorment** [comment]
@marcosrdz you might wana do this feature since you did awesome coldcard integration?

**Comment by bitcoinheiro** [comment]
Very nice. I believe this is already available on iOS but still lacking on Android. I see import tx option on iOS but not on Android apk
