### ISSUE TITLE
Legacy BRD Freezes, Incorrect balance, Error

### ISSUE THREAD

**Issue by dimaatmelodromru** [BlueWallet/BlueWallet#977]
![EE6761C2-2637-4CC7-A08C-33724B0F3E8F](https://user-images.githubusercontent.com/4951450/79081015-3b91ea80-7d22-11ea-827d-e07f5d3f25c5.png)

**Comment by Overtorment** [comment]
Another attempt to fix was made here, https://github.com/BlueWallet/BlueWallet/pull/1004
along with adding SEND, let's see if it helps

**Comment by Overtorment** [comment]
will be out in next release

**Comment by dimaatmelodromru** [comment]
Now send is present
But the balance is _**WAY**_ wrong

**Comment by limpbrains** [comment]
BRD incorrect balance was fixed here #2131
If you re-import the wallet, it should be ok
