### ISSUE TITLE
multiple crashes when connecting to Electrum Server

### ISSUE THREAD

**Issue by maltokyo** [BlueWallet/BlueWallet#988]
Version 5.3.0

It eventually connected fine. But first few tries, the app crashed after pressing save and "back" button. 

Attached the crash log android showed me. It wouldn't let me copy the text, and it was proposing to send to Xiaomi, rather than here ;(

![image](https://user-images.githubusercontent.com/1388507/79284603-7418fc00-7ebb-11ea-934f-e0f4c083546f.png)

**Comment by Overtorment** [comment]
confirmed.
crashes happen somnetimes on android when app can't connect to electrum server

**Comment by ncoelho** [comment]
Seems fixed, reopen if not please.

**Comment by maltokyo** [comment]
Hello. This is still not fixed on latest Google play store version. I still get frequently this crash. 

Also someone on the telegram mailing list tried to send me an apk on telegram directly. Is that legit? I'll never install something in that way.

**Comment by ncoelho** [comment]
If someone is sending you things to install on telegram is a scammer. Be
aware

**Comment by maltokyo** [comment]
This person sent it. Looks like they use your handle.

**Comment by maltokyo** [comment]
Could you please reopen this. It's definitely an issue. Is there something more I can provide you, logs etc? I'm thinking to move away from blue wallet. It's unusable if it can't connect to an electrum server. And I cannot get it working. And not help or tips here(?)

**Comment by Overtorment** [comment]
will work on it, this or next week.
reproducible on android (ios is ok)

**Comment by maltokyo** [comment]
Thank you!!

**Comment by maltokyo** [comment]
Still get constant crashes on 5.3.9. @Overtorment is it just me? Really unusable, please let me know how I can provide logs. Anything...

**Comment by Overtorment** [comment]
thank you for your patience! indeed, for most people all is fine, but the problem is clearly in the network library, which I planned to work on this or next week. I will post updates to this thread.

**Comment by Overtorment** [comment]
electrum code was refactored in https://github.com/BlueWallet/BlueWallet/pull/1223 and hopefully it fixes this issue. will be out in next release

**Comment by maltokyo** [comment]
Thank you. I installed latest release from apk. Is it included? I ask because the crashes continue for me.

**Comment by Overtorment** [comment]
No, latest APK is not published yet, I think its gonna be up on monday

**Comment by Overtorment** [comment]
`v5.4.3` and higher

**Comment by maltokyo** [comment]
Got it. Thank you. Will wait for that.

**Comment by Overtorment** [comment]
released. let me know if the issue is not fixed
