### ISSUE TITLE
Warning when creating wallet

### ISSUE THREAD

**Issue by ncoelho** [BlueWallet/BlueWallet#99]
![img_0328](https://user-images.githubusercontent.com/1238429/46583634-40ede500-ca5a-11e8-8491-5400f5894817.PNG)

> ERROR
> 17:53
> Warning: Can't call setState (or forceUpdate) on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
> 
> Stack trace:
>   node_modules/fbjs/lib/warning.js:33:20 in printWarning
>   node_modules/fbjs/lib/warning.js:57:25 in warning
>   node_modules/react-native/Libraries/Renderer/ReactNativeRenderer-dev.js:12196:6 in warnAboutUpdateOnUnmounted
>   node_modules/react-native/Libraries/Renderer/ReactNativeRenderer-dev.js:13273:41 in scheduleWorkImpl
>   node_modules/react-native/Libraries/Renderer/ReactNativeRenderer-dev.js:6224:19 in enqueueSetState
>   node_modules/react/cjs/react.development.js:413:31 in setState
>   screen/wallets/transactions.js:122:20 in <unknown>
>   node_modules/react-native/Libraries/Core/Timers/JSTimers.js:152:6 in _callTimer
>   node_modules/react-native/Libraries/Core/Timers/JSTimers.js:405:17 in callTimers
>   ...

**Comment by Overtorment** [comment]
This is valid, but very old. Reproduceable only when runing under Expo. Basically it says it does nothing ("no-op"), so it can be safely ignored until there is really nothing else to do
