### ISSUE TITLE
Hierarchy navigator screen

### ISSUE THREAD

**Issue by Overtorment** [BlueWallet/BlueWallet#990]
Need something like this:

![image](https://user-images.githubusercontent.com/1913337/79360291-9ce0d600-7f3b-11ea-9808-5a0e520ce14b.png)

A list of receive/change addresses with balances and transactions num.
There should be an option for each address to see (and copy) public key, priv key, sign/verify message, encrypt/decrypt message.
also, maybe button to request payment with a specific amount to this exact address, and option to assign text label to an address.

**Comment by jaonoctus** [comment]
Any progress on this feature yet? Should I send some PR?

**Comment by Overtorment** [comment]
no progress yet. I was itchy to build it myself but eventually got busy with other stuff.
PR would be nice! @ncoelho do we have designs for such screen..?

**Comment by jaonoctus** [comment]
@ncoelho @Overtorment Maybe we should use a similar approach to that of Coin Control screen?

**Comment by ncoelho** [comment]
I played with this concept. Could get some feedback before, not super polished and may be missing some things.

<img width="757" alt="Screenshot 2021-01-30 at 18 07 43" src="https://user-images.githubusercontent.com/1238429/106363013-34c27b80-6326-11eb-9543-7b1e8360936f.png">

**Comment by Overtorment** [comment]
needs to display indexes for both internal (change) & external (receive) addresses.
needs to display number of transactions on each address - address might be empty (0 btc), but still have some transactions which means it is "used"
needs to display which index is the "tip" - next free address for internal & external hierarchy, and an option to show + 20 (or more..?) addresses in case user wants to manually give away his addresses to his payers

**Comment by ncoelho** [comment]
Ok, I will adapt the proposed design to be able to handle more data upfront. Will update the issue later.

**Comment by ncoelho** [comment]
Ok, this seems more solid to me. Any more feedback, let me know. 

<img width="779" alt="Screenshot 2021-02-01 at 16 54 05" src="https://user-images.githubusercontent.com/1238429/106482852-328b2900-64ae-11eb-8bb6-534980a825fb.png">

**Comment by Overtorment** [comment]
maybe gray-out whole row for used addresses..?
![image](https://user-images.githubusercontent.com/1913337/106489086-4d5c9e00-64ac-11eb-9568-a00803f4f3b4.png)

**Comment by jaonoctus** [comment]
Where can I add the action for this screen? Is "wallet details" (`screen/wallets/details.js`) a good place?

![image](https://user-images.githubusercontent.com/7918067/106858850-04216f80-66a1-11eb-8b5c-6320ed5acba1.png)

**Comment by ncoelho** [comment]
Yes, that would be the place.

**Comment by jaonoctus** [comment]
WIP

https://github.com/jaonoctus/BlueWallet/commits/feature/hierarchy-navigator-screen

**Comment by ncoelho** [comment]
> WIP
> 
> https://github.com/jaonoctus/BlueWallet/commits/feature/hierarchy-navigator-screen

How is this going @jaonoctus do you need any guidance with this? 
We hangout [here](https://t.me/joinchat/VAz1m-2vSguDPLZJ)
